### ISSUE TITLE
[QUESTION]springboot用fastjson2返回数据，LocalDate和LocalTime格式化问题

### ISSUE THREAD

**Issue by wugui0823** [alibaba/fastjson2#1003]
fastjson2版本：2.0.20
springboot配置
![image](https://user-images.githubusercontent.com/16262592/206635521-5b9a7135-40fe-4e70-b6b3-2224a8c23af4.png)

属性注解
![image](https://user-images.githubusercontent.com/16262592/206636565-41d6658f-5a96-4262-b972-977ffe02741e.png)

返回结果
![image](https://user-images.githubusercontent.com/16262592/206636079-dbdb8f25-a119-4ade-9aff-f38e8e309ed5.png)

之前看到issues有提高LocalDate、LocalTime会有默认的格式yyyy-MM-dd和HH:mm:ss，但是我试了下没有效果，不知道是不是我配置问题.
不知道fastjson2是否支持spring自带的fasterxml jackson注解

**Comment by wenshao** [comment]
已经支持通过Jackson Annotation JsonFormat，fastjson2也支持JSONField(format="xxx")的方式配置日期格式

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.21
问题已修复，请用新版本

**Comment by wugui0823** [comment]
升级后可以了，谢谢
