### ISSUE TITLE
[BUG]设置Filter之后只要值为null时Feature即使设置输出NULL都不会输出该KEY

### ISSUE THREAD

**Issue by AlienXLiu** [alibaba/fastjson2#1004]
### 问题描述
String toJSONString(Object object, String format, Filter[] filters, JSONWriter.Feature... features)
设置Filter之后只要值为null时Feature即使设置输出NULL都不会输出该KEY

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
private static final SimplePropertyPreFilter SIMPLE_1 = new SimplePropertyPreFilter();
	static {
		Set<String> excludes1 = SIMPLE_1.getExcludes();
		excludes1.add("AA");
	}

Map jsonObject = new HashMap();
jsonObject.put("birthDay", new Date());
jsonObject.put("id", 1);
jsonObject.put("seq", null);

String s3 = com.alibaba.fastjson2.JSON.toJSONString(
               jsonObject,
	      "yyyy-MM-dd HH:mm",
		new Filter[]{SIMPLE_1},
		JSONWriter.Feature.WriteMapNullValue
);

System.out.println(s3);

```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
期望输出 seq 字段信息即：
{"birthDay":"2022-12-09 15:34:05","id":1,"seq":null}

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
现在输出却是：{"birthDay":"2022-12-09 15:34","id":1}
没有seq 

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
Bug 位置：com.alibaba.fastjson2.writer.ObjectWriterImplMap#writeWithFilter
![fec45e37bb9ea245e1518ac6f838660](https://user-images.githubusercontent.com/8159035/206649580-5155a425-6991-4f57-ab61-2d1088b4ff79.jpg)

**Comment by wenshao** [comment]
都找到问题了，你提交PR参与进来吧

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
