### ISSUE TITLE
[QUESTION] 如何使用fastjson序列化和反序列化接口interface对象

### ISSUE THREAD

**Issue by RemHero** [alibaba/fastjson2#1008]
### 如何使用fastjson序列化和反序列化接口interface对象
需要反序列化的类是A，A中包含一个接口对象B
B有两个实现B1和B2
请问，我如何使用fastjson对A进行反序列化？
以往使用的是gson，gson的一种方法是通过register()
```java
builder.registerTypeAdapter(type, new TimeSeriesIntervalAdapter());
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/wiki/JSONType_SeeAlso_cn
看下这个是不是你想要的

**Comment by RemHero** [comment]
谢谢，问题已解决！
