### ISSUE TITLE
[BUG]当字符串存在大量需要转义字符时出现数组越界异常

### ISSUE THREAD

**Issue by wangping2012** [alibaba/fastjson2#1025]
### 问题描述
当字符串存在大量需要转义字符时出现数组越界异常

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.13]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 8000长度字符串
2. 设置其中2000为不可显字符
3. 序列化出现错误
```java
    StringBuilder sb = new StrinqBuilder();
    for(int i =0;i<8000;i++) {
        sb .append("A");
    }
    byte[] temp = sb.tostring ().getBytes ("UTF-8") ;
    for(int i =0;i<2000;i++) {
        temp[i] =0x01;
    }
    try{
        System.out.printIn(JSON.toJSONString(new String(temp,"UTE-8"))) ;
    catch(Exception e) {
        e.printStackTrace();
    }
```

### 期待的正确结果
正确序列化

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/
问题已修复，请帮忙用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦期间发布

**Comment by wangping2012** [comment]
验证了，没问题

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
