### ISSUE TITLE
[BUG] not support type : LOCAL_DATETIME

### ISSUE THREAD

**Issue by dyj2012** [alibaba/fastjson2#1026]
### 问题描述
*简要描述您碰到的问题。*
使用WriteClassName, map中存在LocalDateTime和LocalDate反序列化失败

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java

        Map<String, Object> map = new HashMap<>(20);
        map.put("1", LocalDateTime.now());
        map.put("2", LocalDate.now());
        map.put("3", new Date());
        byte[] bytes = JSONB.toBytes(map, JSONWriter.Feature.WriteClassName);
        Object aa = JSONB.parseObject(bytes, Object.class,
                JSONReader.Feature.SupportAutoType, JSONReader.Feature.SupportClassForName);
        System.out.println(aa);
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
com.alibaba.fastjson2.JSONException: not support type : LOCAL_DATETIME -88, offset 8/39
![image](https://user-images.githubusercontent.com/37611109/208598358-f4d91c60-bec9-440b-a6c6-81eaed7cedaf.png)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/
问题已修复，请帮忙用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
