### ISSUE TITLE
[QUESTION] 在fastjson2中 如何实现 fastjson1中的 decimalFormat

### ISSUE THREAD

**Issue by lyhu** [alibaba/fastjson2#1029]
### 请问：在fastjson2中 如何实现 fastjson1 中的 decimalFormat 需求。

```java
    @JSONField(decimalFormat = "0.00")
    private List<Double> nums;
```

谢谢!

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/
已经支持，用帮忙用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦前发布

用法如下：
```java
JSONField(format = "0.00")
 private List<Double> nums;
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本

**Comment by lyhu** [comment]
3ks.
