### ISSUE TITLE
fastjson2是否不在计划支持InputStream的反序列化？如JSON.parseObject(is, Map.class)

### ISSUE THREAD

**Issue by kervin521** [alibaba/fastjson2#103]
String path = "json.txt";
InputStream is = new FileInputStream(new File(path));
Map<String,Object> map = JSON.parseObject(is, Map.class);

**Comment by wenshao** [comment]
已经支持，快照版本 https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.2-SNAPSHOT/
正式版本明天发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本

**Comment by hwtl** [comment]
兼容版这个还没有纳入进来，2.0.6 和2.0.7

**Comment by hwtl** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.2 问题已修复，请使用新版本
这个版本还没有引入，2.0.6和2.0.7 @wenshao

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
