### ISSUE TITLE
[BUG] JSON.toJSONString(object, filter, ...features)存在filter时features不生效

### ISSUE THREAD

**Issue by WeaponZhao** [alibaba/fastjson2#1030]
### 问题描述
使用JSON.toJSONString(object, filter, ...features)将一个hashMap中某些字段过滤掉，并对剩下的字段排序输出成字符串。通过跟踪源码发现执行过过滤方法后，直接生成了字符串并返回，并没有执行字段排序的代码，在1.X的版本中是没有这个问题的。

### 环境信息
 - OS信息： MacOS 12.6.2 4Core 2.3GHz 8GB
 - JDK信息： Oracle JDK 1.8.0_351
 - 版本信息： Fastjson2 2.0.17-2.0.21
 
### 重现步骤

1. 使用 `com.alibaba.fastjson.JSON.toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)` 方法
```java
    Map<String, String> newParams = new HashMap<>();
    newParams.put("pageSize", "10");
    newParams.put("q", "");
    newParams.put("pageIndex", "0");
    SimplePropertyPreFilter filter = new SimplePropertyPreFilter();
    filter.getExcludes().add("_t");
    String params = JSON.toJSONString(newParams, filter, SerializerFeature.MapSortField);
    //params = {"q":"","pageIndex":"0","pageSize":"10"}
```

### 期待的正确结果
{"pageIndex":"0","pageSize":"10","q":""}

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
问题已经修复，请用新版本
