### ISSUE TITLE
[BUG] Swagger2 /v2/api-docs 返回多嵌套了一层

### ISSUE THREAD

**Issue by MX8CLUB** [alibaba/fastjson2#1033]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 spring boot 2.7.7
jdk8
fastjson2 2.0.21
swagger2

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
{
	"value":"{\"swagger\":\"2.0\",\"info\":.........
}

与https://github.com/alibaba/fastjson2/issues/954问题相同，Fastjson 2.0.21也还是存在

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by MX8CLUB** [comment]
JSONWriter.Feature.FieldBased

**Comment by MX8CLUB** [comment]
发现是因为`JSONWriter.Feature.FieldBased`这行配置导致的，去除后正常

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/
问题已经修复，请用2.0.22-SNAPSHOT版本验证，2.0.22版本在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
