### ISSUE TITLE
[QUESTION]JSONObject.to()出现空指针异常

### ISSUE THREAD

**Issue by 18681466471** [alibaba/fastjson2#1034]
public static void main(String[] args) {
        String json = "{\"PARAMETER\":{\"SSRC\":[null,15,null,null,null,null,null,null,null,null,null,null,null],\"RUN\":124}}";
        Param<?> param = JSON.parseObject(json, Param.class);
        JSONObject jsonBody = (JSONObject) param.getParameter();
        TypeReference<Test> typeReference = new TypeReference<Test>() {
        };
        Object to = jsonBody.to(typeReference.getType());
        System.out.println(to);
    }
    @Getter
    @Setter
    static class Test {
        @JSONField(name = "RUN")
        private Integer run;
        @JSONField(name = "SSRC")
        private List<Integer> ssrc;
    }

    @Getter
    @Setter
    static class Param<T> {
        @JSONField(name = "PARAMETER")
        private T parameter;
    }

fastjson2: 2.0.12
result is :
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.createInstance(ObjectReaderImplList.java:176)
	at com.alibaba.fastjson2.JSONArray.to(JSONArray.java:939)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:109)
	at com.alibaba.fastjson2.JSONObject.to(JSONObject.java:1141)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.22-SNAPSHOT/
问题已经修复，请用2.0.22-SNAPSHOT版本验证，2.0.22版本在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
