### ISSUE TITLE
请教有关Feature.PrettyFormat的问题

### ISSUE THREAD

**Issue by MASON-PRINCE** [alibaba/fastjson2#104]
使用JSONWriter.Feature.PrettyFormat时输出的格式存在问题
![image](https://user-images.githubusercontent.com/101661502/165770001-35712525-3bc0-46cd-957d-f6c62cfe8094.png)
为什么和之前使用SerializerFeature.PrettyFormat的格式不太一样
![image](https://user-images.githubusercontent.com/101661502/165774645-654eae61-b815-4d3f-a114-46cfd394a946.png)

**Comment by wenshao** [comment]
这个是BUG，请提供文本数据，帮助我修复后做比对。

**Comment by T-Atlas** [comment]
1.2.80版本
{
	"passengerId":"220802200005217748",
	"firstName":"Hong",
	"lastName":"Test",
	"age":99,
	"telephone":"13104362222"
}

2.0.1版本
{
	"passengerId":"220802200005217748","firstName":"Hong","lastName":"Test","age":99,"telephone":"13104362222"
}

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
