### ISSUE TITLE
JSON.to导致内存溢出

### ISSUE THREAD

**Issue by 4104389** [alibaba/fastjson2#1047]
调用JSON.to的时候回导致内存溢出
`public static void main(String[] args) {
        Integer[] to = JSON.to(Integer[].class, "[1");
        System.out.println(Arrays.toString(to));
    }`

![image](https://user-images.githubusercontent.com/74517757/210298710-84e6ff15-996c-491d-92f5-f9cafa9863ed.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/
问题已经修复，请帮忙用2.0.23-SNAPSHOT版本验证，2.0.23版本预计在2月15日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
问题已经修复，请用新版本
