### ISSUE TITLE
[BUG] 2.0.22版本使用parseObject时出现空指针异常

### ISSUE THREAD

**Issue by cuixin3266** [alibaba/fastjson2#1054]
### 问题描述
*简要描述您碰到的问题。*
2.0.22版本使用JSONObject.parseObject()格式化对象时出现空指针异常，2.0.16使用正常解析
```
SensorSoilTemperature@3ecd23d9[value=24.4801]
```

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Win10 21H2 19044.2364 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz  10Core  24 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_281]
 - 版本信息：[e.g.：Fastjson2 2.0.22]
 

### 重现步骤
*如何操作可以重现该问题：*
1. 切换使用2.0.22版本
2. 运行以下代码
```java
public static void main(String[] args) {
    System.out.println(JSONObject.parseObject("{\"value\":24.4801}", SensorSoilTemperature.class));
}

Model:
@JSONType(
        serializeFeatures = { JSONWriter.Feature.FieldBased },
        deserializeFeatures = {JSONReader.Feature.UseDefaultConstructorAsPossible, JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean},
        ignores = {"dataTime", "id", "sensorId"}
)
public class SensorSoilTemperature extends SensorModel {
        @JSONField(name = "value")
        private BigDecimal value;
// getter、setter...
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
```java
Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.genReadFieldValue(ObjectReaderCreatorASM.java:1941)
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.genMethodReadJSONBObject(ObjectReaderCreatorASM.java:985)
	at com.alibaba.fastjson2.reader.ObjectReaderCreatorASM.createObjectReader(ObjectReaderCreatorASM.java:576)
	at com.alibaba.fastjson2.reader.ObjectReaderProvider.getObjectReader(ObjectReaderProvider.java:950)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:600)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1906)
	at com.xxx.data.analysis.service.calculation.AbstractDataCalculationService.main(AbstractDataCalculationService.java:135)

```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by cuixin3266** [comment]
> ```java
> public class Issue1054 {
>     @Test
>     public void test() {
>         SensorSoilTemperature temperature = JSONObject.parseObject("{\"value\":24.4801}", SensorSoilTemperature.class);
>         assertNotNull(temperature);
>         assertEquals(new BigDecimal("24.4801"), temperature.value);
>     }
> 
>     public class SensorSoilTemperature
>             extends SensorModel {
>         @JSONField(name = "value")
>         private BigDecimal value;
> 
>         public BigDecimal getValue() {
>             return value;
>         }
> 
>         public void setValue(BigDecimal value) {
>             this.value = value;
>         }
>     }
> 
>     public static class SensorModel {
>     }
> }
> ```
> 
> 问题未重现

我这边再测试了一下，发现当移除 **@JSONType** 中的 **deserializeFeatures** 字段 **JSONReader.Feature.FieldBased** 属性时正常，这个在2.0.16中是正常使用的

**Comment by fy287216637** [comment]
设置 JSON.config(JSONWriter.Feature.ReferenceDetection); 也会导致空指针,请尽快排查下原因呢~

模拟JSON：
{
    "success": false,
    "requestId": "requestId",
    "error": [
        {
            "code": "111",
            "message": "message",
            "longMessage": "--",
            "source": "666"
        }
    ],
    "data": {
        "requestString": "{\"scope\":\"1\",\"action\":\"1\",\"OrderNumber\":\"1\"}"
    }
}

接受对象的字段：
public boolean success;

public String requestId;

public String data;

public String error;

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/
问题已修复，请用2.0.23版本帮忙验证，2.0.23版本预计在1月14日前发布

**Comment by cuixin3266** [comment]
> @wenshao 麻烦问下我的这个也解决了嘛 ![image](https://user-images.githubusercontent.com/29773167/211231831-29a7eafa-853a-4411-a829-641aaf959fb2.png)

我这边测试快照版本已经修复了我上述问题，你这个问题我不是特别懂，你可以下温少上述提供的快照地址中的jar自行测试一下。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
请用新版本
