### ISSUE TITLE
[BUG]2.0.22没有GenericFastJsonRedisSerializer支持吗

### ISSUE THREAD

**Issue by the-tsing** [alibaba/fastjson2#1055]
### 问题描述
*简要描述您碰到的问题。*
升级到fastjson2-extension-spring6 2.0.22后GenericFastJsonRedisSerializer找不到包

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：springboot3.0.1]
 - JDK信息： [e.g.：Openjdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.22]
 

![image](https://user-images.githubusercontent.com/56435687/210811457-e61ea61b-c4f3-4919-967d-50207013cdb7.png)
![image](https://user-images.githubusercontent.com/56435687/210811514-63f935cd-9e69-405e-a444-fa23071df558.png)

**Comment by wenshao** [comment]
先同时依赖这两个吧：
```xml
<dependency>
    <groupId>com.alibaba.fastjson2</groupId>
    <artifactId>fastjson2-extension-spring5</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.fastjson2</groupId>
    <artifactId>fastjson2-extension-spring6</artifactId>
</dependency>
```

这样不好，下个版本会在spring6中补上这个

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
请用新版本
