### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by KongDone** [alibaba/fastjson2#1056]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
1、请求参数带下滑线或者请求参数为大驼峰，实体对象属性是小驼峰写法，目前fastjson2不支持自动转换了吗？测试在fastjson中是支持.的。

**Comment by wenshao** [comment]
```java
JSONReader.Feature.SupportSmartMatch
```
用上面这个Feature，2.0.x不是缺省打开的

**Comment by KongDone** [comment]
> ```java
> JSONReader.Feature.SupportSmartMatch
> ```
> 
> 用上面这个Feature，2.0.x不是缺省打开的

可以，3Q
