### ISSUE TITLE
fastjson2不支持设置返回参数的策略了吗？

### ISSUE THREAD

**Issue by KongDone** [alibaba/fastjson2#1057]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
在fastJSON中可以通过以下方式设置策略，在fastjson2中不知道怎么使用了。
SerializeConfig fieldFilterConfig = SerializeConfig.getGlobalInstance();
fieldFilterConfig.propertyNamingStrategy = PropertyNamingStrategy.PascalCase;

**Comment by wenshao** [comment]
```java
ObjectWriterProvider provider = new ObjectWriterProvider(PropertyNamingStrategy. PascalCase);
```

**Comment by KongDone** [comment]
> 
> ```java
> ObjectWriterProvider provider = new ObjectWriterProvider(PropertyNamingStrategy. PascalCase);
> ```
没理解上述代码的意思，new ObjectWriterProvider的入参应该是ObjectWriterCreator 类型，这和返回参数的配置有什么关系？

**Comment by KongDone** [comment]
> ```java
> ObjectWriterProvider provider = new ObjectWriterProvider(PropertyNamingStrategy. PascalCase);
> ```

奥，得用2.0.22以上的版本，了解了，Thanks♪(･ω･)ﾉ
