### ISSUE TITLE
[BUG]JSON.parseArray("[{[]}]")不报错

### ISSUE THREAD

**Issue by fourangrymen** [alibaba/fastjson2#1058]
### 问题描述
我并不十分确定这是一个bug

### 环境信息
 - 版本信息：[Fastjson2 2.0.22]
 
### 重现步骤
`System.out.println(JSON.parseArray("[{[]}]"));`
输出：
`[{"":[]}]`

`System.out.println(JSON.parseObject("{[]}"));`
报错：
`Exception in thread "main" com.alibaba.fastjson2.JSONException: not allow unquoted fieldName, offset 2, character [, line 1, column 3, fastjson-version 2.0.22 {[]}`

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/
问题已修复，请用2.0.23版本帮忙验证，2.0.23版本预计在1月14日前发布

**Comment by fourangrymen** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/ 问题已修复，请用2.0.23版本帮忙验证，2.0.23版本预计在1月14日前发布

好的，谢谢！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
问题已经修复，请用新版本
