### ISSUE TITLE
[QUESTION] JSONPath中, 如果我不确定类型是否能够处理

### ISSUE THREAD

**Issue by yizems** [alibaba/fastjson2#1059]
### 请描述您的问题
例如
```json
{
  "a":{
     "b":"xxx"
   }
}
```

```json
{
  "a":[
      {
       "b":"xxx"
     }
  ]
}
```

如果我不确定a的类型, 但是我又希望通过`$.a.b` 将b全部删除, 请问可行吗

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.23-SNAPSHOT/
已经支持，请用2.0.23版本帮忙验证，2.0.23版本预计在1月14日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
问题已经修复，请用新版本
