### ISSUE TITLE
JSONArray getObject(int index, Type type)兼容问题

### ISSUE THREAD

**Issue by zhouchengfei** [alibaba/fastjson2#106]
String str = "[{\"name\":\"mask\"}]";
        com.alibaba.fastjson2.JSONArray array = com.alibaba.fastjson2.JSON.parseArray(str);
        Map object = array.getObject(0, Map.class);
        //没值
        System.out.println(JSON.toJSONString(object));//{}

        com.alibaba.fastjson.JSONArray array2 = com.alibaba.fastjson.JSON.parseArray(str);
        Map object2 = array2.getObject(0, Map.class);
        //有值
        System.out.println(JSON.toJSONString(object2));//{"name":"mask"}

**Comment by wenshao** [comment]
已经修复，等5月3日发布2.0.2版本吧

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
