### ISSUE TITLE
2.0.22版本使用parseObject时出现空指针异常[BUG]

### ISSUE THREAD

**Issue by fy287216637** [alibaba/fastjson2#1061]
### 问题描述
2.0.22版本设置 JSON.config(JSONWriter.Feature.ReferenceDetection); 会导致空指针报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：WIN11]
 - JDK信息： [e.g.：Openjdk 11]
 - 版本信息：[e.g.：Fastjson2 2.0.22]
 

### 重现步骤
*如何操作可以重现该问题：*
JSON.config(JSONWriter.Feature.ReferenceDetection); 
// 测试json
```
String json="{
    "success": false,
    "requestId": "requestId",
    "error": [
        {
            "code": "111",
            "message": "message",
            "longMessage": "--",
            "source": "666"
        }
    ],
    "data": {
        "requestString": "{\"scope\":\"1\",\"action\":\"1\",\"OrderNumber\":\"1\"}"
    }
}";
```
// 定义的对象字段
```
public boolean success;

public String requestId;

public String data;

public String error;
```

// 反序列化(空指针报错)
JSON.parseObject(json, 定义的对象字段.class);

![image](https://user-images.githubusercontent.com/29773167/211310289-1aede7ef-1927-413b-8076-5f74904116ef.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.23
问题已经修复，请用新版本
