### ISSUE TITLE
[BUG]依赖rocketmq-spring-boot-starter的fastjson1怎么升级为2或者1.2.80

### ISSUE THREAD

**Issue by JayFeiFei** [alibaba/fastjson2#1066]
### 问题描述
*简要描述您碰到的问题。*
项目同时依赖了fastjson2和rocketmq-spring-boot。
rocketmq-spring-boot依赖的是fastjson1.2.67怎么升级为2？
直接排除依赖也不会使用fastjson2的依赖。
请求大佬解答

**Comment by wenshao** [comment]
排除后加上这个依赖
```xml
<dependency>
	<groupId>com.alibaba</groupId>
	<artifactId>fastjson</artifactId>
	<version>2.0.22</version>
</dependency>
```

**Comment by JayFeiFei** [comment]
感谢

**Comment by GavinHwa** [comment]
这个直接替换暂无法解决该问题的...
经过对源码的阅读直接替换成2.0.22版本后org.apache.rocketmq.remoting.protocol.BitSetSerializerDeserializer 类中使用了 SerializeWriter 的 writeByteArray 方法在2.x版本中已经移除... 程序将会在运行中报错
