### ISSUE TITLE
fastjson-version 2.0.23 集合反序列化异常

### ISSUE THREAD

**Issue by 1455668754** [alibaba/fastjson2#1082]
{"@type":"com.xueyi.system.api.model.LoginUser","permissions":Set["*:*:*"],"roleIds":Set[],"roles":Set["administrator","admin"],"userId":1,"userType":"00"}
用原LoginUser对象则没问题
但当直接用Object类型转换如上字符串时，发生转换错误（Set问题）
illegal input S, offset 62, character S, line 1, column 63, fastjson-version 2.0.23

**Comment by zhangleqi1** [comment]
请教一下，怎么解决的
