### ISSUE TITLE
ContextValueFilter使用问题

### ISSUE THREAD

**Issue by TsukasaHwan** [alibaba/fastjson2#1090]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

实现ContextValueFilter接口的proccess方法时BeanContext获取不到Field，请问是有啥配置项需要配置嘛

**Comment by TsukasaHwan** [comment]
发现需要配置JSONWriter的FieldBased，但是在使用过程中出现了问题，与ObjectMapper似乎有冲突导致ObjectMapper序列化时出现这种格式：value: "{\"swagger\":\"2.0\"}，期望为{"swagger": "2.0"}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.24-SNAPSHOT/
问题已修复，不用加FieldBased，请用2.0.24-SNAPSHOT版本帮忙验证，2.0.24-SNAPSHOT预计在2月中旬发布。

**Comment by TsukasaHwan** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.24-SNAPSHOT/ 问题已修复，不用加FieldBased，请用2.0.24-SNAPSHOT版本帮忙验证，2.0.24-SNAPSHOT预计在2月中旬发布。

已验证，没问题了
