### ISSUE TITLE
[BUG]fastjson(2.0.23)序列化 com.fasterxml.jackson.databind.node.ArrayNode 丢失数据

### ISSUE THREAD

**Issue by xiaomacdut** [alibaba/fastjson2#1091]
### 问题描述
序列化 com.fasterxml.jackson.databind.node.ArrayNode 丢失数据

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson 2.0.23]
 

### 重现步骤

```java
 ArrayNode arrayNode=new ArrayNode(new JsonNodeFactory(true)); 
 arrayNode.add(32342342342l);
```
数据类型是ArrayNode,序列化上面的arrayNode的结果是：
{"@type":"com.fasterxml.jackson.databind.node.ArrayNode","array":true,"bigDecimal":false,"bigInteger":false,"binary":false,"boolean":false,"containerNode":true,"double":false,"empty":false,"float":false,"floatingPointNumber":false,"int":false,"integralNumber":false,"long":false,"missingNode":false,"nodeType":"ARRAY","null":false,"number":false,"object":false,"pojo":false,"short":false,"textual":false,"valueNode":false}
其中32342342342l丢失了。
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.24-SNAPSHOT/
问题已修复，请用2.0.24-SNAPSHOT版本帮忙验证，2.0.24-SNAPSHOT预计在2月中旬发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.24
问题已修复，请用新版本
