### ISSUE TITLE
[BUG] 当重复key的数量大于2时，DuplicateKeyValueAsArray这个feature失效

### ISSUE THREAD

**Issue by yzezzm** [alibaba/fastjson2#1100]
### 问题描述
当json object中同名的key有三个时，使用DuplicateKeyValueAsArray后，实际得到的value只有一个，而不是一个数组

### 环境信息

 - OS信息：  [macos  13.1 16 GB]
 - JDK信息： [Openjdk 18.0.2]
 - 版本信息：[Fastjson2 2.0.21]
 

### 重现步骤
String str = "{\"a\":2,\"b\":1,\"b\":2,\"b\":3}";
JSONObject jsonObject = JSON.parseObject(str, JSONReader.Feature.DuplicateKeyValueAsArray);
String b = jsonObject.get("b").toString();

---
输出结果为： 3

### 期待的正确结果
[1,2,3]

#### 附加信息
com.alibaba.fastjson2.JSONReader#readObject(java.lang.Object, long)

2.0.21 版本 com.alibaba.fastjson2.JSONReader这个类的1556行，value应替换为origin

![image](https://user-images.githubusercontent.com/85478394/217545211-b6f6dcbd-6db9-4c24-b938-766e924f4a09.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.24-SNAPSHOT/
问题已修复，请用2.0.24-SNAPSHOT版本帮忙验证，2.0.24-SNAPSHOT预计在2月中旬发布。

**Comment by yzezzm** [comment]
> 

验证ok
