### ISSUE TITLE
无法注册FastJsonHttpMessageConverter

### ISSUE THREAD

**Issue by Yefeng888999** [alibaba/fastjson2#1101]
### 问题描述
无法注册fastjson2消息转换器，全部爆红

### 环境信息
*请填写以下信息：*

 - OS信息：win10  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息：Openjdk 1.8.0_312[e.g.：Openjdk 1.8.0_312]
 - 版本信息：Fastjson2 2.0.23[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
![image](https://user-images.githubusercontent.com/112799483/217557081-99feea1f-67a1-4b0e-94a2-529f99574f15.png)

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
就是修改springboot默认的json支持为fastjson2

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by Yefeng888999** [comment]
![image](https://user-images.githubusercontent.com/112799483/217569080-13fa4db2-b5c6-4652-be22-0e6d28c25916.png)
弄好了，但运行显示Long类型还是未转换为字符串
![image](https://user-images.githubusercontent.com/112799483/217569261-83f4ba7d-b262-42c9-b02a-9ddab9084f07.png)

**Comment by Yefeng888999** [comment]
已解决，依赖没刷新好，应该有缓存，测试出问题了

**Comment by Yefeng888999** [comment]
出现了新的问题，我项目本来集成的swagger2崩了
![image](https://user-images.githubusercontent.com/112799483/217571833-80ffb103-b083-4f06-8084-cff60ba2a033.png)
路径mapping丢失了，这个mapping不是我配置的，是swagger2默认的

**Comment by Yefeng888999** [comment]
![image](https://user-images.githubusercontent.com/112799483/217575988-efbd6264-2afe-4b9d-9977-e2bb95e3bbc6.png)
配置了之后还是无法访问
![image](https://user-images.githubusercontent.com/112799483/217576238-a0ace0d4-3d9f-4e5e-b226-d9bc20b36abb.png)
 用着有点费劲啊

**Comment by Yefeng888999** [comment]
能否帮忙解决下，项目在搁置，无法使用fastjosn2,这样我只能启用fastjson2了

**Comment by VictorZeng** [comment]
@Yefeng888999 fastjson理论上不会影响swagger-ui的路径mapping，请检查一下swagger的相应配置

**Comment by Yefeng888999** [comment]
已解决

//EnableSwagger2-是springfox:提供的一个注解，代表swagger2相关技术开启。
//会扫描当前类所在包，及子包中所有的类型中的注解-》swagger文档
@EnableSwagger2
@Configuration
public class SwaggerConfiguration  implements WebMvcConfigurer {

    /**
     * 创建Docket对象，交给SpringContainer管理
     * Docker是swagger的全局配置对象
     *
     * @return {@link Docket}
     */
    @Bean
    public Docket docket() {
        //描述swagger文档版本
        Docket docket = new Docket(DocumentationType.SWAGGER_2);

        ApiInfo apiInfo = new ApiInfoBuilder()
                .contact(//配置swagger文档的主体的联系信息
                        new Contact(
                                "",//文档发布者的名称
                                "http://0.0.top",//文档发布者的网站地址
                                "")//文档发布者的电子邮箱
                )
                .title("Random Extract Swagger Develop Documentation")
                .description("随机抽取，世界无奇不有")
                .version("1.0")
                .build();

        //给swagger上下文配置api的描述信息
        docket.apiInfo(apiInfo);

        docket.select() //获取Docket的选择器构建者，返回ApiSelectorBuilder 如：扫描什么包的注解
                .apis(RequestHandlerSelectors.basePackage("top.maple.night"));//要扫描的包的路径(include son package)
        return docket;
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/**").addResourceLocations(
                "classpath:/static/");
        registry.addResourceHandler("swagger-ui.html").addResourceLocations(
                "classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations(
                "classpath:/META-INF/resources/webjars/");
        WebMvcConfigurer.super.addResourceHandlers(registry);
    }
}

**Comment by yangcanlin** [comment]
> ![image](https://user-images.githubusercontent.com/112799483/217569080-13fa4db2-b5c6-4652-be22-0e6d28c25916.png) 弄好了，但运行显示Long类型还是未转换为字符串 ![image](https://user-images.githubusercontent.com/112799483/217569261-83f4ba7d-b262-42c9-b02a-9ddab9084f07.png)

您好，你这个是怎么解决的。我现在也是从 16版本升级到24版本后出现这个爆红情况。

**Comment by Yefeng888999** [comment]
爆红不应该,你根据官网的配置文档,更新对应版本的配置类,就是这个图片
![](https://user-images.githubusercontent.com/112799483/217569080-13fa4db2-b5c6-4652-be22-0e6d28c25916.png)

**Comment by Yefeng888999** [comment]
![image](https://user-images.githubusercontent.com/112799483/224200338-953e7e39-6740-4054-b3f6-d973a656fae7.png)
依赖 用这个

**Comment by yangcanlin** [comment]
> ![image](https://user-images.githubusercontent.com/112799483/224200338-953e7e39-6740-4054-b3f6-d973a656fae7.png) 依赖 用这个

解决了，谢谢，为了兼容Spring5和6，好像在 2.0.23 版本把 FastJsonHttpMessageConverter 类迁移到 Spring5 或 Spring6 的jar里面了，所以导致我找不到。非常感觉您的回复。
