### ISSUE TITLE
[QUESTION]兼容包中JSONArray实现的是List而非List<Object>, 导致类型推断出错。

### ISSUE THREAD

**Issue by metal-huang** [alibaba/fastjson2#1103]
### 兼容包中JSONArray实现的是List而非`List<Object>`, 导致类型推断出错。

```
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>fastjson</artifactId>
    <version>2.0.23</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/37770893/217711458-f1f99f84-953b-4f32-b26c-e232cf138a78.png)

![image](https://user-images.githubusercontent.com/37770893/217711262-c37f39eb-c43d-45ce-97c9-a06d5c29d254.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.24-SNAPSHOT/
问题已修复，请用2.0.24-SNAPSHOT版本帮忙验证，2.0.24-SNAPSHOT预计在2月中旬发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.24
问题已修复，请用新版本

**Comment by metal-huang** [comment]
已验证该修复
