### ISSUE TITLE
[BUG]JSONArray.parseArray方法缺少public关键字

### ISSUE THREAD

**Issue by wjf8882300** [alibaba/fastjson2#1107]
### 问题描述

    static <T> List<T> parseArray(String input, Class<T> type) {
        return JSON.parseArray(input, type);
    }

无法通过静态方法调用了：JSONArray.parseArray

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.24-SNAPSHOT/
问题已修复，请用2.0.24-SNAPSHOT版本帮忙验证，2.0.24-SNAPSHOT预计在2月中旬发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.24
问题已修复，请用新版本
