### ISSUE TITLE
文档里没有自定义消息转化器的示例

### ISSUE THREAD

**Issue by Yefeng888999** [alibaba/fastjson2#1109]
### 问题描述
序列化LocalDateTime格式失效

### 环境信息
*请填写以下信息：*

 - OS信息： win10 [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息：1.8 [e.g.：Openjdk 1.8.0_312]
 - 版本信息：2.023[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*
![image](https://user-images.githubusercontent.com/112799483/218249800-4b3a679b-9fa0-4ef8-a838-1ce4e752cf8f.png)

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
我想配置一个全局自动解析时间时期的消息转化器，可以格式将localdateTime格式的字段格式化为指定格式，请问1、config.setDateFormat("yyyy-MM-dd HH:mm:ss");这个配置在哪里生效了，配了有什么用
2、我如果自定义全局的消息转换器，为何你们文档中找不到示例，不支持消息转化器吗？

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by Yefeng888999** [comment]
网上的搜索结果乱七八糟，版本也都不一致，你们文档不该写一个自定义消息转化器示例吗

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/blob/main/extension-spring5/src/main/java/com/alibaba/fastjson2/support/spring/http/converter/FastJsonHttpMessageConverter.java
你看下内置的代码，自己写一个？

**Comment by Yefeng888999** [comment]
大佬你好，你那个类要重写的方法有点多，我不确定我们说的是用一个东西，之前用jackson的只需这样配置就好
 /**
     * LocalDateTime转换器，用于转换RequestParam和PathVariable参数
     */
    @Bean
    public Converter<String, LocalDateTime> localDateTimeConverter() {
        return new Converter<String, LocalDateTime>() {
            @Override
            public LocalDateTime convert(@NotNull String source) {
                return LocalDateTime.parse(source, DateTimeFormatter.ofPattern(DEFAULT_DATE_TIME_FORMAT));
            }
        };
    }

/**
     * Json序列化和反序列化转换器，用于转换Post请求体中的json以及将我们的对象序列化为返回响应的json
     */
    @Bean
    public ObjectMapper objectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        objectMapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);

        //LocalDateTime系列序列化和反序列化模块，继承自jsr310，我们在这里修改了日期格式

        JavaTimeModule javaTimeModule = new JavaTimeModule();
        javaTimeModule.addSerializer(LocalDateTime.class, new LocalDateTimeSerializer(DateTimeFormatter.ofPattern(DEFAULT_DATE_TIME_FORMAT)));
        javaTimeModule.addSerializer(LocalDate.class, new LocalDateSerializer(DateTimeFormatter.ofPattern(DEFAULT_DATE_FORMAT)));
        javaTimeModule.addSerializer(LocalTime.class, new LocalTimeSerializer(DateTimeFormatter.ofPattern(DEFAULT_TIME_FORMAT)));
        javaTimeModule.addDeserializer(LocalDateTime.class, new LocalDateTimeDeserializer(DateTimeFormatter.ofPattern(DEFAULT_DATE_TIME_FORMAT)));
        javaTimeModule.addDeserializer(LocalDate.class, new LocalDateDeserializer(DateTimeFormatter.ofPattern(DEFAULT_DATE_FORMAT)));
        javaTimeModule.addDeserializer(LocalTime.class, new LocalTimeDeserializer(DateTimeFormatter.ofPattern(DEFAULT_TIME_FORMAT)));


        //Date序列化和反序列化
        javaTimeModule.addSerializer(Date.class, new JsonSerializer<Date>() {
            @Override
            public void serialize(Date date, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
                SimpleDateFormat formatter = new SimpleDateFormat(DEFAULT_DATE_TIME_FORMAT);
                String formattedDate = formatter.format(date);
                jsonGenerator.writeString(formattedDate);
            }
        });
        javaTimeModule.addDeserializer(Date.class, new JsonDeserializer<Date>() {
            @Override
            public Date deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws IOException, JsonProcessingException {
                SimpleDateFormat format = new SimpleDateFormat(DEFAULT_DATE_TIME_FORMAT);
                String date = jsonParser.getText();
                try {
                    return format.parse(date);
                } catch (ParseException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        objectMapper.registerModule(javaTimeModule);
        return objectMapper;
    }

写个类型转化器然后注册下就好，FastJson2应该也有类似这种配置的东西吧

**Comment by Yefeng888999** [comment]
![image](https://user-images.githubusercontent.com/112799483/218251100-10488e8f-1837-457f-8165-263eb9f760ab.png)
上面代码看着有点乱

**Comment by wenshao** [comment]
fastjson2中不需要这个，内置了LocalDateTime和String的转换，你这个格式，是不需要做额外配置的。

**Comment by Yefeng888999** [comment]
首先，感谢温哥在帮忙之中为我解答问题，我真的感觉为了这种小问题打扰温哥挺不好意思；其次，我之所以想将springboot项目的默认json改为fastjson2，最初仅仅是国产，心里更喜欢用国产的东西去做开发，但这几天发现，fastjson2真的很适合国内的开发环境，各种配置感觉设计的都很周全，我目前公司项目使用默认json工具是jackson，fastjson只是引入在代码中进行解析json字符串，但我个人打算自己的私人小项目都用fastjson2来做默认json工具，希望fastjson2做的越来越好。

**Comment by Yefeng888999** [comment]
![image](https://user-images.githubusercontent.com/112799483/218261682-0af722c4-3512-4feb-9eff-224255c25b2a.png)
![image](https://user-images.githubusercontent.com/112799483/218261697-0e4d1bc3-f87e-42e9-8c3c-6331df00ec00.png)
![image](https://user-images.githubusercontent.com/112799483/218261703-c15e0c25-a255-4ecc-a107-56a5d341a26b.png)
![image](https://user-images.githubusercontent.com/112799483/218261715-38f7267e-5344-41fc-b4ae-3b79be4b84c8.png)
从浏览器接受Long类型的拿到了所有的精度来看，fastjson2的配置已经生效了，但不知为何我的时间格式不仅没有按默认配置去转化，反而变成了数组，希望能解答一下。

**Comment by imalexyang** [comment]
写成这样试试？
fastJsonConfig.setSerializerFeatures(SerializerFeature.WriteDateUseDateFormat);

**Comment by Yefeng888999** [comment]
我用的最新的2.023版本，fastJsonConfig配置类根本没这个Api

**Comment by Yefeng888999** [comment]
![image](https://user-images.githubusercontent.com/112799483/218724475-c6360036-8cdb-4b7b-9b2b-4cdf95abd439.png)
![image](https://user-images.githubusercontent.com/112799483/218724510-5098b2d6-3abc-4631-8a4e-2453e70aee97.png)
去掉 这个注解问题直接解决了
