### ISSUE TITLE
JSONArray的实例不再有toJSONString的方法了吗？

### ISSUE THREAD

**Issue by RyouonRitsu** [alibaba/fastjson2#111]
1.0的版本的时候是可用的，更新到2.0版本后不可用了，请问是不再支持了吗？文档里没看到有写？

**Comment by wenshao** [comment]
有两种用法：
 ```java
JSONArray array = ...;
array.toJSONString();
```

```java
JSON.toJSONString(xxx);
```

JSONArray没有继承自JSON了，所有有变化，需要你改一下

**Comment by RyouonRitsu** [comment]
我在使用`array = JSON.parseArray(string)`和`string = JSON.toJSONString(array)`的过程中项目提示我**出现了非法的反射使用…所有的非法反射使用将在后续被拒绝**，是我的用法有问题吗

**Comment by wenshao** [comment]
fastjson2会针对JDK 17后的版本做不同的实现

**Comment by RyouonRitsu** [comment]
所以我是该无视它继续用还是回滚到1.x老版本

**Comment by wenshao** [comment]
你可以无视他

**Comment by RyouonRitsu** [comment]
好的，感谢您的回复
