### ISSUE TITLE
关于fastjson格式化json的问题

### ISSUE THREAD

**Issue by chenze12** [alibaba/fastjson2#1110]
fastjson 2.0版本使用

JSON.toJSONString(jsonObject, SerializerFeature.PrettyFormat,
SerializerFeature.WriteMapNullValue,
SerializerFeature.WriteDateUseDateFormat);
![image](https://user-images.githubusercontent.com/66512654/218358550-9ef1703f-246e-48cf-b539-134b5520aa01.png)

无法将 data 格式化，
目前测试1.4，1.8 版本的都可以格式化，请问下是我这边使用方法不对吗？
![image](https://user-images.githubusercontent.com/66512654/218358528-aad8aa28-4df7-43d9-8a5b-d6a851050f29.png)

**Comment by wenshao** [comment]
可以用最新版本2.0.23验证么？

**Comment by chenze12** [comment]
2.0.4是项目的版本，用最新的验证了 可以格式化  谢谢

**Comment by chenze12** [comment]
好的 ，已经解决了 感谢
