### ISSUE TITLE
Long类型转字符串失败

### ISSUE THREAD

**Issue by Yefeng888999** [alibaba/fastjson2#1111]
### 问题描述
*简要描述您碰到的问题。*
我配置了   //在大范围超过JavaScript支持的整数，输出为字符串格式
                JSONWriter.Feature.BrowserCompatible);
但结果却是前端虽然接受到了整个Long数字的全精度，但还是数字类型，并没有转换为字符串类型，导致前端只要对这个数字进行操作就会丢失精度

### 环境信息
*请填写以下信息：*

 - OS信息：  win10[e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： jdk1,8[e.g.：Openjdk 1.8.0_312]
 - 版本信息：Fastjson2 2.0.23[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://user-images.githubusercontent.com/112799483/218475734-1ce94bf9-f83b-46af-9e16-77017a482605.png)
如上图所示，所有Long类型的id都没有双引号，都是数字，同时时间字段不知为何都成了数组，望解决

**Comment by Yefeng888999** [comment]
你这种是代码内部使用，我是用fastjson2替换掉了默认的jackson,然后前后端传递json数据就会出现问题，请问能留个联系方式吗，比如邮箱之类的，我把项目直接发你，你启动下即可复现

**Comment by wenshao** [comment]
你检查下版本号，如果版本不是2.0.23，就用更新到最新版本验证，如果最新版本仍然有问题，尝试调试到如下方法：com.alibaba.fastjson2.JSONWriterUTF16#writeInt64 

```java
class JSONWriterUTF16
    @Override
    public final void writeInt64(long i) {
        boolean writeAsString = false;
        if ((context.features & (Feature.WriteNonStringValueAsString.mask | WriteLongAsString.mask)) != 0) {
            writeAsString = true;
        } else if ((context.features & Feature.BrowserCompatible.mask) != 0
                && (i > 9007199254740991L || i < -9007199254740991L)) {
            writeAsString = true;
        }
       // ...
    }
}
```

**Comment by Yefeng888999** [comment]
打了断点，根本没有进入到这一步，没进去到这个方法，我有配置有问题吗
![image](https://user-images.githubusercontent.com/112799483/218714650-b488a484-4dad-4802-9e30-7dcc3afea69f.png)
![image](https://user-images.githubusercontent.com/112799483/218714699-7ca930d3-3f35-40eb-b30d-f407e6d64a12.png)

**Comment by Yefeng888999** [comment]
我2.022和2.023版本都尝试了

**Comment by wenshao** [comment]
看下是否走到这个方法 com.alibaba.fastjson2.JSONWriterUTF8#writeInt64，如果都没有，就要看下是否真的用了fastjson2了

**Comment by Yefeng888999** [comment]
刚刚突然解决了，去掉了一个注解，之后全都好了
![image](https://user-images.githubusercontent.com/112799483/218724216-556e69a5-c097-4f6f-855d-59a94fc31676.png)
但这个注解是你们文档里带的啊
![image](https://user-images.githubusercontent.com/112799483/218724304-3b78671f-e966-4429-87ce-74a705741c49.png)
可给我折腾坏了

**Comment by Yefeng888999** [comment]
温哥可以看看这个文章，https://blog.csdn.net/Zong_0915/article/details/126625489，有没有可能你们搞错了，我不确定
