### ISSUE TITLE
[BUG] 某些情况下浮点数反序列化异常

### ISSUE THREAD

**Issue by louis-wangxiao** [alibaba/fastjson2#1120]
### 问题描述
*{"rate": 0.000000006E3}, the corresponding java fied 'rate' is of BigDecimal type, and an exception will be thrown during deserialization*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：macOS]
 - JDK信息： [e.g.：jdk11.0.15.1]
 - 版本信息：[e.g.：Fastjson2 2.0.19]
 

### 重现步骤
*JSON.parseObject(json,XXX.class)*

**Comment by wenshao** [comment]
科学计数法会被缺省识别为Double类型，你可以这样用：
```java
JSONObject object = JSON.parseObject("{\"rate\": 0.000000006E3}");
BigDecimal rate = object.getBigDecimal("rate");
assertEquals(BigDecimal.valueOf(Double.parseDouble("0.000000006E3")), rate);
```

**Comment by louis-wangxiao** [comment]
> 



> 科学计数法会被缺省识别为Double类型，你可以这样用：
> 
> ```java
> JSONObject object = JSON.parseObject("{\"rate\": 0.000000006E3}");
> BigDecimal rate = object.getBigDecimal("rate");
> assertEquals(BigDecimal.valueOf(Double.parseDouble("0.000000006E3")), rate);
> ```

同样抛出异常：
![image](https://user-images.githubusercontent.com/37292240/219576748-12099399-3a96-4445-9dc1-09025faac339.png)

**Comment by wenshao** [comment]
这个问题修复过，帮忙用2.0.23版本验证下

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.24-SNAPSHOT/
感谢反馈，问题已经修复，请帮忙用2.0.24-SNAPSHOT版本验证，2.0.24版本预计在周末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.24
问题已修复，请用新版本

**Comment by soosu6688** [comment]
JSONObject jsonObject = JSON.parseObject(result);
java.lang.NumberFormatException: For input string: "3.5737170345857214211049055E-11E-11"
还是会出错，怎么回事？
