### ISSUE TITLE
[BUG]JSONObject.toJSONString属性名称错误

### ISSUE THREAD

**Issue by xcocean** [alibaba/fastjson2#1124]
### 问题描述
JSONObject.toJSONString属性名称错误，序列化后首字符变大写了：`pId` → `PId`

### 环境信息
 - OS信息：  `win10 x64`
 - JDK信息： `openjdk version "17.0.4" 2022-07-19 LTS`
 - 版本信息：`Fastjson2 2.0.23`
 

### 重现步骤
1、编写一个简单的bean
2、使用`JSONObject.toJSONString`输出
3、错误的 `pId` 属性
```java
@Data
public class CategoryVo implements Serializable {
    private String id;

    // @JSONField(name = "pId")
    private String pId;

    private String name;
}

// 调用代码
System.out.println(JSONObject.toJSONString(categories));
```

### 期待的正确结果
```
// 正确的：
{"pId":"1","createTime":"2023-02-18 23:10:58","id":"1676733058995","name":"生活"}

// 实际的，，注意这个PId，应该是pId，通过序列化首字符却变成了大写
{"PId":"1","createTime":"2023-02-18 23:10:58","id":"1676733058995","name":"生活"}
```
1、目前的解决方案是添加 @JSONField(name = "pId")
2、我并没有试调追踪源码，有空的同学请试调一下这个bug

### 相关日志输出
无

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
JavaBean就是这个规范，你看java.beans.Introspector#decapitalize 这个方法实现

**Comment by xcocean** [comment]
@wenshao 原来是有规范，好的谢谢！

**Comment by xcocean** [comment]
@wenshao 原来是有规范，好的谢谢！
