### ISSUE TITLE
[QUESTION]JSON.isValid() 与 JSON.isValidObject() 有什么区别么？

### ISSUE THREAD

**Issue by YuLv-o3o** [alibaba/fastjson2#1129]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
发现有些 JSON 字符串 JSON.isValidObject() 可以通过校验，但是 JSON.isValid() 无法通过校验。

**Comment by wenshao** [comment]
JSON除了Object之外，还可以是Array、Number、String、Null、Boolean
