### ISSUE TITLE
JSONPath.extract  与 JSONPath.eval 表现不一致

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/fastjson2#113]
String testJson2 = "{\"result\":[{\"puid\":\"21025318\"},{\"puid\":\"21482682\"},{\"puid\":\"21025345\"}],\"state\":0}";
Object result2 = JSONPath.extract(testJson2,"$.result[0,2].puid");
System.out.println(result2);//null
Object result3 = JSONPath.eval(testJson2, "$.result[0,2].puid");
System.out.println(result3);//["21025318","21025345"]

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
