### ISSUE TITLE
[BUG]json字段有多个数组时，解析arr1数组的字段值时得到了arr2数组的结果

### ISSUE THREAD

**Issue by jindabit** [alibaba/fastjson2#1130]
### 问题描述
利用fastjson2解析对应的数组字段不能得到期望结果

### 环境信息

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.25]
 

### 重现步骤
*如何操作可以重现该问题：*
  解析json字段 "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"b\"]}"，期望得到数组arr2中的第一个值b，但输入arr2[0]后，得到的是arr1数组中的值a。

```java
//可在此输入示例代码
 String raw = "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"b\"]}";
    instance.eval(raw, "$.arr2[0]");
    Mockito.verify(collector, Mockito.times(1)).collect(Row.of("b"));

### 期待的正确结果
期待得到正确的数组字段解析结果

**Comment by wenshao** [comment]
```java
        String raw = "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"b\"]}";
        Object result = JSONPath.eval(raw, "$.arr2[0]");
        assertEquals("b", result);
```
我测试没发现问题啊

**Comment by jindabit** [comment]
补了几个测试用例；case2和case5是正常的，但是case3和case4测下来有问题
 ```
@Test
  public void testArrayParseCase2() {

    String raw = "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"b\"]}";
    Assert.assertEquals("b", ((String) JSONPath.extract(raw, "$.arr2[0]")));
    Assert.assertEquals("b", ((String) JSONPath.eval(raw, "$.arr2[0]")));
  }

  @Test
  public void testArrayParseCase3() {
    String raw = "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"b\"]}";
    Assert.assertEquals("b", ((JSONArray) JSONPath.extract(raw, "$.arr2[*][0]")));
    Assert.assertEquals("b", ((JSONArray) JSONPath.eval(raw, "$.arr2[*][0]")));
  }

  @Test
  public void testArrayParseCase4() {
    String raw = "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"b\"]}";
    String[] paths = new String[] {"$.arr2[0]"};

    Type[] types = new Type[paths.length];
    Arrays.fill(types, String.class);
    JSONPath path = JSONPath.of(paths, types);
    Object[] results = (Object[]) path.extract(raw);
    Assert.assertEquals("b", results[0]);
  }

@Test
  public void testArrayParseCase5() {
    String raw = "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"b\"]}";
    String[] paths = new String[] {"$.arr2[0]", "$.arr1[0]"};

    Type[] types = new Type[paths.length];
    Arrays.fill(types, String.class);
    JSONPath path = JSONPath.of(paths, types);
    Object[] results = (Object[]) path.extract(raw);
    Assert.assertEquals("b", results[0]);
    Assert.assertEquals("a", results[1]);
  }
 ```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布。

可以说下你使用场景么？

**Comment by lhaox** [comment]
@wenshao  也许JSONPathTypedMultiIndexes还存在缺陷，补充case
``` java
@Test
public void testArrayParseCase6() {
    String raw = "{\"arr1\":[\"a\"],\"numeric\":1,\"arr2\":[\"a\"]}";
    JSONPath path = JSONPath.of(new String[]{"$.arr2[0]", "$.arr2[0]"}, new Type[]{String.class, String.class});
    Object[] results = (Object[]) path.extract(raw);
    assertArrayEquals(new Object[]{"a", "a"}, results);
}
```
运行结果：
org.opentest4j.AssertionFailedError: array contents differ at index [1], 
Expected :a
Actual   :null

**Comment by wenshao** [comment]
我对你的PR做了一个性能优化，在没有重复index时，不做额外的计算。

可以分享下你的使用场景么？我对大家怎么用这个功能需要反馈

**Comment by lhaox** [comment]
> 我对你的PR做了一个性能优化，在没有重复index时，不做额外的计算。
> 
> 可以分享下你的使用场景么？我对大家怎么用这个功能需要反馈

@wenshao 感谢您对我这个PR斧正。
我并没有在实际生产中使用到这个功能，只是对fastjson2感兴趣，测试这个issue的作者提供的case时发现了问题

**Comment by Leoyzen** [comment]
@wenshao 我们主要在大数据场景下，通过 fastjson2 实现 json udf 来加速 json 的解析。所以相关的 issue 会比较多。
类似于 json_path 函数、get_json_object、from_json 等hive 、flink 下比较常用的 json udf 用法。

**Comment by Leoyzen** [comment]
另外之前的一个 issue 下的补充，貌似还没解决，也是相关的#1070：


// 测试不通过，返回的是嵌套数据 "[[[{\"a\":1},{\"a\":2}],[{\"a\":3}]]]";
String raw = "[[{\"a\":1},{\"a\":2}],[{\"a\":3}]]";
Assert.assertEquals("[[{\"a\":1},{\"a\":2}],[{\"a\":3}]]",
                ((JSONArray) JSONPath.extract(raw, "$")).toJSONString());
// 测试通过
Assert.assertEquals("[[{\"a\":1},{\"a\":2}],[{\"a\":3}]]";,
                ((JSONArray) JSONPath.extract(raw, "$[*]")).toJSONString());

**Comment by wenshao** [comment]
@Leoyzen 
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
问题已修复，请帮忙用2.0.26-SNAPSHOT版本验证，2.0.26版本预计在4月中旬发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
新版本已发布，请用新版本
