### ISSUE TITLE
[FEATURE]我已经不搞编程了，但是我提供一个最快最简单最正确的序列化思路

### ISSUE THREAD

**Issue by benjaminyin01** [alibaba/fastjson2#1132]
json序列化这个问题，其实好的办法就是最简单的方法——硬编码：
```
public class Person {
    public String name;
    public int age;
    public String toJson()  {
        return "{ 'name': "+this.name+", 'age': "+this.age+" }"
    }
}
```
但是这种办法太麻烦，也容易出错，最好的办法就是编译器自动支持生成硬编码，就相当于把一些第三方代码生成工具的功能加进编译器里。我听说.net已经添加这种功能了。给类添加一个注解，或者继承一个interface，编译器就自动生成一部分代码。我更喜欢实现接口的方式，语义上更合理。
```
@JsonSerialization
public class Person  implements IJsonSerialization {
}
```
如果目前Java编译器还不支持这种特性，则可以用字节码生成功能把这个硬编码的函数。
这种方法又简单又高效。

我不搞编程的原因是，一岁数大了，二，中国理工科技计算机行业加班太重，三，只有家里穷、没见识的家庭的孩子才搞苦大仇深的理工科技计算机

**Comment by wenshao** [comment]
现在fastjson就做了JIT的方式，会针对每个JavaBean对象生成一个Serializer&Deserializer类，不会有反射

**Comment by benjaminyin01** [comment]
那你们阿里巴巴牛逼吹的那么响，不应该只使用JIT字节码，应该把代码生成模版功能添加到Java编译器啊。
