### ISSUE TITLE
Boolean的get方法与is方法共存时不可预测[BUG]

### ISSUE THREAD

**Issue by Trager324** [alibaba/fastjson2#1133]
### 问题描述
Boolean的get方法与is方法共存时无法预测会调用哪个方法

### 环境信息
 - OS信息：  windows
 - JDK信息： jdk1.8
 - 版本信息：Fastjson2 2.0.23
 

### 重现步骤
以下测试用例能否通过不可预测
```java
import com.alibaba.fastjson2.JSON;
import lombok.Data;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.fail;

public class FastJsonBooleanTest {
    @Data
    static class A {
        private Boolean success;
        public Boolean isSuccess() {
            fail();
            return null;
        }
    }

    @Test
    void test() {
        System.out.println(JSON.toJSONString(new A()));
    }
}
```

### 期待的正确结果
按照JavaBean约定，**boolean**对应方法以**is**开头，**Boolean**对应方法以**get**开头
建议忽略以**is**开头的**Boolean**方法，或明确指定这种情况下应该以哪个方法为优先

### 相关日志输出
![image](https://user-images.githubusercontent.com/60724385/220317657-10f79d0f-4a9c-48af-9702-ba5464a33f71.png)
![image](https://user-images.githubusercontent.com/60724385/220317730-dd3fba57-993d-4cfe-9c9c-64d739e9a83e.png)

#### 附加信息
猜测获取FiledWriter时使用了并发扫描并进行了全局缓存，导致所有后续结果会以缓存结果为准

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25预计在3月中旬发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
