### ISSUE TITLE
[BUG] Map中key为数字类型没序列化为字符串，导致客户端报错

### ISSUE THREAD

**Issue by logan2013** [alibaba/fastjson2#1135]
### 问题描述
*简要描述您碰到的问题。*

客户端会校验标准的json格式，不是就报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 
最新版本

### 重现步骤

        HashMap<Integer, Integer> map = new HashMap<>();
        map.put(1, 2);
        System.out.println(JSON.toJSONString(map));

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

期望：
{"1":2}

实际：
{1:2}

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by logan2013** [comment]
https://github.com/alibaba/fastjson2/issues/273
看了这个问题，好像是因为fastjson1而改的

而我这边是把jackson换成fastjson2

**Comment by wenshao** [comment]
```java
JSON.toJSONString(obj, JSONWriter.Feature.WriteNonStringKeyAsString)
```

或者全局配置
```java
JSON.config(JSONWriter.Feature.WriteNonStringKeyAsString)
```

**Comment by logan2013** [comment]
谢谢
