### ISSUE TITLE
int,boolean类型值未按照指定方式转换

### ISSUE THREAD

**Issue by edeye** [alibaba/fastjson2#1136]
### 问题描述
int,boolean类型值未按照指定方式转换

### 环境信息
*请填写以下信息：*

 - OS信息：  [win10 x64]
 - JDK信息： [Oracle-jdk 1.8.0_212]
 - 版本信息：[fastjson2 2.0.24, fastjson2-extension-spring5 2.0.24]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
    public static void main(String[] args) {
        JSON.register(java.lang.Boolean.class, (jsonWriter, o, o1, type, l) -> jsonWriter.writeString("boolean:" + o.toString()));
        JSON.register(java.lang.Integer.class, (jsonWriter, o, o1, type, l) -> jsonWriter.writeString("int:" + o.toString()));
        JSON.register(java.lang.Long.class, (jsonWriter, o, o1, type, l) -> jsonWriter.writeString("long:" + o.toString()));
        JSON.register(java.util.Date.class, (jsonWriter, o, o1, type, l) -> jsonWriter.writeString("date:意思意思"));
        Map<String, Object> test = new HashMap<>();
        test.put("bl", true);
        test.put("int", 111);
        test.put("long", 222L);
        test.put("date", new java.util.Date());
        System.out.println(JSON.toJSONString(test, JSONWriter.Feature.PrettyFormat));
    }
```

### 期待的正确结果
{
	"date":"date:意思意思",
	"bl":"boolean:true",
	"int":"int:111",
	"long":"long:222"
}

### 相关日志输出
{
	"date":"date:意思意思",
	"bl":true,
	"int":111,
	"long":"long:222"
}

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
为什么要做这种定制序列化？能说下场景么？

**Comment by edeye** [comment]
> 为什么要做这种定制序列化？能说下场景么？

发给前端的数据必须都是字符串格式的, 既是是Boolean也到前端也必须变成'true'或'false', 这是我们的要求.没有场景硬性规定,

代码中特意指定了ObjectWriter的情况就应该按照指定的方式进行转换, 现在Double,Long,Float,Bigdecimal都可以,
就只有Boolean和Integer还是按照未指定的方式转换的, 那指定ObjectWriter针对Boolean或者Integer就没有意义了

**Comment by wenshao** [comment]
```java
JSON.toJSONString(obj, JSONWriter.Feature.WriteNonStringValueAsString)
```
看下这个是否符合你的要求？使用注册的定制序列化类是不好做性能优化的。

**Comment by edeye** [comment]
> ```java
> JSON.toJSONString(obj, JSONWriter.Feature.WriteNonStringValueAsString)
> ```
> 
> 看下这个是否符合你的要求？使用注册的定制序列化类是不好做性能优化的。

感谢百忙之中的回复 Orz,已经用改代码的方式暴力解决了.....
> ```java
ObjectWriterImplMap.java 481 ==> else if (valueClass == Integer.class) 
ObjectWriterImplMap.java 492 ==> else if (valueClass == Boolean.class)
> ```
这2个判断内直接 jsonWriter.writeString(value.toString());
