### ISSUE TITLE
[BUG] can not cast to java.sql.Timestamp, from class java.lang.Long

### ISSUE THREAD

**Issue by Lerchar** [alibaba/fastjson2#1146]
### 问题描述
在将包含Long类型时间戳的字符串转换成明确的对象时，提示can not cast to java.sql.Timestamp, from class java.lang.Long

### 环境信息
*请填写以下信息：*

 - OS信息： win11
 - JDK信息：jdk11
 - 版本信息：Fastjson2.0.23
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
public class Test {
    public static void main(String[] args) {

        String str2 = "[{\"ts\":1677459527000,\"name\":\"商品\"}]";

        JSONArray jsonArray = JSON.parseArray(str2);
        List<Product> products = jsonArray.toJavaList(Product.class);
        System.out.println(products.get(0).getName());
    }

    static class Product {
        public String name;
        public Timestamp ts;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Timestamp getTs() {
            return ts;
        }

        public void setTs(Timestamp ts) {
            this.ts = ts;
        }
    }
}
```

### 期待的正确结果
不想使用@JSONField注解，因为对象中这个字段就是表明时间戳，而不是要显示为明确格式的字符串

### 相关日志输出
Exception in thread "main" com.alibaba.fastjson2.JSONException: can not cast to java.sql.Timestamp, from class java.lang.Long
	at com.alibaba.fastjson2.util.TypeUtils.cast(TypeUtils.java:1279)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:128)
	at com.alibaba.fastjson2.JSONArray.toList(JSONArray.java:1028)
	at com.alibaba.fastjson2.JSONArray.toJavaList(JSONArray.java:1117)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布。

**Comment by Lerchar** [comment]
已验证， long to java.sql.Time/Timestamp/Date 可以转换
