### ISSUE TITLE
JSONPath读取JSONArray不支持负数索引[BUG]

### ISSUE THREAD

**Issue by xinyuanlee** [alibaba/fastjson2#1153]
### 问题描述
*JSONPath读取JSONArray不支持负数索引。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：WIN10]
 - JDK信息： [e.g.：Openjdk 1.8.0_202]
 - 版本信息：[e.g.：Fastjson2.0.24]
 

### 重现步骤
1. 使用 `JSONPath.extract` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
        JSONPath PATH_1 = JSONPath.of("$.[-1].fullName");

        String json = " [{\"age\":11,\"dateOfBirth\":\"2023-02-27 17:49:15\",\"fullName\":\"Tide\"}," +
                "{\"age\":81,\"dateOfBirth\":\"1976-09-10 11:17:36\",\"fullName\":\"Bob\"}," +
                "{\"age\":52,\"dateOfBirth\":\"1998-11-16 07:44:16\",\"fullName\":\"Sony\"}]";

        /*
            $.[0].fullName - Tide
            [0].fullName - Tide
            [1].fullName - Bob
            [-1].fullName - Tide ??? 
         */
        JSONReader reader = JSONReader.of(json);
        String extract = (String) PATH_1.extract(reader);

        System.out.println("JSONReader extract : = " + extract);
```

### 期待的正确结果
*JSONReader extract : = Sony*

### 相关日志输出
*JSONReader extract : = Tide*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
