### ISSUE TITLE
使用jackson的@JsonFormat(shape = JsonFormat.Shape.STRING)，输出的字段不是String

### ISSUE THREAD

**Issue by wugui0823** [alibaba/fastjson2#1167]
在实体上的字段上使用的jackson的@JsonFormat，将其他类型转成String类型输出，但是结果还是数值类型，现在是否支持，或者有什么方案可以替换的吗。
![image](https://user-images.githubusercontent.com/16262592/222084035-319e3c65-4cd0-4e60-9703-6f4fa2faf076.png)
![image](https://user-images.githubusercontent.com/16262592/222084187-48019788-94f2-4a54-96bc-b93fd6579284.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布。

**Comment by wugui0823** [comment]
换成2.0.25-SNAPSHOT可以了，谢谢大佬。
但是如果fastjson2-extension也升级到2.0.25-SNAPSHOT，就会提示找不到FastJsonHttpMessageConverter，是有新的替换类吗

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
