### ISSUE TITLE
[QUESTION]SimpleDateFormatSerializer 在兼容模式升级下找不到

### ISSUE THREAD

**Issue by 1uanWu** [alibaba/fastjson2#1176]
### 请描述您的问题
使用兼容模式升级到了2.0.23，但是之前1.2.83 使用的 SimpleDateFormatSerializer 提示没有这个类了，是在新版本中被移除了吗
<img width="400" alt="image" src="https://user-images.githubusercontent.com/23513206/222365721-dc610dfa-355a-4614-9cd1-6de5dbe92ca5.png">
<img width="848" alt="image" src="https://user-images.githubusercontent.com/23513206/222365818-0b44342d-1027-4f08-b26d-088ffb542170.png">

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.25
问题已修复，请用新版本
