### ISSUE TITLE
JSON.parseObject 大小写敏感[BUG]

### ISSUE THREAD

**Issue by paras0l** [alibaba/fastjson2#1195]
### 问题描述
*JSON.parseObject 大小写敏感*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*
JSON.parseObject 大小写敏感
![image](https://user-images.githubusercontent.com/75265556/223347920-ec9fd8fe-5254-47ec-896d-7bd8427c511f.png)

```
import com.alibaba.fastjson2.JSON;
import lombok.Data;


public class TestFJ {
    public static void main ( String[] args ) {
        Dataa sse = JSON.parseObject ("{\"expId\":\"20059\",\"expCode\":\"1x011\",\"expCodeNe\":\"101a011\",\"GID\":\"GIsYLkkkPiT\"}",Dataa.class);
        Dataa ss = JSON.parseObject ("{\"ExpId\":\"20059\",\"ExpCode\":\"1x011\",\"ExpCodeNe\":\"101a011\",\"GID\":\"GIsYLkkkPiT\"}",Dataa.class);
        Dataa bb =
                com.alibaba.fastjson.JSON.parseObject ("{\"ExpId\":\"20059\",\"ExpCode\":\"1x011\",\"ExpCodeNe\":\"101a011\",\"GID\":\"GIsYLkkkPiT\"}",Dataa.class);
    }
}
@Data
class Dataa{
    private Integer expId;
    private String expCode;
    private String expCodeNe;
    private String gID;
}
```

### 期待的正确结果
*Dataa ss = JSON.parseObject ("{\"ExpId\":\"20059\",\"ExpCode\":\"1x011\",\"ExpCodeNe\":\"101a011\",\"GID\":\"GIsYLkkkPiT\"}",Dataa.class); ss属性不为空*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
可以用这个Feature.SupportSmartMatch，比如：
```java
JSON.parseObject("xxx", Bean.class, Feature.SupportSmartMatch)
```
