### ISSUE TITLE
请教关于2.0.2快照版本中JsonObject类继承LinkedHashMap去掉泛型<String, Object>用意

### ISSUE THREAD

**Issue by T-Atlas** [alibaba/fastjson2#120]
温少您好，我今日使用2.0.2快照版本发现JsonObject类继承LinkedHashMap去掉了泛型<String, Object>，因此我们原先代码中的jsonObj.entrySet()期望返回entry变成返回object，我不清楚这样更改后的用意，请指教

![54b7580a7f0f9d6238be63f6eecfe4b](https://user-images.githubusercontent.com/69239617/166139540-93146c32-f5f8-4e26-bf85-7df6db62133f.png)
![86e31421bd25b45c624c64db31dd7bc](https://user-images.githubusercontent.com/69239617/166139545-aa8bc040-fd09-4d0f-9268-3753fa7745bd.png)

```java
private static String[] getCsvContents(JSONObject jsonObj, String[] csvHeaders, int i) {
        String[] csvContent = new String[csvHeaders.length];
        //TODO:BUG FIX HERE
        for (Map.Entry<String, Object> entry : jsonObj.entrySet()) {
            if (entry.getValue() instanceof String) {
                csvContent[i] = (String) entry.getValue();
            } else {
                //TODO:Check the update of fastjson2 2.0.2
                JSONObject innerJsonObj = jsonObj.getJSONObject(entry.getKey());
                Iterator<Map.Entry<String, Object>> iterator = innerJsonObj.entrySet().iterator();
                csvContent[i] = (String) iterator.next().getValue();
            }
            i++;
        }
        return csvContent;
    }
```

**Comment by T-Atlas** [comment]
![image](https://user-images.githubusercontent.com/69239617/166140061-c4a83439-9b4f-4163-a786-761fc8ead844.png)

**Comment by wenshao** [comment]
为了修复这个issue https://github.com/alibaba/fastjson2/issues/110

**Comment by T-Atlas** [comment]
请问有没有迁移这段代码功能的建议呢/

**Comment by wenshao** [comment]
请更新代码再试试看

**Comment by T-Atlas** [comment]
这个问题解决了，但是JSON.toJSONString中使用JSONWriter.Feature.WriteNonStringValueAsString属性对double和boolean不生效，只能吧int转换为String

**Comment by wenshao** [comment]
你可以另外开一个issue并且能提供重现代码的例子么？

**Comment by T-Atlas** [comment]
好的

**Comment by MASON-PRINCE** [comment]
> 你可以另外开一个issue并且能提供重现代码的例子么？

issue125 已提供
