### ISSUE TITLE
[BUG]fastjson1和2同版本结果不一致(兼容问题)

### ISSUE THREAD

**Issue by w-sf** [alibaba/fastjson2#1203]
### 问题描述
使用snakeyaml.loadAs方法解析出的json，1版本可以操作，2版本不行
### 环境信息
 - OS信息：  [Windows10家庭中文版22H2-19045.2673]
 - JDK信息： [1.8.0_291]
 - 版本信息：[2.0.24]
```xml
<groupId>org.yaml</groupId>
<artifactId>snakeyaml</artifactId>
<version>2.0</version>
```
### 重现步骤
1. 使用 `snakeyaml.loadAs` 方法
2. 操作解析后的json
3. 1版本可以操作，结果(a,b)；2版本不行，结果只有(a)
```java
JSONArray array = new JSONArray();
array.add("a");
JSONObject object = new JSONObject();
object.put("array", array);
Yaml yaml = new Yaml();
JSONObject json = yaml.loadAs(new StringReader(object.toString()), JSONObject.class);
JSONArray res = json.getJSONArray("array");
res.add("b");
System.out.println(json.getJSONArray("array"));
```
### 期待的正确结果
2版本也可以操作（兼容1版本）

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.25-SNAPSHOT/
问题已修复，请帮忙用2.0.25-SNAPSHOT版本验证，2.0.25版本预计在3月中旬发布。
