### ISSUE TITLE
[QUESTION] is fastjson-extension support spring-webflux?

### ISSUE THREAD

**Issue by magical1989** [alibaba/fastjson2#1205]
```
var webClient = WebClient.builder()
                .codecs(configurer -> {
                    configurer.defaultCodecs().jackson2JsonDecoder(new Fastjson2Decoder());
                    configurer.defaultCodecs().jackson2JsonEncoder(new Fastjson2Encoder());
                });
```
Dear Wen,
the code snippets show how we used fastjson2 on spring 5+ in our project.
is there any functions can be supportted in fastjson2-extension-spring5/6 ?

**Comment by wenshao** [comment]
你能提交一个PR参与进来一起完善fastjson2么？

**Comment by magical1989** [comment]
> 这是一个很好的建议，也应该有这样的功能，你能提交一个PR参与进来一起完善fastjson2么？

非常感谢您的邀请，当前内部的版本还比较简易，可能还需要一些修订和测试用例，后续完善后我会尝试提交一个可用的PR。
再次感谢您的回复。

**Comment by wenshao** [comment]
代码已经合入主干

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
请用新版本
