### ISSUE TITLE
引入pom依赖报错

### ISSUE THREAD

**Issue by Yefeng888999** [alibaba/fastjson2#1221]
### 问题描述
*简要描述您碰到的问题。*
![image](https://user-images.githubusercontent.com/112799483/224201395-a4a64888-87f3-4cf3-9c8e-277ebfd06e0f.png)
在家使用没事,在公司从git上拉下来就报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息：1.8 [e.g.：Openjdk 1.8.0_312]
 - 版本信息：2.023[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by Yefeng888999** [comment]
![image](https://user-images.githubusercontent.com/112799483/224201841-ec1ff6cf-41d2-4404-9746-af74d6c25722.png)
换成最新的2.0.24就不报错了
这是咋回事啊?

**Comment by wenshao** [comment]
2.0.23的artifactId是fastjson2-extension-spring，2.0.24为了支持spring6，将两个分开了
