### ISSUE TITLE
[BUG]TypeReference 序列化在lamada表达式里无法返回正确对象

### ISSUE THREAD

**Issue by gougang** [alibaba/fastjson2#1222]
### 问题描述
* 使用TypeReference在lamada中始终返回Object类型，而不是TypeReference中指定的类型*

### 环境信息
*请填写以下信息：*

 - OS信息：MacBook Air  12.4 / 1.2 GHz 四核Intel Core i7 / 16 GB 3733 MHz LPDDR4X
 - JDK信息： java version "1.8.0_301"
 - 版本信息：fastjson 2.0.24
 

### 重现步骤
*如何操作可以重现该问题：*
静态编译就报错了。复制下面代码到idea就能复现。 

```java
 @Test
    public void testTypeRefence() {
        String text = "{\"businessLine\":5,\"ccId\":\"913440103290\",\"cardNo\":\"24000000039QWERR\"}";
        Map<String, String> users = JSONObject.parseObject(text, new TypeReference<HashMap<String, String>>() {
        });

        HashMap<String, String> users2 = Optional.ofNullable(text).map(t->JSONObject.parseObject(t, new TypeReference<HashMap<String, String>>() {
        })).orElse(new HashMap<>());
    }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出

Incompatible types. Found: 'java.lang.Object', required: 'java.util.Map<java.lang.String,java.lang.String>'

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
<img width="931" alt="image" src="https://user-images.githubusercontent.com/5705339/224276742-dbd6ff0b-e52a-4c73-b945-3418d202d415.png">

**Comment by wenshao** [comment]
```java
String text = "{\"businessLine\":5,\"ccId\":\"913440103290\",\"cardNo\":\"24000000039QWERR\"}";

HashMap<String, String> users2 = Optional
        .ofNullable(text)
        .map(
                t -> (HashMap<String, String>) JSONObject.parseObject(
                        t,
                        new TypeReference<HashMap<String, String>>() {}
                )
        ).orElse(new HashMap<>());

assertEquals("5", users2.get("businessLine"));
```
需要加一个强制类型转换，除此之外似乎没有好的办法

**Comment by gougang** [comment]
@wenshao

**Comment by gougang** [comment]
@wenshao 下面是1.2.69的代码，fastjson2 中能不能也帮我们默认强转一下

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/5705339/224594660-fd9044c3-fe92-47fe-89b4-0f878f8af8c9.png">

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
问题已修复，请用新版本
