### ISSUE TITLE
[BUG]JSON.register(java.util.Date.class, ObjectReader<java.util.Date>); 无法生效 

### ISSUE THREAD

**Issue by codefan** [alibaba/fastjson2#1227]
### 问题描述
#1225 题的问题，非常感谢快速修复了CST时区的问题，但是2.0.25依然没有解决
 JSON.register(java.util.Date.class, ObjectReader<java.util.Date>); 这个自定义ObjectReader 的问题

### 环境信息

OS信息： [e.g.：Windows 11 4Core 3.10GHz 16 GB]
JDK信息： [e.g.：Openjdk 1.8.0_301]
版本信息：[e.g.：Fastjson2 2.0.24]

### 重现步骤

        JSON.config(JSONReader.Feature.AllowUnQuotedFieldNames);

        JSON.register(java.util.Date.class, UtilDateSerializer.instance); // ObjectReader  **不生效**
        JSON.register(java.sql.Date.class, SqlDateSerializer.instance); // ObjectReader。可以
        JSON.register(java.sql.Timestamp.class, SqlTimestampSerializer.instance); // ObjectReader 可以

        JSON.register(java.util.Date.class, UtilDateDeserializer.instance); //ObjectWriter 可以
        JSON.register(java.sql.Date.class, SqlDateDeserializer.instance); //ObjectWriter  可以
        JSON.register(java.sql.Timestamp.class, SqlTimestampDeserializer.instance); //ObjectWriter 可以

JSON.register 注册ObjectReader 和 ObjectWriter 时，只有 java.util.Date.class,  ObjectReader  这一条不能生效。

### 期待的正确结果

使用自定义的 ObjectReader<java.util.Date> 对象。目的主要为了容错，因为我们获取的数据各种各样。

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by codefan** [comment]
{"sqlDate":"2021-11-11 12:12:12 CST","timestamp":"2023-03-13 09:41:16.404 CST","utilDate":"2020-12-31 00:00:00 CST"}
Exception in thread "main" java.time.zone.ZoneRulesException: Unknown time-zone ID: PST
	at java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:272)
	at java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:227)
	at java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.time.ZoneId.of(ZoneId.java:411)
	at java.time.ZoneId.of(ZoneId.java:359)
	at com.alibaba.fastjson2.util.DateUtils.getZoneId(DateUtils.java:3363)
	at com.alibaba.fastjson2.JSONReaderUTF16.readZonedDateTimeX(JSONReaderUTF16.java:6483)
	at com.alibaba.fastjson2.JSONReader.readMillisFromString(JSONReader.java:1225)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readDate(ObjectReaderImplDate.java:168)
	at com.alibaba.fastjson2.reader.ObjectReaderImplDate.readObject(ObjectReaderImplDate.java:70)
	at com.alibaba.fastjson2.reader.ORG_1_3_JsonWithDateField.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:642)
	at com.centit.support.test.TestJsonIO.main(TestJsonIO.java:67)

Process finished with exit code 1

**Comment by codefan** [comment]
谢谢！

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
请帮忙用2.0.26-SNAPSHOT版本验证，已经自动识别
```java
{"sqlDate":"2021-11-11 12:12:12 CST","timestamp":"2023-03-13 09:41:16.404 CST","utilDate":"2020-12-31 00:00:00 CST"}
```

**Comment by codefan** [comment]
测试还是没有通过，我看了您的更新 https://github.com/alibaba/fastjson2/commit/2837840c621098635834f51dc30f40db5a1b8baa

这个不是我想要的，我提的内容不是需要日期支持 CST、PST 等等时区， 而是要能够支持注册java.util.Date.class 类的自定义  ObjectReader 。

```
public class UtilDateDeserializer implements ObjectReader<java.util.Date> {

    @Override
    public java.util.Date readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {

        if (jsonReader.readIfNull()) {
            return null;
        }
       return DatetimeOpt.smartPraseDate(strVal); 
       //这个是我自己实现的日期格式分析器，
    }

}

**JSON.register(java.util.Date.class, UtilDateDeserializer.instance);** /*问题是这个注册是无法生效的，我debug无法进入上面的UtilDateDeserializer 类中。*/
```

**Comment by codefan** [comment]
JSON.register(java.sql.Date.class, SqlDateDeserializer.instance); //ObjectReader<java.sql.Date>
JSON.register(java.util.Date.class, UtilDateSerializer.instance); //ObjectWriter<java.util.Date>
奇怪的是上面两条都是可以生效的，唯独
**JSON.register(java.util.Date.class, UtilDateDeserializer.instance)**;//ObjectReader<java.util.Date>
不能生效。

**Comment by wenshao** [comment]
内置的日期解析做很多特别的优化，通常自定义日期反序列化不如内置的性能好，你自己实现日期解析器的需求是怎样的？

**Comment by codefan** [comment]
内置的日期解析 当然好，但是不一定能考虑到各种情况， 我觉得 JSON.register 这个设计非常棒，可以给使用的人员有一个替代的选择。 但是 JSON.register  不能注册 java.util.Date.class类型的解释器应该算一个缺陷。

我自己实现的日期解析器 更多的是考虑到项目上的需求， 比如 “7 ene 2023 03:33:31 GMT-8” 墨西哥的格式，还有 “Jan 1, 2023 6:15:03 p.m. PST” 太平洋时区的格式， 很多还是不规范的，比如 p.m. 。 这些有的不具有普遍意义，所以放在内置日期解析中不科学， 用这个JSON.register 注册个性化的解析器非常好。 现在把类型换成 java.sql.Date 是可以的。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
请帮忙用2.0.26-SNAPSHOT版本验证，已经支持java.util.Date类型的自定义反序列化

**Comment by codefan** [comment]
抱歉回复迟了。 经过测试已经可以正确注册了，非常感谢🙏

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
新版本已发布，请用新版本

**Comment by codefan** [comment]
收到，谢谢！
