### ISSUE TITLE
[BUG] 复杂对象类型在进行序列化和反序列化时会出现以下问题，望

### ISSUE THREAD

**Issue by mystox** [alibaba/fastjson2#1234]
### 问题描述
*简要描述您碰到的问题。*
在默认序列化和反序列化内置对象重复引用时，会出现以下问题：
![image](https://user-images.githubusercontent.com/18431419/225049604-1d6fecf8-9507-481b-a247-a8e2a9885e3a.png)
重复的数组对象引用似乎不能正常获取对象的引用位置$ref的引用似乎有点混乱，这个在以前版本应该是没有出现过的。
序列化后的文本如下：
{"page":1,"pageSize":9999,"queryCI":[{},{},{}],"queryRe":[{"point":1},{"$ref":"$.queryCI.queryRe[0]"}]}
如果实体的内容值越丰富似乎会越复杂
如：
{"page":1,"pageSize":9999,"queryCI":[{"nodeType":"CI","queryParam":[{"queryKey":"id","queryValue":["USTAR-POWER_ENV-BASE_STATION-35a0f61a-7fe5-4f19-a747-14be63d15a2c"],"unit":" in "}],"returnParam":[{"belong":"p","distinct":0,"group":0,"returnAlias":"roomRegionCode","returnKey":"SITE_LEVEL"}]},{"nodeType":"CI","queryParam":[{"queryKey":"type","queryValue":"OUTSIDE_CABINET","unit":" = "}]},{"nodeType":"CI","queryParam":[],"returnParam":[{"belong":"p","distinct":0,"group":0,"returnAlias":"name","returnKey":"NAME"},{"belong":"p","distinct":0,"group":0,"returnAlias":"type","returnKey":"type"},{"belong":"p","distinct":0,"group":0,"returnAlias":"ciId","returnKey":"id"},{"belong":"p","distinct":0,"group":0,"returnAlias":"serialNum","returnKey":"SERIAL_NUMBER"},{"belong":"p","distinct":0,"group":0,"returnAlias":"brand","returnKey":"BRAND"},{"belong":"p","distinct":0,"group":0,"returnAlias":"model","returnKey":"MODEL"},{"belong":"p","distinct":0,"group":0,"returnAlias":"lessee","returnKey":"THE_TENANT"}]}],"queryRe":[{"containYourself":true,"openDepth":false,"point":1,"reType":"RELATIONSHIP"},**{"$ref":"$.queryCI[0].queryParam[0][1][2].queryParam.queryRe[0]"}**]}

### 重现步骤
*如何操作可以重现该问题：*

1. 使用toJSONString后再parseObject相关类
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
public class FastjsonTest {
    public static void main(String[] args) {
        QueryDTO queryDTOFather = new QueryDTO();
        QueryDTO queryDTOOutDoor = new QueryDTO();
        QueryDTO queryDTOEquipment = new QueryDTO();
        RelationShipDTO relationShipDTO = new RelationShipDTO();
        relationShipDTO.setPoint(1);
//        AssetDTO assetDTO = new AssetDTO();
//        assetDTO.setQueryCI(Arrays.asList(queryDTOFather, queryDTOOutDoor, queryDTOEquipment));
//        assetDTO.setQueryRe(Arrays.asList(relationShipDTO,relationShipDTO));
        AssetDTO assetDTO = AssetDTO.BuilderQueryCI.startBuild()
                .queryCI(queryDTOFather).queryCI(queryDTOOutDoor).queryCI(queryDTOEquipment)
                .queryRe(relationShipDTO).queryRe(relationShipDTO)
                .page(1).pageSize(9999)
                .create();

        System.out.println(assetDTO);
        String x = JSONObject.toJSONString(assetDTO);
        System.out.println(x);
        AssetDTO assetDTO1 = JSONObject.parseObject(x, AssetDTO.class);
        System.out.println(assetDTO1);
    }
}

public class AssetDTO {

    private List<QueryDTO> queryCI;

    private List<RelationShipDTO> queryRe;

    private Integer page;

    private Integer pageSize;

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    public AssetDTO() {
    }

    private AssetDTO(BuilderQueryCI builderQueryCI) {
        this.queryCI =builderQueryCI.queryCI;
        this.queryRe = builderQueryCI.queryRe;
        this.page = builderQueryCI.page;
        this.pageSize = builderQueryCI.pageSize;
    }


    public List<QueryDTO> getQueryCI() {
        return queryCI;
    }

    public void setQueryCI(List<QueryDTO> queryCI) {
        this.queryCI = queryCI;
    }

    public List<RelationShipDTO> getQueryRe() {
        return queryRe;
    }

    public void setQueryRe(List<RelationShipDTO> queryRe) {
        this.queryRe = queryRe;
    }
    public static class BuilderQueryCI{
        private List<QueryDTO> queryCI;

        private List<RelationShipDTO> queryRe;

        private Integer page;

        private Integer pageSize;

        public AssetDTO create() {
            return new AssetDTO(this);
        }

        public BuilderQueryCI() {
        }

        public static BuilderQueryCI startBuild() {
            return new BuilderQueryCI();
        }


        public BuilderQueryCI queryCI(QueryDTO... queryDTO) {

            if(this.queryCI == null){
                this.queryCI = new ArrayList<>();
            }
            queryCI.addAll(Arrays.asList(queryDTO));
            return this;
        }
        public BuilderQueryCI queryRe(RelationShipDTO... relationShipDTO) {

            if(this.queryRe==null){
                this.queryRe = new ArrayList<>();
            }
            queryRe.addAll(Arrays.asList(relationShipDTO));
            return this;
        }


        public BuilderQueryCI page(Integer page) {
            this.page = page;
            return this;
        }


        public BuilderQueryCI pageSize(Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }
    }
}

public class RelationShipDTO {
    private Integer point;

    public Integer getPoint() {
        return point;
    }

    public void setPoint(Integer point) {
        this.point = point;
    }
}

public class QueryParam {
}


```

### 期待的正确结果
正确的序列化结果：
{"page":1,"pageSize":9999,"queryCI":[{},{},{}],"queryRe":[{"point":1},{"$ref":"$.queryRe[0]"}]}
正确反序列化结果应该能还原原来实例结构

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.26-SNAPSHOT/
问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证。

**Comment by mystox** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.26-SNAPSHOT/ 问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证。

已经修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
新版本已发布，请用新版本
