### ISSUE TITLE
fastjson2 有无实现 Record 计划

### ISSUE THREAD

**Issue by HowardLei** [alibaba/fastjson2#124]
在 JDK 17 中有的地方会使用 record 定义实体，但是现在实体类转 json 的时候仍然为空

**Comment by HowardLei** [comment]
请问温少有支持计划吗？

**Comment by wenshao** [comment]
有的，2.0.2要在明天发布，来不及做了。预计在5月底会发布2.0.3版本支持record

**Comment by wenshao** [comment]
已经支持，你可以用SNAPSHOT版本帮忙验证么？ 
SNAPSHOT版本地址： https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.3-SNAPSHOT/

**Comment by HowardLei** [comment]
> 已经支持，你可以用SNAPSHOT版本帮忙验证么？ SNAPSHOT版本地址： https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.3-SNAPSHOT/

好的温少，我去测试一下
