### ISSUE TITLE
[FEATURE]Feature.WriteBooleanAsNumber踩坑

### ISSUE THREAD

**Issue by jiangguilong2000** [alibaba/fastjson2#1241]
在用的过程中还是遇到了一个坑，记录如下，百度和google了一下，还没人遇到过？：
Feature.WriteBooleanAsNumber 通过字面意思为为true的序列化成1，为false的值序列化成0，
但 通过  

```java
JSON.toJSONString(message, Feature.WriteBooleanAsNumber);
```

 或者通过如下方式
```java
  @JSONField(serializeFeatures = Feature.WriteBooleanAsNumber)
    private boolean human;
    
    public boolean isHuman() {
        return human;
    }

    public void setHuman(boolean human) {
        this.human = human;
    }
```
都无效生成的结果还是true 或者false, 

那么，是否是isHuman出了问题呢，于是把isHuman改成getHuman,
```java
  @JSONField(serializeFeatures = Feature.WriteBooleanAsNumber)
    private boolean human;
    
    public boolean getHuman() {
        return human;
    }

    public void setHuman(boolean human) {
        this.human = human;
    }
```
发现结果还是不对.

会不会是包装类和基本类型的问题呢，于是改成如下：
```java
    @JSONField(serializeFeatures = Feature.WriteBooleanAsNumber)
    private Boolean human;

    public Boolean getHuman() {
        return human;
    }

    public void setHuman(Boolean human) {
        this.human = human;
    }
```
再次通过JSON.toJSONString(message); 发现还是无效，于是改成

```java
    private Boolean human;

    public Boolean getHuman() {
        return human;
    }

    public void setHuman(Boolean human) {
        this.human = human;
    }
```
JSON.toJSONString(message, Feature.WriteBooleanAsNumber); 结果符合预期：{"human":1}

这里有两个问题：
1:为什么基本类型boolean不给支持？
2:为什么通过@JSONField(serializeFeatures = Feature.WriteBooleanAsNumber) 这种方式就不行？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
问题已修复，请用新版本
