### ISSUE TITLE
[BUG]正常json对象，fastjson1能序列化，fastjson2报nullpoint

### ISSUE THREAD

**Issue by waterif** [alibaba/fastjson2#1242]
### 问题描述
正常json对象，fastjson1能序列化，fastjson2报nullpoint

### 环境信息

 - OS信息：  window10 4Core 2.2GHz 16 GB
 - JDK信息： 1.8.0_101
 - 版本信息：Fastjson2 2.0.23
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 JSON.toJSONString(object) 方法
2. 输入 java对象， 数据内容如下：
{
		"legend": ["数据1", "数据2", "数据3", "数据4"],
		"series": [{
				"data": [1002, 2166, 2399, 2576, 2391, 2294, 2623, 3145, 3109, 2927, 1935, 986, 429, 219, 167, 282, 493, 977, 1528, 2024, 2267, 2128, 2395, 2261, 2454, 2566, 2427, 2858, 2392, 2723, 3008, 3429, 3522, 3384, 2335, 1158, 514, 413, 280, 275, 666, 1201, 1597, 2262, 2738, 2641, 3054, 3203, 2917, 2791, 2876, 3095, 2788, 3244, 3040, 3444, 3534, 2856, 2087, 1130, 679, 339, 374, 439, 573, 932, 1724, 1841, 2124, 2328, 2307, 2300, 2122, 2327, 2557, 2765, 3045, 2550, 2763, 2446, 2497, 2337, 1590, 836, 448, 207, 185, 174, 456, 599, 1103, 1200, 1254, 1558, 1780, 1543, 1779, 1677, 1639, 1783, 1675, 1776, 1898, 2044, 2274, 1879, 1328, 909, 384, 261, 280, 215, 438, 607, 1143, 1305, 2041, 2205, 2060, 2224, 2473, 2568, 2481, 2289, 2298, 2498, 2988, 3106, 3284, 2803, 1457, 961, 407, 419, 271, 316, 489, 1191, 1785, 2261, 2497, 2559, 2574, 2991, 2582, 2514, 2824, 2746, 2289, 3241, 3187, 3182, 3582, 3224, 1941, 1076, 501, 287, 383, 272, 566, 1287, 1710, 2005, 2528, 2230, 2256, 2471, 1529],
				"name": "数据1",
				"type": "line"
			}, {
				"data": [808, 2128, 2187, 2573, 2902, 2616, 2384, 3056, 3116, 2801, 2171, 1139, 526, 445, 266, 329, 438, 912, 1395, 2454, 2219, 2481, 2819, 2457, 2440, 2436, 2816, 2486, 2883, 3201, 3275, 3757, 4112, 3995, 3041, 1295, 730, 302, 388, 492, 693, 1025, 1887, 2369, 3024, 3574, 3392, 3402, 3115, 3545, 3616, 3873, 4097, 3604, 3753, 3743, 3747, 3350, 2897, 1452, 992, 658, 379, 531, 537, 908, 1777, 2098, 2502, 3183, 2723, 2468, 2862, 3245, 3441, 3411, 3076, 3180, 2951, 3359, 3441, 2278, 1926, 1153, 764, 245, 364, 375, 363, 670, 880, 1059, 1590, 2232, 1697, 2104, 1835, 1819, 1776, 1761, 1920, 2368, 2076, 2296, 2524, 2230, 1405, 682, 452, 342, 246, 327, 355, 572, 976, 1545, 1710, 2051, 2090, 2122, 2266, 2585, 2705, 2542, 2599, 3093, 2532, 2619, 3175, 2794, 1865, 1056, 350, 332, 327, 313, 364, 853, 1234, 3039, 2629, 2611, 2241, 2401, 2559, 2263, 2703, 2517, 2855, 2633, 2432, 2837, 3043, 2952, 1874, 1240, 631, 249, 242, 251, 428, 930, 1240, 1656, 2037, 2329, 2116, 2616, 1569],
				"name": "数据2",
				"type": "line"
			}
		],
		"xAxis": ["2023030814", "2023030815", "2023030816", "2023030817", "2023030818", "2023030819", "2023030820", "2023030821", "2023030822", "2023030823", "2023030900", "2023030901", "2023030902", "2023030903", "2023030904", "2023030905", "2023030906", "2023030907", "2023030908", "2023030909", "2023030910", "2023030911", "2023030912", "2023030913", "2023030914", "2023030915", "2023030916", "2023030917", "2023030918", "2023030919", "2023030920", "2023030921", "2023030922", "2023030923", "2023031000", "2023031001", "2023031002", "2023031003", "2023031004", "2023031005", "2023031006", "2023031007", "2023031008", "2023031009", "2023031010", "2023031011", "2023031012", "2023031013", "2023031014", "2023031015", "2023031016", "2023031017", "2023031018", "2023031019", "2023031020", "2023031021", "2023031022", "2023031023", "2023031100", "2023031101", "2023031102", "2023031103", "2023031104", "2023031105", "2023031106", "2023031107", "2023031108", "2023031109", "2023031110", "2023031111", "2023031112", "2023031113", "2023031114", "2023031115", "2023031116", "2023031117", "2023031118", "2023031119", "2023031120", "2023031121", "2023031122", "2023031123", "2023031200", "2023031201", "2023031202", "2023031203", "2023031204", "2023031205", "2023031206", "2023031207", "2023031208", "2023031209", "2023031210", "2023031211", "2023031212", "2023031213", "2023031214", "2023031215", "2023031216", "2023031217", "2023031218", "2023031219", "2023031220", "2023031221", "2023031222", "2023031223", "2023031300", "2023031301", "2023031302", "2023031303", "2023031304", "2023031305", "2023031306", "2023031307", "2023031308", "2023031309", "2023031310", "2023031311", "2023031312", "2023031313", "2023031314", "2023031315", "2023031316", "2023031317", "2023031318", "2023031319", "2023031320", "2023031321", "2023031322", "2023031323", "2023031400", "2023031401", "2023031402", "2023031403", "2023031404", "2023031405", "2023031406", "2023031407", "2023031408", "2023031409", "2023031410", "2023031411", "2023031412", "2023031413", "2023031414", "2023031415", "2023031416", "2023031417", "2023031418", "2023031419", "2023031420", "2023031421", "2023031422", "2023031423", "2023031500", "2023031501", "2023031502", "2023031503", "2023031504", "2023031505", "2023031506", "2023031507", "2023031508", "2023031509", "2023031510", "2023031511", "2023031512", "2023031513", "2023031514"]
	}

3. 出现 `NullPointException` 错误，如下图：
![image](https://user-images.githubusercontent.com/8745968/225520526-8f0b87e1-275b-4ba7-8e64-65cd639dc51e.png)

### 期待的正确结果
能正常序列化json数据

### 相关日志输出
Exception in thread "main" com.alibaba.fastjson.JSONException: toJSONString error
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1481)
	at com.ly.member.Test.main(Test.java:77)
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.JSONWriter.setPath(JSONWriter.java:200)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:223)
	at com.alibaba.fastjson2.writer.OWG_1_4_WelfareSendingReportVo.write(Unknown Source)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1473)
	... 1 more

#### 附加信息
fastjson1可以正常序列化，fastjson2.0.23出现nullpoint异常；
尝试调整java对象，将series中的data的长度减少到一定程度后，fastjson2.0.23也能正常徐序列化；

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证

**Comment by waterif** [comment]
2.0.26-SNAPSHOT版本： 验证通过。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
新版本已发布，请用新版本
