### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skiray** [alibaba/fastjson2#1246]
### 问题描述
源实体类属性值是大写，序列化的时候key变成了小写，1.x是正常的，2.x是小写;
并且属性名称是单个字母加数字如：P2，@JSONField(name="") 也不生效

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：MacBook Pro (13-inch, M1, 2020)]
 - JDK信息： [e.g.：Openjdk 11.02]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
{"age":"22","name":"xiaom","aaa":"asda"}
{"age":"22","name":"xiaom","P2":"asda"}

### 相关日志输出
{"age":"22","name":"xiaom","p2":"asda"}

#### 附加信息

![image](https://user-images.githubusercontent.com/37934352/225603527-140a6c09-1892-420d-b261-798383887fff.png)

![image](https://user-images.githubusercontent.com/37934352/225603569-b458eccf-97b2-4bb3-bc18-17db84d00c16.png)

换多字母名称可，好像跟getter、setter名称有关
![image](https://user-images.githubusercontent.com/37934352/225603863-05076ad4-6407-454f-a852-ccff5c966a79.png)

**Comment by skiray** [comment]
![image](https://user-images.githubusercontent.com/37934352/225604564-65d9d941-1329-4ad4-9a57-a1d478be72e9.png)

**Comment by skiray** [comment]
1.x是正常的大写

**Comment by skiray** [comment]
![image](https://user-images.githubusercontent.com/37934352/225625475-7ccf104c-9673-45a0-a92e-1c3d5f670fa8.png)
当属性值是private时，transient 与JSONField均无效;应该是用了getter  setter方法。
当属性值是public ,一切正常，看起来不是bug总感觉管怪怪的当private transient String xxx；

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.26-SNAPSHOT/
问题已经修复，请帮忙用2.0.26-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.26
问题已修复，请用新版本
