### ISSUE TITLE
Feature.WriteNonStringValueAsString测试

### ISSUE THREAD

**Issue by MASON-PRINCE** [alibaba/fastjson2#125]
public class NonStringTest {

    @Test
    public void writeNonStringValueAsStringTest() {
        People people = new People();
        people.setAge(20);
        people.setAdult(true);
        people.setWeight(145.5);
        String peopleStr = JSON.toJSONString(people, JSONWriter.Feature.WriteNonStringValueAsString);
        JSONObject jsonObj = JSON.parseObject(peopleStr);
        assertTrue (jsonObj.get("age") instanceof String);
        assertTrue (jsonObj.get("adult") instanceof String);
        assertTrue (jsonObj.get("weight") instanceof String);
    }

    @Data
    public static class People {
        public int age;
        public boolean adult;
        public double weight;
    }
}

**Comment by MASON-PRINCE** [comment]
issue120中 JSON.toJSONString中使用JSONWriter.Feature.WriteNonStringValueAsString属性对double和boolean不生效，只能吧int转换为String的测试类

**Comment by wenshao** [comment]
已经支持，你更新快照试试看

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
