### ISSUE TITLE
[FEATURE]能不能在jsonobject和jsonarry上加上带有为null取默认值的方法，比如getDateOrDefault(keyName,defaultValue)这样的

### ISSUE THREAD

**Issue by GeYiPeng** [alibaba/fastjson2#1252]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*
能不能在jsonobject和jsonarray上加上带有默认值得获取方法，比如getDateOrDefault(keyName,defaultValue)这样的，或者直接重载getDate(keyName,defaultValue)
现有的只有一个getOrDefault方法返回的是一个object很多时候无法直接使用，而且例如getInteger这样的会对一些常见类型自动转换比如字符串“111”转成int的111，尤其是getDate这个方法，现在可以将json中有个key:"2023/3/19 18:56:02"直接转成Date，getOrDefault貌似不行，有个getDateOrDefault("key",new Date())不是会方便很多吗

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*
替代方案的话在hutool的json，apache camel的json中都有类似的方法
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
可以的啊，你可以提交一个PR参与捡来么？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
请用新版本
