### ISSUE TITLE
[BUG] 集成openapi有误，参考#387

### ISSUE THREAD

**Issue by towangle** [alibaba/fastjson2#1256]
### 问题描述
*简要描述您碰到的问题。*
springboot3.0.4 ,openapi 2.0.4, 无法正常使用
类似原问题
https://github.com/alibaba/fastjson2/issues/387

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win10 ]
 - JDK信息： [e.g.：Openjdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.26]
 

### 重现步骤
*如何操作可以重现该问题：*

1.使用jackson作为消息转换器，正常使用：
![image](https://user-images.githubusercontent.com/17812692/226542864-aecfb08e-c50f-45f1-9fe4-7865b99194d7.png)

2.使用fastjson2 作为消息转换器，接口返回异常：
![image](https://user-images.githubusercontent.com/17812692/226542185-f0ade0a2-e8a4-4714-87ab-7ffb196837b2.png)
![image](https://user-images.githubusercontent.com/17812692/226542365-f06d4a5b-b4b0-4173-b954-4acd5a907df6.png)
![image](https://user-images.githubusercontent.com/17812692/226542434-af360132-07ca-41cf-8c32-cfe11c81ff4f.png)

返回header无Content-Length 。手工设置无用。

该版本内，无任何有关openapi的处理，
![image](https://user-images.githubusercontent.com/17812692/226543255-1f10e8af-d6d1-4282-96be-cdd5417b249c.png)

https://github.com/alibaba/fastjson2/blob/32a4f418208a859dea324e2bac6570bad9f6ce3b/extension-spring5/src/test/java/com/alibaba/fastjson2/springdoc/OpenApiJsonWriterTest.java
测试类没看懂
![image](https://user-images.githubusercontent.com/17812692/226543439-08e165a8-01ba-4ddc-9acf-af11094cb38e.png)
#387 修复没看懂

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
#387 说2.0.6修复，现在版本2.0.26，期望处理。

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
@towangle 我不是很熟悉Swagger，需要些时间学习才能处理

**Comment by YangLiCcc** [comment]
> @towangle 我不是很熟悉Swagger，需要些时间学习才能处理

这个问题类似 [#387](https://github.com/alibaba/fastjson2/issues/387)，是同时使用 FastJsonHttpMessageConverter 和 springdoc-openapi 出现的。

springdoc 需要的好像是 String 类型，但是被FastJsonHttpMessageConverter特殊处理之后就不行了...

提供一下我使用的依赖：

<img width="663" alt="image" src="https://user-images.githubusercontent.com/65808963/227457430-d9fe441a-be10-46dc-9390-ae13d3ab9281.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/65808963/227457551-a7041a2c-4ae1-402b-8756-8e0b69a53251.png">

MessageConverter：

<img width="841" alt="image" src="https://user-images.githubusercontent.com/65808963/227457773-c1ef5e1b-ee72-40cf-a296-779cb7faad70.png">

同样，最后访问 springdoc 是如下错误：
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/65808963/227458113-b0f3a55d-e413-45e0-b14b-f6b3afeb0b5d.png">

**Comment by Merely-chao** [comment]
@towangle 可以试试 
`      
//converters.add(0,converter);
        converters.add(new ByteArrayHttpMessageConverter());
        converters.add(converter);
`

**Comment by telechow** [comment]
@towangle  @wenshao 
这个问题，我昨天也遇到了。说一下我的解决方法及思路，希望是正确的。

我的版本是

```xml
<properties>
        <java.version>17</java.version>
		<spring-boot.version>3.0.4</spring-boot.version>
		<!--fastjson2-->
		<fastjson2.version>2.0.26</fastjson2.version>
		<!--openapi-->
		<springdoc-openapi-starter-webmvc-ui.version>2.0.4</springdoc-openapi-starter-webmvc-ui.version>
</properties>


<dependencies>
			<!--fastjson2-->
			<dependency>
				<groupId>com.alibaba.fastjson2</groupId>
				<artifactId>fastjson2-extension-spring6</artifactId>
				<version>${fastjson2.version}</version>
			</dependency>

			<!--接口文档-->
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
				<version>${springdoc-openapi-starter-webmvc-ui.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-common</artifactId>
				<version>${springdoc-openapi-starter-webmvc-ui.version}</version>
			</dependency>
</dependencies>
```

和你的一样，都是最新的。



然后按照fastjson2的推荐配置

```java
@Configuration
@EnableWebMvc
public class WebMvcConfigurer extends WebMvcConfigurerAdapter {

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
        //自定义配置...
        FastJsonConfig config = new FastJsonConfig();
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
        config.setWriterFeatures(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat);
        converter.setFastJsonConfig(config);
        converter.setDefaultCharset(StandardCharsets.UTF_8);
        converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
        converters.add(0, converter);
    }
}
```

注意这里有一个@EnableWebMvc注解，有没有这个注解，很不一样。

- 当有这个注解时，`converters`将会被覆盖，执行完此方法之后只有`FastJsonHttpMessageConverter`这一个转换器。

- 当没有这个注解时，我们打个断点看下，有很多个转换器
  
  ![2023-03-31-11-18-49-image](https://user-images.githubusercontent.com/9656433/229019880-cc40dc5a-65d4-4b6a-9dfa-7cf57cb5f5d0.png)
  
  且`FastJsonHttpMessageConverter`被放在最前面，如果fastjson的转换器能够处理就会先处理了。
  
  

接下来，我们找到`openapi`的`api-docs`的`controller`，`org.springdoc.webmvc.api.OpenApiWebMvcResource`

![2023-03-31-11-21-25-image](https://user-images.githubusercontent.com/9656433/229019986-0bf61a9d-9a07-425e-a4ae-68556f5f7bda.png)

它的响应是一个字节数组，且强制指定了MediaType。



然后我们再看看`FastJsonHttpMessageConverter`的源码的关键方法。

![2023-03-31-11-23-54-image](https://user-images.githubusercontent.com/9656433/229020022-6ee492f9-128c-425e-8855-922c6601fac6.png)

可以看到并没有对字节数组类型的响应做特殊处理，直接`JSON.writeTo`写到`HttpOutputMessage`的`body`中了。



那么，我现在想到有两种解法。

1. 配置的时候，不要加上`@EnableWebMvc`注解，并且将`FastJsonHttpMessageConverter`放在`ByteArrayHttpMessageConverter`之后  
   
   对响应的类型为`byte[]`的控制器，先交给`ByteArrayHttpMessageConverter`处理，那么`FastJsonHttpMessageConverter`就不会去处理了。
   
   ```java
   //@EnableWebMvc
   @Configuration
   @RequiredArgsConstructor(onConstructor_ = @Autowired)
   public class Fastjson2WebMvcConfigurer implements WebMvcConfigurer {
   
       private final FastJsonConfig fastJsonConfig;
   
       @Override
       public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
           FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
           converter.setFastJsonConfig(fastJsonConfig);
           //2.设置字符集为UTF8
           converter.setDefaultCharset(StandardCharsets.UTF_8);
           //3.设置支持的MediaType为application/json
           converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
           converters.add(1, converter);
       }
   
       @Override
       public void configureViewResolvers(ViewResolverRegistry registry) {
           FastJsonJsonView fastJsonJsonView = new FastJsonJsonView();
           //1.使用io.github.telechow.garoupa.config.fastjson2.Fastjson2Configuration中的配置
           fastJsonJsonView.setFastJsonConfig(fastJsonConfig);
           registry.enableContentNegotiation(fastJsonJsonView);
       }
   }
   ```

    这种方法的缺点是，`converters.add(1, converter);`这句里面有个魔法值，而且我也不确定`ByteArrayHttpMessageConverter`会不会每次都在`converters`最前面。

2. `@EnableWebMvc`注解随便有没有，继承`FastJsonHttpMessageConverter`，并重写`writeInternal`方法，仅仅对`byte[]`类型做了一下处理
   
   ```java
   public class CustomFastJsonHttpMessageConverter extends FastJsonHttpMessageConverter {
   
       private FastJsonConfig config = new FastJsonConfig();
   
       /**
        * @return the fastJsonConfig.
        */
       public FastJsonConfig getFastJsonConfig() {
           return config;
       }
   
       /**
        * @param fastJsonConfig the fastJsonConfig to set.
        */
       public void setFastJsonConfig(FastJsonConfig fastJsonConfig) {
           this.config = fastJsonConfig;
       }
   
       @Override
       protected void writeInternal(Object object, HttpOutputMessage outputMessage) throws IOException, HttpMessageNotWritableException {
           HttpHeaders headers = outputMessage.getHeaders();
   
           try {
               int contentLength;
   
               //我用的jdk17，这里是instanceof模式匹配语法，jdk8没有的，自己强转一下object
               if(object instanceof byte[] bytes){
                   contentLength = bytes.length;
                   outputMessage.getBody().write(bytes, 0, bytes.length);
               }
               else if (object instanceof String && JSON.isValidObject((String) object)) {
                   byte[] strBytes = ((String) object).getBytes(config.getCharset());
                   contentLength = strBytes.length;
                   outputMessage.getBody().write(strBytes, 0, strBytes.length);
               } else {
                   contentLength = JSON.writeTo(
                           outputMessage.getBody(),
                           object, config.getDateFormat(),
                           config.getWriterFilters(),
                           config.getWriterFeatures()
                   );
               }
   
               if (headers.getContentLength() < 0 && config.isWriteContentLength()) {
                   headers.setContentLength(contentLength);
               }
           } catch (JSONException ex) {
               throw new HttpMessageNotWritableException("Could not write JSON: " + ex.getMessage(), ex);
           } catch (IOException ex) {
               throw new HttpMessageNotWritableException("I/O error while writing output message", ex);
           }
       }
   }
   ```
   
   然后，配置文件
   
   ```java
       @Override
       public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
           CustomFastJsonHttpMessageConverter converter = new CustomFastJsonHttpMessageConverter();
           converter.setFastJsonConfig(fastJsonConfig);
           //2.设置字符集为UTF8
           converter.setDefaultCharset(StandardCharsets.UTF_8);
           //3.设置支持的MediaType为application/json
           converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
           converters.add(0, converter);
       }
   ```



我们还可以再多思考一些，fastjson2是不是对所有的`byte[]`类型的响应处理起来都有问题呢？

一般情况下，我们是不会像openapi这样响应一个`byte[]`，又强制指定`MeidaType`为`application/json`的。这种写法，比较少见。

![2023-03-31-11-53-23-image](https://user-images.githubusercontent.com/9656433/229020076-445e1bde-964b-441d-a60a-1af3ee8dfee7.png)

1. 我们保持fastjson2的推荐配置，并写个简单的controller试试看

```java
@Configuration
@EnableWebMvc
public class WebMvcConfigurer extends WebMvcConfigurerAdapter {

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
        //自定义配置...
        FastJsonConfig config = new FastJsonConfig();
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
        config.setWriterFeatures(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat);
        converter.setFastJsonConfig(config);
        converter.setDefaultCharset(StandardCharsets.UTF_8);
        converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
        converters.add(0, converter);
    }
}
```

```java
/**
 * 首页 控制器
 *
 * @author Telechow
 * @since 2023/1/30 15:24
 */
@RestController
@RequestMapping("/index")
@RequiredArgsConstructor(onConstructor_ = @Autowired)
public class IndexController {

	private final IIndexService indexService;

	/**
	 * 展示首页
	 *
	 * @param text 前端说的话
	 * @return byte[] 首页的一句话
	 * @author Telechow
	 * @since 2023/1/30 15:27
	 */
	@GetMapping(value = "/show")
//	@GetMapping(value = "/show", produces = MediaType.APPLICATION_JSON_VALUE)
	public byte[] show(@RequestParam(name = "text") String text) {
		String show = indexService.show(text);
		return show.getBytes(StandardCharsets.UTF_8);
	}
}
```

结果是不论我们`@GetMapping`是否强制指定`MediaType`，响应都不符合预期。

![2023-03-31-12-11-30-image](https://user-images.githubusercontent.com/9656433/229020907-bb3da9f6-42d3-4e05-8cb9-93442f39cbe4.png)

因为`@RestController`会把`MediaType`设置为`application/json`，此控制器的`byte[]`响应会被`FastJsonHttpMessageConverter`处理



2. 我们把`@RestController`换成`@Controller`，`@GetMapping`不指定`MediaType`
   
   结果是会抛异常
   
   ![2023-03-31-11-51-56-image](https://user-images.githubusercontent.com/9656433/229020156-65b5c18d-96e9-488f-8af4-ee0bdc3857f0.png)

因为`FastJsonHttpMessageConverter`配置了`converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));`只支持`application/json`,而`@Controller`和`@GetMapping`都没有将`MediaType`设置为`application/json`。

且使用了`@EnableWebMvc`导致，转换器只有一个，没有任何转换器能够处理，所以抛异常了。

3. 我们使用我的两种解法中的任意一种
   
   发现可以正常得到结果。因为我们可以在`MediaType`为`application/json`的情况下，去处理`byte[]`类型的响应了。


---


最后推销一下自己，辞职一个月了，最近在找工作。等一个有缘人内推。我的邮箱`laughho@qq.com`。

**Comment by TsukasaHwan** [comment]
> @towangle @wenshao 这个问题，我昨天也遇到了。说一下我的解决方法及思路，希望是正确的。
> 
> 我的版本是
> 
> ```
> <properties>
>         <java.version>17</java.version>
> 		<spring-boot.version>3.0.4</spring-boot.version>
> 		
> 		<fastjson2.version>2.0.26</fastjson2.version>
> 		
> 		<springdoc-openapi-starter-webmvc-ui.version>2.0.4</springdoc-openapi-starter-webmvc-ui.version>
> </properties>
> 
> 
> <dependencies>
> 			
> 			<dependency>
> 				<groupId>com.alibaba.fastjson2</groupId>
> 				<artifactId>fastjson2-extension-spring6</artifactId>
> 				<version>${fastjson2.version}</version>
> 			</dependency>
> 
> 			
> 			<dependency>
> 				<groupId>org.springdoc</groupId>
> 				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
> 				<version>${springdoc-openapi-starter-webmvc-ui.version}</version>
> 			</dependency>
> 			<dependency>
> 				<groupId>org.springdoc</groupId>
> 				<artifactId>springdoc-openapi-starter-common</artifactId>
> 				<version>${springdoc-openapi-starter-webmvc-ui.version}</version>
> 			</dependency>
> </dependencies>
> ```
> 
> 和你的一样，都是最新的。
> 
> 然后按照fastjson2的推荐配置
> 
> ```java
> @Configuration
> @EnableWebMvc
> public class WebMvcConfigurer extends WebMvcConfigurerAdapter {
> 
>     @Override
>     public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
>         FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
>         //自定义配置...
>         FastJsonConfig config = new FastJsonConfig();
>         config.setDateFormat("yyyy-MM-dd HH:mm:ss");
>         config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
>         config.setWriterFeatures(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat);
>         converter.setFastJsonConfig(config);
>         converter.setDefaultCharset(StandardCharsets.UTF_8);
>         converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
>         converters.add(0, converter);
>     }
> }
> ```
> 
> 注意这里有一个@EnableWebMvc注解，有没有这个注解，很不一样。
> 
> * 当有这个注解时，`converters`将会被覆盖，执行完此方法之后只有`FastJsonHttpMessageConverter`这一个转换器。
> * 当没有这个注解时，我们打个断点看下，有很多个转换器
>   ![2023-03-31-11-18-49-image](https://user-images.githubusercontent.com/9656433/229019880-cc40dc5a-65d4-4b6a-9dfa-7cf57cb5f5d0.png)
>   且`FastJsonHttpMessageConverter`被放在最前面，如果fastjson的转换器能够处理就会先处理了。
> 
> 接下来，我们找到`openapi`的`api-docs`的`controller`，`org.springdoc.webmvc.api.OpenApiWebMvcResource`
> 
> ![2023-03-31-11-21-25-image](https://user-images.githubusercontent.com/9656433/229019986-0bf61a9d-9a07-425e-a4ae-68556f5f7bda.png)
> 
> 它的响应是一个字节数组，且强制指定了MediaType。
> 
> 然后我们再看看`FastJsonHttpMessageConverter`的源码的关键方法。
> 
> ![2023-03-31-11-23-54-image](https://user-images.githubusercontent.com/9656433/229020022-6ee492f9-128c-425e-8855-922c6601fac6.png)
> 
> 可以看到并没有对字节数组类型的响应做特殊处理，直接`JSON.writeTo`写到`HttpOutputMessage`的`body`中了。
> 
> 那么，我现在想到有两种解法。
> 
> 1. 配置的时候，不要加上`@EnableWebMvc`注解，并且将`FastJsonHttpMessageConverter`放在`ByteArrayHttpMessageConverter`之后
>    对响应的类型为`byte[]`的控制器，先交给`ByteArrayHttpMessageConverter`处理，那么`FastJsonHttpMessageConverter`就不会去处理了。
>    ```java
>    //@EnableWebMvc
>    @Configuration
>    @RequiredArgsConstructor(onConstructor_ = @Autowired)
>    public class Fastjson2WebMvcConfigurer implements WebMvcConfigurer {
>    
>        private final FastJsonConfig fastJsonConfig;
>    
>        @Override
>        public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
>            FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
>            converter.setFastJsonConfig(fastJsonConfig);
>            //2.设置字符集为UTF8
>            converter.setDefaultCharset(StandardCharsets.UTF_8);
>            //3.设置支持的MediaType为application/json
>            converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
>            converters.add(1, converter);
>        }
>    
>        @Override
>        public void configureViewResolvers(ViewResolverRegistry registry) {
>            FastJsonJsonView fastJsonJsonView = new FastJsonJsonView();
>            //1.使用io.github.telechow.garoupa.config.fastjson2.Fastjson2Configuration中的配置
>            fastJsonJsonView.setFastJsonConfig(fastJsonConfig);
>            registry.enableContentNegotiation(fastJsonJsonView);
>        }
>    }
>    ```
> 
>     这种方法的缺点是，`converters.add(1, converter);`这句里面有个魔法值，而且我也不确定`ByteArrayHttpMessageConverter`会不会每次都在`converters`最前面。
> 
> 2. `@EnableWebMvc`注解随便有没有，继承`FastJsonHttpMessageConverter`，并重写`writeInternal`方法，仅仅对`byte[]`类型做了一下处理
>    ```java
>    public class CustomFastJsonHttpMessageConverter extends FastJsonHttpMessageConverter {
>    
>        private FastJsonConfig config = new FastJsonConfig();
>    
>        /**
>         * @return the fastJsonConfig.
>         */
>        public FastJsonConfig getFastJsonConfig() {
>            return config;
>        }
>    
>        /**
>         * @param fastJsonConfig the fastJsonConfig to set.
>         */
>        public void setFastJsonConfig(FastJsonConfig fastJsonConfig) {
>            this.config = fastJsonConfig;
>        }
>    
>        @Override
>        protected void writeInternal(Object object, HttpOutputMessage outputMessage) throws IOException, HttpMessageNotWritableException {
>            HttpHeaders headers = outputMessage.getHeaders();
>    
>            try {
>                int contentLength;
>    
>                //我用的jdk17，这里是instanceof模式匹配语法，jdk8没有的，自己强转一下object
>                if(object instanceof byte[] bytes){
>                    contentLength = bytes.length;
>                    outputMessage.getBody().write(bytes, 0, bytes.length);
>                }
>                else if (object instanceof String && JSON.isValidObject((String) object)) {
>                    byte[] strBytes = ((String) object).getBytes(config.getCharset());
>                    contentLength = strBytes.length;
>                    outputMessage.getBody().write(strBytes, 0, strBytes.length);
>                } else {
>                    contentLength = JSON.writeTo(
>                            outputMessage.getBody(),
>                            object, config.getDateFormat(),
>                            config.getWriterFilters(),
>                            config.getWriterFeatures()
>                    );
>                }
>    
>                if (headers.getContentLength() < 0 && config.isWriteContentLength()) {
>                    headers.setContentLength(contentLength);
>                }
>            } catch (JSONException ex) {
>                throw new HttpMessageNotWritableException("Could not write JSON: " + ex.getMessage(), ex);
>            } catch (IOException ex) {
>                throw new HttpMessageNotWritableException("I/O error while writing output message", ex);
>            }
>        }
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    然后，配置文件
>    ```java
>        @Override
>        public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
>            CustomFastJsonHttpMessageConverter converter = new CustomFastJsonHttpMessageConverter();
>            converter.setFastJsonConfig(fastJsonConfig);
>            //2.设置字符集为UTF8
>            converter.setDefaultCharset(StandardCharsets.UTF_8);
>            //3.设置支持的MediaType为application/json
>            converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
>            converters.add(0, converter);
>        }
>    ```
> 
> 我们还可以再多思考一些，fastjson2是不是对所有的`byte[]`类型的响应处理起来都有问题呢？
> 
> 一般情况下，我们是不会像openapi这样响应一个`byte[]`，又强制指定`MeidaType`为`application/json`的。这种写法，比较少见。
> 
> ![2023-03-31-11-53-23-image](https://user-images.githubusercontent.com/9656433/229020076-445e1bde-964b-441d-a60a-1af3ee8dfee7.png)
> 
> 1. 我们保持fastjson2的推荐配置，并写个简单的controller试试看
> 
> ```java
> @Configuration
> @EnableWebMvc
> public class WebMvcConfigurer extends WebMvcConfigurerAdapter {
> 
>     @Override
>     public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
>         FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
>         //自定义配置...
>         FastJsonConfig config = new FastJsonConfig();
>         config.setDateFormat("yyyy-MM-dd HH:mm:ss");
>         config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
>         config.setWriterFeatures(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat);
>         converter.setFastJsonConfig(config);
>         converter.setDefaultCharset(StandardCharsets.UTF_8);
>         converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));
>         converters.add(0, converter);
>     }
> }
> ```
> 
> ```java
> /**
>  * 首页 控制器
>  *
>  * @author Telechow
>  * @since 2023/1/30 15:24
>  */
> @RestController
> @RequestMapping("/index")
> @RequiredArgsConstructor(onConstructor_ = @Autowired)
> public class IndexController {
> 
> 	private final IIndexService indexService;
> 
> 	/**
> 	 * 展示首页
> 	 *
> 	 * @param text 前端说的话
> 	 * @return byte[] 首页的一句话
> 	 * @author Telechow
> 	 * @since 2023/1/30 15:27
> 	 */
> 	@GetMapping(value = "/show")
> //	@GetMapping(value = "/show", produces = MediaType.APPLICATION_JSON_VALUE)
> 	public byte[] show(@RequestParam(name = "text") String text) {
> 		String show = indexService.show(text);
> 		return show.getBytes(StandardCharsets.UTF_8);
> 	}
> }
> ```
> 
> 结果是不论我们`@GetMapping`是否强制指定`MediaType`，响应都不符合预期。
> 
> ![2023-03-31-12-11-30-image](https://user-images.githubusercontent.com/9656433/229020907-bb3da9f6-42d3-4e05-8cb9-93442f39cbe4.png)
> 
> 因为`@RestController`会把`MediaType`设置为`application/json`，此控制器的`byte[]`响应会被`FastJsonHttpMessageConverter`处理
> 
> 2. 我们把`@RestController`换成`@Controller`，`@GetMapping`不指定`MediaType`
>    结果是会抛异常
>    ![2023-03-31-11-51-56-image](https://user-images.githubusercontent.com/9656433/229020156-65b5c18d-96e9-488f-8af4-ee0bdc3857f0.png)
> 
> 因为`FastJsonHttpMessageConverter`配置了`converter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));`只支持`application/json`,而`@Controller`和`@GetMapping`都没有将`MediaType`设置为`application/json`。
> 
> 且使用了`@EnableWebMvc`导致，转换器只有一个，没有任何转换器能够处理，所以抛异常了。
> 
> 3. 我们使用我的两种解法中的任意一种
>    发现可以正常得到结果。因为我们可以在`MediaType`为`application/json`的情况下，去处理`byte[]`类型的响应了。
> 
> 最后推销一下自己，辞职一个月了，最近在找工作。等一个有缘人内推。我的邮箱`laughho@qq.com`。

点个赞，今天刚好遇到这个问题，跟我想的一样

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
感谢认真诊断反馈问题，问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
