### ISSUE TITLE
[QUESTION]怎么设置默认时区，现在出现了时间丢失一天的情况

### ISSUE THREAD

**Issue by ztianz** [alibaba/fastjson2#1264]
字段上加了    @JSONField(format = "yyyy-MM-dd")。序列化出来比实际少了一天。感觉应该是时区的问题，怎么配置默认的时区啊。全化怎么配置

**Comment by wenshao** [comment]
可以如下的方式设置时区
```java
JSONWriter.Context context = JSONFactory.createWriteContext();
context.setZoneId(ZoneOffset.UTC); // 设置时区
JSON.toJSONString(object, context);
```

**Comment by iarrived** [comment]
有没有一种方法，可以实现全局的时区设置，比如和 JSON.configWriterDateFormat()并列。 @wenshao

**Comment by scccy** [comment]
> 有没有一种方法，可以实现全局的时区设置，比如和 JSON.configWriterDateFormat()并列，类似：
> 
> `JSON.configWriterZoneId()`
> 
> @wenshao

好哥哥找到了 FastJsonConfig config = new FastJsonConfig(); 这样的全局配置了吗
