### ISSUE TITLE
[BUG]父类泛型，子类byte[]类型序列化时，增加format参数后，WriteByteArrayAsBase64不生效

### ISSUE THREAD

**Issue by Alex-hu** [alibaba/fastjson2#1271]
### 问题描述
*简要描述您碰到的问题。*
父类含泛型，子类byte[]，序列化时，WriteByteArrayAsBase64不生效

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*
```java
    private static class Model<T> {
        public T value;
    }

    private static class Model1
            extends Model<byte[]> {
    }

    @Test
    public void test_1() {
        Model1 model = new Model1();
        model.value = "ABCDEG".getBytes();

        String json = JSON.toJSONString(model, JSONWriter.Feature.WriteByteArrayAsBase64);
        assertEquals("{\"value\":\"QUJDREVH\"}", json); // correct

        json = JSON.toJSONString(model, "yyyy-MM-dd HH:mm:ss", JSONWriter.Feature.WriteByteArrayAsBase64);
        assertEquals("{\"value\":\"QUJDREVH\"}", json); // mistake
    }

```

### 期待的正确结果

format应该只控制时间格式

### 相关日志输出

```bash
org.junit.ComparisonFailure: 
Expected :{"value":"QUJDREVH"}
Actual   :{"value":[65,66,67,68,69,71]}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
