### ISSUE TITLE
[BUG]先反序列，再序列化，字符集错误。

### ISSUE THREAD

**Issue by kingbo1587** [alibaba/fastjson2#1277]
### 问题描述
*简要描述您碰到的问题。*
先反序列，再序列化，字符集错误。

### 环境信息
*请填写以下信息：*

 - OS信息：  windows 10
 - JDK信息： jdk-17.0.5
 - 版本信息：Fastjson 2.0.26
 

### 重现步骤
*如何操作可以重现该问题：*

```java
Map<String, String> params = new HashMap<>();
params.put("name", "{\"paternalSurname\": \"Rodríguez\"}");
JSONObject jsonObject = JSON.parseObject(JSON.toJSONString(params));
// output: {"name":"{\"paternalSurname\": \"Rodr￭guez\"}"}
// Rodríguez 变成了 Rodr￭guez
System.out.println(JSON.toJSONString(jsonObject));
```

### 期待的正确结果
{"name":"{\"paternalSurname\": \"Rodríguez\"}"}

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by kingbo1587** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/ 问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

已验证，问题已解决。感谢。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
请用新版本
