### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by keepgoodfeeling** [alibaba/fastjson2#1285]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [win10 android studio 2021.2.1]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.26]
 - 引用方式:  api 'com.alibaba.fastjson2:fastjson2:2.0.26'
 

### 重现步骤

android 项目 引用后编译报错,无法打包apk;

AGPBI: {"kind":"error","text":"com.android.tools.r8.a: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)","sources":[{"file":"C:\\Users\\xxx\\.gradle\\caches\\transforms-3\\43a08b606894f7ed06fbd65fa1ea4f0d\\transformed\\jetified-fastjson2-2.0.26.jar"}],"tool":"D8"}

Execution failed for task ':app:mergeExtDexExampleDebug'.
> Could not resolve all files for configuration ':app:exampleDebugRuntimeClasspath'.
   > Failed to transform fastjson2-2.0.26.jar (com.alibaba.fastjson2:fastjson2:2.0.26) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\xxx\.gradle\caches\transforms-3\43a08b606894f7ed06fbd65fa1ea4f0d\transformed\jetified-fastjson2-2.0.26.jar.
         > Error while dexing.

**Comment by kraity** [comment]
您好, 目前的版本底层使用到了methodhandle, 而安卓sdk26才引入, 目前版本的解决办法是应用级build.gradle设置安卓sdk版本,  26<=minSdkVersion<=targetSdkVersion   [#91](http://kgithub.com/alibaba/fastjson2/issues/91)

**Comment by keepgoodfeeling** [comment]
目前主流的app,minSdkVersion=21,太高则有不少手机无法使用.希望能优化下版本适配吧.
