### ISSUE TITLE
[BUG] isValid有误

### ISSUE THREAD

**Issue by ls148478** [alibaba/fastjson2#1287]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows11-25309]
 - JDK信息： [e.g.：jdk-17--17.0.6]
 - 版本信息：[e.g.：Fastjson2 2.0.26]
 

### 重现步骤
*如何操作可以重现该问题：*

简单明了
```Kotlin
fun main() {
    println(JSON.isValid("033EYV000oYgHP1Rkw100g16Id0EYV0o"))
    println(JSON.VERSION)
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
true
2.0.26

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://user-images.githubusercontent.com/38435967/227776249-fd6c047a-2c5c-468a-af62-ba4929077e8e.png)

![image](https://user-images.githubusercontent.com/38435967/227776320-2a3780b3-c955-4699-ba5b-fc2e8b64afcd.png)

![image](https://user-images.githubusercontent.com/38435967/227776415-effba795-0982-4830-9dc8-0cd0195b03e8.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by ls148478** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/ 问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

感谢修复 验证通过

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
