### ISSUE TITLE
fastjson1支持返回的泛型的DTO转成List，fastjson2不支持

### ISSUE THREAD

**Issue by hcxxiaomo** [alibaba/fastjson2#1291]
###fastjson1支持返回的泛型的DTO转成List，fastjson2不支持
*fastjson1和2数据返回兼容不同*
温少好，跟 https://github.com/alibaba/fastjson2/issues/1240 类似，又发现另一个fastjson1的兼容性问题

### 环境信息
*请填写以下信息：*

 - OS信息：  windows  16G
 - JDK信息：Openjdk 1.8.0_291
 - 版本信息：Fastjson2 2.0.27
 

### 重现步骤
 代码如下
```java
        String info = "{\"obj\":{\"unitCode\":\"955H\"}}";
        Result<List<String>> listResult = com.alibaba.fastjson.JSON.parseObject(info, new com.alibaba.fastjson.TypeReference<Result<List<String>>>() {});
        System.out.println(listResult.obj);
        System.out.println(listResult.obj.get(0));


        listResult = com.alibaba.fastjson2.JSON.parseObject(info, new com.alibaba.fastjson2.TypeReference<Result<List<String>>>() {});
        System.out.println(listResult.obj);
        System.out.println(listResult.obj.get(0));
```

### 期待的正确结果
上面fastjson1的，能正常解析，但是下面fastjson2的，就会报错

### 相关日志输出

com.alibaba.fastjson2.JSONException: offset 8, character {, line 1, column 9, fastjson-version 2.0.26 {"obj":{"unitCode":"955H"}}

	at com.alibaba.fastjson2.reader.ObjectReaderImplListStr.readObject(ObjectReaderImplListStr.java:181)
	at com.alibaba.fastjson2.reader.ORG_1_1_Result.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:786)
	at com.xiaomo.maven.cha.com.xiaomo.study.enums.reflect.JsonTest.test1(JsonTest.java:26)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
