### ISSUE TITLE
愿景

### ISSUE THREAD

**Issue by objectboy2016** [alibaba/fastjson2#13]
protobuf被工业物联网广泛使用, 除了其效率高以外还有一个最重要的点就是其生成对象后体积小, fastjson2也能提供这种体积小的方法?

**Comment by wenshao** [comment]
JSONB就是支持这种场景的。

```java
import com.alibaba.fastjson2.JSONB;

// 序列化
byte[] jsonbBytes = JSONB.toBytes(obj);

// 反序列化
JSONB.parseObject(jsonbBytes, Bean.class);
```

**Comment by objectboy2016** [comment]
> JSONB就是支持这种场景的。
> 
> ```java
> import com.alibaba.fastjson2.JSONB;
> 
> // 序列化
> byte[] jsonbBytes = JSONB.toBytes(obj);
> 
> // 反序列化
> JSONB.parseObject(jsonbBytes, Bean.class);
> ```

我回头和bp对比下,
