### ISSUE TITLE
[BUG] 2.0.26 parseObject(input, TypeReference)导致编译报错

### ISSUE THREAD

**Issue by liuliuliu12138** [alibaba/fastjson2#1302]
### 问题描述
*简要描述您碰到的问题。*
从2.0.25升级到2.0.26时，parseObject(input, TypeReference) 在mvn package时编译报错

### 环境信息
*请填写以下信息：*

 - OS信息：  macOS Ventura 13.2.1
 - JDK信息： Openjdk 1.8
 - 版本信息：Fastjson2 2.0.26
 

### 重现步骤
代码：
```java
public List<Map<String, Object>> constructOutbound(Set<String> guids)
    {
        // 省略 一些代码
        List<Map<String, Object>> results = xxx;

        results = JSON.parseObject(JSON.toJSONString(results, (ValueFilter) (o, name, value) -> {
            if (StringUtils.isEmpty(Objects.toString(value, null)))
            {
                return null;
            }
            return value;
        }, JSONWriter.Feature.WriteNulls), new com.alibaba.fastjson2.TypeReference<List<LinkedHashMap<String, Object>>>()
        {
        });
        return results;
    }
```
mvn 报错信息：
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR]/some/path/information :[65,35] incompatible types: inference variable T has incompatible bounds
    equality constraints: java.util.List<java.util.LinkedHashMap<java.lang.String,java.lang.Object>>
    upper bounds: java.util.List<java.util.Map<java.lang.String,java.lang.Object>>,java.lang.Object
[ERROR] ]/some/path/information :[35,39] incompatible types: inference variable T has incompatible bounds
    equality constraints: java.util.List<java.util.LinkedHashMap<java.lang.String,java.lang.Object>>
    upper bounds: java.util.List<java.util.Map<java.lang.String,java.lang.Object>>,java.lang.Object

### 期待的正确结果
期望返回List<Map<String, Object>> 能接收List<LinkedHashMap<String, Object>>

**Comment by wenshao** [comment]
不能改回去了，改回去会导致其他的不兼容。你可以这样写：
```java
    public List<Map<String, Object>> constructOutbound(Set<String> guids) {
        // 省略 一些代码
        List<Map<String, Object>> results = new ArrayList<>();
        results = JSON.parseObject(
                JSON.toJSONString(
                        results,
                        (ValueFilter) (o, name, value) -> {
                            if (StringUtils.isEmpty(Objects.toString(value, null))) {
                                return null;
                            }
                            return value;
                        },
                        JSONWriter.Feature.WriteNulls
                ),
                new TypeReference<List<LinkedHashMap<String, Object>>>() {}.getType()
        );
        return results;
    }
```

**Comment by liuliuliu12138** [comment]
多谢回复，测试了没问题
