### ISSUE TITLE
[BUG]2.0.26版本 TypeUtils.compatibleWithFieldName = true 不起作用，反序列化后还是默认字段的首字母为小写

### ISSUE THREAD

**Issue by sfq28268** [alibaba/fastjson2#1303]
### 问题描述
2.0.26版本 TypeUtils.compatibleWithFieldName = true 不起作用，反序列化后还是默认字段的首字母为小写。
private String SPOrderSerialId

### 重现步骤
反序列化后 输出 sPOrderSerialId

### 期待的正确结果
反序列化后 应该按字段名原样输出 SPOrderSerialId

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
请用新版本

**Comment by reducm** [comment]
补充一下，给只用2的同学，没有了`TypeUtils.compatibleWithFieldName = true`，

从源码看到的配置方式

```java

         ObjectWriterProvider owp = new ObjectWriterProvider(PropertyNamingStrategy.CamelCase1x);
        JSONWriter.Context writeContext = JSONFactory.createWriteContext(
                owp,
                JSONWriter.Feature.IgnoreNonFieldGetter,
                JSONWriter.Feature.IgnoreErrorGetter,
                JSONWriter.Feature.WriteNonStringKeyAsString,
                JSONWriter.Feature.WriteByteArrayAsBase64,
                JSONWriter.Feature.ReferenceDetection,
                JSONWriter.Feature.WriteEnumsUsingName
        );

        String dateFormat = "millis";
        writeContext.setDateFormat(dateFormat);

        return JSON.toJSONString(object, writeContext);

```

**Comment by sfq28268** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.27 请用新版本

使用了，对象字段加了@TableField("BSOShouldPayAmount")注解的  可以原样输出， 
![image](https://user-images.githubusercontent.com/18158058/236134481-2c5f9125-c6d6-48fa-907d-a71633f3692e.png)


而没有加任何注解的首字母大写字段 仍然返回小驼峰形式。
![image](https://user-images.githubusercontent.com/18158058/236135153-b1592a12-5585-4a48-8c03-8df4dc539804.png)

返回结果：
![image](https://user-images.githubusercontent.com/18158058/236133851-0d9fbaef-bb41-4eb9-9d28-9a579398102c.png)
