### ISSUE TITLE
[FEATURE] 希望在FastJsonHttpMessageConverter中加入byte[]数组默认转为json字符串，或者在JSONWriter.Feature中增加

### ISSUE THREAD

**Issue by TsukasaHwan** [alibaba/fastjson2#1309]
由于有的框架返回json时使用的jackson进行返回的，jackson默认是将byte[]数组转换为json，然后我这边无法修改源码，使用fastjson进行返回的时候，返回的是一个byte[]，导致前端那边显示错误

**Comment by TsukasaHwan** [comment]
https://github.com/alibaba/fastjson2/issues/1256#issue-1633375864

**Comment by TsukasaHwan** [comment]
https://github.com/alibaba/fastjson2/issues/1256#issue-1633375864
提到的问题就是这个

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by TsukasaHwan** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/ 问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

已验证，没问题了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
