### ISSUE TITLE
[BUG]调用JSON.toJSONString() 方法时，产生npe

### ISSUE THREAD

**Issue by immaojiangle** [alibaba/fastjson2#1315]
### 问题描述
调用JSON.toJSONString() 方法时，产生npe

### 环境信息

 - JDK信息：openjdk version "1.8.0_312"
 - 版本信息：      
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>fastjson</artifactId>
        <version>2.0.26</version>
      </dependency>
 

### 重现步骤
*如何操作可以重现该问题：*
1、分别定义2个类（一点要是公共类）
```
@Data
public class Aa {
    private List<Bb> bList;
}

@Data
public class Bb {
    private List<LocalDateTime> dateTimes;
}

2、执行测试用例
 @Test
    public void t2(){
        Aa a =new Aa();
        List<Bb> bList = new ArrayList<>();
        Bb b1 = new Bb();
        bList.add(b1);
        Bb b2 = new Bb();
        bList.add(b2);
        List<LocalDateTime> dateTimes1 = new ArrayList<>();
        dateTimes1.add(LocalDateTime.now());
        dateTimes1.add(LocalDateTime.now());
        b1.setDateTimes(dateTimes1);


        List<LocalDateTime> dateTimes2 = new ArrayList<>();
        dateTimes2.add(LocalDateTime.now());
//        dateTimes2.add(LocalDateTime.now());
        b2.setDateTimes(dateTimes2);
        a.setBList(bList);
        Map<String, Object> map2 = ReflectUtils.buildObjectForMap(a);
        String json = JSON.toJSONString(map2);
        System.out.println(json);
    }
```
3. 出现空指针异常
![image](https://user-images.githubusercontent.com/10411913/229697994-37deb4d8-a702-4d2d-bffb-3e3955564bcc.png)

![image](https://user-images.githubusercontent.com/10411913/229699038-e1701b38-1a14-4fb9-8ed7-5ec9cc8d9ec4.png)

### 期待的正确结果
目前正在把fastjson1升级到fastjson2，这个bug是在升级过程中发现的，希望能尽快处理

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by immaojiangle** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.27-SNAPSHOT/ 问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证
bug依然存在
![image](https://user-images.githubusercontent.com/10411913/230258792-fb430652-5715-4bc2-bfc7-5595eeb7a9ea.png)

**Comment by immaojiangle** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.27-SNAPSHOT/ 问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证
bug依然存在
![image](https://user-images.githubusercontent.com/10411913/230259001-17929bcb-3232-407c-b2b3-e016c89de2bf.png)

**Comment by immaojiangle** [comment]
bug依然存在
https://github.com/alibaba/fastjson2/issues/1315#issuecomment-1498412277
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月5日(星期三) 凌晨1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson2] [BUG]调用JSON.toJSONString() 方法时，产生npe (Issue #1315)





 
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
 问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本

**Comment by immaojiangle** [comment]
[BUG]fastjson1.2.83升级到2.0.47，原先序列化引用对象的数据，再进行反序列化报错&nbsp;#2275

链接：
https://github.com/alibaba/fastjson2/issues/2275
麻烦大佬处理下
