### ISSUE TITLE
[BUG] fastjson2 输出 openapi3 api数据出错

### ISSUE THREAD

**Issue by zeroxiao** [alibaba/fastjson2#1318]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：MAC M1 /win10 I7 7700  16 GB]
 - JDK信息： [e.g.：jdk 1.8.0_322]
 - 版本信息：[e.g.：Fastjson2 2.0.26]
 

### 重现步骤
*如何操作可以重现该问题：*
<dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
                <version>4.1.0</version>
            </dependency>

openapi3 API文档数据不能输出，ERR：Could not write JSON: JSON#writeTo cannot serialize '[B@578ec0f7' to 'OutputStream'

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/7564943/229843157-c78b01d4-8594-42a7-b804-0d412288105e.png">
转为String 可以看到是API文档JSON数据
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/7564943/229843756-49149fdf-8c60-48e4-b8ff-2407d946a202.png">
出错的地方
<img width="998" alt="image" src="https://user-images.githubusercontent.com/7564943/229844749-90ea6e13-7f0c-448e-b954-c662f2434459.png">

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by yhl452493373** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/

已解决。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
