### ISSUE TITLE
JSONWriter.Feature Date 格式化

### ISSUE THREAD

**Issue by JiakunXu** [alibaba/fastjson2#132]
fastjson 1.x 可以在 httpMessageConverters() 通过
```
FastJsonConfig fastJsonConfig = new FastJsonConfig();
fastJsonConfig.setSerializerFeatures(SerializerFeature.WriteDateUseDateFormat);
```
统一配置 json 返回 Date 格式化
在 fastjson2 需要 如何配置，或者 自定义扩展？

**Comment by wenshao** [comment]
FastJsonConfig有dateFormat这个属性，你配置下看是否能生效，如果还不行，找 @VictorZeng

**Comment by JiakunXu** [comment]
嗯，有看到这个属性
```
FastJsonConfig fastJsonConfig = new FastJsonConfig();
fastJsonConfig.setDateFormat("yyyy-MM-dd HH:mm:ss");
```
试过，不行

**Comment by VictorZeng** [comment]
@JiakunXu  Hi, 目前fastjson2的`FastJsonConfig`在对于自定义DateFormat目前还没有支持，在下一个版本会考虑进去。

**Comment by HowardLei** [comment]
Hello，在之前的测试中，同样发现@JsonField(format = "") 中不支持 java.time 的时间，测试代码如下

**Comment by wenshao** [comment]
@HowardLei 你遇到LocalDateTime日期格式化的问题已经修复，你可以帮忙用2.0.3-SNAPSHOT版本帮忙验证么？

https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/

**Comment by HowardLei** [comment]
> @HowardLei 你遇到LocalDateTime日期格式化的问题已经修复，你可以帮忙用2.0.3-SNAPSHOT版本帮忙验证么？
> 
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/

好的，我重新拉一下 SNAPSHOT 版本进行验证
