### ISSUE TITLE
[BUG]反序列化 空字符 转换成list，会默认创建不为空的list

### ISSUE THREAD

**Issue by cao191495902** [alibaba/fastjson2#1320]
### 问题描述
空字符串 转换成list 反序列化的时候，会默认创建一个list，size=1，而fastjson不会

### 环境信息
*请填写以下信息：*

 - OS信息：  windows
 - JDK信息： jdk 1.8.0_312
 - 版本信息：Fastjson2 2.0.26
 

### 重现步骤

@Data
public class Test1 {

    private List<String> listTest;
}

    public static void main(String[] args) {
       String json = "{\"listTest\":\"\"}";

        Test1  test1 = com.alibaba.fastjson2.JSONObject.parseObject(json,Test1.class);

        Test1  test2 = com.alibaba.fastjson.JSONObject.parseObject(json,Test1.class);

        System.out.println(test1);
        System.out.println(test2);
    }
### 期待的正确结果
期待 fastjson2 和fastjson 结果相同

### 相关日志输出
Test1(listTest=[])
Test1(listTest=null)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
