### ISSUE TITLE
[BUG] fastjson:2.0.27-SNAPSHOT版本调用JSON.toJSONString() 方法时，产生npe

### ISSUE THREAD

**Issue by immaojiangle** [alibaba/fastjson2#1332]
### 问题描述
fastjson 2.0.27-SNAPSHOT版本调用JSON.toJSONString() 方法时，产生npe

### 环境信息

![image](https://user-images.githubusercontent.com/10411913/230548166-dd2b6a0b-870a-4b7b-87ad-8e0563613958.png)

### 重现步骤
1、分别定义2个类（一点要是公共类）
```java
@Data
public class Aa {
    private List<Bb> bList;
}

@Data
public class Bb {
    private List<LocalDateTime> dateTimes;
}
```
2、执行测试用例
```java
 @Test
    public void t2(){
        Aa a =new Aa();
        List<Bb> bList = new ArrayList<>();
        Bb b1 = new Bb();
        bList.add(b1);
        Bb b2 = new Bb();
        bList.add(b2);
        List<LocalDateTime> dateTimes1 = new ArrayList<>();
        dateTimes1.add(LocalDateTime.now());
        dateTimes1.add(LocalDateTime.now());
        b1.setDateTimes(dateTimes1);


        List<LocalDateTime> dateTimes2 = new ArrayList<>();
        dateTimes2.add(LocalDateTime.now());
//        dateTimes2.add(LocalDateTime.now());
        b2.setDateTimes(dateTimes2);
        a.setBList(bList);
        Map<String, Object> map2 = ReflectUtils.buildObjectForMap(a);
        String json = JSON.toJSONString(map2);
        System.out.println(json);
    }
```
出现空指针异常
![image](https://user-images.githubusercontent.com/10411913/230548193-a68bbde0-f105-4ee5-b5d7-3f3e06cce428.png)

![image](https://user-images.githubusercontent.com/10411913/230548177-b4d9d8e8-62d4-440e-853c-385a148e642c.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
问题已修复，请用新版本
