### ISSUE TITLE
[QUESTION] Fastjson Kotlin集成模块 2.2.0.27未上传到maven

### ISSUE THREAD

**Issue by ls148478** [alibaba/fastjson2#1334]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
如标题所示

**Comment by wenshao** [comment]
https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2-kotlin/2.0.27/
有啊

**Comment by ls148478** [comment]
> https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2-kotlin/2.0.27/ 有啊

好吧 我是在这里看的 https://mvnrepository.com/artifact/com.alibaba.fastjson2/fastjson2-kotlin
