### ISSUE TITLE
[BUG]2.0.27 序列化错误$super$

### ISSUE THREAD

**Issue by 1195952223** [alibaba/fastjson2#1337]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.27]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://user-images.githubusercontent.com/35017668/230718640-6f0a0f58-b9b6-4ae8-9766-ddea8d28c30b.png)
![image](https://user-images.githubusercontent.com/35017668/230718681-69c852c1-8920-4bd4-91b5-470b220a1e94.png)

**Comment by 1195952223** [comment]
![image](https://user-images.githubusercontent.com/35017668/230754754-e76b2318-0ace-4700-b4c1-fe82dfa791f5.png)
升级到27版本，不能正常序列化返回json

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
确实是问题，是考虑不周全了。问题已修复，请帮忙用2.0.28-SNAPSHOT版本验证，2.0.28预计在下周发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本
