### ISSUE TITLE
重大bug，fastjson2升级到2.0.27后Hutool工具的Dict字段接收不到数据了

### ISSUE THREAD

**Issue by yuxicun** [alibaba/fastjson2#1338]
重大bug，fastjson2升级到2.0.27后Hutool工具的Dict字段接收不到数据了，只能回退fastjson2

**Comment by yuxicun** [comment]
经过反复分析,发现原因是升级后,序列号变成这样了
![image](https://user-images.githubusercontent.com/18489852/230730027-a52a01cd-e62d-45e3-9843-5569ff458635.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
确实是问题，是考虑不周全了。问题已修复，请帮忙用2.0.28-SNAPSHOT版本验证，2.0.28预计在下周发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本
