### ISSUE TITLE
[BUG]序列化Map属性时改变属性名称，并设置Feature.WriteMapNullValue，序列化结果格式出错，无value值

### ISSUE THREAD

**Issue by lineng-hao-jie** [alibaba/fastjson2#1348]
### 问题描述
对象中存在Map属性，当属性值为null，JSON.toJSONString序列化时，设置Filter:NameFilter.of(PropertyNamingStrategy.UpperCamelCaseWithUnderScores) && Feature.WriteMapNullValue，此时序列化结果格式出错，k-v结构中缺少value信息，如：{"A_Map":}，尝试通过自定义实现NameFilter，发现只要改变name值，就会出现这问题。

### 环境信息
*请填写以下信息：*

 - OS信息：  windows 11
 - JDK信息：openjdk version "18.0.1.1"
 - 版本信息：Fastjson2 2.0.27

### 重现步骤
*运行示例代码即可重现，或者只要尝试改变name值*
```java
@Data
@Builder
@AllArgsConstructor
public class NameFilterTest {
    private Map<String, Date> aMap;

    public static void main(String[] args) {
        System.out.println(
                JSON.toJSONString(
                        NameFilterTest.builder().build(),
                        NameFilter.of(PropertyNamingStrategy.UpperCamelCaseWithUnderScores),
                        new JSONWriter.Feature[]{JSONWriter.Feature.WriteMapNullValue}));
    }
}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
问题已修复，请帮忙有2.0.8-SNAPSHOT版本验证，2.0.28版本预计会在周末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本
