### ISSUE TITLE
[BUG]JSONWriter.Feature.BrowserCompatible处理map的Long类型key值不正确

### ISSUE THREAD

**Issue by MartinDai** [alibaba/fastjson2#1350]
### 问题描述
添加JSONWriter.Feature.BrowserCompatible后输出的map的Long类型key值没有添加双引号，fastjson 1.x是可以正确处理的

### 环境信息
*请填写以下信息：*

 - OS信息：  MacOS 13.3.1
 - JDK信息：Openjdk 1.8.0_312
 - 版本信息：Fastjson2 2.0.27
 

### 重现步骤

```java
public class Test {

    Map<Long, String> map = new HashMap<>();

    public Test(){
        map.put(0L, "Test");
    }

    public Map<Long, String> getMap() {
        return map;
    }

    public static void main(String[] args) {
        Test test = new Test();
        String invalid = new String(JSON.toJSONString(test).getBytes(Charset.defaultCharset()), Charset.defaultCharset());
        String valid = new String(JSON.toJSONString(test, SerializerFeature.BrowserCompatible).getBytes(Charset.defaultCharset()), Charset.defaultCharset());
        System.out.println(invalid);
        System.out.println(valid);
    }
}
```

### 期待的正确结果
{"map":{0:"Test"}}
{"map":{"0":"Test"}}

### 相关日志输出
{"map":{0:"Test"}}
{"map":{0:"Test"}}

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
问题已修复，请帮忙有2.0.8-SNAPSHOT版本验证，2.0.28版本预计会在周末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本

**Comment by MartinDai** [comment]
@wenshao 2.0.28这个问题还是没修复，我使用这个版本测试输出的key还是没有双引号的
