### ISSUE TITLE
[BUG]枚举转换异常

### ISSUE THREAD

**Issue by zhuangjiaju** [alibaba/fastjson2#1355]
### 问题描述
*简要描述您碰到的问题。*

枚举
```java 
public enum TestEnum {
    E1,E2;
}

```

对象
```java
@Data
@Builder
public class TestDTO {
    private TestEnum testEnum;
}

```

测试代码
```java
  @Test
    public void test() {
        log.info("dto:{}", JSON.toJSONString(TestDTO.builder().testEnum(TestEnum.E1).build()));
        log.info("enum:{}", JSON.toJSONString(TestEnum.E1));
    }
```

输出
```text
// 就是这里有问题 居然输出了 0 ，希望输出的是枚举的.name()
11:06:49.315 [main] INFO com.alibaba.spring.test.fastjson.FastjsonTest - dto:{"testEnum":0}
11:06:49.334 [main] INFO com.alibaba.spring.test.fastjson.FastjsonTest - enum:"E1"
```

fastjson没有问题  fastjson2有问题，期望 输出：
 dto:{"testEnum":"E1"}

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：2.0.27
 

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
期望：
* 在枚举的情况下都是调用.name() 都是输出 "E1" ，而不是 在对象内输出0 ，纯枚举输出"E1"
* 在fastjson里面都是出"E1"的，所以没问题。 建议 1 和 2的默认值一样，用户体验更好。

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
使用JSONWriter.Feature.WriteEnumsUsingName，比如：
```java
JSON.toJSONString(obj, JSONWriter.Feature.WriteEnumsUsingName);
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本
