### ISSUE TITLE
[BUG][不兼容]解析带有超大数字的json时，fastjson1 直接报错，但是fastjson2却将数字截断，未报错。

### ISSUE THREAD

**Issue by xiaoxiao556655** [alibaba/fastjson2#1357]
[BUG][不兼容]解析带有超大数字的json时，fastjson1 直接报错，但是fastjson2却将数字截断，未报错。

**Comment by wenshao** [comment]
多大的数字？能提供重现问题的testcase么？

**Comment by xiaoxiao556655** [comment]
@Data
@Builder
@NoArgsConstructor
class PersonTest {

    private Integer pSsrc;

    private String pUserId;

    private boolean flag;

    private Map<String, String> map;

    public PersonTest(int pSsrc, String pUserId, boolean flag, Map<String, String> map) {
        super();
        this.pSsrc = pSsrc;
        this.pUserId = pUserId;
        this.flag = flag;
        this.map = map;
    }
}

String t1 = "{\"flag\":false,\"pSsrc\":6666665678858,\"pUserId\":\"\"}";
PersonTest t2 = com.alibaba.fastjson2.JSON.parseObject(t1, PersonTest.class);
t2 = com.alibaba.fastjson.JSON.parseObject(t1, PersonTest.class);

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
问题已修复，请帮忙有2.0.8-SNAPSHOT版本验证，2.0.28版本预计会在周末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本

**Comment by Hatawenzi** [comment]
还是有问题，譬如2147483666，10270867890这些还是能正常转换，但结果不对
