### ISSUE TITLE
[QUESTION]源码中ObjectReader.readObject接口下有92个实现，请问一下这个接口是怎么选择具体哪一个实现方法的

### ISSUE THREAD

**Issue by mebest100** [alibaba/fastjson2#1358]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
最近在跟踪fastjson的源码：

从JSON.parseObject方法进来==》ObjectReader.readObject方法：
发现ObjectReader.readObject接口下有92个实现，但是这里找不到它具体是怎么调用哪一个方法的。debug断点也看过，没有找到线索，结果是跳到了isJSONB方法。 不清楚它这里选择具体实现的机制
请问readObject接口具体是怎么从这个92个实现选择出一个具体实现的，具体的机制是什么？ 看起来应该不是自动选择的吧
![image](https://user-images.githubusercontent.com/11530991/231790119-1fd6d560-1777-449d-9a8f-bb2c748b4ecc.png)
![image](https://user-images.githubusercontent.com/11530991/231790266-b4c4dfef-41c7-4f27-bb41-22df7ddbd59b.png)

**Comment by wenshao** [comment]
在ObjectReaderProvider通过cache/cacheFieldBased来控制，你你调试下就知道了

**Comment by mebest100** [comment]
这个调试了一下还是没有看出什么线索，你说的这个cache/cacheFieldBased无非就是个缓存，但最终还是会生成一个ObjectReader。而我的问题是：ObjectReader在readObject时是如何自动匹配实现的，这个跟你说的那个缓存没有什么关系吧

**Comment by mebest100** [comment]
我建议你不清楚的话就不要胡说八道了，你说的完全就是牛头不对马嘴，胡说八道还不如不说！

**Comment by wenshao** [comment]
在ObjectReaderProvider这个方法:
```
public ObjectReader getObjectReader(Type objectType, boolean fieldBased) {
      // ...
}
```
生成后放在缓存cache/cacheFieldBased中

**Comment by mebest100** [comment]
> 在ObjectReaderProvider这个方法:
> 
> ```
> public ObjectReader getObjectReader(Type objectType, boolean fieldBased) {
>       // ...
> }
> ```
> 
> 生成后放在缓存cache/cacheFieldBased中

老哥，你没看懂我意思啊。这个缓存我当然知道的，可是我问的是ObjectReader的readObject时是如何自动匹配实现方法的，毕竟这个接口下有92个实现方法，难道是自动识别实现方法的？还是随机选择实现的？
包括你readObject方法实现中的ObjectReaderInterface里面又会再次套用readObject接口，那这次又是选择哪一个实现方法？这个地方的选择机制到底是什么？

![image](https://user-images.githubusercontent.com/11530991/232184162-e2121056-ef1e-4d68-a518-39a6550cc6dc.png)

**Comment by mebest100** [comment]
说你什么好，问你接口实现机制，你跟我谈缓存，是来搞笑的吗？ 我大概看明白了：是工厂方法自实现接口，非继承。但你什么理解力，非要跟我扯什么缓存，回答不了理解不了就直接close issue, 真是笑死人了，深圳大学出来的果然就这理解能力了

**Comment by oday-xiexin** [comment]
哈哈哈 wenshao说的是对的啊 你没听懂罢了
