### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LambdaV5** [alibaba/fastjson2#1364]
### 问题描述
*简要描述您碰到的问题。*
按照以下配置序列化出现异常

### 环境信息
*请填写以下信息：*
fastjson2 2.0.27

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
    public static String snakeCaseJson(Object object) {
        NameFilter nameFilter = NameFilter.of(PropertyNamingStrategy.SnakeCase);
        return JSON.toJSONString(object, nameFilter,
                JSONWriter.Feature.WriteNulls,
                JSONWriter.Feature.NullAsDefaultValue,
                JSONWriter.Feature.ReferenceDetection,
                JSONWriter.Feature.WriteBigDecimalAsPlain);
    }

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
直接使用JSON.toJSONString默认配置序列化正常

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
正常JSON数据
{
  "child_order_list": [
    {
      "order_sn_title": "子订单编号",
      "real_flower_money_title": "实际花材费01",
      "seller_name": "订单联调供货S",
      "order_sn": "HD1306130752023041436-1",
      "child_order_id": 654,
      "date": "2023-04-14 11:16:55",
      "order_total_number": 4,
      "order_frames": [],
      "order_pay_status_text": "已付款",
      "order_pay_status_text_color": "#00d366",
      "order_pay_status_tips_text": "普通订单，已付款",
      "pay_platform": "未知",
      "order_real_pay_money": 0.0,
      "pay_status_text": "已支付",
      "pay_status_text_color": "#7bc78a",
      "pay_time": "2023-04-14 11:16:58",
      "order_bottom_fields": [
        {
          "title": "预付花材费",
          "value": 209.41,
          "value_text_color": "#000000"
        },
        {
          "title": "预付打包运费",
          "value": 0.0,
          "value_text_color": "#000000"
        },
        {
          "title": "实付款",
          "value": 0.0,
          "value_text_color": "#000000"
        },
        {
          "title": "支付方式",
          "value": "未知",
          "value_text_color": "#000000"
        },
        {
          "title": "支付状态",
          "value": "已支付",
          "value_text_color": "#7bc78a"
        },
        {
          "title": "支付时间",
          "value": "2023-04-14 11:16:58",
          "value_text_color": "#000000"
        },
        {
          "title": "退款状态",
          "value": "未退款",
          "value_text_color": "#cccccc"
        },
        {
          "title": "退款金额",
          "value": "¥0.00",
          "value_text_color": "#cccccc"
        },
        {
          "title": " ",
          "value": "退款金额已原路返回，将在七个工作日内到账",
          "value_text_color": "red"
        },
        {
          "title": "优惠券",
          "value": "¥40",
          "coupon_tags": "[{\"coupon_id\":1,\"coupon_name\":\"花材券\",\"money\":20},{\"coupon_id\":3,\"coupon_name\":\"花材券\",\"money\":10}]",
          "value_text_color": "red"
        }
      ],
      "money_filed_explain": "order_flower_money=花材金额 order_package_express_fee=打包费运费 order_coupon_money=使用优惠券settlement_flower_money=结算花材费 pre_pay_flower_money=预付花材费 real_flower_money=实际花材费",
      "pre_pay_flower_money": 209.41,
      "order_flower_money": 209.41,
      "order_package_express_fee": 0.0,
      "order_coupon_money": 0.0,
      "settlement_flower_money": 109.51,
      "real_flower_money": 109.51,
      "create_order_date": "2023-04-14 11:16:55",
      "normal_flower_list": [
        {
          "seller_name": "订单联调供货",
          "goods_type": 1,
          "goods_name": "绣球",
          "goods_level": "B",
          "grow_level": "全生",
          "goods_unit": "1枝/扎",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 33.22,
          "real_money": 33.22,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1279,
          "order_id": 654,
          "real_deliver_money": 33.22
        },
        {
          "seller_name": "供货1002",
          "goods_type": 1,
          "goods_name": "马斯特",
          "goods_level": "B",
          "grow_level": "全生",
          "goods_unit": "20枝/扎",
          "buy_number": 1,
          "real_deliver_num": 0.0,
          "real_deliver_num_text_color": "#ff2000",
          "pre_pay_money": 99.9,
          "real_money": 99.9,
          "sorting_number": 0,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1281,
          "order_id": 654,
          "real_deliver_money": 0.0
        }
      ],
      "agent_flower_list": [
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "马斯特",
          "goods_level": "C",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 14.82,
          "real_money": 14.82,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1280,
          "order_id": 654,
          "real_deliver_money": 14.82
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "黄天霸/木门单头",
          "goods_level": "B",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 61.47,
          "real_money": 61.47,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1282,
          "order_id": 654,
          "real_deliver_money": 61.47
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "进口郁金香蜜桃粉",
          "goods_level": "B",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 59.02,
          "real_money": 59.02,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1283,
          "order_id": 655,
          "real_deliver_money": 59.02
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "进口郁金香蜜桃粉",
          "goods_level": "C",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 16.97,
          "real_money": 16.97,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1284,
          "order_id": 656,
          "real_deliver_money": 16.97
        }
      ],
      "show_receiving_orders_icon_and_text_explain": "是否显示先货后款订单 是否已接单状态文字及图标 0=不显示  1=显示图标及按钮 =2仅显示文字",
      "show_receiving_orders_icon_and_text": 0,
      "show_cancel_order_btn_explain": "是否显示取消订单按钮；1=显示  0=不显示",
      "show_cancel_order_btn": 0,
      "is_show_buy_more_flower_btn": 0,
      "send_goods_to_stock_explain": "send_goods_to_stock_date=送货日期  send_goods_to_stock_number=送货数量 send_goods_to_stock_money=已送货金额"
    },
    {
      "order_sn_title": "子订单编号",
      "real_flower_money_title": "实际花材费01",
      "seller_name": "订单联调供货S",
      "order_sn": "HD1306130752023041436-2",
      "child_order_id": 655,
      "date": "2023-04-14 11:22:34",
      "order_total_number": 1,
      "order_frames": [],
      "order_pay_status_text": "已付款",
      "order_pay_status_text_color": "#00d366",
      "order_pay_status_tips_text": "普通订单，已付款",
      "pay_platform": "未知",
      "order_real_pay_money": 0.0,
      "pay_status_text": "已支付",
      "pay_status_text_color": "#7bc78a",
      "pay_time": "2023-04-14 11:23:07",
      "order_bottom_fields": [
        {
          "title": "预付花材费",
          "value": 59.02,
          "value_text_color": "#000000"
        },
        {
          "title": "预付打包运费",
          "value": 0.0,
          "value_text_color": "#000000"
        },
        {
          "title": "实付款",
          "value": 0.0,
          "value_text_color": "#000000"
        },
        {
          "title": "支付方式",
          "value": "未知",
          "value_text_color": "#000000"
        },
        {
          "title": "支付状态",
          "value": "已支付",
          "value_text_color": "#7bc78a"
        },
        {
          "title": "支付时间",
          "value": "2023-04-14 11:23:07",
          "value_text_color": "#000000"
        },
        {
          "title": "退款状态",
          "value": "未退款",
          "value_text_color": "#cccccc"
        },
        {
          "title": "退款金额",
          "value": "¥0.00",
          "value_text_color": "#cccccc"
        },
        {
          "title": " ",
          "value": "退款金额已原路返回，将在七个工作日内到账",
          "value_text_color": "red"
        },
        {
          "title": "优惠券",
          "value": "¥40",
          "coupon_tags": "[{\"coupon_id\":1,\"coupon_name\":\"花材券\",\"money\":20},{\"coupon_id\":3,\"coupon_name\":\"花材券\",\"money\":10}]",
          "value_text_color": "red"
        }
      ],
      "money_filed_explain": "order_flower_money=花材金额 order_package_express_fee=打包费运费 order_coupon_money=使用优惠券settlement_flower_money=结算花材费 pre_pay_flower_money=预付花材费 real_flower_money=实际花材费",
      "pre_pay_flower_money": 59.02,
      "order_flower_money": 59.02,
      "order_package_express_fee": 0.0,
      "order_coupon_money": 0.0,
      "settlement_flower_money": 168.53,
      "real_flower_money": 168.53,
      "create_order_date": "2023-04-14 11:22:34",
      "normal_flower_list": [
        {
          "seller_name": "订单联调供货",
          "goods_type": 1,
          "goods_name": "绣球",
          "goods_level": "B",
          "grow_level": "全生",
          "goods_unit": "1枝/扎",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 33.22,
          "real_money": 33.22,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1279,
          "order_id": 654,
          "real_deliver_money": 33.22
        },
        {
          "seller_name": "供货1002",
          "goods_type": 1,
          "goods_name": "马斯特",
          "goods_level": "B",
          "grow_level": "全生",
          "goods_unit": "20枝/扎",
          "buy_number": 1,
          "real_deliver_num": 0.0,
          "real_deliver_num_text_color": "#ff2000",
          "pre_pay_money": 99.9,
          "real_money": 99.9,
          "sorting_number": 0,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1281,
          "order_id": 654,
          "real_deliver_money": 0.0
        }
      ],
      "agent_flower_list": [
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "马斯特",
          "goods_level": "C",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 14.82,
          "real_money": 14.82,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1280,
          "order_id": 654,
          "real_deliver_money": 14.82
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "黄天霸/木门单头",
          "goods_level": "B",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 61.47,
          "real_money": 61.47,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1282,
          "order_id": 654,
          "real_deliver_money": 61.47
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "进口郁金香蜜桃粉",
          "goods_level": "B",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 59.02,
          "real_money": 59.02,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1283,
          "order_id": 655,
          "real_deliver_money": 59.02
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "进口郁金香蜜桃粉",
          "goods_level": "C",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 16.97,
          "real_money": 16.97,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1284,
          "order_id": 656,
          "real_deliver_money": 16.97
        }
      ],
      "show_receiving_orders_icon_and_text_explain": "是否显示先货后款订单 是否已接单状态文字及图标 0=不显示  1=显示图标及按钮 =2仅显示文字",
      "show_receiving_orders_icon_and_text": 0,
      "show_cancel_order_btn_explain": "是否显示取消订单按钮；1=显示  0=不显示",
      "show_cancel_order_btn": 0,
      "is_show_buy_more_flower_btn": 0,
      "send_goods_to_stock_explain": "send_goods_to_stock_date=送货日期  send_goods_to_stock_number=送货数量 send_goods_to_stock_money=已送货金额"
    },
    {
      "order_sn_title": "子订单编号",
      "real_flower_money_title": "实际花材费01",
      "seller_name": "订单联调供货S",
      "order_sn": "HD1306130752023041436-3",
      "child_order_id": 656,
      "date": "2023-04-14 11:25:04",
      "order_total_number": 1,
      "order_frames": [],
      "order_pay_status_text": "已付款",
      "order_pay_status_text_color": "#00d366",
      "order_pay_status_tips_text": "普通订单，已付款",
      "pay_platform": "未知",
      "order_real_pay_money": 0.0,
      "pay_status_text": "已支付",
      "pay_status_text_color": "#7bc78a",
      "pay_time": "2023-04-14 11:25:08",
      "order_bottom_fields": [
        {
          "title": "预付花材费",
          "value": 16.97,
          "value_text_color": "#000000"
        },
        {
          "title": "预付打包运费",
          "value": 0.0,
          "value_text_color": "#000000"
        },
        {
          "title": "实付款",
          "value": 0.0,
          "value_text_color": "#000000"
        },
        {
          "title": "支付方式",
          "value": "未知",
          "value_text_color": "#000000"
        },
        {
          "title": "支付状态",
          "value": "已支付",
          "value_text_color": "#7bc78a"
        },
        {
          "title": "支付时间",
          "value": "2023-04-14 11:25:08",
          "value_text_color": "#000000"
        },
        {
          "title": "退款状态",
          "value": "未退款",
          "value_text_color": "#cccccc"
        },
        {
          "title": "退款金额",
          "value": "¥0.00",
          "value_text_color": "#cccccc"
        },
        {
          "title": " ",
          "value": "退款金额已原路返回，将在七个工作日内到账",
          "value_text_color": "red"
        },
        {
          "title": "优惠券",
          "value": "¥40",
          "coupon_tags": "[{\"coupon_id\":1,\"coupon_name\":\"花材券\",\"money\":20},{\"coupon_id\":3,\"coupon_name\":\"花材券\",\"money\":10}]",
          "value_text_color": "red"
        }
      ],
      "money_filed_explain": "order_flower_money=花材金额 order_package_express_fee=打包费运费 order_coupon_money=使用优惠券settlement_flower_money=结算花材费 pre_pay_flower_money=预付花材费 real_flower_money=实际花材费",
      "pre_pay_flower_money": 16.97,
      "order_flower_money": 16.97,
      "order_package_express_fee": 0.0,
      "order_coupon_money": 0.0,
      "settlement_flower_money": 185.5,
      "real_flower_money": 185.5,
      "create_order_date": "2023-04-14 11:25:04",
      "normal_flower_list": [
        {
          "seller_name": "订单联调供货",
          "goods_type": 1,
          "goods_name": "绣球",
          "goods_level": "B",
          "grow_level": "全生",
          "goods_unit": "1枝/扎",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 33.22,
          "real_money": 33.22,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1279,
          "order_id": 654,
          "real_deliver_money": 33.22
        },
        {
          "seller_name": "供货1002",
          "goods_type": 1,
          "goods_name": "马斯特",
          "goods_level": "B",
          "grow_level": "全生",
          "goods_unit": "20枝/扎",
          "buy_number": 1,
          "real_deliver_num": 0.0,
          "real_deliver_num_text_color": "#ff2000",
          "pre_pay_money": 99.9,
          "real_money": 99.9,
          "sorting_number": 0,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1281,
          "order_id": 654,
          "real_deliver_money": 0.0
        }
      ],
      "agent_flower_list": [
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "马斯特",
          "goods_level": "C",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 14.82,
          "real_money": 14.82,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1280,
          "order_id": 654,
          "real_deliver_money": 14.82
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "黄天霸/木门单头",
          "goods_level": "B",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 61.47,
          "real_money": 61.47,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1282,
          "order_id": 654,
          "real_deliver_money": 61.47
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "进口郁金香蜜桃粉",
          "goods_level": "B",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 59.02,
          "real_money": 59.02,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1283,
          "order_id": 655,
          "real_deliver_money": 59.02
        },
        {
          "seller_name": "订单联调供货S",
          "goods_type": 2,
          "goods_name": "进口郁金香蜜桃粉",
          "goods_level": "C",
          "grow_level": "全开",
          "goods_unit": "",
          "buy_number": 1,
          "real_deliver_num": 1.0,
          "real_deliver_num_text_color": "#00ab00",
          "pre_pay_money": 16.97,
          "real_money": 16.97,
          "sorting_number": 1,
          "sorting_number_text_color": "#6eca80",
          "seller_mobile": 0,
          "order_goods_id": 1284,
          "order_id": 656,
          "real_deliver_money": 16.97
        }
      ],
      "show_receiving_orders_icon_and_text_explain": "是否显示先货后款订单 是否已接单状态文字及图标 0=不显示  1=显示图标及按钮 =2仅显示文字",
      "show_receiving_orders_icon_and_text": 0,
      "show_cancel_order_btn_explain": "是否显示取消订单按钮；1=显示  0=不显示",
      "show_cancel_order_btn": 0,
      "is_show_buy_more_flower_btn": 0,
      "send_goods_to_stock_explain": "send_goods_to_stock_date=送货日期  send_goods_to_stock_number=送货数量 send_goods_to_stock_money=已送货金额"
    }
  ]
}
出问题JSON数据片段
"normal_flower_list": [
        {
          "$ref": "$[0][0]"
        },
        {
          "$ref": "$[0][1]"
        }
      ],
      "agent_flower_list": [
        {
          "$ref": "$[0][0]"
        },
        {
          "$ref": "$[0][1]"
        },
        {
          "$ref": "$[0][2]"
        },
        {
          "$ref": "$[0][3]"
        }
      ],

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
去掉JSONWriter.Feature.ReferenceDetection试试看

**Comment by LambdaV5** [comment]
去掉JSONWriter.Feature.ReferenceDetection后输出正常，（备注：待序列化的数据类型全是通过hashmap组装的）
