### ISSUE TITLE
[QUESTION]包“fastjson1-compatible”有一些可能会引起开源协议歧义的信息说明，是否考虑去掉这些信息？

### ISSUE THREAD

**Issue by eishen** [alibaba/fastjson2#1365]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

(https://github.com/alibaba/fastjson2/tree/main/fastjson1-compatible/src/test/java/com/alibaba/json/bvtVO)/
这个包下面的几个文件，如IEvent.java
有下面这样的版权信息，会造成一下开源协议的歧义，是否考虑去掉这些信息？

/**
 * Project: eve.services
 * <p>
 * File Created at 2011-12-21
 * $Id$
 * <p>
 * Copyright 2008 Alibaba.com Corporation Limited.
 * All rights reserved.
 * <p>
 * This software is the confidential and proprietary information of
 * Alibaba Company. ("Confidential Information").  You shall not
 * disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into
 * with Alibaba.com.
 */

**Comment by wenshao** [comment]
done

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本
