### ISSUE TITLE
[BUG]JSONSchema校验字符串类型的枚举和常量失败

### ISSUE THREAD

**Issue by 864381832** [alibaba/fastjson2#1367]
### 问题描述
*简要描述您碰到的问题。*
在使用JSONSchema对json文件进行校验时，发现字符串类型的枚举和常量不支持，一直显示校验通过。
同时看源码发现枚举类型似乎只支持整型和浮点型，但测试下面类型名需填int，标准的JsonSchema中定义的为integer和number。
同样的校验在使用com.networknt:json-schema-validator:1.0.79工具包中可以正常校验。

### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.27]
 

### 重现步骤
*如何操作可以重现该问题：*
1. 使用 `schema.isValid` 方法
2. 输入 `{\"姓\": \"3\"}`  数据
3. 出现校验结果错误
```java
String schemaStr = "{\"type\": \"object\",\"properties\": {\"姓\": {\"type\": \"string\",\"enum\": [\"1\", \"2\"]}}}";
String schemaStr2 = "{\"type\":\"object\",\"properties\":{\"姓\":{\"type\":\"string\",\"const\":\"1\"}}}";
JSONSchema schema = JSONSchema.of(JSON.parseObject(schemaStr));
JSONSchema schema2 = JSONSchema.of(JSON.parseObject(schemaStr2));
String jsonStr = "{\"姓\": \"3\"}";
System.out.println(schema.isValid(JSON.parseObject(jsonStr)));
System.out.println(schema2.isValid(JSON.parseObject(jsonStr)))
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
能正确校验字符串枚举值和常量

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
<img width="948" alt="image" src="https://user-images.githubusercontent.com/6625207/232066961-8ac143cd-408c-4787-84af-91c8a7d3be7a.png">

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
问题已修复，请帮忙有2.0.28-SNAPSHOT版本验证，2.0.28版本预计在明天发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本

**Comment by 864381832** [comment]
验证完成，修复的速度挺快👍🏻
