### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dongxp** [alibaba/fastjson2#1369]
### 问题描述
*简要描述您碰到的问题。*
针对$.A.B[?(@.C==null)]解析会报异常，path解析代码读取==后面的字符时没有考虑可能为null的场景，导致必须先临时将==null删除才可以绕过

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 $.A.B[?(@.C==null)] 方法
2. 输入 {"A": {"B": {"C": null, "D": 1}}}  数据
3. 出现 `...` 错误:jsonpath syntax error, offset 38, character n, line 1, column 39
```java
//可在此输入示例代码
```
result = JSONPath.eval(rootObject, "$.A.B[?(@.C==null)]");
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
过滤条件考虑==后面出现null的场景，jayway就支持

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
问题已修复，请帮忙有2.0.28-SNAPSHOT版本验证，2.0.28版本预计在明天发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本
