### ISSUE TITLE
fastjson2的jsonpath不再支持$.fooList[0].name 语法了么？

### ISSUE THREAD

**Issue by liuccc1** [alibaba/fastjson2#1388]
json字符串格式：{"fooList":[{"name":"Kyrie Irving"},{"name":"LeBron James"}],"name":"NBA2016"}
使用jsonpath的extract不能获取$.fooList[0].name

**Comment by wenshao** [comment]
```java
        String json = "{\"fooList\":[{\"name\":\"Kyrie Irving\"},{\"name\":\"LeBron James\"}],\"name\":\"NBA2016\"}";
        Object result = JSONPath.extract(json, "$.fooList[0].name");
        assertEquals("Kyrie Irving", result.toString());
```
支持的，你用的是什么版本？

**Comment by liuccc1** [comment]
`    @Test
    public void testJsonPathExtract() {
        String json = "{\"fooList\":[{\"name\":\"Kyrie Irving\"},{\"name\":\"LeBron James\"}],\"name\":\"NBA2016\"}";
        JSONReader parser = JSONReader.of(json);

        JSONPath namePath = JSONPath.of("$.name");
        //可以正常输出
        Console.log("$.name: {}", namePath.extract(parser));
        //输出null
        Console.log("$.fooList[0].name: {}", JSONPath.of("$.fooList[0].name").extract(parser));
    }`
`    @Test
    public void testJsonPathExtract() {
        String json = "{\"fooList\":[{\"name\":\"Kyrie Irving\"},{\"name\":\"LeBron James\"}],\"name\":\"NBA2016\"}";
        JSONReader parser = JSONReader.of(json);
        //可以正常输出
        Console.log("$.fooList[0].name: {}", JSONPath.of("$.fooList[0].name").extract(parser));
    }`
按理第一个测试用例应该都能正确输出才对

**Comment by wenshao** [comment]
```java
JSONReader parser 
```
这个只能用一次，有状态的
