### ISSUE TITLE
[BUG]JSONWriter.Feature.BrowserCompatible处理map的Long类型key值不正确

### ISSUE THREAD

**Issue by MartinDai** [alibaba/fastjson2#1401]
### 问题描述
添加JSONWriter.Feature.BrowserCompatible后输出的map的Long类型key值没有添加双引号，fastjson 1.x是可以正确处理的

#1350 提过这个问题然后说是修复了，但是我验证了还是不行的

### 环境信息
*请填写以下信息：*

 - OS信息：  MacOS 13.3.1
 - JDK信息：Openjdk 1.8.0_312
 - 版本信息：Fastjson2 2.0.28
 

### 重现步骤

```java
public class Test {

    Map<Long, String> map = new HashMap<>();

    public Test(){
        map.put(0L, "Test");
    }

    public Map<Long, String> getMap() {
        return map;
    }

    public static void main(String[] args) {
        Test test = new Test();
        String invalid = new String(JSON.toJSONString(test).getBytes(Charset.defaultCharset()), Charset.defaultCharset());
        String valid = new String(JSON.toJSONString(test, JSONWriter.Feature.BrowserCompatible).getBytes(Charset.defaultCharset()), Charset.defaultCharset());
        System.out.println(invalid);
        System.out.println(valid);
    }
}
```

### 期待的正确结果
{"map":{0:"Test"}}
{"map":{"0":"Test"}}

### 相关日志输出
{"map":{0:"Test"}}
{"map":{0:"Test"}}

**Comment by kraity** [comment]
您好, `Feature.BrowserCompatible`特性不是针对非字符串Key. 
需要使用  `JSONWriter.Feature.WriteNonStringKeyAsString` (非字符串Key作为字符串) 才能符合预期

**Comment by MartinDai** [comment]
> 您好, `Feature.BrowserCompatible`特性不是针对非字符串Key. 需要使用 `JSONWriter.Feature.WriteNonStringKeyAsString` (非字符串Key作为字符串) 才能符合预期

但是在fastjson 1.x使用SerializerFeature.BrowserCompatible是可以的  这块在2.x不兼容吗

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.30-SNAPSHOT/
问题已修复，请帮忙用2.0.30-SNAPSHOT验证，2.0.30版本预计在周末5月7日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.30
请用新版本

**Comment by rowstop** [comment]
有歧义，使用WriteNonStringKeyAsString
