### ISSUE TITLE
[BUG]@JsonFormat日期反序列化支持格式太少

### ISSUE THREAD

**Issue by yonghao9531** [alibaba/fastjson2#1412]
### 问题描述
*简要描述您碰到的问题。*
   @Data
    public class TestNotice implements Serializable {
        private Long id;
        @JsonFormat(
                pattern = "yyyy-MM-dd"
        )
        private Date sendTime;
    }

    public static void main(String[] args) {
        String s = "{\"id\":1,\"sendTime\":\"2023-03-24 11:10:11\"}";
        TestNotice notice = JSON.parseObject(s, TestNotice.class);
        System.out.println(notice.toString());
    }

错误：
Text '2023-03-24 11:10:11' could not be parsed, unparsed text found at index 10

期望：
yyyy-MM-dd,dd/MM/yyyy 都能正常转换，支持日期格式太少

**Comment by kraity** [comment]
您好, 由于指定了日期的Pattern, 故而按照指定的格式解析. 
根据给定的测试数据看出应该定义为 `pattern = "yyyy-MM-dd HH:mm:ss"` 具体可以查阅Java日期格式化文档

**Comment by yonghao9531** [comment]
@JsonFormat  是需要返回给前端的格式，我反序列化的时候应该是按字符串时间格式来转换

**Comment by kraity** [comment]
> @JsonFormat 是需要返回给前端的格式，我反序列化的时候应该是按字符串时间格式来转换

如果是这样, 说明解析和序列化是格式需要不一致, 可以使用VO/DTO进行转换, 
或者可以自定义解析 `@JSONField(deserializeUsing=YourCustomDateObjectReader.class)`, 具体可以参照ObjectReader文档实现

**Comment by yonghao9531** [comment]
@JsonFormat(pattern = "dd/MM/yyyy")
 @JSONField(format = "yyyy-MM-dd HH:mm:ss")
可以解决，顺序不能乱，我是用fastjson把实体类转换成VO/DTO，返回给前端，fastjson 已经有了JSONField，为什么还要兼容JsonFormat

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.30-SNAPSHOT/
请帮忙用2.0.30-SNAPSHOT版本验证下，2.0.30版本预计在5月9日前发布

**Comment by yonghao9531** [comment]
使用 fastjson2-2.0.30-20230503.120628-20.jar 问题依然存在，还是需要使用
@JsonFormat(pattern = "dd/MM/yyyy")
@JSONField(format = "yyyy-MM-dd HH:mm:ss")
缺一不可

**Comment by wenshao** [comment]
要加上JSONReader.Feature.SupportSmartMatch，比如：

```java
    @Test
    public void test1() {
        String s = "{\"date\":\"2023-03-24 11:10:11\"}";
        Bean1 bean = JSON.parseObject(s, Bean1.class, JSONReader.Feature.SupportSmartMatch);
        assertNotNull(bean);
    }

    @Data
    public static class Bean1 {
        @JsonFormat(pattern = "dd/MM/yyyy")
        private Date date;
    }
```

**Comment by yonghao9531** [comment]
确认已解决，期待2.0.30版本发布

**Comment by yonghao9531** [comment]
已解决，感谢
