### ISSUE TITLE
Dubbo version: 3.2.0 序列化问题，fastjson2 ，配置java正常[BUG]

### ISSUE THREAD

**Issue by tb8367085** [alibaba/fastjson2#1421]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 - Dubbo version: 3.2.0
 - fastjson2.0.27
Operating System version: window11
Java version: 17/19 都有问题
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

dubbo.provider.prefer-serialization: fastjson2 报反射找不到 java.util.Collection$SynchronizedRandomAccessList的构造器，构造器jdk17+不是public的，所有报错，感觉是fastjson2 的问题

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
![image](https://user-images.githubusercontent.com/18565542/235046870-72af66f5-f38b-4d1b-a4e8-4a75ac6c3a52.png)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
我在dubbo也提了一个
https://github.com/apache/dubbo/issues/12196#issue-1684675799

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.30-SNAPSHOT/
问题已修复，请帮忙用2.0.30-SNAPSHOT验证，2.0.30版本预计在5月9日发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.30
请用新版本
