### ISSUE TITLE
[BUG]MySQL的JSON字段插入时重新排序key，导致无法识别@type

### ISSUE THREAD

**Issue by LeeYuze** [alibaba/fastjson2#1428]
### 问题描述
*MySQL的JSON字段插入时重新排序key，导致无法识别@type*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

像下面的数据就无法正常自动还原type
```json
[{"x": 399, "y": 318, "@type": "com.ruirui.common.dto.PositionData"}, {"x": 553, "y": 319, "@type": "com.ruirui.common.dto.PositionData"}, {"x": 414, "y": 196, "@type": "com.ruirui.common.dto.PositionData"}]
```

我知道Object转json时时正常的，@type是在头部的，但是插入到MySQL后会重新排序，希望改一下parse的源码，不要只从头部判断有没有@type哈

**Comment by wenshao** [comment]
目前设计就是这样的，不支持非头部@type
