### ISSUE TITLE
[BUG]将指定实体序列化为JSON字符串时，会偶然增加frozen,valid,managed等非原本字段

### ISSUE THREAD

**Issue by ChinaFLTV** [alibaba/fastjson2#1430]
### 问题描述
序列化会偶现字段自动添加的情况

### 环境信息
*请填写以下信息：*

 - OS信息：  android 9
 - JDK信息： jdk 11
 - 版本信息：Fastjson2 2.0.23
 

### 重现步骤
比如我要序列化一个Book实体，
该实体的固有属性为String name,Double price,
然后进行序列化

### 期待的正确结果
{

"name":"XXXX",
"price":6.66

}

### 实际输出

{

"name":"XXXX",
"price":6.66,
 frozen:false,
 managed:false,
 valid:true,
 loaded:true

}

ps:我们这边就只有这一种特定的实体出现了这种情况，其他正常

**Comment by wenshao** [comment]
是什么实体类？

**Comment by ChinaFLTV** [comment]
就是这个
![image](https://user-images.githubusercontent.com/109414112/236125849-5f01a734-f8af-46ad-a652-48e7dd1db39d.png)，
我们序列化其他类都没问题，唯独这个类有时候好好的，有时候序列化的时候就会多出上面列举的几个字段

**Comment by wenshao** [comment]
RealmObject就有这些方法啊

**Comment by ChinaFLTV** [comment]
好的，我去看一下
