### ISSUE TITLE
TypeUtils.compatibleWithFieldName = true 配置没有生效

### ISSUE THREAD

**Issue by sfq28268** [alibaba/fastjson2#1432]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
请用新版本

_Originally posted by @wenshao in https://github.com/alibaba/fastjson2/issues/1303#issuecomment-1500751437_

> https://github.com/alibaba/fastjson2/releases/tag/2.0.27 请用新版本

使用了2.0.28最新版本的jar，对象字段加了@TableField("BSOShouldPayAmount")注解的  可以原样输出， 
![image](https://user-images.githubusercontent.com/18158058/236134481-2c5f9125-c6d6-48fa-907d-a71633f3692e.png)

而没有加任何注解的首字母大写字段 仍然返回小驼峰形式。
![image](https://user-images.githubusercontent.com/18158058/236135153-b1592a12-5585-4a48-8c03-8df4dc539804.png)

返回结果：
![image](https://user-images.githubusercontent.com/18158058/236133851-0d9fbaef-bb41-4eb9-9d28-9a579398102c.png)

补充，而且使用注解@TableId(value = "Id") 返回也是小驼峰 不是原样输出
![image](https://user-images.githubusercontent.com/18158058/236173223-0673c444-3597-4297-8fbb-16b7ab51499a.png)
 
返回数据：
![image](https://user-images.githubusercontent.com/18158058/236173548-ca7421f6-a92e-4412-8651-ef025c8fd7b6.png)

**Comment by sfq28268** [comment]
@JSONField(name = "BSOShouldPayAmount")

**Comment by wenshao** [comment]
使用@JSONField(name="BSOShouldPayAmount") 试下？

**Comment by sfq28268** [comment]
> 使用@JSONField(name="BSOShouldPayAmount") 试下？

也不行

**Comment by CodePlayer** [comment]
> > 使用@JSONField(name="BSOShouldPayAmount") 试下？
> 
> 也不行

你这个 Issue 提得貌似非常不专业：
1. 你说的那些 `@TableField`、`@TableId` 注解设置和 fastjson **有什么关系呢** ？！，那是 MyBatis 的注解，和 fastjson **完全是风马牛不相及的两码事**。fastjson 完全都不关注你的 MyBatis 的注解。
2. `@JsonProperty` 这应该是 Jackson 的注解，你加 Jackson 的注解 关 fastjson 什么事 ？只有 `@JSONField` 是 fastjson 的注解。
3. 你这个问题，连提问的标题都极其**不规范**，问题描述也没有准确地表述出来——你的期望是什么？你到底想要实现什么样的效果？

最后再回到你的问题本身，属性 `Id` 输出为 `id` 是没有问题的、`BSOShouldPayAmount` 输出为 `BSOShouldPayAmount` 也是没有问题。
JSON工具将 JavaBean 序列化为 JSON 字符串，**不是**根据 字段本身的名称来的，而是**根据 JavaBean 规范**来的，所有的JSON工具都应该遵守 JavaBean 的命名规范。
因为，字段 `Id` 的 getter 方法 为 `getId()`、`BSOShouldPayAmount` 的 getter 方法为 `getBSOShouldPayAmount()`。按照 JavaBean 规范，需要根据 getter 方法名称来获得对应的属性名，一般都是先去掉 `get` 或 `is` 前缀，再把首字母变小写。
所以，`getId()` -（去掉get前缀）-> `Id` -（首字母变小写）-> `id`，所以 fastjson 输出为小写的 `id` 是没问题的。

那为什么  `getBSOShouldPayAmount()` 并没有变成首字母小写的  `bSOShouldPayAmount` 呢 ？因为 JavaBean规范还有一条特殊规则：如果第二个字母是大写，则首字母不会转小写。比如 `getCPU()` -（去掉get前缀）-> `CPU` -（由于P大写，所以C不会变小写）-> `CPU`。

你自己可以看看 Java 自带的转换方法 `java.beans.Introspector#decapitalize(String)` 的源代码。

如果你想要将 `Id` 原样输出为 `Id`，自己加 注解 `@JSONField(name = "Id")` 即可。

**Comment by sfq28268** [comment]
> > > 使用@JSONField(name="BSOShouldPayAmount") 试下？
> > 
> > 
> > 也不行
> 
> 你这个 Issue 提得貌似非常不专业：
> 
> 1. 你说的那些 `@TableField`、`@TableId` 注解设置和 fastjson **有什么关系呢** ？！，那是 MyBatis 的注解，和 fastjson **完全是风马牛不相及的两码事**。fastjson 完全都不关注你的 MyBatis 的注解。
> 2. `@JsonProperty` 这应该是 Jackson 的注解，你加 Jackson 的注解 关 fastjson 什么事 ？只有 `@JSONField` 是 fastjson 的注解。
> 3. 你这个问题，连提问的标题都极其**不规范**，问题描述也没有准确地表述出来——你的期望是什么？你到底想要实现什么样的效果？
> 
> 最后再回到你的问题本身，属性 `Id` 输出为 `id` 是没有问题的、`BSOShouldPayAmount` 输出为 `BSOShouldPayAmount` 也是没有问题。 JSON工具将 JavaBean 序列化为 JSON 字符串，**不是**根据 字段本身的名称来的，而是**根据 JavaBean 规范**来的，所有的JSON工具都应该遵守 JavaBean 的命名规范。 因为，字段 `Id` 的 getter 方法 为 `getId()`、`BSOShouldPayAmount` 的 getter 方法为 `getBSOShouldPayAmount()`。按照 JavaBean 规范，需要根据 getter 方法名称来获得对应的属性名，一般都是先去掉 `get` 或 `is` 前缀，再把首字母变小写。 所以，`getId()` -（去掉get前缀）-> `Id` -（首字母变小写）-> `id`，所以 fastjson 输出为小写的 `id` 是没问题的。
> 
> 那为什么 `getBSOShouldPayAmount()` 并没有变成首字母小写的 `bSOShouldPayAmount` 呢 ？因为 JavaBean规范还有一条特殊规则：如果第二个字母是大写，则首字母不会转小写。比如 `getCPU()` -（去掉get前缀）-> `CPU` -（由于P大写，所以C不会变小写）-> `CPU`。
> 
> 你自己可以看看 Java 自带的转换方法 `java.beans.Introspector#decapitalize(String)` 的源代码。
> 
> 如果你想要将 `Id` 原样输出为 `Id`，自己加 注解 `@JSONField(name = "Id")` 即可。

首先感谢大佬的讲解哈！

解释一下 我的 问题只是借用之前的一个问题链接过来的，没有贴上之前的链接 是我的错哈。

现在我没有说MyBatis 的注解，和  jackson注解 与fastjson  有什么直接关系，我只是阐述案例  表象等，

因为我现有的SpringBoot项目中确实是这样的测试结果，方便我们一起探讨这其中是否有兼容性的问题等等。

SpringBoot 项目自身就是使用的jackson来反序列化数据流的，像你说的使用@JSONField(name = "Id")注解确实不能返回Id

现在的方法是的解决是重写了get方法 使用了JsonProperty注解，才得到真正返回想要的结果，如下图：

![image](https://user-images.githubusercontent.com/18158058/236761605-d74082d2-8640-4713-9e89-518ad81bf0ac.png)

以上纯属本人自测项目，如有解释不到位，还请轻喷！

**Comment by CodePlayer** [comment]
如果你用了 `@JsonProperty` 注解就有效，那就证明你一直使用的都是 Jackson，而**不是** fastjson，所以你不管怎么使用 fastjson 的注解，都没有任何作用。
你可以检查一下自己的 `HttpMessageConverter` 相关配置，是否有正确配置。

**Comment by sfq28268** [comment]
> 

之前使用的1.2.83 没有一定要是用@JsonProperty 注解才生效，现在升级到2.0.28才是这样的情况。

回归于问题的起源 还是 在（2.0.28版本） 配置中的 TypeUtils.compatibleWithFieldName = true;  没有生效   

而在没有升级之前的1.2.83 版本 是没有问题的。

PS: 当前项目中的HttpMessageConverter 配置如下：

![image](https://user-images.githubusercontent.com/18158058/236977710-23bb7d32-72da-4868-ad08-b7f2c9ad47fe.png)

**Comment by wenshao** [comment]
这个问题修复过，你帮忙试下2.0.31是否问题还存在

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/ 
这个是兼容问题，已经修复，请帮忙用2.0.32-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.32
请用新版本
