### ISSUE TITLE
[BUG]错误的注释内容

### ISSUE THREAD

**Issue by hnxiaoyuan** [alibaba/fastjson2#1434]
### 问题描述
*代码注释错误，容易造成误导*

`com.alibaba.fastjson2.annotation.JSONField`[第73行](https://github.com/alibaba/fastjson2/blob/f542abadaba0146c720788c8b3f2ebe1599423c4/core/src/main/java/com/alibaba/fastjson2/annotation/JSONField.java#LL73C68-L73C68)中的注释应该是`ObjectReader`

**Comment by wenshao** [comment]
帮忙提交个PR修正？
