### ISSUE TITLE
无法全局统一设置默认 dateFormat

### ISSUE THREAD

**Issue by CodePlayer** [alibaba/fastjson2#1437]
fastjson1 对 `Date` 类型默认输出为 毫秒级 的时间戳，然而 fastjson2 默认输出的是格式化后的字符串。
我们想保持与 fastjson1 的向后兼容性，想要全局设置 `dateFormat = "millis"`，以确保全局默认输出为 毫秒级的时间戳。
但是，不管是搜索历史的 issue，还是查找源代码，貌似都没有看到全局的 `dateFormat` 设置API。

目前已知的，都是针对单个 `FastJsonConfig` 对象进行传入设置，但是如果调用的是 `com.alibaba.fastjson2.JSON#toJSONString(java.lang.Object)` 这种原生方法，仍然无法全局生效。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.30-SNAPSHOT/
帮忙用2.0.30-SNAPSHOT验证，2.0.30预计在周末（5月7日前）发布

新增加API
```java
package com.alibaba.fastjson2;

interface JSON {
     static void configReaderDateFormat(String dateFormat);
     static void configWriterDateFormat(String dateFormat);
}
```

**Comment by CodePlayer** [comment]
本地在 开发环境 和 测试环境 测试过，暂时没发现任何问题。
我也看了一下源代码，应该是 OK 的。

不过目前我看 `Context` 每次都是 `new` 的。其实在大多数情况下，用户定制JSON输出的场景还是相对比较少的。
那么，我在考虑，是否可以提供一个全局的 `Context`。如果用户不传入自定义的 `Context` 或 自定义的 `Filter`/`Feature` 等定制参数，就直接使用全局默认的 `Context`，避免每次 `new`，也避免了每次重复整合 `Feature` 以及 `Filter` 的计算开销。
用户要修改全局配置，直接修改这个全局的 `Context` 即可（ 如需修改，最好是让用户 `new` 一个新的 来替换，避免过程中可能存在的并发冲突）。

**Comment by wenshao** [comment]
这个开销比较小，不过你的建议可考虑的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.30
请用新版本

**Comment by hks2002** [comment]
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.alibaba.fastjson2.JSON;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        JSON.configWriterDateFormat("yyyy-MM-dd");
        SpringApplication.run(Application.class, args);
    }
}
