### ISSUE TITLE
[BUG] set 中存在 null 值导致序列化丢失分隔符

### ISSUE THREAD

**Issue by xuender** [alibaba/fastjson2#1439]
### 问题描述
set 中存在 null 值导致序列化丢失分隔符

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤

```java
Set<Long> a = new HashSet<>();
a.add(null);
a.add(666L);
System.out.println(JSON.toJSONString(a));
```

### 期待的正确结果
[null,666]

### 相关日志输出
[null666]

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.31-SNAPSHOT/
问题已修复，请帮忙用2.0.31-SNAPSHOT版本验证，2.0.31版本预计在5月27日前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.31
请用新版本
