### ISSUE TITLE
[QUESTION] 取消自动解码unicode

### ISSUE THREAD

**Issue by cloud-jie** [alibaba/fastjson2#1441]
System.out.println(JSON.parseObject("{\"ad\":\"\\u738Bi\\u897F\"}"));
输出结果：
{"ad":"王i西"}
预期结果：
{"ad":"\u738Bi\u897F"}

**Comment by wenshao** [comment]
用JSONWriter.Feature.EscapeNoneAscii看下是不是你想要的，如下：
```java
JSON.toJSONString(obj, JSONWriter.Feature.EscapeNoneAscii)
```

**Comment by wenshao** [comment]
EscapeNoneAscii 不能满足需求么？
