### ISSUE TITLE
[BUG] Code contains multiple always true / false comparisons

### ISSUE THREAD

**Issue by Marcono1234** [alibaba/fastjson2#1442]
- `JSONReaderASCII` and `JSONReaderUTF8` contain multiple checks similar to `c <= 0xFF`, where `c` is a `byte`. These checks are always true because the maximum value of `byte` is 127 and `0xFF` is 255. For example:
  - https://github.com/alibaba/fastjson2/blob/f3a464699e22ebc1523c0247db312564c1de00bc/core/src/main/java/com/alibaba/fastjson2/JSONReaderASCII.java#L164
  - https://github.com/alibaba/fastjson2/blob/f3a464699e22ebc1523c0247db312564c1de00bc/core/src/main/java/com/alibaba/fastjson2/JSONReaderUTF8.java#L601

- `JSONStreamReaderUTF16` and `CSVReaderUTF16` check if values from a `char[]` are negative. This is always false because the minimum value of `char` is 0:
  - https://github.com/alibaba/fastjson2/blob/f3a464699e22ebc1523c0247db312564c1de00bc/core/src/main/java/com/alibaba/fastjson2/stream/JSONStreamReaderUTF16.java#L43
  - https://github.com/alibaba/fastjson2/blob/f3a464699e22ebc1523c0247db312564c1de00bc/core/src/main/java/com/alibaba/fastjson2/support/csv/CSVReaderUTF16.java#L94

- `StreamReader` checks if a `char` is `< 0`. This is always false because the minimum value of `char` is 0:
https://github.com/alibaba/fastjson2/blob/f3a464699e22ebc1523c0247db312564c1de00bc/core/src/main/java/com/alibaba/fastjson2/stream/StreamReader.java#L144

I haven't investigated what the correct implementation for each of these would be because I am not familiar with the code base, you would have to do this yourself, sorry. Also I haven't checked whether this was already reported as separate bug reports where users experienced incorrect behavior due to this.

Maybe it would be good to investigate using Error Prone (see [ComparisonOutOfRange rule](https://errorprone.info/bugpattern/ComparisonOutOfRange)) or SpotBugs. They might find these issues, and prevent similar issues in the future.

**Comment by wenshao** [comment]
fixed, thank you for feedback on these issues!

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.31
please use new version
