### ISSUE TITLE
[QUESTION] 通过fastjson2序列化高效，还是自己写一个函数遍历函数体高效？

### ISSUE THREAD

**Issue by RemHero** [alibaba/fastjson2#1443]
### fastjson2效率考究
我的需求是，有一个复杂的嵌套类S，最终需要通过thrift传输。我有两种实现方案：
1、通过fastjson2将S序列化后，通过thrift以string形式传输
2、在thrift中对应的结构体T，然后自己写函数将S映射到T，然后再通过thrift传输

第一种方法需要序列化两遍，第二种方法需要自己遍历函数体，我想知道哪方法更高效？
我已经查阅过相关资料，了解到fastjson2很快 https://blog.csdn.net/chenthe1/article/details/129136618
所以我想知道用哪种方法更好？

**Comment by wenshao** [comment]
可能fastjson2序列化更快，建议你自己做benchmark比较
