### ISSUE TITLE
fastjson2中没有做JSONObject.getString(LocalDate)的兼容

### ISSUE THREAD

**Issue by justToBeGood** [alibaba/fastjson2#1446]
toJSONString()对LocalDate的序列化做了兼容，但是getString()没有。
fastjson1.0中getString()是调用LocalDate的重写的toString()，不加双引号
![image](https://user-images.githubusercontent.com/50023670/236594712-b72c1eee-1cb6-4b04-8c8d-8e8286720d12.png)
fastjson2.0中getString()这里的判断导致执行了JSON.toJSONString(LocalDate），加双引号
![image](https://user-images.githubusercontent.com/50023670/236594814-6804f00f-4592-4124-8698-21bbc52f612b.png)
实例代码：
    @Test
    public void test2(){
        com.alibaba.fastjson.JSONObject json1 = new com.alibaba.fastjson.JSONObject();
        JSONObject json2 = new JSONObject();
        LocalDate now = LocalDate.now();
        json1.put("date", now);
        json2.put("date", now);
        System.out.println(json1.getString("date"));
        System.out.println(json2.getString("date"));
        System.out.println(JSON.toJSONString(json1));
        System.out.println(JSON.toJSONString(json2));
        System.out.println(com.alibaba.fastjson.JSON.toJSONString(json1));
        System.out.println(com.alibaba.fastjson.JSON.toJSONString(json2));
        System.out.println(JSON.toJSONString(now));
        System.out.println(com.alibaba.fastjson.JSON.toJSONString(now));
        System.out.println(com.alibaba.fastjson.JSON.VERSION);
        System.out.println(JSON.VERSION);
    }

_Originally posted by @justToBeGood in https://github.com/alibaba/fastjson2/issues/447#issuecomment-1537021920_

**Comment by wenshao** [comment]
这个是问题，你能帮忙提交个PR参与进来么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/
已发布快照版本，请帮忙用2.0.32-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.32
请用新版本
