### ISSUE TITLE
[QUESTION]fastjson2 的 serializeUsing属性 不再支持了？

### ISSUE THREAD

**Issue by zhaobo3k** [alibaba/fastjson2#1449]
fastjson2 的 serializeUsing属性 不再支持了？

在@JSONField 上的这个属性，以前通过实现ObjectSerializer可以生效，现在这个接口没有了，尝试用ObjectWriter也无法生效
或者是我的打开方式不对？

**Comment by wenshao** [comment]
有啊，你用的是什么版本

**Comment by zhaobo3k** [comment]
用的是最新的2.0.31
`
//将boolean转换成YN显示
public class JsonBoolSerializer implements ObjectWriter<Boolean> {

    //public static JsonBoolSerializer INSTANCE = new JsonBoolSerializer();

    public void write(JSONWriter jsonWriter, Object object) {
        if (object == null) {
            jsonWriter.writeNull();
        } else {
            String strVal = object.toString();
            if (strVal.equals("true")) {
                jsonWriter.writeString("Y");
            } else {
                jsonWriter.writeString("N");
            }
        }

    }
}

`

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/
已发布快照版本，请帮忙用2.0.32-SNAPSHOT版本验证下。

**Comment by Q10Viking** [comment]
> 
Fastjson v1兼容模块,有ObjectSerializer这个类
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>fastjson</artifactId>
    <version>2.0.31</version>
</dependency>
```
------------
但是Fastjson 2 里面没有ObjectSerializer这个类
```xml
<dependency>
    <groupId>com.alibaba.fastjson2</groupId>
    <artifactId>fastjson2</artifactId>
    <version>2.0.32</version>
</dependency>
```
看注释是说
```java
/**
     * Specifies that {@link com.alibaba.fastjson2.writer.ObjectWriter} is used when serializing
     */
    @SuppressWarnings("rawtypes")
    Class serializeUsing() default Void.class;
```
是不在fastjson2中用ObjectWriter替换了fastjson1的 ObjectSerializer？

**Comment by zhaobo3k** [comment]
2.0.32版本已经修复了
