### ISSUE TITLE
[BUG]JSONB反序列化异常 fastjson2 2.0.31

### ISSUE THREAD

**Issue by kaizen84** [alibaba/fastjson2#1451]
复现代码
https://github.com/kaizen84/dubbo-test/blob/master/dubbo-consumer/src/test/java/top/rows/dubbo/test/consumer/FastjsonTest.java
可以的话再测一下，这个类里的dubbo的泛化调用 ，异常有点不一样，感谢大佬
https://github.com/kaizen84/dubbo-test/blob/master/dubbo-consumer/src/test/java/top/rows/dubbo/test/consumer/ConsumerTest.java

**Comment by kaizen84** [comment]
![image](https://user-images.githubusercontent.com/49264728/236799996-503327be-0103-47b1-8dde-f31856c20f6f.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/
问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证。

原因是Object Key导致，比如：
```json
{
	"stackable":{
		"coupon":true,
		"payTimeout":{
			"zero":false,
			"seconds":0,
			"negative":false,
			"nano":30000000,
			"units":[
				"SECONDS",
				"NANOS"
			],
			"class":"java.time.Duration"
		},
		"vip":true,
		"class":"top.rows.dubbo.test.api.model.StackableDiscount",
		"full":true
	},
	"extra":{
		"@type":"JSONObject#0",
		"@value":{
			"teamNo":"TM20210508100001"
		}
	},
	"class":"top.rows.dubbo.test.api.model.ActivityResp",
	"skuKeyPriceMap":{
		{
			"productId":2,
			"shopId":2,
			"class":"top.rows.dubbo.test.api.model.ShopProductSkuKey",
			"skuId":2
		}:100
	}
}
```

**Comment by kaizen84** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/ 问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证。
> 
> 原因是Object Key导致，比如：
> 
> ```json
> {
> 	"stackable":{
> 		"coupon":true,
> 		"payTimeout":{
> 			"zero":false,
> 			"seconds":0,
> 			"negative":false,
> 			"nano":30000000,
> 			"units":[
> 				"SECONDS",
> 				"NANOS"
> 			],
> 			"class":"java.time.Duration"
> 		},
> 		"vip":true,
> 		"class":"top.rows.dubbo.test.api.model.StackableDiscount",
> 		"full":true
> 	},
> 	"extra":{
> 		"@type":"JSONObject#0",
> 		"@value":{
> 			"teamNo":"TM20210508100001"
> 		}
> 	},
> 	"class":"top.rows.dubbo.test.api.model.ActivityResp",
> 	"skuKeyPriceMap":{
> 		{
> 			"productId":2,
> 			"shopId":2,
> 			"class":"top.rows.dubbo.test.api.model.ShopProductSkuKey",
> 			"skuId":2
> 		}:100
> 	}
> }
> ```

已验证，已解决

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.32
请用新版本

**Comment by kaizen84** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.32 请用新版本

收到
