### ISSUE TITLE
[BUG]FastJson1.X升级2.X开启智能匹配结果特定场景不符合预期

### ISSUE THREAD

**Issue by dxf1595** [alibaba/fastjson2#1460]
### 问题描述
FastJson1.X升级2.X开启智能匹配结果特定场景不符合预期

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win10]
 - JDK信息： [e.g.：jdk 1.8.0_312]
 - 版本信息：\- com.alibaba:fastjson:jar:2.0.29:compile
[INFO]    \- com.alibaba.fastjson2:fastjson2-extension:jar:2.0.29:compile
[INFO]       \- com.alibaba.fastjson2:fastjson2:jar:2.0.29:compile
 - 开启智能匹配 JSONReader.Feature.SupportSmartMatch
 

### 重现步骤
该错误发生的条件：
1，类有带参数的构造函数，没有无参构造函数。如果没有带参数的构造函数则不会有问题。
2，字符串和参数类字段名不一致，且不是标准的命名规则。如”userName“与”username“。如果是”userName“、”user_name“、”UserName“等标准命名规则则也不会有问题，之间可以正常匹配。

示例代码：

```
class User {
        private String userName;

        public User(String userName) {
            this.userName = userName;
        }

        public String getUserName() {
            return userName;
        }

        public void setUserName(String userName) {
            this.userName = userName;
        }
    }

 public static void main(String[] args) {
        String value = "{\"username\":\"zhangsan\"}";
        User user = JSON.parseObject(value, User.class, JSONReader.Feature.SupportSmartMatch);
    }

```
![image](https://github.com/alibaba/fastjson2/assets/17734812/130ea758-c873-4421-a20c-7ee639b2a0c0)
![image](https://github.com/alibaba/fastjson2/assets/17734812/02f9a8a7-17ef-4f15-93e9-3d7311b1c969)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/
问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.32
请用新版本

**Comment by xigpz** [comment]
redis序列化用value时候 ，fastjson 1.x升级2.x，对于存在括号等字符，导致2.x生成的byte数组长度小于1.x生成的byte数组长度，导致json字符串无法匹配
