### ISSUE TITLE
[BUG] 使用lombok时，@JSONField 注解在方法上时 serializeUsing无效

### ISSUE THREAD

**Issue by zhaobo3k** [alibaba/fastjson2#1461]
当  @JSONField(serializeUsing = XXX.class) 注解在对象属性上时，序列化正常，但是注解在方法上时，serializeUsing属性没有发挥作用；

比如：
```

import com.alibaba.fastjson2.annotation.JSONField;
import com.wbs.run.convert.Bool2Yn;
import lombok.Data;

@Data
public class DemoBean {

     // Boolean被正确序列化为预期结果:Y/N

    @JSONField(serializeUsing = Bool2Yn.class) 
    private Boolean saleYn;


   // Boolean仍然序列化为常规结果：true/false 

    @JSONField(serializeUsing = Bool2Yn.class)  
    public Boolean validYn() {
        return true;
    }

}
```

结果
```
{
	"saleYn":"Y",
	"validYn":true
}
```

 - OS信息：  mac
 - JDK信息： Openjdk 17
 - 版本信息：Fastjson2 2.0.31

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/
问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.32
请用新版本
