### ISSUE TITLE
[BUG] 使用Spring Security时，实体类实现UserDetails时使用@JSONField(serialize = false)不序列化authorities无效

### ISSUE THREAD

**Issue by TsukasaHwan** [alibaba/fastjson2#1465]
使用Spring Security时，实体类实现UserDetails时使用@JSONField(serialize = false)不序列化authorities无效

    public static void main(String[] args) {
        TestUser testUser = new TestUser();
        testUser.setUsername("test");
        testUser.setPassword("123456");
        testUser.setAuthorities(Sets.newHashSet());
        String s = JSON.toJSONString(testUser);
        System.out.println(s);
    }

    @Data
    public static class TestUser implements UserDetails {
        private String username;

        private String password;

        @JSONField(serialize = false)
        private Set<GrantedAuthority> authorities;

        @Override
        @JSONField(serialize = false)
        public boolean isAccountNonExpired() {
            return true;
        }

        @Override
        @JSONField(serialize = false)
        public boolean isAccountNonLocked() {
            return true;
        }

        @Override
        @JSONField(serialize = false)
        public boolean isCredentialsNonExpired() {
            return true;
        }

        @Override
        @JSONField(serialize = false)
        public boolean isEnabled() {
            return true;
        }
    }

输出结果为{"authorities":[],"password":"123456","username":"test"}
期望为{"password":"123456","username":"test"}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/
问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证。

**Comment by TsukasaHwan** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.32-SNAPSHOT/ 问题已修复，请帮忙用2.0.32-SNAPSHOT版本验证。

已验证，没问题了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.32
请用新版本
