### ISSUE TITLE
[BUG]dubbo 3.2.0引用的fastjson   传输时报错

### ISSUE THREAD

**Issue by songlongkuan** [alibaba/fastjson2#1485]
### 问题描述
*简要描述您碰到的问题。*

一个参数和返回值都为String的dubbo接口，确序列化出错了
autoType not support input javax.validation.NoProviderFoundException

    @Path("getPerson")
    String getPerson(@QueryParam("source") String source);

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g. Macos]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.27]
 

### 重现步骤
*如何操作可以重现该问题：*
 dubbo调用 必现
1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: getMetadataInfo, provider: dubbo://172.25.171.133:8001/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=dubbo-provider&port=8001&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.0&retries=0&side=provider&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: com.alibaba.fastjson2.JSONException: autoType not support input javax.validation.NoProviderFoundException
com.alibaba.fastjson2.JSONException: autoType not support input javax.validation.NoProviderFoundException
	at com.alibaba.fastjson2.JSONReaderJSONB.checkAutoType(JSONReaderJSONB.java:1200)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:527)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:118)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:103)
	at org.apache.dubbo.common.serialize.ObjectInput.readThrowable(ObjectInput.java:74)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.33
请用新版本
