### ISSUE TITLE
[BUG] jsonpath 包含点无法支持

### ISSUE THREAD

**Issue by zhangzhenling** [alibaba/fastjson2#1487]
### 问题描述
使用版本：2.0.27
样例数据：{'P1Q1': {1.0: '选项 1', 2.0: '选项 2', 3.0: '选项 3'}}

使用：```JSONObject.parse(result) ```
报错信息：`com.alibaba.fastjson2.JSONException: illegal input ., offset 1358, character .`

在fastjson1 中可以支持的

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/
问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.33
请用新版本
