### ISSUE TITLE
[QUESTION] 反序列化 typeKey使用请教

### ISSUE THREAD

**Issue by Mrwcz** [alibaba/fastjson2#1488]
我在反序列化不同子类对象时给typeKey配置一个自定义字段“aniType”，
如果aniType是String类型时，运行下面test()方法运行正常，可以得到正确的子对象；
如果aniType是Int类型时，运行下面test()方法直接报错
com.alibaba.fastjson2.JSONException: No suitable ObjectReader found foraniType, offset 12, character 1, line 1, column 13, fastjson-version 2.0.32 {"aniType":1,"dogName":"dog1001"}

请问aniType为Int类型时，需要如何配置可以正常解析？

```java
@JSONType(seeAlso={Dog.class, Cat.class},typeKey = "aniType")
   public static class Animal {
      public int aniType;
   }

   @JSONType(typeName = "1" )
   public static class Dog extends Animal {
      public String dogName;
   }

   @JSONType(typeName = "2" )
   public static class Cat extends Animal {
      public String catName;
   }

   public static void test(){
      Dog dog = new Dog();
      dog.dogName = "dog1001";
      dog.aniType = 1;

      String text = JSON.toJSONString(dog);
      Dog cat = (Dog) JSON.parseObject(text,Animal.class);
   }
```

**Comment by wenshao** [comment]
目前还不支持non-string typeName，我考虑下怎么支持

**Comment by Mrwcz** [comment]
> extends

好的，谢谢关注

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/
问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

**Comment by Mrwcz** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/ 问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

用上面版本试过可以了，多谢🙏

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.33
请用新版本
