### ISSUE TITLE
[BUG]序列化Map类型时输出的JSON的key不是字符串

### ISSUE THREAD

**Issue by fmjsjx** [alibaba/fastjson2#1492]
### 问题描述
有一个Map，并且Map的Key不是String类型时，
通过`JSON.toJSONString`序列化的JSON字符串中，key不会自动转换成字符串，
会导致**输出的不是标准JSON**

### 环境信息
*请填写以下信息：*

 - OS信息： 任意
 - JDK信息： 任意
 - 版本信息：Fastjson2 2.0.32
 

### 重现步骤

1. 创建一个Map<Integer, Integer>
2. 为Map赋值：1 => 1, 2 =>2, 3=> 3
3. 打印`JSON.toJSONString()`输出的结果：`{1:1,2:2,3:3}`
```java
    public static void main(String[] args) {
        Map<Integer, Integer> map = new LinkedHashMap<>();
        map.put(1, 1);
        map.put(2, 2);
        map.put(3, 3);
        System.out.println(JSON.toJSONString(map));
    }
```

### 期待的正确结果
正确的JSON字符串应当为：`{"1":1,"2":2,"3":3}`

**Comment by yanxutao89** [comment]
貌似显示指定就可以，如下所示：
JSON.toJSONString(map, JSONWriter.Feature.WriteNonStringKeyAsString)

**Comment by fmjsjx** [comment]
> 貌似显示指定就可以，如下所示： JSON.toJSONString(map, JSONWriter.Feature.WriteNonStringKeyAsString)

好的，谢谢
