### ISSUE TITLE
[QUESTION] JSONPObject这个是不支持了吗?返回JSONP之后,参数都被序列化了,请问这个该如何设置呢

### ISSUE THREAD

**Issue by qingqingdaxia** [alibaba/fastjson2#1493]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
JSONPObject找不到了,这个是不支持了吗?

**Comment by qingqingdaxia** [comment]
JSONPObject jsonp = new JSONPObject(callBack,data);
            JsonGenerator gen = new JsonGenerator();
            try {
                jsonp.serializeWithType(gen, null, null);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }

            String str = gen.getJSONWriter().toString();
            return jsonp;
接口返回的时候都给序列化了{
	"function": "abc",
	"value": {
		"code": "0000"}}

**Comment by qingqingdaxia** [comment]
![图片](https://github.com/alibaba/fastjson2/assets/21982180/f2632e81-f9aa-4d5b-8d5e-b989f2b16520)
以前fastjson1有这个jsonp的判断的,fastjson2没找到这个判断

**Comment by qingqingdaxia** [comment]
大神,我看你改成bug了,请问一下,这个JSONP的返回判断会添加到FastJsonHttpMessageConverter里面吗?

**Comment by qingqingdaxia** [comment]
@wenshao

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.33-SNAPSHOT/
问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

**Comment by qingqingdaxia** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.33-SNAPSHOT/ 问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

@wenshao 收到!我下周验证一下.验证结果出来了,及时同步到这里.麻烦了,谢谢

**Comment by qingqingdaxia** [comment]
> > https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.33-SNAPSHOT/ 问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。
> 
> @wenshao 收到!我下周验证一下.验证结果出来了,及时同步到这里.麻烦了,谢谢

@wenshao 已测试,返回JSONP参数正常了,谢谢.期待release版本
