### ISSUE TITLE
[BUG]日期格式化问题

### ISSUE THREAD

**Issue by zacat** [alibaba/fastjson2#1497]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows 10]
 - JDK信息： [e.g.：Openjdk 19]
 - 版本信息：[e.g.：Fastjson2 2.0.32]
 
日期输出
   2023-05-19 通过 JSONWriterUTF8.writeDateYYYMMDD10 函数后变成 20230519

修改前
 @Override
    public final void writeDateYYYMMDD10(int year, int month, int dayOfMonth) {
        int minCapacity = off + 12;
        if (minCapacity >= bytes.length) {
            ensureCapacity(minCapacity);
        }

        bytes[off++] = (byte) quote;
        write4(year, bytes, off);
        off += 4;
        bytes[off + 5] = '-';
        write2(month, bytes, off);
        off += 2;
        bytes[off + 8] = '-';
        write2(dayOfMonth, bytes, off);
        off += 2;
        bytes[off++] = (byte) quote;
    }

修改后
@Override
    public final void writeDateYYYMMDD10(int year, int month, int dayOfMonth) {
        int minCapacity = off + 12;
        if (minCapacity >= bytes.length) {
            ensureCapacity(minCapacity);
        }

        bytes[off++] = (byte) quote;
        write4(year, bytes, off);
        off += 4;
        bytes[off++] = '-';
        write2(month, bytes, off);
        off += 2;
        bytes[off++] = '-';
        write2(dayOfMonth, bytes, off);
        off += 2;
        bytes[off++] = (byte) quote;
    }

**Comment by wenshao** [comment]
你提交个PR吧
