### ISSUE TITLE
[BUG]LocalDate类型的默认时间【1900-01-01】返回加上@JSONField(format = "yyyy-MM-dd") 不起作用

### ISSUE THREAD

**Issue by sfq28268** [alibaba/fastjson2#1502]
### 问题描述
LocalDate类型的字段为数据库默认时间【1900-01-01】返回加上@JSONField(format = "yyyy-MM-dd") 不起作用 如下图代码：
![image](https://github.com/alibaba/fastjson2/assets/18158058/37c7301c-764e-49c3-8340-f149c0287d77)

返回后的结果为 “19000101” 没有按照 format 格式输出
![image](https://github.com/alibaba/fastjson2/assets/18158058/c8b38a12-67c9-487a-84ea-b238a9351c74)

反序列化“19000101”也会报错  如下图 
![image](https://github.com/alibaba/fastjson2/assets/18158058/87d50597-d53f-4fdd-bdc3-30248ee1809d)

而 在1.2.83版本不会报错，会原样输入
![image](https://github.com/alibaba/fastjson2/assets/18158058/38c0f63c-e24d-4051-80c8-e9c1410dda12)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.32]

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/
问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.33
请用新版本

**Comment by BruceAn1978** [comment]
我使用2.0.37版本还是存在这个问题
![image](https://github.com/alibaba/fastjson2/assets/39219907/3ca376db-c14f-418c-8eed-bfa24cadd415)
![image](https://github.com/alibaba/fastjson2/assets/39219907/c456d2a2-5b9a-41d6-82f7-ef9f1c06b132)
