### ISSUE TITLE
设置safeMode=true后AutoType的转换问题

### ISSUE THREAD

**Issue by Allen123Hao** [alibaba/fastjson2#1503]
当vm设置-Dfastjson2.parser.safeMode=true后不支持AutoType没问题，但是设置了JSONReader.autoTypeFilter后，转换的对象也会丢失子类的属性，请问怎么回事？
Filter AUTO_TYPE_FILTER = JSONReader.autoTypeFilter("org.example.model");
String json = JSON.toJSONString(versionInfo,
                JSONWriter.Feature.WriteClassName);
        System.out.println(json);
        VersionInfo versionInfo1 = JSON.parseObject(bytes,VersionInfo.class,AUTO_TYPE_FILTER);
        System.out.println(JSON.toJSONString(versionInfo1));
打印结果：
{"appVersion":{"@type":"org.example.model.CustomerAppVersion","appVersion":"v1.1.0","platform":1},"userName":"Allen","version":"v1"}
{"appVersion":{"appVersion":"v1.1.0"},"userName":"Allen","version":"v1"}
反序列化丢失了platform属性。

**Comment by wenshao** [comment]
这个问题修复过，帮忙用2.0.32版本验证下

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/
问题已修复，请帮忙用2.0.33-SNAPSHOT版本验证。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.33
请用新版本
