### ISSUE TITLE
[BUG]fastjson反序列化一个字段有多个set

### ISSUE THREAD

**Issue by fatebugs** [alibaba/fastjson2#1506]
### 问题描述
fastjson反序列化一个字段有多个set怎么选默认的set
比如说我需要使用这张图里第一个set方法来反序列化
这是否是一个Bug，或者能否有一个注解来标注默认序列化和反序列化的方法
![image](https://github.com/alibaba/fastjson2/assets/65278566/4612cf9b-9055-4046-80d7-0036fcc3b446)

**Comment by wenshao** [comment]
已经支持通过@JSONField来配置，有@JSONFIeld的优先

https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.33-SNAPSHOT/

请帮忙用2.0.33-SNAPSHOT版本验证

**Comment by fatebugs** [comment]
不知道为什么，我校验不了，我下载不到fastjson2-parent:pom:2.0.33-SNAPSHOT
这导致我不能在项目中使用
