### ISSUE TITLE
[BUG]使用SpringRedis集成fastjson执行lua脚本bug

### ISSUE THREAD

**Issue by TsukasaHwan** [alibaba/fastjson2#1510]
### 问题描述
使用SpringRedis集成fastjson时使用RedisTemplate的`execute()`方法执行lua脚本时，如果参数传为基本数据类型long时，序列化出来的字节数组会带一个`L`字节的标识，导致执行lua脚本提示@user_script:6: ERR value is not an integer or out of range

![1685274249003](https://github.com/alibaba/fastjson2/assets/46735688/893ba1a5-f92d-4254-8bdd-58e93e7bf049)
![1685274249024](https://github.com/alibaba/fastjson2/assets/46735688/a0d344d6-880d-43a6-a2cb-8173c4baa6bc)
76对应的ASCII为L

**Comment by wenshao** [comment]
什么版本？是不是配置了WriteClassName

**Comment by TsukasaHwan** [comment]
> 什么版本？是不是配置了WriteClassName

2.0.32，对配置了WriteClassName

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.34-SNAPSHOT/
帮用2.0.23-SNAPSHOT版本配置如下参数验证下
```java
JSONWriter.Feature.NotWriteNumberClassName
```

**Comment by TsukasaHwan** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.34-SNAPSHOT/ 帮用2.0.23-SNAPSHOT版本配置如下参数验证下
> 
> ```java
> JSONWriter.Feature.NotWriteNumberClassName
> ```

验证没问题了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.34
问题已修复，请用新版本
