### ISSUE TITLE
[BUG]2.0.32 同一个属性 子类serialize = true 父类serialize = false 序列化后字段不存在

### ISSUE THREAD

**Issue by TomZhang0507** [alibaba/fastjson2#1513]
### 问题描述
同一个属性 子类serialize = true 父类serialize = false 序列化后字段不存在

### 环境信息
  <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>fastjson</artifactId>
      <version>2.0.32</version>
  </dependency>

### 重现步骤
![image](https://github.com/alibaba/fastjson2/assets/20785477/95082934-6bb9-43c5-99fa-bb521b467ad6)
![image](https://github.com/alibaba/fastjson2/assets/20785477/0d55e867-3589-46ac-afb7-859ac27143e5)
![image](https://github.com/alibaba/fastjson2/assets/20785477/7c03931e-c836-4cad-8f95-4b564c98254c)
序列化之后config字段不存在

跟了一下源码 
/.m2/repository/com/alibaba/fastjson2/fastjson2/2.0.32/fastjson2-2.0.32-sources.jar!/com/alibaba/fastjson2/writer/ObjectWriterBaseModule.java:319
这个类的
![image](https://github.com/alibaba/fastjson2/assets/20785477/0f96f31e-4f18-43db-b929-d14d274e993c)
这一段方法 只处理了隐藏字段，当父类隐藏 子类显示的时候就会出现子类设置不生效的情况。怀疑是bug。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.34-SNAPSHOT/
问题已修复，请帮忙用2.0.23-SNAPSHOT版本验证看问题是否还存在

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/edit/2.0.34
问题已修复，请用新版
