### ISSUE TITLE
用native-image 编译,有许多这样的告警,Warning: RecomputeFieldValue.FieldOffset automatic substitution failed.

### ISSUE THREAD

**Issue by zhonghuali** [alibaba/fastjson2#1519]
用native-image 编译,有许多这样的告警:
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.a
libaba.fastjson2.writer.ObjectWriterImplMap. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., The field com.alibaba.fastjson2.writer.ObjectWriterImplMap.jsonObject1InnerMapOffset,
 where the value produced by the field offset computation is stored, is not static final.

请问如何消除掉?
谢谢

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.34-SNAPSHOT/
帮用这个版本再看下，具体的告警信息帖上来，我挨个处理

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/edit/2.0.34
问题已修复，请用新版

**Comment by lizhen789** [comment]
![image](https://github.com/user-attachments/assets/01817703-2dfc-4b82-bd30-d736e3d35be5)
版本：2.0.52，springboot 3.3.3
