### ISSUE TITLE
请问fastjson2 中filter如何使用，从1升级到2，发现过滤使用方法不一样了 [QUESTION]

### ISSUE THREAD

**Issue by GitACDreamer** [alibaba/fastjson2#1525]
### 请描述您的问题
fastjson2如何使用过滤
*询问有关本项目的使用和其他方面的相关问题。*
//日志数据太长的直接过滤掉
```
PropertyFilter filter= (o, name, value) -> {
    int length = 500;
    return value == null || value.toString().length() <= length;
};
params = new StringBuilder(JSONObject.toJSONString(arguments, filter));
```
发现在fastjson2中 toJSONString无法这样使用了，fastjson2如何使用filter

**Comment by GitACDreamer** [comment]
v1当中是有个重载函数 `static String toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)`
![image](https://github.com/alibaba/fastjson2/assets/19402747/e84d154b-8c4c-4ced-a13c-fbee33e08af4)

**Comment by zoze0** [comment]
> v1当中是有个重载函数 `static String toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)` ![image](https://user-images.githubusercontent.com/19402747/242771032-e84d154b-8c4c-4ced-a13c-fbee33e08af4.png)

fastjson2 也有这个方法呀, 我这边试了propertyFilter可以过滤

**Comment by GitACDreamer** [comment]
@zoze0  找到区别了 ，我前面用不兼容模式： 引入：`import com.alibaba.fastjson2.JSONObject;` 是没有上面说的这个函数， 把库引入改成 `import com.alibaba.fastjson.JSONObject;` 是可兼容的，有这个函数`static String toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)` , 这个后面使用不兼容模式如何处理？
·

**Comment by zoze0** [comment]
> @zoze0 找到区别了 ，我前面用不兼容模式： 引入：`import com.alibaba.fastjson2.JSONObject;` 是没有上面说的这个函数， 把库引入改成 `import com.alibaba.fastjson.JSONObject;` 是可兼容的，有这个函数`static String toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)` , 这个后面使用不兼容模式如何处理？ ·

fastjson2 使用 `JSON.toJSONString` , JSONObject的toJSONString似乎没有这个重载函数

**Comment by GitACDreamer** [comment]
@zoze0 好的，谢谢您，已解决

> > @zoze0 找到区别了 ，我前面用不兼容模式： 引入：`import com.alibaba.fastjson2.JSONObject;` 是没有上面说的这个函数， 把库引入改成 `import com.alibaba.fastjson.JSONObject;` 是可兼容的，有这个函数`static String toJSONString(Object object, SerializeFilter filter, SerializerFeature... features)` , 这个后面使用不兼容模式如何处理？ ·
> 
> fastjson2 使用 `JSON.toJSONString` , JSONObject的toJSONString似乎没有这个重载函数
