### ISSUE TITLE
[BUG]2.0.32 对象转换出错，2.0.31无此问题

### ISSUE THREAD

**Issue by sobuh** [alibaba/fastjson2#1527]
### 问题描述
FastJsonHttpMessageConverter 报错，不好排查问题，就写了下面的例子，结果也报错
at com.alibaba.fastjson2.JSON.writeTo(JSON.java:3168)
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:131)
	... 60 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method)
	at com.alibaba.fastjson2.util.IOUtils.getDecimalChars(IOUtils.java:276)
	at com.alibaba.fastjson2.JSONWriterUTF8.writeDecimal(JSONWriterUTF8.java:2277)
	at com.alibaba.fastjson2.writer.OWG_64_28_WinCandidateVo.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:373)
	at com.alibaba.fastjson2.JSON.writeTo(JSON.java:3163)
	... 61 common frames omitted

### 测试例子
@Data
public class WinCandidateVo implements Serializable {

    /** ID */
    private Long id;
    private Short dataType;
    private Long businessId;
    private Long bidSectionId;
    private Short examType;
    private String tenderProjectCode;
    private String bidSectionCode;
    private String unifiedDealCode;
    private Long winCandidateId;
    private String winCandidateName;
    private String bidderCodeType;
    private String winCandidateCode;
    private Short winCandidateOrder;
    private Short isWinBidder;
    private String evaluationResult;
    private Short priceFormCode;
    private BigDecimal bidPrice;
    private String priceCurrency;
    private Short priceUnit;
    private String otherBidPrice;
    private String platformCode;
    private String pubServicePlatCode;
    private String tradePlat;
    private String pubServicePlat;
    private String remark;
    private BigDecimal score;
    private String address;
    private String linkPhone;
    public void setBidPrice(BigDecimal bidPrice) {
        this.bidPrice = bidPrice==null?bidPrice:bidPrice.stripTrailingZeros();
    }
}

public static void main(String[] args) throws Exception {
        String arr = "[{\"bidPrice\":2E+2,\"bidSectionId\":1664532788087062529,\"bidderCodeType\":\"\",\"examType\":2,\"isWinBidder\":1,\"otherBidPrice\":\"\",\"priceCurrency\":\"156\",\"priceUnit\":1,\"remark\":\"\",\"score\":10.000,\"winCandidateCode\":\"130301198505058776\",\"winCandidateId\":1659808515294371841,\"winCandidateName\":\"投标人tbr2204\",\"winCandidateOrder\":1},{\"bidPrice\":2E+2,\"bidSectionId\":1664532788087062529,\"bidderCodeType\":\"\",\"examType\":2,\"isWinBidder\":1,\"otherBidPrice\":\"\",\"priceCurrency\":\"156\",\"priceUnit\":1,\"remark\":\"\",\"score\":10.000,\"winCandidateCode\":\"130301198505057597\",\"winCandidateId\":1659810194731442178,\"winCandidateName\":\"投标人tbr2205\",\"winCandidateOrder\":2},{\"bidPrice\":2E+2,\"bidSectionId\":1664532788087062529,\"bidderCodeType\":\"\",\"examType\":2,\"isWinBidder\":1,\"otherBidPrice\":\"\",\"priceCurrency\":\"156\",\"priceUnit\":1,\"remark\":\"\",\"score\":10.000,\"winCandidateCode\":\"130301198505058231\",\"winCandidateId\":1659811112965251074,\"winCandidateName\":\"投标人tbr2206\",\"winCandidateOrder\":3}]";
        List<WinCandidateVo> vo = JSON.parseArray(arr, WinCandidateVo.class, JSONReader.Feature.FieldBased,
                JSONReader.Feature.SupportClassForName,
                JSONReader.Feature.SupportArrayToBean,
                JSONReader.Feature.IgnoreSetNullValue,
                JSONReader.Feature.SupportSmartMatch,
                JSONReader.Feature.SupportAutoType);
        arr = JSON.toJSONString(vo, JSONWriter.Feature.FieldBased,
                JSONWriter.Feature.BrowserCompatible,
                JSONWriter.Feature.BrowserSecure,
                //JSONWriter.Feature.NullAsDefaultValue,
                JSONWriter.Feature.WriteNullStringAsEmpty,
                JSONWriter.Feature.WriteNonStringKeyAsString,
                JSONWriter.Feature.WriteNullListAsEmpty,
                JSONWriter.Feature.WriteBigDecimalAsPlain,
                JSONWriter.Feature.WriteEnumsUsingName,
                JSONWriter.Feature.WriteMapNullValue);
        System.out.printf(vo.toString());
    }

字符串转对象时报错： （2.0.31 可以正常转换）
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.alibaba.fastjson2.util.IOUtils.getDecimalChars(IOUtils.java:325)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeDecimal(JSONWriterUTF16.java:1017)
	at com.alibaba.fastjson2.writer.OWG_1_28_WinCandidateVo.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:373)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2758)
	at com.web.TestController.main(TestController.java:56)

**Comment by wenshao** [comment]
这个问题2.0.33修复过，是否可以用2.0.33再试一下？

**Comment by sobuh** [comment]
升级到2.0.33已解决
