### ISSUE TITLE
com.alibaba.fastjson2.reader.ObjectReaderImplObject中 Thread.currentThread().getContextClassLoader()为null 导致空指针

### ISSUE THREAD

**Issue by lyy12332133** [alibaba/fastjson2#1534]
### 问题描述
com.alibaba.fastjson2.reader.ObjectReaderImplObject中 Thread.currentThread().getContextClassLoader()为null 导致空指针

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.33]

**Comment by yanxutao89** [comment]
麻烦给下测试用例

**Comment by lyy12332133** [comment]
![image](https://github.com/alibaba/fastjson2/assets/32724564/97d3b942-f6fe-48a7-aac7-c22faad3ab33)
private SpeechRecognizer speechRecognizer;

![image](https://github.com/alibaba/fastjson2/assets/32724564/94168f24-f737-4e54-8515-3ab7b0bb062c)

抱歉，没法给测试用例，使用微软asr的sdk回调函数里面获取的Thread.currentThread().getContextClassLoader()就是null。
之前使用fastjson:1.2.83没有这个问题，升级到2.0.33后存在这个问题。

**Comment by yanxutao89** [comment]
调用fastjson的代码片段也行吧

**Comment by lyy12332133** [comment]
`package com.alibaba.fastjson.support.spring;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.support.config.FastJsonConfig;
import org.springframework.data.redis.serializer.RedisSerializer;
import org.springframework.data.redis.serializer.SerializationException;

/**
 * Fastjson for Spring Data Redis Serializer.
 * <p>
 * Compatible fastjson 1.2.x
 *
 * @author lihengming
 * @author Victor.Zxy
 * @see RedisSerializer
 * @since 2.0.2
 */
public class FastJsonRedisSerializer<T>
        implements RedisSerializer<T> {
    private final Class<T> type;
    private FastJsonConfig fastJsonConfig = new FastJsonConfig();

    public FastJsonRedisSerializer(Class<T> type) {
        this.type = type;
    }

    public FastJsonConfig getFastJsonConfig() {
        return fastJsonConfig;
    }

    public void setFastJsonConfig(FastJsonConfig fastJsonConfig) {
        this.fastJsonConfig = fastJsonConfig;
    }

    @Override
    public byte[] serialize(T type) throws SerializationException {
        if (type == null) {
            return new byte[0];
        }
        try {
            return JSON.toJSONBytes(type, fastJsonConfig.getSerializeFilters(), fastJsonConfig.getSerializerFeatures());
        } catch (Exception ex) {
            throw new SerializationException("Could not serialize: " + ex.getMessage(), ex);
        }
    }

    @Override
    public T deserialize(byte[] bytes) throws SerializationException {
        if (bytes == null || bytes.length == 0) {
            return null;
        }
        try {
            return JSON.parseObject(bytes, type, fastJsonConfig.getFeatures());
        } catch (Exception ex) {
            throw new SerializationException("Could not deserialize: " + ex.getMessage(), ex);
        }
    }
}
`

redis用到了fastjson的序列化，反序列化时候报错了。

**Comment by yanxutao89** [comment]
> `package com.alibaba.fastjson.support.spring;
> 
> import com.alibaba.fastjson.JSON; import com.alibaba.fastjson.support.config.FastJsonConfig; import org.springframework.data.redis.serializer.RedisSerializer; import org.springframework.data.redis.serializer.SerializationException;
> 
> /**
> 
> * Fastjson for Spring Data Redis Serializer.
> * 
> * Compatible fastjson 1.2.x
> * @author lihengming
> * @author Victor.Zxy
> * @see RedisSerializer
> * @SInCE 2.0.2
>   */
>   public class FastJsonRedisSerializer
>   implements RedisSerializer {
>   private final Class type;
>   private FastJsonConfig fastJsonConfig = new FastJsonConfig();
>   public FastJsonRedisSerializer(Class type) {
>   this.type = type;
>   }
>   public FastJsonConfig getFastJsonConfig() {
>   return fastJsonConfig;
>   }
>   public void setFastJsonConfig(FastJsonConfig fastJsonConfig) {
>   this.fastJsonConfig = fastJsonConfig;
>   }
>   @OverRide
>   public byte[] serialize(T type) throws SerializationException {
>   if (type == null) {
>   return new byte[0];
>   }
>   try {
>   return JSON.toJSONBytes(type, fastJsonConfig.getSerializeFilters(), fastJsonConfig.getSerializerFeatures());
>   } catch (Exception ex) {
>   throw new SerializationException("Could not serialize: " + ex.getMessage(), ex);
>   }
>   }
>   @OverRide
>   public T deserialize(byte[] bytes) throws SerializationException {
>   if (bytes == null || bytes.length == 0) {
>   return null;
>   }
>   try {
>   return JSON.parseObject(bytes, type, fastJsonConfig.getFeatures());
>   } catch (Exception ex) {
>   throw new SerializationException("Could not deserialize: " + ex.getMessage(), ex);
>   }
>   }
>   }
>   `
> 
[fastjson2-2.0.34-SNAPSHOT.zip](https://github.com/alibaba/fastjson2/files/11672559/fastjson2-2.0.34-SNAPSHOT.zip)

> redis用到了fastjson的序列化，反序列化时候报错了。

麻烦用这个试试，

**Comment by lyy12332133** [comment]
可以了 @yanxutao89

**Comment by yanxutao89** [comment]
> 可以了 @yanxutao89

麻烦多次验证吧，如果没有问题我就提交改动了，谢谢

**Comment by lyy12332133** [comment]
> > 可以了 @yanxutao89
> 
> 麻烦多次验证吧，如果没有问题我就提交改动了，谢谢

试过了 没问题了

**Comment by yanxutao89** [comment]
> > > 可以了 @yanxutao89
> > 
> > 
> > 麻烦多次验证吧，如果没有问题我就提交改动了，谢谢
> 
> 试过了 没问题了

好的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/edit/2.0.34
问题已修复，请用新版本
