### ISSUE TITLE
[BUG] 2.0.8 Set集合的情况下，null元素如果在首位，序列化后会丢失逗号

### ISSUE THREAD

**Issue by zs121233** [alibaba/fastjson2#1536]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.8]
 

### 重现步骤
public static void main(String[] args) {
        String a = "{\"positions\":[null,217091,22222,217089,217088,217095,217094,217092,217099,217098,217097,217096,217103,217102,217101,217100,217107,217106,581657,217105,583706,217104,217111,217110,581661,217109,217108,583711,217115,217114,400415,217113,217112,217119,217118,217117,583703,217116,217123,217122,217121,217120,217127,217126,217125,217124,217131,217129,583714,217128,217135,399402,583717,217132,217139,217138,217137,217143,217142,217141,217140,217147,217146,400447,217145,217144,217151,217150,217149,217148,217155,217154,217153,217152,217159,217157,217156,217163,217162,534593,217161,217160,217167,217166,217164,217171,217170,217168,217175,217174,217173,217172,217179,217176,217183,270424,217182,217181,217180,653398,217187,217186,217185,217184,217191,750703,217190,217189,217188,217195,400494,217194,217193,217192,217199,400490,217198,217197,750693,217202,750714,217200,400499,217205,217204,217211,400510,217209,217208,801911,217214,217212,217219,217218,217217,750729,217216,217223,400515,217221,217220,217227,697474,217226,217225,217224,217231,217230,750726,217229,217228,400521,217235,217233,217232,217239,217238,400531,217237,217236,217243,217242,217241,479389,217240,217247,217246,217245,217244,697493,217251,217250,217249,217248,217255,217254,217253,217252,217259,217258,217257,217256,217263,400554,217262,217261,217260,217267,217266,217265,217271,217270,217268,217275,217274,217273,217272,217279,217278,217277,217276,217283,217282,217281,217280,217287,217286,217285,217284,324803,217291,496847,217290,217289,484557,487629,217288,217295,496843,217294,217293,217292,217299,217298,217297,217296,479444,217303,217302,217301,799962,217300,496848,217307,217306,217305,217304,479452,217311,217310,217309,217308,217315,217314,217313,479461,217312,217319,217318,217317,615662,217316,479456,217323,217322,217321,217320,217327,217326,217325,217324,217331,295157,217330,217329,217328,217335,217334,217333,217332,217339,217338,217337,217336,217343,217342,217341,404728,217340,217347,217346,217345,217344,217351,217350,404739,217349,217348,217355,404750,217354,217353,217352,217359,217358,217357,217356,217363,561433,217362,217361,217360,217367,217366,217365,217364,217371,217370,217369,217368,518428,217375,217374,217373,217372,217379,217378,217377,217376,217383,217382,217381,653615,217380,217387,217386,217385,217384,217391,217390,217389,217388,217395,217394,217392,653626,217399,217398,217397,217396,217403,217401,217407,217406,217405,217404,217411,217410,217409,217408,217415,217414,217413,217412,217419,217418,217417,217416,217423,217422,217421,473417,217420,217427,217426,217425,217424,217431,217430,549213,217428,217435,217433,653650,217439,217437,217443,217441,217440,217447,217446,217445,217451,217450,217449,217455,217454,217453,217452,217459,217458,217457,217456,217463,217462,308593,217461,308594,217460,308595,217467,217466,217465,217464,781686,217469,217468,309638,562575,426377,487831,493974,562588,552349,562591,641426,562594,660927,459203,601539,308686,601542,757231,330228,330231,550390,330234,599563,599566,599576,599581,599569,599573,359975,621102,687664,217662,217661,217671,217669,217675,217674,217673,217672,217679,217678,217677,217676,536135,312916,217683,217681,217680,217687,690783,217686,217685,563807,217684,217688,217694,217693,626282,617066,217696,597601,360041,360042,487024,626288,294522,633463,328325,294533,294535,294543,328329,294538,671406,278194,321210,417478,560841,321216,300750,543431,626389,486105,543465,486116,680672,387835,322317,532249,515858,488231,540457,540458,540459,488228,653100,330548,563012,503626,563013,651096,351063,651091,413529,526189,413548,413555,526198,438145,424844,424841,606110,489371,489370,489369,574380,273324,273325,273326,273327,273323,273328,273329,650191,377794,273352,217038,626628,273355,217043,273364,217041,217040,217047,217046,589789,273361,410579,217045,273362,650207,273363,217051,217050,217049,217048,217055,217054,217053,217052,217059,273380,217058,217057,217063,217062,685039,217061,217060,217067,217066,217065,217064,217071,217070,217069,217068,217075,217074,217073,217072,217079,217078,217077,217076,685053,217083,217082,217081,217080,217087,217086,217085,217084]}";
        Posit positionTarget = JSON.parseObject(a, Posit.class);
        System.out.println(JSON.toJSONString(positionTarget));
    }

    @Data
    public static class Posit{
        Set<Long> positions;
    }
``` 
null元素在首位的情况下，序列化结果丢失逗号
### 错误结果
{"positions":[null217091,217089,21708........]}
逗号丢失


### 期待的正确结果
{"positions":[null,217091,217089,21708........]}
(1.x版本结果是正确的)


### 相关日志输出
复现很简单，提供的字符串反序列化成Set<Long>,再序列化即可

#### 附加信息

**Comment by GabrielHwang** [comment]
新版本已经解决这个bug了
