### ISSUE TITLE
[BUG] OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by liminggangRs** [alibaba/fastjson2#1545]
### 问题描述
*简要描述您碰到的问题。*
字符串转为实体对象时出现内存溢出

### 环境信息
*请填写以下信息：*

 - OS信息： windows11
 - JDK信息： [e.g.：oracle jdk17]
 - 版本信息：[e.g.：Fastjson2 2.0.11  , Fastjson2 2.0.33]
 

### 重现步骤
*如何操作可以重现该问题：*

json内容：

{"type":"MANUALLY","signType":"COUNTER_SIGN","approvers":[{"identifierId":"USER-001","identifierType":"USER"},{"identifierId":"68a8ec4e16cb46f8a476b19a2c29dcf0","identifierType":"ROLE"}],"emptyApprover":{"type":"SELECTED","approvers":[{"identifierId":"USER-001","identifierType":"USER"},{"identifierId":"68a8ec4e16cb46f8a476b19a2c29dcf0","identifierType":"ROLE"}]},"requireComment":true,"fieldPermissions":[{"mode":"READ","fieldId":"updatedTime"},{"mode":"WRITE","fieldId":"LolbEOcRuS"},{"mode":"WRITE","fieldId":"vgq86dOxpQ"},{"mode":"READ","fieldId":"updatedBy"},{"mode":"READ","fieldId":"createdBy"},{"mode":"WRITE","fieldId":"szv9SZNCSH"},{"mode":"READ","fieldId":"createdTime"},{"mode":"READ","fieldId":"ID"}],"approverSettingType":"SELECTED"}

```

String s = "{\"type\":\"MANUALLY\",\"signType\":\"COUNTER_SIGN\",\"approvers\":[{\"identifierId\":\"USER-001\",\"identifierType\":\"USER\"},{\"identifierId\":\"68a8ec4e16cb46f8a476b19a2c29dcf0\",\"identifierType\":\"ROLE\"}],\"emptyApprover\":{\"type\":\"SELECTED\",\"approvers\":[{\"identifierId\":\"USER-001\",\"identifierType\":\"USER\"},{\"identifierId\":\"68a8ec4e16cb46f8a476b19a2c29dcf0\",\"identifierType\":\"ROLE\"}]},\"requireComment\":true,\"fieldPermissions\":[{\"mode\":\"READ\",\"fieldId\":\"updatedTime\"},{\"mode\":\"WRITE\",\"fieldId\":\"LolbEOcRuS\"},{\"mode\":\"WRITE\",\"fieldId\":\"vgq86dOxpQ\"},{\"mode\":\"READ\",\"fieldId\":\"updatedBy\"},{\"mode\":\"READ\",\"fieldId\":\"createdBy\"},{\"mode\":\"WRITE\",\"fieldId\":\"szv9SZNCSH\"},{\"mode\":\"READ\",\"fieldId\":\"createdTime\"},{\"mode\":\"READ\",\"fieldId\":\"ID\"}],\"approverSettingType\":\"SELECTED\"}";
var a =  JSONObject.parseObject(s,ApproveActionConfig.class);

```

### 相关日志输出
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3512)
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:454)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at com.alibaba.fastjson2.reader.ORG_1_7_ApproveActionConfig.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:707)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1988)

**Comment by yanxutao89** [comment]
ApproveActionConfig 麻烦提供下

**Comment by liminggangRs** [comment]
@Data
    public  class ApproveActionConfig {

        private ApproveType type;

        private ApproverSettingType approverSettingType;

        private List<ApproverIdentifier> approvers;

        private SignatureType signType;

        private EmptyApprover emptyApprover;

        private List<FieldPerm.PermMode> fieldPermissions;

        private Boolean requireComment;
}

public enum ApproveType {

    MANUALLY,

    AUTO
}

public enum ApproverSettingType {

    SELECTED,

    SELF_SELECT
}

@Data
public class ApproverIdentifier  {

    private String identifierId;

    private ApproverIdentifierType identifierType;

    public enum ApproverIdentifierType {

        USER,

        ROLE,

        GROUP
    }
}

public enum SignatureType {

    COUNTER_SIGN,

    PARALLEL_SIGN


}

@Data
public class EmptyApprover {

    private Type type;

    private List<ApproverIdentifier> approvers;

    enum Type {
        AGREE,

        REJECT,

        SELECTED
    }
}

@Data
public class FieldPerm {

    private String fieldId;

    private PermMode mode;

    public enum PermMode {

        READ,

        WRITE,

        NONE
    }
}

**Comment by yanxutao89** [comment]
有以下两种方案供参考：
1.Bean里面的fieldPermissions的类型改为List<FieldPerm>；
2.Json里面的fieldPermissions改为["READ","WRITE"].
总之，Bean和Json对应类型请保持一直。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/edit/2.0.34
问题已修复，请用新版本
