### ISSUE TITLE
[BUG] arraycopy: last destination index 8194 out of bounds for char[8192]

### ISSUE THREAD

**Issue by leshalv** [alibaba/fastjson2#1557]
使用 JSONObject.toJSONString(error, JSONWriter.Feature.PrettyFormat); 报错：[BUG] arraycopy: last destination index 8194 out of bounds for char[8192]

**Comment by yanxutao89** [comment]
麻烦给下测试用例

**Comment by wenshao** [comment]
什么版本？能提供下出错堆栈信息么？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/edit/2.0.34
问题已修复，请用新版本
