### ISSUE TITLE
[BUG] 当在对象double属性上加上@JSONField(format="#.##") ,赋值NaN序列化出来不是null

### ISSUE THREAD

**Issue by Merely-chao** [alibaba/fastjson2#1562]
### 问题描述
*当在对象double属性上加上@JSONField(format="#.##") NaN序列化出来不是null*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win11]
 - JDK信息： [e.g.：Openjdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.33]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
	@Data
    class Cs {


        @JSONField(format = "#.##")
        private double value = Double.NaN;


    }

    @Test
    void test() {

        Cs s = new Cs();
        var tt = JSON.toJSONString(s);

        System.out.println(tt);


    }
```
输出结果
``` 
{"value":NaN}
````

### 期待的正确结果
*希望输出：*
```
{"value":null}
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/edit/2.0.34
问题已修复，请用新版本
