### ISSUE TITLE
[BUG]JSONB.toJSONString duplicates TIMESTAMP

### ISSUE THREAD

**Issue by vopaldragon** [alibaba/fastjson2#1568]
### 问题描述
JSONB.toJSONString duplicates TIMESTAMP value

### 环境信息
 - OS信息： Windows 11
 - JDK信息： Amazon correto-17
 - 版本信息：fastjson2:2.0.33
 

### 重现步骤
This code reproduce the problem

```java
 static class Time {
    public Date d = new Date();
  }

  public static void main(String[] args) {
    JSON.configWriterDateFormat("millis");
    Time t = new Time();
    byte[] bytes = JSONB.toBytes(t);
    System.out.println(JSON.toJSONString(t));
    System.out.println(JSONB.toJSONString(bytes));
  }
```
Output:

{"d":1686833234124}
{
	"d":16868332341241686833234124
}

### 期待的正确结果
Timestamp should be written once

#### 附加信息
It seems this [line](https://github.com/alibaba/fastjson2/blob/8876c08b2cee4c1d4addfacaadaf02134afff95d/core/src/main/java/com/alibaba/fastjson2/JSONBDump.java#L126) is cause of the problem

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/edit/2.0.34
问题已修复，请用新版本
