### ISSUE TITLE
[BUG] JSON.parseObject 解析String异常

### ISSUE THREAD

**Issue by coder-yaojie** [alibaba/fastjson2#1573]
### 问题描述
*JSON.parseObject  解析String异常*

### 环境信息
*请填写以下信息：*

 - OS信息：  [Windows 10]
 - JDK信息： [e.g.：Oracle jdk 1.8.0_111]
 - 版本信息：[e.g.：Fastjson2.0.33]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSON.parseObject(String text, Class<T> clazz)` 方法
2. 输入 `任意非数字的字符，Class为String`  数据
3. 出现 `报错异常` 错误
```java
public static void main(String[] args) {
		String text = "asdsf";
		String ret = JSON.parseObject(text, String.class);
		System.out.println(ret);
	}
```

### 期待的正确结果
*不报异常*

### 相关日志输出
*Exception in thread "main" com.alibaba.fastjson2.JSONException: illegal input : a, offset 1, character a, line 1, column 2, fastjson-version 2.0.33 asdsf
	at com.alibaba.fastjson2.JSONReaderUTF16.readString(JSONReaderUTF16.java:4025)
	at com.alibaba.fastjson2.reader.ObjectReaderImplString.readObject(ObjectReaderImplString.java:25)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:707)*

#### 附加信息
*至少fastjson1 解析String的时候，没有报错；是否fastjson2是不支持的，这样的话，业务上层我就自行处理了*

**Comment by kraity** [comment]
根据`www.json.org`中规范定义, 字符串是由`"`包裹
示例中`asdsf`不是一个`Number`也没有由`"`包裹, fastjson2视为非法格式

**Comment by mek1986** [comment]
字符串解析成String.class，是不是就该原样返回字符串就好了呢？

**Comment by wenshao** [comment]
这个不是BUG，报错是合理的

**Comment by coder-yaojie** [comment]
> 字符串解析成String.class，是不是就该原样返回字符串就好了呢？

是的，我的意思就是原样返回就好了

**Comment by coder-yaojie** [comment]
> 这个不是BUG，报错是合理的

好的，上层我自己处理一下
