### ISSUE TITLE
[BUG] java.lang.ArrayIndexOutOfBoundsException: Index 12288 out of bounds for length 12288

### ISSUE THREAD

**Issue by leshalv** [alibaba/fastjson2#1591]
升级到2.0.34后出现新的错误：java.lang.ArrayIndexOutOfBoundsException: Index 12288 out of bounds for length 12288

JSONObject.toJSONString(error, JSONWriter.Feature.PrettyFormat)

**Comment by leshalv** [comment]
https://github.com/alibaba/fastjson2/issues/1557

**Comment by wenshao** [comment]
能发下下更详细的堆栈信息么？

**Comment by leshalv** [comment]
java.lang.ArrayIndexOutOfBoundsException: Index 12288 out of bounds for length 12288\n\tat com.alibaba.fastjson2.JSONWriterUTF16.startObject(JSONWriterUTF16.java:106)\n\tat com.alibaba.fastjson2.writer.ObjectWriterAdapter.write(ObjectWriterAdapter.java:299)\n\tat com.alibaba.fastjson2.writer.ObjectWriterArrayFinal.write(ObjectWriterArrayFinal.java:104)\n\tat com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:83)\n\tat com.alibaba.fastjson2.writer.ObjectWriterException.write(ObjectWriterException.java:48)\n\tat com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2801)\n\tat com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1146)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.35-SNAPSHOT/
请帮忙用2.0.35-SNAPSHOT版本验证

**Comment by leshalv** [comment]
好了，什么时候可以发正式呀

**Comment by wenshao** [comment]
2.0.35正式版预计7月2日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.35
问题已修复，请用新版本

**Comment by futann** [comment]
2.0.48 出现该问题，尝试改为2.0.52解决成功

**Comment by fly0wing** [comment]
2.0.61又出现这个问题了，降到2.0.60正常。
