### ISSUE TITLE
[BUG] 识别Gson的SerializedName问题

### ISSUE THREAD

**Issue by biubiubiu3971** [alibaba/fastjson2#1595]
### 问题描述
 

属性名上用Gson的@SerializedName，竟然被识别了，这个是bug还是特性？
用1.X的没有识别，用2.x的识别了

### 环境信息
*请填写以下信息：*

fastJson 版本：2.0.32
jdk：1.8

### 重现步骤

<img width="827" alt="246383007-29187696-e0a3-4f42-82fd-eda1fbbea554" src="https://github.com/alibaba/fastjson2/assets/36981492/09f7a02c-d3ab-41ac-b1cb-3fb0ba3c1167">

<img width="385" alt="246383025-1835d930-1cc4-421f-a022-0f0d76b36270" src="https://github.com/alibaba/fastjson2/assets/36981492/1a5f21df-f07f-4fb5-a4cd-8508223f96bf">

 
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

按理来说不应该识别非本SDK外的任何特性，所以这个是fastJson2的新特性还是别的问题？

**Comment by CherryRum** [comment]
https://github.com/alibaba/fastjson2/commit/3583173a8985900674bd345c34edc03d647903f5
有意支持的

**Comment by biubiubiu3971** [comment]
理解是特性，但是可以问下出于啥想法加这个特性呢？这种做法感觉还其实不太符合SDK的原则。

**Comment by JadeSpring** [comment]
有开关配置可以关掉这个特性吗
