### ISSUE TITLE
[BUG] JSON数组反序列化

### ISSUE THREAD

**Issue by byunghohwang** [alibaba/fastjson2#1597]
### 问题描述
JSON数组反序列化，其中有一个元素为null时，死循环无限创建对象导致OOM。

### 环境信息
 - JDK信息：1.8.0_291
 - 版本信息：Fastjson2 2.0.9
 

### 重现步骤
@Data
public class User {

    private String name;

    private Integer age;

}

public static void main(String[] args) {
	String json = "[{\"name\":\"tom\",\"age\":11},null]";
	List<User> users = JSON.parseArray(json, User.class);
}

**Comment by wenshao** [comment]
这个问题修复过，请用2.0.34版本帮忙验证下

**Comment by byunghohwang** [comment]
验证了，没问题。

**Comment by DevinYDQ** [comment]
String json = "[{"name":"tom","age":11},null]"; 
List users = JSON.parseArray(json, User.class);
作者提出的这个json， 使用新版本虽然没问题了，但是反序列化后users会有一个null的元素，这个并没有意义，能否把没有意义的元素忽略掉呢？
