### ISSUE TITLE
[FEATURE] JSONField 的 format 改进

### ISSUE THREAD

**Issue by suqiernb** [alibaba/fastjson2#1599]
```java
  @JSONField(name = "background-color", format = "#%08X")
  public int backgroundColor;
  @JSONField(name = "border-color", format = "#%08X")
  public int borderColor;
```

format 只对时间类型起作用, 我想格式化十六进制类型的颜色代码, 难道只能将数据类型改为 `String` 吗
我认为可以添加对基本数据类型的 `String.format` 支持

另外再问一下, 我现在怎么解决目前遇到的问题

**Comment by wenshao** [comment]
收到需求，将会在下个版本中支持

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.35
问题已修复，请用新版本
