### ISSUE TITLE
[BUG] 序列化 toJSONBytes 时，如果属性为 null，序列化后的 bytes 转 String 时，格式不对，多了 “,”

### ISSUE THREAD

**Issue by DemonJun** [alibaba/fastjson2#1603]
### 问题描述
*简要描述您碰到的问题。*

序列化 toJSONBytes 时，如果属性为 null，序列化后的 bytes 转 String 时，格式不对，多了 “,”

### 环境信息
*请填写以下信息：*

 - OS信息：  Macos 13
 - JDK信息： openjdk 11
 - 版本信息：fastjson2 2.0.33/2.0.34
 

### 重现步骤
*如何操作可以重现该问题：*

```java
    JSONObject jsonObject =
        JSON.parseObject(
            "{\"deviceId\":\"16584\",\"srcAddress\":\"109.55.156.215\",\"ssssss\":null}");
    byte[] jsonBytes = JSON.toJSONBytes(jsonObject);
    System.out.println(new String(jsonBytes));
```

### 期待的正确结果
{"deviceId":"16584","srcAddress":"109.55.156.215"}

### 相关日志输出
{"deviceId":"16584","srcAddress":"109.55.156.215",}

#### 附加信息
<img width="1056" alt="image" src="https://github.com/alibaba/fastjson2/assets/21258148/22d2efe7-40db-4757-b666-61bbaf377dce">

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.35
问题已修复，请用新版本
