### ISSUE TITLE
[QUESTION] com.alibaba.fastjson2.JSONException: auotype not support : xx.xxx.boot.dubbo.exception.DubboException

### ISSUE THREAD

**Issue by panghu-max** [alibaba/fastjson2#1607]
使用版本：2.0.34
继承dubbo RpcException
![image](https://github.com/alibaba/fastjson2/assets/67360365/593bcf92-2683-45e6-9f36-b1a4e5c23d2b)
在DUBBO的过滤器中使用
![image](https://github.com/alibaba/fastjson2/assets/67360365/34e7c517-26b2-4903-96ec-79ff1c7b0ab8)
在springboot 全局异常捕获
![image](https://github.com/alibaba/fastjson2/assets/67360365/8695c350-be6f-4abf-b4ce-db4db6b3c114)

**Comment by kaizen84** [comment]
你这是没有 setter 吧

**Comment by panghu-max** [comment]
> 你这是没有 setter 吧

我重新加了 setter后还是一样报错

**Comment by AlbumenJ** [comment]
https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/class-check/ 按照这个文档需要手动配白名单

**Comment by panghu-max** [comment]
> https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/class-check/ 按照这个文档需要手动配白名单

感谢，问题成功解决
