### ISSUE TITLE
新版本不支持下划线转驼峰对象key-json（大小写）反序列化了？[BUG]

### ISSUE THREAD

**Issue by mystox** [alibaba/fastjson2#1615]
### 问题描述
*简要描述您碰到的问题。*
json报文中包含下划线（包括大小写）的反序列化问题

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.34]
 

### 重现步骤
*如何操作可以重现该问题：*
```java
main{
        JSONObject test = new JSONObject();
        test.put("live_url", "123");
        //test.puT("LIVE_URL", "123")
        CameraVO cameraVO = test.toJavaObject(CameraVO.class);
        System.out.println(cameraVO);
}

public class CameraVO extends EquipmentVO {
    private String liveUrl;
    private String replayUrl;

    public String getReplayUrl() {
        return replayUrl;
    }

    public void setReplayUrl(String replayUrl) {
        this.replayUrl = replayUrl;
    }

    public String getLiveUrl() {
        return liveUrl;
    }

    public void setLiveUrl(String liveUrl) {
        this.liveUrl = liveUrl;
    }
```

### 期待的正确结果
能够正常反序列化成功

**Comment by wenshao** [comment]
toJavaObject可以配置JSONReader.Feature，比如
```java
jsonObject.toJavaObject(CameraVO.class, JSONReader.Feature. SupportSmartMatch)
```

fastjson 2.x需要显式打开SupportSmartMatch

**Comment by mystox** [comment]
> 

冒昧问下，为何2.0.32版本之前还是隐式支持（经测试），为何改为显式打开呢

**Comment by mystox** [comment]
> toJavaObject可以配置JSONReader.Feature，比如
> 
> ```java
> jsonObject.toJavaObject(CameraVO.class, JSONReader.Feature. SupportSmartMatch)
> ```
> 
> fastjson 2.x需要显式打开SupportSmartMatch

且 JSONArray的 toJavaList() 方法怎么方便的显式打开 JSONReader.Feature. SupportSmartMatch

**Comment by wenshao** [comment]
toJavaList也是一样：
```java
jsonArray.toJavaList(CameraVO.class, JSONReader.Feature. SupportSmartMatch)
```

**Comment by wenshao** [comment]
> > 
> 
> 冒昧问下，为何2.0.32版本之前还是隐式支持（经测试），为何改为显式打开呢

因为要和JSON.parseObject的缺省行为一致

**Comment by mystox** [comment]
> toJavaList也是一样：
> 
> ```java
> jsonArray.toJavaList(CameraVO.class, JSONReader.Feature. SupportSmartMatch)
> ```

已经发现问题，项目中用的是com.alibaba.fastjson.JSONArray这个包，能否在这个包里也添加支持jsonArray.toJavaList(CameraVO.class, JSONReader.Feature. SupportSmartMatch)参数方法呢

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.36-SNAPSHOT/
问题已经修复，帮忙用2.0.36-SNAPSHOT版本验证

**Comment by mystox** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.36-SNAPSHOT/ 问题已经修复，用兼容API已经默认打开SupportSmartMatch，请帮忙用2.0.36-SNAPSHOT版本验证

测试验证通过，谢谢

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.36
请用新版本

**Comment by dengfuwei** [comment]
这种不兼容的版本升级，至少应该升第二位版本号吧！
