### ISSUE TITLE
[BUG] JSONObject.from后toString跟JSONObject.toJSONString不一致

### ISSUE THREAD

**Issue by scrollsyou** [alibaba/fastjson2#1617]
### 问题描述
*目前我有一个类中有生日字段，配置了格式化日期为yyyy-MM-dd，当通过JSONObject.from(object)转为JSONObject后去toString时，格式化不生效。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.34]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 创建Demo.java类，其中存在字段private Date birthday，并在上方指定格式@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
2. 创建Demo对象，并将生日赋当前时间
3. 通过(JSONObject.from(demo)).toString();转化为json字符串时，生日带时分秒，并未格式化
```java
@Data
public class Demo implements Serializable {
//    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date birthday;
}

    @Test
    public void testObjectToStr(){

        Demo demo = new Demo ();
        demo .setBirthday(new Date());
        String s = (JSONObject.from(demo )).toString();
        System.out.println(s);
        String s1 = JSONObject.toJSONString(demo );
        System.out.println(s1);

    }

```

### 期待的正确结果
*{"birthday":"2023-07-05"}
{"birthday":"2023-07-05"}*

### 相关日志输出
*{"birthday":"2023-07-05 18:33:28.278"}
{"birthday":"2023-07-05"}*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by GabrielHwang** [comment]
>
https://github.com/alibaba/fastjson2/blob/3b17f012fa51360472791a9dbe457d8a03497d7d/core/src/main/java/com/alibaba/fastjson2/JSONWriter.java#L1557-L1559C10
![issue](https://github.com/alibaba/fastjson2/assets/71489814/68c89115-c52f-4662-9467-3f6be9a4328c)

大概是注解的参数没有读取到

**Comment by wenshao** [comment]
···
@DateTimeFormat(pattern = "yyyy-MM-dd")
···
这个更换为
```java
@JSONField(format = "yyyy-MM-dd")
```

更多fastjson2的annotation介绍看这里 https://github.com/alibaba/fastjson2/blob/main/docs/annotations_cn.md

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.35
问题已修复，请用新版本
