### ISSUE TITLE
level too large : " + this.level

### ISSUE THREAD

**Issue by KissSmile** [alibaba/fastjson2#1618]
throw new JSONException("level too large : " + this.level);
会抛出这个异常是因为啥原因。

**Comment by wenshao** [comment]
有循环引用

**Comment by KissSmile** [comment]
目测没循环引用。同样的方法，数据量小的没问题，只有数据量大的才有这个错。

**Comment by wenshao** [comment]
因为这样的报错有多个地方，能提供下错误堆栈信息么？

**Comment by KissSmile** [comment]
暂时没有了。下回有在碰到在贴上来。

**Comment by AaronWong002** [comment]
遇到类似问题，寻求帮助
com.alibaba.fastjson2.JSONException: level too large : 2048      (不方便获取全部堆栈信息，此为手敲)
......                                                            JSONWriterJSONB.java:81
....................................
.......                                                           DubboCodec.java:284
....................................
......                                                             DubboCountCodec.java:51

问题描述：大批量（20000）返回时报这个问题，将单次数据返回量限制到一定条数（150）以下，不再报这个问题

**Comment by AaronWong002** [comment]
这个问题如果出现在dubbo服务中只需换掉fastjson2序列化，使用hessian2即可，配置dubbo.protocol.serialization=hassian2

**Comment by wenshao** [comment]
帮忙用fastjson 2.0.35版本试下问题是否还存在

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.36-SNAPSHOT/
问题已经修复，帮忙用2.0.36-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.36
请用新版本
