### ISSUE TITLE
Dubbo 3.2 Rpc 中使用 fastjson2 的问题

### ISSUE THREAD

**Issue by liaozan** [alibaba/fastjson2#1623]
#### 前提
由于公司之前基础框架是`SpringCloud`，所有的服务调用接口为了方便服务间调用以及前端调用，都使用了包装类进行包装
```java
public class BaseResult<T> implements Serializable {
    /**
     * 是否成功
     */
    private boolean success;
    /**
     * 错误码
     */
    private Integer code;
    /**
     * 错误信息
     */
    private String message;
    /**
     * 数据data
     */
    private T data;
    /**
     * requestId
     */
    private String requestId;
```
公司统一框架为`Dubbo`之后，由于部分接口未补充详细泛型信息，在 `SpringCloud` 环境下以及 `Dubbo` 3.2之前都是可以正常使用的（hessian2 序列化）接口，在升级到`Dubbo` 3.2 之后，切换到了默认 `fastjson2` 序列化，出现了无法反序列化的情况

#### 错误堆栈
<img width="1568" alt="image" src="https://github.com/alibaba/fastjson2/assets/26990889/a77a0a67-0e6c-4736-acb3-a72b5dd098e8">

#### 截取接口定义
<img width="473" alt="image" src="https://github.com/alibaba/fastjson2/assets/26990889/eea13ace-6771-47b2-ac30-2030c9ef6f32">

#### 猜想错误原因
由于服务提供方接口定于未定义泛型，虽然 fastjson2 在序列化时带上了类型信息，但是在消费方进行反序列化时，没有开启 autoType，并且类型未在接口申明，所以导致反序列化失败

因为涉及到的服务接口太多，如果改动的话实在太多了，所以想问下，这种情况有什么办法能在框架层面解决吗？

**Comment by wenshao** [comment]
https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/class-check/
按照这个文档需要手动配白名单

**Comment by liaozan** [comment]
试了一下，我碰到的这个情况应该不是被 proxy 导致
按照文档中的方法，在本地测试了下白名单前缀，还是不能正常反序列化
仔细观察了下，发现是因为没有写泛型，导致没有强校验，响应中要反序列化的类在 consumer 端不存在，导致反序列化失败。
最终测试在 consumer 端引入依赖后，即可配合白名单进行正常反序列化

这部分问题还是需要改业务代码才能解决
