### ISSUE TITLE
[BUG] (Android4)ZoneId.SHANGHAI_ZONE_ID空指针异常

### ISSUE THREAD

**Issue by muedsa** [alibaba/fastjson2#1633]
### 问题描述
 ZoneId.SHANGHAI_ZONE_ID 空指针异常

### 环境信息
 - OS信息：  Android API 34
 - JDK信息： jdk 17
 - 版本信息：2.0.35.android4
 

### 重现步骤
在 ZoneId类中如果系统默认时区不是`Asia/Shanghai`,会导致`SHANGHAI_ZONE_ID = ZoneId.of("Asia/Shanghai")`
但是在`of()`方法中
```
 if (tzid.equals("Asia/Shanghai")) {
            return SHANGHAI_ZONE_ID;
 }
```
ZoneId中的部分代码
https://github.com/alibaba/fastjson2/blob/c262c7889c8030f9f5a521adeed5c378755a0bc3/core/src/main/java/com/alibaba/fastjson2/time/ZoneId.java#L15C1-L19C48

https://github.com/alibaba/fastjson2/blob/c262c7889c8030f9f5a521adeed5c378755a0bc3/core/src/main/java/com/alibaba/fastjson2/time/ZoneId.java#L60C1-L74C6

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
```
Caused by: java.lang.NullPointerException: Cannot read field "id" because "com.alibaba.fastjson2.time.ZoneId.SHANGHAI_ZONE_ID" is null
	at com.alibaba.fastjson2.time.ZoneId.getOffsetTotalSeconds(ZoneId.java:31)
	at com.alibaba.fastjson2.util.DateUtils.&lt;clinit&gt;(DateUtils.java:41)
```

#### 附加信息
[*Github Action Failure*](https://github.com/muedsa/BilibiliLiveTV/actions/runs/5517059679/jobs/10059176014)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.36.android4-SNAPSHOT/
请帮忙用2.0.36.android4-SNAPSHOT验证问题是否已修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.36
请用新版本
