### ISSUE TITLE
dubbo 序列化并发问题如何诊断？

### ISSUE THREAD

**Issue by rickiehsu** [alibaba/fastjson2#1636]

**Comment by rickiehsu** [comment]
dubbo的client（tomcat容器）通过方法调用传递Map数据到dubbo的provider（另一个容器）。一段时间内运行良好，在大量用户使用一段时间后，发现map里面的key发生互串。譬如 A对象的map中的key为 tf_type跑到  B对象map中去了。这种情况比较难复现，服务器重启后又好了。改如何去诊断此问题？

**Comment by wenshao** [comment]
fastjson 2什么版本？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/blob/main/core/src/test/java/com/alibaba/fastjson2/JSONFactoryNameCacheTest.java
我补充了并发测试，并没发现问题，希望你不能提供更多的信息。包括串的key等等。

**Comment by rickiehsu** [comment]
> fastjson 2什么版本？请提供更多的环境信息
dubbo 3.2.3
fastjson 2.0.33
![image](https://github.com/alibaba/fastjson2/assets/15170218/1d22e52a-c5e6-4581-bb46-7c77fc8b0e32)

**Comment by rickiehsu** [comment]
1. web controller 调用 Map<String, Object> getObject(String tableName, String objectId) 传参为ac_to(表名），1341（主键），正常应该返回 如下json（在dubbo server端通过FastJson2ObjectOutput的writeObject序列化，在web端FastJson2ObjectInput的readObject反序列化） :
`{
    "pkid": 1341,
    "pre_pkid": null,
    "eva_pkid": null,
    "to_type": "OTHER",
    "apply_type": "A",
    "ef_mode": null,
    "apply_desc": null,
    "to_no": "MAO-A320-72-012",
    "to_ver": 0,
    "to_no_ver": "MAO-A320-72-012R00",
    "acfleet": "A320",
    "model": "A320",
    "ata": "72",
    "title": "干燥剂包检查程序\nDesiccant Bags Inspection Procedure",
    "work_type": null,
    "work_type1": null,
    "check_level": "A",
    "if_cad": 0,
    "issue_deadline": null,
    "issue_date": null,
    "repetition": 1,
    "deadline": null,
    "issue_reason": "发动机封存要求\nStorage Requirement of Engine",
    "execute_desc": "参见工卡内“建议时间表”\nRef to the description in Task Card suggested schedule",
    "man_hours": 0.2,
    "elapsed_time": 0.2,
    "if_feedback_engineer": 0,
    "skills": "ME",
    "zone": "400",
    "feedback_demand": null,
    "issue_org": "EM",
    "receive_org": "PPC",
    "if_rev": 0,
    "rev_reason": null,
    "if_new": null,
    "if_custom": 1,
    "state": 1,
    "cancel_by": null,
    "cancel_time": null,
    "cancel_reason": null,
    "proc_inst_id": null,
    "create_byid": 20041,
    "create_by": "TEST",
    "create_by_id": 20041,
    "create_time": 1689036503000,
    "check_man": null,
    "check_man_id": null,
    "check_date": null,
    "audit_man": null,
    "audit_man_id": null,
    "audit_date": null,
    "ratify_by": null,
    "ratify_byId": null,
    "ratify_time": null,
    "effective_date": null,
    "file_xml_path": null,
    "file_pdf_id": null,
    "proced_pdf_path": null,
    "old_pkid": null,
    "if_must_check": null,
    "if_eachother_check": null,
    "if_test_run": null,
    "urgency_level": null,
    "bill_type": "TO",
    "pre_finished": 1,
    "task_source": null,
    "if_dm": null,
    "if_anti_stop": null,
    "task_type": null,
    "if_doc_written": 1,
    "editable": true
}
`
上述调用一段时间内没有问题，但是运行1天后，出现to_type变成了tf_type(这个字段在另一个表中)，我们尝试重启了Web端的tomcat，又变正常了。我们怀疑writeObject没问题，readObject出问题了。
另一个场景（一段时间内没问题）：上面的json put更新其中to_type修改了一个值，其中web端以及重启，此时writeObject没问题，在dubbo provider的服务没有重启，此时to_type丢失了。我们再重启dubbo provider服务，to_type又有了，又正常了。怀疑dubbo provider端的readObject出问题了。
2.

**Comment by wenshao** [comment]
分析了代码，没找到to_type变成tf_type的地方，你也分析下自己的业务代码中是否可能有这种改变吧
