### ISSUE TITLE
[BUG]null key反序列化出现异常，在1.2.83版本是支持的Exception in thread "main" com.alibaba.fastjson.JSONException: TODO : : 	at com.alibaba.fastjson.JSON.parseObject(JSON.java:517)

### ISSUE THREAD

**Issue by fhhly** [alibaba/fastjson2#1646]
### 问题描述
    public static void main(String[] args) {
        String s = "{\"test\":{null:\"a\",\"b\":\"c\"}}";
        Test appPkg = (Test) JSONObject.parseObject(s, Test.class);
    }

public class Test {
    private Map<String, String> test;

    public Map<String, String> getTest() {
        return test;
    }

    public void setTest(Map<String, String> test) {
        this.test = test;
    }
}
存在null key的情况反序列化会出现异常，经测试1.2.83版本支持。想问一下2.0.25版本是否支持这种反序列化，应该怎么使用

### 相关日志输出
Caused by: com.alibaba.fastjson2.JSONException: TODO : :
	at com.alibaba.fastjson2.JSONReaderUTF16.readString(JSONReaderUTF16.java:3826)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapString.readObject(ObjectReaderImplMapString.java:56)
	at com.alibaba.fastjson2.reader.ORG_1_1_Test.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:507)
	... 1 more

**Comment by fhhly** [comment]
补充一下上面版本描述错误，现在使用的是2.0.25版本不是2.0.5

**Comment by wenshao** [comment]
需要配置JSONReader.Feature.AllowUnQuotedFieldNames)
```java
  @Test
    public void test() {
        String s = "{\"test\":{null:\"a\",\"b\":\"c\"}}";
        Bean bean = (Bean) JSONObject.parseObject(s, Bean.class, JSONReader.Feature.AllowUnQuotedFieldNames);
        assertEquals("a", bean.getTest().get("null"));
    }

    public class Bean {
        private Map<String, String> test;
        public Map<String, String> getTest() {
            return test;
        }

        public void setTest(Map<String, String> test) {
            this.test = test;
        }
    }
```

**Comment by fhhly** [comment]
![image](https://github.com/alibaba/fastjson2/assets/39481402/eeae973a-271f-4e6f-8137-0ed72e5e273f)
还是不行哦

**Comment by wenshao** [comment]
fastjson2什么版本？

**Comment by fhhly** [comment]
2.0.25，刚试了下最新版本是可以的了，多谢。
