### ISSUE TITLE
JSONObject的父类LinkedHashMap应该加上泛型

### ISSUE THREAD

**Issue by louisjiang** [alibaba/fastjson2#165]

**Comment by louisjiang** [comment]
https://github.com/alibaba/fastjson2/issues/110
至于这个bug,应该从scala的写法上去修复.

**Comment by louisjiang** [comment]
`
    public  void test1(JSONObject param1){

    }
    public  void test1(Map<String,String> param1){

    }

`
在2.0.2的版本这样的写法是有问题的.

**Comment by CodeInDreams** [comment]
+1，升到2.0.x就发现put方法有warning，一看源码没泛型<String,Object>

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases
2.0.3已经发布，put方法不会警告，请用新版本
