### ISSUE TITLE
解析超大数组对象示例代码

### ISSUE THREAD

**Issue by songjygithub** [alibaba/fastjson2#1651]
如一个超大文本：[{"id":1,"username":"张三"},..]，如何批量解析入库呢

**Comment by wenshao** [comment]
是每一行一个JSON么？

**Comment by wenshao** [comment]
```java
import com.alibaba.fastjson2.stream;

 try (
                InputStream fis = new FileInputStream(tempFile)
        ) {
            JSONStreamReader streamReader = JSONStreamReader.of(fis);

            int rowCount = 0;
            Object object;
            while ((object = streamReader.readLineObject()) != null) {
                JSONObject jsonObject = (JSONObject) object;
                jsonObject.size();
                rowCount++;
            }
        }
```
这个是不是你想要的？

**Comment by songjygithub** [comment]
> ```java
> import com.alibaba.fastjson2.stream;
> 
>  try (
>                 InputStream fis = new FileInputStream(tempFile)
>         ) {
>             JSONStreamReader streamReader = JSONStreamReader.of(fis);
> 
>             int rowCount = 0;
>             Object object;
>             while ((object = streamReader.readLineObject()) != null) {
>                 JSONObject jsonObject = (JSONObject) object;
>                 jsonObject.size();
>                 rowCount++;
>             }
>         }
> ```
> 
> 这个是不是你想要的？

那如果对方给的是如下格式呢？
[
  {
    "id": 1,
    "username": "张三"
  },
  {
    "id": 2,
    "username": "李四"
  },
  ...
]

**Comment by wenshao** [comment]
目前还不支持，但要支持不难，我要想下API怎样设计

**Comment by songjygithub** [comment]
> 目前还不支持，但要支持不难，我要想下API怎样设计

期待！！！streamReader.readLineObject()也能解决目前的问题，感谢🙏！！！
