### ISSUE TITLE
BigDecimal 值序列化

### ISSUE THREAD

**Issue by fatallt** [alibaba/fastjson2#1652]
### 问题描述
*简要描述您碰到的问题。*
BigDecimal 值为25.000000000000000000的反序列化为对象值变成了6.553255926290448384

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：12th Gen Intel(R) Core(TM) i5-12500   3.00 GHz 16g]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.35]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
 String s2 = JSON.toJSONString(new BigDecimal("25.000000000000000000"));
 System.out.println(JSON.parseObject(s2, BigDecimal.class));

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*


### 相关日志输出
*请复制并粘贴任何相关的日志输出。*


#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*


![Screenshot 2023-07-17 102502](https://github.com/alibaba/fastjson2/assets/18119869/5898bf99-53ea-43ea-91ee-34f379c43a6b)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.36-SNAPSHOT/
问题已经修复，帮忙用2.0.36-SNAPSHOT版本验证

**Comment by fatallt** [comment]
2.0.36-SNAPSHOT已验证，可以用
