### ISSUE TITLE
[FEATURE]期望增加一个全局的方法，统一设置时区

### ISSUE THREAD

**Issue by iarrived** [alibaba/fastjson2#1653]
### 请描述您的需求或者改进建议
spring mvc返回的json日期格式，期望全部为类似“2022-12-12T12:12:12.121Z”的格式，当使用JSON.configWriterDateFormat("iso8601")时，由于机器默认时区为东八区，所以格式为“2022-12-12T12:12:12.121+8:00“。如果我们能有一个全局的函数，设置为0时区，就应该能等到期望的格式。

### 请描述你建议的实现方案
为JSON增加一个设置时区的函数，比如：JSON.configWriterZoneId(xxx)

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.36
请用新版本
