### ISSUE TITLE
jsonpath做过滤如果字段不存在，返回的非预期

### ISSUE THREAD

**Issue by dongxp** [alibaba/fastjson2#1667]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
1. 使用indexDatas[?(@.isSummary != 1)]时，如果其中一个JsonObject不存在isSummary字段，应该返回，但是看jsonpath代码里判断字段是空，直接返回false
2. 
![image](https://github.com/alibaba/fastjson2/assets/18159554/462afb36-65da-497a-baf4-c5b2e68f3e61)

### 期待的正确结果
不存在的字段就是null，结合过滤表达式时，应该与具体的值对象比较再返回，不应该直接返回false

### 相关日志输出
![image](https://github.com/alibaba/fastjson2/assets/18159554/d5cda717-3845-46d9-94d8-b40232fb4e54)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.37-SNAPSHOT/
问题已修复，请帮忙用2.0.37-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.37
请用新版本
