### ISSUE TITLE
[QUESTION] 1.x 和 2.x 对于 对象中字段类型为 byte[] 的处理问题

### ISSUE THREAD

**Issue by hidao** [alibaba/fastjson2#1668]
之前许多系统使用 1.x 序列化，现在打算将新开发的系统升级到 2.x，使用过程上发现 `byte[]` 类型的数据 1.x序列化的数据没法使用 2.x进行反序列化，了解到可以在反序列化的对象 `byte[]` 类型的字段中增加 `@JSONField(format = "base64")`，但由于序列化的对象是通用模块，不能依赖第三方类库，是否有 `.config(Feature.xxx)` 来进行全局配置呢

**Comment by wenshao** [comment]
```java
JSON.config(JSONReader.Feature.Base64StringAsByteArray)
```

**Comment by hidao** [comment]
> ```java
> JSON.config(JSONReader.Feature.Base64StringAsByteArray)
> ```

感谢，这个有效
