### ISSUE TITLE
v1兼容包JSONValidator不存在

### ISSUE THREAD

**Issue by rootshk** [alibaba/fastjson2#167]
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.2</version>
        </dependency>

import com.alibaba.fastjson.JSONValidator;
这个包不存在

**Comment by wenshao** [comment]
请你是怎么用的？这个不能完全兼容，我会尽量补充一些兼容的实现。

**Comment by rootshk** [comment]
package xxxx.xxx.xx;

import com.alibaba.fastjson.JSONValidator;

public class Util {
    public void send(Object o) {
        // 此处JSONValidator类不存在
        if (JSONValidator.from(o.toString()).validate()) {
            throw new ServiceException("error");
        }
    }
}

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/167061053-b5ead6ff-d99b-49d5-a397-13b7f7bea102.png)
