### ISSUE TITLE
[BUG] 反序列化不支持EnumMap类型

### ISSUE THREAD

**Issue by cycle2zhou** [alibaba/fastjson2#1679]
<img width="1236" alt="image" src="https://github.com/alibaba/fastjson2/assets/33155330/b53afa22-02bd-41f1-b883-76152700830a">

**Comment by cycle2zhou** [comment]
不行还是报错
<img width="1053" alt="image" src="https://github.com/alibaba/fastjson2/assets/33155330/e2a6a7e3-e123-4eef-aabb-542bc053d48b">

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.38-SNAPSHOT/
问题已修复，请更新快照用2.0.38-SNAPSHOT版本帮忙再验证下

**Comment by cycle2zhou** [comment]
测试通过 👍

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.38
请用新版本
