### ISSUE TITLE
[FEATURE] 注册objectWritter的时候是否能增加参数

### ISSUE THREAD

**Issue by DanteCY** [alibaba/fastjson2#1691]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*
//        JSON.register(CurveFitter.class,writer);
//        System.out.println(JSON.toJSONString(t,JSONWriter.Feature.PrettyFormat, JSONWriter.Feature.ReferenceDetection));

        JSONFactory.getDefaultObjectWriterProvider().register(CurveFitter.class,writer,true);
        System.out.println(JSON.toJSONString(t,JSONWriter.Feature.FieldBased,JSONWriter.Feature.PrettyFormat, JSONWriter.Feature.ReferenceDetection));
可以看到.注册ObjectWritter的时候.如果特性配置了FieldBased .则使用 JSON.register(CurveFitter.class,writer);是不会启用的
通过代码发现里面其实是有一个public方法能注册fieldbase的objectWritter的.
所以.能不能统一一下.那filedBase的objectWritter也能通过 JSON.register 来注册..
不然看着很奇怪..

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

 JSON.register(CurveFitter.class,writer,true);
### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.38
请用新版本
