### ISSUE TITLE
[QUESTION]  SerializerFeature.WriteNullListAsEmpty 找不到对应的包

### ISSUE THREAD

**Issue by catgptjourney** [alibaba/fastjson2#1692]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

从1.x 升级到 2.x 发现
@JSONField(serialzeFeatures = SerializerFeature.WriteNullListAsEmpty)
此注解找不到对应的包

望解答，谢谢。

**Comment by zoze0** [comment]
```java
JSONWriter.Feature.WriteNullListAsEmpty
```

参考1：https://github.com/alibaba/fastjson2/wiki/fastjson_1_upgrade_cn#fastjson-1x%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97

参考2：https://github.com/alibaba/fastjson2/wiki/Features_cn

**Comment by catgptjourney** [comment]
了解了，谢谢。
