### ISSUE TITLE
[BUG] 对象使用fluent模式时，fastjson序列化及反序列化失效

### ISSUE THREAD

**Issue by YAGAMIL** [alibaba/fastjson2#1701]
### 问题描述
*简要描述您碰到的问题。*
当使用lombok
@Accessors(fluent = true)
实现getter和setter方法时，fastjson序列化及反序列化字段都会失效

类似的FiledBase可以实现该效果，但与gson及jackson不一致
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `@Accessors(fluent = true)` 注解或者fluent模式生成getter及setter
2. 输入 JSON.toString或JSON.parseObject方法
3. 字段属性输出皆为空
```java
    @Test
    public void testParse() {
        FluentModel fluentModel = FluentModel.builder().name("test").order(1).build();
        String json = "{\"name\":\"test\",\"order\":1}";
        System.err.println(JSON.parseObject(json, FluentModel.class));
        System.out.println(fluentModel);
        System.err.println(JSON.toJSONString(fluentModel));

    }

    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Accessors(fluent = true)
    @Data
    public static class FluentModel {
        private String name;

        private Integer order;
    }
```

结果：
![image](https://github.com/alibaba/fastjson2/assets/16757285/358d5881-6f8a-4cbb-aa7a-e0d111fb0fad)

### 期待的正确结果
正反序列化应该都可以，但反序列化字段为null，序列化输出为空
*对您期望发生的结果进行清晰简洁的描述。*
fluent模式的字段属性可以被正反序列化

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
