### ISSUE TITLE
数据类型为List<Hashtable<String, String>>解析json串结果为空对象

### ISSUE THREAD

**Issue by lukeit** [alibaba/fastjson2#1707]
### 问题描述
fastjson2版本下，数据类型为List<Hashtable<String, String>>解析json串结果为空对象，换成List<HashMap<String, String>>就没有问题，同样的json串在fastjson下解析没有问题。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows 10 4Core 3.20GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 17.0.7]
 - 版本信息：[e.g.：Fastjson2 2.0.34+]
 

### 重现步骤
模型：
public class DictionaryModule implements Serializable {
    private static final long serialVersionUID = -1L;
    private String dictKey;
    private String tableName;
    private Hashtable<String, String> queryColumns;
    private Hashtable<String, List<HashMap<String, Object>>> params;
    private List<Hashtable<String, String>> orders;
...
}
json串：
'{"dictKey":"sys_post","tableName":"sys_post",' +
      '"queryColumns":{"code":"post_id","sort":"post_sort","label":"post_name","value":"post_id"},' +
      '"params":{"orCondition":[{"column":"status","operator":"<>","value":1},{"column":"status","operator":"is","value":null}]},' +
      '"orders":[{"column":"post_sort","sequences":"asc"},{"column":"create_time","sequences":"desc"}]}'
解析结果：orders属性只有两个空对象，其它属性没有问题；orders类型换成List<HashMap<String, String>>就没有问题，同样的json串在fastjson下解析没有问题。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
