### ISSUE TITLE
优化大对象 序列化 反序列化的内存占用

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/fastjson2#171]
优化大对象 序列化 反序列化的内存占用

**Comment by zzqangel** [comment]
FastJson使用上，目前看，除了安全问题外，遇到比较多的，就是内存占用的问题，引发gc，甚至导致JVM完全卡死的情况，都遇到过，请问fastJson2中是否有做优化呢？优化策略是什么呢

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
最新版本已经修复反序列化内存占用问题，请用更新到2.0.12版本
