### ISSUE TITLE
[BUG]序列化和反序列化出错，Dubbo使用过程中发现

### ISSUE THREAD

**Issue by C20171008S** [alibaba/fastjson2#1710]
JDK17
FastJson2.0.38
当变量默认值是true时在设置为false 序列化后反序列化无法成功

 
![iShot_2023-08-03_11 51 59](https://github.com/alibaba/fastjson2/assets/12716056/e3d400f5-9671-4d2e-afc8-91f3d9a231a0)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
