### ISSUE TITLE
[BUG]同时使用ContextValueFilter和ContextNameFilter时获取不到field信息

### ISSUE THREAD

**Issue by cbib-guoguifang** [alibaba/fastjson2#1713]
### 问题描述
在单独使用ContextValueFilter时可以正确获取到field，但是在同时使用ContextValueFilter和ContextNameFilter时就会出现获取不到field的情况

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.38]
 

### 重现步骤
```java
public static void main(String[] args) {
    UserInfo userInfo = new UserInfo();
    userInfo.setMobile("13012345678");
    userInfo.setUserId(123L);
    List<Filter> filters = new ArrayList<>();
    filters.add((ContextValueFilter) (context, object, name, value) -> {
        System.out.println("ContextValueFilter field: " + context.getField());
        return value;
    });
    filters.add((ContextNameFilter) (context, object, name, value) -> {
        System.out.println("ContextNameFilter field: " + context.getField());
        return name;
    });
    System.out.print(JSON.toJSONString(userInfo, filters.toArray(new Filter[0])));
}
```

#### 附加信息
![image](https://github.com/alibaba/fastjson2/assets/137134935/44a3c212-ec3f-4b0b-8577-8057aa3958c2)
![image](https://github.com/alibaba/fastjson2/assets/137134935/27ca84db-7f00-4f93-9a9f-b215bc088362)
![image](https://github.com/alibaba/fastjson2/assets/137134935/00a3d2a6-72a5-489b-9647-0a3c9608f5c8)
![image](https://github.com/alibaba/fastjson2/assets/137134935/214152b3-a01e-4a25-985c-24a097553293)

**Comment by MoshiCoCo** [comment]
我这里正常，贴一下Userinfo的类结构？

**Comment by MoshiCoCo** [comment]
把UserInfo里的private字段改成public试试。

**Comment by cbib-guoguifang** [comment]
> 把UserInfo里的private字段改成public试试。

你看我的图，在单独使用ContextValueFilter时是可以正确获取到field的信息的，但是在加上ContextNameFilter时才会出现两个filter都获取不到field的信息，而且为什么要把bean里的field改成public的，这不是说笑吗

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
