### ISSUE TITLE
[BUG] 当 属性为 public 修饰的 枚举类型时，其序列化结果与 getter 方法的返回值不一致

### ISSUE THREAD

**Issue by CodePlayer** [alibaba/fastjson2#1727]
### 问题描述

当  Java Bean 中存在一个 `public` 关键字修饰的 枚举类型属性时，Fastjson 2 将忽略 对应 getter 方法的输出，并强制使用该枚举属性直接输出。 
只有去掉 `public` 关键字，才能优先使用 getter 的返回值作为属性输出。

### 环境信息

 - OS信息：  Windows 10
 - JDK信息：JDK 17.0.6
 - 版本信息：Fastjson2 2.0.38
 

### 重现步骤
参考如下代码：

```java
	public static enum Color {

		RED(1),
		YELLOW(3),
		BLUE(5),
		;

		final Integer value;

		Color(Integer value) {
			this.value = value;
		}
	}

	@Getter
	public static class Bean {

		public Color color;

		public Integer getColor() {
			return color.value;
		}

	}

	@Test
	public void test() {
		final Bean bean = new Bean();
		bean.color = Color.BLUE;
		
		// 当 Bean.color 有 public 关键字修饰时，将输出 {"color":"BLUE"}
               // 去掉 Bean.color 的 public 关键字后，将输出 {"color":5}
		System.out.println(JSON.toJSONString(bean));
	}
```

### 期待的正确结果
除非指定了 `JSONReader.Feature.FieldBased` ，否则都应该默认优先基于 getter 的返回值进行序列化输出。

### 相关日志输出
无

#### 附加信息
无

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
