### ISSUE TITLE
[BUG] JSONObject#to接口在反序列化到record时，赋值异常

### ISSUE THREAD

**Issue by MagicFollower** [alibaba/fastjson2#1731]
### 问题描述🤔️
JSONObject#to接口在反序列化到record时，如果record中存在空参构造函数，则反序列化后record中属性为空参构造函数中赋值的数据。
移除空构造函数后，可以正常反序列化。

### 环境信息

 - OS信息：  Windows 11 22H2 AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz 64 GB
 - JDK信息： Openjdk 17
 - 版本信息：Fastjson2 2.0.38
 

### 重现步骤
1.创建一个含有空参构造函数的record🚩
```java
public record UserRecord(String id, String name, Integer age) {
    public UserRecord() {
        this(null, null, 37);
    }
}
```

2.执行反序列化操作🚩

```java
UserRecord userRecord = new UserRecord("test-id", "test-name", 999);
UserRecord userRecord1 = JSONObject.from(userRecord).to(UserRecord.class);
System.out.println(JSONObject.toJSONString(userRecord1, JSONWriter.Feature.PrettyFormat));
```

3.输出结果💣

```json
{
	"age":37
}
```

### 期待的正确结果😊
正常完成从json字符串到record的反序列化，数据填充不受record中空参构造函数影响
```json
{
	"age":999,
	"id":"test-id",
	"name":"test-name"
}
```

#### 附加信息🌐
谷歌的gson: 2.10.1不会出现上述情况
```java
UserRecord userRecord = new UserRecord("test-id", "test-name", 999);
Gson gson = new Gson();
UserRecord userRecord1 = gson.fromJson(gson.toJson(userRecord), UserRecord.class);
System.out.println(JSONObject.toJSONString(userRecord1, JSONWriter.Feature.PrettyFormat));
```
输出：
```json
{
	"age":999,
	"id":"test-id",
	"name":"test-name"
}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
问题已修复，请帮忙用2.0.39-SNAPSHOT版本验证，2.0.39版本预计在8月27日前发布

**Comment by MagicFollower** [comment]
fastjson2-2.0.39-20230814.044906-15.jar测试通过，解决很迅速，点赞👍

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
