### ISSUE TITLE
[BUG]使用JSONObject.parseObject时，会修改key值

### ISSUE THREAD

**Issue by shadow-dust** [alibaba/fastjson2#1734]
### 问题描述
将fastjson版本从1.2.73升级到2.0.38后，原本正常的parseObject会出现key值错误的情况

### 环境信息
*请填写以下信息：*

 - OS信息：  [Windows 10]
 - JDK信息： [jdk 1.8.0_291]
 - 版本信息：[Fastjson2 2.0.38]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSONObject.parseObject 方法
2. 输入 json字符串  数据
3. 出现 key值“access_token” 解析成“aceess_token” 错误
```java
String result = HttpUtil.post(BASE_OAUTH_URL + "token", header, params);
JSONObject tokenObj = JSONObject.parseObject(result);
```

### 期待的正确结果
tokenObj={access_token: "", refresh_token: "", token_type: "", expires_in: 3600}

#### 附加信息
解析出来的JSONObject对象
![b62c54aadeec712e5ea1da7da7a9ee7](https://github.com/alibaba/fastjson2/assets/60652562/e62264bc-5aa6-4cd8-95ae-538e31837a6a)
JSON字符串
![25ee035f626b6d096cb26eea9ec71cb](https://github.com/alibaba/fastjson2/assets/60652562/afb6c6b5-65bf-4479-8f6e-797a77a761bb)

**Comment by wenshao** [comment]
请提供文本代码重现问题的testcase，提供图片怎么重现啊

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本

**Comment by shadow-dust** [comment]
已解决，谢谢
