### ISSUE TITLE
[BUG]JSON.parseObject把字符串转换为对象的时候出现多余的前缀，使用小于等于2.0.33的版本就是正常的

### ISSUE THREAD

**Issue by 523219809** [alibaba/fastjson2#1735]
### 问题描述

Joson字符串转换的时候会出现多余的字符串

### 环境信息

 - OS信息：  [e.g.：window11
 - JDK信息： [e.g.：Openjdk 14
 - 版本信息：[e.g.：Fastjson2.0.38
 
### 2、如果USERNAME设置为空或者删掉这个字段就能正常显示。
var Json = "{\"DG_GridMain\":[{\"PKFIELDNAME\":\"USERID\",\"USERNAME\":\"测试\"}],\"DG_GridColumn\":[{\"FIELDNAME\":\"USERID\"}]}";
var JsonObj = JSON.parseObject(Json);
发生问题的图如下，这个箭头不应该是这样的应该是没有PK的：
![image](https://github.com/alibaba/fastjson2/assets/7053590/f15ff001-f2eb-4976-918f-367dea3f1bd7)
使用小于等于2.0.33的版本就是正常的：
![image](https://github.com/alibaba/fastjson2/assets/7053590/33af357d-6ab8-45ba-beb2-819a559b3a60)

### 期待的正确结果
希望别在有多余的东西出现。

**Comment by 523219809** [comment]
依然还是有问题
&nbsp;


Admin
***@***.***



&nbsp;

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.39-SNAPSHOT/
请帮忙更新快照用2.0.39-SNAPSHOT版本再验证一次看问题是否还存在，该问题只在JDK 8下会存在。

**Comment by 523219809** [comment]
今天下午2点的这个没问题，非常感谢，我是挨个试的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
请用新版本
