### ISSUE TITLE
JSONField 在fastjson2中未支持defaultValue

### ISSUE THREAD

**Issue by chinayin** [alibaba/fastjson2#174]
fastjson1中  以下是支持的
@JSONField(ordinal = 1, name = "job", defaultValue = "ChatMessageMedia")

fastjson2 未支持

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.3-SNAPSHOT/

在2.0.3-SNAPSHOT版本中已经支持，2.0.3正式发布预计在月底
