### ISSUE TITLE
[BUG]序列化对象时JSONWriter.Feature.BrowserCompatible对属性List<Long>类型无效

### ISSUE THREAD

**Issue by zh112500** [alibaba/fastjson2#1742]
### 问题描述
*序列化对象时JSONWriter.Feature.BrowserCompatible对属性List\<Long\>类型无效*

### 环境信息

 - 版本信息：[e.g.：Fastjson2 2.0.39]
 

### 重现步骤
```java
  @Getter
  public static class TestFastJson {
      private long a = 1443605444282772302L;
      private List\<Long\> b = new ArrayList\<Long\>() {{
          add(1443605444282772302L);
          add(1443605444282772303L);
          add(1443605444282772304L);
      }};
  }

  public static void main(String[] args) {
      System.out.println(JSON.toJSONString(new TestFastJson(), JSONWriter.Feature.BrowserCompatible));
  }
```

### 期待的正确结果
*{"a":"1443605444282772302","b":[“1443605444282772302”,“1443605444282772303”,“1443605444282772304”]}。*

### 相关日志输出
*{"a":"1443605444282772302","b":[1443605444282772302,1443605444282772303,1443605444282772304]}*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
请帮忙用2.0.40-SNAPSHOT验证问题是否已经修复

**Comment by zh112500** [comment]
已解决

**Comment by zh112500** [comment]
![微信截图_20230821102410](https://github.com/alibaba/fastjson2/assets/35336336/03c86405-2084-4327-8ed5-60819fb6fc21)
![微信截图_20230821102455](https://github.com/alibaba/fastjson2/assets/35336336/3a1aece9-6620-47f3-8847-a7c7b2878d05)
又出现新的问题了！！！

**Comment by GabrielHwang** [comment]
是应该全都 !(v <= 9007199254740991L && v >= -9007199254740991L);

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40 
请用新版本，这个版本部分修复。完整修复预计在2.0.41版本

https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.41-SNAPSHOT/
请帮忙用2.0.41-SNAPSHOT验证问题是否已经完全修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
请用新版本
