### ISSUE TITLE
dubbo 系列化日期类型变成hashMap

### ISSUE THREAD

**Issue by rickiehsu** [alibaba/fastjson2#1743]
### 请描述您的问题
dubbo 3.2.4
采用内置的fastjson序列化

dubbo provider在对map对象中的java.util.Date和java.sql.timestamp序列化后反序列化变成Hashmap对象，需要在dubbo环境怎么配置dateFormat？

![image](https://github.com/alibaba/fastjson2/assets/15170218/a3fc4e45-985d-4699-8ebd-4d3ef318f3d7)

**Comment by wenshao** [comment]
提供的信息无法诊断问题，能提供更多信息么？比如：
fastjson2版本，接口类型信息

**Comment by rickiehsu** [comment]
解决问题了。把java.sql.Date和java.sql.Timestamp加入到白名单。谢谢。
