### ISSUE TITLE
[BUG]”is“开头的boolean类型属性值丢失

### ISSUE THREAD

**Issue by luckytao** [alibaba/fastjson2#1754]
### 问题描述
*简要描述您碰到的问题。*
我把fastjson从1.x升级到2.x最新版本2.0.39，发现在JSONObject的toJavaObject方法时，boolean类型属性如果时is开头的值丢失。

### 环境信息
*请填写以下信息：*

 - OS信息：  win11
 - JDK信息： jdk1.8
 - 版本信息：2.0.39
 

### 重现步骤
public class AttributeEntity {
    private String name;
    private String type;
    private boolean isRequired;
    private boolean isMultivalued;
   ...........
}

public class JsonTest {

    public static void main(String[] args) {
        JSONObject json = new JSONObject();
        json.put("name","test");
        json.put("isRequired",true);
        json.put("isMultivalued","true");
        AttributeEntity obj = json.toJavaObject(AttributeEntity.class, JSONReader.Feature.SupportSmartMatch);
        System.out.println(obj.toString());
    }
}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本
