### ISSUE TITLE
[BUG]json解析字符串乱码

### ISSUE THREAD

**Issue by winskyan** [alibaba/fastjson2#1755]
### 问题描述
*简要描述您碰到的问题。*
解析字符串 "{\"code\":0,\"message\":\"success\",\"sid\":\"ist000dcb32@dx189fc5a39f87910822\",\"data\":{\"status\":1,\"result\":{\"sn\":4,\"dd\":false}}}" 
出现乱码
String str="{\"code\":0,\"message\":\"success\",\"sid\":\"ist000dcb32@dx189fc5a39f87910822\",\"data\":{\"status\":1,\"result\":{\"sn\":4,\"dd\":false}}}";
JSONObject jsonObject = JSON.parseObject(str);
Log.e(TAG, "testJson: " + jsonObject.toJSONString());

### 环境信息
*请填写以下信息：*

 - OS信息：  Android
 - JDK信息：1.8
 - 版本信息：2:2.0.39
 

### 重现步骤
    implementation 'com.alibaba.fastjson2:fastjson2:2.0.39'

String str="{\"code\":0,\"message\":\"success\",\"sid\":\"ist000dcb32@dx189fc5a39f87910822\",\"data\":{\"status\":1,\"result\":{\"sn\":4,\"dd\":false}}}";
JSONObject jsonObject = JSON.parseObject(str);
Log.e(TAG, "testJson: " + jsonObject.toJSONString());

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by kraity** [comment]
similar to #1744

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本
