### ISSUE TITLE
[QUESTION] JSONFeature.SupportAutoType标识为deprecated并且移除内置黑名单

### ISSUE THREAD

**Issue by alon-sys** [alibaba/fastjson2#1756]
JSONFeature.SupportAutoType标识为deprecated并且移除内置黑名单，有相应的替换解决方案吗？

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.JSONWriter;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.ByteBufInputStream;
import io.netty.buffer.ByteBufOutputStream;
import org.redisson.client.codec.BaseCodec;
import org.redisson.client.protocol.Decoder;
import org.redisson.client.protocol.Encoder;

import java.io.IOException;

public class FastJsonCodec extends BaseCodec {
    /**
     * 编码器
     */
    private final Encoder encoder = in -> {
        ByteBuf out = ByteBufAllocator.DEFAULT.buffer();
        try {
            ByteBufOutputStream os = new ByteBufOutputStream(out);
            JSON.writeTo(os, in, JSONWriter.Feature.WriteClassName);
            return os.buffer();
        } catch (Exception e) {
            out.release();
            throw new IOException(e);
        }
    };

    /**
     * 解码器
     */
    private final Decoder<Object> decoder = (buf, state) ->
            JSON.parseObject(new ByteBufInputStream(buf), Object.class, JSONReader.Feature.SupportAutoType);

    @Override
    public Decoder<Object> getValueDecoder() {
        return decoder;
    }

    @Override
    public Encoder getValueEncoder() {
        return encoder;
    }
}

去掉JSONReader.Feature.SupportAutoType，解析就异常了

**Comment by luckytao** [comment]
https://github.com/alibaba/fastjson2/wiki/fastjson2_autotype_cn

看下文档吧

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/wiki/fastjson2_autotype_cn
看文档中的第5点

**Comment by alon-sys** [comment]
好的，谢谢
