### ISSUE TITLE
[QUESTION]  UTF8转换异常，疑似bug

### ISSUE THREAD

**Issue by zzgwd** [alibaba/fastjson2#1757]
JSONWriterUTF8.java  版本号2.0.39

 @Override
    public final void write(JSONObject map) {
        。。。
            if (!first) {
                if (off == bytes.length) {
                    ensureCapacity(off + 1);
                }
                **if (value != null && (context.features & Feature.WriteMapNullValue.mask) == 0) {
                    bytes[off++] = ',';
                }**
            }
。。。
}

加粗这行是否逻辑有问题，是否应该是使用 || 进行连接。序列化出现json字符串缺少“,”

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本
