### ISSUE TITLE
dubbo反序列化属性被篡改

### ISSUE THREAD

**Issue by rickiehsu** [alibaba/fastjson2#1758]
### 问题描述
*简要描述您碰到的问题。*
对象属性值在反序列化后属性被篡改。

此问题在之前出现过：
https://github.com/alibaba/fastjson2/issues/1636
服务重启后问题消失。

### 环境信息
*请填写以下信息：*
 - OS信息：  Window11
 - JDK信息： JDK1.8
 - 版本信息：FastJson2.0.34/dubbo3.2.4
  

### 重现步骤
1. 在反序列化时对FastJson2ObjectInput的readObject打上debugger，然后查看bytes数据
<img width="922" alt="Snipaste_2023-08-16_17-46-50" src="https://github.com/alibaba/fastjson2/assets/15170218/384a867b-f05f-403d-8f28-454ffa9e4cdb">
属性为tf_pkid正确
2. 检查 JSONB.parseObject 是否存在问题 JSONB.parseObject(bytes,QueryModel.class)
<img width="840" alt="Snipaste_2023-08-16_17-49-46" src="https://github.com/alibaba/fastjson2/assets/15170218/3ea1e890-7a1d-4f98-8aae-05735391857d">
属性为tf_pkid正确
3.   检查FastJson2ObjectInput的readObject 对JSONB.parseObject完整参数评估结果发现不正确
<img width="906" alt="Snipaste_2023-08-16_17-43-36" src="https://github.com/alibaba/fastjson2/assets/15170218/939f74e9-3fd1-4d5a-8ab7-91bf18e6437a">
属性为to_pkid不正确 ，然后再次对securityFilter设置为null，在进行评估也是不正确属性为to_pkid
![9VOXCF_`1W (JO7B(~U$K~X](https://github.com/alibaba/fastjson2/assets/15170218/37b474f9-1380-4037-b351-1df86a3fa4ec)

4. 对byte进行写入到文件
[querymodel.zip](https://github.com/alibaba/fastjson2/files/12358342/querymodel.zip)
toJsonString样式为：
`{
	"@type":"com.airboot.model.QueryModel",
	"checkPerm":true,
	"draw":2,
	"limit":20,
	"orderClauses":[
		{
			"ascending":true,
			"fieldName":"seq_no"
		}
	],
	"queryObj":{
		"tf_type":"EO",
		"tf_pkid":"3299"
	}
}`
6. 单独对querymodel.dump文件反序列化也没有问题，如图
![image](https://github.com/alibaba/fastjson2/assets/15170218/cdffc473-a810-417e-a7fd-771e3315808d)

[java.zip](https://github.com/alibaba/fastjson2/files/12358396/java.zip)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.39
该问题在2.0.39版本中修复了，请帮忙在用 2.0.39验证下问题是否已经还存在

**Comment by rickiehsu** [comment]
已解决。
