### ISSUE TITLE
快的核心原理是什么？

### ISSUE THREAD

**Issue by chummyhe89** [alibaba/fastjson2#176]
相比于Jackson gson 等同类库，快那么多的原因是？
先mark，有时间自己研究下。

**Comment by CodeInDreams** [comment]
我采访了一些同事，快其实主要是开发快：  
静态访问不需要bean；  
运行时异常也不用单独try-catch；  
常用的序列化/反序列化功能都有。

**Comment by wenshao** [comment]
快的原因：
1. 用了一个避免构造Key的算法，具体看这里 https://github.com/alibaba/fastjson2/wiki/design_doc_cn
2. 通过ASM动态JIT的方式针对每个JavaBean生成Parser，使得parse的过程更紧凑
3. 很多编程技巧，比如 https://github.com/alibaba/fastjson2/wiki/fastjson_string_codec_methods

**Comment by timandy** [comment]
@wenshao 字段模式是否支持 ASM生成代码

**Comment by wenshao** [comment]
> @wenshao 字段模式是否支持 ASM生成代码

支持
