### ISSUE TITLE
[BUG] JSONArray反序列化带泛型的自定义集合不正确

### ISSUE THREAD

**Issue by haihaisea** [alibaba/fastjson2#1761]
![image](https://github.com/alibaba/fastjson2/assets/17777292/b6ad4be5-303b-4065-8068-1be3d39df70a)

**Comment by wenshao** [comment]
为了方便构造testcase，请提供代码，而不是提供图片

**Comment by haihaisea** [comment]
测试代码
```
public class JsonArrayTest {

    @Test
    public void test(){
        String    json      = "[{'userId':'123'}]";
        JSONArray jsonArray = JSON.parseArray(json);

        MyListImpl<User> myList = jsonArray.to(new TypeReference<MyListImpl<User>>() {}.getType());

        Assertions.assertTrue(myList.size() == 1);
    }
}
```

自定义集合
```
public class MyListImpl<E> extends ArrayList<E>{

}
```

Domain
```
@Getter
@Setter
public class User {
    private String userId;
}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by cbib-guoguifang** [comment]
@wenshao 这个问题我使用你最新的2.0.40-SNAPSHOT版本还是依旧有问题，经过我多次验证，发现在实现一个接口的时候，如果set方法返回值是接口类型及泛型时会出现这个问题，在你的testcase上复现了一下问题，比较代码如下
`public class Issue1676 {
    
    public static void main(String[] args) {
        test1();
        test2();
    }
    
    private static void test1() {
        ParameterizedType parameterizedType = new ParameterizedType() {
            @Override
            public Type[] getActualTypeArguments() {
                return new Type[] {Bean.class};
            }
            
            @Override
            public Type getRawType() {
                return PageImpl.class;
            }
            
            @Override
            public Type getOwnerType() {
                return null;
            }
        };
        String s = "{\"current\":1,\"hitCount\":false,\"optimizeCountSql\":true,\"orders\":[],\"pages\":1,\"records\":[{\"name\": \"test\"}],\"searchCount\":true,\"size\":10,\"total\":1}";
        PageImpl fastJson2PageObject = com.alibaba.fastjson2.JSON.parseObject(s, parameterizedType);
        System.out.println("实现IPage接口的fastJson2解析结果：");
        System.out.println(Objects.equals(Bean.class, fastJson2PageObject.getRecords().get(0).getClass()));
        
        PageImpl fastJson1PageObject = com.alibaba.fastjson.JSON.parseObject(s, parameterizedType);
        System.out.println("实现IPage接口的fastJson1解析结果：");
        System.out.println(Objects.equals(Bean.class, fastJson1PageObject.getRecords().get(0).getClass()));
    }
    
    private static void test2() {
        ParameterizedType parameterizedType = new ParameterizedType() {
            @Override
            public Type[] getActualTypeArguments() {
                return new Type[] {Bean.class};
            }
            
            @Override
            public Type getRawType() {
                return Page.class;
            }
            
            @Override
            public Type getOwnerType() {
                return null;
            }
        };
        
        String s = "{\"current\":1,\"hitCount\":false,\"optimizeCountSql\":true,\"orders\":[],\"pages\":1,\"records\":[{\"name\": \"test\"}],\"searchCount\":true,\"size\":10,\"total\":1}";
        Page fastJson2PageObject = com.alibaba.fastjson2.JSON.parseObject(s, parameterizedType);
        System.out.println("不实现IPage接口的fastJson2解析结果：");
        System.out.println(Objects.equals(Bean.class, fastJson2PageObject.getRecords().get(0).getClass()));
    }
    
    public static class Bean {
        
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
    }
    
    public interface IPage<T> extends Serializable {
        
        List<T> getRecords();
        
        // 问题出现在这里，如果这里返回结果是IPage<T>，那么fastjson2就会解析有问题，但fastjson1不会有问题；如果返回结果是void也不会有问题
        IPage<T> setRecords(List<T> records);
        
    }
    
    public static class PageImpl<T> implements IPage<T> {
        
        protected List<T> records;
        
        @Override
        public List<T> getRecords() {
            return this.records;
        }
        
        @Override
        public PageImpl<T> setRecords(List<T> records) {
            this.records = records;
            return this;
        }
    }

    public static class Page<T> {
        private List<T> records;

        public List<T> getRecords() {
            return records;
        }

        public Page<T> setRecords(List<T> records) {
            this.records = records;
            return this;
        }
    }
}`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本
