### ISSUE TITLE
代码实现细节探讨 与 疑似bug确认

### ISSUE THREAD

**Issue by CodePlayer** [alibaba/fastjson2#1765]
https://github.com/alibaba/fastjson2/blob/89f84378448297c61a9c8b71cd9f98993efac0bb/core/src/main/java/com/alibaba/fastjson2/writer/ObjectWriterCreatorASM.java#L3163-L3169

上述代码片段存在两个重复的分支条件判断，且代码不一致。
建议核实一下是否无误，并去掉冗余的代码。

**Comment by wenshao** [comment]
确实是重复了，你提交的PR为啥关了啊

**Comment by CodePlayer** [comment]
提交时，Author 名称没有和 Github 的 Name 完全一致，签署 协议 Agreement 时遇到点问题，所以就 关闭 重新提交了。

**Comment by CodePlayer** [comment]
#### 数组 `typeTable` 在这里只是被初始化并赋值，但实际并没有用到。

如果只需要循环 `read*`，那就没必要保留这个 `typeTable`。

https://github.com/alibaba/fastjson2/blob/e2152602bb0219fb074b9d1b0069d970034689ed/core/src/main/java/com/alibaba/fastjson2/internal/asm/ClassReader.java#L219-L225

**Comment by CodePlayer** [comment]
`case 19` 没有 `break`，继续向下执行，`readLocalDateTime19()` 会被 `readLocalDateTime20()` 覆盖。

https://github.com/alibaba/fastjson2/blob/e2152602bb0219fb074b9d1b0069d970034689ed/core/src/main/java/com/alibaba/fastjson2/JSONReader.java#L1669-L1680

**Comment by CodePlayer** [comment]
https://github.com/alibaba/fastjson2/blob/e2152602bb0219fb074b9d1b0069d970034689ed/core/src/main/java/com/alibaba/fastjson2/writer/ObjectWriterCreatorASM.java#L40-L58

1. 第 46 行的 `property` 是不是写错了 ？应该是 `str` 吧？
2. 第 50 行的 `value ` 变量只被初始化并赋值，但没有被用到。是冗余的代码，还是不小心漏掉了相应的使用代码 ？

**Comment by wenshao** [comment]
> 

46的property是对的，在JVM启动参数是如下的场景：
```
-Dfastjson2.disableStringUnsafeGet
```

但DISABLE_STRING_UNSAFE_GET已经不再使用了，应该整块代码要删除，DISABLE_STRING_UNSAFE_GET字段也要删除。

**Comment by wenshao** [comment]
> 

对的，是漏了

**Comment by wenshao** [comment]
> `case 19` 没有 `break`，继续向下执行，`readLocalDateTime19()` 会被 `readLocalDateTime20()` 覆盖。
> 
> https://github.com/alibaba/fastjson2/blob/e2152602bb0219fb074b9d1b0069d970034689ed/core/src/main/java/com/alibaba/fastjson2/JSONReader.java#L1669-L1680

这个地方是漏了break

**Comment by wenshao** [comment]
> 



> #### 数组 `typeTable` 在这里只是被初始化并赋值，但实际并没有用到。
> 如果只需要循环 `read*`，那就没必要保留这个 `typeTable`。
> 
> https://github.com/alibaba/fastjson2/blob/e2152602bb0219fb074b9d1b0069d970034689ed/core/src/main/java/com/alibaba/fastjson2/internal/asm/ClassReader.java#L219-L225

对的，这个地方可以去掉 typeTable

**Comment by CodePlayer** [comment]
> https://github.com/alibaba/fastjson2/blob/e2152602bb0219fb074b9d1b0069d970034689ed/core/src/main/java/com/alibaba/fastjson2/writer/ObjectWriterCreatorASM.java#L40-L58
> 
> 1. 第 46 行的 `property` 是不是写错了 ？应该是 `str` 吧？
> 2. 第 50 行的 `value ` 变量只被初始化并赋值，但没有被用到。是冗余的代码，还是不小心漏掉了相应的使用代码 ？

我明白你的意思。但从代码来看，这里的意思：

1. 先从`System.getProperty(key)` 获取这个设置属性（赋值给变量 `property`）；
2. 如果为空，就再从 `JSONFactory.getProperty(key)` 获取（赋值给变量 `str`）。
3. 如果 `str` 的值不为空（ 46行 这里的判断应该是判断 `str` 不为空，也就是 ` str != null && !str.isEmpty()`，而**不是**目前的 ` str != null && !property.isEmpty()` ），就赋值给 `property`。

**Comment by wenshao** [comment]
> fastjson2.disableStringUnsafeGet

不用纠结这个了，这个已经是废弃代码，我把这块代码删了
