### ISSUE TITLE
[FEATURE] jsonschema 支持递归引用

### ISSUE THREAD

**Issue by shpodg** [alibaba/fastjson2#1766]
### 支持如下格式的jsonschema解析
```json
{
  "$defs": {
    "person": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "children": { "$ref": "#/$defs/personList" }
      }
    },
    "personList": {
      "type": "array",
      "items": { "$ref": "#/$defs/person" }
    }
  },
  "type": "object",
  "properties": {
    "family": { "$ref": "#/$defs/person" }
  }
}
```
当前使用版本2.0.39
解析后的schema对如下json进行校验报错
```json
{"family":{"name":"1","children":[{"name":"2"}]}}
```
报错信息
> com.alibaba.fastjson2.JSONSchemaValidException: property family invalid; property children invalid; not fail

查看解析后的schema发现如下内容，循环引用的部分被解析成为了not any
![image](https://github.com/alibaba/fastjson2/assets/16442317/b31072c5-01e8-4e87-a14f-b3864987c6ff)

**Comment by wenshao** [comment]
支持的啊，你遇到什么问题了

**Comment by shpodg** [comment]
> 支持的啊，你遇到什么问题了

问题信息已经补充

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本
