### ISSUE TITLE
[BUG]SnakeCaseStrategy驼峰下划线互相转化的问题

### ISSUE THREAD

**Issue by sk142857** [alibaba/fastjson2#1768]
### 问题描述

**Comment by CodePlayer** [comment]
@sk142857 
1. `@JsonNaming` 是 Jackson 的注解诶，你不要把 Fastjson 和 Jackson **搞混** 了！ 
    如果只想对单个类使用 SnakeCase，可以在类上面加 Fastjson 2的注解 `@JSONType(naming = PropertyNamingStrategy.SnakeCase)`。
    如果想对所有类使用，则可以 `JSON.toJSONString(userDto, NameFilter.of(PropertyNamingStrategy.SnakeCase))`。
2. 直接输出当然没有效果，因为你都用错方法了。在你的代码里面，`JSON.toJSON( )` 只是把 `userDto` 转为了 `JSONObject`，打印的时候，只是相当于自动调用了 `JSONObject.toString()` 方法，这个方法是**不**包含 `JSONWriter.Feature.WriteNulls` 这个特性的，自然也就不会输出为 null 的字段。 
    你应该将 `JSON.toJSON( )`  改为 `JSON.toJSONString( )`。
