### ISSUE TITLE
JSONObject.put()泛型警告⚠️

### ISSUE THREAD

**Issue by xiangyunup** [alibaba/fastjson2#177]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/33372099/167080387-0b8926d8-8cee-4d58-955b-1543db999dd3.png">

使用新的JSONObject 对象构建的时候，工具会提示一个泛型警告⚠️
强迫症看着很难受，如果可以的话，希望可以优化掉；

**Comment by xiangyunup** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.3-SNAPSHOT/
> 
> 你试下新的快照版本，看问题是否已经解决

我依赖不到这个快照版本，下载下来本地配置了，修改了包路径也识别不了；只能你这边看看了

**Comment by VirensCn** [comment]
其实这个问题很好解决，只需要在[JSONObject ](https://github.com/alibaba/fastjson2/blob/79db68b54cec10e0d03ea6e3ccecff3b8158ac65/core/src/main/java/com/alibaba/fastjson2/JSONObject.java#L18)类继承的LinkedHashMap 上添加泛型申明，LinkedHashMap <String,Object> 或者LinkedHashMap <Object,Object>

**Comment by xiangyunup** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.3-SNAPSHOT/
> 
> 你试下新的快照版本，看问题是否已经解决

经过对这个快照版本的测试，put方法已经不在提示泛型警告；但是 putAll 方法任然存在警告提示；

**Comment by wenshao** [comment]
putAll不好解决
