### ISSUE TITLE
[BUG] Support nested duplicate keys when enable DuplicateKeyValueAsArray

### ISSUE THREAD

**Issue by cxzl25** [alibaba/fastjson2#1786]
### 问题描述
```
String json = "{\"c1\":{\"a\":1,\"a\":2}}";
JSONObject jsonObject =JSON.parseObject(json, JSONReader.Feature.DuplicateKeyValueAsArray);
System.out.println(((JSONObject) jsonObject.get("c1")).get("a").toString());
```
Output
```
2
```

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：Fastjson2 2.0.39
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
```
[1,2]
```

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
请用新版本
