### ISSUE TITLE
[BUG] fastjson 解析businessType有问题

### ISSUE THREAD

**Issue by Ive4** [alibaba/fastjson2#1800]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
public static void main(String[] args) {
    var req =
        JSON.parseObject(
            "{\n" + "  \"cardStruct\": \"2\",\n" + "  \"businessType \": 2,\n" + "}\n");

    Validations.notNull(req.getInteger("businessType"), " 不能为空");
  }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by Ive4** [comment]
22.3.r19-gr，macos 14beta

**Comment by 82295007** [comment]
![image](https://github.com/alibaba/fastjson2/assets/7088584/d389039f-f5e6-45b4-9281-074af834bde9)
