### ISSUE TITLE
[BUG]dubbo3.2.5使用triple协议+fastjson2序列化，RPC调用报错UnsupportedOperationException

### ISSUE THREAD

**Issue by 237chenhao** [alibaba/fastjson2#1805]
### 问题描述
dubbo3.2.5中默认是使用fastjson2序列化和反序列化，RPC方法参数中包含自定义枚举类时，序列化报错。简单查看了源码确认应该是fastjson2的问题。
报错信息：
![image](https://github.com/alibaba/fastjson2/assets/12470925/2fd35b03-2d11-4b32-bd4b-ed4a5f46d9d2)
问题应该是出在com.alibaba.fastjson2.writer.ObjectWriterCreatorASM类
![image](https://github.com/alibaba/fastjson2/assets/12470925/6879251c-57f0-4c65-aa3d-1b1d66717070)
最终返回的是FieldWriterObject类，FieldWriterObject并没有实现方法writeEnumJSONB
![image](https://github.com/alibaba/fastjson2/assets/12470925/7dbabb90-3f5c-465d-b37a-1ae8bfcac5ce)
我的枚举类：
![image](https://github.com/alibaba/fastjson2/assets/12470925/b1c36203-7ceb-494e-aba9-4901aefaa05b)

### 环境信息
*请填写以下信息：*

 - OS信息：  mac
 - JDK信息： jdk17
 - 版本信息：2.0.39

### 期待的正确结果
正确实现序列化和反序列化

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by 237chenhao** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/ 问题已修复，请用2.0.40-SNAPSHOT帮忙验证

验证已OK，太棒了，效率杠杠的！

**Comment by wenshao** [comment]
预计9月3日（本周末）发布2.0.40版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
请用新版本
