### ISSUE TITLE
使用JSON.isValid(String text)校验字符串是否是个json时，很多情况都是不准确的

### ISSUE THREAD

**Issue by gemo12123** [alibaba/fastjson2#181]
` System.out.println(JSON.isValid("123"));//true`
`System.out.println(JSON.isValid("1}"));//true`
`System.out.println(JSON.isValid("\"aaa\""));//抛出数组下标越界异常`

**Comment by wsxe9988** [comment]
123 纯数字确实符合json规范，后两个确实是bug

**Comment by gemo12123** [comment]
> 123 纯数字确实符合json规范，后两个确实是bug

请问在哪里可以找到纯数字符合json规范的相关说明呢？我在www.json.org中看到了对JSON的说明，但是我理解他的说明中并不包含这一点。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/

@gemo12123 你用快照版本试试看

**Comment by wsxe9988** [comment]
> > 123 纯数字确实符合json规范，后两个确实是bug
> 
> 请问在哪里可以找到纯数字符合json规范的相关说明呢？我在www.json.org中看到了对JSON的说明，但是我理解他的说明中并不包含这一点。

![image](https://user-images.githubusercontent.com/5828057/167240724-f052ca36-faae-452d-b3bd-22e7193f5d9d.png)
在线json格式化或者检验工具  输入纯数字(如123)都是显示正确json

**Comment by dezhonger** [comment]
> > 123 纯数字确实符合json规范，后两个确实是bug
> 
> 请问在哪里可以找到纯数字符合json规范的相关说明呢？我在www.json.org中看到了对JSON的说明，但是我理解他的说明中并不包含这一点。

https://www.json.org/json-en.html 这个DFA就是json的规范定义。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.3-SNAPSHOT/
已经修复，你可以用快照版本先验证。预计月底发布的2.0.3版本
