### ISSUE TITLE
[BUG] 反序列化西班牙语加了换行\n，会乱码

### ISSUE THREAD

**Issue by chuankang** [alibaba/fastjson2#1811]
### 问题描述

- 

String json = "{"remark":"1. ¡Múltiples\n 2. six" }";
Request req = com.alibaba.fastjson.JSON.parseObject( json, Request.class);

**序列化后的结果：remark-> 1. ﾡM￺ltiples \n 2. six**

- 

String json = "{"remark":"1. ¡Múltiples 2. six" }";
Request req = com.alibaba.fastjson.JSON.parseObject( json, Request.class);

**序列化后的结果：remark-> 1. ¡Múltiples 2. six**

**所以是加了\n导致的问题，请问怎么解决呢**

**Comment by wenshao** [comment]
什么版本？

**Comment by chuankang** [comment]
fastjson-2.0.11

**Comment by chuankang** [comment]
> 什么版本？

fastjson-2.0.11

**Comment by wenshao** [comment]
更新到2.0.40试试看

**Comment by chuankang** [comment]
2.0.40可以，谢谢

**Comment by chuankang** [comment]
> 更新到2.0.40试试看

2.0.40 可以，谢谢
