### ISSUE TITLE
[BUG] jdk17 JSONB.toBytes 数组越界

### ISSUE THREAD

**Issue by SmileTower** [alibaba/fastjson2#1812]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Win10]
 - JDK信息： [e.g.：Oracle Jdk 17.0.8]
 - 版本信息：[e.g.：Fastjson2 2.0.39]
 

### 重现步骤

```java
@Data
public class Driver3 implements Serializable {
    private List<String> names;
}

@Test
  public void tes10() {
      List<Map<String, List<String>>> list = Lists.newArrayList();
      for (int i = 0; i < 10; i++) {
          Map<String, List<String>> map = Maps.newHashMap();
          map.put("names", ListUtil.of(RandomUtil.randomString(10000)));
          list.add(map);
      }
      List<Driver3> s1 = JSON.parseArray(JSON.toJSONString(list), Driver3.class);
      JSONB.toBytes(s1);
  }

```
java 8 正常，java 11、17 都报错
只要最简单的嵌套， JSONB.toBytes  超过一定数量就报错，只要改变循环次数或者随机字符串长度即会报错，应该跟哪块内存有关
### 相关日志输出
```java
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 209962 out of bounds for byte[209952]

	at java.base/java.lang.System.arraycopy(Native Method)
	at com.alibaba.fastjson2.JSONWriterJSONB.writeString(JSONWriterJSONB.java:695)
	at com.alibaba.fastjson2.writer.OWG_1_47_DriverEntity2.writeJSONB(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.writeJSONB(ObjectWriterImplList.java:230)
	at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:1104)

```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by wenshao** [comment]
已经删除内容，并且修复问题，请更新快照帮忙再验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本

**Comment by palytoxin** [comment]
jdk21，2.0.61 错误复现，退回2.0.40正常  @wenshao

**Comment by jujn** [comment]
> jdk21，2.0.61 错误复现，退回2.0.40正常

你好，能否提供测试用例 ？

**Comment by palytoxin** [comment]
@jujn 数据不太方便公开，提供邮箱或者其他方式我发你

<img width="1231" height="392" alt="Image" src="https://github.com/user-attachments/assets/a82951db-3e47-4a3f-b803-b8f7830f1345" />

**Comment by jujn** [comment]
> [@jujn](https://github.com/jujn) 数据不太方便公开，提供邮箱或者其他方式我发你
> 
> <img alt="Image" width="1231" height="392" src="https://private-user-images.githubusercontent.com/1829328/556683090-a82951db-3e47-4a3f-b803-b8f7830f1345.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzI0Mjc0ODYsIm5iZiI6MTc3MjQyNzE4NiwicGF0aCI6Ii8xODI5MzI4LzU1NjY4MzA5MC1hODI5NTFkYi0zZTQ3LTRhM2YtYjgwMy1iOGY3ODMwZjEzNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAzMDJUMDQ1MzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRiZWE1MjVhMjQyMWRmNTNhNGE4MmQ4NTEzMmE4NGMwMWQ0YjlhYmMxMWJhYzFjMjdlODJmNjBkNmEyODJmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wCx2jBDQGXx5IUqKgSOBsvtyWe_u2Z7GHg32EXYjO48">

@palytoxin 在这里上传是否可以？我收到后告诉你，即可删除
