### ISSUE TITLE
[BUG]JSONArray.toJavaList反序列化结果和JSONObject.parseArray不同

### ISSUE THREAD

**Issue by cyandata** [alibaba/fastjson2#1813]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息： MacOS 13.4.1 (22F82)
 - JDK信息： OpenJDK 64-Bit Server VM (Zulu 8.56.0.23-CA-macos-aarch64) (build 25.302-b08, mixed mode)
 - 版本信息：2.0.39
 

### 重现步骤
*如何操作可以重现该问题：*
用两种方法反序列化为一个嵌套的类时，toJavaList的子类类型是LinkedHashMap，而非定义的类型。
    public static void main(String[] args) throws Exception {
        String str = "{\"accounts\":[{\"aliyunid\":\"aliyuntest\",\"apis\":[{\"coordinate\":\"Ecs:2021-05-03:CreateInstance*\",\"description\":\"用于XXX\",\"parameters\":[{\"key\":\"InstanceName\",\"value\":\"StringLike(\\\"%teststring%\\\")\"}]},{\"coordinate\":\"Ecs:*:RunInstances\",\"description\":\"用于XXXXX\",\"parameters\":[{\"key\":\"InstanceName\",\"value\":\"StringLike(\\\"%teststring%\\\")\"},{\"key\":\"InternetMaxBandwidthIn\",\"value\":0}]}]}]}";
        JSONArray json = JSONObject.parseObject(str).getJSONArray("accounts");
        List<PermissionsBoundaryBaseline> r1 = json.toJavaList(PermissionsBoundaryBaseline.class);
        List<PermissionsBoundaryBaseline> r2 = JSONObject.parseArray(json.toJSONString(), PermissionsBoundaryBaseline.class);
    }

![image](https://github.com/alibaba/fastjson2/assets/3434467/048b7bb2-c57d-4da4-8417-13ed1e941594)
![image](https://github.com/alibaba/fastjson2/assets/3434467/82fcc268-e598-43de-9675-0b962c979af2)

### 期待的正确结果
期待两种方式反序列化结果相同。

### 相关日志输出
参考上述截图。

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本
