### ISSUE TITLE
反序列化问题咨询

### ISSUE THREAD

**Issue by SuperIllidan** [alibaba/fastjson2#1821]
案例：对于字符串 [1,,3]进行反序列化为list, fastjson1 和 fastjson2 代码一样，分别反序列化为integer和Long
       List<Integer> set = JSON.parseObject("[1,,3]", new TypeReference<List<Integer>>() {});//fastjson1 和 2，结果均为 [1,3] 
       List<Long> set = JSON.parseObject("[1,,3]", new TypeReference<List<Long>>() {});//fastjson1 结果 [1,3]，fastjson2结果[]1,0,3]
对于上面两种结果，其实都不是很满意，理论上上面的字符串不是一个合理的List<Integer or Long> ，比如jackson会对此报错；、
即便不报错，fastjson2在将其解析为Long泛型时，把空的那个位置解析为了0，感觉不是很合理，fastjson1自始至终都是将其忽略反而更合理。

**Comment by yanxutao89** [comment]
版本是最新吗？

**Comment by SuperIllidan** [comment]
嗯，专门用了2.0.39试验的

**Comment by yanxutao89** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/ 用这个试试

**Comment by SuperIllidan** [comment]
似乎并没有什么变化呢，依然把两个逗号中间的空值解析为了0，用的这个最新的fastjson2-2.0.40-20230831.161219-42.jar，这个案例很简单啊，您自己也可以随时地试一下

**Comment by SuperIllidan** [comment]
![图片](https://github.com/alibaba/fastjson2/assets/22414705/643feb72-f7eb-44ea-a33f-23a353740a83)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.40
问题已修复，请用新版本
