### ISSUE TITLE
[BUG] JSONB 序列化集合时，如果集合里有空的元素，会序列化失败

### ISSUE THREAD

**Issue by liaozan** [alibaba/fastjson2#1826]
### 问题描述

JSONB 序列化集合时，如果集合里有空的元素，会序列化失败

### 环境信息

 - 版本信息：[e.g.：Fastjson2 2.0.39]
 

### 重现步骤
<img width="765" alt="image" src="https://github.com/alibaba/fastjson2/assets/26990889/1f8a4029-e994-4dbd-9f43-0be986a24c01">

![image](https://github.com/alibaba/fastjson2/assets/26990889/4e68e26c-f238-4fb2-ae51-9d39a11f41e0)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.40-SNAPSHOT/
问题已修复，请用2.0.40-SNAPSHOT帮忙验证

**Comment by liaozan** [comment]
Fixed

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
请用新版本
