### ISSUE TITLE
[FEATURE] 为JSONWriter.Feature 添加 WriteDateAsTimestamps配置

### ISSUE THREAD

**Issue by shpodg** [alibaba/fastjson2#1833]
### 请描述您的需求或者改进建议
为JSONWriter.Feature 添加 WriteDateAsTimestamps配置

使用的版本：2.0.39

当前只能通过如下的方式配置时间输出为时间戳
```java
final JSONWriter.Context writeContext = JSONFactory.createWriteContext();
writeContext.setDateFormat("millis");
JSON.toJSONString(body, writeContext)
```
但是部分接口不支持传入context， 例如`JSON.toJSON(body)`就不支持配置context，而且会将日期转换为字符串，也就无法配置Date类型的输出格式。

### 描述您考虑过的替代方案
fastjson1 支持配置SerializerFeature.WriteDateAsTimestamps

**Comment by HongJian-Yang** [comment]
所以说现在把Date LocalDateTime转换成时间戳, 还是要写这么一长串吗
