### ISSUE TITLE
禁用BigDecimal的代码应该怎么写呢

### ISSUE THREAD

**Issue by yangyongdehao30** [alibaba/fastjson2#184]
JSONReader.getContext().config() 
和直接JSON.parseObject()添加Feature都不行，用的2.0.2的版本

**Comment by yangyongdehao30** [comment]
求大佬回复，这次升级对项目很重要

**Comment by wenshao** [comment]
```java
String str = "{\"val\":1.2}";
JSONObject object = JSON.parseObject(str, JSONReader.Feature.UseBigDecimalForDoubles);
Object val = object.get("val");
assertEquals(Double.class, val.getClass());
```
这个是不是你想要的？

**Comment by yangyongdehao30** [comment]
JSONObject object = JSON.parseObject(str, JSONReader.Feature.UseBigDecimalForDoubles,JSONReader.Feature.UseBigDecimalForFloats);   发现全部转换成了float

**Comment by yangyongdehao30** [comment]
不好意思，这边应该是直接通过值范围判断的，不是fastjson2的问题
