### ISSUE TITLE
[BUG] com.alibaba.fastjson2.support.csv.CSVReader 解析 CSV 数据有 Bug

### ISSUE THREAD

**Issue by ldcsaa** [alibaba/fastjson2#1849]
### 问题描述
有两行数据，都是13个字段，但 CSVReader 对第二行数据只解析出 12 个字段。
```
"Indosat","JAN6B41111111111","1111111111","1","成功","","","3","3","6","1365000","11","15015000"
"Indosat","JAZ6A72222222222","2222222222","1","失败","3","IOT_SHell_Login: err: connect rt:-215","","","","","",""
```

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Win10]
 - JDK信息： [e.g.：JDK17]
 - 版本信息：[e.g.：Fastjson-2.0.37]
 

### 重现步骤
```java
CSVReader<?> reader = CSVReader.of(
	new File(natHoleFile),
	Charset.forName(CsvFileWriter.DEF_CHARSET),
	String.class,
	String.class,
	String.class,
	int.class,
	String.class,
	Integer.class,
	String.class,
	Integer.class,
	Integer.class,
	Integer.class,
	Integer.class,
	Integer.class,
	Integer.class
	);

for(; ; )
{
	Object[] values = reader.readLineValues();
	
	if(values == null || values.length == 0)
		break;
	
	String source = (String)values[0];
	String longEseeId = (String)values[1];
	String eseeId = (String)values[2];
	int sequence = (Integer)values[3];
	boolean success = "成功".equals(values[4]);
	Integer errStep = (Integer)values[5];
	String errMsg = (String)values[6];
	Integer connServerTime = (Integer)values[7];
	Integer connPeerTime = (Integer)values[8];
	Integer totalHoleTime = (Integer)values[9];
	Integer transRate = (Integer)values[10];
	Integer transTime = (Integer)values[11];
	// 解析第2行时，这里抛出数组越界异常
	Integer recvBytes = (Integer)values[12];
}
```

### 期待的正确结果
正确解析第2行

#### 附加信息
![image](https://github.com/alibaba/fastjson2/assets/5990337/a53459b9-2dea-41a4-a79b-7c2c77a15cc6)

**Comment by ldcsaa** [comment]
还有一个问题：读取表头也会进行类型转换，导致类型转换异常

```
CSVReader<?> reader = CSVReader.of(
	new File(natHoleFile),
	Charset.forName(CsvFileWriter.DEF_CHARSET),
	String.class,
	String.class,
	String.class,
	int.class,
	String.class,
	Integer.class,
	String.class,
	Integer.class,
	Integer.class,
	Integer.class,
	Integer.class,
	Integer.class,
	Integer.class
	);

// 如果有表头，readHeader() 会抛出异常：java.lang.NumberFormatException
List<String> headers = reader.readHeader();
System.out.println(headers);
```

![image](https://github.com/alibaba/fastjson2/assets/5990337/ad4285c4-c6e7-4692-9711-b2728fcb55e7)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.41-SNAPSHOT/
问题已修复，请用2.0.41-SNAPSHOT帮忙验证

**Comment by hpsocket** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.41-SNAPSHOT/ 问题已修复，请用2.0.41-SNAPSHOT帮忙验证

好的

**Comment by hpsocket** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.41-SNAPSHOT/ 问题已修复，请用2.0.41-SNAPSHOT帮忙验证

第一个问题解决了，但第二个问题还没解决。
https://github.com/alibaba/fastjson2/issues/1849#issuecomment-1712577161
读取表头也会进行类型转换，导致类型转换异常

**Comment by wenshao** [comment]
第二个问题没重现，是否可以帮忙提供下重现问题的testcase

**Comment by hpsocket** [comment]
> 第二个问题没重现，是否可以帮忙提供下重现问题的testcase

[test-maven.zip](https://github.com/alibaba/fastjson2/files/12644153/test-maven.zip)

CSV文件内容：
```
"姓名","年龄","薪酬"
"怪兽","23","12345"
"大美丽","34","54321"
```

源码及输出：
![image](https://github.com/alibaba/fastjson2/assets/142854599/7a52f005-5bc2-4c26-b873-afbf51323aa1)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本
