### ISSUE TITLE
[BUG] 当类中有get方法且无对应属性，序列化时会误将该方法调用

### ISSUE THREAD

**Issue by m479345807** [alibaba/fastjson2#1852]
### 问题描述
*简要描述您碰到的问题。*
当类中有get方法且无对应属性，序列化时会误将该方法调用

### 环境信息
*请填写以下信息：*

 - OS信息：  windows 11
 - JDK信息： oracle jdk 1.8.0_66
 - 版本信息：Fastjson2 2.0.40
 

### 重现步骤
*如何操作可以重现该问题：*

1. 创建类MetaDataDto 
2. 新建属性type，并编写get方法
3. 编写一个不相干的方法getValue
4. 创建MetaDataDto 调用JSON.toJSONString
```java
import com.alibaba.fastjson.JSON;

public class MetaDataDto {

    private String type;

    public Object getValue(){
        return "word";
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public static void main(String[] args) {
        MetaDataDto dto = new MetaDataDto();
        dto.setType("string");
        System.out.println(JSON.toJSONString(dto));
    }
}

```

### 期待的正确结果
期望结果是 {"type":"string"}

### 相关日志输出

![image](https://github.com/alibaba/fastjson2/assets/42465822/6daa7691-84fa-4a31-806e-40d132bfddbf)

**Comment by wenshao** [comment]
JSONWriter.Feature.IgnoreNonFieldGetter
这个是不是你想要的？

**Comment by m479345807** [comment]
> JSONWriter.Feature.IgnoreNonFieldGetter 这个是不是你想要的？

是的，多谢
