### ISSUE TITLE
[BUG]开启 JDK9 Module功能，当使用FastJsonConfig进行配置时提示报名冲突

### ISSUE THREAD

**Issue by EthanKk** [alibaba/fastjson2#1856]
### 问题描述
*简要描述您碰到的问题。*
开启 JDK9 Module功能，当使用FastJsonConfig进行参数配置，
module 要求 import fastjson2.extension 和 import com.alibaba.fastjson2，
而 FastJsonConfig 所在包的包名 com.alibaba.fastjson2.support.config 在这两个 module 中都有，提示：
Package com.alibaba.fastjson2.support in both module fastjson2.extension and module com.alibaba.fastjson2
### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：jdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.40]

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本
