### ISSUE TITLE
[BUG] com.alibaba.fastjson2.JSONException: TODO : n

### ISSUE THREAD

**Issue by s-nataraju** [alibaba/fastjson2#1861]
### 问题描述
*简要描述您碰到的问题。*

Unable to parse the json using JSON.parseObject(json, MyData.class); if one of the field is of type OffsetDateTime and it's value is null

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312] 17.0.7+0
 - 版本信息：[e.g.：Fastjson2 2.x.x] 2.0.38
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
Test class to reprodoce 
```

 @Test
    public void test1() {

        String json = "{\"myData1\":{\"myData2\":{\"key\":{\"startTime\":null}}}}";
        MyData data = JSON.parseObject(json, MyData.class);
        logger.error("data " + data.toString());
    }
```
Model used to identify the issue.

```
public class MyData {

    private MyData1 myData1;
    public MyData1 getMyData1() {
        return myData1;
    }

    public void setMyData1(MyData1 myData1) {
        this.myData1 = myData1;
    }
}
```

``` 
public class MyData1 {
    @JsonProperty("myData2")
    private @Valid Map<String, MyData2> myData2 = null;

    public Map<String, MyData2> getMyData2() {
        return myData2;
    }

    public void setMyData2(Map<String, MyData2> myData2) {
        this.myData2 = myData2;
    }

}
```
```
public class MyData2 {
    @JsonProperty("startTime")
    private OffsetDateTime startTime;

    public OffsetDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
    }
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

TODO : n
com.alibaba.fastjson2.JSONException: TODO : n
	at app//com.alibaba.fastjson2.JSONReader.readZonedDateTime(JSONReader.java:1448)
	at app//com.alibaba.fastjson2.JSONReaderUTF8.readOffsetDateTime(JSONReaderUTF8.java:7116)
	at com.alibaba.fastjson2.reader.ORG_3_1_MyData2.readObject(Unknown Source)
	at app//com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:373)
	at com.alibaba.fastjson2.reader.ORG_2_1_MyData1.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_1_1_MyData.readObject(Unknown Source)
	at app//com.alibaba.fastjson2.JSON.parseObject(JSON.java:726)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本
