### ISSUE TITLE
[BUG] parseObject("null")报错

### ISSUE THREAD

**Issue by guoyachao1** [alibaba/fastjson2#1867]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.40]
 

### 重现步骤
*如何操作可以重现该问题：*
```
      System.out.println(com.alibaba.fastjson.JSON.parseObject("null", Map.class));
      System.out.println(com.alibaba.fastjson2.JSON.parseObject("null", Map.class));
```
```java
//可在此输入示例代码
```

### 期待的正确结果
 结果一样

### 相关日志输出

Exception in thread "main" com.alibaba.fastjson2.JSONException: illegal input， offset 1, char n

![image](https://github.com/alibaba/fastjson2/assets/8247899/519566e5-045d-4662-afef-e674d3b7bdf3)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本
