### ISSUE TITLE
[BUG] JSONArray to toJavaList 布尔 和 0/1 无法序列化

### ISSUE THREAD

**Issue by QYG2297248353** [alibaba/fastjson2#1874]
### 问题描述
*简要描述您碰到的问题。*
序列化使用：
`Feature.WriteBooleanAsNumber`
将 布尔转为数字，当反序列化时并没有处理布尔
`
com.alibaba.fastjson2.JSONException: can not cast to java.lang.Boolean, from class java.lang.Integer
	at com.alibaba.fastjson2.util.TypeUtils.cast(TypeUtils.java:244)
	at com.alibaba.fastjson2.reader.ObjectReader.createInstance(ObjectReader.java:111)
	at com.alibaba.fastjson2.JSONArray.toList(JSONArray.java:1032)
	at com.alibaba.fastjson2.JSONArray.toJavaList(JSONArray.java:1119)
`
在TypeUtils类方法cast，完全没有处理布尔
`
public static <T> T cast(Object obj, Class<T> targetClass) {
}
`

### 环境信息
*请填写以下信息：*

 - OS信息：  win10
 - JDK信息： Openjdk 1.8.0_312
 - 版本信息：Fastjson2 2.0.15

**Comment by yanxutao89** [comment]
试试 2.0.40

**Comment by QYG2297248353** [comment]
> 试试 2.0.40

OK 问题已解决
![image](https://github.com/alibaba/fastjson2/assets/56836951/2d01c503-e225-4426-ac2d-3cb62640aec8)
![image](https://github.com/alibaba/fastjson2/assets/56836951/80724c71-ab90-45b0-b32d-d046ae37d10f)

**Comment by yanxutao89** [comment]
测试用例可以提供下吗？

**Comment by QYG2297248353** [comment]
> 测试用例可以提供下吗？
上方回答有
https://github.com/alibaba/fastjson2/issues/1874#issuecomment-1730721963
