### ISSUE TITLE
JSONPath.remove 与fastjson1.x行为不一致

### ISSUE THREAD

**Issue by wenkang-du** [alibaba/fastjson2#1889]
fastjson1.x:移除了key和value
fastjson2.0.40:仅移除了value

**Comment by wenkang-du** [comment]
另:使用兼容包 JSON.parseObject后内部的JSONobject为fastjson2.x的对象

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by wenkang-du** [comment]
String text = "{\n" +
                "  \"a\": {\n" +
                "    \"b\": 0,\n" +
                "    \"c\": 2\n" +
                "  }\n" +
                "}";
        JSONObject jsonObject = JSON.parseObject(text);
        JSONPath.remove(jsonObject, "$..b");
        System.out.println(JSON.toJSONString(jsonObject, JSONWriter.Feature.WriteNulls));
这个是fastjson2  结果:{"a":{"b":null,"c":2}}

**Comment by wenkang-du** [comment]
String text = "{\n" +
                "  \"a\": {\n" +
                "    \"b\": 0,\n" +
                "    \"c\": 2\n" +
                "  }\n" +
                "}";
        JSONObject jsonObject = JSON.parseObject(text);
        JSONPath.remove(jsonObject, "$..b");
        System.out.println(JSON.toJSONString(jsonObject, SerializerFeature.WriteMapNullValue));
这是fastjson1 结果:{"a":{"c":2}}

**Comment by wenkang-du** [comment]
JSONObject jsonObject = new JSONObject();
        JSONPath.set(jsonObject,"$a.d", new JSONObject().fluentPut("cc",1));
        System.out.println(jsonObject.get("a").getClass().getName());
        System.out.println(jsonObject.getJSONObject("a").get("d").getClass().getName());
输出
![image](https://github.com/alibaba/fastjson2/assets/49199144/dabf4020-1ac0-43ac-81a5-643f1c07f5e4)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.41
问题已修复，请用新版本

**Comment by wenkang-du** [comment]
> ```
>     JSONObject jsonObject = new JSONObject();
>     JSONPath.set(jsonObject,"$a.d", new JSONObject().fluentPut("cc",1));
>     System.out.println(jsonObject.get("a").getClass().getName());
>     System.out.println(jsonObject.getJSONObject("a").get("d").getClass().getName());
> ```
> 
> ![image](https://user-images.githubusercontent.com/49199144/270846883-bb7e4dff-949e-44f4-af09-ebd7eaf17e7a.png)
> 
> 是使用JSONPath.set后发现的,不是parseObject,前面描述有误

这个问题还未修复吧

**Comment by wenshao** [comment]
是两个事情了，你能再建一个issue么？

**Comment by wenkang-du** [comment]
> 是两个事情了，你能再建一个issue么？

行,我再建一个issue
