### ISSUE TITLE
使用兼容包的JSONPath.set构建json对象,内部同时存在com.alibaba.fastjson2.JSONObject和com.alibaba.fastjson.JSONObject对象

### ISSUE THREAD

**Issue by Vinke2** [alibaba/fastjson2#1922]
JSONObject jsonObject = new JSONObject();
        JSONPath.set(jsonObject,"$a.d", new JSONObject().fluentPut("cc",1));
        System.out.println(jsonObject.get("a").getClass().getName());
        System.out.println(jsonObject.getJSONObject("a").get("d").getClass().getName());
![image](https://github.com/alibaba/fastjson2/assets/49199144/bb7e4dff-949e-44f4-af09-ebd7eaf17e7a)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.42-SNAPSHOT/
问题已修复，请帮忙用2.0.42-SNAPSHOT版本验证，正式版本预计在下个周末（11月5日）发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.42
问题已修复，请用新版本

**Comment by Vinke2** [comment]
你好,我在最新2.0.49版本的兼容包上面又遇到了这个问题:
        List<JSONObject> array = (List<JSONObject>) JSONPath.read("{\n" +
                "  \"data\": [\n" +
                "    {\n" +
                "      \"id\": 7315635187420579130\n" +
                "    },\n" +
                "    {\n" +
                "      \"id\": 7315635187420579130\n" +
                "    }\n" +
                "  ]\n" +
                "}", "data");
        for (JSONObject jsonObject : array) {
            System.out.println(jsonObject.get("id"));
![image](https://github.com/alibaba/fastjson2/assets/49199144/c37321c8-6518-40da-8c1e-39d4bfa4ce69)
        }
