### ISSUE TITLE
[BUG]开启 JDK9 Module功能，fastjson2 和 fastjson2-extension 包的 module name 同名

### ISSUE THREAD

**Issue by EthanKk** [alibaba/fastjson2#1923]
### 问题描述
开启 JDK9 Module功能，fastjson2 和 fastjson2-extension 包的 module name 同名

### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：Oracle jdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.41]
 

### 重现步骤
在代码中使用  com.alibaba.fastjson2.support.config.FastJsonConfig 类，需要在 module-info.java 中 requires com.alibaba.fastjson2。
FastJsonConfig 类在 fastjson2-extension.jar 中，此 jar 的 module-info.java 中配置的 module name 为 com.alibaba.fastjson2。

但是 fastjson2.jar 中 module-info.java 配置的 module name 同样为 com.alibaba.fastjson2，两个 jar 的 module name 同名。

当两个 jar 同时被引用时，根据 module name 冲突

此 bug 为 #1856 修复后的新 bug

**Comment by yanxutao89** [comment]
麻烦提供下可以复现的测试示例吧

**Comment by EthanKk** [comment]
![image](https://github.com/alibaba/fastjson2/assets/6426859/f5eec34a-f9ff-4aa7-88a3-6bafd5e5b29c)
不同 jar 包使用了相同的 module name

**Comment by wenshao** [comment]
2.0.42版本这个问题还存在么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/
请帮2.0.45-SNAPSHOT验证问题是否已经修复

**Comment by EthanKk** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/ 请帮2.0.45-SNAPSHOT验证问题是否已经修复

是 fastjson2-extension 包中的 module name 不对，而不是 fastjson2 包。
看了fastjson2-extension的源码，并没有显式指定 module-info.java，但 jar 包中有 module-info.class，里面的 module name 仍然是是错的：
![image](https://github.com/alibaba/fastjson2/assets/6426859/5ebad1b6-3418-4ba0-8b88-6ef9408db47d)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2-extension/2.0.45-SNAPSHOT/

2.0.45-SNAPSHOT我看到已经改好了

**Comment by EthanKk** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2-extension/2.0.45-SNAPSHOT/
> 
> 2.0.45-SNAPSHOT我看到已经改好了

恩，最新的快照里已经 ok 了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.45
问题已修复，请用新版本
