### ISSUE TITLE
@JsonIgnore 这个注解是jackson的，Fastjson2好像识别了它。导致很多地方不能区分了，例如我使用security登录

### ISSUE THREAD

**Issue by xiangyunup** [alibaba/fastjson2#1937]
@JsonIgnore 这个注解是jackson的，Fastjson2好像识别了它。导致很多地方不能区分了，例如我使用security登录。密码并不想返回给前端，只是作为内部使用，都会加上这个注解，升级后不得移除这个注解。

**Comment by wenshao** [comment]
你可以通过JVM启动参数配置禁用jackson的annotation:
```
-Dfastjson2.useJacksonAnnotation=false
```

你也可以放一个fastjson2.properties文件，做如下配置：
```
fastjson2.useJacksonAnnotation=false
```
