### ISSUE TITLE
自定义 bean的序列化

### ISSUE THREAD

**Issue by wjzxc123** [alibaba/fastjson2#1943]
开发者你好：
在 java bean自定义序列化中，分别实现ObjectWriter 和 ObjectReader 并且使用 JSON.register()方法注册这两个类，如果我只是就使用一次这种自定义序列化方式，其他时候还是默认的序列化，那么我要怎么操作？还是注册自定义后这个bean只能按照这种方式序列化了

**Comment by kaizen84** [comment]
有点特别这个需求，可以详细描述下使用逻辑
尝试使用 注解 JSONField或者使用 Filter实现

**Comment by wjzxc123** [comment]
> 有点特别这个需求，可以详细描述下使用逻辑 尝试使用 注解 JSONField或者使用 Filter实现，或者直接不使用序列化工具

谢谢，我通过filter解决了这个问题，感谢
