### ISSUE TITLE
fastjson与springboot整合时API成批分配利用问题

### ISSUE THREAD

**Issue by lizhixin-git-hub** [alibaba/fastjson2#1944]
您好！

fastjson与springboot整合，当反序列化时存在多余字段，例如：

    //配置
    @Bean
    public HttpMessageConverters fastJsonHttpMessageConverters() {
        FastJsonHttpMessageConverter converter = new FastJsonHttpMessageConverter();
        FastJsonConfig config = new FastJsonConfig();
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
        config.setWriterFeatures(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat);
        converter.setFastJsonConfig(config);
        converter.setDefaultCharset(StandardCharsets.UTF_8);
        List<MediaType> supportedMediaTypes = new ArrayList<>();
        supportedMediaTypes.add(MediaType.APPLICATION_JSON);
        supportedMediaTypes.add(MediaType.APPLICATION_JSON_UTF8);
        converter.setSupportedMediaTypes(supportedMediaTypes);
        return new HttpMessageConverters(converter);
    }

    //接口
    @RequestMapping("/api")
    public TestBean api(@RequestBody TestBean testBean) {
        return testBean;
    }

   //实体
   public class TestBean {
  
      private String name;
  
      private Integer age;
  
      public String getName() {
          return name;
      }
  
      public void setName(String name) {
          this.name = name;
      }
  
      public Integer getAge() {
          return age;
      }
  
      public void setAge(Integer age) {
          this.age = age;
      }
  
  }

  //参数
  {
    "name": "张三",
    "age": 10,
    "username": "xxx"
  }

  当参数中存在比实体多余出来的字段，在jackson中如果json对象中有不存在的属性时候，有是否报错->fail_on_unknown_properties=true这个配置项，在fastjson中未找到相关配置，是否也存在这样的配置参数？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.42-SNAPSHOT/
这个版本已经引入了JSONReader.Feature.ErrorOnUnknownProperties)
```java
        JSONObject jsonObject = JSONObject.of("id", 123, "name", "xxx");
        String str = jsonObject.toJSONString();
        assertEquals(
                jsonObject.getIntValue("id"),
                JSON.parseObject(str, Bean.class).id);
        assertThrows(
                JSONException.class,
                () -> JSON.parseObject(str, Bean.class, JSONReader.Feature.ErrorOnUnknownProperties)
        );

        assertEquals(
                jsonObject.getIntValue("id"),
                jsonObject.toJavaObject(Bean.class).id
        );
        assertThrows(
                JSONException.class,
                () -> jsonObject.toJavaObject(Bean.class, JSONReader.Feature.ErrorOnUnknownProperties)
        );
```

请帮忙验证是否符合你的需求

**Comment by lizhixin-git-hub** [comment]
好的，谢谢，我升级下版本，测试一下！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.42
问题已修复，请用新版本
