### ISSUE TITLE
[FEATURE]BeanToArray 存放一个字段名表头,这样在反序列化的时候如果对象字段修改了,不影响反序列化

### ISSUE THREAD

**Issue by wangjing112** [alibaba/fastjson2#1952]
### 请描述您的需求或者改进建议
对于一个对象采用BeanToArray序列化后,大大优化了输出json的大小.但是存在一个问题是在对象字段修改后,无法正确的反序列化了.

### 请描述你建议的实现方案
如果在序列化的时候放一个表头的字段如:
class A{
public int id;
public int val1;
}
如果生成的json是这样:{@params{"id","val1"},[[1,2][1,2]]}
这样在反序列化时,结构修改成了
class A{
public int id;
public int key;
public int val1;
}
仍然能正确反序列化数据到正确的字段上.

否则BeanToArray的应用场景会被大大折扣,因为谁都不敢保证数据字段以后不会有修改.

**Comment by wenshao** [comment]
```java
 @Test
    public void test() {
        Bean bean = new Bean();
        bean.v0 = 0;
        bean.v1 = 1;
        bean.v2 = 2;
        bean.v3 = 3;
        assertEquals("[2,1,3,0]", JSON.toJSONString(bean, JSONWriter.Feature.BeanToArray));
    }

    @JSONType(orders = {"v2", "v1", "v3", "v0"})
    public static class Bean {
        public int v0;
        public int v1;
        public int v2;
        public int v3;
    }
```
这个现在就支持，可以通过@JSONType(orders={})来实现，如上
