### ISSUE TITLE
json字符串中含注释时，解析异常[BUG]

### ISSUE THREAD

**Issue by fufenghua** [alibaba/fastjson2#1954]
### 问题描述
*简要描述您碰到的问题。*
```json
{ /*
   * Created by jiemu
   * @Author: admin
   * @Date: 2023-10-26 17:10:23
   * @Desc 
  */
    "name": "EUXFD0OP9PHYUBWI9M08",
    "version": 1000,
    "parser_version": 1,
    "scene": {
        "signals": {
 //TODO
},
        "fusions":{
 //TODO
},
        "actuator": {
            "actions":[ ]        }
    }
}
```
以上字符串，使用JSONObject.parseObject 在fastjson【1.2.83】可以正常解析，在fastjson2 【2.0.41】不可以，在fastjson【2.0.41】也不可以

错误信息：not allow unquoted fieldName, offset 9, character *, line 2, column 6

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
String a = "{ /*\n" +
                "   * Created by jiemu\n" +
                "   * @Author: admin\n" +
                "   * @Date: 2023-10-26 17:10:23\n" +
                "   * @Desc \n" +
                "  */\n" +
                "    \"name\": \"EUXFD0OP9PHYUBWI9M08\",\n" +
                "    \"version\": 1000,\n" +
                "    \"parser_version\": 1,\n" +
                "    \"scene\": {\n" +
                "        \"signals\": {\n" +
                " //TODO\n" +
                "},\n" +
                "        \"fusions\":{\n" +
                " //TODO\n" +
                "},\n" +
                "        \"actuator\": {\n" +
                "            \"actions\":[ ]        }\n" +
                "    }\n" +
                "}";
        JSONObject j = JSONObject.parseObject(a);
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
{"parser_version":1,"name":"EUXFD0OP9PHYUBWI9M08","version":1000,"scene":{"actuator":{"actions":[]},"signals":{},"fusions":{}}}

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.42-SNAPSHOT/
问题已修复，请帮忙用2.0.42-SNAPSHOT版本验证，正式版本预计在下个周末（11月5日）发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.42
问题已修复，请用新版本
