### ISSUE TITLE
[BUG]fastjson解析字符串到jsonobject如果前面的对象出现不区分大小写的key，后面的对象解析到jsonobject属性变了

### ISSUE THREAD

**Issue by dongxp** [alibaba/fastjson2#1955]
问题：
这类不规范的json,{
    "contractInfo":
    [
        {
            "SelectList": null,
            "Description": "项目名称"
        }
    ],
    "BidNode":
    [
        {
            "selectList": null,
            "description": "土建工程"
        }
    ]
}
现象：调用JSON.parseIbject后BidNode里的selectList和description都变成了之前出现的大写
![image](https://github.com/alibaba/fastjson2/assets/18159554/5dbf73dd-80df-4227-8ea1-605d489a9205)

**Comment by yanxutao89** [comment]
试试最新版吧，我这里没问题
![Uploading image.png…]()

**Comment by dongxp** [comment]
2.36版本是有问题的，2.37一样的问题

**Comment by dongxp** [comment]
看了新最新的版本2.0.41没问题了，我以为2.0.37最新了
