### ISSUE TITLE
请问这个 fastjson2 是在fastjson的代码基础上进行改造  还是重新写的？

### ISSUE THREAD

**Issue by li-xiao-shuang** [alibaba/fastjson2#2]

**Comment by wenshao** [comment]
是重新写了，从2021年10月1日开始到现在，大约花了半年时间多时间。当然参考了原来的代码和重用了很多testcase。

**Comment by li-xiao-shuang** [comment]
> 是重新写了，从2021年10月1日开始到现在，大约花了半年时间多时间。当然参考了原来的代码和重用了很多testcase。
> 
> 目标是为下一个十年提供一个高性能的JSON库，所以做得比较仔细，花了很多时间。
> 
> 欢迎参与进来。

好的
