### ISSUE TITLE
JSONObject.parseObject()转换包含java内部类时，出现系统崩溃

### ISSUE THREAD

**Issue by wujs-king** [alibaba/fastjson2#2012]
### 问题描述
*简要描述您碰到的问题。*
当java实体类中有内部类时，用JSONObject.parseObject()方法进行转换时，系统时不时就会崩溃，（注：在1fastjson1.x版本中没出现过，升级2.x版本后则频繁出现，在此期间除升级fastjson，其他没任何修改）

### 环境信息
*请填写以下信息：*

 - OS信息：CentOS 7.7.1908 4Core 2.30GHz 16GB
 - JDK信息： jdk_1.8.0_291
 - 版本信息： fastjson2.0.40
 

### 重现步骤
*如何操作可以重现该问题：*
出现该问题为偶发，但非常频繁。

```java
//可在此输入示例代码
@Data
public class BlooddonationqueryVO {
    /**
     * cardType : 
     * name : 
     * beginTime :
     * endTime :
     * cardNo : 
     * results :
     */
    private String cardType;
    private String name;
    @ApiModelProperty(value = "开始时间")
    private String beginTime;
    @ApiModelProperty(value = "结束时间")
    private String endTime;
    private String cardNo;
    @ApiModelProperty(value = "返回集合")
    private ResultsEntity results;
    @ApiModelProperty(value = "返回信息")
    private String msg;
    @ApiModelProperty(value = "返回状态")
    private String code;




    @Data
    public class ResultsEntity {
        private List<DataListEntiy> result;

    }

    @Data
    public static class DataListEntiy {


        private String donateAddress;
        private String bloodCapacity;
        private String donateTime;


    }



}
```

### 期待的正确结果
使用JSONObject.parseObject()转换包含java内部类时，不再出现系统崩溃。

### 相关日志输出
Current thread (0x00007fdfc45b8800):  JavaThread "http-nio-18029-exec-1" daemon [_thread_in_vm, id=224285, stack(0x00007fdf9c01e000,0x00007fdf9c09f000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000010

Registers:
RAX=0x00000000c3b0ba28, RBX=0x00007fdfc45b8800, RCX=0x0000000000000000, RDX=0x00007fdfc9c1fed0
RSP=0x00007fdf9c09bd60, RBP=0x00007fdf9c09bd90, RSI=0x00007fdf9c09bda0, RDI=0x00007fdfc401aa90
R8 =0x00007fdf9c09bdb8, R9 =0x00007fdf544615c0, R10=0x00007fdfb5161de0, R11=0x00007fdfb5161d98
R12=0x0000000000000010, R13=0x00007fdfc9c4f340, R14=0x00007fdf9c09bdb8, R15=0x00000000c3b0ba28
RIP=0x00007fdfc972564b, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000006
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fdf9c09bd60)
0x00007fdf9c09bd60:   00007fdf3bcb2dd8 00007fdf9f47db98
0x00007fdf9c09bd70:   0000000000000000 00007fdf9c09be00
0x00007fdf9c09bd80:   00007fdf9c09bf90 00007fdfc45b8800
0x00007fdf9c09bd90:   00007fdf9c09bde0 00007fdfb5161e56
0x00007fdf9c09bda0:   000000008094fe30 0000000000000000
0x00007fdf9c09bdb0:   0000000000000000 00000000c3b0ba28
0x00007fdf9c09bdc0:   0000000000000000 0000000000000000
0x00007fdf9c09bdd0:   0000000000000000 0000000000000000
0x00007fdf9c09bde0:   00007fdf9c09be80 00007fdfb4debffd
0x00007fdf9c09bdf0:   0000000000000000 00007fdfb4debffd
0x00007fdf9c09be00:   00000000c3b0ba28 0000000000000010
0x00007fdf9c09be10:   0000000083833270 0000000000000000
0x00007fdf9c09be20:   000000008094fe30 0000000000000000
0x00007fdf9c09be30:   00000000c3b0ba28 00000000c3b0b9b0
0x00007fdf9c09be40:   00007fdf9c09be40 00007fdf3bcaf9a5
0x00007fdf9c09be50:   00007fdf9c09bf90 00007fdf3bcb0910
0x00007fdf9c09be60:   0000000000000000 00007fdf3bcafbd8
0x00007fdf9c09be70:   00007fdf9c09be00 00007fdf9c09bfa0
0x00007fdf9c09be80:   00007fdf9c09c0e8 00007fdfb66ab4a4
0x00007fdf9c09be90:   0000000000000000 0000000000000000
0x00007fdf9c09bea0:   0000000000000000 0000000000000000
0x00007fdf9c09beb0:   0000000000000000 0000000000000000
0x00007fdf9c09bec0:   0000000000000000 0000000000000000
0x00007fdf9c09bed0:   0000000000000000 0000000000000000
0x00007fdf9c09bee0:   0000000000000000 0000000000000000
0x00007fdf9c09bef0:   0000000000000000 0000000000000000
0x00007fdf9c09bf00:   0000000000000000 0000000000000000
0x00007fdf9c09bf10:   0000000000000000 0000000000000000
0x00007fdf9c09bf20:   0000000000000000 0000000000000000
0x00007fdf9c09bf30:   0000000000000000 0000000000000000
0x00007fdf9c09bf40:   0000000000000000 0000000000000000
0x00007fdf9c09bf50:   0000000000000000 0000000000000005 

Instructions: (pc=0x00007fdfc972564b)
0x00007fdfc972562b:   0f 85 d7 00 00 00 31 c0 4d 85 ff 74 13 48 8d 15
0x00007fdfc972563b:   91 a8 4f 00 4c 89 f8 48 2b 02 8b 4a 08 48 d3 e8
0x00007fdfc972564b:   41 89 04 24 49 8b 7d 00 83 7f 0c 01 0f 85 e2 fe
0x00007fdfc972565b:   ff ff 48 8b 87 90 00 00 00 49 c1 ec 09 42 c6 04 

Register to memory mapping:

RAX=0x00000000c3b0ba28 is an oop
blooddonationquery.BlooddonationqueryVO 
 - klass: '/blooddonationquery/BlooddonationqueryVO'
RBX=0x00007fdfc45b8800 is a thread
RCX=0x0000000000000000 is an unknown value
RDX=0x00007fdfc9c1fed0: <offset 0xfa6ed0> in /software/java/jre/lib/amd64/server/libjvm.so at 0x00007fdfc8c79000
RSP=0x00007fdf9c09bd60 is pointing into the stack for thread: 0x00007fdfc45b8800
RBP=0x00007fdf9c09bd90 is pointing into the stack for thread: 0x00007fdfc45b8800
RSI=0x00007fdf9c09bda0 is pointing into the stack for thread: 0x00007fdfc45b8800
RDI=0x00007fdfc401aa90 is an unknown value
R8 =0x00007fdf9c09bdb8 is pointing into the stack for thread: 0x00007fdfc45b8800
R9 =0x00007fdf544615c0 is an unknown value
R10=0x00007fdfb5161de0 is at entry_point+96 in (nmethod*)0x00007fdfb5161c10
R11=0x00007fdfb5161d98 is at entry_point+24 in (nmethod*)0x00007fdfb5161c10
R12=0x0000000000000010 is an unknown value
R13=0x00007fdfc9c4f340: <offset 0xfd6340> in /software/java/jre/lib/amd64/server/libjvm.so at 0x00007fdfc8c79000
R14=0x00007fdf9c09bdb8 is pointing into the stack for thread: 0x00007fdfc45b8800
R15=0x00000000c3b0ba28 is an oop
blooddonationquery.BlooddonationqueryVO 
 - klass: 'blooddonationquery/BlooddonationqueryVO'

Stack: [0x00007fdf9c01e000,0x00007fdf9c09f000],  sp=0x00007fdf9c09bd60,  free space=503k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xaac64b]  Unsafe_SetObject+0x1cb
J 1021  sun.misc.Unsafe.putObject(Ljava/lang/Object;JLjava/lang/Object;)V (0 bytes) @ 0x00007fdfb5161e56 [0x00007fdfb5161d80+0xd6]
j  com.alibaba.fastjson2.reader.ORG_14_8_BlooddonationqueryVO.readObject(Lcom/alibaba/fastjson2/JSONReader;Ljava/lang/reflect/Type;Ljava/lang/Object;J)Ljava/lang/Object;+757
J 15727 C1 com.alibaba.fastjson2.JSON.parseObject(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; (174 bytes) @ 0x00007fdfb66ab4a4 [0x00007fdfb66aae80+0x624]
J 16391 C1 com.alibaba.fastjson2.JSONObject.parseObject(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; (6 bytes) @ 0x00007fdfb6627a5c [0x00007fdfb6627a00+0x5c]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68b16a]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xe1a
V  [libjvm.so+0x9a1b98]  Reflection::invoke(instanceKlassHandle, methodHandle, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*)+0xae8
V  [libjvm.so+0x9a3566]  Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)+0x126
V  [libjvm.so+0x702545]  JVM_InvokeMethod+0x115
J 2452  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (0 bytes) @ 0x00007fdfb56207ad [0x00007fdfb56206c0+0xed]
J 10866 C2 sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (104 bytes) @ 0x00007fdfb66b36b0 [0x00007fdfb66b3640+0x70]
J 3672 C2 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (62 bytes) @ 0x00007fdfb5366e9c [0x00007fdfb5366e00+0x9c]
J 16175 C1 org.springframework.web.method.support.InvocableHandlerMethod.doInvoke([Ljava/lang/Object;)Ljava/lang/Object; (128 bytes) @ 0x00007fdfb55e800c [0x00007fdfb55e7d20+0x2ec]

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by yanxutao89** [comment]
具体的代码调用样例麻烦提供一下

**Comment by wujs-king** [comment]
@Data
public class BlooddonationqueryVO {
    /**
     * cardType : 
     * name : 
     * beginTime :
     * endTime :
     * cardNo : 
     * results :
     */
    private String cardType;
    private String name;
    @ApiModelProperty(value = "开始时间")
    private String beginTime;
    @ApiModelProperty(value = "结束时间")
    private String endTime;
    private String cardNo;
    @ApiModelProperty(value = "返回集合")
    private ResultsEntity results;
    @ApiModelProperty(value = "返回信息")
    private String msg;
    @ApiModelProperty(value = "返回状态")
    private String code;




    @Data
    public class ResultsEntity {
        private List<DataListEntiy> result;

    }

    @Data
    public static class DataListEntiy {


        private String donateAddress;
        private String bloodCapacity;
        private String donateTime;


    }



}
 public static void main(String[] args) {
        BlooddonationqueryVO blooddonationqueryVO = new BlooddonationqueryVO();
         String rep="{\"prnd\":1699865962262,\"code\":0,\"msg\":\"success\",\"data\":\"<?xml version='1.0' encoding='utf-8'?><businessDataResponse><cardType>身份证</cardType><cardNo>123</cardNo><name>xxx</name><beginTime>2022-11-13</beginTime><endTime>2023-11-13</endTime><results></results></businessDataResponse>\"}";
        String josnob = JSONObject.parseObject(rep).getString("data");
        if(josnob==null){
            blooddonationqueryVO.setCode(JSONObject.parseObject(rep).getString("code"));
            blooddonationqueryVO.setMsg(JSONObject.parseObject(rep).getString("msg"));
        }else{
            String buss = XML.toJSONObject(josnob).getJSONObject("businessDataResponse").toString();
            blooddonationqueryVO = JSONObject.parseObject(buss, BlooddonationqueryVO.class);
            blooddonationqueryVO.setCode(JSONObject.parseObject(rep).getString("code"));
            blooddonationqueryVO.setMsg(JSONObject.parseObject(rep).getString("msg"));
        }
        System.out.println(blooddonationqueryVO);
    }

**Comment by wujs-king** [comment]
@Data
public class BlooddonationqueryVO {
    /**
     * cardType : 
     * name : 
     * beginTime :
     * endTime :
     * cardNo : 
     * results :
     */
    private String cardType;
    private String name;
    @ApiModelProperty(value = "开始时间")
    private String beginTime;
    @ApiModelProperty(value = "结束时间")
    private String endTime;
    private String cardNo;
    @ApiModelProperty(value = "返回集合")
    private ResultsEntity results;
    @ApiModelProperty(value = "返回信息")
    private String msg;
    @ApiModelProperty(value = "返回状态")
    private String code;




    @Data
    public class ResultsEntity {
        private List<DataListEntiy> result;

    }

    @Data
    public static class DataListEntiy {


        private String donateAddress;
        private String bloodCapacity;
        private String donateTime;


    }



}
 public static void main(String[] args) {
        BlooddonationqueryVO blooddonationqueryVO = new BlooddonationqueryVO();
   //      String rep="{\"prnd\":1699865962262,\"code\":0,\"msg\":\"success\",\"data\":\"<?xml version='1.0' encoding='utf-8'?><businessDataResponse><cardType>身份证</cardType><cardNo>123</cardNo><name>xxx</name><beginTime>2022-11-13</beginTime><endTime>2023-11-13</endTime><results></results></businessDataResponse>\"}";
        String josnob = JSONObject.parseObject(rep).getString("data");
        if(josnob==null){
            blooddonationqueryVO.setCode(JSONObject.parseObject(rep).getString("code"));
            blooddonationqueryVO.setMsg(JSONObject.parseObject(rep).getString("msg"));
        }else{
            String buss = XML.toJSONObject(josnob).getJSONObject("businessDataResponse").toString();
            blooddonationqueryVO = JSONObject.parseObject(buss, BlooddonationqueryVO.class);
            blooddonationqueryVO.setCode(JSONObject.parseObject(rep).getString("code"));
            blooddonationqueryVO.setMsg(JSONObject.parseObject(rep).getString("msg"));
        }
        System.out.println(blooddonationqueryVO);
    }

**Comment by wujs-king** [comment]
吴金生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 中午1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012)





 
具体的代码调用样例麻烦提供一下

**Comment by wujs-king** [comment]
发到github上的代码会变，请以，此附件为准


吴金生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 中午1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012)





 
具体的代码调用样例麻烦提供一下

**Comment by yanxutao89** [comment]
> 发到github上的代码会变，请以，此附件为准 吴金生 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/fastjson2" ***@***.***&gt;; 发送时间:&nbsp;2023年11月14日(星期二) 中午1:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012) 具体的代码调用样例麻烦提供一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

未找到附件

**Comment by wujs-king** [comment]
@Data public class BlooddonationqueryVO {     /**      * cardType :       * name :       * beginTime :      * endTime :      * cardNo :       * results :      */     private String cardType;     private String name;     @ApiModelProperty(value = "开始时间")     private String beginTime;     @ApiModelProperty(value = "结束时间")     private String endTime;     private String cardNo;     @ApiModelProperty(value = "返回集合")     private ResultsEntity results;     @ApiModelProperty(value = "返回信息")     private String msg;     @ApiModelProperty(value = "返回状态")     private String code;     @Data     public class ResultsEntity {         private List<DataListEntiy&gt; result;     }     @Data     public static class DataListEntiy {         private String donateAddress;         private String bloodCapacity;         private String donateTime;     } }  public static void main(String[] args) {         BlooddonationqueryVO blooddonationqueryVO = new BlooddonationqueryVO();    //      String rep="{\"prnd\":1699865962262,\"code\":0,\"msg\":\"success\",\"data\":\"<?xml version='1.0' encoding='utf-8'?&gt;<businessDataResponse&gt;<cardType&gt;身份证</cardType&gt;<cardNo&gt;123</cardNo&gt;<name&gt;xxx</name&gt;<beginTime&gt;2022-11-13</beginTime&gt;<endTime&gt;2023-11-13</endTime&gt;<results&gt;</results&gt;</businessDataResponse&gt;\"}";         String josnob = JSONObject.parseObject(rep).getString("data");         if(josnob==null){             blooddonationqueryVO.setCode(JSONObject.parseObject(rep).getString("code"));             blooddonationqueryVO.setMsg(JSONObject.parseObject(rep).getString("msg"));         }else{             String buss = XML.toJSONObject(josnob).getJSONObject("businessDataResponse").toString();             blooddonationqueryVO = JSONObject.parseObject(buss, BlooddonationqueryVO.class);             blooddonationqueryVO.setCode(JSONObject.parseObject(rep).getString("code"));             blooddonationqueryVO.setMsg(JSONObject.parseObject(rep).getString("msg"));         }         System.out.println(blooddonationqueryVO);     }





吴金生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012)





  
发到github上的代码会变，请以，此附件为准 吴金生 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/fastjson2" @.&gt;; 发送时间:&nbsp;2023年11月14日(星期二) 中午1:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012) 具体的代码调用样例麻烦提供一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
未找到附件

**Comment by yanxutao89** [comment]
最新版本可以正常解析
![Uploading image.png…]()

**Comment by wujs-king** [comment]
我使用2.0.42版本还是不行，请问目前的最新版是？






吴金生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012)





 
最新版本可以正常解析

**Comment by yanxutao89** [comment]
> 我使用2.0.42版本还是不行，请问目前的最新版是？ 吴金生 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/fastjson2" ***@***.***&gt;; 发送时间:&nbsp;2023年11月14日(星期二) 下午2:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012) 最新版本可以正常解析 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

抱歉，复现了，正在修复

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43-SNAPSHOT/
问题已修复，请帮忙用2.0.43-SNAPSHOT版本验证，2.0.43正式版本预计在12月3日前发布

**Comment by wujs-king** [comment]
好的





吴金生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月20日(星期一) 上午8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson2] JSONObject.parseObject()转换包含java内部类时，出现系统崩溃 (Issue #2012)





 
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43-SNAPSHOT/
 问题已修复，请帮忙用2.0.43-SNAPSHOT版本验证，2.0.43正式版本预计在12月3日前发布
