### ISSUE TITLE
[BUG] - Potential non-deterministic failures in `fastjson1-compatible` module

### ISSUE THREAD

**Issue by krishnanand5** [alibaba/fastjson2#2017]
### 问题描述
I am a masters student from University of Illinois-Urbana Champaign and as part of my research project, I test open-source repositories to detect and address flaky tests. For carrying out this process, I use a tool called [NonDex](https://github.com/TestingResearchIllinois/NonDex).

I have been assigned the fastjson2 repository for my research project. Earlier, students from the same university have addressed some flaky tests in fastjson1.

I have begun testing the various modules under fastjson2 for detecting potential flaky tests. I am sharing the initial round of results based on the `fastjson1-compatible`.

Please let me know if I can proceed with developing fixes for the detected flaky tests.

### 环境信息
*请填写以下信息：*

 - OS信息：  [MacOS Sonoma 8GB]
 - JDK信息： [JAVA 11.0.21-amzn]
 - 版本信息：[2.0.42]
 

### 重现步骤
*如何操作可以重现该问题：*

1. Run `mvn -pl fastjson1-compatible edu.illinois:nondex-maven-plugin:2.1.1:nondex -DnondexMode=ONE` to identify potential flaky tests in the fastjson1-compatible module.
2. This execution will run all tests in `fastjson1-compatible` module by shuflling the order of non-deterministic elements.
3. The section **Across all seeds**  in the logs displays the list of flaky tests detected in the execution.

### 期待的正确结果
Most of the flaky tests detected in the fastjson1-compatible module seem to be arising from the non-deterministic nature in which certain JAVA data storage types tend to store data. If we can change the data storage types to ones which keep the order definite and don't shuffle elements when its accessed, we can make those tests more resilient to non-deterministic failures.

### 相关日志输出
The list of tests identified by NonDex as potential flaky tests are as follows:

```
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] com.alibaba.fastjson.issue_2400.Issue2447#test_for_issue2
[INFO] com.alibaba.fastjson.issue_2400.Issue2447#test_for_issue
[INFO] com.alibaba.fastjson.issue_2100.Issue2182#test_for_issue
[INFO] com.alibaba.fastjson.issue_2400.Issue2428#test_for_issue
[INFO] com.alibaba.fastjson.issue_1900.Issue1972#test_for_issue
[INFO] com.alibaba.fastjson.issue_1300.Issue1363#test_for_issue
[INFO] com.alibaba.fastjson.issue_1300.Issue1363#test_for_issue_1
[INFO] com.alibaba.fastjson.issue_1100.Issue1177_1#test_for_issue
[INFO] com.alibaba.fastjson.issue_1100.Issue1177_2#test_for_issue
[INFO] com.alibaba.fastjson.geo.FeatureCollectionTest#test_geo
[INFO] com.alibaba.fastjson.jsonp.JSONPParseTest1#test_f
[INFO] com.alibaba.fastjson.jsonp.JSONPParseTest#test_f
```

#### 附加信息
Based on how the developers want to take this forward, I can run nondex for other fastjson2 modules and create separate issues to track flaky tests reported in different modules individually.

Your inputs on whether I can proceed with creating PRs for the identified issues will be of great help towards strengthening my research project.

**Comment by wenshao** [comment]
Welcome to participate in the test of fastjson2. I will try my best to respond to your PR in a timely manner. Generally, it will be processed within 2 to 3 days, not more than 1 week.
