### ISSUE TITLE
[QUESTION]QueryWrapper反序列化失败，因构造函数默认级别

### ISSUE THREAD

**Issue by cyfrank124** [alibaba/fastjson2#2025]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
```java
        QueryWrapper qw = new QueryWrapper<>();
        qw.select("*");
        qw.eq("sys_id", 1712740060383170562L);
        qw.ne("ceshi", 1);
        qw.in("wode", 3, 4);
        qw.orderByAsc("time");
        qw.groupBy("group");
        qw.having("SUM({0}) AS nums", "group");

        String json = JSON.toJSONString(qw
                , JSONWriter.Feature.FieldBased // 基于 field，而非 getter 方法
                , JSONWriter.Feature.ReferenceDetection);
        //qw.set("full_name", "test111");
        System.out.println(json);
        //new TypeReference<QueryWrapper>() {}.getType()
        QueryWrapper query = JSON.parseObject(json,
                QueryWrapper.class
                , JSONReader.Feature.FieldBased);
```
![企业微信截图_20231117105414](https://github.com/alibaba/fastjson2/assets/40955465/5d0e709b-5612-4b07-b0e5-fa70a440d67b)
错误信息如下
```shell
java.lang.IllegalAccessError: tried to access method com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList.<init>()V from class com.alibaba.fastjson2.reader.ORG_2_6_MergeSegments
```

**Comment by zacat** [comment]
[Mybatis](https://github.com/shenluw/mybatis-plus-serialization)
你可以看一下这个。

**Comment by cyfrank124** [comment]
> [Mybatis](https://github.com/shenluw/mybatis-plus-serialization) 你可以看一下这个。
其他的我都有试过，你这个类似于自定义对象转换（我也写过不是他们想要的0.0），实际dubbo采用 nativeJava的序列化方式，对象也是可以传递的，如果不引入也可以选择文件保存传递，原理类似

**Comment by kaizen84** [comment]
![image](https://github.com/alibaba/fastjson2/assets/49264728/8087be47-6e06-4c9c-aa43-b327a23b06e0)
wrapper 最好不要进行序列化饭序列话操作

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43-SNAPSHOT/
问题已修复，请帮忙用2.0.43-SNAPSHOT版本验证，2.0.43正式版本预计在12月3日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43
请用新版本

**Comment by cyfrank124** [comment]
> ![image](https://private-user-images.githubusercontent.com/49264728/285566607-8087be47-6e06-4c9c-aa43-b327a23b06e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTMwNzgsIm5iZiI6MTcwMTY1Mjc3OCwicGF0aCI6Ii80OTI2NDcyOC8yODU1NjY2MDctODA4N2JlNDctNmUwNi00YzljLWFhNDMtYjMyN2EyM2IwNmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAxMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMWM5MGNmYmRkZDQ5MDRmODUzOTZmZmMzZTVmOWY2ZWZhZjNkNTQ0YjcyOGNkYmJlYWJmZDQ0ZGVkYjUwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XlbgBG3VwWh9ds9f6nBW8qXqq7prHOYwYLajw176rQk) wrapper 最好不要进行序列/反序列化操作，有些太重了

道理说了，总有人不听 0.0

**Comment by cyfrank124** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.43-SNAPSHOT/ 问题已修复，请帮忙用2.0.43-SNAPSHOT版本验证，2.0.43正式版本预计在12月3日前发布

测试了下，对于后续使用目前是没问题，发现另外一个 toJSONString 不加Feature的方式，序列化前后的不一致，初步估计应该是泛型的问题
![企业微信截图_20231204101526](https://github.com/alibaba/fastjson2/assets/40955465/659fe278-885e-451e-9bfc-8b318ed18c94)
