### ISSUE TITLE
Feature.OrderedField 的替换方案

### ISSUE THREAD

**Issue by 18670032796** [alibaba/fastjson2#203]
fastjson 1.2.7 版本：JSON.parseObject(result, User.class, Feature.OrderedField);
fastjson2 2.0.1版本： Feature.OrderedField 找不到这个属性，请教一下大佬，替换方案是什么。

**Comment by wenshao** [comment]
缺省就是，所以OrderedField就不用了

**Comment by 18670032796** [comment]
已验证，没有问题。
