### ISSUE TITLE
[QUESTION]fastjson2--2.0.42自定义反序列化报错

### ISSUE THREAD

**Issue by demonxinghen** [alibaba/fastjson2#2035]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

依赖版本fastjson2-extension-spring5--2.0.42

前端post参数
![image](https://github.com/alibaba/fastjson2/assets/23410956/ce65238d-0fe6-42ec-9c78-5ba519437404)

fastjson2配置
![image](https://github.com/alibaba/fastjson2/assets/23410956/052fab5b-748c-4d2b-ad88-31fe3fca560c)

vo对象
``
![image](https://github.com/alibaba/fastjson2/assets/23410956/67f5752f-444f-4247-9983-400e1c3460cf)

自定义反序列化类
![image](https://github.com/alibaba/fastjson2/assets/23410956/8485facb-5fe7-4863-b63a-a2024cc40752)

只解析username和password没问题，date加上deserializeUsing = TimeSerializer.class就报错。
Exception in thread "main" com.alibaba.fastjson2.JSONException: expect ':', but }, offset 51, character ", line 1, column 52, fastjson-version 2.0.42 {"username": "admin","password": "123456","date": "abc"}
	at com.alibaba.fastjson2.JSONReaderUTF8.readFieldNameHashCode(JSONReaderUTF8.java:2972)

麻烦大佬们帮忙看下这个问题，感激不尽。

**Comment by yanxutao89** [comment]
自定义反序列化类中最好调用下jsonReader.readString()

**Comment by demonxinghen** [comment]
> 自定义反序列化类中最好调用下jsonReader.readString()

太谢谢你了，加了这行代码，真的就好了 @yanxutao89

**Comment by demonxinghen** [comment]
@yanxutao89 请问下哥，反序列化类里有办法获取当前field吗？ 我需要搭配字段上的其他注解
