### ISSUE TITLE
[BUG]JSONObject.parseObject("null")报错

### ISSUE THREAD

**Issue by kelvinlou** [alibaba/fastjson2#2040]
### 问题描述
*简要描述您碰到的问题。*
JSONObject.parseObject("null")报错（com.alibaba.fastjson.JSONException: offset 1, character n, line 1, column 2, fastjson-version 2.0.42 null）

### 环境信息
*请填写以下信息：*

 - OS信息： macOs bigSure 8Core 3.10GHz 16 GB
 - JDK信息： jdk1.8.0_202
 - 版本信息：Fastjson2 2.0.42
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用JSONObject actionAttrsJson = JSONObject.parseObject("null");
2. 出现报错信息如下：
Caused by: com.alibaba.fastjson2.JSONException: offset 1, character n, line 1, column 2, fastjson-version 2.0.42 null
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:2066)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
```java
//可在此输入示例代码
```
 JSONObject actionAttrsJson = JSONObject.parseObject("null");
### 期待的正确结果
*期望跟fastjson 1.2.83输一样的结果为null

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
![Uploading image.png…]()

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.43-SNAPSHOT/
问题已修复，请帮忙用2.0.43-SNAPSHOT版本验证，2.0.43正式版本预计在12月3日前发布

**Comment by kelvinlou** [comment]
感谢修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43
请用新版本
