### ISSUE TITLE
[QUESTION]v1兼容包的性能提升不明显

### ISSUE THREAD

**Issue by wrck** [alibaba/fastjson2#205]
### 请描述您的问题
测试了v1兼容包和v1序列化和反序列化同个对象，发现性能提升并不是很明显，如果想要有明显的性能提升，是否需要直接改用fastjson2

**Comment by wenshao** [comment]
需要提供更多的信息，比如提供测试的代码，看下是测试代码的问题，还是测试场景的问题

**Comment by wrck** [comment]
测试项目的问题，不够纯净
