### ISSUE TITLE
自定义注解指定了自定义序列化器，如何在序列化时获取这个注解 [QUESTION]

### ISSUE THREAD

**Issue by kaizen84** [alibaba/fastjson2#2053]
fastjson2：2.0.42
1. 自定义了一个注解（作用于字段）
2. 注解使用@JSONField(serializeUsing = XXX.class)指定了序列化器
3. 我该如何在实现的这个方法里取到这个注解？wcom.alibaba.fastjson2.writer.ObjectWriter#write(com.alibaba.fastjson2.JSONWriter, java.lang.Object, java.lang.Object, java.lang.reflect.Type, long)
4. filter 可以实现，但是 filter太重了，只要注册过它 所有的序列化都会执行

**Comment by kaizen84** [comment]
因为我没有找到能获取这个被注解字段filed的地方

**Comment by kaizen84** [comment]
第二个参数是这个字段的值，第三个参数是这个字段的名称，我找不到这个字段的所属的跟对象的类信息

**Comment by kaizen84** [comment]
实例化这个writer的时候 使用的是一个空参构造方法
![image](https://github.com/alibaba/fastjson2/assets/49264728/57aff420-2fdd-493d-b1ab-05a3a0a03bd0)

**Comment by kaizen84** [comment]
😭急急急，没想到有什么好办法

**Comment by kaizen84** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by Doghole** [comment]
根对象信息在 jsonWriter 里面，但是是个 protected 对象，你需要用反射来获取
```java
package com.doghole.mess.test;

import java.lang.reflect.Field;
import java.lang.reflect.Type;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.writer.ObjectWriter;

public class FastJson2Issue2053 {

    static class Weight {
        @JSONField(serializeUsing = SelfDefinedValueSerializer.class)
        private String weight = null;
        
        public Weight() {}
        
        public void setWeight(String weight) {
            this.weight = weight;
        }
        
        public String getWeight() {
            return weight;
        }
    }
    
    static class Height {
        @JSONField(serializeUsing = SelfDefinedValueSerializer.class)
        private String height = null;
        
        public Height() {}
        
        public void setHeight(String height) {
            this.height = height;
        }
        
        public String getHeight() {
            return height;
        }
    }
    
    static class SelfDefinedValueSerializer implements ObjectWriter<String> {

        @Override
        public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
            try {
                if (object != null) {
                    Field field = JSONWriter.class.getDeclaredField("rootObject");
                    if (field.trySetAccessible()) {
                        Class<?> rootObjectClazz = field.get(jsonWriter).getClass();
                        if (rootObjectClazz == Height.class) {
                            jsonWriter.writeString(((String)object) + "cm");
                        }
                        else if (rootObjectClazz == Weight.class) {
                            jsonWriter.writeString(((String)object) + "kg");
                        }
                    }
                }
            } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
                e.printStackTrace();
            }
        }
    }
    
    @Test
    void test() {
        Weight weight = new Weight();
        weight.setWeight("100");
        
        Assertions.assertEquals("{\"weight\":\"100kg\"}", JSON.toJSONString(weight));
        
        Height height = new Height();
        height.setHeight("100");
        Assertions.assertEquals("{\"height\":\"100cm\"}", JSON.toJSONString(height));
    }
    
}


```

**Comment by kaizen84** [comment]
> 根对象信息在 jsonWriter 里面，但是是个 protected 对象，你需要用反射来获取
> 
> ```java
> package com.doghole.mess.test;
> 
> import java.lang.reflect.Field;
> import java.lang.reflect.Type;
> 
> import org.junit.jupiter.api.Assertions;
> import org.junit.jupiter.api.Test;
> 
> import com.alibaba.fastjson2.JSON;
> import com.alibaba.fastjson2.JSONWriter;
> import com.alibaba.fastjson2.annotation.JSONField;
> import com.alibaba.fastjson2.writer.ObjectWriter;
> 
> public class FastJson2Issue2053 {
> 
>     static class Weight {
>         @JSONField(serializeUsing = SelfDefinedValueSerializer.class)
>         private String weight = null;
>         
>         public Weight() {}
>         
>         public void setWeight(String weight) {
>             this.weight = weight;
>         }
>         
>         public String getWeight() {
>             return weight;
>         }
>     }
>     
>     static class Height {
>         @JSONField(serializeUsing = SelfDefinedValueSerializer.class)
>         private String height = null;
>         
>         public Height() {}
>         
>         public void setHeight(String height) {
>             this.height = height;
>         }
>         
>         public String getHeight() {
>             return height;
>         }
>     }
>     
>     static class SelfDefinedValueSerializer implements ObjectWriter<String> {
> 
>         @Override
>         public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
>             try {
>                 if (object != null) {
>                     Field field = JSONWriter.class.getDeclaredField("rootObject");
>                     if (field.trySetAccessible()) {
>                         Class<?> rootObjectClazz = field.get(jsonWriter).getClass();
>                         if (rootObjectClazz == Height.class) {
>                             jsonWriter.writeString(((String)object) + "cm");
>                         }
>                         else if (rootObjectClazz == Weight.class) {
>                             jsonWriter.writeString(((String)object) + "kg");
>                         }
>                     }
>                 }
>             } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
>                 e.printStackTrace();
>             }
>         }
>     }
>     
>     @Test
>     void test() {
>         Weight weight = new Weight();
>         weight.setWeight("100");
>         
>         Assertions.assertEquals("{\"weight\":\"100kg\"}", JSON.toJSONString(weight));
>         
>         Height height = new Height();
>         height.setHeight("100");
>         Assertions.assertEquals("{\"height\":\"100cm\"}", JSON.toJSONString(height));
>     }
>     
> }
> ```

😂这个我也看到了，这个是最顶级对象，得深层遍历也不一定能取到，不能完全靠字段名匹配

**Comment by Doghole** [comment]
没懂你的意思，rootObject 不就是字段所属对象吗？也没有多深层的遍历。
例子只是提示你如何在 write 方法内获取到对象，如果你还要在对象中获取添加了该注解的字段，继续对该对象调用反射方法即可。

**Comment by kaizen84** [comment]
> 没懂你的意思，rootObject 不就是字段所属对象吗？也没有多深层的遍历。 例子只是提示你如何在 write 方法内获取到对象，如果你还要在对象中获取添加了该注解的字段，继续对该对象调用反射方法即可。

我意思是 如果有很深的对象嵌套的化，可能会有问题。比如 多个非同类型对象 都用了这个字段名 字段值也完全一样，那他可能就会取错数据

**Comment by Doghole** [comment]
不太清楚你的具体场景，不过我试图列举了以下几种情况：

1. 如果注解在同类的多个字段上，字段名自然不可能一致，此时不会混淆；
2. 如果注解在同类的单个字段上，当且仅当该类该字段序列化时才进入 write 方法，此时不会混淆；
3. 如果注解在多个类的同名字段上，而这多个类是嵌套关系（如 user -> gender 和 user -> bird -> gender），则序列化 User 时由于 rootObject 仅可能为 User 导致无法判断 gender 是属于 User 的 还是 Bird 的。

如果是 3，好像没有什么特别的方法，如果字段值是基本类型，不包含额外信息，不用 Filter 的话，还是只能从 rootObject 入手，毕竟这是唯一一个可以在 write 内部获得当前序列化对象的地方。

受限于 rootObject 仅在序列化根对象时配置，如果你需要在嵌套对象序列化时将当前嵌套对象设为根对象，你可以考虑如下的办法：为嵌套对象定义一个 ObjectWriter：
```java
    /**
     * 为嵌套对象定义一个 NestedWriter，使用该 Writer 就可以获得具体的 rootObject
     */
    static class NestedWriter implements ObjectWriter<Object> {
        @Override
        public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
            jsonWriter.writeAny(JSON.parse(JSON.toJSONString(object, jsonWriter.context)));
            // 你也可以用 jsonWriter.setRootObject 方法
        }
    }
```
再在 XXX.class write 方法中用上面提到的反射获取 rootObject 来判断该类即可，但考虑到嵌套可能不仅仅是但对象，还可能是 Iterable，Array 和 Map 等，实际情况要复杂得多，我不确定这是最佳做法，使用上可能并不比 Filter 方便多少。我也想不到其他更好的方法了。下面是例子：
```java
package com.doghole.mess.test;

import java.lang.reflect.Field;
import java.lang.reflect.Type;
import org.junit.jupiter.api.Test;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.writer.ObjectWriter;

import lombok.Data;

public class FastJson2Issue2053 {

    static final String FEMALE = "female";
    static final String MALE = "male";

    @Data
    static class User {
        @JSONField(serializeUsing = CommonGenderWriter.class)
        private String gender;
        
        @JSONField(serializeUsing = NestedWriter.class)
        private Chicken chicken;

        @JSONField(serializeUsing = NestedWriter.class)
        private User mate;

        @JSONField(serializeUsing = NestedWriter.class)
        private Alien alienFriend;
        
    }

    @Data
    static class Chicken {
        
        @JSONField(serializeUsing = CommonGenderWriter.class)
        private String gender;
        
    }

    @Data
    static class Alien {

        @JSONField(serializeUsing = CommonGenderWriter.class)
        private String gender;
    }
    
    /**
     * 为嵌套对象定义一个 NestedWriter，使用该 Writer 就可以获得具体的 rootObject
     */
    static class NestedWriter implements ObjectWriter<Object> {
        @Override
        public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
            jsonWriter.writeAny(JSON.parse(JSON.toJSONString(object, jsonWriter.context)));
            // 你也可以用 jsonWriter.setRootObject 方法
        }
    }
    
    static class CommonGenderWriter implements ObjectWriter<Object> {
        
        private static String toSelfDefinedGender(Class<?> clazz, String gender) {
            
            if (gender == null) return "unknown";
            
            if (clazz == Chicken.class) {
                if (gender.equals(MALE)) {
                    return "cock";
                }
                else if (gender.equals(FEMALE)) {
                    return "hen";
                }
            }
            else if (clazz == User.class) {
                if (gender.equals(MALE)) {
                    return "man";
                }
                else if (gender.equals(FEMALE)) {
                    return "woman";
                }
            }
            else {
                return gender;
            }
            return "unknown";
        }

        @Override
        public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
            try {
                Field field = JSONWriter.class.getDeclaredField("rootObject");
                if (field.trySetAccessible()) {
                    Object rootObject = field.get(jsonWriter);
                    Class<?> rootObjectClazz = rootObject.getClass();
                    String gender = (String)object;
                    
                    // TODO: Iterable & Array & Map，考虑的情况太多还不如分开定义 ObjectWriter
                    jsonWriter.writeString(toSelfDefinedGender(rootObjectClazz, gender));
                }
            } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
                e.printStackTrace();
            }
        }
    }
    
    @Test
    void test() {
        
        Chicken chicken = new Chicken();
        chicken.setGender(MALE);
        
        User user = new User();
        user.setGender(FEMALE);
        user.setChicken(chicken);
        

        Chicken matesChicken = new Chicken();
        matesChicken.setGender(FEMALE);

        User mate = new User();
        mate.setGender(MALE);
        mate.setChicken(matesChicken);
        
        user.setMate(mate);
        
        Alien alien = new Alien();
        alien.setGender("wal-mart bag");
        user.setAlienFriend(alien);
        
        System.out.println(JSON.toJSONString(user));
    }
    
}
```
输出：
```json
{"alienFriend":{"gender":"wal-mart bag"},"chicken":{"gender":"cock"},"gender":"woman","mate":{"chicken":{"gender":"hen"},"gender":"man"}}
```

**Comment by kaizen84** [comment]
> 不太清楚你的具体场景，不过我试图列举了以下几种情况：
> 
> 1. 如果注解在同类的多个字段上，字段名自然不可能一致，此时不会混淆；
> 2. 如果注解在同类的单个字段上，当且仅当该类该字段序列化时才进入 write 方法，此时不会混淆；
> 3. 如果注解在多个类的同名字段上，而这多个类是嵌套关系（如 user -> gender 和 user -> bird -> gender），则序列化 User 时由于 rootObject 仅可能为 User 导致无法判断 gender 是属于 User 的 还是 Bird 的。
> 
> 如果是 3，好像没有什么特别的方法，如果字段值是基本类型，不包含额外信息，不用 Filter 的话，还是只能从 rootObject 入手，毕竟这是唯一一个可以在 write 内部获得当前序列化对象的地方。
> 
> 受限于 rootObject 仅在序列化根对象时配置，如果你需要在嵌套对象序列化时将当前嵌套对象设为根对象，你可以考虑如下的办法：为嵌套对象定义一个 ObjectWriter：
> 
> ```java
>     /**
>      * 为嵌套对象定义一个 NestedWriter，使用该 Writer 就可以获得具体的 rootObject
>      */
>     static class NestedWriter implements ObjectWriter<Object> {
>         @Override
>         public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
>             jsonWriter.writeAny(JSON.parse(JSON.toJSONString(object, jsonWriter.context)));
>             // 你也可以用 jsonWriter.setRootObject 方法
>         }
>     }
> ```
> 
> 再在 XXX.class write 方法中用上面提到的反射获取 rootObject 来判断该类即可，但考虑到嵌套可能不仅仅是但对象，还可能是 Iterable，Array 和 Map 等，实际情况要复杂得多，我不确定这是最佳做法，使用上可能并不比 Filter 方便多少。我也想不到其他更好的方法了。下面是例子：
> 
> ```java
> package com.doghole.mess.test;
> 
> import java.lang.reflect.Field;
> import java.lang.reflect.Type;
> import org.junit.jupiter.api.Test;
> 
> import com.alibaba.fastjson2.JSON;
> import com.alibaba.fastjson2.JSONWriter;
> import com.alibaba.fastjson2.annotation.JSONField;
> import com.alibaba.fastjson2.writer.ObjectWriter;
> 
> import lombok.Data;
> 
> public class FastJson2Issue2053 {
> 
>     static final String FEMALE = "female";
>     static final String MALE = "male";
> 
>     @Data
>     static class User {
>         @JSONField(serializeUsing = CommonGenderWriter.class)
>         private String gender;
>         
>         @JSONField(serializeUsing = NestedWriter.class)
>         private Chicken chicken;
> 
>         @JSONField(serializeUsing = NestedWriter.class)
>         private User mate;
> 
>         @JSONField(serializeUsing = NestedWriter.class)
>         private Alien alienFriend;
>         
>     }
> 
>     @Data
>     static class Chicken {
>         
>         @JSONField(serializeUsing = CommonGenderWriter.class)
>         private String gender;
>         
>     }
> 
>     @Data
>     static class Alien {
> 
>         @JSONField(serializeUsing = CommonGenderWriter.class)
>         private String gender;
>     }
>     
>     /**
>      * 为嵌套对象定义一个 NestedWriter，使用该 Writer 就可以获得具体的 rootObject
>      */
>     static class NestedWriter implements ObjectWriter<Object> {
>         @Override
>         public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
>             jsonWriter.writeAny(JSON.parse(JSON.toJSONString(object, jsonWriter.context)));
>             // 你也可以用 jsonWriter.setRootObject 方法
>         }
>     }
>     
>     static class CommonGenderWriter implements ObjectWriter<Object> {
>         
>         private static String toSelfDefinedGender(Class<?> clazz, String gender) {
>             
>             if (gender == null) return "unknown";
>             
>             if (clazz == Chicken.class) {
>                 if (gender.equals(MALE)) {
>                     return "cock";
>                 }
>                 else if (gender.equals(FEMALE)) {
>                     return "hen";
>                 }
>             }
>             else if (clazz == User.class) {
>                 if (gender.equals(MALE)) {
>                     return "man";
>                 }
>                 else if (gender.equals(FEMALE)) {
>                     return "woman";
>                 }
>             }
>             else {
>                 return gender;
>             }
>             return "unknown";
>         }
> 
>         @Override
>         public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
>             try {
>                 Field field = JSONWriter.class.getDeclaredField("rootObject");
>                 if (field.trySetAccessible()) {
>                     Object rootObject = field.get(jsonWriter);
>                     Class<?> rootObjectClazz = rootObject.getClass();
>                     String gender = (String)object;
>                     
>                     // TODO: Iterable & Array & Map，考虑的情况太多还不如分开定义 ObjectWriter
>                     jsonWriter.writeString(toSelfDefinedGender(rootObjectClazz, gender));
>                 }
>             } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
>                 e.printStackTrace();
>             }
>         }
>     }
>     
>     @Test
>     void test() {
>         
>         Chicken chicken = new Chicken();
>         chicken.setGender(MALE);
>         
>         User user = new User();
>         user.setGender(FEMALE);
>         user.setChicken(chicken);
>         
> 
>         Chicken matesChicken = new Chicken();
>         matesChicken.setGender(FEMALE);
> 
>         User mate = new User();
>         mate.setGender(MALE);
>         mate.setChicken(matesChicken);
>         
>         user.setMate(mate);
>         
>         Alien alien = new Alien();
>         alien.setGender("wal-mart bag");
>         user.setAlienFriend(alien);
>         
>         System.out.println(JSON.toJSONString(user));
>     }
>     
> }
> ```
> 
> 输出：
> 
> ```json
> {"alienFriend":{"gender":"wal-mart bag"},"chicken":{"gender":"cock"},"gender":"woman","mate":{"chicken":{"gender":"hen"},"gender":"man"}}
> ```

好的 明白🫡，感谢
