### ISSUE TITLE
[BUG]jsonpath_multi提取和直接使用JSONPath提取结果不一致

### ISSUE THREAD

**Issue by ChaYedan666** [alibaba/fastjson2#2058]
### 问题描述
*简要描述您碰到的问题。*
使用wiki:https://github.com/alibaba/fastjson2/wiki/jsonpath_multi_cn 中批量求值时，返回的结果不合预期。

### 环境信息
*请填写以下信息：*

 - OS信息：  macos 11.6
 - JDK信息： Openjdk 1.8.0_192
 - 版本信息：Fastjson2 2.0.42
 

### 重现步骤
*如何操作可以重现该问题：*
代码1：使用批量求值的代码，期望是提取出来是数组后，是数组的toString结果，但执行eval后，extract为null
```java

        String jsonStr = "{\"a\":{\"b\":{\"c\":\"xxxx\"},\"d\":{\"c\":\"qqqq\"}}}";
        JSONObject jsonObject = JSON.parseObject(jsonStr);

        JSONPath jsonPath = JSONPath.of(
                new String[]{"$.a.*.c"},
                new Type[]{String.class}
        );

        Object extract = jsonPath.eval(jsonObject);

```

代码2：使用Object extract(JSONReader jsonReader)能得到期望的结果，result为JsonArray
```java

        String jsonStr = "{\"a\":{\"b\":{\"c\":\"xxxx\"},\"d\":{\"c\":\"qqqq\"}}}";
        JSONPath jsonPath = JSONPath.of("$.a.*.c");
        JSONReader parser = JSONReader.of(jsonStr);
        Object result = jsonPath.extract(parser);

```

### 期待的正确结果
批量提取值时的结果为array：["xxxx","qqqq"]

**Comment by chlch** [comment]
```
        JSONPath jsonPath = JSONPath.of("$.a.*.c");
```
都构造这样得jsonPath 两个方法返回是一致得

**Comment by ChaYedan666** [comment]
> ```
>         JSONPath jsonPath = JSONPath.of("$.a.*.c");
> ```
> 
> 都构造这样得jsonPath 两个方法返回是一致得

问题就在于我有同一个JSON做多个JSONPath求值的场景，qps也较高，想尽可能的提升性能，所以按照wiki里的写了，就发现了问题。现在换回循环一个一个求了😂

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43
请用新版本
