### ISSUE TITLE
将String解析成JSONObject这个场景，fastjson2表现没有两倍于fastjson1的性能[QUESTION]

### ISSUE THREAD

**Issue by chxuan** [alibaba/fastjson2#206]
你好，温少，我在测试将String解析成JSONObject这个场景，fastjson2表现没有两倍于fastjson1的性能，测试环境：MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
测试json使用的eishay.json
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/6542180/167404586-9fea371b-721a-4952-a48c-b5bd3d6d14a8.png">

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/blob/main/core/src/test/java/com/alibaba/fastjson_perf/eishay/EishayParseTreeStringPretty.java

你跑下这个类的main方法，我刚测试的结果：
```java
Benchmark                               Mode  Cnt     Score   Error   Units
EishayParseTreeStringPretty.fastjson1  thrpt    5   647.006 ± 7.090  ops/ms
EishayParseTreeStringPretty.fastjson2  thrpt    5  1093.328 ± 7.012  ops/ms
EishayParseTreeStringPretty.jackson    thrpt    5   708.005 ± 1.783  ops/ms
```

**Comment by wenshao** [comment]
结果类似，这个场景都是快60%多一些

**Comment by chxuan** [comment]
@wenshao 温少，如果测试json里面还有嵌套json字符串，在进行解析的时候会反转义，那么fastjson2相较于fastjson的性能提升就更不明显了（提升百分之几到百分之二十）,如果json字符串更大（比如10k+）fastjson2还要比fastjson慢百分之几到百分之三十左右，我目前使用fastjson的场景是解析json日志（日志场景特点：1.json字符串较大，3k左右；2.日志里面会有大量转义字符）

**Comment by wenshao** [comment]
如果方便提供脱敏后的样本数据给我，我做下性能验证。我的邮箱 shaojin.wensj(at)alibaba-inc.com

**Comment by chxuan** [comment]
@wenshao 好的，温少，就是在处理json转义时不管是fastjson还是fastjson2的性能都会急剧下降，温少辛苦了，开源不易。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.3-SNAPSHOT/

@chxuan 做了一些优化，已经能比fastjson 1.x快大约30%，你用上面链接的2.0.3-SNAPSHOT版本试试看
