### ISSUE TITLE
[BUG] 字节数组转json

### ISSUE THREAD

**Issue by TongZYY** [alibaba/fastjson2#2067]
### 问题描述
*简要描述您碰到的问题。*
array是byte[]
JSON.parseObject(array)，报错java.lang.ArrayIndexOutOfBoundsException: Index 296 out of bounds for length 296，
array是下面字符串转的
`{'code':3006,'data':{'betList':[5,10,20,50,100],'buyCards':[],'cur_round':0,'mapId':40,'my_player':'{\'uid\':13730840,\'nickname\':\'王10\',\'sex\':0,\'headimgurl\':\'http://thirdwsx.qlogo.cn/mmopen/vi_32/s0tWG8WNxdfUjicicle40ODeyHBt8DttcKAw5zbgwgsEru2hMPdiasd2gH68Vz8Tx0smvlwjN2GydWj7ia4tUJPYHicA/132\',\'client_pos\':0,\'is_offline\':false,\'is_viewer\':1,\'ivpanr\':1,\'balance\':1000.0,\'totalPay\':0.0,\'totalPayCnt\':0}','roomId':164509742}}`
删掉my_player就好了。fastjson2就可以转了。说明在这块转的时候有问题。
这段字符串用fastjson1就可以正常解析,例如JSON.parseObject(str.getBytes(), JSONObject.class);

        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.33</version>
        </dependency>

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.43
请用新版本
