### ISSUE TITLE
SpringMVC中序列化和反序列化 List<LocalDateTime>

### ISSUE THREAD

**Issue by YiMoWanXia** [alibaba/fastjson2#2073]
版本：fastjson 2.0.32 springboot 3.1.1

实体类中有private List<LocalDateTime> timeList;

这种方式实现不了
①
  @JSONField(format = DatePattern.UTC_SIMPLE_PATTERN)
  private List<LocalDateTime> timeList;
②

`
    @Bean
    @SuppressWarnings("NullableProblems,ConstantValue")
    public Formatter<List<LocalDateTime>> localDateFormatter() {
        return new Formatter<>() {
            @Override
            public List<LocalDateTime> parse(String text, Locale locale) {
                if (StrUtil.isBlank(text)) {
                    return null;
                }
                return JSONArray.parseArray(text, String.class).stream().map(LocalDateTimeUtil::parse).toList();
            }

            @Override
            public String print(List<LocalDateTime> localDateTimeList, Locale locale) {
                if (Objects.isNull(localDateTimeList)) {
                    return null;
                }

                List<String> localDateTimeStrList = localDateTimeList.stream().map(localDateTime -> LocalDateTimeUtil.format(localDateTime, DatePattern.UTC_SIMPLE_PATTERN)).toList();
                return JSON.toJSONString(localDateTimeStrList);
            }
        };
    }
`

期望使用用方式①。

**Comment by YiMoWanXia** [comment]
这是将在 后续版本解决的意思是吗，当下有解决方案吗

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.44-SNAPSHOT/
问题重现并且修复，请帮忙用2.0.44-SNAPSHOT版本验证，2.0.44版本预计在2024年元旦发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.44
请用新版本
