### ISSUE TITLE
[BUG]这个是？这样不是很奇怪吗？

### ISSUE THREAD

**Issue by kaizen84** [alibaba/fastjson2#2093]
version:fastjson2-2.0.43
![image](https://github.com/alibaba/fastjson2/assets/49264728/3ee44ee1-39ca-46c1-92e3-b73f17eccaf6)

**Comment by kaizen84** [comment]
会有人这么玩 LocalTime 吗？难道要给每个 LocalTime字段都加上 @JSONField(format = "xx")?如果是 Map,List 这种数据结构里面放 LocalTime怎么加JSONField

**Comment by kaizen84** [comment]
有点火大，JSON.register一个 writer 又会让 @JSONField(format = "xx")失效，因为没有 format 交传给 writer
![image](https://github.com/alibaba/fastjson2/assets/49264728/1bf31a67-b662-408c-a034-943f3f113e6f)

**Comment by kaizen84** [comment]
![image](https://github.com/alibaba/fastjson2/assets/49264728/cdc8c140-c585-4fff-96e2-eb1169de2f0e)
这个东西又是一个非 public且 final 的，就很难受

**Comment by kaizen84** [comment]
还有一个问题  #2040 这个需求怎么实现？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.44-SNAPSHOT/
这个版本已经支持List/Map类型的@JSONField(format="HH:mm:ss")这样的配置

**Comment by wenshao** [comment]
```java
    @Data
    public static class Bean {
        @JSONField(format = "HH:mm:ss")
        private List<LocalDateTime> times;

        @JSONField(format = "HH:mm:ss")
        private Map<String, LocalDateTime> timeMap;
    }

        ObjectWriterProvider provider = new ObjectWriterProvider();
        BeanInfo beanInfo = new BeanInfo();
        FieldInfo fieldInfo = new FieldInfo();
        Class beanClass = Bean.class;
        Method method = beanClass.getMethod("getTimes");
        provider.getFieldInfo(beanInfo, fieldInfo, beanClass, method);
```

如上这样的方式可以读取到format
