### ISSUE TITLE
[BUG]com.alibaba.fastjson2.JSONException: parseInt error, value : PER_FOREVER

### ISSUE THREAD

**Issue by chq1024** [alibaba/fastjson2#2095]
### 问题描述
*简要描述您碰到的问题。*
JsonObject ->字符串->对象
枚举字段转化出现错误

### 环境信息
*请填写以下信息：*

 - OS信息：  windows,centos
 - JDK信息： 11
 - 版本信息：fastjson2.0.43
 

### 重现步骤
*如何操作可以重现该问题：*

其中字符串是对象转化的，包含枚举字段，并转化成了name
反序列化时其他枚举值转化成功，但同一个枚举中部分枚举转化失败
报：com.alibaba.fastjson2.JSONException: parseInt error, value : PER_FOREVER   // PER_FOREVER  是枚举元素name

![image](https://github.com/alibaba/fastjson2/assets/48238007/69a2378f-7357-40d7-8fcd-2412ddd896c8)

**Comment by rowstop** [comment]
能给下复现代码吗
