### ISSUE TITLE
[BUG] 删除Map类型的属性反序列化异常

### ISSUE THREAD

**Issue by xiaoe** [alibaba/fastjson2#2102]
### 问题描述
删除Map类型的属性反序列化异常
A，有个Map类型的属性
```java
public class JavaBeanA {
    private Map<Integer, Integer> map = new HashMap<>();

    public Map<Integer, Integer> getMap() {
        return map;
    }

    public void setMap(Map<Integer, Integer> map) {
        this.map = map;
    }
}
```
序列化后得到byte[] = [123, 34, 109, 97, 112, 34, 58, 123, 49, 58, 49, 125, 125]
删除A类的Map属性
```java
public class JavaBeanB {
// 就当他是A类删除属性后的结构
}
```
反序列失败
```java
Exception in thread "main" com.alibaba.fastjson2.JSONException: not support unquoted name
	at com.alibaba.fastjson2.JSONReaderUTF8.skipName(JSONReaderUTF8.java:5452)
	at com.alibaba.fastjson2.JSONReaderUTF8.skipValue(JSONReaderUTF8.java:5522)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:129)
	at com.alibaba.fastjson2.reader.ORG_1_0_JavaBeanB.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1365)
	at com.huiyunetwork.slg.FastjsonTest.main(FastjsonTest.java:32)
```
测试Main
```java
public static void main(String[] args) {
        JavaBeanA a = new JavaBeanA();
        a.getMap().put(1, 1);
        byte[] bytes = JSON.toJSONBytes(a);
        System.out.println(Arrays.toString(bytes));

        JSON.parseObject(bytes, JavaBeanB.class);
    }
```

### 环境信息
 - JDK信息： jdk 21
 - 版本信息：fastjson2.0.43 :)
 

### 期待的正确结果
希望修复删除字段后能兼容

**Comment by kaizen84** [comment]
这个不是因为你使用了Integer作为key 的原因吗？ String可能就好了
`not support unquoted name` 这个提示是说 key 没有加引号

**Comment by xiaoe** [comment]
com.alibaba.fastjson2.JSONReader.Feature#AllowUnQuotedFieldNames
没有效果，还是那个异常

这个Map类型的Key是Integer，但是他做为一个属性应该是合理的，且序列化也是可以正常识别
生成的JSON为 {"map":{1:1}}
```
{    "   m    a   p    "   :   {    1   :   1   }    }
123, 34, 109, 97, 112, 34, 58, 123, 49, 58, 49, 125, 125
```
理论上反序列化时，删除属性是Map类型的map，应该跳过这个 "map":{1:1} ，看异常，他进Value分析了

**Comment by kaizen84** [comment]
不是标准的 JSON 格式 
com.alibaba.fastjson2.JSONReader.Feature#ANonStringKeyAsString这个再试下

**Comment by kaizen84** [comment]
实在不行序列化的时候加上这个 com.alibaba.fastjson2.JSONWriter.Feature#WriteNonStringKeyAsString

**Comment by xiaoe** [comment]
这个com.alibaba.fastjson2.JSONWriter.Feature#WriteNonStringKeyAsString是可以的，但解决方案不太理想

1. 已存档的数据并不能自我修复
2. map属性可以序列化，在不缺省的情况下是可以反序列，这里算不算不是标准的 JSON 格式
3. 当删除map属性的字段，反序列失败，这个应该是兼容性问题, 不应该使用WriteNonStringKeyAsString就算了



分析一下结构
```
{    "   m    a   p    "   :   {    1   :   1   }    }
123, 34, 109, 97, 112, 34, 58, 123, 49, 58, 49, 125, 125
```
反序列化应该是发现缺少map属性

直接跳过此属性Key与Value
```
skipName();
skipValue();
```

我看一下代码
com.alibaba.fastjson2.JSONReaderUTF8#skipValue

其中
```
case '{': {
                next();
                for (; ; ) {
                    if (ch == '}') {
                        next();
                        break;
                    }
                    skipName();// 问题在这里，这里是按标准的JSON格式在处理
                    skipValue();
                }
                break;
            }
```
忽略Value是不是可以直接查找对应的 { } ，直接数数位置，直接增加 offset

**Comment by kaizen84** [comment]
只能说是兼容不兼容的问题 不能说它兼容了 他就是标准格式

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.44-SNAPSHOT/
问题重现并且修复，请帮忙用2.0.44-SNAPSHOT版本并加上AllowUnQuotedFieldNames验证，2.0.44版本预计在2024年元旦发布

**Comment by xiaoe** [comment]
感谢修复，跑了一下没有问题了，再观察几天数据~~~

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.44
请用新版本
