### ISSUE TITLE
com.alibaba.fastjson2.JSONException: offset 60, character , line 1, column 61, fastjson-version 2.0.43 "{\"patientName\":\"aasf\",\"callNumber\":51,\"queueId\":1}"

### ISSUE THREAD

**Issue by mxj009** [alibaba/fastjson2#2110]
### 问题描述
*简要描述您碰到的问题。*
很简单的字符转化："{\"patientName\":\"aasf\",\"callNumber\":51,\"queueId\":1}"
JSONObject json = JSON.parseObject(message);

报错信息如下：
com.alibaba.fastjson2.JSONException: illegal input， offset 60, char 

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：window11]
 - JDK信息： [e.g.：jdk21]
 - 版本信息：[e.g.：Fastjson2 2.0.39]

**Comment by mxj009** [comment]
![Uploading 1.png…]()

**Comment by mxj009** [comment]
<img width="938" alt="1" src="https://github.com/alibaba/fastjson2/assets/25301802/8d51ecb6-9b2e-49ee-adc1-97a265380e20">

**Comment by mxj009** [comment]
<img width="938" alt="1" src="https://github.com/alibaba/fastjson2/assets/25301802/e7fa7d41-4815-45c4-812e-8bb9452f1045">
https://github.com/alibaba/fastjson2/assets/25301802/e7fa7d41-4815-45c4-812e-8bb9452f1045

**Comment by kaizen84** [comment]
2.0.43未复现
![image](https://github.com/alibaba/fastjson2/assets/49264728/afe32e7b-a750-4207-a695-29656129829f)

**Comment by mxj009** [comment]
奇怪了，你看我那个已经走到2039行了，这里判断如果是空，则return，因为不为空，所以走到异常了
