### ISSUE TITLE
[BUG]反序列化后内容错误

### ISSUE THREAD

**Issue by lngex** [alibaba/fastjson2#2113]
### 问题描述
对JSON字符串反序列后部分字段值错误，如sContent值中Résumé反序列化后为R￩sum￩

### 环境信息
*请填写以下信息：*

 - OS信息： win11与Centos7
 - JDK信息： Openjdk 17.0.6
 - 版本信息：fastjson2 2.0.25
 

### 重现步骤
*如何操作可以重现该问题：*

```
    public static void main(String[] args) {
        String json = """
                {"attentionCount":0,"commentsCount":0,"iCreateTime":1703123381,"iHeatRank":6,"iInfluence":2,"iMediaBrief":0,"iMediaValueTotal":0.0,"iNewsImages":0,"iPublishTime":1703088000,"iSimCount":0,"iSiteArea":5,"iSiteCountryArea":43,"iSiteId":5577,"itype":1,"likeNum":0,"prodType":1,"readNum":0,"repostsCount":0,"sAuthor":"YouTube","sContent":"{09}An own goal, a sublime goal by Mateo Kovacic and a well-placed one by Bernardo Silva gave UEFA Champions - Manchester ...Related{092}r{092}n{09}Monaco vs. TOULOUSE #ligue1 #highlights #messi{092}r{092}n{09}Wissam Ben Yedder Goals, Toulouse vs Monaco (1-2), All Goals Results And Extended Highlights-2023.{092}r{092}n{09}AS MONACO - TOULOUSE FC 2-1 Résumé | ASM - TFC | MONACO Vs TOULOUSE | Ligue 1 Uber Eats 2023-24{092}r{092}n{09}Alexandre Golovine Carton rouge Toulouse vs Monaco LIGUE 1 23{092}r{092}n{09}Toulouse vs AS Monaco 1-2 Ligue 1 Uber Eats 2023 Breaking News{092}r{092}n{09}Frank Magri but incroyable : Toulouse vs Monaco.{092}r{092}n{09}TOULOUSE vs AS MONACO - odds comparison - bet (12-20){092}r{092}n{09}Toulouse - AS Monaco (1 - 2) - Résumé - (TFC - ASM) / 2023-24{092}r{092}n{09}Ben Yedder Goal,Toulouse vs AS Monaco (1-1) All Goals and Extended Highlights{092}r{092}n{09}Toulouse vs AS Monaco Résumé Ligue 1 2023\\\\24{092}r{092}n{09}Wissam Ben Yedder Goal, Toulouse vs Monaco 1-2 | All Goals and Extended Highlights.{092}r{092}n{09}Toulouse - Monaco 17ème j. 2023 débrief","sExtractText":"","sId":"netn9010F96561FE1203E986114413C212E7","sInnerTypes":"0","sInstruction":"","sLanguage":"en","sLink":"https://america.easybranches.com/chile/17278895","sSimFlag":"netn9010F96561FE1203E986114413C212E7","sSiteName":"easybranches","sTitle":"Manchester City 3 - 0 Urawa Reds | Kovacic and Silva Score | FIFA Club World Cup | Live on StarTimes","sTrCode":"4d424f481ac7fce33279945045f90c51","sType":"Chile","sWebSite":"spider|oc_website|5577","solrflag":1,"tablename":"oc_yuqing_news_202312","tagSolr":6,"wordCount":209}
                """;
        System.out.println(json);
        System.out.println(JSON.parseObject(json, JSONReader.Feature.FieldBased));
    }
```

### 期待的正确结果
{"attentionCount":0,"commentsCount":0,"iCreateTime":1703123381,"iHeatRank":6,"iInfluence":2,"iMediaBrief":0,"iMediaValueTotal":0.0,"iNewsImages":0,"iPublishTime":1703088000,"iSimCount":0,"iSiteArea":5,"iSiteCountryArea":43,"iSiteId":5577,"itype":1,"likeNum":0,"prodType":1,"readNum":0,"repostsCount":0,"sAuthor":"YouTube","sContent":"{09}An own goal, a sublime goal by Mateo Kovacic and a well-placed one by Bernardo Silva gave UEFA Champions - Manchester ...Related{092}r{092}n{09}Monaco vs. TOULOUSE #ligue1 #highlights #messi{092}r{092}n{09}Wissam Ben Yedder Goals, Toulouse vs Monaco (1-2), All Goals Results And Extended Highlights-2023.{092}r{092}n{09}AS MONACO - TOULOUSE FC 2-1 Résumé | ASM - TFC | MONACO Vs TOULOUSE | Ligue 1 Uber Eats 2023-24{092}r{092}n{09}Alexandre Golovine Carton rouge Toulouse vs Monaco LIGUE 1 23{092}r{092}n{09}Toulouse vs AS Monaco 1-2 Ligue 1 Uber Eats 2023 Breaking News{092}r{092}n{09}Frank Magri but incroyable : Toulouse vs Monaco.{092}r{092}n{09}TOULOUSE vs AS MONACO - odds comparison - bet (12-20){092}r{092}n{09}Toulouse - AS Monaco (1 - 2) - Résumé - (TFC - ASM) / 2023-24{092}r{092}n{09}Ben Yedder Goal,Toulouse vs AS Monaco (1-1) All Goals and Extended Highlights{092}r{092}n{09}Toulouse vs AS Monaco Résumé Ligue 1 2023\\24{092}r{092}n{09}Wissam Ben Yedder Goal, Toulouse vs Monaco 1-2 | All Goals and Extended Highlights.{092}r{092}n{09}Toulouse - Monaco 17ème j. 2023 débrief","sExtractText":"","sId":"netn9010F96561FE1203E986114413C212E7","sInnerTypes":"0","sInstruction":"","sLanguage":"en","sLink":"https://america.easybranches.com/chile/17278895","sSimFlag":"netn9010F96561FE1203E986114413C212E7","sSiteName":"easybranches","sTitle":"Manchester City 3 - 0 Urawa Reds | Kovacic and Silva Score | FIFA Club World Cup | Live on StarTimes","sTrCode":"4d424f481ac7fce33279945045f90c51","sType":"Chile","sWebSite":"spider|oc_website|5577","solrflag":1,"tablename":"oc_yuqing_news_202312","tagSolr":6,"wordCount":209}

### 相关日志输出
{"attentionCount":0,"commentsCount":0,"iCreateTime":1703123381,"iHeatRank":6,"iInfluence":2,"iMediaBrief":0,"iMediaValueTotal":0.0,"iNewsImages":0,"iPublishTime":1703088000,"iSimCount":0,"iSiteArea":5,"iSiteCountryArea":43,"iSiteId":5577,"itype":1,"likeNum":0,"prodType":1,"readNum":0,"repostsCount":0,"sAuthor":"YouTube","sContent":"{09}An own goal, a sublime goal by Mateo Kovacic and a well-placed one by Bernardo Silva gave UEFA Champions - Manchester ...Related{092}r{092}n{09}Monaco vs. TOULOUSE #ligue1 #highlights #messi{092}r{092}n{09}Wissam Ben Yedder Goals, Toulouse vs Monaco (1-2), All Goals Results And Extended Highlights-2023.{092}r{092}n{09}AS MONACO - TOULOUSE FC 2-1 Résumé | ASM - TFC | MONACO Vs TOULOUSE | Ligue 1 Uber Eats 2023-24{092}r{092}n{09}Alexandre Golovine Carton rouge Toulouse vs Monaco LIGUE 1 23{092}r{092}n{09}Toulouse vs AS Monaco 1-2 Ligue 1 Uber Eats 2023 Breaking News{092}r{092}n{09}Frank Magri but incroyable : Toulouse vs Monaco.{092}r{092}n{09}TOULOUSE vs AS MONACO - odds comparison - bet (12-20){092}r{092}n{09}Toulouse - AS Monaco (1 - 2) - Résumé - (TFC - ASM) / 2023-24{092}r{092}n{09}Ben Yedder Goal,Toulouse vs AS Monaco (1-1) All Goals and Extended Highlights{092}r{092}n{09}Toulouse vs AS Monaco Résumé Ligue 1 2023\\24{092}r{092}n{09}Wissam Ben Yedder Goal, Toulouse vs Monaco 1-2 | All Goals and Extended Highlights.{092}r{092}n{09}Toulouse - Monaco 17ème j. 2023 débrief","sExtractText":"","sId":"netn9010F96561FE1203E986114413C212E7","sInnerTypes":"0","sInstruction":"","sLanguage":"en","sLink":"https://america.easybranches.com/chile/17278895","sSimFlag":"netn9010F96561FE1203E986114413C212E7","sSiteName":"easybranches","sTitle":"Manchester City 3 - 0 Urawa Reds | Kovacic and Silva Score | FIFA Club World Cup | Live on StarTimes","sTrCode":"4d424f481ac7fce33279945045f90c51","sType":"Chile","sWebSite":"spider|oc_website|5577","solrflag":1,"tablename":"oc_yuqing_news_202312","tagSolr":6,"wordCount":209}

{"attentionCount":0,"commentsCount":0,"iCreateTime":1703123381,"iHeatRank":6,"iInfluence":2,"iMediaBrief":0,"iMediaValueTotal":0.0,"iNewsImages":0,"iPublishTime":1703088000,"iSimCount":0,"iSiteArea":5,"iSiteCountryArea":43,"iSiteId":5577,"itype":1,"likeNum":0,"prodType":1,"readNum":0,"repostsCount":0,"sAuthor":"YouTube","sContent":"{09}An own goal, a sublime goal by Mateo Kovacic and a well-placed one by Bernardo Silva gave UEFA Champions - Manchester ...Related{092}r{092}n{09}Monaco vs. TOULOUSE #ligue1 #highlights #messi{092}r{092}n{09}Wissam Ben Yedder Goals, Toulouse vs Monaco (1-2), All Goals Results And Extended Highlights-2023.{092}r{092}n{09}AS MONACO - TOULOUSE FC 2-1 R￩sum￩ | ASM - TFC | MONACO Vs TOULOUSE | Ligue 1 Uber Eats 2023-24{092}r{092}n{09}Alexandre Golovine Carton rouge Toulouse vs Monaco LIGUE 1 23{092}r{092}n{09}Toulouse vs AS Monaco 1-2 Ligue 1 Uber Eats 2023 Breaking News{092}r{092}n{09}Frank Magri but incroyable : Toulouse vs Monaco.{092}r{092}n{09}TOULOUSE vs AS MONACO - odds comparison - bet (12-20){092}r{092}n{09}Toulouse - AS Monaco (1 - 2) - R￩sum￩ - (TFC - ASM) / 2023-24{092}r{092}n{09}Ben Yedder Goal,Toulouse vs AS Monaco (1-1) All Goals and Extended Highlights{092}r{092}n{09}Toulouse vs AS Monaco R￩sum￩ Ligue 1 2023\\24{092}r{092}n{09}Wissam Ben Yedder Goal, Toulouse vs Monaco 1-2 | All Goals and Extended Highlights.{092}r{092}n{09}Toulouse - Monaco 17￨me j. 2023 d￩brief","sExtractText":"","sId":"netn9010F96561FE1203E986114413C212E7","sInnerTypes":"0","sInstruction":"","sLanguage":"en","sLink":"https://america.easybranches.com/chile/17278895","sSimFlag":"netn9010F96561FE1203E986114413C212E7","sSiteName":"easybranches","sTitle":"Manchester City 3 - 0 Urawa Reds | Kovacic and Silva Score | FIFA Club World Cup | Live on StarTimes","sTrCode":"4d424f481ac7fce33279945045f90c51","sType":"Chile","sWebSite":"spider|oc_website|5577","solrflag":1,"tablename":"oc_yuqing_news_202312","tagSolr":6,"wordCount":209}

**Comment by 805728578** [comment]
@lngex 已在v2.0.43版本验证，此问题不存在，请你升级版本后确认一下

**Comment by lngex** [comment]
> @lngex 已在v2.0.43版本验证，此问题不存在，请你升级版本后确认一下

谢谢已升级解决
