### ISSUE TITLE
[FEATURE] features优化建议，统一封装

### ISSUE THREAD

**Issue by rowstop** [alibaba/fastjson2#2121]
1.  项目中对于 features的判断非常多，如读和写的特性判断，但是没有做统一封装，用起来稍显繁琐
2. 我考虑提供一套统一封装的方法。这有助于项目的可维护性和整体一致性。通过遵循一致的编码标准，用户可以更轻松地理解，有助于这个项目的长期发展
3. 我将做以下调整：
   - Context：Reader Context 和 Writer Context 将继承这个类， 目前包含一个 features 属性，并且提供一些 Feature 特性判断方法
   - Feature：Reader  Feature 和 Writer Feature 将继承这个类，包含一个获取 mask的方法 
   - 修改项目中特性判断的代码，使用统一封装的方法
4. 如果有什么建议，可以提出来，我可以考虑进去

**Comment by wenshao** [comment]
不建议为因为这种做大的改动，因为要很小心做过不同平台的benchmark评估对性能的影响

**Comment by rowstop** [comment]
> 不建议为因为这种做大的改动，因为要很小心做过不同平台的benchmark评估对性能的影响

这里是指方法调用的性能开销？若果调用频率很高，JVM会优化为内联形式。影响应该会很小。但是可维护性将会很好
如果不考虑的话，我将关闭这个 issue

**Comment by wenshao** [comment]
不考虑，使用mask是故意而为之

**Comment by rowstop** [comment]
OK
