### ISSUE TITLE
2.0.44 数字过长导致负数转换为整数的bug

### ISSUE THREAD

**Issue by org-kepe** [alibaba/fastjson2#2128]
### 问题描述
*简要描述您碰到的问题。*
```java
String str="{\"amt\":-22.1400000000000005684341886080801486968994140625}";
System.out.println(JSONObject.parseObject(str, Map.class));
//输出{amt=22.1400000000000005684341886080801486968994140625}
```
应该结果是负数的，结果值变了

### 环境信息
*请填写以下信息：*

 - OS信息： windows linix
 - JDK信息：1.8 
 - 版本信息：2.0.44

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/
问题已修复，请帮2.0.45-SNAPSHOT验证问题是否已经修复，我会尽快发布新版本

**Comment by org-kepe** [comment]
问题已修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.45
问题已修复，请用新版本
