### ISSUE TITLE
感觉太奇怪了，字段orderNumber会变成outerNumber

### ISSUE THREAD

**Issue by wghdir** [alibaba/fastjson2#2131]
![image](https://github.com/alibaba/fastjson2/assets/19346934/5a44f84a-b2a3-4e2f-ab37-226dc30b24b8)
//取字段内容转成JSONObject
 public static JSONObject getMapJSONObject(Map<String, ?> map, String colname, JSONObject def) {
        if (map == null) return def;
        if (map.containsKey(colname)) {
            Object _obj = map.get(colname);
            if (_obj == null)
                return def;
            else {
                try {
                    return JSONObject.parseObject(_obj.toString());
                } catch (Exception e) {
                    return def;
                }
            }
        } else {
            return def;
        }
    }
JSONObject js = getMapJSONObject(retjs, "obj", null);
打印出js的内容就是orderNumber变成了outerNumber，这个情况非常少，有时取不到值 ，后来加了个取不到值时打印出来看下才发现，但不知道怎么回事，这情况非常少
用的是fastjson2.0.35

**Comment by wghdir** [comment]
出现这情况后我重启一下服务器后又好了。出现的时候就次数比较多。

**Comment by wenshao** [comment]
这个问题修复过，你帮忙升到2.0.44版本看下问题是否已经解决了

**Comment by wghdir** [comment]
这个orderNumber变outerNumber不是常发生哦，我这循环转了几个小时都没出现,不知道什么条件下会这样。

**Comment by wenshao** [comment]
是一个缓存name加速的bug导致的
