### ISSUE TITLE
[BUG] 升级到 2.0.39 以及更新的版本 JSON.toJSON 报错

### ISSUE THREAD

**Issue by naivetoby** [alibaba/fastjson2#2144]
### 问题描述

*升级到 2.0.39 以及更新的版本 JSON.toJSON 报错*

### 环境信息
*请填写以下信息：*

 - OS信息：  macOS Sonoma 14.2.1
 - JDK信息： OpenJDK Runtime Environment Corretto-17.0.9.8.1
 - 版本信息：2.0.10 - 2.0.38 正常 / 2.0.39 - 2.0.44 报错
 

### 重现步骤
*如何操作可以重现该问题：*

```java

@Data
public class A {

    public B buildB() {
        return buildB(new B());
    }

    public <T extends B> T buildB(T b) {
        return b;
    }

}

@Data
public class B {

    public B buildB() {
        return buildB(new B());
    }

    public <T extends B> T buildB(T b) {
        return b;
    }

}

public static void main(String[] args) {
    final A a = new A();
    log.info("b: {}", JSON.toJSON(a.buildB()));
}

```

**版本 2.0.10 - 2.0.38 正常打印结果**

```bash
-- b: {}
```

**版本 2.0.39 - 2.0.44 控制台打印错误**

```bash
com.alibaba.fastjson2.JSONException: level too large : 2048
	at com.alibaba.fastjson2.JSONWriterUTF16.startObject(JSONWriterUTF16.java:117)
	at com.alibaba.fastjson2.writer.OWG_1_1_B.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_1_1_B.write(Unknown Source)
	at com.alibaba.fastjson2.writer.OWG_1_1_B.write(Unknown Source)
```

**Comment by naivetoby** [comment]
你好，是不是我反馈的问题描述不清晰？还是用法存在问题，辛苦给一个反馈，这个问题影响到公司底层框架的使用，非常紧急，万分感谢🙏！！！

**Comment by wenshao** [comment]
问题已重现，我尽快处理，争取1月7日前修复发布新版本。

**Comment by naivetoby** [comment]
> 问题已重现，我尽快处理，争取1月7日前修复发布新版本。

辛苦啦！！！

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/
问题已修复，请帮2.0.45-SNAPSHOT验证问题是否已经修复，将会在1月7日前发布新版本

**Comment by naivetoby** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/ 问题已修复，请帮2.0.45-SNAPSHOT验证问题是否已经修复，将会在1月7日前发布新版本

已修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.45
问题已修复，请用新版本

**Comment by songhanlin** [comment]
2.0.47仍然存在

**Comment by sgalcheung** [comment]
Version 2.0.51 still has this problem.

**Comment by dlwss** [comment]
Version 2.0.52 still has this problem.

**Comment by jujn** [comment]
> 2.0.58 也有

已收到反馈

**Comment by jujn** [comment]
> 2.0.58 也有

能否提供一下测试用例？
