### ISSUE TITLE
[BUG] 解析不正确：JSONObject.parse("{1,2}") => {1:2}

### ISSUE THREAD

**Issue by yanchangyou** [alibaba/fastjson2#2155]
### 问题描述
*JSON解析不正确*

### 环境信息
*请填写以下信息：*

 - OS信息：  MacOS
 - JDK信息： corretto-11.0.21
 - 版本信息：2.0.42
 

### 重现步骤
*如何操作可以重现该问题：*

JSONObject.parse("{1,2}") => {1:2}

```java
        System.out.println(JSONObject.parse("{1,2}"));
```

### 期待的正确结果
提示：语法错误

### 相关日志输出
{1:2}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/
问题已修复，请帮2.0.45-SNAPSHOT验证问题是否已经修复，将会在1月7日前发布新版本

**Comment by yanchangyou** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.45-SNAPSHOT/ 问题已修复，请帮2.0.45-SNAPSHOT验证问题是否已经修复，将会在1月7日前发布新版本

JSONObject.parse("{1,2}") => {1:2}  好了，但又发现一些增加位数的case

JSONObject.parse("{10,2}") => {10:2} 
JSONObject.parse("{1,20}") => {1:20}

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.45
问题已修复，请用新版本
