### ISSUE TITLE
[BUG] 使用 jdk9 module 功能后，要求不同的 module 中的 package 不能相同

### ISSUE THREAD

**Issue by EthanKk** [alibaba/fastjson2#2176]
### 问题描述
*简要描述您碰到的问题。*

fastjson2 和 fastjson2-extension 包含了相同的包名。

根据 JDK9 module 功能的规定，不同 module 中不能出现相同名称的 package “com.alibaba.fastjson2.support”。

![Uploading image.png…]()

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：jdk9]
 - 版本信息：[e.g.：Fastjson2 2.0.45]
 
#1923

**Comment by EthanKk** [comment]
补充截图
![image](https://github.com/alibaba/fastjson2/assets/6426859/7273e15c-547a-4dc8-abbf-db6a12fd3885)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
问题已修复，请用新版本
