### ISSUE TITLE
JSON.parseObject(resultJsonStr, new TypeReference<T>() {}) 空指针

### ISSUE THREAD

**Issue by Crayon-kk** [alibaba/fastjson2#2177]
JSON.parseObject(resultJsonStr, new TypeReference<T>() {})主线程不报错，启用线程报错
![image](https://github.com/alibaba/fastjson2/assets/33805801/2d5c9174-42c2-443f-bcbb-5d43700c6764)

**Comment by rowstop** [comment]
泛型方法只有在调用时才能确定具体的类型，而lambda表达式只是声明函数不是调用函数，类型丢失了
你需要在声明之前定义好泛型参数，然后声明时使用它

**Comment by Crayon-kk** [comment]
6
