### ISSUE TITLE
[FEATURE] 反序列化时的Support Auto Type特性能否支持@type注释的重排或规范化处理

### ISSUE THREAD

**Issue by ConquerMyHer** [alibaba/fastjson2#2179]
Support Auto Type 的@type注释默认是从json字符串开头获取。
存在一些场景，例如特殊的数据库/持久化需求，需要序列化的json字符串按照数据库的默认json格式存入。
此时数据库会对json做重排序，或者在输出时并不严格保持输入的顺序，也就导致了@type的格式混乱。
此时的JsonReader即便设置了Support Auto Type的特性，也是无法正确解析的。
但是这个注解在理论上是可解析的，也就是说顺序的混乱应该不影响注解的含义。

因此希望在反序列化时，如果处理@type注释，希望加上重排或规范化处理机制，使其可以应对@type顺序混乱的情况。

**Comment by rowstop** [comment]
我的理解：因为顺序未知，读取到一半需要重新读取，应该是对性能影响比较大。
1. SupportAutoType 本身不是一个安全的特性开关
2. 如果读取时知道准确的类型，就不需要写入类型；或者是否可以使用 text 类型存储；或者考虑自定义读取

**Comment by rowstop** [comment]
也许后面会支持这种格式

**Comment by wenshao** [comment]
不支持重排，设计就是这样的
