### ISSUE TITLE
$.ref 不在数组中如何还原

### ISSUE THREAD

**Issue by longchengli** [alibaba/fastjson2#2180]
https://github.com/alibaba/fastjson2/issues/2140

**Comment by longchengli** [comment]
![image](https://github.com/alibaba/fastjson2/assets/49945982/3ea656c7-792b-42a0-9ca7-756eb9ed7ea9)
在数组中能还原回去

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
请用新版本
