### ISSUE TITLE
[BUG] JSONWriter.Feature.BrowserCompatible 导致 LocalDateTime 类型未按预期格式进行格式化处理

### ISSUE THREAD

**Issue by SkiffBoy** [alibaba/fastjson2#2183]
### 问题描述
JSONWriter.Feature.BrowserCompatible 未对日期型数据进行格式化：
 Map 中 键类型为 LocalDateTime 的数据

### 环境信息

 - OS信息：  [MacOS 12.7 MacBook M1 ]
 - JDK信息： [Oracle OpenJDK 1.8.0_391]
 - 版本信息：[Fastjson2 2.0.44]
 

### 重现步骤

1. 使用 `JSONWriter.Feature.BrowserCompatible` 作为序列化要求
2. 序列化  `LocalDateTime` 作为 key 的 Map 类型数据
3. 出现 `日期型 key 未按照指定格式进行格式化` 的问题

预期输出结果：
{"2024-01-12 19:55:57":1705060557443,"now":"2024-01-12 19:55:57"}
实际输出结果：
{"2024-01-12T19:55:57.443":1705060557443,"now":"2024-01-12 19:55:57"}

```java
@Test
public void testBrowserCompatible() {
    // 全局设置：默认日期时间格式、默认时区
    JSON.configReaderZoneId(ZoneId.of("Asia/Shanghai"));
    JSON.configWriterZoneId(ZoneId.of("Asia/Shanghai"));
    JSON.configReaderDateFormat("yyyy-MM-dd HH:mm:ss");
    JSON.configWriterDateFormat("yyyy-MM-dd HH:mm:ss");

    Map data = new HashMap();
    data.put("now", LocalDateTime.now());
    data.put(LocalDateTime.now(), System.currentTimeMillis());

    final String json1 = JSONObject.toJSONString(data, JSONWriter.Feature.BrowserCompatible);
    final String json2 = JSONObject.toJSONString(data);
    System.out.println(json1);
    System.out.println(json2);
    Assertions.assertEquals(json1, json2, "日期格式处理异常");
}
```

### 期待的正确结果
期望 `JSONWriter.Feature.BrowserCompatible` 不会影响日期格式的序列化 `yyyy-MM-dd HH:mm:ss`

### 相关日志输出
```log
org.opentest4j.AssertionFailedError: 日期格式处理异常 ==> 
预期:{"2024-01-12T19:55:57.443":1705060557443,"now":"2024-01-12 19:55:57"}
实际:{"2024-01-12 19:55:57":1705060557443,"now":"2024-01-12 19:55:57"}
```

#### 附加信息

<img width="823" alt="image" src="https://github.com/alibaba/fastjson2/assets/12690001/508b6e62-22cf-45de-b472-2044eae86474">

**Comment by rowstop** [comment]
会直接 toString

**Comment by rowstop** [comment]
Map 里的BrowserCompatible 等同于 WriteNonStringKeyAsString

**Comment by rowstop** [comment]
Map里的BrowserCompatible 等同于 WriteNonStringKeyAsString

**Comment by rowstop** [comment]
> 感谢解答，目前如果要对日期型 key，Fastjson 可以统一处理吗
我是觉得直接 toString 有点草率了，而且导致BrowserCompatible有歧义

**Comment by rowstop** [comment]
我能想到的就是根据前后的 offset 偏移量取出序列化后的值，然后重写这部分序列化的结果

**Comment by rowstop** [comment]
@wenshao 这个你在做了吗？我这边做了一版，试了下没问题，要不要我提个 PR 看下？

**Comment by rowstop** [comment]
已经提了 PR，看下是否合适

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
请用新版本
