### ISSUE TITLE
[BUG] Kotlin Json解析错误

### ISSUE THREAD

**Issue by zfdx123** [alibaba/fastjson2#2186]
### 问题描述
*简要描述您碰到的问题。*
json解析到对象

### 环境信息
*请填写以下信息：*

 - OS信息：  开发环境：Win10 I5-7300HQ 16GRAM 运行环境：Android14  HyperOS
 - JDK信息： OracleJDK 21
 - 版本信息：FsatJson 2.0.45
 

### 重现步骤
*如何操作可以重现该问题：*
代码如图
![00f851307aa26b95553d5ddad998760](https://github.com/alibaba/fastjson2/assets/47835976/7bade5b3-62fb-458a-aa5e-f6af0d2e3b41)

![22d9975295eda40f33a256be1b087ba](https://github.com/alibaba/fastjson2/assets/47835976/2d835eea-c82f-4e1e-80d3-73025b4fa7d5)

json如下
```
{"status":200,"message":"OK","info":{"token":"XXXXXXX","name":"admin"}}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
```
FastJson: invoke constructor error, public com.hylab.centralcontrol.utils.Info(java.lang.String,java.lang.String)
```

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
```xml
  <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <scope>provided</scope>
        </dependency>
```
这个依赖加上了么？

**Comment by zfdx123** [comment]
哦并没有，我用的Gradle我一会加入  ```implementation("org.jetbrains.kotlin:kotlin-reflect:$kotlin_version")``` 测试一下

**Comment by zfdx123** [comment]
错误似乎依然存在 ```onResponse: com.alibaba.fastjson2.JSONException: invoke constructor error, public com.hylab.centralcontrol.utils.MessageList(int,java.lang.String,java.lang.String,java.util.List)```

**Comment by wenshao** [comment]
```kotlin
data class Message(
        var status: Int,
        var message: String,
        var msgInfo: String?,
        var info: Info
)
```
msgInfo字段缺失了，修改成这样就好了
