### ISSUE TITLE
反序列化fastjson2比fastjson慢3倍多

### ISSUE THREAD

**Issue by ananas-xxj** [alibaba/fastjson2#2189]
### 问题描述
如题，fastjson2不是优化了解析速度吗？

### 环境信息

 - OS信息：  [android7]
 - JDK信息： [jdk8]
 - 版本信息：[fastjson2:2.0.45.android4]
 

### 重现步骤
MGLog.i("MJson",templateDatas);
long startTime = System.currentTimeMillis();
List<TemplateData> list = com.alibaba.fastjson.JSON.parseArray(templateDatas, TemplateData.class);
MGLog.i("MJson",String.valueOf(System.currentTimeMillis()-startTime));
long startTime2 = System.currentTimeMillis();
List<TemplateData> list2 = com.alibaba.fastjson2.JSON.parseArray(templateDatas, TemplateData.class);
MGLog.i("MJson","2:"+String.valueOf(System.currentTimeMillis()-startTime2));
```

### 期待的正确结果
fastjson2解析速度应该更快


### 相关日志输出
689
2:1963


#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by ananas-xxj** [comment]
我这边测试，这个性能实在是个迷，有时比fastjson快有时候慢，现在就是这种情况吗？跟内存有关？但是我测试内存紧张的时候两个都慢。有点崩溃了，之前调研的时候没跑大量数据，简单跑下看到性能提升很大，现在接进来发现性能不稳定啊。 @wenshao

**Comment by ananas-xxj** [comment]
目前没看到fastjson2在Android平台上的测试结果，能否说下是否跑过Android平台的测试，测试结果怎么样呢？谢谢，感谢，期望回答下。

**Comment by wenshao** [comment]
我在华为的Mate40上测试过的场景都是快的，android环境不同的设备是不一样的，fastjson2.android4的性能测试确实没有fastjson 1.1.x.android测试充分。

如果遇到慢的场景，请提供详细的信息，好方便做重现以及优化。

**Comment by wangyatong** [comment]
会不会是每一个安卓设备的硬盘性能都不一样， soc 也不一样, 并且就算是一款soc 每一个厂商的理解也不一样导致的？

**Comment by wenshao** [comment]
最近已经在2.0.46.android4版本上做android真机性能优化了

**Comment by wenshao** [comment]
2.0.46.android5
==========
你帮忙用这个版本在验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.47
问题已修复，请用新版本
