### ISSUE TITLE
[FEATURE]支持java record

### ISSUE THREAD

**Issue by cjdxhjj** [alibaba/fastjson2#219]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*
目前已经升级到java 17,record 的序列化为空对象

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*
通过基类判断record类型后剔除hashcode等方法输出json和反序列化

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wsxe9988** [comment]
java record  in 2.0.3 version, will be released soon.

**Comment by cjdxhjj** [comment]
谢谢。

**Comment by wsxe9988** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.3-SNAPSHOT/

你试下新的快照版本，看问题是否已经解决

**Comment by cjdxhjj** [comment]
好的

**Comment by cjdxhjj** [comment]
我看你发的是fastjson, 我注意到仓库里有fastjson, fastjson 2,命名空间有差异，建议使用哪个

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/167757609-d700c0e2-88a6-496d-8942-edac876d42ed.png)
![image](https://user-images.githubusercontent.com/5616997/167757659-d03d41a9-582c-40cf-9fe3-58d53002fe6a.png)
简单测试了一下，可以了，谢谢
