### ISSUE TITLE
[QUESTION] JSONPath 支持这种需求吗？

### ISSUE THREAD

**Issue by qichhhhh** [alibaba/fastjson2#2190]
{"code":0,"errMsg":"","Data":{"is_focus":1,"user_info":{"userid":"13814","nickname":"没事改昵称"}}}

JSONPath 能做到判断 Data.user_info.userid 这个 key 如果存在的话返回 Data 的 value 吗 ？
应该怎么写呢，感谢各位

**Comment by wenshao** [comment]
现在不支持，将会2.0.46版本（春节前发布）支持

**Comment by wenshao** [comment]
```java
    public void test() {
        String str = "{\"code\":0,\"errMsg\":\"\",\"Data\":{\"is_focus\":1,\"user_info\":{\"userid\":\"13814\",\"nickname\":\"没事改昵称\"}}}";
        JSONObject jsonObject = JSON.parseObject(str);
        assertSame(jsonObject, JSONPath.eval(jsonObject, "[?exists(@.Data.user_info.userid)]"));
        assertNull(JSONPath.eval(jsonObject, "[?exists(@.Data.user_info.userid1)]"));
        assertNull(JSONPath.eval(jsonObject, "[?exists(@.Data.user_info1.userid)]"));
        assertNull(JSONPath.eval(jsonObject, "[?exists(@.Data1.user_info.userid)]"));
    }
```

https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.46-SNAPSHOT/
问题已修复，请帮忙用2.0.46-SNAPSHOT版本验证，正式版本预计在3月初发布。

**Comment by qichhhhh** [comment]
可以正常匹配并且返回 Data 的 value 了，感谢 @wenshao

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
问题已修复，请用新版本
