### ISSUE TITLE
[QUESTION] 單字段的 parsing 方式

### ISSUE THREAD

**Issue by cookieandcoke** [alibaba/fastjson2#2197]
在 RFC 7159 中，`"Hello World!"` 是合法的 JSON format, 請問在 2.0.40 要如何正確的 parse?
```
Object name = JSON.parse("Hello World!");
```
上面的代碼執行會發生 `com.alibaba.fastjson2.JSONException: offset 1, character T, line 1, column 2, ...` 的例外。

**Comment by wenshao** [comment]
```java
Object name = JSON.parse("\“Hello World!\“");
```
需要这样才是合法的
