### ISSUE TITLE
Date格式反序列化异常

### ISSUE THREAD

**Issue by zzqw** [alibaba/fastjson2#2199]
### 问题描述
*简要描述您碰到的问题。*
实体类使用@JSONField(format = "yyyy-MM-dd hh:mm:ss")定义日期格式字段，在反序列化的时候抛出异常，使用1.X是可以正常反序列化的

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows11]
 - JDK信息： [e.g.：Openjdk 1.8.0_381]
 - 版本信息：[e.g.：Fastjson2 2.0.45]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
public class Test {

    @Data
    public static class Obj1 {
        @JSONField(format = "yyyy-MM-dd hh:mm:ss")
        private Date startTime;
    }

    public static void main(String[] args) throws IOException {
        Obj1 orderBO = new Obj1();
        orderBO.setStartTime(new Date());
        String s  = JSONObject.toJSONString(orderBO);
        System.out.println(s);
        System.out.println(JSONObject.parseObject(s, Obj1.class));
    }

}
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
![image](https://github.com/alibaba/fastjson2/assets/32407444/2edaed32-6bab-4523-b441-01468dbcf10b)

这是使用1.X的反序列化结果
![image](https://github.com/alibaba/fastjson2/assets/32407444/934bc4a2-e828-4d25-b608-760f65a25758)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by GabrielHwang** [comment]
https://github.com/alibaba/fastjson2/blob/a979db481783041e314e43925284c0ce354009a9/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderImplDate.java#L89-L93
89行的 &&是不是应该改成 ||

**Comment by wenshao** [comment]
你要的是：
```java
"yyyy-MM-dd HH:mm:ss"
```
HH应该是大写

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.46-SNAPSHOT/
兼容问题已修复，请帮忙用2.0.46-SNAPSHOT版本验证，正式版本预计在3月初发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
问题已修复，请用新版本
