### ISSUE TITLE
fastjson从1.2.83升级到兼容版本2.0.39序列化ChannelSftp导致后续sftp命令无法执行

### ISSUE THREAD

**Issue by cheers512** [alibaba/fastjson2#2202]
### 问题描述
channelsftp对象序列化后，后续执行sftp的如cd、put命令会一直卡住

### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：Openjdk 1.8.0_144]
 - 版本信息：[e.g.：Fastjson2.0.39 1.X兼容版本]
 

### 重现步骤

依赖版本
<dependency>
                <groupId>com.jcraft</groupId>
                <artifactId>jsch</artifactId>
                <version>0.1.55</version>
            </dependency>

<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>2.0.39</version>
            </dependency>
```java
            JSch jsch = new JSch();
            Session sshSession = jsch.getSession(customUserName, customHost, customPort);
            java.util.Properties config = new java.util.Properties();
            config.put("StrictHostKeyChecking", "no");
            sshSession.setConfig(config);
//            sshSession.setConfig("StrictHostKeyChecking", "no");
            sshSession.setPassword(customPassword);
            sshSession.connect(5000);
            ChannelSftp channelSftp = (ChannelSftp) sshSession.openChannel("sftp");
            channelSftp.connect(5000);
            log.info("连接成功",JSON.toJSONString(channelSftp));
            channelSftp.cd("/test");

### 期待的正确结果
sftp命令能够正常执行

**Comment by cheers512** [comment]
![1705650336798](https://github.com/alibaba/fastjson2/assets/157100322/c5e04225-4ec7-48f5-92d8-e24e1b7d75bf)

**Comment by cheers512** [comment]
![2](https://github.com/alibaba/fastjson2/assets/157100322/e488948d-4efc-4902-b35a-6a929e6458c9)

**Comment by rowstop** [comment]
用法貌似不太合适，日志这种地方可以尝试手动拼接自己想看到的参数，转 JSON 没必要。

**Comment by rowstop** [comment]
没开启 filedbase 默认基于 get 序列化貌似`sftp.getInputStream()`影响到了,你在 cd前 getInputStream 会导致一样的问题

**Comment by rowstop** [comment]
你可以通过这种方式，排除inputStream，但把输入输出流全部排
```java
        PropertyPreFilter propertyPreFilter = (writer,obj,name)-> !"inputStream".equals(name);
        JSON.toJSONString(sftp,propertyPreFilter);
```

**Comment by rowstop** [comment]
用法貌似不太合适，日志这种地方可以尝试手动拼接自己想看到的参数，转 JSON 没必要。
没开启 filedbase 默认基于 get 序列化貌似`sftp.getInputStream()`影响到了,你在 cd前 getInputStream 会导致一样的问题
你可以通过这种方式，排除inputStream，但建议把所有输入输出流全部排除
```java
        PropertyPreFilter propertyPreFilter = (writer,obj,name)-> !"inputStream".equals(name);
        JSON.toJSONString(sftp,propertyPreFilter);
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.46-SNAPSHOT/
兼容问题已修复，忽略所有的InputStream Getter，请帮忙用2.0.46-SNAPSHOT版本验证，正式版本预计在3月初发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
请用新版本
