### ISSUE TITLE
[BUG]类似于java.sql.Struct类型数据返回内存溢出，建议优化处理

### ISSUE THREAD

**Issue by 1195952223** [alibaba/fastjson2#2205]
### 问题描述
*简要描述您碰到的问题。*
已转换解决，建议优化处理

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.45]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://github.com/alibaba/fastjson2/assets/35017668/54b4c918-4ea8-4c42-b03c-b620878d8f30)

![image](https://github.com/alibaba/fastjson2/assets/35017668/7057b86c-fd9c-481e-87d2-0f25d80bbb15)

**Comment by wenshao** [comment]
什么驱动下发生的？

**Comment by 1195952223** [comment]
达梦驱动、druid连接池

**Comment by 1195952223** [comment]
[Uploading 1.8.0.zip…]()

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
问题已修复，请用新版本
