### ISSUE TITLE
在字段上使用JSONField注解中的deserializeUsing、serializeUsing无效不起作用。

### ISSUE THREAD

**Issue by zhouzhibing** [alibaba/fastjson2#2213]
**ListIntReader.java**
---------------------------------------------------------------------
```
public class ListIntReader implements ObjectReader<Object> {

    public static final ListIntReader INSTANCE = new ListIntReader();
    @Override
    public Object readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
        System.out.println("ListInt.Reader");
        return null;
    }
}

```
**TextEntity.java**
---------------------------------------------------------------------
```
public class TextEntity {

    @JSONField(deserializeUsing = ListIntReader.class, serializeUsing = ListIntWriter.class)
    private List<Integer> idList;

    public static void main(String[] args) {
        String body = "{\"idList\":[1,2,3]}";
        TextEntity textEntity = JSON.parseObject(body , TextEntity.class, JSONReader.Feature.FieldBased);
        System.out.println();
    }
}
```
上述该示例，我在`TextEntity.java`中`idList`字段上，使用了JSONField该注解，并指定了序列化的反序列化自定义的使用，
`@JSONField(deserializeUsing = ListIntReader.class, serializeUsing = ListIntWriter.class)`
但实际运行时，无法去执行`ListIntReader.java`中的打印操作。

如果我想实现针对**该类型**中**该字段**定制个性化序例化的效果，我该怎么操作？

- OS信息： windows
- JDK信息： jdk 21
- 版本信息：'com.alibaba.fastjson2:fastjson2:2.0.45'

**Comment by HongJian-Yang** [comment]
我也很好奇 这个 deserializeUsing 和 serializeUsing 的用法

**Comment by HongJian-Yang** [comment]
你没写getset所以没触发deserializeUsing

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.46
问题已修复，请用新版本
