### ISSUE TITLE
[BUG] 将localdatetime put到jsonobject，再次输出时候T不见了

### ISSUE THREAD

**Issue by zck573693104** [alibaba/fastjson2#2221]
### 问题描述
*简要描述您碰到的问题。*
  JSONObject jsonObject = new JSONObject();
        jsonObject.put("key", LocalDateTime.of(2024, 1, 1, 1, 1, 1));
        JSONObject res = JSONObject.parseObject(jsonObject.toString());
   // 2024-01-01 01:01:01
        System.out.println(res.get("key"));

### 环境信息
*请填写以下信息：*
2.0.46的fastjson2
 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by rowstop** [comment]
toString()时才会进行序列化, 如果想序列化成这种格式 可以在序列化之前指定它的格式
`JSON.configWriterDateFormat("yyyy-MM-dd'T'HH:mm:ss");`

**Comment by zck573693104** [comment]
> toString()时才会进行序列化，序列化之前它的类型仍然是LocalDateTime，如果想序列化成这种格式 可以在序列化之前指定格式 比如 `JSON.configWriterDateFormat("yyyy-MM-dd'T'HH:mm:ss");`

tks，原来如此
