### ISSUE TITLE
[BUG]JSONPath不支持中划线

### ISSUE THREAD

**Issue by cloud-jie** [alibaba/fastjson2#2228]
### 问题描述
JSONPath不支持中划线

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：windows11]
 - JDK信息： [e.g.：jdk17]
 - 版本信息：[e.g.：Fastjson2 2.0.45]
 

### 重现步骤
![image](https://github.com/alibaba/fastjson2/assets/63632785/a2374b69-9afa-44fd-b490-827cef2f5ec4)
```java
JSONObject u = JSON.parseObject("{\"phone-Numbers\": \"XXX\"}");
        Map<String, Object> paths = JSONPath.paths(u);
        JSONPath.set(u,"$.phone-Numbers", "ccc");
```

### 期待的正确结果
json键”phone-Numbers“的值被正确设置为ccc

### 相关日志输出
Exception in thread "main" com.alibaba.fastjson2.JSONException: not support -
	at com.alibaba.fastjson2.JSONPathParser.parse(JSONPathParser.java:109)
	at com.alibaba.fastjson2.JSONPath.of(JSONPath.java:452)
	at com.alibaba.fastjson2.JSONPath.set(JSONPath.java:91)
	at org.example.demo.main(demo.java:17)

**Comment by wenshao** [comment]
```java
JSONObject u = JSON.parseObject("{\"phone-Numbers\": \"XXX\"}");
        Map<String, Object> paths = JSONPath.paths(u);
        JSONPath.set(u,"$['phone-Numbers']", "ccc");
```
换一种写法试试看？

**Comment by wenshao** [comment]
是的，我要修改paths的实现的

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.47-SNAPSHOT/
=========
帮忙用这个版本验证，这个版本paths返回有特别字符时，会使用['escaped-name']这种语法了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.47
问题已修复，请用新版本
