### ISSUE TITLE
[BUG]Dubbo Tri协议调用序列化报错

### ISSUE THREAD

**Issue by pigeon-fancier** [alibaba/fastjson2#2231]
详情请前往：https://github.com/apache/dubbo/issues/13733#issue-2116390973

**Comment by rowstop** [comment]
你这边先加上nullable临时解决一下

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.47-SNAPSHOT/
问题已修复，请帮忙用2.0.47-SNAPSHOT版本验证，2.0.47版本预计在2月底发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.47
问题已修复，请用新版本

**Comment by pigeon-fancier** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.47 问题已修复，请用新版本

fastjson2-kotlin还没有2.0.47版本，希望可以同步上，辛苦了

**Comment by pigeon-fancier** [comment]
https://github.com/apache/dubbo/issues/13733#issuecomment-1968571011

**Comment by pigeon-fancier** [comment]
> [apache/dubbo#13733 (comment)](https://github.com/apache/dubbo/issues/13733#issuecomment-1968571011)

@wenshao

**Comment by wenshao** [comment]
@pigeon-fancier 
https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2-kotlin/2.0.47/
