### ISSUE TITLE
[BUG]  版本2.0.46 引用类型、Boolean、Short 不支持JSONWriter.Feature.WriteNulls 

### ISSUE THREAD

**Issue by focuse8** [alibaba/fastjson2#2234]
### 问题描述
*简要描述您碰到的问题。*
序列化指定了JSONWriter.Feature.WriteNulls，对于Boolean、Short类型null没有正常序列号

fastjson2版本：2.0.46

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。
com.alibaba.fastjson2.writer.ObjectWriterCreatorASM#gwFieldValueJSONB
不同于Integer Long String Date，其它引用生成的字节码是com.alibaba.fastjson2.writer.ObjectWriterCreatorASM#gwFieldValueObjectJSONB。这里没有对JSONWriter.Feature.WriteNulls特性进行支持

**Comment by rowstop** [comment]
你的用法能发一下吗，使用了JSONB吗？

**Comment by rowstop** [comment]
没有复现，你能给个可复现 demo 吗
![image](https://github.com/alibaba/fastjson2/assets/100893704/4976867e-6875-4114-8bcc-d69476ef2bfc)

**Comment by focuse8** [comment]
> 没有复现，你能给个可复现 demo 吗 ![image](https://private-user-images.githubusercontent.com/100893704/302092147-ea026d89-b732-44c7-a65f-fdd73ddb70d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNjE1NDksIm5iZiI6MTcwNzA2MTI0OSwicGF0aCI6Ii8xMDA4OTM3MDQvMzAyMDkyMTQ3LWVhMDI2ZDg5LWI3MzItNDRjNy1hNjVmLWZkZDczZGRiNzBkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxNTQwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWVlZmY3YjJhMTI4Y2VkMTEyZDJkZGI0OWQ5NjFiMjhhYjIzZDdhNjZhOWZjZDkwZWU3ZDRjMzNmYzg2OWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zg8eHSHMaXb1Pq2R8hLrLPQpmvVpuawgZY9JG3LC2fc)

你给bool设一个默认值  numberShort一个默认值

**Comment by rowstop** [comment]
没复现
![image](https://github.com/alibaba/fastjson2/assets/100893704/0e9cb00f-efa8-4d98-ac93-1a9c35521b15)

**Comment by rowstop** [comment]
![image](https://github.com/alibaba/fastjson2/assets/100893704/5c5b0679-baa3-4e14-ab63-588815bdf6ad)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.47-SNAPSHOT/
问题已修复，请帮忙用2.0.47-SNAPSHOT版本验证，2.0.47版本预计在2月底发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.47
问题已修复，请用新版本
