### ISSUE TITLE
1.x升级到2.x出现的问题

### ISSUE THREAD

**Issue by shuohao** [alibaba/fastjson2#2259]
当使用了com.fasterxml.jackson.annotation.JsonIgnore注解后，fastjson 2.x里识别导致不输出。目前我这个项目是提供了sdk给其他应用，sdk里使用了fastjson，所以迁移到2.x之后引用我sdk的项目有的出现了问题，查阅了issues，发现目前的方案只能通过全局-D和fastjson2.properties，而这种方式对我这个需求来说不合适

需求建议：希望能增加方法级的设置，设置useJacksonAnnotation

**Comment by rowstop** [comment]
`com.alibaba.fastjson2.JSONFactory#setUseJacksonAnnotation`

**Comment by shuohao** [comment]
> `com.alibaba.fastjson2.JSONFactory#setUseJacksonAnnotation`

thanks
