### ISSUE TITLE
[BUG] kotlin jdk 21.0.2 情况下JSONWriter.Feature.WriteEnumsUsingName不生效

### ISSUE THREAD

**Issue by ganweiming** [alibaba/fastjson2#2276]
### 问题描述
*fastjson 2.0.47 , kotlin jdk 21.0.2 情况下JSONWriter.Feature.WriteEnumsUsingName不生效*
jdk 1.8情况下正常生效

### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：Openjdk 21.0.2]
 - 版本信息：[e.g.：Fastjson2 2.0.47
 

### 重现步骤
1. 定义枚举
enum class RegistrationStatusEnum {
    @JSONField(name = "Accepted")
    ACCEPTED,
    @JSONField(name = "Pending")
    PENDING,
    @JSONField(name = "Rejected")
    REJECTED
}

2. 输出枚举
println("Enum Result: " + RegistrationStatusEnum.PENDING.toJSONString(features = arrayOf(JSONWriter.Feature.WriteEnumsUsingName)))

3. 输出结果"PENDING"

### 期待的正确结果
jdk 1.8情况下会正常输出"Pending"
![企业微信截图_17090940529913](https://github.com/alibaba/fastjson2/assets/18005096/31f25631-553e-42ae-84ec-994bf8b9cb9a)
![企业微信截图_17090941021717](https://github.com/alibaba/fastjson2/assets/18005096/8d8e5edd-597e-4a7d-bb52-7b2340d24b38)
![企业微信截图_17090941082602](https://github.com/alibaba/fastjson2/assets/18005096/2bc069d1-8c0f-414b-bb4b-8e4f20922b02)

**Comment by rowstop** [comment]
这个 usingName 是指 Enum.name()

**Comment by ganweiming** [comment]
> 这个 usingName 是指 Enum.name()

但是WriteEnumsUsingName在jdk 1.8中会使用@JSONField中的name属性输出

**Comment by rowstop** [comment]
> > 这个 usingName 是指 Enum.name()
> 
> 但是WriteEnumsUsingName在jdk 1.8中会使用@JSONField中的name属性输出

🤔表现不一致?这是个问题

**Comment by ganweiming** [comment]
> > > 这个 usingName 是指 Enum.name()
> > 
> > 
> > 但是WriteEnumsUsingName在jdk 1.8中会使用@JSONField中的name属性输出
> 
> 🤔表现不一致?这是个问题

是的, 表现不一致才提出的issue

**Comment by wenshao** [comment]
```kotlin
  @Test
    fun test() {
        var str = JSON.toJSONString(Type.ACCEPTED, JSONWriter.Feature.WriteEnumsUsingName)
        assertEquals("\"Accepted\"", str)
        assertEquals(Type.ACCEPTED, JSON.parseObject(str, Type::class.java))
    }

    enum class Type {
        @JSONField(name = "Accepted")
        ACCEPTED,
        @JSONField(name = "Pending")
        PENDING,
        @JSONField(name = "Rejected")
        REJECTED
    }
```
问题没有重现啊

**Comment by ganweiming** [comment]
> ```kotlin
> var str = JSON.toJSONString(Type.ACCEPTED, JSONWriter.Feature.WriteEnumsUsingName)
> ```

jdk 17以上的版本打印输出的为"ACCEPTED", 预期输出为"Accepted"

**Comment by wenshao** [comment]
我测试过JDK 17也是对的啊

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.49-SNAPSHOT/
问题已修复，请帮忙用2.0.49-SNAPSHOT验证，2.0.49版本预计在月底发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.49
问题已修复，请用新版本
