### ISSUE TITLE
[BUG] BigDecimal 0.123456789012345678 在 JSONWriter.Feature.BrowserCompatible 下不是输出字符串

### ISSUE THREAD

**Issue by jaconliang** [alibaba/fastjson2#2283]
### 问题描述
数字0.123456789012345678在JavaScript不能精确表达，但是BigDecimal 0.123456789012345678 在 JSONWriter.Feature.BrowserCompatible 下不是输出字符串而是直接输出数字。

### 环境信息
*请填写以下信息：*

 - 版本信息：Fastjson2 2.0.47
 

### 重现步骤
下面代码输出结果是：{"num":0.123456789012345678}，期望的结果是：{"num":"0.123456789012345678"}
```java
        BigDecimal num = new BigDecimal("0.123456789012345678");
        JSONObject jsonObj = new JSONObject();
        jsonObj.put("num", num);
        System.out.println(jsonObj.toString(JSONWriter.Feature.BrowserCompatible));
```

### 期待的正确结果
期望正确输出：{"num":"0.123456789012345678"}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/
问题已修复，请帮忙用2.0.48-SNAPSHOT版本帮忙验证，2.0.48版本预计在3月底前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
