### ISSUE TITLE
[BUG] Spring6版的FastJsonHttpMessageConverter存在问题，导致请求头不返回Content-Length

### ISSUE THREAD

**Issue by 451973663** [alibaba/fastjson2#2284]
`extension-spring6` 中的 `FastJsonHttpMessageConverter` 存在问题，会导致返回的请求头中无 `Content-Length` 字段
查了一下，该问题已经在 `extension-spring5` 中修复，麻烦修复更新一下 `extension-spring6` ，辛苦！感谢！

`extension-spring6`  `FastJsonHttpMessageConverter` 已知问题位置：
![extension-spring6 BUG位置](https://github.com/alibaba/fastjson2/assets/49486614/22d4b2af-2802-41c9-975d-e4243e5e6181)

`extension-spring5`  `FastJsonHttpMessageConverter` 已知问题修复：
![extension-spring5 问题已修复](https://github.com/alibaba/fastjson2/assets/49486614/f8f030c7-7c51-406e-a34c-cdc9eb1c0d57)

**Comment by VictorZeng** [comment]
@451973663 感谢提出的issue，这个地方确实有问题，是否可以帮忙贡献修复一下~

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/
请帮忙用2.0.48-SNAPSHOT版本帮忙验证，2.0.48版本预计在3月底前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
