### ISSUE TITLE
需要通过JEP 417 Java Vector API支持更快的json解析

### ISSUE THREAD

**Issue by zhugf** [alibaba/fastjson2#2290]
### 请描述您的需求或者改进建议
simd-json使用avx2指令实现了超快速的json解析, jdk21有了vector api, 
建议在新的fastjson库中同时支持类似技术, 加快json解析.

### 请描述你建议的实现方案
参见: simdjson-java项目: https://github.com/simdjson/simdjson-java

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/tree/main/incubator-vector/src/main/java/com/alibaba/fastjson2
现在就有使用Vector API优化的实现，simdjson-java的API看起来不是可用的，我还没有在一个可用的比较场景中证明simdjson-java更快。

**Comment by gubaojian** [comment]
官网上说比 fastjson2还快： https://github.com/simdjson/simdjson-java
