### ISSUE TITLE
[BUG] class java.util.HashSet cannot be cast to class java.util.List

### ISSUE THREAD

**Issue by rongmome** [alibaba/fastjson2#2302]
### 问题描述

Caused by: java.lang.ClassCastException: class java.util.HashSet cannot be cast to class java.util.List (java.util.HashSet and java.util.List are in module java.base of loader 'bootstrap')
	at com.alibaba.fastjson2.reader.FieldReaderList.readFieldValue(FieldReaderList.java:100)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:390)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:515)

### 环境信息
 - OS信息： 
 - JDK信息： jdk-21
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.47</version>
        </dependency>
 

### 重现步骤
运行下面代码
```java
import com.alibaba.fastjson.JSON;
import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;

public class Test {

    public static void main(String[] args) {
        TestA a = new TestA();
        a.areaIds.add(1000);
        String jsonStr = JSON.toJSONString(a);
        System.out.println(jsonStr); // {"areaIds":[1000]}
        JSON.parseObject(jsonStr, TestA.class);
    }

    public static class TestA {
        public Set<Integer> areaIds = new HashSet<>();
        transient public AtomicBoolean supplying = new AtomicBoolean(false);
    }
}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/
问题已修复，请帮忙用2.0.48-SNAPSHOT版本帮忙验证，2.0.48版本预计在3月底前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
