### ISSUE TITLE
枚举类型自定义反序列化，调用readObejct时传入targetClass，用于反序列化具体的枚举[FEATURE]

### ISSUE THREAD

**Issue by ljj18** [alibaba/fastjson2#2329]
### 请描述您的需求或者改进建议
枚举类型自定义反序列化，调用readObejct时传入targetClass，用于反序列化具体的枚举

### 请描述你建议的实现方案
com.alibaba.fastjson2.util.TypeUtils.cast方法（第1501行）
原代码：
return (T) objectReader.readObject(jsonReader, null, null, 0);
建议改为：
return (T) objectReader.readObject(jsonReader, targetClass, null, 0);
这样就可以具体的枚举

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
版本： V2.0.46
反序列化是采用JSONType注解到枚举类
@JSONType(serializer = DictSerializer.class, deserializer = DictDeserializer.class, writeEnumAsJavaBean = true)
public enum AuthStrengthType implements IDict

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/
问题已修复，请帮忙用2.0.48-SNAPSHOT版本帮忙验证，2.0.48版本预计在3月底前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本

**Comment by ljj18** [comment]
已测试，功能已实现
