### ISSUE TITLE
[QUESTION] JSON.parse后，1.2.83版本没问题，2.0.47报错

### ISSUE THREAD

**Issue by 1029219814** [alibaba/fastjson2#2334]
对于字符串。"\"{\\\"data\\\":{\\\"signature\\\":\\\"xxx\\\",\\\"payment\\\":{\\\"to\\\":\\\"xxx\\\",\\\"from\\\":\\\"xxx\\\",\\\"fee\\\":\\\"200000000\\\",\\\"token\\\":\\\"1\\\",\\\"nonce\\\":\\\"0\\\",\\\"memo\\\":\\\"\\\",\\\"amount\\\":\\\"0\\\",\\\"valid_until\\\":\\\"0\\\"},\\\"stake_delegation\\\":null,\\\"create_token\\\":null,\\\"create_token_account\\\":null,\\\"mint_tokens\\\":null}}\""

  ```
 public static void main(String[] args) {
        String rawTx = "\"{\\\"data\\\":{\\\"signature\\\":\\\"xxx\\\",\\\"payment\\\":{\\\"to\\\":\\\"xxx\\\",\\\"from\\\":\\\"xxx\\\",\\\"fee\\\":\\\"200000000\\\",\\\"token\\\":\\\"1\\\",\\\"nonce\\\":\\\"0\\\",\\\"memo\\\":\\\"\\\",\\\"amount\\\":\\\"0\\\",\\\"valid_until\\\":\\\"0\\\"},\\\"stake_delegation\\\":null,\\\"create_token\\\":null,\\\"create_token_account\\\":null,\\\"mint_tokens\\\":null}}\"";
        JSONObject signedTx = JSONObject.parseObject(JSONObject.parse(rawTx).toString());
        System.err.println(signedTx);
    }
```

1.2.83可以正常解析，但是2.0.47报Exception in thread "main" com.alibaba.fastjson2.JSONException: offset 541, character , line 1, column 541, fastjson-version 2.0.47 错误。这是预期的错误吗？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/ 问题已修复，请帮忙用2.0.48-SNAPSHOT验证，2.0.48正式版本预计在月末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
