### ISSUE TITLE
[QUESTION]fastjson2 解析Gson的@SerializedName 有开关关闭吗

### ISSUE THREAD

**Issue by JadeSpring** [alibaba/fastjson2#2346]
项目中有使用Gson的@SerializedName 注解的字段，在使用fastjson转json时不希望使用@SerializedName 注解的字段名

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/ 

请帮忙用2.0.48-SNAPSHOT验证，2.0.48正式版本预计在月末发布

在2.0.48-SNAPSHOT中，可以通过JVM启动参数关闭Gson Annoation的解析，比如：
```
-Dfastjson2.useGsonAnnotation=false
```

又或者在classpath中加上fastjson2.properties文件，并在文件里加上如下内容：
```
fastjson2.useGsonAnnotation=false
```

**Comment by JadeSpring** [comment]
我这边是使用
<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>2.0.45</version>
            </dependency>
            兼容版本有吗

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本

**Comment by wenshao** [comment]
com.alibaba
fastjson
2.0.48
也可以用这个版本
