### ISSUE TITLE
[BUG]关于jsonDirect=true报错

### ISSUE THREAD

**Issue by fy287216637** [alibaba/fastjson2#2347]
### 问题描述
*当某个字段设置了jsonDirect=true,能否为null的时候调用JSON.toJsonString不报错*

@Getter
@Setter
public class TestJson2 {

    private String name;

    @JSONField(jsonDirect = true)
    private String jsonStr;

}

public static void main(String[] args) {
        TestJson2 testJson2 = new TestJson2();
        testJson2.setName("测试");
        System.out.println(JSON.toJSONString(testJson2));
    }

当jsonStr为null的时候报错：
![image](https://github.com/alibaba/fastjson2/assets/29773167/04338b08-2cc3-4cea-9142-673c76b877d4)

期望输出结果为：{"jsonStr":null,"name":"测试"}

**Comment by wenshao** [comment]
什么版本？问题没重现哦

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
