### ISSUE TITLE
[BUG],序列化再反序列化，重复引用的对象不能正确反序列化

### ISSUE THREAD

**Issue by jiao-jia-nan** [alibaba/fastjson2#2348]
### 问题描述
*序列化再反序列化，重复引用的对象不能正确反序列化。*

### 环境信息

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：adopt-openjdk-11.0.9]
 - 版本信息：[e.g.：Fastjson2 2.0.47]
 

### 重现步骤

```java
        ArrayList<Object> items = new ArrayList<>();
        HashMap<Object, Object> item = new HashMap<>();
        item.put("data","data");
        items.add(item);
        items.add(item);
        List<HashMap> newItems = JSONArray.parseArray(JSONArray.toJSONString(items),HashMap.class);
```

### 期待的正确结果

newItems ，有两个item

**Comment by wenshao** [comment]
能提供更详细能直接重现问题的代码么？

**Comment by JavaSynchronized** [comment]
已更新重现步骤

**Comment by rowstop** [comment]
没复现
![image](https://github.com/alibaba/fastjson2/assets/100893704/92c16e23-c291-42c6-8c25-f0a29215a7b1)

**Comment by JavaSynchronized** [comment]
![Uploading 微信图片_20240326164144.png…]()

**Comment by JavaSynchronized** [comment]
![2](https://github.com/alibaba/fastjson2/assets/34121123/8e877605-ba49-4c35-b4b8-3e7ca51d18ec)

**Comment by JavaSynchronized** [comment]
![image](https://github.com/alibaba/fastjson2/assets/34121123/c54c1548-87d6-4ad0-ab13-c4207fffbdfb)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.49
问题已修复，请用新版本
