### ISSUE TITLE
[BUG],SupportSmartMatch全局配置无效

### ISSUE THREAD

**Issue by xuzhe521** [alibaba/fastjson2#2349]
问题描述
SupportSmartMatch全局配置无效

环境信息
OS信息： win11
JDK信息：jdk17
版本信息：Fastjson2 2.0.46    springboot3.2.0
重现步骤：
![image](https://github.com/alibaba/fastjson2/assets/35841999/ce20d1ab-15a5-4a36-9085-ff8f22504b0d)
在启动类加全局配置开启SupportSmartMatch，
jsonArray.toJavaList(obj.class)反序列化会使大量字段值为null 
![image](https://github.com/alibaba/fastjson2/assets/35841999/010a6e93-6568-4467-b85e-b65c5146d8eb)

需使用jsonArray.toJavaList(obj.class, JSONReader.Feature.SupportSmartMatch)才能正常反序列化
![image](https://github.com/alibaba/fastjson2/assets/35841999/dc315eb5-6263-442e-907f-4c269d3a4d6c)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.48-SNAPSHOT/ 问题已修复，请帮忙用2.0.48-SNAPSHOT验证，2.0.48正式版本预计在月末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.48
请用新版本
