### ISSUE TITLE
[BUG]2.0.2 getjsonobject报错

### ISSUE THREAD

**Issue by cjdxhjj** [alibaba/fastjson2#236]
### 问题描述
*简要描述您碰到的问题。*
当json里不存在指定的键时，报错
![image](https://user-images.githubusercontent.com/5616997/168229180-aea51f6d-e2aa-44c1-a563-ef40bb1753a8.png)

![image](https://user-images.githubusercontent.com/5616997/168229063-55299b07-5fbe-4e2c-b5e3-94c203009647.png)
### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
null

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wsxe9988** [comment]
@cjdxhjj 根据您反馈的，我做了一个tesatcase 没有抛出异常，直接返回了null,
<dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.3-SNAPSHOT</version>
        </dependency>

你可以依赖最新的快照版试下

**Comment by wenshao** [comment]
2.0.2是有问题的，2.0.3已经修复，预计周末发布，到时候通知你
