### ISSUE TITLE
[QUESTION] Controller 接口使用 @RequestBody JSONObject requestBody封装json嵌套问题

### ISSUE THREAD

**Issue by xiaobaibi** [alibaba/fastjson2#237]
Request:
`
{
    "name":"alice",
    "age":"11",
    "xxx":{
        "aa":"aaValue"
        "bb":"bbValue"
     }
}
`
Controller
`
public JSONObject weChatPayResponseV3(@RequestBody JSONObject requestBody){
    requestBody.getJSONObject("xxx")    报错 ---> java.util.LinkedHashMap cannot be cast to com.alibaba.fastjson2.JSONObject
} 
`
Q: 版本1中使用JSONObject直接 pase,现在需要使用JSON进行pase 
导致Spring的封装出现问题,这要怎么解啊

**Comment by VictorZeng** [comment]
@xiaobaibi  根据您的描述，我做了一下testcase，未发现问题呀，您可以试用一下2.0.3-SNAPSHOT版本。

**Comment by xiaobaibi** [comment]
这个版本   我们拿不到啊
![image](https://user-images.githubusercontent.com/47133955/168235702-dd25bce7-e863-473b-82e5-38c78bcd6ec9.png)

**Comment by VictorZeng** [comment]
@xiaobaibi 这个是快照版本，直接依赖就行
```xml
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.3-SNAPSHOT</version>
        </dependency>
```

**Comment by wenshao** [comment]
2.0.3 已经发布，请使用新版本 https://github.com/alibaba/fastjson2/releases/tag/2.0.3
