### ISSUE TITLE
fastjson2如何禁用特殊key检查

### ISSUE THREAD

**Issue by chenxiang-coder** [alibaba/fastjson2#2372]
### fastjson2如何禁用特殊key检查
*在fastjson版本parse方法可以禁用特殊key检查，例如：
JSONObject.parseObject(response, Feature.DisableSpecialKeyDetect)
那么在在fastjson2里面如何支持？*

**Comment by wenshao** [comment]
在fastjson2中，缺省就是DisableSpecialKeyDetect，不用单独配置

**Comment by chenxiang-coder** [comment]
> 在fastjson2中，缺省就是DisableSpecialKeyDetect，不用单独配置

测试后发现确实是默认的，谢谢回答！
