### ISSUE TITLE
[BUG]@JSONType(serializeFeatures = JSONWriter.Feature.WriteNonStringValueAsString)对于List<Long> 类型的属性序列化时不生效

### ISSUE THREAD

**Issue by Bruce-Lin318** [alibaba/fastjson2#2431]
### 问题描述

@JSONType(serializeFeatures = JSONWriter.Feature.WriteNonStringValueAsString)对于List<Long> 类型的属性序列化时不生效
对于非字符串类型的数据可以正常序列化为字符串，但是List<Long>类型解析后，数组内仍为数字类型。
如果不适用@JSONType，而是使用JSON.toJSONString(obj, JSONWriter.Feature.WriteNonStringValueAsString)则无此问题

### 环境信息

 - OS信息： Win11
 - JDK信息：jdk 17.0.8.7.1
 - 版本信息：Fastjson2 2.0.41

### 重现步骤

1. 实体类上增加@JSONType(serializeFeatures = JSONWriter.Feature.WriteNonStringValueAsString)

2. 接口给前端返参时，Long id 的属性可以按照预期展示为字符类型，List<Long> ids 序列化后，数组内仍为数字类型

   

```java
    @Data
    @JSONType(serializeFeatures = JSONWriter.Feature.WriteNonStringValueAsString)
    public static class TestClass {
        private Long id;

        private List<Long> ids;
    }

    @Test
    public void testJson() {
        TestClass testClass = new TestClass();
        testClass.setId(1L);
        testClass.setIds(List.of(1L, 2L));
        System.out.println(JSON.toJSONString(testClass));
    }
```

### 期待的正确结果

期待的正确结果为：

```json
{"id":"1","ids":["1","2"]}
```

现在的结果为：

```json
{"id":"1","ids":[1,2]}
```

#### 附加信息

如果不适用@JSONType, 序列化时指定JSONWriter.Feature.WriteNonStringValueAsString，可以实现预期效果，所以猜测是对于List类型解析时注解未生效（@JSONField与@JSONType均测试过，效果相同）

```java
    @Data
    public static class TestClass {
        private Long id;

        private List<Long> ids;
    }

    @Test
    public void testJson() {
        TestClass testClass = new TestClass();
        testClass.setId(1L);
        testClass.setIds(List.of(1L, 2L));
        System.out.println(JSON.toJSONString(testClass, JSONWriter.Feature.WriteNonStringValueAsString));
    }
```

打印结果：

```json
{"id":"1","ids":["1","2"]}
```

**Comment by jsontype** [comment]
我想咨询一下有关安全的问题。 @带有jsontype的邮件好像被发送到外部(我)。

***@***.*** 。 因为是个人电子邮件，所以我认为最好防止邮件发到这边的问题。 请多多关照。

2024년 4월 12일 (금) 오전 10:27, Bruce-Lin318 ***@***.***>님이 작성:

**Comment by Bruce-Lin318** [comment]
> 我想咨询一下有关安全的问题。 @带有jsontype的邮件好像被发送到外部(我)。 ***@***.*** 。 因为是个人电子邮件，所以我认为最好防止邮件发到这边的问题。 请多多关照。 2024년 4월 12일 (금) 오전 10:27, Bruce-Lin318 ***@***.***>님이 작성:

不好意思！之前确实没注意到这个事情，之后会注意的，对带来的不便给您道歉。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.49
问题已修复，请帮忙用新版本验证
