### ISSUE TITLE
分页查询 pageSize>=1000 序列化出错，结果集也没超过1000

### ISSUE THREAD

**Issue by sun99413** [alibaba/fastjson2#2433]
### 问题描述

![image](https://github.com/alibaba/fastjson2/assets/21192535/42a1b718-b7d0-48c7-8253-b842aec7d792)
![image](https://github.com/alibaba/fastjson2/assets/21192535/776ebdc6-03cc-4731-a151-f86b39b8c148)

**Comment by sun99413** [comment]
![image](https://github.com/alibaba/fastjson2/assets/21192535/f98bd7e8-3100-4455-a6f3-7a27127a091c)

**Comment by yanxutao89** [comment]
方便提供简单的复现代码示例吗

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.49-SNAPSHOT/
问题已经修复，请帮忙用2.0.49-SNAPSHOT版本验证，2.0.49版本预计在本周末（4月14日）前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.49
问题已修复，请帮忙用新版本验证
