### ISSUE TITLE
[FEATURE]能否增加一个方法：JavaBean直接一步转换为JsonObject

### ISSUE THREAD

**Issue by fy287216637** [alibaba/fastjson2#2445]
*没有找到方法，可以直接将JavaBean转换为JsonObject*

貌似目前想把一个Java对象转换为JsonObject只能先将对象转换为JsonString，然后再将JsonString变为JsonObject。。。

我不知道是否为底层限制还是说需求小众的原因哈，我个人希望能有一个方法直接将Java对象转换为JsonObject，而不是导过来导过去

@wenshao  辛苦看下这个是否可行，还是我没有找到对应的方法。感谢~

**Comment by wenshao** [comment]
JSONObject jsonObject = (JSONObject) JSON.toJSON(javaBean);

**Comment by fy287216637** [comment]
> JSONObject jsonObject = (JSONObject) JSON.toJSON(javaBean);

哈哈  好一个强转~   感谢回复

**Comment by rowstop** [comment]
> > JSONObject jsonObject = (JSONObject) JSON.toJSON(javaBean);
> 
> 哈哈 好一个强转~ 感谢回复

com.alibaba.fastjson2.JSONObject#from(java.lang.Object)
