### ISSUE TITLE
fastjson2 序列化兼容问题

### ISSUE THREAD

**Issue by bodhili** [alibaba/fastjson2#2446]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

fastjson2 序列化 java.time.Period，
`Period period = Period.ofDays(2)`
如何兼容fastjson，输出为“P2D”这种形式

重现方式： `String json = JSON.toJSONString(period);`
问题：fastjson 和 fastjson2输出结果不一致， 如何让fastjson2 与 fastjson输出结果一致 ？

上述序列化方式：fastjson 会调用 Period toString 方法，而 fastjson2 不会

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
已经支持，请帮忙用2.0.50-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本
