### ISSUE TITLE
[BUG] Serialization to byte[] / Deserialization to class ruins field ordering

### ISSUE THREAD

**Issue by ender1214** [alibaba/fastjson2#2448]
I apologize, I can't write in Chinese.

As the title says, fastjson2 overrides and imposes what seems to be an alphabetical / lexicographical ordering of field names. It seems to also not respect if the data type of the field enforces insertion order (LinkedHashMap, LinkedHashSet).

If this an override on the part of fastjson2, is there a way to disable it? Honestly, it seems too strong an opinion for a library to make and should only be optional and be disabled by default.

**Comment by yanxutao89** [comment]
Can you provide such a demo?

**Comment by wenshao** [comment]
You can configure JSONType#alphabetic=false through Annotation to avoid serialized output sorting. But this sorting depends on the behavior of the compiler, which is not completely certain.

```java
    @Test
    public void test() {
        Bean bean = new Bean();
        bean.a1 = 1;
        bean.a2 = 2;
        bean.a3 = 3;
        String json = JSON.toJSONString(bean);
        System.out.println(json);
    }

    @JSONType(alphabetic = false)
    public static class Bean {
        public int a2;
        public int a1;
        public int a3;
    }
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/

Global configuration of ordering has been supported. Please help to verify with version 2.0.50-SNAPSHOT, as follows:

```java
 @Test
    public void test() {
       JSONFactory.setDefaultWriterAlphabetic(true); // global config

        Bean bean = new Bean();
        bean.a1 = 1;
        bean.a2 = 2;
        bean.a3 = 3;
        String json = JSON.toJSONString(bean);
        System.out.println(json);
    }

    @JSONType(alphabetic = false)
    public static class Bean {
        public int a2;
        public int a1;
        public int a3;
    }
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50 has been released, please use the new version

**Comment by hks2002** [comment]
我的环境，这个设置不起作用，无效。输出的json字段还是排过序的，和model里定义的字段顺序不一样。

**Comment by hks2002** [comment]
默认排序这个设置，个人觉得不好，使得和其他库不兼容，想迁移过来就会发生问题。

**Comment by lottoHelious** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.50 2.0.50 has been released, please use the new version

JSONFactory.setDefaultWriterAlphabetic(false);
System.out.println(JSONFactory.isDefaultWriterAlphabetic());
System.out.println(JSONFactory.getDefaultObjectWriterProvider().isAlphabetic());//实际未生效

@JSONType(alphabetic = false)注解是起作用的
JSONFactory.setDefaultWriterAlphabetic(false)配置不起作用
希望修复谢谢

**Comment by jujn** [comment]
> > https://github.com/alibaba/fastjson2/releases/tag/2.0.50 2.0.50 has been released, please use the new version
> 
> JSONFactory.setDefaultWriterAlphabetic(false); System.out.println(JSONFactory.isDefaultWriterAlphabetic()); System.out.println(JSONFactory.getDefaultObjectWriterProvider().isAlphabetic());//实际未生效
> 
> [@jsontype](https://github.com/jsontype)(alphabetic = false)注解是起作用的 JSONFactory.setDefaultWriterAlphabetic(false)配置不起作用 希望修复谢谢

已收到反馈

**Comment by jujn** [comment]
> > https://github.com/alibaba/fastjson2/releases/tag/2.0.50 2.0.50 has been released, please use the new version
> 
> JSONFactory.setDefaultWriterAlphabetic(false); System.out.println(JSONFactory.isDefaultWriterAlphabetic()); System.out.println(JSONFactory.getDefaultObjectWriterProvider().isAlphabetic());//实际未生效
> 
> [@jsontype](https://github.com/jsontype)(alphabetic = false)注解是起作用的 JSONFactory.setDefaultWriterAlphabetic(false)配置不起作用 希望修复谢谢

问题已修复，可以等下个版本发布时帮忙验证
