### ISSUE TITLE
[QUESTION]1.2.83升级至2.0.49后，JSONSerializer代码不兼容

### ISSUE THREAD

**Issue by lbhkobe** [alibaba/fastjson2#2450]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
由于1.2.83安全性问题，升级至2.x版本，但是老代码中调用的JSONSerializer.containsReference、writeReference、println、incrementIdent、decrementIdent方法全部被删除了，希望能有替代方案
![image](https://github.com/alibaba/fastjson2/assets/38060554/89b7c0fd-6f94-4af8-a02b-090c4b385150)
![image](https://github.com/alibaba/fastjson2/assets/38060554/d52f5cf5-95ad-4e77-907f-b8948af24a02)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
已经支持，请帮忙用2.0.50-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
已经支持，请帮忙用2.0.50-SNAPSHOT版本验证

**Comment by lbhkobe** [comment]
@wenshao 您好，在com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT中未能找到JSONSerializer这个类，现在项目引的pom是<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.49</version>
        </dependency>，代码和底层框架中的路径都是com.alibaba.fastjson, 无法升级至fastjson2
![image](https://github.com/alibaba/fastjson2/assets/38060554/036817bd-e5d5-4fbc-b2f0-8e35aa8d907a)
![image](https://github.com/alibaba/fastjson2/assets/38060554/6ee7d28f-023f-4967-93e3-8b014d7a5676)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.50-SNAPSHOT/
抱歉，我搞错了，你依赖下这个兼容包

**Comment by lbhkobe** [comment]
@wenshao 您好，已经验证，目前还有JSONSerializer.setContext(Serializer parent,Object object,Object fieldName,int features)方法和SerializerWriter.append(CharSequence csq)这两个方法被删除了
![image](https://github.com/alibaba/fastjson2/assets/38060554/fc9ae680-87b9-47ea-9242-c46cf68defb0)
![image](https://github.com/alibaba/fastjson2/assets/38060554/4120f2b2-9292-448c-bd1f-c4b4f3f621f9)
![image](https://github.com/alibaba/fastjson2/assets/38060554/6cf519a5-bac9-4b0c-bdf2-3305d7001a77)

**Comment by wenshao** [comment]
自定义序列化类的完整代码可以发出来么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
已经支持，请帮忙更新2.0.50-SNAPSHOT版本验证

**Comment by lbhkobe** [comment]
@wenshao 您好，之前使用https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.50-SNAPSHOT/这个地址进行验证的，我们这边的老项目无法引用com.alibaba.fastjson2这个group的包

**Comment by lbhkobe** [comment]
@wenshao 您好，自定义序列化类如下
[自定义序列化类-1713749766935.txt](https://github.com/alibaba/fastjson2/files/15056207/-1713749766935.txt)

**Comment by lbhkobe** [comment]
@wenshao 您好 有时间修复一下吧 谢谢~

**Comment by wenshao** [comment]
@lbhkobe 计划在5.1期间处理哈

**Comment by lbhkobe** [comment]
期待ing

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请帮忙用新版本验证

**Comment by lbhkobe** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.50 2.0.50已发布，请帮忙用新版本验证

好的
