### ISSUE TITLE
[BUG]hutool中CaseInsensitiveMap、CaseInsensitiveLinkedMap等相关的map类型序列化问题

### ISSUE THREAD

**Issue by 1195952223** [alibaba/fastjson2#2458]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.49]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
    public static void main(String[] args) {
        Map m2 = new CaseInsensitiveLinkedMap();
        m2.put("a", "V");
        System.out.println(JSON.toJSONString(m2, JSONWriter.Feature.FieldBased, JSONWriter.Feature.WriteNullStringAsEmpty));
        System.out.println(JSON.toJSONString(m2, JSONWriter.Feature.WriteNullStringAsEmpty));

    }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
2种序列化结果一致

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
{"raw":{"a":"V"}}
{"a":"V"}

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
已经支持，请帮忙用2.0.50-SNAPSHOT版本验证

**Comment by 1195952223** [comment]
还有其他的类型 还有就是我继承的类 现在这种方式还是不行
![image](https://github.com/alibaba/fastjson2/assets/35017668/ec113556-0b64-47c8-b74c-e59d1bdae0fd)
![image](https://github.com/alibaba/fastjson2/assets/35017668/41e66018-ab12-4a00-afda-4f7152bb1a0f)

**Comment by 1195952223** [comment]
Map.class.isAssignableFrom(objectClass) 这种方式是否可行

**Comment by wenshao** [comment]
有些Map的实现的字段不能忽略的，不可行

**Comment by 1195952223** [comment]
好的 能在类上通过加注解或者其他方式解决吗

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本
