### ISSUE TITLE
[BUG]序列化Set<Date>类型的数据异常，导致解析报错

### ISSUE THREAD

**Issue by ybbwk** [alibaba/fastjson2#2475]
### 问题描述
使用GenericFastJsonRedisSerializer或者JSON.toJSONString方法序列化到Redis，对象中存在Set<Date>类型的字段，序列化到Redis的数据为“Set[new Date(xxxxxxxxxxxxxxx)]”，当从Redis反序列化到对象的时候，报错“string length only support string input”。将Set<Date>类型改为List<Date>则能正确的序列化并可正确反序列化

### 环境信息
 - OS信息：  Windows 11、Ubuntu
 - JDK信息： Openjdk 17
 - 版本信息：Fastjson2 2.0.49

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
请帮忙用2.0.50-SNAPSHOT版本验证

**Comment by ybbwk** [comment]
使用2.0.50-SNAPSHOT可正常解析，不报错。序列化后的JSON字符串没有变化，List和Set的解析结果不一致（Set带类名，List不带类名），不知是否有意为之。

附测试代码


    public static void testFastJson2SetDate() {
        FastJsonConfig config = new FastJsonConfig();
        config.setReaderFeatures(JSONReader.Feature.SupportAutoType);
        config.setWriterFeatures(JSONWriter.Feature.WriteClassName);

        Set<Date> dateSet = new HashSet<>();
        dateSet.add(new Date());

        List<Date> dateList = new ArrayList<>();
        dateList.add(new Date());

        TestDto testDto = new TestDto();
        testDto.setId(UUID.fastUUID().toString());
        testDto.setCollSetDate(dateSet);
        testDto.setCollListDate(dateList);
        System.out.println("TestDto: " + testDto);

        String jsonString = JSON.toJSONString(testDto, config.getWriterFeatures());
        System.out.println("JsonString: " + jsonString);

        Object json = JSON.parseObject(jsonString, Object.class, config.getReaderFeatures());
        System.out.println("Json: " + json);
    }

    @Data
    static class TestDto {
        private String id;

        private Set<Date> collSetDate;

        private List<Date> collListDate;
    }



输出结果
`
TestDto: FastJson2Test.TestDto(id=5466fe74-8cd9-4f58-86e6-f98e8f93df3e, collSetDate=[Sun Apr 28 09:14:12 CST 2024], collListDate=[Sun Apr 28 09:14:12 CST 2024])
JsonString: {"@type":"com.ruoyi.FastJson2Test$TestDto","collListDate":["2024-04-28 09:14:12.768"],"collSetDate":Set[new Date(1714266852768)],"id":"5466fe74-8cd9-4f58-86e6-f98e8f93df3e"}
Json: FastJson2Test.TestDto(id=5466fe74-8cd9-4f58-86e6-f98e8f93df3e, collSetDate=[Sun Apr 28 09:14:12 CST 2024], collListDate=[Sun Apr 28 09:14:12 CST 2024])
`

**Comment by wenshao** [comment]
Set带类名设计就是这样的

https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本

**Comment by martin-1120** [comment]
2.0.59还是有问题:

含有set的bean 序列化成json string 变成了这样 :

<img width="1057" height="564" alt="Image" src="https://github.com/user-attachments/assets/ce8e6d4f-7569-4fad-ae4e-136b9bba600e" />
测试代码:
`import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;

import lombok.Data;


@Data
public class Test {
	private Set<String> perms;
	public static void main(String[] args)   {
		Test t= new Test();
		t.setPerms(new HashSet<>(List.of("da")));
		String str = JSON.toJSONString(t,JSONWriter.Feature.WriteClassName);
		System.out.println(str);
		
		
	}


}`
