### ISSUE TITLE
使用兼容包的JSONPath.read读取json对象,内部同时存在com.alibaba.fastjson2.JSONObject和com.alibaba.fastjson.JSONObject对象

### ISSUE THREAD

**Issue by Vinke2** [alibaba/fastjson2#2476]
你好,我曾经在 https://github.com/alibaba/fastjson2/issues/1922  反馈过类似问题,现在我在最新2.0.49版本的兼容包上面又遇到了这个问题:
```java
List array = (List) JSONPath.read("{\n" +
" "data": [\n" +
" {\n" +
" "id": 7315635187420579130\n" +
" },\n" +
" {\n" +
" "id": 7315635187420579130\n" +
" }\n" +
" ]\n" +
"}", "data");
for (JSONObject jsonObject : array) {
System.out.println(jsonObject.get("id"));
}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.50-SNAPSHOT/
问题已修复，请帮忙用2.0.50-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本
