### ISSUE TITLE
[BUG]Fastjson v1兼容模块会将LocalDate、LocalDateTime序列化为时间戳格式

### ISSUE THREAD

**Issue by johnshawn-david** [alibaba/fastjson2#2477]
### 问题描述
Fastjson v1兼容模块会将LocalDate、LocalDateTime序列化为时间戳格式

### 重现步骤
```java
public void jsonTest() {
      Map<String, Object> map = new HashMap<>();
      map.put("startDate", LocalDate.now());
      map.put("endDate", LocalDate.now().plusMonths(1));
      System.out.println(JSON.toJSONString(map));
  }
```

### 相关日志输出
{"endDate":1716393600000,"startDate":1713801600000}

**Comment by wenshao** [comment]
https://repo1.maven.org/maven2/com/alibaba/fastjson/2.0.50/
问题已修复，请用新版本

**Comment by wujie6166** [comment]
这个问题在 [2.0.51](https://github.com/alibaba/fastjson2/milestone/51), [2.0.50](https://github.com/alibaba/fastjson2/milestone/50)  上好像依然存在

**Comment by wujie6166** [comment]
![image](https://github.com/user-attachments/assets/a9b89178-d487-4c92-ac53-8f6810dc330e)
@wenshao  已经是2.0.51 版本了 依然 序列化为时间戳格式
