### ISSUE TITLE
[FEATURE] 支持jsr367和jsr374标准

### ISSUE THREAD

**Issue by xiaoma20082008** [alibaba/fastjson2#2479]
### 请描述您的需求或者改进建议
*是否考虑支持jsr标准*
[JSR 367: JavaTM API for JSON Binding (JSON-B)](https://jcp.org/en/jsr/detail?id=367)
[JSR 374: JavaTM API for JSON Processing 1.1](https://jcp.org/en/jsr/detail?id=374)

### 请描述你建议的实现方案

1. 实现json binding api
2. 实现json processing api

### 描述您考虑过的替代方案
*当前可以使用*
[johnzon](https://johnzon.apache.org/)

**Comment by wenshao** [comment]
没什么人用这两个JSR吧

**Comment by xiaoma20082008** [comment]
> 没什么人用这两个JSR吧

确实用的少，jackson也只提供了数据读取的 [jakarta-jsonp](https://github.com/FasterXML/jackson-datatypes-misc/tree/2.18/jakarta-jsonp)

**Comment by wenshao** [comment]
没计划，这种没人用的标准，支持了只会增加代码的后期维护工作量

**Comment by xiaoma20082008** [comment]
> 没计划，这种没人用的标准，支持了只会增加代码的后期维护工作量

好的，那我关掉了
