### ISSUE TITLE
[BUG] java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Sunx6** [alibaba/fastjson2#2484]
### 问题描述
转成jsonstring时 数组下标越界

### 环境信息
*请填写以下信息：*

 - 版本信息：Fastjson2 2.0.49]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSON.toJSONString` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
ava.lang.ArrayIndexOutOfBoundsException: Index 8192 out of bounds for length 8192
java.lang.ArrayIndexOutOfBoundsException: Index 8192 out of bounds for length 8192
	at com.alibaba.fastjson2.JSONWriterUTF16.writeName7Raw(JSONWriterUTF16.java:1694)
	at com.alibaba.fastjson2.writer.OWG_5_31_SysUser.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeListValue(FieldWriterList.java:218)
	at com.alibaba.fastjson2.writer.OWG_4_10_Page.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2976)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://github.com/alibaba/fastjson2/assets/52391309/8bc22bba-fefb-424b-b52a-62d5c073f034)

**Comment by Sunx6** [comment]
> 按理来说，2.0.49不应该有这个问题，你可以帮忙再次确认下版本么？

我这边再确认了下，2.0.49是没这个问题，本地项目版本依赖冲突导致的 是2.0.48有这个问题 
![image](https://github.com/alibaba/fastjson2/assets/52391309/9c4af7f6-002c-4e86-afcb-38ca97e88b34)

**Comment by Sunx6** [comment]
还想询问下 后期会提供 类似于jackson的 @JsonInclude(JsonInclude.Include.NON_NULL) 这种不同场景下的字段级别的null输出控制吗  #1730

**Comment by wenshao** [comment]
现在就支持的，比如：
```java
public static class Bean {
    @JSONField(serializeFeatures = JSONWriter.Feature.WriteMapNullValue)
    public Date updateTime;
}
```

也支持Jackson的Annotation
