### ISSUE TITLE
[FEATURE] 增加对["true"]这样的boolean解析

### ISSUE THREAD

**Issue by tywo45** [alibaba/fastjson2#2493]
### 请描述您的需求或者改进建议
JSON.parseObject()好像解析不了["true"]，但是能解析["9090"]等非boolean的。详细见图
![72015b883ae5cf8c5443ba6afb7628f](https://github.com/alibaba/fastjson2/assets/4993939/a49f6d42-b0ee-4c82-9696-5fed8f5d44a2)

![adeaff1542f7f00876735d2a5896d99](https://github.com/alibaba/fastjson2/assets/4993939/53e1c7b0-a38a-4ce3-a2c3-8aff792d75fd)

![538df5d344ced490e6c0a11c731b9e4](https://github.com/alibaba/fastjson2/assets/4993939/2dd5fc5c-61c0-4077-bae3-9b2384b33798)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
问题已修复，请帮忙用2.0.50-SNAPSHOT版本验证，2.0.50版本预计在5月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本
