### ISSUE TITLE
[BUG]JSONObject  转换字符串 boolean类型的属性出错

### ISSUE THREAD

**Issue by luckytao** [alibaba/fastjson2#2502]
### 问题描述
*简要描述您碰到的问题。*
碰到JSONObject转换json字符串时格式错误问题，刚开始运行正常，运行一段时间就会出错，出错后就会一直存在，重启服务后就有好了

服务器是华为云鲲鹏  kylinV10 aarch64 ，程序是部署在docker容器中，docker容器操作系统是centos8 aarch64，

![1111](https://github.com/alibaba/fastjson2/assets/8801167/b9222f1b-09f3-4064-b1a9-036b6c2e201a)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8 ]
 - JDK信息： [e.g.：jdk-8u401-linux-aarch64]
 - 版本信息：[e.g.：Fastjson2 2.0.49]
 

### 重现步骤
*如何操作可以重现该问题：*
偶尔出现，一旦出现一直存在

SONObject licenseObj = null;
......
logger.info("loginValidateredirect==>licenseObj:{}", licenseObj);
logger.info("loginValidateredirect==>licenseObj.toString() = {}", licenseObj.toString());
logger.info("loginValidateredirect==>JSON.toJSONString(licenseObj) = {}", JSON.toJSONString(licenseObj));

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
很抱歉，没看懂你的意思，可以帮构建能直接运行重现问题的testcase么？

**Comment by luckytao** [comment]
> 很抱歉，没看懂你的意思，可以帮构建能直接运行重现问题的testcase么？


 JSONObject jsonObject = new JSONObject();
        jsonObject.put("endData", 1743004800000L);
        jsonObject.put("machineId", "6b69b21c178a8254dedfe031");
        jsonObject.put("maxDeviceNum",1000);
        jsonObject.put("maxUserNum",1000);
        jsonObject.put("message","LIcense授权成功！");
        jsonObject.put("sModes", "11111111");
        jsonObject.put("startDate",1713456000000L);
        jsonObject.put("sucess",true);

        System.out.println(jsonObject.toString());
        System.out.println(JSON.toJSONString(jsonObject));


就是JSONObject 对象转字符串的时候，toString()和toJSONString() 的结果都是错误的，  是由于boolean类型的值转换的结果不对导致字符串的格式异常

**Comment by wenshao** [comment]
我这里没有重现问题，你能帮调试下这个方法么？com.alibaba.fastjson2.JSONWriterUTF16#writeBool
```java
package com.alibaba.fastjson2;

class JSONWriterUTF16
    public void writeBool(boolean value) {
        int minCapacity = off + 5;
        if (minCapacity >= this.chars.length) {
            ensureCapacity(minCapacity);
        }

        char[] chars = this.chars;
        int off = this.off;
        if ((context.features & WriteBooleanAsNumber.mask) != 0) {
            chars[off++] = value ? '1' : '0';
        } else {
            if (!value) {
                chars[off++] = 'f';
            }
            UNSAFE.putLong(chars, ARRAY_CHAR_BASE_OFFSET + ((long) off << 1), value ? TRUE_64 : ALSE_64);
            off += 4;
        }
        this.off = off;
    }
}
```

看下chars,off这些变量发生啥变化了

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
问题已修复，请帮忙用2.0.50-SNAPSHOT版本验证，2.0.50版本预计在5月12日前发布

**Comment by wenshao** [comment]
最新版本的快照版本已经在多种aarch64架构的服务器上通过JDK8/11/17测试，包括：
* 阿里云倚天710
* 华为云鲲鹏服务
* Amazon EC2 C7g (Arm-based AWS Graviton3)
* Orange Pi5 Plus RK3588
* Orange Pi Aipro (昇腾)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本

**Comment by DirgeDos** [comment]
这个问题我也遇到了，我用的2.0.46版本，一开始是正常的，用着用着就出问题，重新部署又正常了，但是就只有循环往复。我这边toString后boolean会变成其他字符,现在是打算升级到最新版本
![Snipaste_2025-01-02_11-41-22](https://github.com/user-attachments/assets/06a597f8-1662-4a64-be25-883ae3cead67)

**Comment by DirgeDos** [comment]
这个问题我也遇到了，我用的2.0.46版本，一开始是正常的，用着用着就出问题，重新部署又正常了，但是就只有循环往复。我这边toString后boolean会变成其他字符,现在是打算升级到最新版本，部署的服务器是aws
![Snipaste_2025-01-02_11-42-37](https://github.com/user-attachments/assets/723e2072-5222-4ba9-a4ae-b3d5ab4bb7e9)

**Comment by wenshao** [comment]
帮忙验证下升级到2.0.57新版本问题是否还存在

**Comment by DirgeDos** [comment]
我升级到2.0.53后，从我反馈问题的时间到目前为止运行正常
compile group: 'com.alibaba.fastjson2', name: 'fastjson2', version: '2.0.53'

**Comment by zhpengsy** [comment]
> 帮忙验证下升级到2.0.57新版本问题是否还存在

升级到2.0.57会有多种功能会有报错，类似：https://github.com/alibaba/fastjson2/issues/3477
使用的上面测试通过的2.0.53测试，会偶发如下错误：

![Image](https://github.com/user-attachments/assets/c4759af9-028d-4f3d-b42a-73131b2f7ed4)
缺少了双引号，测试代码如下：

![Image](https://github.com/user-attachments/assets/40c41399-0561-4800-8ef6-cb7bea6c134b)

[参数.txt](https://github.com/user-attachments/files/19956965/default.txt)

[转字符串.txt](https://github.com/user-attachments/files/19956966/default.txt)
