### ISSUE TITLE
[BUG] JSON.parseObject 缓存com.alibaba.fastjson2.JSONReaderUTF16#readFieldName nameValue0计算问题，导致全局反序列化结果混乱

### ISSUE THREAD

**Issue by xuqqiang** [alibaba/fastjson2#2503]
### 问题描述
JSON.parseObject 缓存com.alibaba.fastjson2.JSONReaderUTF16#readFieldName nameValue0计算问题，导致全局反序列化结果混乱，不同的json字符串反序列化出的对象属性一致
![image](https://github.com/alibaba/fastjson2/assets/33706850/a6f69132-cccc-4b58-9067-de81cd3b7c29)

### 环境信息

 - 版本信息：[e.g.：Fastjson2 2.0.38]
 

### 重现步骤

def "fastJson2 测试"() {
        given:
        def object = JSON.parseObject("{\"sinkAAAAAAAA\":\"A\"}")
        def object2 = JSON.parseObject("{\"s**kAAAAAAAA\":\"A\"}")
        def object3 = JSON.parseObject("{\"saakAAAAAAAA\":\"A\"}")
        def object4 = JSON.parseObject("{\"S**kAAAAAAAA\":\"A\"}")

        println(object.toString())
        println(object2.toString())
        println(object3.toString())
        println(object4.toString())
        println(1)
    }

### 相关日志输出
{"sinkAAAAAAAA":"A"}
{"sinkAAAAAAAA":"A"}
{"sinkAAAAAAAA":"A"}
{"sinkAAAAAAAA":"A"}
1

#### 附加信息
com.alibaba.fastjson2.JSONReaderUTF16#readFieldName，2327行计算nameValue0时，缺少‘（）’导致 “+” 和 “<<” 运算顺序错误导致结果冲突

**Comment by wenshao** [comment]
这个问题修复过，请帮忙用2.0.49版本验证是否还存在

**Comment by xuqqiang** [comment]
感谢你的解答，已验证新版本已修复该问题。

**Comment by pigeon-fancier** [comment]
> 抱歉给你带来麻烦了，这个问题修复过，请帮忙用2.0.49版本验证是否还存在

2.0.50又出现了，复现数据不能提供，抱歉
 java.lang.RuntimeException: com.alibaba.fastjson2.JSONException: expect ':', but ,, offset 4379, character ", line 1, column 4379, fastjson-version 2.0.50 
at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:1346)
	at com.alibaba.fastjson2.reader.ORG_23_2_ProductDetail.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_22_4_Products.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_18_4_FlightFieldDTO.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:786)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1984)
