### ISSUE TITLE
[BUG] 反序列化泛型类时crash

### ISSUE THREAD

**Issue by stc-W** [alibaba/fastjson2#2533]
### 问题描述
*简要描述您碰到的问题。*
反序列化泛型类时crash，报空指针错误

### 环境信息
*请填写以下信息：*

- OS信息：  [Ubuntu 22.04.3 LTS]
- JDK信息： [openjdk 11.0.22 2024-01-16]
- 版本信息：[Fastjson 2.0.49 兼容1.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*
Test case
```java
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.TypeReference;
import com.alibaba.fastjson.parser.Feature;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

import java.nio.charset.StandardCharsets;

public class Test661 {

    static class A<T> {
        T value;
    }

    static class B {
        String name;
    }

    @Test
    public void testBug661() {
        String json = "{\"value\":{\"name\":\"test\"}}";
        byte[] input = json.getBytes(StandardCharsets.UTF_8);
        TypeReference<A<B>> mType = new TypeReference<A<B>>() {};
        A<B> result = JSON.parseObject(input, 0, input.length, StandardCharsets.UTF_8, mType.getType(), Feature.AllowISO8601DateFormat);
        assertEquals("test", result.value.name);
    }
}
```

### 期待的正确结果
*可以正常反序列化*

### 相关日志输出
*java.lang.NullPointerException: Cannot read field "name" because "result.value" is null

	at Test661.testBug661(Test661.java:27)*

**Comment by eahau** [comment]
因为你定义的字段没有设置 public, fastjson 则忽略了非 public 字段的值写入，源代码见

https://github.com/alibaba/fastjson2/blob/89a6c29622a2cc2b8cb91bb36980118d39afeef6/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderCreator.java#L1649

https://github.com/alibaba/fastjson2/blob/89a6c29622a2cc2b8cb91bb36980118d39afeef6/core/src/main/java/com/alibaba/fastjson2/reader/ObjectReaderCreator.java#L1422-L1424

所以你需要做的是，加上 `JSONReader.Feature.FieldBased`, [JSONReader.Feature介绍](https://github.com/alibaba/fastjson2/wiki/Features_cn#4-jsonreaderfeature%E4%BB%8B%E7%BB%8D)
```java
JSON.parseObject(json, new TypeReference<A<B>>() {}.getType(), JSONReader.Feature.FieldBased);
```

**Comment by stc-W** [comment]
明白了感谢
