### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vanguardw** [alibaba/fastjson2#2562]
### 问题描述
*简要描述您碰到的问题。*
Spring Boot使用fastjson2序列化复杂对象，里面包含了Object类型的属性，会报错

### 环境信息
*请填写以下信息：*

 - OS信息：  UOS
 - JDK信息：JDK17.0.8
 - 版本信息：fastjson2.0.49
 

### 重现步骤
*如何操作可以重现该问题：*
Spring Boot使用fastjson2序列化复杂对象，里面包含了Object类型的属性

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
正常序列化

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
Handler dispatch failed: java.lang.IllegalAccessError: failed to access class java.security.ProtectionDomain$Key from class com.alibaba.fastjson2.writer.0WG_41_7_ProtectionDomain (java.security.ProtectionDomain$Key is in modue java.base of loader, 'bootstrap'; com.alibaba. fastjson2.writer.Owc_41 7 ProtectionDomain is in unnamed module of loader com.alibaba. fastjson2.uti1.DynamicclassLoader @18f2e0r6)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096)
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.50-SNAPSHOT/
问题已修复，请帮忙用2.0.50-SNAPSHOT版本验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.50
2.0.50已发布，请用新版本

**Comment by vanguardw** [comment]
之前那个不报错了，现在又出现了了新的错误，能否把这些错误统一处理了？
Jakarta.servlet.ServletException: Handler dispatch failed: java. lang. IllegalAccessError: failed to access class java.lang. ref.ReferenceQueue$Lock from class com.alibaba.fastjson2.writer.OWG_58_3_Null ( java.lang. ref.ReferenceQueue$Lock is in module java base of loader 'bootstrap'; com.alibaba.fastjson2.writer.0WG_58_3_Null is in unnamed module of loader com.alibaba.fastjson2.util.DynamicclassLoader @6282086b)at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
.fastjson2.writer.0WG_58_3_Null (java.lang.ref.Referencequeue$Lock is in module java.bas
