### ISSUE TITLE
[QUESTION] JSONObject LinkedHashMap 泛型问题

### ISSUE THREAD

**Issue by MisakaTAT** [alibaba/fastjson2#257]
### 请描述您的问题
```java
public class JSONObject extends LinkedHashMap implements InvocationHandler
```
如题，`fastjson2`相较于`v1`版本移除了`LinkedHashMap`泛型，在原项目升级`v2`版本后出现多处以下告警，经翻阅`issues`了解到是为了修复 #110，目前暂时用`@SuppressWarnings("unchecked")`抑制了告警，想请问下后续会考虑将泛型加回来吗？关联问题 #165。
```
Unchecked assignment: 'com.alibaba.fastjson2.JSONObject' to 'java.util.Map<java.lang.String,java.lang.Object>
```

**Comment by wenshao** [comment]
你用的是什么版本？

**Comment by MisakaTAT** [comment]
> 你用的是什么版本？

2.0.3

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.4
问题已经修复，请用新版本
