### ISSUE TITLE
JSON.parseObject(json, Map.class) 整数0为key的问题

### ISSUE THREAD

**Issue by 156370005** [alibaba/fastjson2#2570]
fastjson1升fastjson2时，使用的是Fastjson v1兼容模块
\<dependency\>
    \<groupId\>com.alibaba\</groupId\>
    \<artifactId\>fastjson\</artifactId\>
    \<version\>2.0.50\</version\>
\</dependency\>

出现以下问题

String json = "{0:12,1:13,2:14,\\\"date\\\":\\\"2024-05-14\\\"}";
Map<Object,Object> map = JSON.parseObject(json, Map.class);

fastjson1取值如下：
Integer date0 = (Integer) map.get(0);// 取到值为12
Integer date1 = (Integer) map.get(1);// 取到值为13

fastjson2用com.alibaba.fastjson.JSON取值如下：
Integer date0 = (Integer) map.get(0);// 取到值为null
Integer date1 = (Integer) map.get(1);// 取到值为13

fastjson2下得到的date0是不对的，发现fastjson2把key为0转成了字符串，但key为1又还是整数，这也太奇怪了。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.51-SNAPSHOT/
问题已修复，请帮忙用2.0.51-SNAPSHOT版本验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.51
问题已修复，请用新版本
