### ISSUE TITLE
fastjson2报错，com.alibaba.fastjson2.writer.0WG_58_3_Null is in unnamed module of loader com.alibaba.fastjson2.util.DynamicclassLoader 

### ISSUE THREAD

**Issue by vanguardw** [alibaba/fastjson2#2571]
现在又出现了了新的错误，能否把这些错误统一处理了？
Jakarta.servlet.ServletException: Handler dispatch failed: java. lang. IllegalAccessError: failed to access class java.lang. ref.ReferenceQueue$Lock from class com.alibaba.fastjson2.writer.OWG_58_3_Null ( java.lang. ref.ReferenceQueue$Lock is in module java base of loader 'bootstrap'; com.alibaba.fastjson2.writer.0WG_58_3_Null is in unnamed module of loader com.alibaba.fastjson2.util.DynamicclassLoader @6282086b)at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
.fastjson2.writer.0WG_58_3_Null (java.lang.ref.Referencequeue$Lock is in module java.bas

_Originally posted by @vanguardw in https://github.com/alibaba/fastjson2/issues/2562#issuecomment-2109248566_

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.51-SNAPSHOT/
问题已修复，请帮忙用2.0.51-SNAPSHOT版本验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.51
问题已修复，请用新版本

**Comment by wangwenming0918** [comment]
这个问题在2.0.51中还是存在
![image](https://github.com/user-attachments/assets/6cfa998f-9026-4812-9af7-dc4473a8b8b3)
