### ISSUE TITLE
[FEATURE]添加对java.awt.Color类型的序列化和反序列化支持

### ISSUE THREAD

**Issue by kenanor** [alibaba/fastjson2#2578]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*
1.x版本是支持的，在2.0.50版本中反序列化出来的rgb全是0
希望实现类似于如下效果：
`String colorStr = JSONObject.toJSONString(Color.BLUE); //{"r":0,"g":0,"b":255,"alpha":255}`
`Color color = JSONObject.parseObject(colorStr, Color.class);//java.awt.Color[r=0,g=0,b=255]`

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*
略

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*
略

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
略

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.51-SNAPSHOT/
问题已修复，请帮忙用2.0.51-SNAPSHOT版本验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.51
问题已修复，请用新版本
