### ISSUE TITLE
[QUESTION] 全局使用BrowserCompatible后如何局部返回number类型

### ISSUE THREAD

**Issue by logan2013** [alibaba/fastjson2#2605]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
目前fastjson2设置了BrowserCompatible后，如果大于9007199254740991L，会序列化成字符串

String jsonString = JSON.toJSONString(new TestDto(), JSONWriter.Feature.BrowserCompatible);

@Data
public static class TestDto {
    @JSONField(serializeUsing = IgnoreBrowserCompatibleObjectWriter.class)
    private BigDecimal amount = new BigDecimal("2000000000000000000");
}
由于历史原因，客户端某些字段需要返回number类型，请问如何覆盖全局的设置呢

**Comment by logan2013** [comment]
@Deprecated
public class IgnoreBrowserCompatibleObjectWriter implements ObjectWriter<BigDecimal> {

    @Override
    public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
        if (object instanceof BigDecimal) {
            jsonWriter.config(JSONWriter.Feature.BrowserCompatible, false);
            jsonWriter.config(JSONWriter.Feature.WriteBigDecimalAsPlain, true);
            jsonWriter.writeDecimal((BigDecimal) object);
            jsonWriter.config(JSONWriter.Feature.BrowserCompatible, true);
        } else {
            jsonWriter.writeNull();
        }
    }
}
临时找到了这个方案，请问安全吗

**Comment by logan2013** [comment]
@wenshao 在线求助，十分感谢

**Comment by wenshao** [comment]
@logan2013 这个做法可行的

**Comment by logan2013** [comment]
好的，感谢
