### ISSUE TITLE
[FEATURE] 希望增加 Context::config 的“与”操作

### ISSUE THREAD

**Issue by noear** [alibaba/fastjson2#2610]
JSONReader.Context::config(..) 和 JSONWriter.Context::config(..)

它们内部是 `|=` 操作，能不能出一个 `&=` 的操作？

**Comment by noear** [comment]
如果可以的话，希望再加个直接修改 `long features` 的接口，或者重置它的接口

**Comment by wenshao** [comment]
```java
 public void config(Feature feature, boolean state) 
```
用这个不可以么？

**Comment by noear** [comment]
啊哈，看走眼了。。。这个确实可以。

那，如何想重置为默认值，有什么接口可用吗？

**Comment by wenshao** [comment]
```java
JSON.config
```
这个是重置全局默认值的

**Comment by noear** [comment]
这个影响太大了。。。我是想重置 context 里的 long features 值。

应用场景是：

我给定了些默认的特性，但是用户不想要。用户想重置后，再添加自己的特性。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.51-SNAPSHOT/
已经支持，请帮忙用2.0.51-SNAPSHOT版本验证
JSONReader.Context和JSONWriter.Context都已经支持setFeatures(long)方法

**Comment by noear** [comment]
感谢！

**Comment by noear** [comment]
在我这儿。算是：在默认配置后，还有一个“二次配置”的可能。

**Comment by noear** [comment]
还需要提供获取它们的两个函数（重置默认时用）：

```
JSONFactory.defaultWriterFeatures
JSONFactory.defaultReaderFeatures
```

**Comment by noear** [comment]
还需要加个 jsonb 相关的接口：

````
JSON.parse(byte[] bytes, JSONReader.Context)
````

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.51-SNAPSHOT/
已经加上相关方法，请帮忙用2.0.51-SNAPSHOT版本验证

**Comment by noear** [comment]
谢谢。。。哎，做开源人真不容易啊：）

**Comment by noear** [comment]
JSONFactory.defaultWriterFeatures
JSONFactory.defaultReaderFeatures

这两个，还没有对应的方法可以获取？！

**Comment by noear** [comment]
是不是可以添加：
JSONFactory.getDefaultReaderFeatures()
JSONFactory.getDefaultWriterFeatures()

**Comment by noear** [comment]
@wenshao 不差两个函数啊：）

**Comment by wenshao** [comment]
@noear 你帮提交个PR？

**Comment by noear** [comment]
pr 提交了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.51
请用新版本
