### ISSUE TITLE
[BUG] 使用WriteClassName序列化，然后再反序列化时@type信息没有去除

### ISSUE THREAD

**Issue by elitewe** [alibaba/fastjson2#2623]
### 问题描述
使用序列化方法JSON.toJSONString(dataMap, SerializerFeature.WriteClassName)，反序列话后的对象中包含@type信息，理想情况下应该不会出现@type（fastjson1反序列化后没有@type)

### 环境信息

 - OS信息： Windows
 - JDK信息： JDK17
 - 版本信息：Fastjson2 2.0.49
 

### 重现步骤
```
        Map<String, Object> dataMap = new HashMap<>(2);
        dataMap.put("aInteger", 1);
        dataMap.put("aLong", 2L);
        dataMap.put("aFloat", 3F);
        String jsonStr = JSON.toJSONString(dataMap, SerializerFeature.WriteClassName);
        System.out.println(jsonStr);

        System.out.println("--- fastjson -----");
        Map<String, Object> fastMap = JSON.parseObject(jsonStr, new TypeReference<Map<String, Object>>() {});
        printMap(fastMap);
```

### 期待的正确结果
期望的输出结果（使用fastjson1.2.68）
![image](https://github.com/alibaba/fastjson2/assets/37527269/b61a3477-f737-4daf-b294-ba6311a75f16)

### 相关日志输出
![image](https://github.com/alibaba/fastjson2/assets/37527269/52eaa2d0-3fa3-4cf7-8b7c-f19ab42edf24)

**Comment by elitewe** [comment]
> 可以通过开启SupportAutoType避免反序列化后携带@type字段
> 
> ```
> Map<String, Object> fastMap = JSON.parseObject(jsonStr, new TypeReference<Map<String, Object>>() {}, JSONReader.Feature.SupportAutoType);
> ```

好的谢谢，为什么fastjson1.2.68版本不用主动开启SupportAutoType就可以过滤@type字段？是fastjson1和fastjson2的默认策略不一样吗

**Comment by wenshao** [comment]
2.0.x如果不配置SupportAutoType，就不会做任何相关处理，这个是为了安全考虑。

**Comment by elitewe** [comment]
> 2.0.x如果不配置SupportAutoType，就不会做任何相关处理，这个是为了安全考虑。

好的，请问开启SupportAutoType这个功能是在哪一个版本添加上去的，我使用fastjson2.0.13版本加上SupportAutoType后@type仍然没有去除

**Comment by elitewe** [comment]
> 2.0.x如果不配置SupportAutoType，就不会做任何相关处理，这个是为了安全考虑。

另外我发现一个问题，如果序列化对象是java.sql.Date时，使用上述接口会报错
```
Map<String, Object> map = new HashMap<>();
        map.put("a", 1L);
        map.put("b", 2);
        map.put("c", 3f);
        map.put("d", new Date(System.currentTimeMillis()));

        String s = JSON.toJSONString(map, JSONWriter.Feature.WriteClassName);
        System.out.println(s);
        Map<String, Object> map2 = JSON.parseObject(s, new TypeReference<Map<String, Object>>(){}, JSONReader.Feature.SupportAutoType);
        System.out.println(map2);
```
报错日志如下
Exception in thread "main" com.alibaba.fastjson2.JSONException: read LocalDateTime error val, offset 86, character :, line 1, column 86, fastjson-version 2.0.49 {"@type":"java.util.HashMap","a":1L,"b":2,"c":3.0F,"d":{"@type":"java.sql.Date","val":1716789581756}}
	at com.alibaba.fastjson2.JSONReader.readLocalDateTime(JSONReader.java:1226)
	at com.alibaba.fastjson2.util.JdbcSupport$DateReader.readObject(JdbcSupport.java:669)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:129)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:397)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:991)
	at demo21.main(demo21.java:24)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.51
问题已修复，请用新版本
