### ISSUE TITLE
[FEATURE]含有重复key的json转为JSONObject使得重复的key元素的部分，合并为数组形式

### ISSUE THREAD

**Issue by mancong** [alibaba/fastjson2#263]
### 请描述您的需求或者改进建议

可否实现 [含有重复key的json字串转化jsonObject，使得重复的key元素的部分，合并为数组形式](https://blog.csdn.net/Noreaday/article/details/88078680) 效果呢？

### 请描述你建议的实现方案

按照标准json规范来将，此类情况应当为JSONArray 格式，
但是在解析 某些已有的数据时，会存在该种情况，且也会存在数据丢失的问题。

### 描述您考虑过的替代方案

使用net.sf.json.JSONObject 可以实现

**Comment by wenshao** [comment]
json规范没有规定这个吧

**Comment by mancong** [comment]
> json规范没有规定这个吧

是的，所以这个 是以特殊情况下的 需求，不知道 大佬 如何 规划了😀

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

已经支持，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

```java
String str = "{\"item\":1,\"item\":2}";
JSONObject object = (JSONObject) JSON.parse(str, JSONReader.Feature.DuplicateKeyValueAsArray);
```
你可以这样用

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
