### ISSUE TITLE
[BUG] java.util.BitSet JDK 17 原生支持

### ISSUE THREAD

**Issue by AlbumenJ** [alibaba/fastjson2#265]
### 问题描述
*简要描述您碰到的问题。*
![image](https://user-images.githubusercontent.com/9292748/168585058-fc254d9a-a412-4181-901f-1a10889e8fb8.png)

java.util.BitSet JDK17 下无法反序列化

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： openjdk 17
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.4
问题已经在2.0.4版本中修复，请用新版本
