### ISSUE TITLE
自定义枚举反序列化器失败

### ISSUE THREAD

**Issue by tuhanbao** [alibaba/fastjson2#2688]
![image](https://github.com/alibaba/fastjson2/assets/18526473/4841638f-aa65-42a0-bb65-6c04b10a0070)

这个else分支是不是要挪到外面，我自定义的ObjectReader走不进去，ObjectReaderImplEnum是个final，也没法通过继承绕过去

**Comment by tuhanbao** [comment]
com.alibaba.fastjson2.util.TypeUtils类

**Comment by yanxutao89** [comment]
麻烦提供下可复现的示例代码

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.52
问题已修复，请用新版本
