### ISSUE TITLE
[BUG]小数点后超过38位后，json解析数据错误

### ISSUE THREAD

**Issue by liushan150** [alibaba/fastjson2#269]
### 问题描述
*简要描述您碰到的问题。*
解析json为小数时，小数位超过38位时数据解析错误。
String jsonStr="{\"test_prr\":2.9900000000000002131628207280300557613372802734375}";

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：MacOS 12.3.1]
 - JDK信息： [e.g.：zulu8_jdk8.0.312]
 - 版本信息：[e.g.：Fastjson2 2.0.3]
 

### 重现步骤
```java
//可在此输入示例代码
 String jsonStr="{\"test_prr\":2.9900000000000002131628207280300557613372802734375}";
        JSONObject json = JSON.parseObject(jsonStr, JSONReader.Feature.UseBigDecimalForDoubles);
        BigDecimal val = json.getBigDecimal("test_prr");
        System.out.println(val.doubleValue());
        System.out.println(json.toJSONString());
        System.out.println( JSON.toJSONString(json));
```

### 错误结果：
3.287119106202786E-11

### 当小数位少于或等于38位时，输出结果为保留两位小数结果
2.99

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
2.9900000000000002131628207280300557613372802734375

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by MisakaTAT** [comment]
#15

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/

问题已经修复，请帮忙用 2.0.4-SNAPSHOT 版本验证，2.0.4版本预计在5月22日前发布

**Comment by liushan150** [comment]
已修复，辛苦了。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.4
问题已经在2.0.4版本中修复，请用新版本
