### ISSUE TITLE
[BUG]JSON.toJSONString()方法序列化字段转化错误问题

### ISSUE THREAD

**Issue by JiahaoLin2018** [alibaba/fastjson2#2713]
### 问题描述
*JSON.toJSONString(sampleSelectVO)序列化字段转化错误问题*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows]
 - JDK信息： [e.g.：Openjdk 21]
 - 版本信息：[e.g.：Fastjson2 2.0.51]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
@Getter
@Setter
@FieldNameConstants
public class SampleSelectVO {
    /**
     * y列
     */
    private String yColumn;
}

public static void main(String[] args) {
    SampleSelectVO sampleSelectVO = new SampleSelectVO();
    sampleSelectVO.setYColumn("var");
    String jsonString = JSON.toJSONString(sampleSelectVO);
    System.out.println(jsonString);
}
```

1. 使用 `JSON.toJSONString(sampleSelectVO)` 方法
2. 序列化后的jsonString为：{"YColumn":"dpd30_MOB1"}

### 期待的正确结果
*正确的输出结果为：{"yColumn":"var"}*

### 相关日志输出
*{"YColumn":"var"}*

**Comment by yanxutao89** [comment]
默认以method作为属性名，开启FieldBased则与field保持严格一致

**Comment by JiahaoLin2018** [comment]
> 默认以method作为属性名，开启FieldBased则与field保持严格一致

是的，按理说，默认以method作为属性名的话，Java Bean规范应该是一致的，getYColumn应该解析成yColumn，而getThirdType应该解析成thirdType。
提取字段名的规则应该是使用字段的method去掉get前缀，将首字母改为小写吧？

**Comment by yanxutao89** [comment]
> > 默认以method作为属性名，开启FieldBased则与field保持严格一致
> 
> 是的，按理说，默认以method作为属性名的话，Java Bean规范应该是一致的，getYColumn应该解析成yColumn，而getThirdType应该解析成thirdType。 提取字段名的规则应该是使用字段的method去掉get前缀，将首字母改为小写吧？

默认的提取字段名策略是CamelCase，当method去掉get前缀后，仅当第一个字母大写且第二个字母小写时，才会将首字母改为小写。如果要保持你说的首字母直接小写，可以显式指定CamelCase1X的策略，即在Bean上加@JSONType(naming = PropertyNamingStrategy.CamelCase1x)

**Comment by JiahaoLin2018** [comment]
> > > 默认以method作为属性名，开启FieldBased则与field保持严格一致
> > 
> > 
> > 是的，按理说，默认以method作为属性名的话，Java Bean规范应该是一致的，getYColumn应该解析成yColumn，而getThirdType应该解析成thirdType。 提取字段名的规则应该是使用字段的method去掉get前缀，将首字母改为小写吧？
> 
> 默认的提取字段名策略是CamelCase，当method去掉get前缀后，仅当第一个字母大写且第二个字母小写时，才会将首字母改为小写。如果要保持你说的首字母直接小写，可以显式指定CamelCase1X的策略，即在Bean上加@jsontype(naming = PropertyNamingStrategy.CamelCase1x)

好的，谢谢你的帮助，既然不是bug我将close掉这个issue。
