### ISSUE TITLE
反序列化Map<Integer, Long>类型存在问题

### ISSUE THREAD

**Issue by qiuwenner** [alibaba/fastjson2#273]
### 问题描述
`Map<Integer, Long>`类型的一个map，序列化后json中的key，在fastjson1中是数字，fastjson2中是字符串，2是标准的json格式没问题。
但是2反序列化`Map<Integer, Long> parseObject = JSON.parseObject(json2, new TypeReference<HashMap<Integer, Long>>() {}.getType())`，后map中的key是String而不是Integer，但是在fastjson1中，该方法是可以正确解析的。

```java
        Map<Integer, Long> map = new HashMap<>();
        map.put(1, 111L);
        map.put(2, 222L);
        String json = JSON.toJSONString(map);
        Map<Integer, Long> parseObject = JSON.parseObject(json, new TypeReference<HashMap<Integer, Long>>() {
        }.getType());
        System.out.println(parseObject.get(1));
```

# 版本
2.0.3

**Comment by qiuwenner** [comment]
已解决

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.4-SNAPSHOT/
问题已经修复，你可以用快照版本验证
