### ISSUE TITLE
ObjectSerializer 和 ObjectDeserializer 被移除了，有什么新的代替方案

### ISSUE THREAD

**Issue by zwq9018** [alibaba/fastjson2#275]
ObjectSerializer 和 ObjectDeserializer 被移除了，有什么新的代替方案

**Comment by wenshao** [comment]
* Annotation介绍 https://github.com/alibaba/fastjson2/wiki/fastjson2_annotations
* Annotation注入介绍 https://github.com/alibaba/fastjson2/wiki/mixin_cn
* Feature介绍 https://github.com/alibaba/fastjson2/wiki/Features_cn
* 使用Mixin注入Anntation定制序列化和反序列化 https://github.com/alibaba/fastjson2/wiki/mixin_cn
* 实现ObjectWriter和ObjectReader实现定制序列化和反序列化 https://github.com/alibaba/fastjson2/wiki/register_custom_reader_writer_cn

以上这些文档看是否满足你的要求

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
新版本已发布，已经支持ObjectSerializer/ObjectDeserializer

**Comment by zwq9018** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月29日(星期天) 凌晨2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/fastjson2] ObjectSerializer 和 ObjectDeserializer 被移除了，有什么新的代替方案 (Issue #275)





 
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
 新版本已发布，已经支持ObjectSerializer/ObjectDeserializer
