### ISSUE TITLE
请教反序列化包含泛型的问题

### ISSUE THREAD

**Issue by lianfuye** [alibaba/fastjson2#28]
Result<TestUser> result = JSON.parseObject(str, new TypeReference<Result<TestUser>>(){});

2.x 中这么使用反序列化（包含泛型）时 IDEA 提示下面的错误，请教 2.x 如何处理这块 ？感谢！

无法解析方法'parseObject(java.lang.String, anonymous com.alibaba.fastjson2.TypeReference<com.william.mall.common.model.Result<com.william.mall.common.model.TestUser>>)'

**Comment by wenshao** [comment]
```java
String str = "{}";

Result result = JSON.parseObject(str, new TypeReference<Result>(){}.getType());
assertNotNull(result);
```

可以先通过上面的方法解决，下一个版本2.0.2会直接支持传入TypeReference

**Comment by lianfuye** [comment]
thanks 大佬 ~

**Comment by wenshao** [comment]
2.0.2预计5月3日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
