### ISSUE TITLE
如何替换原来的SpringMVC统一的json消息转换器

### ISSUE THREAD

**Issue by javaHBZ** [alibaba/fastjson2#281]
![image](https://user-images.githubusercontent.com/97934537/169186599-8b93f1b5-8cb5-4d30-9775-ba87548d2ffc.png)
![image](https://user-images.githubusercontent.com/97934537/169186645-485cbd10-6a5a-4809-85fc-b5d63184249a.png)

**Comment by VictorZeng** [comment]
@javaHBZ Hi, fastjson2对SpringMVC的支持`com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter`在扩展包里面：
```xml
<dependency>
    <groupId>com.alibaba.fastjson2</groupId>
    <artifactId>fastjson2-extension</artifactId>
    <version>2.0.x</version>
</dependency>
```
> 关于Features的使用请参考https://github.com/alibaba/fastjson2/wiki/Features_cn

**Comment by javaHBZ** [comment]
@VictorZeng  好的 感谢您的回复

**Comment by logan2013** [comment]
会导致swagger用不了

**Comment by VictorZeng** [comment]
@logan2013 能否提供一下测试数据和测试用例说明一下~

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
