### ISSUE TITLE
如何通过全局设置指定使用 NamingStrategy.SnakeCase 格式输出字段？

### ISSUE THREAD

**Issue by LyZane** [alibaba/fastjson2#2810]
我在 springboot 项目中使用 fastjson2，通过自定义 HttpMessageConverters 使用 fastjson 作为 json 序列化实现。
在 fastjson1 版本中，我使用如下代码设置全局使用 SnackCase，但是在 fastjson2 中没有查到怎么实现。

```java
// 全局设置 fastjson 序列化的命名策略为下划线
SerializeConfig.getGlobalInstance().propertyNamingStrategy = PropertyNamingStrategy.SnakeCase;
```

请告诉我如何在自定义 HttpMessageConverters 中指定使用 NamingStrategy.SnakeCase，或者告诉我如何全局设置使用 NamingStrategy.SnakeCase。

**Comment by wenshao** [comment]
```java
JSONFactory.getDefaultObjectWriterProvider()
                .setNamingStrategy(PropertyNamingStrategy.SnakeCase)
```

**Comment by LyZane** [comment]
Thanks

successed!
