### ISSUE TITLE
[BUG] Compilation failure 找不到模块: fastjson

### ISSUE THREAD

**Issue by ZhReimu** [alibaba/fastjson2#2812]
### 问题描述
使用了 module-info 后编译失败

### 环境信息
*请填写以下信息：*

 - OS信息：  Windows 11 23h2 22631.3880
 - JDK信息： `java 21.0.2 2024-01-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)
`
 - 版本信息：Fastjson2 2.0.51
 

### 重现步骤
新建一个项目，导入 fastjson2 依赖, 加入 module-info.java
```java
module example.module {
     requires com.alibaba.fastjson2;
}
```

### 期待的正确结果
正常编译通过

### 相关日志输出
java: 找不到模块: fastjson

#### 附加信息
为什么 fastjson2 需要依赖 fastjson1
![image](https://github.com/user-attachments/assets/94ed907b-4dad-4271-8e35-b1e8f1f7f4c8)
导入 fastjson 后构建成功
```xml
    <dependencies>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.51</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.50</version>
        </dependency>
    </dependencies>
```

**Comment by wenshao** [comment]
这个问题修复过，帮忙升级到2.0.52验证下是否问题还存在

**Comment by ZhReimu** [comment]
> 这个问题修复过，帮忙升级到2.0.52验证下是否问题还存在

2.0.52 版本可以了, 我没在 issue 里搜到相关问题, 所以提了个
