### ISSUE TITLE
[BUG] 字符串转JSONObject 失败

### ISSUE THREAD

**Issue by BEF841CA** [alibaba/fastjson2#2827]
### 问题描述
字符串转JSONObject 失败，提示
class java.lang.String cannot be cast to class com.alibaba.fastjson2.JSONObject (java.lang.String is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.JSONObject is in unnamed module of loader 'app')

### 环境信息
*请填写以下信息：*

 - OS信息：  Windows 11 专业版 23H2
 - JDK信息： openjdk version "21" 2023-09-19
 - 版本信息：fastjson2 2.0.52
 

### 重现步骤
*如何操作可以重现该问题：*

1. 调用main方法
2. 抛出ClassCastException异常
```java
    public static void main(String[] args) {
        String body= "{\"errcode\":0,\"errmsg\":\"ok\",\"access_token\":\"xxxxx\",\"expires_in\":7200}";
  
        System.out.println(body);
        JSONObject json = JSONObject.from(body);
  
        System.out.println(json.toString());
    }
```

### 期待的正确结果
字符串正常转换成JSONObject 

### 相关日志输出
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
{"errcode":0,"errmsg":"ok","access_token":"xxxxx","expires_in":7200}
Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class com.alibaba.fastjson2.JSONObject (java.lang.String is in module java.base of loader 'bootstrap'; com.alibaba.fastjson2.JSONObject is in unnamed module of loader 'app')
	at com.alibaba.fastjson2.JSONObject.from(JSONObject.java:2068)

**Comment by xcodemap** [comment]
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/cffc8f71-2740-43b1-946c-7b5b83a1b20f">
使用[XCodeMap](https://xcodemap.tech)跟了一下源码，toJson的基本原理是，先把参数 Object 变为 String，然后在 parse 时read 回来。 如果参数Object本身是一个String，则在write阶段，escape一下，read阶段再去掉escape。但是，显然整个函数返回的对象是一个String 而不是 JSONObject。  这个感觉是一个设计问题。 对于用户来说，如果要把一个String变成JSONObject，应该调用JSON.parseObject函数。

**Comment by BEF841CA** [comment]
感谢大佬回复
字符串转json使用JSON.parseObject()。object转json使用JSONObject.from()
