### ISSUE TITLE
[QUESTION] 如果想把空对象序列化为空数组，应该怎么写 

### ISSUE THREAD

**Issue by duyucongc** [alibaba/fastjson2#2828]
因为遇到一些接口的某些字段的，正常情况下是一个数组，但是当空的时候，会直接返回一个空对象，想问一下，现在有什么好的接受办法么
比如
正常情况下是

{"array":["1","2"]}

空的情况下会直接返回

{"array":{}}

如果我的对象是

class TestArray {
private List array;
}

因为遇到一些接口的某些字段的，正常情况下是一个数组，但是当空的时候，会直接返回一个空对象，想问一下，现在有什么好的接受办法么
比如
正常情况下是
{"array":["1","2"]}
空的情况下会直接返回
{"array":{}}
如果我的对象是
class TestArray {
private List array;
}

我该怎么写方法才可以接受，有什么预先写好的方法或者自定义写法么

**Comment by rowstop** [comment]
如果没有开启 fieldbase 可以在 setter方法里处理 使用 Object 接收数据，然后自行处理

**Comment by xcodemap** [comment]
解决办法见 https://github.com/alibaba/fastjson/issues/4521

**Comment by duyucongc** [comment]
谢谢感谢~
