### ISSUE TITLE
Could not write JSON: null; nested exception is com.alibaba.fastjson2.JSONException

### ISSUE THREAD

**Issue by javaHBZ** [alibaba/fastjson2#283]
在不动原来的功能下,1.2.x版本是正常运行的,
下面是我替换成2.0.x版本的配置,出现了:Could not write JSON: null; nested exception is com.alibaba.fastjson2.JSONException
下面代码中注释部分是1.2.x版本的配置
![image](https://user-images.githubusercontent.com/97934537/169222465-d1938cdc-3cb5-4a82-9e6b-d38abfca066c.png)

是否是我配置错误了，望大佬解答

**Comment by javaHBZ** [comment]
这是我导包部分
![image](https://user-images.githubusercontent.com/97934537/169222847-474cd0ee-f755-4f62-8aa4-e2ca81df65ae.png)

**Comment by VictorZeng** [comment]
@javaHBZ 是否能提供一下测试数据和测试用例

**Comment by javaHBZ** [comment]
@VictorZeng `@PostMapping("/xx/xx")
	public Map<String, Object> login(@RequestBody SysLoginForm form)throws IOException {


		//生成token，并保存到数据库
		Map<String, Object> r = new HashMap<>();
		r.put("code", 0);
		r.put("expire", 43200);
		r.put("msg", "success");
		r.put("token", "05600918b21afba2298729d2b24c4af9");
		return r;
}`

**Comment by javaHBZ** [comment]
@VictorZeng 
`@PostMapping("/xx/xx")
	public Map<String, Object> login(@RequestBody SysLoginForm form)throws IOException {


		//生成token，并保存到数据库
		Map<String, Object> r = new HashMap<>();
		r.put("code", 0);
		r.put("expire", 43200);
		r.put("msg", "success");
		r.put("token", "05600918b21afba2298729d2b24c4af9");
		return r;
	}`

**Comment by javaHBZ** [comment]
`@PostMapping("/xx/xx")
	public Map<String, Object> login(@RequestBody SysLoginForm form)throws IOException {


		//生成token，并保存到数据库
		Map<String, Object> r = new HashMap<>();
		r.put("code", 0);
		r.put("expire", 43200);
		r.put("msg", "success");
		r.put("token", "05600918b21afba2298729d2b24c4af9");
		return r;
	}`

**Comment by javaHBZ** [comment]
@PostMapping("/xx/xx")
	public Map<String, Object> login(@RequestBody SysLoginForm form)throws IOException {


		//生成token，并保存到数据库
		Map<String, Object> r = new HashMap<>();
		r.put("code", 0);
		r.put("expire", 43200);
		r.put("msg", "success");
		r.put("token", "05600918b21afba2298729d2b24c4af9");
		return r;
	}

**Comment by javaHBZ** [comment]
@VictorZeng

**Comment by VictorZeng** [comment]
`SysLoginForm` 能提供一下吗~

**Comment by javaHBZ** [comment]
@Data
public class SysLoginForm {
    /**
     * 账号
     */
    private String username;
    /**
     * 密码
     */
    private String password;
    /**
     * 验证码
     */
    private String captcha;
    /**
     * 请求码
     */
    private String uuid;
    /**
     * 是否记住我
     */
    private boolean rememberMe;


}

**Comment by VictorZeng** [comment]
@javaHBZ 可以尝试一下快照版本，看看您的问题是否解决。
```xml
<dependency>
     <groupId>com.alibaba.fastjson2</groupId>
     <artifactId>fastjson2-extension</artifactId>
     <version>2.0.4-SNAPSHOT</version>
</dependency>
```

**Comment by VictorZeng** [comment]
@javaHBZ 根据您提供的信息，我做了下testcase，问题已修复，See https://github.com/alibaba/fastjson2/blob/main/extension/src/test/java/com/alibaba/fastjson2/spring/issues/issue283/Issue283.java

**Comment by javaHBZ** [comment]
![image](https://user-images.githubusercontent.com/97934537/169433565-d841a604-8b0d-41e5-b741-c5b8e05246e9.png)
依赖好像没在仓库中找到

**Comment by javaHBZ** [comment]
@VictorZeng

**Comment by VictorZeng** [comment]
@javaHBZ maven central 的快照仓库有的噢~
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2-extension/2.0.4-SNAPSHOT/
