### ISSUE TITLE
Android不支持fastjson2[BUG]

### ISSUE THREAD

**Issue by Serendipithub** [alibaba/fastjson2#286]
### 问题描述
Android ART虚拟机不支持fastjson2, 缺少类
`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory`

### 环境信息

 - OS信息：  Android10 API 29
 - JDK信息： Android ART
 - 版本信息：Fastjson2 2.0.3
 

### 重现步骤

1. 使用 `JSON::toJSONString(Any)` 方法
2. 输入数据
 ```kotlin
var obj = object {
    var message = "Hello"
}
``` 
4. 出现 `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory` 错误
```kotlin
val obj = object {
    var message = "Hello"
}
val jsonString = JSON.toJSONString(obj)
println(jsonString)
```

### 期待的正确结果
在JDK 11上实际输出如下
`{"message":"Hello"}`

安卓期望输出
`{"message":"Hello"}`
实际报错

### 相关日志输出
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 31029
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
        at ...
```

```java
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/com.example.myapplication-DSxjsAQ_wm5Pn6Uxsz3adQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myapplication-DSxjsAQ_wm5Pn6Uxsz3adQ==/lib/arm64, /data/app/com.example.myapplication-DSxjsAQ_wm5Pn6Uxsz3adQ==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
```

#### 附加信息
原因是安卓ART虚拟机缺少类`java/lang/management/ManagementFactory`

**Comment by Serendipithub** [comment]
### 如果fastjson2没有像readme中所说的那样支持Android的话, 请忽略此ISSUE.

**Comment by wenshao** [comment]
支持的，有专门的android版本 2.0.3.android

https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2/2.0.3.android/

**Comment by Serendipithub** [comment]
> 支持的，有专门的android版本 2.0.3.android
> 
> https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2/2.0.3.android/
> 
> 但我还没针对android做过2.x完整的调优

在fastjson2的readme中未找到任何有关Android版本的gradle或maven地址.
此项目的安卓版本是否上传到了maven中心仓库?

**Comment by Serendipithub** [comment]
请将readme修改一下, 加入或提示一下地址 `com.alibaba.fastjson2:fastjson2:2.0.3.android`

**Comment by wenshao** [comment]
已经发布到maven中央仓库
https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2/2.0.3.android/
