### ISSUE TITLE
[QUESTION]请问fastjson1中的ParserConfig.global.clearDeserializers() 在fastjson2有替代方案吗？

### ISSUE THREAD

**Issue by panaleica** [alibaba/fastjson2#2860]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
请问fastjson1中的ParserConfig.global.clearDeserializers() 在fastjson2有替代方案吗？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.53-SNAPSHOT/

最新的快照，增加了clear方法，可以如下方法使用
```java
JSONFactory.getDefaultObjectWriterProvider().clear();
JSONFactory.getDefaultObjectReaderProvider().clear();
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.53
问题已修复，请用新版本
