### ISSUE TITLE
[QUESTION] I am trying to read a number in JSONReader with Feature.UseBigDecimalForDoubles , but when i get a String while parsing of "0E-18"

### ISSUE THREAD

**Issue by satrajitN1** [alibaba/fastjson2#2866]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.53-SNAPSHOT/
问题已修复，请帮忙用2.0.53-SNAPSHOT版本验证，2.0.53版本预计在月底发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.53
问题已修复，请用新版本

**Comment by ForrestCai** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.53 问题已修复，请用新版本
@wenshao , 你好，最近2.0.52里发现security exception crash 漏洞， 下面网页里提到commit 'c9b25596692344d052978539120c0862b1f8c047' 可以fix掉。想和你确认下issue #2866的fix (2.0.53)同时可以解决这个漏洞么?
https://vulert.com/vuln-db/oss-fuzz-fastjson2-150335
