### ISSUE TITLE
[QUESTION] I am trying to read a number in JSONReader with Feature.UseBigDecimalForDoubles , but when i get a String while parsing of "0E-18" i get it as double

### ISSUE THREAD

**Issue by satrajitN1** [alibaba/fastjson2#2867]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

I am trying to read a number in JSONReader with Feature.UseBigDecimalForDoubles , but when i get a String while parsing of "0E-18" i get it as double, i Observed in  the code in line https://github.com/alibaba/fastjson2/blob/191c8c2d586e5db8817c15ca7e2ac464ee6e7273/core/src/main/java/com/alibaba/fastjson2/JSONReader.java#L3006-L3010
that we are directly returning the double value , why is this a expected behaviour is there anyway while parsing i can force this to parse as BigDecimal ?

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.53
问题已修复，请用新版本
