### ISSUE TITLE
[QUESTION] HH:mm:ss格式的时间无法解析为java.util.Date

### ISSUE THREAD

**Issue by KaiserDeng** [alibaba/fastjson2#2905]
`
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.annotation.JSONField;
import lombok.Data;
import java.util.Date;

@Data
public class TestOrder {

    @JSONField(format = "HH:mm:ss")
    private Date saleEndTime;

    public static void main(String[] args) {
        String s = "{\"saleEndTime\": \"23:00:00\"}";
        TestOrder order = JSON.parseObject(s, TestOrder.class);
        System.out.println(JSON.toJSONString(order));
    }
}
`
从fastjson升级到2.0.52后执行以上代码时，出现报错：
` Text '23:00:00' could not be parsed: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 23:00 of type java.time.format.Parsed`

请问我该如何解决该问题？

**Comment by KaiserDeng** [comment]
thanks

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.53
请用新版本
