### ISSUE TITLE
[BUG]JSONB反序列化LocalDate报错:name not support input : LOCAL_DATE -87

### ISSUE THREAD

**Issue by 237chenhao** [alibaba/fastjson2#2907]
### 问题描述
使用JSONB进行对象拷贝操作，例如：JSONB.parseObject(JSONB.toBytes(对象A), 目标类B.class)
如果类A中有LocalDate属性，类B没有，并且对象A的LocalDate属性不为null，那么上面的语句将会报错：
![image](https://github.com/user-attachments/assets/d8d3ad8b-c437-4653-b3d4-af26c308f5a8)

### 环境信息
*请填写以下信息：*

 - OS信息：  Mac
 - JDK信息： jdk17
 - 版本信息：Fastjson2 2.0.52
 

### 重现步骤
1、类A
![image](https://github.com/user-attachments/assets/de1f37a8-9eac-4e61-a4b6-8630b0f63dd6)
2、类B
![image](https://github.com/user-attachments/assets/4217d43f-d354-443e-b6a0-bf96898f9d45)
3、代码
![image](https://github.com/user-attachments/assets/38e236d0-c1dc-4ff7-ad95-5487d23297d4)
4、报错
![image](https://github.com/user-attachments/assets/d8d3ad8b-c437-4653-b3d4-af26c308f5a8)
### 期待的正确结果
正常反序列化，或者忽略目标类不存在的属性，设置了好像没用。

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.53
问题已修复，请用新版本
