### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhoujia** [alibaba/fastjson2#2916]
### 问题描述
*简要描述您碰到的问题。*
遇到特殊的报文信息，使用JSONObject.parseObject(param) 解析，会出现进程无限卡死，不释放的情况。

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB ， Windows11]
 - JDK信息： [e.g.： oracle1.8]
 - 版本信息：[e.g.：Fastjson2 2.0.43]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
        String param = "{\"event\":\"product.updated\",\"product\":{\"id\":20091219,\"shop_id\":454444,\"title\":\"my new T short6666661111\",\"handle\":\"my-new-t-short\",\"template_suffix\":\"product\",\"description\":\"<img src=\\\"\\\\\" />hahaha\",\"seo_title\":\"my new T short\",\"seo_description\":null,\"price\":0,\"compare_at_price\":0,\"cost_per_item\":0,\"sku\":null,\"taxable\":0,\"barcode\":\"undefined\",\"weight\":0,\"weight_unit\":null,\"requires_shipping\":0,\"inventory_policy\":0,\"quantity\":0,\"product_type_id\":3102721,\"vendor_id\":140200,\"added_via\":\"product_admin\",\"published_at\":\"2024-09-02 04:23:13\",\"deleted_at\":null,\"created_at\":\"2024-09-02 04:23:13\",\"updated_at\":\"2024-09-02 06:54:48\",\"active\":1,\"is_available_checkout\":1,\"active_for_bots\":0,\"simplybook_id\":0,\"minimum_quantity\":0,\"max_quantity\":0,\"minimum_quantity_count\":0,\"max_quantity_count\":0,\"total_units_sold\":0,\"kit\":0,\"page_link\":null,\"enable_multiple_currencies\":0,\"sales_page\":null,\"vsl\":null,\"google_merchant_status\":\"N\\u00e3o enviado\",\"product_default_variant\":{\"id\":154108551,\"product_id\":20091219,\"default\":1,\"title\":\"Default\",\"price\":\"0.00\",\"compare_at_price\":\"0.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":null,\"position\":1,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"undefined\",\"swatches\":null,\"length\":\"0.00\",\"width\":\"0.00\",\"height\":\"0.00\",\"dimension_unit\":null,\"weight\":0,\"weight_unit\":null,\"requires_shipping\":0,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:21\",\"updated_at\":\"2024-09-02 06:54:48\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},\"product_variants\":[{\"id\":154108542,\"product_id\":20091219,\"default\":0,\"title\":\"xl\\/blue\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108543,\"product_id\":20091219,\"default\":0,\"title\":\"xl\\/red\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108544,\"product_id\":20091219,\"default\":0,\"title\":\"xl\\/blac\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108545,\"product_id\":20091219,\"default\":0,\"title\":\"xxl\\/blue\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108546,\"product_id\":20091219,\"default\":0,\"title\":\"xxl\\/red\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108547,\"product_id\":20091219,\"default\":0,\"title\":\"xxl\\/blac\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108548,\"product_id\":20091219,\"default\":0,\"title\":\"xxxl\\/blue\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108549,\"product_id\":20091219,\"default\":0,\"title\":\"xxxl\\/red\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108550,\"product_id\":20091219,\"default\":0,\"title\":\"xxxl\\/blac\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]}],\"images\":[{\"id\":145093988,\"product_id\":20091219,\"position\":0,\"alt\":\"\",\"src\":\"static\\/products_images\\/64\\/0e\\/81\\/1725261715.jpg\",\"media_type\":\"image\",\"aspect_ratio\":\"1.00\",\"width\":225,\"height\":225,\"created_at\":\"2024-09-02 04:21:55\",\"updated_at\":\"2024-09-02 04:23:13\",\"url\":\"https:\\/\\/assets.mycartpanda.com\\/static\\/products_images\\/64\\/0e\\/81\\/1725261715.jpg\"}],\"kit_items\":[]}}\n";
        

System.out.println(JSONObject.parseObject(param));

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
可以报错，但是不能进程无限卡死。

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by mek1986** [comment]
@zhoujia 你提供的数据格式有问题
img标签src属性这里的反斜杠写法不合法，我给你修改了一下，你看下

> <img src=\\\"\\\\\" />

改成这样写了

> <img src=\\\"\\\" />

``` java []
public class Issue2916 {
    public static void main(String[] args) {
        String param = "{\"event\":\"product.updated\",\"product\":{\"id\":20091219,\"shop_id\":454444,\"title\":\"my new T short6666661111\",\"handle\":\"my-new-t-short\",\"template_suffix\":\"product\",\"description\":\"<img src=\\\"\\\" />hahaha\",\"seo_title\":\"my new T short\",\"seo_description\":null,\"price\":0,\"compare_at_price\":0,\"cost_per_item\":0,\"sku\":null,\"taxable\":0,\"barcode\":\"undefined\",\"weight\":0,\"weight_unit\":null,\"requires_shipping\":0,\"inventory_policy\":0,\"quantity\":0,\"product_type_id\":3102721,\"vendor_id\":140200,\"added_via\":\"product_admin\",\"published_at\":\"2024-09-02 04:23:13\",\"deleted_at\":null,\"created_at\":\"2024-09-02 04:23:13\",\"updated_at\":\"2024-09-02 06:54:48\",\"active\":1,\"is_available_checkout\":1,\"active_for_bots\":0,\"simplybook_id\":0,\"minimum_quantity\":0,\"max_quantity\":0,\"minimum_quantity_count\":0,\"max_quantity_count\":0,\"total_units_sold\":0,\"kit\":0,\"page_link\":null,\"enable_multiple_currencies\":0,\"sales_page\":null,\"vsl\":null,\"google_merchant_status\":\"N\\u00e3o enviado\",\"product_default_variant\":{\"id\":154108551,\"product_id\":20091219,\"default\":1,\"title\":\"Default\",\"price\":\"0.00\",\"compare_at_price\":\"0.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":null,\"position\":1,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"undefined\",\"swatches\":null,\"length\":\"0.00\",\"width\":\"0.00\",\"height\":\"0.00\",\"dimension_unit\":null,\"weight\":0,\"weight_unit\":null,\"requires_shipping\":0,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:21\",\"updated_at\":\"2024-09-02 06:54:48\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},\"product_variants\":[{\"id\":154108542,\"product_id\":20091219,\"default\":0,\"title\":\"xl\\/blue\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108543,\"product_id\":20091219,\"default\":0,\"title\":\"xl\\/red\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108544,\"product_id\":20091219,\"default\":0,\"title\":\"xl\\/blac\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108545,\"product_id\":20091219,\"default\":0,\"title\":\"xxl\\/blue\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108546,\"product_id\":20091219,\"default\":0,\"title\":\"xxl\\/red\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108547,\"product_id\":20091219,\"default\":0,\"title\":\"xxl\\/blac\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108548,\"product_id\":20091219,\"default\":0,\"title\":\"xxxl\\/blue\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108549,\"product_id\":20091219,\"default\":0,\"title\":\"xxxl\\/red\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]},{\"id\":154108550,\"product_id\":20091219,\"default\":0,\"title\":\"xxxl\\/blac\",\"price\":\"0.00\",\"compare_at_price\":\"20.00\",\"cost_per_item\":\"0.00\",\"sku\":\"\",\"aliexpress_sku\":\"\",\"position\":0,\"inventory_policy\":0,\"quantity\":0,\"prevent_out_of_stock_selling\":0,\"taxable\":0,\"barcode\":\"\",\"swatches\":null,\"length\":null,\"width\":null,\"height\":null,\"dimension_unit\":null,\"weight\":0.1,\"weight_unit\":null,\"requires_shipping\":1,\"has_digital_attachment\":0,\"enabled_shopify_redirect\":1,\"created_at\":\"2024-09-02 04:23:14\",\"updated_at\":\"2024-09-02 04:23:14\",\"deleted_at\":null,\"nimble_sku\":null,\"image_id\":\"\",\"mobile_price\":0,\"variant_image\":[]}],\"images\":[{\"id\":145093988,\"product_id\":20091219,\"position\":0,\"alt\":\"\",\"src\":\"static\\/products_images\\/64\\/0e\\/81\\/1725261715.jpg\",\"media_type\":\"image\",\"aspect_ratio\":\"1.00\",\"width\":225,\"height\":225,\"created_at\":\"2024-09-02 04:21:55\",\"updated_at\":\"2024-09-02 04:23:13\",\"url\":\"https:\\/\\/assets.mycartpanda.com\\/static\\/products_images\\/64\\/0e\\/81\\/1725261715.jpg\"}],\"kit_items\":[]}}\n";
        System.out.println(JSONObject.parseObject(param));
    }
}
```

**Comment by zhoujia** [comment]
我也知道数据是不合法的, 这个数据是三方传来的, 结果导致大量进程卡死.  我觉得这个情况不应该出现.

**Comment by mek1986** [comment]
> 我也知道数据是不合法的, 这个数据是三方传来的, 结果导致大量进程卡死. 我觉得这个情况不应该出现.

在未来版本2.0.53中，该问题已经修复。
会抛异常提示非法输入。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.53
问题已修复，请用新版本
