### ISSUE TITLE
JsonArray toJavaList转换问题[BUG]

### ISSUE THREAD

**Issue by idwangmo** [alibaba/fastjson2#296]
### 问题描述

此处代码，在转换为非map类型的时候会提示TODO这个异常 ，可以看到并未对其他类型的转换做出任何的实现

https://github.com/alibaba/fastjson2/blob/da5448de16756eebfa21c7652acb3c8123d96db9/fastjson1-compatible/src/main/java/com/alibaba/fastjson/JSONArray.java#L803

但是在FastJSON老版本中，可以看到这个地方是可以支持任意类型的

https://github.com/alibaba/fastjson/blob/69c0d2aa16d834c38b4a9ea8b7048aa3ffd362c6/src/main/java/com/alibaba/fastjson/JSONArray.java#L453

示例代码如下：

```java
JSONArray.parseArray(i).toJavaList(String.class)
```

**Comment by wenshao** [comment]
问题已修复，修复代码 https://github.com/alibaba/fastjson2/commit/eb6a24421e23d21144c0960d75ba9100987c5635

你可以先用2.0.5-SNAPSHOT版本帮忙验证，2.0.5正式版本预计在5月31日前发布。
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.5-SNAPSHOT/

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
