### ISSUE TITLE
[BUG] com/alibaba/fastjson2/JSONObjectTest.kt 类名重复

### ISSUE THREAD

**Issue by imsai-sh** [alibaba/fastjson2#299]
### 问题描述
*简要描述您碰到的问题。*

src/test/java/com/alibaba/fastjson2/JSONObjectTest.kt
和
src/test/java/com/alibaba/fastjson2/JSONObjectTest.java
类名相同，编译错误

**Comment by wenshao** [comment]
问题已修复，谢谢反馈
