### ISSUE TITLE
关于性能和优化疑问

### ISSUE THREAD

**Issue by kraity** [alibaba/fastjson2#31]
我知道`fastjson2`为了性能做了一些手动内联, 从而减少调用栈. 但是我发现有些方法是可以优化的, 是否必须遵从内联格式从而不去优化这些方法.

**Comment by wenshao** [comment]
应该要根据所在环境进行优化，造成现状是因为手工内联的时候，没有做完根据上下文优化的事情，看到就提PR改进吧。

**Comment by kraity** [comment]
> 另外一个思路做法是 通过编译过程（如编译插件）来完（一些）成手动做的内联动作。

我也赞同您的观点, 通过编译时内联, 省去手工也还可以保障代码一致

**Comment by kraity** [comment]
> 应该要根据所在环境进行优化，造成现状是因为手工内联的时候，没有做完根据上下文优化的事情，看到就提PR改进吧。

好的谢谢温少, 我明白了您的观点。
