### ISSUE TITLE
[QUESTION]序列化的时候如何将驼峰格式转成下划线模式

### ISSUE THREAD

**Issue by fantasy-Kx** [alibaba/fastjson2#3109]
我需要在序列化的时候将字段转成下划线格式，看了下文档除了使用@JSONField和通过JSONFactory.getDefaultObjectWriterProvider()进行全局配置外貌似没有其它的办法了，我想在JSON.toJsonString()的时候进行设置，请问如何配置，因为我不需要一个全局的配置，对接到不同平台有不同的序列化方式

**Comment by rowstop** [comment]
```java
JSONWriter.Context writeContext = JSONFactory.createWriteContext(
                new ObjectWriterProvider(
                        PropertyNamingStrategy.SnakeCase
                )
        );
        String jsonString = JSON.toJSONString(new Bean().setSayHi("abc"), writeContext);
```

**Comment by fantasy-Kx** [comment]
> ```java
> JSONWriter.Context writeContext = JSONFactory.createWriteContext(
>                 new ObjectWriterProvider(
>                         PropertyNamingStrategy.SnakeCase
>                 )
>         );
>         String jsonString = JSON.toJSONString(new Bean().setSayHi("abc"), writeContext);
> ```

非常感谢
