### ISSUE TITLE
[BUG][v.2.0.4]在字段上使用JSONWriter.Feature.WriteEnumsUsingName 没效果

### ISSUE THREAD

**Issue by op520f** [alibaba/fastjson2#314]
### 问题描述
*简要描述您碰到的问题。*
在对象字段上加上	@JSONField(serializeFeatures = {JSONWriter.Feature.WriteEnumsUsingName})
用JSON.toJSONString(o) 输出，枚举字段还是反序列化成index，没有用name。
但如果用JSON.toJSONString(o, JSONWriter.Feature.WriteEnumsUsingName) 是输出枚举的名称。
<img width="503" alt="屏幕截图 2022-05-23 012317" src="https://user-images.githubusercontent.com/20180905/169707642-7caa6acc-956d-47b2-9f5a-90b85d4cb92a.png">
<img width="478" alt="屏幕截图 2022-05-23 012347" src="https://user-images.githubusercontent.com/20180905/169707649-980b5061-9871-4fd9-942b-ff7325c976d6.png">
<img width="496" alt="屏幕截图 2022-05-23 012449" src="https://user-images.githubusercontent.com/20180905/169707697-9b6c57d5-94e4-497a-b13a-85d2b83e45b9.png">

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
