### ISSUE TITLE
[BUG] 解决/v2/api-docs获取不到内容导致获取不到API页面内容的问题

### ISSUE THREAD

**Issue by logan2013** [alibaba/fastjson2#317]
Swagger的Json处理，解决/v2/api-docs获取不到内容导致获取不到API页面内容的问题

**Comment by VictorZeng** [comment]
@logan2013 收到，请稍后~

**Comment by logan2013** [comment]
我也写了一个writer，最终调用writeString，但是序列化出来的是一个字符串，感觉不是合理哈

**Comment by VictorZeng** [comment]
@logan2013 除了序列化成字符串暂时没想到其他好办法~~~

**Comment by VictorZeng** [comment]
可以再快照版本提前使用`SwaggerJsonWriter`
```xml
<dependency>
    <groupId>com.alibaba.fastjson2</groupId>
    <artifactId>fastjson2-extension</artifactId>
    <version>2.0.5-SNAPSHOT</version>
</dependency>
```
```java
JSON.register(springfox.documentation.spring.web.json.Json.class, SwaggerJsonWriter.INSTANCE);
```

**Comment by CodeKjm** [comment]
你好，没看懂这行代码在哪里实现？需要自定义一个类吗？
JSON.register(springfox.documentation.spring.web.json.Json.class, SwaggerJsonWriter.INSTANCE);

**Comment by CodeKjm** [comment]
我看最新版本的SwaggerJsonWriter和OpenApiJsonWriter都不存在，是没合并分支吗？

**Comment by VictorZeng** [comment]
@CodeKjm 已经内置实现，不需要单独注册了。
