### ISSUE TITLE
[FEATURE] 会支持解析XML吗

### ISSUE THREAD

**Issue by gongxuanzhang** [alibaba/fastjson2#3178]
目前Fastjson的API非常好用，这是一直使用的主要原因。
但是当需要解析xml或者是其他应用格式的时候，不得不使用其他库，一般来说会使用jackson。
这样项目中出现两个json解析库很别扭。
如果fastjson支持xml解析就非常棒了

**Comment by wenshao** [comment]
不会，完全不考虑xml

**Comment by gongxuanzhang** [comment]
感谢你的回复
