### ISSUE TITLE
[QUESTION]SwaggerJsonSerializer或ObjectSerializer是不是不计划支持了？

### ISSUE THREAD

**Issue by kervin521** [alibaba/fastjson2#324]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

**Comment by VictorZeng** [comment]
see https://github.com/alibaba/fastjson2/issues/317#issuecomment-1134352059

**Comment by wenshao** [comment]
ObjectSerializer已经有兼容方案了，这个周末发布的2.0.5会带上

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本

**Comment by zhengju5683** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.5 问题已修复，请用新版本

请问如何“兼容方案”,具体怎么用，我用的2.0.7怎么没有找到这个类呢
