### ISSUE TITLE
[QUESTION]  jsonObject.getObject 不支持解析数组了吗?

### ISSUE THREAD

**Issue by hqb72** [alibaba/fastjson2#326]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
    public static void main(String[] args) throws Exception {
        JSONObject obj = new JSONObject();
        obj.put("issue", "3");
        obj.put("company", "aaa");
        obj.put("signer", "bbbb");
        obj.put("title", "cccc");
        obj.put("overview", "ddddd");
        obj.put("details", new String[]{"eeee", "ffff", "eeee"});
        obj.put("datetime", "2022-05-24 14:50:32");
        obj.put("onduty", "gggg");
        obj.put("review", "hhhh");
        String x = JSON.toJSONString(obj);
        System.out.println(x);
        JSONObject jsonObject = JSON.parseObject(x);
        String[] details = jsonObject.getObject("details", String[].class);
        System.out.println(Arrays.toString(details));
    }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
[eeee, ffff, eeee]

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
Exception in thread "main" java.lang.UnsupportedOperationException

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://user-images.githubusercontent.com/30142521/169972081-d8e14607-b225-4c27-afa4-ad12e922a7c3.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.5-SNAPSHOT/
2.0.5-SNAPSHOT版本中已经修复这个问题，2.0.5正式版本预计在本周发布

**Comment by hqb72** [comment]
收到

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
