### ISSUE TITLE
[QUESTION]com.alibaba.fastjson2.JSONArray.of 不等于com.alibaba.fastjson.JSONArray.parseArray

### ISSUE THREAD

**Issue by ipzpy** [alibaba/fastjson2#331]
com.alibaba.fastjson2.JSONArray.of()  != com.alibaba.fastjson.JSONArray.parseArray()
请问fastjson2中什么方法可以替代com.alibaba.fastjson.JSONArray.parseArray()方法？

**Comment by hujian0923** [comment]
JSON.parseArray(text);

**Comment by wenshao** [comment]
2.0.5会补上这个兼容方法，在此之前，你可以用 hujian0923 说的JSON.parseArray方法

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
