### ISSUE TITLE
升级时，SofabootRpcSpringContextInitializer中依赖的fastjson1.0的问题

### ISSUE THREAD

**Issue by lovemsy** [alibaba/fastjson2#332]
目前使用的fastjson为1.2.76，升级使用了兼容版2.0.4，
但是项目中使用了sofaboot
    <parent>
        <groupId>com.alipay.sofa</groupId>
        <artifactId>sofaboot-enterprise-dependencies</artifactId>
        <version>3.4.1</version>
    </parent>
    
在替换项目中的fastjson时，会发现项目启动不起来，定位问题发现
`public class AntVipPropertyFilter implements PropertyFilter`
AntVipPropertyFilter 实现了1.0的PropertyFilter接口，这个接口可否在兼容版本中定义

**Comment by lovemsy** [comment]
不是fastjson2,我引用的是兼容版
`            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>2.0.4</version>
            </dependency>
`
因为有很多jar使用了1.2.x版本的包

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.5-SNAPSHOT/
这个兼容版也有2.0.5-SNAPSHOT，能否帮忙做下验证

**Comment by lovemsy** [comment]
![123](https://user-images.githubusercontent.com/45815308/170186848-ea86ca73-cd29-4c84-9fff-91df7e5d61bb.png)
NameFilter 这个接口还是有问题

**Comment by wenshao** [comment]
可以更新快照再验证下么？

**Comment by lovemsy** [comment]
> 可以更新快照再验证下么？

目前[fastjson-2.0.5-20220525.071529-26.pom] 这个还是又报错

**Comment by lovemsy** [comment]
![image](https://user-images.githubusercontent.com/45815308/170234470-fe44b0b5-380d-4488-89cb-579589db184a.png)
这个下面的很多导包都是fastjson2的，这个应该都做不到兼容吧

**Comment by lovemsy** [comment]
![image](https://user-images.githubusercontent.com/45815308/170460108-16589353-61c2-46f9-af0c-55856960c3fa.png)
这两个是没有吧，我看最新的也没有这两个类
`import com.alibaba.fastjson2.support.AwtRederModule;
import com.alibaba.fastjson2.support.AwtWriterModule;`

**Comment by lovemsy** [comment]
![image](https://user-images.githubusercontent.com/45815308/170460108-16589353-61c2-46f9-af0c-55856960c3fa.png)
这两个是没有吧，我看最新的也没有这两个类
`import com.alibaba.fastjson2.support.AwtRederModule;
import com.alibaba.fastjson2.support.AwtWriterModule;`

**Comment by wenshao** [comment]
在fastjson2-extension
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2-extension/2.0.5-SNAPSHOT/

**Comment by lovemsy** [comment]
> 在fastjson2-extension https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2-extension/2.0.5-SNAPSHOT/

我同时引用这两个pom，目前是可以使用了
 `           <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2-extension</artifactId>
                <version>2.0.4</version>
            </dependency>

            
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>2.0.5-SNAPSHOT</version>
            </dependency>
  `

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
