### ISSUE TITLE
[FEATURE] JSON.parseObject(jsonString, Map.class)将json字符串转为Map时，Date类型没有自动转换为日期类型，而是转成了String类型

### ISSUE THREAD

**Issue by sutubaba** [alibaba/fastjson2#336]
JSON.parseObject(jsonString, Map.class)将json字符串转为Map时，Date类型没有自动转换为日期类型，而是转成了String类型

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by sutubaba** [comment]
```
HashMap<String, Object> map = new HashMap<>();
Date date = new Date();
map.put("date", date);
String jsonString = JSON.toJSONString(map);
Map result = JSON.parseObject(jsonString, Map.class);
```

fastjson1 result中date的类型：
<img width="340" alt="image" src="https://user-images.githubusercontent.com/39782619/171591432-ad403985-9cd3-4879-b3e4-f0ec6f1fac62.png">
fastjson2 result中date的类型:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/39782619/171591594-81376b1e-450e-4fcf-b8c4-3779828e42e5.png">

**Comment by wenshao** [comment]
```java
    HashMap<String, Object> map = new HashMap<>();
        Date date = new Date();
        map.put("date", date);
        String jsonString = JSON.toJSONString(map, JSONWriter.Feature.WriteClassName);
        Map result = JSON.parseObject(jsonString, Map.class);
        assertEquals(date.getTime(), ((Date) result.get("date")).getTime());
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
