### ISSUE TITLE
[BUG] JSON字符串转换为JSONObject时得到的结果与预期不一致

### ISSUE THREAD

**Issue by a1209577113** [alibaba/fastjson2#338]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - 版本信息：[e.g.：Fastjson2 2.0.4]
 

### 重现步骤
*如何操作可以重现该问题：*

预期的结果：{"@type":"com.af.v4.system.api.model.LoginUser","expireTime":1653496818784,"ipaddr":"127.0.0.1","loginTime":1653453618784,"sysUser":{"@type":"com.af.v4.system.api.domain.SysUser","password":"1","userId":3810,"userName":"zkk"},"token":"e3322327-9a35-4715-a7b5-387b20530c0e","userid":3810,"username":"zkk"}
得到的结果：
{"@type":"expireTime","":1653496818784,"ipaddr":"127.0.0.1","loginTime":1653453618784,"sysUser":{"@type":"com.af.v4.system.api.domain.SysUser","password":"1","userId":3810,"userName":"zkk"},"token":"e3322327-9a35-4715-a7b5-387b20530c0e","userid":3810,"username":"zkk"}

```java
public static void main(String[] args) {
        System.out.println(JSON.parse("{\"@type\":\"com.af.v4.system.api.model.LoginUser\",\"expireTime\":1653496818784,\"ipaddr\":\"127.0.0.1\",\"loginTime\":1653453618784,\"sysUser\":{\"@type\":\"com.af.v4.system.api.domain.SysUser\",\"password\":\"1\",\"userId\":3810,\"userName\":\"zkk\"},\"token\":\"e3322327-9a35-4715-a7b5-387b20530c0e\",\"userid\":3810,\"username\":\"zkk\"}"));
}
```

### 期待的正确结果
{"@type":"expireTime","":1653496818784,"ipaddr":"127.0.0.1","loginTime":1653453618784,"sysUser":{"@type":"com.af.v4.system.api.domain.SysUser","password":"1","userId":3810,"userName":"zkk"},"token":"e3322327-9a35-4715-a7b5-387b20530c0e","userid":3810,"username":"zkk"}

**Comment by a1209577113** [comment]
期待的正确结果描述错了，应该是
{"@type":"com.af.v4.system.api.model.LoginUser","expireTime":1653496818784,"ipaddr":"127.0.0.1","loginTime":1653453618784,"sysUser":{"@type":"com.af.v4.system.api.domain.SysUser","password":"1","userId":3810,"userName":"zkk"},"token":"e3322327-9a35-4715-a7b5-387b20530c0e","userid":3810,"username":"zkk"}

**Comment by Grunning** [comment]
![image](https://user-images.githubusercontent.com/10669974/170230700-429822ee-30fc-4435-80d3-cd9b57fc025c.png)
不会是这个问题吧，内部用的关键字，刚好被你踩了雷👀

**Comment by a1209577113** [comment]
> ![image](https://user-images.githubusercontent.com/10669974/170230700-429822ee-30fc-4435-80d3-cd9b57fc025c.png) 不会是这个问题吧，内部用的关键字，刚好被你踩了雷👀

我是用redission反序列化时发现的问题，不管怎么写都没法把json串转回bean

**Comment by Grunning** [comment]
> > ![image](https://user-images.githubusercontent.com/10669974/170230700-429822ee-30fc-4435-80d3-cd9b57fc025c.png) 不会是这个问题吧，内部用的关键字，刚好被你踩了雷👀
> 
> 我是用redission反序列化时发现的问题，不管怎么写都没法把json串转回bean

确实有bug，你可以改用toJSON()试试
`System.out.println(JSON.toJSON("{\"@type\":\"com.af.v4.system.api.model.LoginUser\",\"expireTime\":1653496818784,\"ipaddr\":\"127.0.0.1\",\"loginTime\":1653453618784,\"sysUser\":{\"@type\":\"com.af.v4.system.api.domain.SysUser\",\"password\":\"1\",\"userId\":3810,\"userName\":\"zkk\"},\"token\":\"e3322327-9a35-4715-a7b5-387b20530c0e\",\"userid\":3810,\"username\":\"zkk\"}"));`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
