### ISSUE TITLE
[BUG]2.0.4将jsonobject转化为类时报类型转换问题

### ISSUE THREAD

**Issue by cjdxhjj** [alibaba/fastjson2#340]
### 问题描述
*简要描述您碰到的问题。*
![41bb93d8dea820ff0ff9a874d90766f](https://user-images.githubusercontent.com/5616997/170194017-39453cf7-6324-495c-abdc-12181bf567c2.png)

### 环境信息
*请填写以下信息：*

 - OS信息：  centos 7
 - JDK信息： 17
 - 版本信息：2.0.4
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
