### ISSUE TITLE
[QUESTION]升级到 2.0.4 后依赖问题

### ISSUE THREAD

**Issue by sxpdy8571** [alibaba/fastjson2#345]
fastjson.jar是放在父 pom 里面的，子项目中继承了父 pom 的配置。
fastjson 升级到 2.0.4 后，子项目打包一直报找不到 'dependencies.dependency.version' for com.alibaba.fastjson2:fastjson2:jar is missing.

**Comment by wenshao** [comment]
再试下2.0.5，看问题是否还存在

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
