### ISSUE TITLE
注册ObjectWriter方法中，取defaultObjectWriterProvider方式错误[BUG]

### ISSUE THREAD

**Issue by tyu567567** [alibaba/fastjson2#349]
### 问题描述
com.alibaba.fastjson2.JSON#register(java.lang.reflect.Type, com.alibaba.fastjson2.writer.ObjectWriter<?>)
JSONFactory.defaultObjectWriterProvider.register(type, objectWriter); 
这里是不是应该改成
JSONFactory.getDefaultObjectWriterProvider().register(type, objectWriter)

**Comment by wenshao** [comment]
新的代码已经改了

**Comment by tyu567567** [comment]
看到了  关闭了
