### ISSUE TITLE
[BUG] 默认方式使用fastjson2进行反序列化，并未用到ASM生成动态代码

### ISSUE THREAD

**Issue by weissxu** [alibaba/fastjson2#352]
### 问题描述
使用方式：
 com.alibaba.fastjson2.JSON#parseObject(java.lang.String, java.lang.Class<T>)

过程：
fastjson2在反序列化时默认使用ObjectReaderCreatorASM创建ObjectReader，在ObjectReaderCreatorASM执行创建的过程中，有个match机制，默认情况下会是false，这样的话，从父类创建ObjectReader，最终使用的是Method.invoke的方式绑定字段。

```java
com.alibaba.fastjson2.reader.ObjectReaderCreatorASM#createObjectReader

for (FieldReader fieldReader : fieldReaderArray) {
    if (fieldReader.getMethod() != null) {
        match = false;
        break;
    }

    if (fieldReader instanceof FieldReaderReadOnly
            || fieldReader.isUnwrapped()
    ) {
        match = false;
        break;
    }
}

...

if (!match) {
    return super.createObjectReader(objectClass, objectType, fieldBased, modules);
}
```

虽然最终可以正常的反序列化，并绑定对象，请问这是正常逻辑吗？这个过程中的核心逻辑并未用到ASM的机制？

### 环境信息
*请填写以下信息：*

 - 版本信息：[Fastjson2 2.0.3，2.0.4]
 

### 期待的正确结果
*使用ASM机制动态生成ObjectReader子类，进行反序列化*

**Comment by wenshao** [comment]
这个问题是中间改错了，已经修复了，预计在周末发布的2.0.5版本中修复。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
