### ISSUE TITLE
[FEATURE]对于给定的复杂类型的json，可以去掉value中字符串的前后空格

### ISSUE THREAD

**Issue by keepourfaith** [alibaba/fastjson2#353]
### 请描述您的需求或者改进建议
对于给定的json字符串，去掉其前后空格。比如：  
{ "aNumber": 0, "aString": "   string   " }
=> { "aNumber": 0, "aString": "string" }

给定的json中内容没有规律，可能是复杂的json字符串：
{ "a": 0, "b": "0", "c": [...], "d": {...}, "e":[{...}], "f": {[...]} }

### 请描述你建议的实现方案
类似议题：Java – Can Jackson be configured to trim leading/trailing whitespace from all string properties  
https://itecnote.com/tecnote/java-can-jackson-be-configured-to-trim-leading-trailing-whitespace-from-all-string-properties/

### 描述您考虑过的替代方案
暂无

#### 附加信息
暂无

**Comment by timnick-snow** [comment]
you can use ValueFilter

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
