### ISSUE TITLE
[QUESTION]从1.2.XX版本升级到到2.0.4版本 cannot be cast to org.springframework.security.core.GrantedAuthority

### ISSUE THREAD

**Issue by sqlFC** [alibaba/fastjson2#354]
如题
java.lang.ClassCastException: com.alibaba.fastjson2.JSONObject cannot be cast to org.springframework.security.core.GrantedAuthority

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本

**Comment by liyuu127** [comment]
2.0.10 还是发生这个错误，有解决方案么，试了不同的环境，相同版本的ide和jdk有的会发生有的不会发生
