### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cugftp** [alibaba/fastjson2#355]
### 问题描述
*简要描述您碰到的问题。*
 fastjson2反序列化的字符串中包含汉字的unicode编码，报错

**Comment by wenshao** [comment]
能提供重现问题的testcase和fastjson2版本号么？

**Comment by cugftp** [comment]
testcase: {"code": "00", "msg": "\u64cd\u4f5c\u6210\u529f.", "result": [{"id": "d2303af53f444d9fa965d499d4976c69", "tag_list": [], "tip_tag_list": [{"tag": "\u89e3\u51b3", "tag_weight": 0.683}]}]}
fastjson2版本是：2.0.4

**Comment by wenshao** [comment]
我测试2.0.6是好的，你用2.0.6试一下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
