### ISSUE TITLE
[FEATURE]兼容fastjson特性BeforeFilter，AfterFilter

### ISSUE THREAD

**Issue by supenBenny** [alibaba/fastjson2#359]
### 请描述您的需求或者改进建议
*序列化时在最前或最后添加内容*
*fastjson1有BeforeFilter，AfterFilter可以实现，fastjson2中没有找到相关方法*

### 请描述你建议的实现方案
*用户表有部门ID，希望在转json时可以动态增加部门名称字段*
`public interface PropertyPreFilter extends Filter {
   default void process(JSONWriter writer, Object source, String name,Object value){
          
   }
}`
*有JSONWriter，原对象、属性名、属性值，便可追加一个属性*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
