### ISSUE TITLE
fastjson2:2.0.4android运行出错，缺少Ljava/time/ZoneId[BUG]

### ISSUE THREAD

**Issue by fengzehao** [alibaba/fastjson2#360]
### 问题描述
*使用最新版本的包在android设备上运行出错，报错信息为java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：android 7.1.2]
 - JDK信息： [e.g.：JavaVersion.VERSION_11]
 - 版本信息：[e.g.：Fastjson2 2.0.4.android]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 执行下述代码
`            String jsonStr = "{\"msg\":\"test\"}";
            com.alibaba.fastjson2.JSONObject jsonObject = com.alibaba.fastjson2.JSON.parseObject(jsonStr);`
2. 出现 `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;` 错误
```java
//可在此输入示例代码
String jsonStr = "{\"msg\":\"test\"}";
com.alibaba.fastjson2.JSONObject jsonObject = com.alibaba.fastjson2.JSON.parseObject(jsonStr);
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
正确解析

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
2022-05-27 09:44:23.731 5462-5519/com.demo.example E/MonitorLogger: [OkHttp Dispatcher] crash: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
        at com.alibaba.fastjson2.JSONReader.<clinit>(JSONReader.java:30)
        at com.alibaba.fastjson2.JSONReader.of(JSONReader.java:1871)
        at com.alibaba.fastjson2.JSON.parseObject(JSON.java:81)
        .......
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
@kraity 帮看下这个问题

**Comment by wenshao** [comment]
目前是强依赖java.time API的，需要Android API Level 26，也就是只支持Android 8以上版本

**Comment by fengzehao** [comment]
> 目前是强依赖java.time API的，需要Android API Level 26，也就是只支持Android 8以上版本

好的，谢谢
