### ISSUE TITLE
[QUESTION] 全局配置

### ISSUE THREAD

**Issue by feelinglin** [alibaba/fastjson2#361]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
如何在调用诸如：JSON.toJSONString()等方法时，不用手动添加各种Feature，是否有一个全局配置的地方？我知道有FastJsonConfig，但貌似是用于Message Converter的

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本

JSON类增加了config方法，用于配置全局Features
