### ISSUE TITLE
[BUG]  because "this.defaultCreator" is null -- JSON.parseObject(）

### ISSUE THREAD

**Issue by countree** [alibaba/fastjson2#362]
### 问题描述
*简要描述您碰到的问题。*
Cannot invoke "java.util.function.Supplier.get()" because "this.defaultCreator" is null
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.defaultCreator" is null
	at com.alibaba.fastjson2.reader.ObjectReader3.readObject(ObjectReader3.java:233)
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:174)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258)

### 环境信息
*请填写以下信息：*

 - OS信息：  win10
 - JDK信息：jdk17
 - 版本信息：fastjson2  2.0.4
 

### 重现步骤
*如何操作可以重现该问题：*

```java
String text = "{\"username\":\"dfs\",\"name\":\"电风扇\",\"exception\":\"\"}";
JSON.parseObject(text, User.class);

//执行就报异常
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.defaultCreator" is null
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
User类的代码能提供下么？

**Comment by countree** [comment]
我知道了，应该是有个Exception的字段，删掉后就正常了。
```
@Data
public class User{
 private BusinessException exception;
}
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
