### ISSUE TITLE
[BUG] Fastjson 1.2.* 进行JSON.toJSONString时，WriteMapNullValue并没有默认为false

### ISSUE THREAD

**Issue by WindStorm2013** [alibaba/fastjson2#364]
### 问题描述
Fastjson 1.2.* 进行JSON.toJSONString时，WriteMapNullValue并没有默认为false

### 环境信息
 - OS信息：  Windows10
 - JDK信息： 1.8.0 211
 - 版本信息：Fastjson 1.2.83
 

### 重现步骤
1、创建JAVABEAN：
```java
@Data
public class TestBean {

	private String msg;

	private TestBean bean;

}
```
2、main函数运行：
TestBean bean = new TestBean();
System.out.println(JSON.toJSONString(bean, SerializerFeature.WriteNullStringAsEmpty));

3、执行输出结果：
{"bean":null,"msg":""}

### 期待的正确结果
{"msg":""}

**Comment by wenshao** [comment]
WriteNullStringAsEmpty 启用的时候，WriteNulls也会同时启用，设计成这样的。
