### ISSUE TITLE
[FEATURE] fast不fast我不知道，别天天爆漏洞就行，把业界信誉霍霍光了

### ISSUE THREAD

**Issue by V0idk** [alibaba/fastjson2#366]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by yanrongzhen** [comment]
你可以选择不使用

**Comment by AdminQQZ** [comment]
你白嫖，还有脾气了？

**Comment by AdminQQZ** [comment]
不用就滚蛋

**Comment by V0idk** [comment]
> 你白嫖，还有脾气了？

不好意思，从没用过
