### ISSUE TITLE
简单了尝试了几个常用方法，发现都已经不兼容了~

### ISSUE THREAD

**Issue by xiangyunup** [alibaba/fastjson2#37]
JSONObject.parseObject(var)，这个方法被移除了，需要指定一个转换类型，改为：JSONObject.parseObject(var,JSONObject.class)
JSONArray 同样的道理；查看源码发现这2个都已经不在继承JSON 类，这样划分的更清晰了，但是如果是老项目的话，估计就有很多混用的需要修改了；

还发现一个问题，toJavaObject() 这个方法虽然还在，但是实现方式不一样了，经过简单的测试，发现不能直接转换成Map.class;
String str = "{\"test\":\"123465\"}";
JSONObject json = JSON.parseObject(str);
System.out.println(json.toJavaObject(Map.class));  // 结果为空！
System.out.println(JSON.toJavaObject(json, Map.class));  // 结果为空！
System.out.println(JSON.toJavaObject(str, Map.class)); // 内容正确！
想要升级的，估计得好好思考一下了~

**Comment by wenshao** [comment]
毕竟所有的代码是重写的，确实要仔细测试验证。已有2155个testcase，但还是需要大家帮忙测试验证和反馈一段时间修复兼容问题。

需要你的支持帮忙验证和反馈。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
