### ISSUE TITLE
[BUG] JSON字符串无法解析 unclosed.str.lit u

### ISSUE THREAD

**Issue by jayzch** [alibaba/fastjson2#371]
### 问题描述
2.0.1版本正常升级到2.0.4后发生错误，解析JSON字符串时发生异常，怀疑为\u会导致异常
### 环境信息

 - OS信息： OS name: "linux", version: "5.10.84-10.3.al8.x86_64", arch: "amd64", family: "unix"
 - JDK信息：Java version: 11.0.15, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.15.0.9-2.al8.x86_64
 - 版本信息：Fastjson 2.0.4 兼容包
 

### 重现步骤
                WeixiaoUserInfoResp userInfoBody = JSON.parseObject(userInfoBodyString, WeixiaoUserInfoResp.class);

### 相关日志输出
 【{"errcode":0,"errmsg":"OK","weixiao_stu_id":"mmmmm","card_number":"1111111","name":"\u5f20\u7a0b\u6d69","identity_type":1,"data_source":0,"ocode":"1111111"}】

com.alibaba.fastjson.JSONException: unclosed.str.lit u
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:99)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:74)

**Comment by presenth7s** [comment]
可否提供复现步骤关于：userInfoBodyString && WeixiaoUserInfoResp

**Comment by jayzch** [comment]
> userInfoBodyString

userInfoBodyString的内容为 

{"errcode":0,"errmsg":"OK","weixiao_stu_id":"mmmmm","card_number":"1111111","name":"\u5f20\u7a0b\u6d69","identity_type":1,"data_source":0,"ocode":"1111111"}

**Comment by wenshao** [comment]
谢谢反馈，问题已修复。

https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.5-SNAPSHOT/

你可以用2.0.5-SNAPSHOT版本验证，2.0.5正式版预计在明天发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.5
问题已修复，请用新版本
