### ISSUE TITLE
JSONWriter.Feature.NullAsDefaultValue  "map": null

### ISSUE THREAD

**Issue by axinger** [alibaba/fastjson2#372]
### 问题描述
*简要描述您碰到的问题。*
序列化 map 还是为null
config.setWriterFeatures( JSONWriter.Feature.NullAsDefaultValue)  
map返回为null  "map": null,

### 环境信息
*请填写以下信息：*

springboot 2.6.3
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.4]
 
```java

    @Bean
    public FastJsonHttpMessageConverter fastJsonHttpMessageConverter() {

        FastJsonHttpMessageConverter messageConverter = new FastJsonHttpMessageConverter();
        FastJsonConfig config = messageConverter.getFastJsonConfig();

        config.setReaderFeatures(JSONReader.Feature.FieldBased, JSONReader.Feature.SupportArrayToBean);
        config.setDateFormat("yyyy-MM-dd HH:mm:ss");
        config.setWriterFeatures(
                JSONWriter.Feature.PrettyFormat
                , JSONWriter.Feature.NullAsDefaultValue

        );
        messageConverter.setFastJsonConfig(config);
        messageConverter.setDefaultCharset(StandardCharsets.UTF_8);
        messageConverter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));

        return messageConverter;

    }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
不应该为 "map": {}  的嘛

**Comment by wenshao** [comment]
现在当存在NullAsDefaultValue是，null值是自动生效的

**Comment by axinger** [comment]
@wenshao WriteNulls值是自动生效的 , 那map为空时,输出  "map": null,  和  "map": {} 哪个是预期值呢?

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

问题已经修复，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
