### ISSUE TITLE
JSONPath set

### ISSUE THREAD

**Issue by wenkang-du** [alibaba/fastjson2#379]
JSONObject jsonObject=new JSONObject();
        JSONPath.set(jsonObject,"a/0",1);
        JSONPath.set(jsonObject,"a/1",2);
        System.out.println(jsonObject);

版本:2.0.5
期待{"a":[1,2]} 实际 {"a":2}

**Comment by wsxe9988** [comment]
麻烦请提供下能够复现该问题的case,

**Comment by wenkang-du** [comment]
已经提供了

**Comment by wenkang-du** [comment]
> 麻烦请提供下能够复现该问题的case,

已经重新编辑issue了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6

已经支持，请用新版本，如下：

```java
        JSONObject object = JSONObject.of("item", 1);
        JSONPath path = JSONPath.of("$.item");
        path.set(object, 2, JSONReader.Feature.DuplicateKeyValueAsArray);

        assertEquals(1, object.size());
        assertEquals(JSONArray.class, object.get("item").getClass());
        assertEquals(2, ((Collection) object.get("item")).size());
        assertEquals("[1,2]", object.get("item").toString());
```

**Comment by wenkang-du** [comment]
JSONObject jsonObject = new JSONObject();
        JSONPath.set(jsonObject, "a/0/b", 1);
        System.out.println(jsonObject);

期待 {"a":[{"b":1}]},依然不符合预期
