### ISSUE TITLE
@JSONField(format="")设置无效

### ISSUE THREAD

**Issue by youandeanyou** [alibaba/fastjson2#380]
2.0.5版本中，实体类中时间字段设置@JSONField(format="")注解后，只有JSON.toJSONString()可以生效，但对外输出只依赖全局设置的dateFormat。

示例代码：
https://github.com/youandeanyou/springboot-demo
访问 http://[localhost:8081/test](http://localhost:8081/test) 
期望结果：{"current":"2022-05-30 10:35:56","history":"2022-05-30 10","tomorrow":"2022-05-30 10:35","yesterday":"2022-05-30"}
实际结果：{"current":"2022-05-30 10:35:56","history":"2022-05-30 10:35:56","tomorrow":"2022-05-30 10:35:56","yesterday":"2022-05-30 00:00:00"}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

问题已经修复，请用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by alon-sys** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/
> 
> 问题已经修复，请用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

温少，我想问一下，这快照如何引用，仓库地址要改成哪个？

**Comment by wenshao** [comment]
快照仓库
https://oss.sonatype.org/content/repositories/snapshots/

**Comment by youandeanyou** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/
> 
> 问题已经修复，请用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

快照版本fastjson2-2.0.6-20220531.043509-17中，问题依然存在；同时，https://github.com/alibaba/fastjson2/issues/363#issue-1250414862 所述问题也再次出现。

**Comment by xionggit** [comment]
有一个问题，和这个bug是类似的，在fastjson1中，设置所有date 的默认格式可以这样写
JSON.DEFFAULT_DATE_FORMAT= "yyyyMMdd";
String json = JSON.toJSONString(object,SerializerFeature.WriteDateUseDateFormat);

但是在fastjson2的JSONWrite.Feature中好像不支持了？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本

**Comment by wenshao** [comment]
@youandeanyou @xionggit 不同的问题不要在同一个issue里讨论，要不然会漏了
