### ISSUE TITLE
fastjosn date类型反序列化报错

### ISSUE THREAD

**Issue by rw12306** [alibaba/fastjson2#381]
使用版本：fastjson2-2.0.4.jar

https://user-images.githubusercontent.com/42023195/170903416-ea183b33-5760-41ef-94b1-69d238c4a08e.png

这个日期是Date类型,直接给我序列化为Long了，结果再反序列化的时候就报错了

https://user-images.githubusercontent.com/42023195/170903509-b8d9549c-7b3d-4eea-9539-d47d946a6fe1.png

使用Byte类型也是，反序列化出来成Integer 了，反序列化回来Byte 的字段变成了Integer ， 也是直接报Integer 不能强制转换为Byte

**Comment by wenshao** [comment]
你能提供下你怎么序列化的代码么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/
问题已经修复，请用2.0.7-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
