### ISSUE TITLE
JSONB 序列化和反序列化 List<Enum> 枚举数组属性 解析错误

### ISSUE THREAD

**Issue by dyj2012** [alibaba/fastjson2#385]
![499192](https://user-images.githubusercontent.com/37611109/170990477-204fc61f-418e-4fc6-849d-7bd0f4bf9e1a.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/
问题已经修复，你帮忙用2.0.6-SNAPSHOT验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
已经支持，请用新版本
