### ISSUE TITLE
[BUG]Springboot中集成spring-doc 时(不是Swagger2)，将json对象转成了json字符串，导致接口文档无法显示

### ISSUE THREAD

**Issue by wangyatong** [alibaba/fastjson2#387]
fastjson2测试版本:2.0.5
jdk版本:OracleJDK 17.0.3
springboot版本:2.7.0
springdoc版本:1.6.9

"{\"openapi\":\"3.0.1\",\"info\":{\"title\":\"OpenAPI definition\",\"version\":\"v0\"},\"servers\":[{\"url\":\"http://localhost:8099\",\"description\":\"Generated server url\"}],\"paths\":{},\"components\":{}}"

**Comment by VictorZeng** [comment]
@wangyatong 这样应该可以解决您的问题
```xml
<dependency>
    <groupId>com.alibaba.fastjson2</groupId>
    <artifactId>fastjson2-extension</artifactId>
    <version>2.0.6-SNAPSHOT</version>
</dependency>
```
```java
JSON.register(String.class, OpenApiJsonWriter.INSTANCE);
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2-extension/2.0.6-SNAPSHOT/

问题已经修复，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by duanluan** [comment]
就等发布了

**Comment by duanluan** [comment]
![image](https://user-images.githubusercontent.com/14957667/171993556-ea023526-42a4-42e6-b1c6-c0dbd7b799ec.png)
![image](https://user-images.githubusercontent.com/14957667/171993449-f4cfe35b-5188-442e-89e3-fd620ab18d3e.png)
![image](https://user-images.githubusercontent.com/14957667/171993469-24524c72-7e08-4311-8d48-ea588d4665d4.png)

**Comment by VictorZeng** [comment]
该问题已将在2.0.6版本修复 即将发布~

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/
问题已修复，请帮忙用2.0.27-SNAPSHOT版本验证

**Comment by duanluan** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.27-SNAPSHOT/ 问题已修复，请帮忙用 2.0.27-SNAPSHOT 版本验证

可以了。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.27
请用新版本

**Comment by telechow** [comment]
@wenshao 
2.0.27好像还是不行。
![image](https://user-images.githubusercontent.com/9656433/230769802-1e5c4040-fbed-41fa-bd67-3228febc9156.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.28-SNAPSHOT/
问题已修复，请帮忙用2.0.28-SNAPSHOT版本验证，2.0.28预计在周末发布（4月15日）

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
请用新版本

**Comment by brokenes** [comment]
使用fastjson2版本2.0.36，对应springboot 2.7.9还是有问题，请求返回josn
