### ISSUE TITLE
[QUESTION] @JSONField 注解 属性 deserializeUsing 反序列化化使用自定义类解密

### ISSUE THREAD

**Issue by ang00** [alibaba/fastjson2#388]
### 请描述您的问题
*2.0.5 版本 `@JSONField` 反序列化使用自定义类解密， 如何操作*
1.2.83 使用
```java
@JSONField(serializeUsing = IdCodec.class, deserializeUsing = IdCodec.class)
private Integer id;
```
2.0.5 使用
```java
@JSONField(writeUsing = IdCodec.class)
private Integer id;
```
请问序列化使用 `writeUsing = IdCodec.class` 类hash 加密，反序列化如何解密，就如 1.2.x 版本 deserializeUsing = IdCodec.class

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

问题已经修复，请用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

写法如下：
```java
    @Test
    public void test() {
        Bean bean = new Bean();
        bean.id = 123;

        String str = JSON.toJSONString(bean);
        assertEquals("{\"id\":\"123元\"}", str);

        Bean bean1 = JSON.parseObject(str, Bean.class);
        assertEquals(bean.id, bean1.id);
    }

    public static class Bean {
        @JSONField(serializeUsing = IdCodec.class, deserializeUsing = IdCodec.class)
        public int id;
    }

    public static class IdCodec
            implements ObjectReader, ObjectWriter {
        public long getFeatures() {
            return 0;
        }

        @Override
        public Object readObject(JSONReader jsonReader, long features) {
            String str = jsonReader.readString();
            str = str.replace("元", "");
            return Integer.parseInt(str);
        }

        @Override
        public void write(JSONWriter jsonWriter, Object object, Object fieldName, Type fieldType, long features) {
            jsonWriter.writeString(object.toString() + "元");
        }
    }
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本

**Comment by zhengju5683** [comment]
@wenshao 上面的例子，属性改成private,提供getter和setter，结果是失败的，应该如何使用？
public static class Bean {
        @JSONField(serializeUsing = IdCodec.class,  deserializeUsing = IdCodec.class)
        private int id;
        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }
    }

com.alibaba.fastjson2.JSONException: parseInt error, value : 元

	at com.alibaba.fastjson2.JSONReader.toInt32(JSONReader.java:2074)
	at com.alibaba.fastjson2.JSONReader.getInt32Value(JSONReader.java:527)
	at com.alibaba.fastjson2.JSONReaderUTF16.readInt32Value(JSONReaderUTF16.java:1109)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:453)
