### ISSUE TITLE
建议JSONWrier.Feature.NullAsDefaultValue改变

### ISSUE THREAD

**Issue by HuShao96** [alibaba/fastjson2#391]
### 请描述您的需求或者改进建议
*建议JSONWrier.Feature.NullAsDefaultValue行为中，number默认值去掉。或者把集合，字符串和数值类型分开配置。*

### 请描述你建议的实现方案
*1.0是分开，比较灵活。并且个人觉得，字符串（null转""）和集合(null转[])严格意义来说也是空的，只不过是形式改变了而已，但是number从null 转0；不管对于业务来说都是不实际的*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
