### ISSUE TITLE
java.util.Date字段反序列化可以支持unixtime

### ISSUE THREAD

**Issue by dance3366** [alibaba/fastjson2#392]
### 请描述您的需求或者改进建议
java.util.Date字段反序列化可以支持unixtime，目前直接转换成1970年

### 请描述你建议的实现方案
format支持unixtime

**Comment by wenshao** [comment]
能提供一个你期待结果的代码，现在是支持的，我看哪里漏了

**Comment by dance3366** [comment]
public static void main(String[] args) {
        String date1 = JSONObject.of("date1", 165405316).toString();
        System.out.println("date1 = " + date1);
        Date date = JSON.parseObject(date1, Test.class).getDate1();
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-HH-dd HH:mm:dd");
        System.out.println(sf.format(date));
    }
@Data
class Test{
    @JSONField(format = "unixtime")
    private Date date1;
}

如果是数值类型，直接当毫秒处理了
com.alibaba.fastjson2.reader.FieldReaderDateMethod#readFieldValue方法处理代码如下：
if (jsonReader.isInt()) {
            long millis = jsonReader.readInt64Value();
            fieldValue = new java.util.Date(millis);
 } 
如果是字符串，直接报错，毫秒字符串，比如165405316000可以正常转换
String date1 = JSONObject.of("date1", "165405316").toString();
com.alibaba.fastjson2.reader.FieldReaderDateMethod#readFieldValue报错代码行：
DateTimeFormatter formatter = getFormatter(locale);

还是我使用的有问题

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

问题已经修复，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by dance3366** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/
> 
> 问题已经修复，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

验证数值型是可以成功的，比如：{"date1":1654134285}

但如果是字符：比如：{"date1":“1654134285”}会报错
报错位置如下：
com.alibaba.fastjson2.JSONReader#readMillisFromString
 case 10: {
                LocalDateTime date = readLocalDate10();
                if (date != null) {
                    return ZonedDateTime.of(date,
                            context.getZoneId())
                            .toInstant()
                            .toEpochMilli();
                }
                String str = readString();
                if ("0000-00-00".equals(str)) {
                    return 0;
                }
                throw new JSONException("TODO : " + str);
            }
unixtime刚好是10位，是否可以增加判断IOUtils.isNumber(str)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
