### ISSUE TITLE
[BUG] 2.0.5 版本，json 转换字段排序 Feature.OrderedField 未生效

### ISSUE THREAD

**Issue by chimmhuang** [alibaba/fastjson2#394]
### 问题描述
2.0.5 版本，json 转换字段排序 Feature.OrderedField 未生效

### 环境信息
*请填写以下信息：*

 - OS信息：  [windows11]
 - JDK信息： [Openjdk11.0.10]
 - 版本信息：[Fastjson 2.0.5]
 

### 重现步骤
以下代码使用不同的 fastjson 版本即可复现问题，问题版本：2.0.5、升级前版本：1.2.60

```java
        String json = """
                {
                    "head": {
                        "requestTime": "1654070371884",
                        "merchantcode": "111",
                        "ticket": "111",
                        "version": "1.0.0"
                    },
                    "body": {
                        "phone": "111",
                        "type": "1",
                        "ticket": ""
                    },
                    "sign": "111"
                }
                """;

        System.out.println(JSON.parseObject(json, Feature.OrderedField));
```
输出为
```
{
    "head": {
        "requestTime": "1654070371884",
        "merchantcode": "111",
        "ticket": "111",
        "version": "1.0.0"
    },
    "sign": "111",
    "body": {
        "phone": "111",
        "type": "1",
        "ticket": ""
    }
}
```

期望输出json的顺序不改变，但实际结果是顺序发生了改变。1.2.60 版本不存在此问题

**Comment by dance3366** [comment]
> ### 问题描述
> 2.0.5 版本，json 转换字段排序 Feature.OrderedField 未生效
> 
> ### 环境信息
> _请填写以下信息：_
> 
> * OS信息：  [windows11]
> * JDK信息： [Openjdk11.0.10]
> * 版本信息：[Fastjson 2.0.5]
> 
> ### 重现步骤
> 以下代码使用不同的 fastjson 版本即可复现问题，问题版本：2.0.5、升级前版本：1.2.60
> 
> ```java
>         String json = """
>                 {
>                     "head": {
>                         "requestTime": "1654070371884",
>                         "merchantcode": "111",
>                         "ticket": "111",
>                         "version": "1.0.0"
>                     },
>                     "body": {
>                         "phone": "111",
>                         "type": "1",
>                         "ticket": ""
>                     },
>                     "sign": "111"
>                 }
>                 """;
> 
>         System.out.println(JSON.parseObject(json, Feature.OrderedField));
> ```
> 
> 输出为
> 
> ```
> {
>     "head": {
>         "requestTime": "1654070371884",
>         "merchantcode": "111",
>         "ticket": "111",
>         "version": "1.0.0"
>     },
>     "sign": "111",
>     "body": {
>         "phone": "111",
>         "type": "1",
>         "ticket": ""
>     }
> }
> ```
> 
> 期望输出json的顺序不改变，但实际结果是顺序发生了改变。1.2.60 版本不存在此问题

你可以不加Feature.OrderedField试试，2我测试的结果默认是有序的

**Comment by chimmhuang** [comment]
> 

现在的情况就是，加了 Feature.OrderedField 和 不加 Feature.OrderedField 是一个效果，都是被排序了，并不是我输入的顺序。在1.2.60 版本，不加 Feature.OrderedField 会被排序，加了 Feature.OrderedField 则是我输入的顺序。

**Comment by dance3366** [comment]
> > 
> 
> 现在的情况就是，加了 Feature.OrderedField 和 不加 Feature.OrderedField 是一个效果，都是被排序了，并不是我输入的顺序。在1.2.60 版本，不加 Feature.OrderedField 会被排序，加了 Feature.OrderedField 则是我输入的顺序。

Feature.OrderedField 这个fastjson2已经没有了，你用的应该是兼容包，检查JSON是否引用的包名是否为2，如下
com.alibaba.fastjson2.JSON

**Comment by chimmhuang** [comment]
> > > 
> > 
> > 
> > 现在的情况就是，加了 Feature.OrderedField 和 不加 Feature.OrderedField 是一个效果，都是被排序了，并不是我输入的顺序。在1.2.60 版本，不加 Feature.OrderedField 会被排序，加了 Feature.OrderedField 则是我输入的顺序。
> 
> Feature.OrderedField 这个fastjson2已经没有了，你用的应该是兼容包，检查JSON是否引用的包名是否为2，如下 com.alibaba.fastjson2.JSON

啊这。。。我用的是
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>fastjson</artifactId>
    <version>2.0.5</version>
</dependency>
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

问题已经修复，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
