### ISSUE TITLE
[QUESTION] byte[] 转对象 没有驼峰式转换 fastjson1 有

### ISSUE THREAD

**Issue by qq2429979710** [alibaba/fastjson2#396]
没有驼峰式转换 fastjson1 有

byte[] jsonbBytes = ...
Product product = JSONB.parseObject(jsonbBytes, Product.class);

Product product = JSONB.parseObject(jsonbBytes, Product.class, JSONReader.Feature.SupportBeanArrayMapping);

**Comment by wenshao** [comment]
抱歉，没看懂

**Comment by js20166098** [comment]
现在存在json里是下划线实体类也是下划线但是getset使用驼峰 自己写，不用lombok
类似。
public class TestDomain{
    private String dept_name;
    public String getDeptName() {
        return dept_name;
    }

    public void setDeptName(String dept_name) {
        this.dept_name = dept_name;
    }
}
json
{"dept_name":"dept_name"}
执行代码这个是空的
        TestDomain testDomain = com.alibaba.fastjson2.JSONObject.parseObject(testDoMain, TestDomain.class);
        System.out.println("2.x 版本的结果" +  JSON.toJSONString(testDomain));

**Comment by wenshao** [comment]
@js20166098 
```java
TestDomain testDomain = JSON.parseObject(str, TestDomain.class, JSONReader.Feature.SupportSmartMatch);
```

在2.0中，Feature.SupportSmartMatch需要显式打开。

如果你用兼容API是可以的
```java
TestDomain testDomain = com.alibaba.fastjson.JSON.parseObject(str, TestDomain.class);
```
