### ISSUE TITLE
[BUG] GenericFastJsonRedisSerializer序列化异常

### ISSUE THREAD

**Issue by alon-sys** [alibaba/fastjson2#397]
版本：FastJson2   2.0.6-SNAPSHOT

异常：
![image](https://user-images.githubusercontent.com/22309691/171552365-14060114-cb3f-458a-9b1f-3ac3896e3a33.png)

如果用FastJson 1的版本是正常序列化

JSON数据：

{"@type":"com.test.modules.order.cart.entity.dto.TradeDTO","canUseCoupons":[],"cantUseCoupons":[],"cartList":[],"cartTypeEnum":1,"checkedSkuList":[{"cartType":1,"chdTotalDiffPrice":0.0,"checked":true,"errorMessage":"","goodsSku":{"@type":"com.test.modules.goods.entity.dos.GoodsSku","authFlag":"PASS","brandId":"","buyCount":0,"categoryPath":"1509086343616290818,1524293809023897602","cost":246.17,"createBy":"测试","createTime":"2022-05-23 14:13:38","deleteFlag":false,"dropshippingCost":0.0,"freightTemplateId":"0","goodsId":"1518524930364461058","goodsName":"新疆和田铁漠沙克 营养蜂蜜饮品（6支装） 30ml*6瓶","goodsType":"PHYSICAL_GOODS","goodsUnit":"盒","grade":100.0,"id":"1518524930481901570","indexShow":true,"intro":"","livePrice":270.79,"lowStock":1000,"marketEnable":"UPPER","mobileIntro":"<p><img src=\"https://file.baidu.com/502534330b8e4285998b3fbd0783b13a.jpg\" style=\"max-width:100%\" /></p>","price":999.0,"promotionFlag":true,"promotionPrice":900.0,"quantity":5000,"recommend":false,"salesModel":"RETAIL","selfOperated":false,"selfOperatedPrice":400.66,"sellingPoint":"来自维吾尔多年的神秘配方，利用传统工艺与先进技术结合而成","simpleSpecs":" 30ml*6瓶","small":"https://file.baidu.com/93b98ba581c746fdb036c5b50e92bda1.jpg?x-oss-process=style/200X200","sn":"LS001049-1","specs":"{\"images\":[{\"name\":\"主图.jpg\",\"url\":\"https://file.baidu.com/93b98ba581c746fdb036c5b50e92bda1.jpg\",\"status\":\"finished\"},{\"name\":\"主图1.jpg\",\"url\":\"https://file.baidu.com/5d9691353b884d32b0cf06f44d8dbe3e.jpg\",\"status\":\"finished\"}],\"规格\":\"30ml*6瓶\"}","storeCategoryPath":"","storeId":"1509095000903041026","storeName":"测试公司","suggestedPrice":1240.0,"taxPoint":0.0,"thumbnail":"https://file.baidu.com/93b98ba581c746fdb036c5b50e92bda1.jpg?x-oss-process=style/400X400","updateBy":"测试","updateTime":"2022-05-23 18:24:51","vendordPrice":0.0,"weight":0.0},"invalid":false,"isFreeFreight":false,"isShip":true,"limitNum":2,"notFilterPromotionMap":{"SECKILL-1532208898643271682":{"applyEndTime":"2022-06-03 00:00:00","createBy":"SYSTEM","createTime":"2022-06-02T11:53:01.913+08:00","deleteFlag":false,"endTime":"2022-06-02T23:59:59.999+08:00","goodsNum":4,"hours":"12,13,14,15,16,17,18,19,20,21,22","id":"1532208641759588353","promotionName":"2022-06-03 活动","promotionStatus":"NEW","scopeId":"1518524930481901570,1518523422772219906,1519931144789020674,1509472050201526274,1509729184889782273,1518496881401057281,1517039951075753986,1527207878647341058","scopeType":"PORTION_GOODS","seckillRule":"测试","startTime":"2022-06-02 12:00:00","storeId":"platform","storeName":"platform","updateBy":"admin","updateTime":"2022-06-02T11:53:16.387+08:00"}},"num":1,"priceDetailDTO":{"@type":"com.test.modules.order.order.entity.dto.PriceDetailDTO","billPrice":0.0,"chdTotalDiffPrice":0.0,"couponPrice":0.0,"discountPrice":0.0,"distributionCommission":0.0,"flowPrice":0.0,"freightPrice":0.0,"goodsPrice":0.0,"goodsPriceRatioJson":{},"joinPromotion":[],"originalPrice":0.0,"payPoint":0,"platFormCommission":0.0,"platFormCommissionPoint":0.0,"ratioPrice":0.0,"settlementPrice":0.0,"siteCouponCommission":0.0,"siteCouponPoint":0.0,"siteCouponPrice":0.0,"suggestedPrice":0.0,"updatePrice":0.0},"priceDetailVO":{"@type":"com.test.modules.order.cart.entity.vo.PriceDetailVO","discountPrice":0.0,"finalePrice":0.0,"freight":0.0,"originalPrice":0.0,"payPoint":0},"promotionMap":{"SECKILL-1532208898643271682":{"applyEndTime":"2022-06-03 00:00:00","createBy":"SYSTEM","createTime":"2022-06-02T11:53:01.913+08:00","deleteFlag":false,"endTime":"2022-06-02T23:59:59.999+08:00","goodsNum":4,"hours":"12,13,14,15,16,17,18,19,20,21,22","id":"1532208641759588353","promotionName":"2022-06-03 活动","promotionStatus":"NEW","scopeId":"1518524930481901570,1518523422772219906,1519931144789020674,1509472050201526274,1509729184889782273,1518496881401057281,1517039951075753986,1527207878647341058","scopeType":"PORTION_GOODS","seckillRule":"测试","startTime":"2022-06-02 12:00:00","storeId":"platform","storeName":"platform","updateBy":"admin","updateTime":"2022-06-02T11:53:16.387+08:00"}},"purchasePrice":900.0,"storeId":"1509095000903041026","storeName":"测试公司","subTotal":900.0,"suggestedPrice":1240.0,"utilPrice":900.0}],"memberId":"1529378161307942912","memberName":"Alon","needReceipt":false,"priceDetailDTO":{"@type":"com.test.modules.order.order.entity.dto.PriceDetailDTO","billPrice":0.0,"chdTotalDiffPrice":0.0,"couponPrice":0.0,"discountPrice":0.0,"distributionCommission":0.0,"flowPrice":0.0,"freightPrice":0.0,"goodsPrice":0.0,"goodsPriceRatioJson":{},"joinPromotion":[],"originalPrice":0.0,"payPoint":0,"platFormCommission":0.0,"platFormCommissionPoint":0.0,"ratioPrice":0.0,"settlementPrice":0.0,"siteCouponCommission":0.0,"siteCouponPoint":0.0,"siteCouponPrice":0.0,"suggestedPrice":0.0,"updatePrice":0.0},"skuList":[{"cartType":1,"chdTotalDiffPrice":0.0,"checked":true,"errorMessage":"","goodsSku":{"@type":"com.test.modules.goods.entity.dos.GoodsSku","authFlag":"PASS","brandId":"","buyCount":0,"categoryPath":"1509086343616290818,1524293809023897602","cost":246.17,"createBy":"测试","createTime":"2022-05-23 14:13:38","deleteFlag":false,"dropshippingCost":0.0,"freightTemplateId":"0","goodsId":"1518524930364461058","goodsName":"新疆和田铁漠沙克 营养蜂蜜饮品（6支装） 30ml*6瓶","goodsType":"PHYSICAL_GOODS","goodsUnit":"盒","grade":100.0,"id":"1518524930481901570","indexShow":true,"intro":"","livePrice":270.79,"lowStock":1000,"marketEnable":"UPPER","mobileIntro":"<p><img src=\"https://file.baidu.com/502534330b8e4285998b3fbd0783b13a.jpg\" style=\"max-width:100%\" /></p>","price":999.0,"promotionFlag":true,"promotionPrice":900.0,"quantity":5000,"recommend":false,"salesModel":"RETAIL","selfOperated":false,"selfOperatedPrice":400.66,"sellingPoint":"来自维吾尔多年的神秘配方，利用传统工艺与先进技术结合而成","simpleSpecs":" 30ml*6瓶","small":"https://file.baidu.com/93b98ba581c746fdb036c5b50e92bda1.jpg?x-oss-process=style/200X200","sn":"LS001049-1","specs":"{\"images\":[{\"name\":\"主图.jpg\",\"url\":\"https://file.baidu.com/93b98ba581c746fdb036c5b50e92bda1.jpg\",\"status\":\"finished\"},{\"name\":\"主图1.jpg\",\"url\":\"https://file.baidu.com/5d9691353b884d32b0cf06f44d8dbe3e.jpg\",\"status\":\"finished\"}],\"规格\":\"30ml*6瓶\"}","storeCategoryPath":"","storeId":"1509095000903041026","storeName":"测试公司","suggestedPrice":1240.0,"taxPoint":0.0,"thumbnail":"https://file.baidu.com/93b98ba581c746fdb036c5b50e92bda1.jpg?x-oss-process=style/400X400","updateBy":"测试","updateTime":"2022-05-23 18:24:51","vendordPrice":0.0,"weight":0.0},"invalid":false,"isFreeFreight":false,"isShip":true,"limitNum":2,"notFilterPromotionMap":{"SECKILL-1532208898643271682":{"applyEndTime":"2022-06-03 00:00:00","createBy":"SYSTEM","createTime":"2022-06-02T11:53:01.913+08:00","deleteFlag":false,"endTime":"2022-06-02T23:59:59.999+08:00","goodsNum":4,"hours":"12,13,14,15,16,17,18,19,20,21,22","id":"1532208641759588353","promotionName":"2022-06-03 活动","promotionStatus":"NEW","scopeId":"1518524930481901570,1518523422772219906,1519931144789020674,1509472050201526274,1509729184889782273,1518496881401057281,1517039951075753986,1527207878647341058","scopeType":"PORTION_GOODS","seckillRule":"测试","startTime":"2022-06-02 12:00:00","storeId":"platform","storeName":"platform","updateBy":"admin","updateTime":"2022-06-02T11:53:16.387+08:00"}},"num":1,"priceDetailDTO":{"@type":"com.test.modules.order.order.entity.dto.PriceDetailDTO","billPrice":0.0,"chdTotalDiffPrice":0.0,"couponPrice":0.0,"discountPrice":0.0,"distributionCommission":0.0,"flowPrice":0.0,"freightPrice":0.0,"goodsPrice":0.0,"goodsPriceRatioJson":{},"joinPromotion":[],"originalPrice":0.0,"payPoint":0,"platFormCommission":0.0,"platFormCommissionPoint":0.0,"ratioPrice":0.0,"settlementPrice":0.0,"siteCouponCommission":0.0,"siteCouponPoint":0.0,"siteCouponPrice":0.0,"suggestedPrice":0.0,"updatePrice":0.0},"priceDetailVO":{"@type":"com.test.modules.order.cart.entity.vo.PriceDetailVO","discountPrice":0.0,"finalePrice":0.0,"freight":0.0,"originalPrice":0.0,"payPoint":0},"promotionMap":{"SECKILL-1532208898643271682":{"applyEndTime":"2022-06-03 00:00:00","createBy":"SYSTEM","createTime":"2022-06-02T11:53:01.913+08:00","deleteFlag":false,"endTime":"2022-06-02T23:59:59.999+08:00","goodsNum":4,"hours":"12,13,14,15,16,17,18,19,20,21,22","id":"1532208641759588353","promotionName":"2022-06-03 活动","promotionStatus":"NEW","scopeId":"1518524930481901570,1518523422772219906,1519931144789020674,1509472050201526274,1509729184889782273,1518496881401057281,1517039951075753986,1527207878647341058","scopeType":"PORTION_GOODS","seckillRule":"测试","startTime":"2022-06-02 12:00:00","storeId":"platform","storeName":"platform","updateBy":"admin","updateTime":"2022-06-02T11:53:16.387+08:00"}},"purchasePrice":900.0,"storeId":"1509095000903041026","storeName":"测试公司","subTotal":900.0,"suggestedPrice":1240.0,"utilPrice":900.0}],"skuPromotionDetail":{}}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

问题已经修复，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
