### ISSUE TITLE
@JSONField 需要1.x版本中的 jsonDirect功能，谢谢

### ISSUE THREAD

**Issue by wxhdavid** [alibaba/fastjson2#398]
### 请描述您的需求或者改进建议

@JSONField 需要1.x版本中的 jsonDirect功能，谢谢

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

已经支持，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
