### ISSUE TITLE
[QUESTION] 2.x com.alibaba.fastjson2.JSONArray cannot be cast to com.alibaba.fastjson.JSONArray

### ISSUE THREAD

**Issue by nuoqin** [alibaba/fastjson2#399]
为什么在fastjson2这里不采用原先的jsonArray呢？

1.x中 使用类型转换
`
JSONObject fileJson = JSON.parseObject(jsonStr);
JSONArray files = (JSONArray) fileJson.get("files");
`
更换成2.x后使用上面的代码会出现com.alibaba.fastjson2.JSONArray cannot be cast to com.alibaba.fastjson.JSONArray
是因为格式化代码中的JSONArray  被替换成了com.alibaba.fastjson2.JSONArray。可以再com.alibaba.fastjson2.reader.ObjectReaderImplMap中488行 JSONArray list = new JSONArray();

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.6-SNAPSHOT/

问题已经修复，请帮忙用2.0.6-SNAPSHOT版本验证，2.0.6正式版预计6月5日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.6
问题已经修复，请用新版本
