### ISSUE TITLE
JSONObject 的 getBigDecimal方法没了

### ISSUE THREAD

**Issue by jayzch** [alibaba/fastjson2#40]
https://github.com/alibaba/fastjson2/blob/72470cd21390dbdc733e1dfca59e6ca632198035/fastjson1_compatible/src/main/java/com/alibaba/fastjson/JSONObject.java#L308

**Comment by wenshao** [comment]
漏了，要补上

**Comment by jayzch** [comment]
求更，踩坑中

> 漏了，要补上

**Comment by wenshao** [comment]
预计5月3日前发布2.0.2修复问题

**Comment by wenshao** [comment]
你可以尝试fastjson2的API，这个com.alibaba.fastjson2.JSONObject，fastjson2的JSONObject有这个方法

**Comment by jayzch** [comment]
getBoolean  这个也没了 @wenshao

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
