### ISSUE TITLE
实体类和json下划线字段问题

### ISSUE THREAD

**Issue by js20166098** [alibaba/fastjson2#403]
现在存在json里是下划线实体类也是下划线但是getset使用驼峰 自己写，不用lombok
类似。
public class TestDomain{
    private String dept_name;
    public String getDeptName() {
        return dept_name;
    }

    public void setDeptName(String dept_name) {
        this.dept_name = dept_name;
    }
}
json
{"dept_name":"dept_name"}
执行代码这个是空的
        TestDomain testDomain = com.alibaba.fastjson2.JSONObject.parseObject(testDoMain, TestDomain.class);
        System.out.println("2.x 版本的结果" +  JSON.toJSONString(testDomain));

_Originally posted by @js20166098 in https://github.com/alibaba/fastjson2/issues/396#issuecomment-1145830993_

**Comment by js20166098** [comment]
使用lombok没有问题，自定义get set有问题

**Comment by wenshao** [comment]
在FASTJSON 2中，SmartMatch没有缺省打开，你可以这样用：
```java
TestDomain testDomain = JSON.parseObject(testDoMain, TestDomain.class, JSONReader.Feature.SupportSmartMatch);
```

**Comment by js20166098** [comment]
解决方法可行就是操作的时候和历史习惯冲突习惯了JSONObject.par
