### ISSUE TITLE
[BUG]文档中的bug

### ISSUE THREAD

**Issue by k4n5ha0** [alibaba/fastjson2#405]
### 问题描述
https://alibaba.github.io/fastjson2/autotype_cn  地址中

文字笔误，请看箭头
![image](https://user-images.githubusercontent.com/22064977/171966144-30baba1c-09be-4797-a2c5-28955a98ff80.png)

**Comment by VictorZeng** [comment]
@k4n5ha0 您可以提交一个PR帮忙修复这个问题~
