### ISSUE TITLE
[FEATURE] wiki 文档错误（显式），另外 safeMode 又是啥

### ISSUE THREAD

**Issue by MoonLord-LM** [alibaba/fastjson2#408]
https://github.com/alibaba/fastjson2/wiki/fastjson2_autotype_cn

`必须显示显示打开才能使用`    ->    **显式**

`在safeMode打开后，显式传入AutoType参数也不起作用`    ->    这东西设计的不科学吧，一定要这样的话，应该叫 **强制禁用AutoType模式** 吧

别叫安全模式（safeMode）了吧，既不安全，也不直观

**Comment by wenshao** [comment]
SafeMode是兼容fastjson 1.x的叫法
