### ISSUE TITLE
JSON校验问题[BUG]

### ISSUE THREAD

**Issue by wycst** [alibaba/fastjson2#410]
错误的json也能解析，isValid返回的也是true，下面是代码：

        String json = "{\"key1\":11444-sdsdsd\"key2\":\"sdsdssdsda\"}";
        boolean validate = com.alibaba.fastjson2.JSON.isValid(json);
        System.out.println(" validate: " + validate);
        JSONObject value = com.alibaba.fastjson2.JSON.parseObject(json);
        System.out.println(value);

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/

问题已经修复，你可以先用2.0.7-SNAPSHOT版本验证

**Comment by wycst** [comment]
问题还是存在。  

   String json = "{\n" +
                "  \"store\": {\n" +
                "    \"book\": [\n" +
                "      {\n" +
                "        \"category\": \"reference\",\n" +
                "        \"author\": \"Nigel Rees\"\n" +                                      //  这行把逗号去掉了
                "        \"title\": \"Sayings of the Century\",\n" +
                "        \"price\": 8.95\n1-" +                                                     //  这行在回车后面加了多余字符
                "      },\n" +
                "      {\n" +
                "        \"category\": \"fiction\",\n" +
                "        \"author\": \"Evelyn Waugh\",\n" +
                "        \"title\": \"Sword of Honour\",\n" +
                "        \"price\": 12.99\n" +
                "      },\n" +
                "      {\n" +
                "        \"category\": \"fiction\",\n" +
                "        \"author\": \"Herman Melville\",\n" +
                "        \"title\": \"Moby Dick\",\n" +
                "        \"isbn\": \"0-553-21311-3\",\n" +
                "        \"price\": 8.99\n" +
                "      },\n" +
                "      {\n" +
                "        \"category\": \"fiction\",\n" +
                "        \"author\": \"J. R. R. Tolkien\",\n" +
                "        \"title\": \"The Lord of the Rings\",\n" +
                "        \"isbn\": \"0-395-19395-8\",\n" +
                "        \"price\": 22.99\n" +
                "      }\n" +
                "    ],\n" +
                "    \"bicycle\": {\n" +
                "      \"color\": \"red\",\n" +
                "      \"price\": 19.95\n" +
                "    }\n" +
                "  },\n" +
                "  \"expensive\": 10\n" +
                "}\n";
        System.out.println(JSON.isValid(json));
        System.out.println(JSON.parse(json));

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
