### ISSUE TITLE
 filter导致WriteClassName失效

### ISSUE THREAD

**Issue by spnettec** [alibaba/fastjson2#411]
JSON.toJSONString  加上 filter之后WriteClassName失效

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/

问题已修复，你用2.0.7-SNAPSHOT版本先验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
请用新版本
