### ISSUE TITLE
运行时类型无法还原

### ISSUE THREAD

**Issue by spnettec** [alibaba/fastjson2#412]
`

      public void test() {
              Bean bean = new Bean();
              bean.setAa(Long.valueOf(1));
              assertTrue(bean.getAa() instanceof Long);
              String str = JSON.toJSONString(bean, JSONWriter.Feature.WriteClassName);
              Bean object = JSON.parseObject(str,Bean.class,JSONReader.Feature.SupportClassForName);
              assertTrue(object.getAa() instanceof Long); // 不通过
          }

        public static class Bean {
            public Object getAa() {
                return aa;
            }

          public void setAa(Object aa) {
              this.aa = aa;
          }
  
          private Object aa;
  
      }
`

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/
已经支持，请用2.0.7-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
