### ISSUE TITLE
[QUESTION]转json对象如何保留空值

### ISSUE THREAD

**Issue by yuankc** [alibaba/fastjson2#415]
### 转json对象如何保留空值？
*JSONWriter中有配置项，在JSONReader中没找到*

public static void main(String[] args) {
      Map<Integer, String> map = new HashMap<>();
      map.put(0, "a");
      map.put(1, "b");
      map.put(2, null);
      map.put(3, "c");
      String header = JSON.toJSONString(map, JSONWriter.Feature.WriteMapNullValue);
      System.out.println(header);
      JSONObject jsonObject = JSON.parseObject(header);
      System.out.println(jsonObject);
}

**Comment by yangcanlin** [comment]
你打开 jsonObject  对象看看，里面的属性就是 null,JSONReader不需要设置保留null，因为它就是null，为什么你最后一次打印没打印出来，因为默认不打印空值。。。。
JSON.toJSONString(jsonObject, JSONWriter.Feature.WriteNulls)

![image](https://user-images.githubusercontent.com/76166196/172374545-5716f4ef-eba1-46fc-89ad-c18c7eae64cd.png)

**Comment by yuankc** [comment]
好的，非常感谢
