### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hyuga0410** [alibaba/fastjson2#422]
### 问题描述
fastjson 版本2.0.3和2.0.6
com.alibaba.fastjson2.JSON.toJSONString(fastJsonTest, JSONWriter.Feature.WriteEnumsUsingName)
// {"fastJsonEnum":"FAST_JSON_ENUM"}
com.alibaba.fastjson.JSON.toJSONString(fastJsonTest, SerializerFeature.WriteEnumUsingName)
// {"fastJsonEnum":0}
处理结果不同

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：MacOS]
 - JDK信息： [e.g.：11]
 - 版本信息：[e.g.：Fastjson2 2.0.6]
 

### 重现步骤
@Data
public class FastJsonTest {

    private FastJsonEnum fastJsonEnum = FastJsonEnum.FAST_JSON_ENUM;

    public static void main(String[] args) {
        FastJsonTest fastJsonTest = new FastJsonTest();
        System.out.println(JSON.toJSONString(fastJsonTest));

        System.out.println(com.alibaba.fastjson2.JSON.toJSONString(fastJsonTest, JSONWriter.Feature.WriteEnumsUsingName));
        System.out.println(com.alibaba.fastjson2.JSON.toJSONString(fastJsonTest, JSONWriter.Feature.WriteEnumUsingToString));

        System.out.println(com.alibaba.fastjson.JSON.toJSONString(fastJsonTest));
        System.out.println(com.alibaba.fastjson.JSON.toJSONString(fastJsonTest, SerializerFeature.WriteEnumUsingName));
        System.out.println(com.alibaba.fastjson.JSON.toJSONString(fastJsonTest, SerializerFeature.WriteEnumUsingToString));
    }

}

enum FastJsonEnum {
    FAST_JSON_ENUM;
}

### 期待的正确结果
两者返回结果应该一致

**Comment by wenshao** [comment]
fastjson2缺省输出的ordinal
