### ISSUE TITLE
[QUESTION] BigDecimal和Decimal128转换问题

### ISSUE THREAD

**Issue by lmh2017** [alibaba/fastjson2#427]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
JSON字符串如下：
```json
{
	"salaryStart": {
		"$numberDecimal": "6000"
	},
	"salaryEnd": {
		"$numberDecimal": "9000"
	}
}
```
由于MongoDB不支持BigDecimal类型， 需转换成Decimal128存储。

###  spring 定义转换器 
```java
@ReadingConverter
@WritingConverter
public class BigDecimalToDecimal128Converter implements Converter<Decimal128, BigDecimal> {
    @Override
    public BigDecimal convert(Decimal128 decimal128) {
        return decimal128.bigDecimalValue();
    }
}
```

### 对象字段
```java
public class PositionDO{
    //综合薪资范围起
    private BigDecimal salaryStart;
    //综合薪资范围止
    private BigDecimal salaryEnd;
}
```

所以支持mongodb类型和java类型互转。

现在用原对象接收，抛异常 Exception in thread "Thread-8" com.alibaba.fastjson2.JSONException: TODO : 6

**__问：如何用BigDecimal 接收这样的类型字段，怎样将converter使用进去？_**

**Comment by lmh2017** [comment]
异常是com.alibaba.fastjson2.JSONReader#getBigDecimal 方法抛出来的，因为识别不了此类型，抛异常了
![image](https://user-images.githubusercontent.com/31218115/172287260-f086e501-30c5-4cfa-8498-228a4c126793.png)

**Comment by wenshao** [comment]
Decimal128
这个类是org.bson.types.Decimal128 么？

**Comment by wenshao** [comment]
已经内置支持，请用2.0.7-SNAPSHOT版本验证下
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/

**Comment by lmh2017** [comment]
> 

是的

**Comment by lmh2017** [comment]
> 已经内置支持，请用2.0.7-SNAPSHOT版本验证下 https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/

好的 谢谢 我验证下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
