### ISSUE TITLE
spring 相关的支持无了

### ISSUE THREAD

**Issue by VirensCn** [alibaba/fastjson2#43]
主要是以下几个类
`FastJsonJsonView`
`FastjsonSockJsMessageCodec `
`FastJsonHttpMessageConverter`

**Comment by PleaseCallMeDong** [comment]
还有FastJsonConfig和FastJsonHttpMessageConverter也没有了

**Comment by VictorZeng** [comment]
@PleaseCallMeDong 2.0.2会发布

**Comment by wenshao** [comment]
已经支持，快照版本 https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.2-SNAPSHOT/

正式版本预计明天发布。
