### ISSUE TITLE
JSONPath.set设置的值与预期不符

### ISSUE THREAD

**Issue by microver** [alibaba/fastjson2#431]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
```java
                String jsonStr="{\"aaa\":\"a111\",\"bbb\":\"b11111\"}";
		JSONObject jsonObject=JsonUtil.toJsonObject(jsonStr);
		String valueStr="{\"ccc\":\"c111\",\"ddd\":\"d11111\"}";
		JSONObject value=JsonUtil.toJsonObject(valueStr);
		
		JSONPath.set(jsonObject,"$.aaa", value);
		System.out.println(jsonObject);
```
期待结果：{"aaa":{"ccc":"c111","ddd":"d11111"},"bbb":"b11111"}
在fastjson-1.2.7x以上版本时，结果正确
但在fastjosn-2.0.6版本下，结果如下：
{"aaa":["a111",{"ccc":"c111","ddd":"d11111"}],"bbb":"b11111"}
aaa节点原值a111仍存在，我想把新值valueStr的值完全替换原来的值，该怎么做？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.7-SNAPSHOT/
bug已修复，请帮用2.0.7-SNAPSHOT版本验证

**Comment by microver** [comment]
已验证，达到预期，非常感谢！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
