### ISSUE TITLE
JSONPath.read在2.0.x版本不再支持

### ISSUE THREAD

**Issue by microver** [alibaba/fastjson2#432]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
在fastjson-1.2.7x以上版本时，取对象的值可用 JSONPath.read(jsonString, jsonPath);读取jsonString在jsonPath路径的值，也可以用JSONPath.eval(jsonObject, jsonPath);读取jsonObject在jsonPath路径的值。
fastjson-2.0.x把JSONPath.read方法去掉了，请问，用什么方法可以替代 JSONPath.read(jsonString, jsonPath);的方法?

**Comment by wenshao** [comment]
JSONPath.extract方法

**Comment by microver** [comment]
非常感谢！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
