### ISSUE TITLE
fastjson2中怎么实现所有Date类型字段，格式化输出

### ISSUE THREAD

**Issue by xionggit** [alibaba/fastjson2#433]
当对象中有多个字段类型是Date 的时候，不想每个字段都设置@JSONField(format = "yyyyMMdd")

在fastjson1中，设置所有date 的默认格式可以这样写
JSON.DEFFAULT_DATE_FORMAT= "yyyyMMdd";
String json = JSON.toJSONString(object,SerializerFeature.WriteDateUseDateFormat);

但是在fastjson2的2.0.6中JSONWrite.Feature中好像不支持了？

**Comment by VictorZeng** [comment]
In fastjson2, you can use like ths:
```java
JSON.toJSONString(object, "yyyyMMdd");
```

**Comment by yangcanlin** [comment]
修复LocalDate使用dateFormat'yyyy-MM-dd HH:mm:ss'报错的问题 https://github.com/alibaba/fastjson2/issues/363

2.5 版本已经修复这个问题 可以全局配置一下

**Comment by xionggit** [comment]
> In fastjson2, you can use like ths:
> 
> ```java
> JSON.toJSONString(object, "yyyyMMdd");
> ```

可以了，感谢

**Comment by yangcanlin** [comment]
> > In fastjson2, you can use like ths:
> > ```java
> > JSON.toJSONString(object, "yyyyMMdd");
> > ```
> 
> 可以了，感谢

2.0.5 版本修复  但2.0.6版本 好像又出问题了 已经反馈了，昨晚3点温少已经修复了

**Comment by Kimmyzhao** [comment]
2.0.20版本中怎么又不能用了呢
