### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qinqi** [alibaba/fastjson2#438]
### springboot2.3.5整合fastjson2启动warn

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alibaba.fastjson2.util.JDKUtils (file:/D:/mvnrepo/com/alibaba/fastjson2/fastjson2/2.0.1/fastjson2-2.0.1.jar) to field java.lang.StringUTF16.HI_BYTE_SHIFT
WARNING: Please consider reporting this to the maintainers of com.alibaba.fastjson2.util.JDKUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Win10 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Oracle jdk 11]
 - 版本信息：[e.g.：Fastjson2 2.0.1]

**Comment by wsxe9988** [comment]
可以更新到
<dependency>
    <groupId>com.alibaba.fastjson2</groupId>
    <artifactId>fastjson2</artifactId>
    <version>2.0.6</version>
</dependency>
看看还有没有这个warn

**Comment by wenshao** [comment]
不用管，这是针对JDK 11性能优化的方式，不影响的
