### ISSUE TITLE
[BUG] 对象中含有LocalDate使用JSON.toJSONString 转换失败

### ISSUE THREAD

**Issue by pangzixianrenzhang** [alibaba/fastjson2#449]
### 问题描述
*简要描述您碰到的问题。*
对象中含有LocalDate使用JSON.toJSONString 转换失败

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：Fastjson2 2.0.4
 

### 重现步骤
*如何操作可以重现该问题：*

```java
//示例代码
    @Data
    static class JobParams implements Serializable {
        private LocalDate localDate;

    }


    public static void main(String[] args) throws Exception {
        JobParams jobParams = new JobParams();
        jobParams.setLocalDate(LocalDate.now());
        System.out.println(JSON.toJSONString(jobParams));
    }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.writer.ObjectWriterImplLocalDate.write(ObjectWriterImplLocalDate.java:44)
	at com.alibaba.fastjson2.writer.ObjectWriter_1.write(Unknown Source)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:335)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://user-images.githubusercontent.com/30500778/172972622-9de20601-9677-43da-bf73-42029b43befd.png)

类未添加注解dateFormat注解 fastjson2.0.4代码设置为:"millis"，导致解析失败
![image](https://user-images.githubusercontent.com/30500778/172974299-2f6a6fdc-a04d-4c94-8ac9-778cc8a158df.png)

**Comment by presenth7s** [comment]
BaseJobParam类包含哪些内容啊

**Comment by pangzixianrenzhang** [comment]
> BaseJobParam类包含哪些内容啊

已更新未设置dateformat注解，2.0版本默认设置为"millis"，导致解析失败
![image](https://user-images.githubusercontent.com/30500778/172975729-ca3ca507-a337-4a6f-8a54-2b0fe07f98a7.png)

**Comment by VictorZeng** [comment]
@pangzixianrenzhang 可是尝试使用一下2.0.6+版本，应该修复了您的问题~

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.7
问题已经修复，请用新版本
