### ISSUE TITLE
fastjson1_compatible 的maven group错误

### ISSUE THREAD

**Issue by jayzch** [alibaba/fastjson2#45]
https://github.com/alibaba/fastjson2/blob/87a7f381e1b39210d79faa540435bea768026a0a/fastjson1_compatible/pom.xml#L1-L15

是否应该添加
` <groupId>com.alibaba</groupId> 
`

**Comment by oldratlee** [comment]
@jayzch 是的。👍

`POM`清理的问题，我加回来～
