### ISSUE TITLE
[QUESTION]当对象中含有password属性的时候序列化后获取不到值

### ISSUE THREAD

**Issue by 1076674202** [alibaba/fastjson2#462]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

**Comment by wenshao** [comment]
请提供重现问题的testcase

**Comment by 1076674202** [comment]
如图：设置的password属性值，序列化后没有值了









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/fastjson2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 晚上7:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/fastjson2] [QUESTION]当对象中含有password属性的时候序列化后获取不到值 (Issue #462)





 
请提供重现问题的testcase

**Comment by 1076674202** [comment]
找到原因了因为get方法上加了
@JsonIgnore
@JsonProperty
