### ISSUE TITLE
[BUG] Date 类型 @JSONField 格式化无效

### ISSUE THREAD

**Issue by JiakunXu** [alibaba/fastjson2#468]
### 问题描述
使用 FastJsonHttpMessageConverter FastJsonConfig 配置 Date 格式化（yyyy-MM-dd HH:mm:ss），对象 Date 属性配置格式化 @JSONField(format = "yyyy-MM-dd")，结果 @JSONField 配置无效，返回（yyyy-MM-dd HH:mm:ss）格式

Fastjson2 2.0.6 没有这个问题

### 环境信息

 - 版本信息：[Fastjson2 2.0.7]
 

### 重现步骤

```
    FastJsonConfig fastJsonConfig = new FastJsonConfig();
    fastJsonConfig.setDateFormat("yyyy-MM-dd HH:mm:ss");
```
```
    @JSONField(format = "yyyy-MM-dd")
    private Date                  date;
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/
问题已经修复，请帮忙用2.0.8-SNAPSHOT验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
