### ISSUE TITLE
[FEATURE] Suggest rename to FasterJson <建议改名 FasterJson>

### ISSUE THREAD

**Issue by mx2913** [alibaba/fastjson2#470]
I think it might as well be called FasterJson, and then the next version can be FastestJson.
我感觉还不如叫 FasterJson，然后下一个版本就可以是 FastestJson 了。

**Comment by CarefulHuo** [comment]
666

**Comment by anzhen-tech** [comment]
six six six

**Comment by VictorZeng** [comment]
@mx2913 ~那下下个版本应该叫什么呢 ：）

**Comment by ZGW-GitHub** [comment]
nice

**Comment by mx2913** [comment]
> @mx2913 ~那下下个版本应该叫什么呢 ：）

下下个版本都20年后，说不定那个时候不流行 `JSON`，去流行 `KSON` 了。这样下去又是一个轮回了，`FastKson` => `FasterKson` => `FastestKson`

**Comment by wenshao** [comment]
不改名！
