### ISSUE TITLE
[BUG]JSONPath.set 在多层节点不存在时失效

### ISSUE THREAD

**Issue by Deathencyclopedia** [alibaba/fastjson2#476]
### 问题描述
JSONPath.set 在多层节点不存在时失效

### 环境信息
 - 版本信息：[Fastjson2 2.0.7]
 

### 重现步骤

```java
        JSONObject jsonObject=new JSONObject();
        jsonObject.put("c","c");
        JSONPath.set(jsonObject, "$.a.b", "123");
        System.out.println(jsonObject.toJSONString());
```
输出结果:{"c":"c"},在Fastjson 1.2.83中以上代码可以正确输出结果
### 期待的正确结果
{"a":{"b":"123"},"c":"c"}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/
问题已经修复，请帮忙用2.0.8-SNAPSHOT验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
