### ISSUE TITLE
[BUG]2.0.7，字符串转Json，key不加引号会报错：FASTJSON2.0.7error, offset 5, char a

### ISSUE THREAD

**Issue by woniudiancang** [alibaba/fastjson2#478]
### 问题描述
*简要描述您碰到的问题。*

例如有一个字符串：
`{a: "test"}`

使用 `JSONObject.parseObject` 转为Json。

1.0 的fastjson 一切正常；
2.0.7 会报错，必须在a上面增加引号才可以正常

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.7]
 

### 重现步骤
*如何操作可以重现该问题：*

例如有一个字符串：
`{a: "test"}`

使用 `JSONObject.parseObject` 转为Json。

1.0 的fastjson 一切正常；
2.0.7 会报错，必须在a上面增加引号才可以正常

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

2.0 也应该可以识别key不带引号的

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

`Exception in thread "main" com.alibaba.fastjson2.JSONException: FASTJSON2.0.7error, offset 5, char a
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1388)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:142)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1793)`

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
这个还没想好是否要做支持

**Comment by woniudiancang** [comment]
这个建议需要支持，理由有2:

1. 目前很多三方库对于Json的支持，都是可以识别key不加引号的，fastjson 建议也可以支持；
2. fastjson1.0 是支持的，很多项目中都大量使用了不带引号的写法，支持的话，可以增加兼容性，减少1.0升级到2.0的障碍，让更多人可以升级使用2.0

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
已经支持，请用2.0.9-SNAPSHOT帮忙验证，预计2.0.9版本在7月10日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
