### ISSUE TITLE
mvnrepository中有很多漏洞提示，影响使用吗

### ISSUE THREAD

**Issue by Ryoui** [alibaba/fastjson2#48]
![图片](https://user-images.githubusercontent.com/18000474/164626233-5f534c36-0768-4f2e-a9bb-0672a3c1a116.png)

https://mvnrepository.com/artifact/com.alibaba.fastjson2/fastjson2/2.0.1

**Comment by oldratlee** [comment]
@Ryoui 我来升级一下依赖吧，避免涉及的依赖有这些安全问题。

**Comment by oldratlee** [comment]
`com.alibaba.fastjson2/fastjson2` 的依赖升级 已提交。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
