### ISSUE TITLE
[FEATURE] JSON/JSONArray  toJSONString() 建议保留

### ISSUE THREAD

**Issue by hwtl** [alibaba/fastjson2#481]
version： fastjson 2.0.6/2.0.7
JSON /JSONArray 类里面 原有的toJSONString() 函数目前均已被替代或者是剔除了
导致在选择用兼容版本做升级的时候，程序的改动成本还是非常大的。建议将已有的能力
做好向下兼容。

**Comment by wenshao** [comment]
现在是有的啊，你说的是静态的toJSONString方法么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.8-SNAPSHOT/
问题已经修复，请帮忙用2.0.8-SNAPSHOT验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本

**Comment by hwtl** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.8 问题已经修复，请使用新版本
2.0.8 /2.0.9 没有
JSONArray -- toJSONString();   
JSON -- toJSONString
1.xxx 的版本函数如下
   public String toJSONString() {
        SerializeWriter out = new SerializeWriter();
        try {
            new JSONSerializer(out).write(this);
            return out.toString();
        } finally {
            out.close();
        }
    }
2.0.8 /2.0.9 没有
JSON -- toString
1.xxx 的版本函数如下
  /**
     * @since 1.2.57
     */
    public String toString(SerializerFeature... features) {
        SerializeWriter out = new SerializeWriter(null, JSON.DEFAULT_GENERATE_FEATURE, features);

        try {
            new JSONSerializer(out).write(this);
            return out.toString();
        } finally {
            out.close();
        }
    }
