### ISSUE TITLE
[BUG]JSON.parseObject(null) 从1.2.x升级到2.0.7后报错

### ISSUE THREAD

**Issue by 914313670** [alibaba/fastjson2#482]
### 问题描述
JSON.parseObject(null) 从1.2.83升级到2.0.7后报错

### 环境信息
*请填写以下信息：*

 - OS信息：  Windows 10
 - JDK信息： Openjdk 1.8.0_312
 - 版本信息：Fastjson 2.0.7
 

### 重现步骤
在1.2.83版本时候是正常的
![image](https://user-images.githubusercontent.com/35057623/174215890-c7339587-297b-40df-adb0-1a255f966b1b.png)
升级至2.0.7后同样的代码报错
![image](https://user-images.githubusercontent.com/35057623/174216047-eab041b4-3b5d-4e83-bbac-af32284db3ab.png)

### 期待的正确结果
JSON.parseObject(null) 同样和1.2.83版本响应为空

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/
问题已经修复，请帮忙用2.0.8-SNAPSHOT验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
