### ISSUE TITLE
[BUG]科学计数法的数字转换为BigDecimal类型时出现异常

### ISSUE THREAD

**Issue by JiahaoLin2018** [alibaba/fastjson2#492]
### 问题描述
*科学计数法的数字转换为BigDecimal类型时出现异常*

### 环境信息
 - OS信息：  [Windows]
 - JDK信息： [Openjdk jdk1.8.0_281]
 - 版本信息：[Fastjson2 2.0.7]
 

### 重现步骤

```java
@Getter
@Setter
@ToString
public class TestMO {
    private BigDecimal avaLimit; 
}

public static void main(String[] args) {
    String json = "{\"avaLimit\":1.1111111E7}";
    JSONObject jsonObject = JSON.parseObject(json);
    System.out.println(jsonObject.getBigDecimal("avaLimit"));

    TestMO testMO = JSON.parseObject(json, TestMO.class);
    System.out.println(testMO.getAvaLimit());
}
```

### 期待的正确结果
*11111111
11111111*

### 相关日志输出
*11111111
1.1111111*

```
说明：JSON.parseObject(json, TestMO.class);解析BigDecimal时出现异常。
```
![1655714428488](https://user-images.githubusercontent.com/40542227/174561999-d222ca72-2651-4a3d-b110-76edd349ed03.jpg)
![1655714380665](https://user-images.githubusercontent.com/40542227/174562027-9561af9f-3438-4302-8caa-d739dc32d472.jpg)

**Comment by ocean23** [comment]
这个bug比较严重，生产我们只能降回1.0的版本了，希望这个bug可以尽快解决

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/
问题已经修复，请用2.0.8-SNAPSHOT验证，预计在这个周末（6月26日）发布新版本

**Comment by ocean23** [comment]
好的，谢谢温少:+1:

**Comment by JiahaoLin2018** [comment]
好的，非常感谢。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
