### ISSUE TITLE
[BUG]JSONObject.getDate("")方法值为时间戳报错

### ISSUE THREAD

**Issue by 914313670** [alibaba/fastjson2#493]
### 问题描述
版本从1.2.83升级至2.0.x后
JSONObject.getDate("") 方法值为时间戳时候报错

### 环境信息
 - OS信息：  Windows 10
 - JDK信息：Openjdk 1.8.0_312
 - 版本信息：Fastjson 2.0.7
 

### 重现步骤
1.fastjson 版本为1.2.83时候可以正常获取
![image](https://user-images.githubusercontent.com/35057623/174563295-5437d840-48ca-4b81-99de-20da82d1f0cd.png)
![image](https://user-images.githubusercontent.com/35057623/174563387-bcca3264-f756-442a-a734-aaee9b90a123.png)

2.升级至2.0.7后获取失败
![image](https://user-images.githubusercontent.com/35057623/174563517-fae4d677-e793-46e4-b1bc-c605e296307e.png)
![image](https://user-images.githubusercontent.com/35057623/174563542-aed313c1-5b7b-4fe8-8d47-8a53ca8a7fc8.png)

### 期待的正确结果
JSONObject.getDate("")方法可以正常获取时间对象

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/
问题已经修复，请用2.0.8-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
