### ISSUE TITLE
处理localtime的时候format不生效

### ISSUE THREAD

**Issue by jmzcode** [alibaba/fastjson2#495]
https://github.com/alibaba/fastjson2/blob/ee1e1b9007102e684da7ae13001bc4a1414eccfa/core/src/main/java/com/alibaba/fastjson2/JSONReader.java#L993

**Comment by jmzcode** [comment]
`
@Data
public class Test {

    @JSONField(format = "HH:mm")
    private LocalTime time;

    public static void main(String[] args) {
        String str = "{\"time\": \"09:00\"}";
        Test test = JSONObject.parseObject(str,Test.class);
        System.out.println(JSONObject.toJSONString(test));
    }
}
`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
