### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JackpotHan** [alibaba/fastjson2#496]
### 问题描述
*
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alibaba.fastjson2.util.JDKUtils (file:/Users/Jackpot/.m2/repository/com/alibaba/fastjson2/fastjson2/2.0.5/fastjson2-2.0.5.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of com.alibaba.fastjson2.util.JDKUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：MacOS 12.4 4 Core 2.3GHz 8 GB]
 - JDK信息： [e.g.：Openjdk 11.0.4]
 - 版本信息：[e.g.：Fastjson2 2.0.5]

**Comment by wenshao** [comment]
这个不影响使用，忽略吧

**Comment by JackpotHan** [comment]
不影响使用 但是看到警告 总是出于强迫症响要知道为什么以及如何修复 ..

**Comment by peigen** [comment]
>

同上

**Comment by v3921358** [comment]
先暫時隱藏警告吧

`        try {
            Field field = Unsafe.class.getDeclaredField("theUnsafe");
            field.setAccessible(true);
            Unsafe unsafe = (Unsafe) field.get(null);
            Class className = Class.forName("jdk.internal.module.IllegalAccessLogger");
            Field logger = className.getDeclaredField("logger");
            unsafe.putObjectVolatile(className, unsafe.staticFieldOffset(logger), null);
        } catch (Exception ex) {
        }`
