### ISSUE TITLE
new TypeReference 

### ISSUE THREAD

**Issue by ZerphyrZhang** [alibaba/fastjson2#501]
### 问题描述
*简要描述您碰到的问题。*
在1.0中  new TypeReference<ResponseMessage<V>>(type){};
在.JSON.parseObject(resData, reference)时，是可以转换成复杂对象的，
但是在2.0.7中，提示：type的类型无法转成成ResponseMessage<V>类型

**Comment by ZerphyrZhang** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.8-SNAPSHOT/ 问题已经修复，请用2.0.8-SNAPSHOT验证，2.0.8版本预计在周末发布

Nice

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
