### ISSUE TITLE
[BUG]JSON.toJSONString(Object object, Filter filter, JSONWriter.Feature... features)，WriteNulls不生效

### ISSUE THREAD

**Issue by Aryaxia** [alibaba/fastjson2#503]
### 问题描述
JSON.toJSONString(Object object, Filter filter, JSONWriter.Feature... features)
使用WriteNulls未生效

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by ZerphyrZhang** [comment]
我之前遇到过，升级到2.0.7就好了

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
