### ISSUE TITLE
[BUG]JSONObject.toJavaObject()方法，时间转换问题

### ISSUE THREAD

**Issue by 914313670** [alibaba/fastjson2#504]
### 问题描述
1.2.83版本升级至2.0.7后
实体属性加上
@JSONField(format = "yyyy-MM-dd HH:mm:ss")注解后
调用JSONObject.toJavaObject()方法，json时间字段为空字符串时候会出现报错

### 环境信息
 - OS信息： Windows 10
 - JDK信息： Openjdk 1.8.0_312
 - 版本信息：Fastjson 2.0.7
 

### 重现步骤
实体
![image](https://user-images.githubusercontent.com/35057623/175451036-e3765196-84e6-46c4-a802-f97ba58346eb.png)
1.2.83版本
![image](https://user-images.githubusercontent.com/35057623/175451086-4cc38350-a7ec-4af7-ad9e-be3f4141f8bc.png)
2.0.7版本
![image](https://user-images.githubusercontent.com/35057623/175451176-6e02a991-db44-43cd-a1f6-4cfb1885f490.png)

### 期待的正确结果
toJavaObject方法后和1.2.83版本一致

**Comment by 914313670** [comment]
实体属性加上  @JSONField(format = "yyyy-MM-dd HH:mm:ss") 会报错，反之不会

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本
