### ISSUE TITLE
ParserConfig

### ISSUE THREAD

**Issue by xhygege** [alibaba/fastjson2#505]
fastjson2中ParserConfig取消了propertyNamingStrategy属性，要实现如下转换，请问要怎么处理呢？
 ParserConfig config = ParserConfig.getGlobalInstance();
 config.propertyNamingStrategy = PropertyNamingStrategy.CamelCase;
 jsonObj.toJavaObject(clazz, config, 0);

**Comment by VictorZeng** [comment]
@xhygege `JSONReader.Feature.SupportSmartMatch` 是否能满足您的场景 
see https://github.com/alibaba/fastjson2/blob/main/docs/features_cn.md

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.8
问题已经修复，请用新版本

**Comment by xhygege** [comment]
谢谢解答，问题已经处理
