### ISSUE TITLE
[QUESTION] FastJsonHttpMessageConverter  如何统一自定义反序列化时间格式

### ISSUE THREAD

**Issue by fanyawei** [alibaba/fastjson2#506]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
LocalDateTime或LocalDate在反序列化的时候，如何统一自定义，而不需要在第一个字段上加  @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") 这样的注解。
前端提交的参数，可能是yyyy-MM-dd HH:mm:ss 这样的格式，也可能是 yyyy-MM-dd HH:mm这样的格式，我想让它两个都能反序列化，在哪里可以配置或自定义反序列化逻辑？

**Comment by VictorZeng** [comment]
@fanyawei 在FastjsonConfig中设置dateformat试试能否满足你的场景
