### ISSUE TITLE
[BUG] 2.0.9序列化set

### ISSUE THREAD

**Issue by alon-sys** [alibaba/fastjson2#513]
版本 2.0.9-SNAPSHOT
Redis序列化方式：GenericFastJsonRedisSerializer
问题：
Could not deserialize: offset 1, character S, line 1, column 2, fastjson-version 2.0.9 Set["1541357098843803649"]; nested exception is com.alibaba.fastjson2.JSONException: offset 1, character S, line 1, column 2, fastjson-version 2.0.9 Set["1541357098843803649"]

操作：
set<String> ids = new HashSet<>();
redisTemplate.opsForValue().set(key, ids);

redisTemplate.opsForValue().get(key);

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
问题已修复，请帮忙更新快照2.0.9-SNAPSHOT验证

**Comment by alon-sys** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/ 问题已修复，请帮忙更新快照2.0.9-SNAPSHOT验证

可以了，谢谢

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
