### ISSUE TITLE
[BUG] 日期转json字串时出现\u0000

### ISSUE THREAD

**Issue by zhanglizhi77** [alibaba/fastjson2#516]
### 问题描述
*简要描述您碰到的问题。*

从object转json字串时，对日期字段的转换出现
"2022-02-21 14:33:02.012\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
我测试发现，IBM JDK不能正常转换，Oracle官方JDK可以，OpenJDK没有测试。

### 环境信息
*请填写以下信息：*

 - OS信息：  Windows 10家庭版 4Core 3.10GHz 32 GB
 - JDK信息：IBM JDK 1.8.0_322
 - 版本信息：Fastjson2 2.0.8
 

### 重现步骤
*如何操作可以重现该问题：*

随意的对象（含Date类型字段）序列化成json字串

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
可以按指定格式输出日期字串，如
JSON.toJSONString(data, "yyyy-MM-dd HH:mm:ss.SSS");

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
{
			"birthDate": "2022-02-21 14:33:02.012\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
}

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
data是什么类型？

**Comment by zhanglizhi77** [comment]
data是个随意的类型，比如
class ClassA{
private Date birthDate;//这个字段转json字串有问题
}

**Comment by zhanglizhi77** [comment]
是使用的**IBM** JDK 1.8.0_322吗？
IBM的

**Comment by wenshao** [comment]
不是的，我手上没有IBM JDK的环境

**Comment by zhanglizhi77** [comment]
是否可以安装下环境试下呢？还是我将问题关闭了？
[https://developer.ibm.com/languages/java/semeru-runtimes/downloads/](url)

**Comment by wenshao** [comment]
我来做验证吧

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
在IBM OpenJ9 8.0上确实是有问题，问题已修复，请帮忙更新快照2.0.9-SNAPSHOT验证，2.0.9版本预计在7月10日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
