### ISSUE TITLE
[BUG]不支持 Vector 反序列化吗?

### ISSUE THREAD

**Issue by stephenlam520** [alibaba/fastjson2#517]
### 问题描述
反序列化时如果bean 有vector 就报错java.lang.UnsupportedOperationException, 换成List 就没事

### 环境信息
*请填写以下信息：*

 - OS信息：  [win10]
 - JDK信息： [Oraclejdk 1.8.0_312]
 - 版本信息：[Fastjson2 2.0.8]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSON.parseObject(str, clazz) 方法

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
问题已经修复，请用2.0.9-SNAPSHOT验证，2.0.9版本预计在7月10日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
