### ISSUE TITLE
[BUG]android 使用 fastjson2 序列化崩溃

### ISSUE THREAD

**Issue by wolfhawk163** [alibaba/fastjson2#520]
### 问题描述
- android targetSdk 31
- 使用 fastjson2，版本 2.0.8

- 测试代码如下
```java

  Map<String, String> test = new HashMap<>();
        test.put("key0", "value0");
        String json = JSON.toJSONString(test);
        System.out.println(json );
```

- 结果：崩溃

- 将 fastjson2 换成 fastjson，版本 1.2.71
- 没有问题

**Comment by wenshao** [comment]
你用2.0.8.android

**Comment by wolfhawk163** [comment]
> 你用2.0.8.android

是的 
```shell
implementation 'com.alibaba:fastjson:2.0.8'
```

换成 1.2.71 没问题了

**Comment by wenshao** [comment]
用这个：
```java
com.alibaba:fastjson:2.0.8.android
```

**Comment by wolfhawk163** [comment]
> 用这个：
> 
> ```java
> com.alibaba:fastjson:2.0.8.android
> ```

可以了 谢谢

**Comment by wolfhawk163** [comment]
> 用这个：
> 
> ```java
> com.alibaba:fastjson:2.0.8.android
> ```

可以了 谢谢

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
