### ISSUE TITLE
[BUG] 如果存在重名的set方法，就会导致反序列异常

### ISSUE THREAD

**Issue by VirensCn** [alibaba/fastjson2#523]
### 问题描述

如下图，有2个setType,一个是数值参数，一个是枚举参数，然后使用fastjson反序列化时就会导致异常，json字符串中是Integer类型，但是它会使用到枚举那个setType，最终导致异常。

![image](https://user-images.githubusercontent.com/9736815/176804115-1f3405ed-a5cc-4783-86f8-0ef51b6dc3de.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
问题已修复，请用2.0.9-SNAPSHOT版本验证，2.0.9版本预计在7月10日发布。

修复的办法是，Integer/int类型优先于Enum类型

**Comment by VirensCn** [comment]
这样不是治标不治本么？没先根据字段类型获取对应的set方法，如果没有在基础类型>包装类型

**Comment by wenshao** [comment]
确实是，多个setter方法时，目前只能选择一个

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
