### ISSUE TITLE
[FEATURE]如何得到反序列化的Type

### ISSUE THREAD

**Issue by leonchen83** [alibaba/fastjson2#527]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*

fastjson1的兼容包里`return deserialze(parser, null, null);`, 这里的type和fieldName都是null
```
public interface ObjectDeserializer
        extends ObjectReader {
    @Override
    default Object readObject(JSONReader jsonReader, long features) {
        DefaultJSONParser parser = new DefaultJSONParser(jsonReader, ParserConfig.global);
        return deserialze(parser, null, null);
    }

    <T> T deserialze(DefaultJSONParser parser, Type type, Object fieldName);

    default int getFastMatchToken() {
        return JSONLexer.UNKNOWN;
    }
}
```

那么在写fastjson2的反序列化器，实现ObjectReader时，如何得到`type`与`field`, 我们定制了很多自己的序列化器与反序列化器，需要这个类型信息, fastjson1可以做到取得这个类型信息， jackson 的话实现`ContextualDeserializer`也可以做到取得类型信息

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by leonchen83** [comment]
建议2 ，能不能做一个非static方法的JSON对象，需要做序列化器与反序列化器的不同使用方式的隔离，用JSON.register就做成全局注册了

建议3,  由于上述的原因，我们自己单独创建了`JSONWriter.Context`, `ObjectWriterProvider`, `JSONWriter`等对象
JSONWriter.Context里的configFilter() 是一个protected方法，我们有很多filter, 所以我们还得自己扩展将其转换成public
```
public class XWriterContext extends JSONWriter.Context {
	
	/**
	 * 
	 */
	public XWriterContext(ObjectWriterProvider provider) {
		super(provider);
	}
	
	public XWriterContext(ObjectWriterProvider provider, JSONWriter.Feature... features) {
		super(provider, features);
	}
	
	/**
	 * 
	 */
	@Override
	public void configFilter(Filter... filters) {
		super.configFilter(filters);
	}
}
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本
