### ISSUE TITLE
[BUG] 如果待反序列化内容有null。就会导致java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by VirensCn** [alibaba/fastjson2#528]
![image](https://user-images.githubusercontent.com/9736815/177280813-40b99515-caf2-49fa-a942-a225592f52ca.png)

![image](https://user-images.githubusercontent.com/9736815/177280779-e1d9a058-663a-4985-8676-d8ccef1990f1.png)

![image](https://user-images.githubusercontent.com/9736815/177280843-dd938d3e-987d-49be-8b29-3b581ddf2ef0.png)

我这里主要是将数组长度估计10个，所以序列化出来的存在null，但是将序列化结果反序列化就会导致内存溢出

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.9-SNAPSHOT/
请帮忙用2.0.9-SNAPSHOT版本验证问题是否已经修复

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
问题已修复，请用新版本

**Comment by NeverMorewhz** [comment]
你好，2.0.9版本依然有这个问题
<img width="612" alt="111" src="https://user-images.githubusercontent.com/11847788/180125812-38940e9c-14a9-4c0e-8187-4b3e74e635a7.png">
空值数组序列化，服务直接内存溢出
