### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by bigzeroo** [alibaba/fastjson2#530]
### 嗨，我们升级了fastjson到fastjson2最新版，配置的是兼容1.x的模式，但还是可以命令执行，不知道是什么原因，有什么排查办法吗
配置文件：
l29Book-Pro fastjson % cat pom.properties 
artifactId=fastjson
groupId=com.alibaba
version=2.0.7

检测方法:
post请求包：

POST /api/sso/HTTP/1.1

Host: xxx.xxxx.com

User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1866.237 Safari/537.36

Connection: close

Content-Length: 264

Content-Type: application/json

Cookie: _ga=GA1.2.198772880.1654741598; JSESSIONID=794E66E75C0AB1F5A8C7B79B35; token=7441c3a92663bb700b483b; uid=1; _gid=GA1.2.1708938524.1655454818

Upgrade-Insecure-Requests: 1

Accept-Encoding: gzip

{"@type":"java.net.Inet4Address","val":"dnslog"}

**Comment by wenshao** [comment]
是不是jar冲突优先加载了，不应该的

**Comment by bigzeroo** [comment]
> 是不是jar优先超出加载了，不应该的
我把服务jar宝解压了，只看到这三个fastjson包，而且也和官网maven仓库的fastjson对比了md5校验值，没问题
fastjson-2.0.7.jar
fastjson2-2.0.7.jar
fastjson2-extension-2.0.7.jar
