### ISSUE TITLE
[QUESTION] fastjson2对json path 支持不佳

### ISSUE THREAD

**Issue by oday-xiexin** [alibaba/fastjson2#532]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
详见 竞品对比报告 以及testcase
https://my.oschina.net/noear/blog/5549198

**Comment by wenshao** [comment]
性能测试看起来很不专业

**Comment by wenshao** [comment]
选择性一些case测试就说别的库支持不佳，这个结论不够中立吧

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.9
新版补充了一些新的语法支持，你可以验证下
