### ISSUE TITLE
[QUESTION]支持对【带下划线字段】到【驼峰字段】的自动转换吗？

### ISSUE THREAD

**Issue by ALLCX** [alibaba/fastjson2#533]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
fastjson1 版本收到{"ab_cd":"werwr"}，通过parseObject方法是可以自动匹配 类型中的 abCd字段的，fastjson2中好像不行了。请问，这个功能以后会加吗？或者说fastjson2中应该怎么写？没查到文档....使用文档太缺了...

**Comment by ALLCX** [comment]
看到有人提过这个问题，要显式使用用 smart feature。请问文档在哪里看呀...感谢

**Comment by wsxe9988** [comment]
https://github.com/alibaba/fastjson2/blob/main/docs/features_cn.md
