### ISSUE TITLE
2.x是如何支持在1.x的版本中PropertyPreFilters的？

### ISSUE THREAD

**Issue by qq12157138** [alibaba/fastjson2#535]
我在1.x版本可以这样过滤掉字段，2.x该怎么写？？？
```java
Object[] arg = new Object[];   // 假设这个数组中有很多数据

String[] excludeProperties = {"name", "address"};
PropertyPreFilters filters = new PropertyPreFilters();
PropertyPreFilters.MySimplePropertyPreFilter excludeFilter = filters.addFilter();
excludeFilter.addExcludes(excludeProperties);
log.debug(JSONObject.toJSONString(arg, excludeFilter));
```

**Comment by wenshao** [comment]
和1.x类似，改变的是Filter的package变为com.alibaba.fastjson2.filter，如下：
```java
imports com.alibaba.fastjson2.filter;

JSON.toJSONString(obj, filters);
```

**Comment by RikaShiro** [comment]
同问。请问可以提供更改后的代码模板吗

**Comment by YafengLiang** [comment]
`
 /** 排除敏感属性字段 */
    public static final String[] EXCLUDE_PROPERTIES = { "password", "oldPassword", "newPassword", "confirmPassword" };
 public SimplePropertyPreFilter excludePropertyPreFilter()
    {
        return new SimplePropertyPreFilter(EXCLUDE_PROPERTIES);
    }
`
如上修改即可

**Comment by YafengLiang** [comment]
可以使用SimplePropertyPreFilter代替，看了下源码。应该是没写完，我现在是2.0.52最新版，
![image](https://github.com/user-attachments/assets/839d7f48-0528-4f82-ab3f-f95d1858d530)
只有包含的代码，没有排除的代码，可以考虑参考自写一个，期待更新

**Comment by YafengLiang** [comment]
`@Getter
public class SimplePropertyPreFilter implements PropertyPreFilter {

    private final Class<?> clazz;
    private final Set<String> includes;
    private final Set<String> excludes;
    private int maxLevel;


    public SimplePropertyPreFilter(String... properties) {
        this((Class)null, properties);
    }

    public SimplePropertyPreFilter(Class<?> clazz, String... properties) {
        this.includes = new HashSet<>();
        this.excludes = new HashSet<>();
        this.clazz = clazz;
        String[] var3 = properties;
        int var4 = properties.length;

        for(int var5 = 0; var5 < var4; ++var5) {
            String item = var3[var5];
            if (item != null) {
                this.excludes.add(item);
            }
        }

    }

    public void setMaxLevel(int maxLevel) {
        this.maxLevel = maxLevel;
    }

    @Override
    public boolean process(JSONWriter writer, Object source, String name) {
        if (source == null) {
            return true;
        } else if (this.clazz != null && !this.clazz.isInstance(source)) {
            return true;
        } else if (this.excludes.contains(name)) {
            return false;
        } else if (this.maxLevel > 0 && writer.level() > this.maxLevel) {
            return false;
        } else {
            return this.includes.size() == 0 || this.includes.contains(name);
        }
    }
}`

**Comment by YafengLiang** [comment]
#### 完整代码如下：

`import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.filter.PropertyPreFilter;
import lombok.Getter;

import java.util.HashSet;
import java.util.Set;

/**
 *
 * <p>Project: rtn - SimplePropertyPreFilter
 * @author: liangyafeng
 * <p>Date: 2024-09-03 14:22:11
 * <p>Description: json排除指定内容
 */
 
@Getter
public class SimplePropertyPreFilter implements PropertyPreFilter {

    private final Class<?> clazz;
    private final Set<String> includes;
    private final Set<String> excludes;
    private int maxLevel;


    public SimplePropertyPreFilter(String... properties) {
        this(null, properties);
    }

    public SimplePropertyPreFilter(Class<?> clazz, String... properties) {
        this.includes = new HashSet<>();
        this.excludes = new HashSet<>();
        this.clazz = clazz;

        for (String item : properties) {
            if (item != null) {
                this.excludes.add(item);
            }
        }

    }

    @Override
    public boolean process(JSONWriter writer, Object source, String name) {
        if (source == null) {
            return true;
        } else if (this.clazz != null && !this.clazz.isInstance(source)) {
            return true;
        } else if (this.excludes.contains(name)) {
            return false;
        } else if (this.maxLevel > 0 && writer.level() > this.maxLevel) {
            return false;
        } else {
            return this.includes.isEmpty() || this.includes.contains(name);
        }
    }
}`
