### ISSUE TITLE
[QUESTION]Android O (--min-api 26)

### ISSUE THREAD

**Issue by jacksonjim** [alibaba/fastjson2#543]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
com.android.tools.r8.internal.a2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

**Comment by wenshao** [comment]
用的是什么版本？

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kraity** [comment]
fastjson2目标java8+, 在安卓上是使用MethodHandle, 虽然MethodHandle是jdk7加的但是安卓是在Android API26(安卓8)才支持MethodHandle, 故而需要您的项目`app\build.gradle`minSdk设置为26

样例:
```java
android {
    defaultConfig {
        ..................
        minSdk 26
        ..................
    }
     ..................
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by tzSharing** [comment]
Android studio上用java或kotlin版确实会出现minSdk 小于26时报错问题。
解决方法：
用这个 `implementation "com.alibaba.fastjson2:fastjson2:2.0.10.android"`

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wenshao** [comment]
fastjson2只支持Android 8+(API Level 26)以上的版本

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by TanZhiL** [comment]
> Android studio上用java或kotlin版确实会出现minSdk 小于26时报错问题。 解决方法： 用这个 `implementation "com.alibaba.fastjson2:fastjson2:2.0.10.android"`

那后续的功能就用不了了吗？求大佬出兼容版本 @jacksonjim

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
