### ISSUE TITLE
[BUG]not allow unquoted fieldName, offset 2, character c, line 1, column 3, fastjson-version 2.0.9 {code:1234}

### ISSUE THREAD

**Issue by woniudiancang** [alibaba/fastjson2#544]
2.0.9 没有引号的json还是无法反序列化

`
JSONObject json1 = JSON.parseObject("{code:1234}");

System.out.println(json1);

JSONObject json2 = JSONObject.parseObject("{code:1234}");

System.out.println(json2);
`

报错：

`
Exception in thread "main" com.alibaba.fastjson2.JSONException: not allow unquoted fieldName, offset 2, character c, line 1, 

column 3, fastjson-version 2.0.9 {code:1234}

	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1378)

	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:142)

	at test.Test.main(Test.java:21)

`

**Comment by wsxe9988** [comment]
JSONObject object1 = JSON.parseObject("{code:1234}",JSONReader.Feature.AllowUnQuotedFieldNames);
System.out.println(object1);

**Comment by woniudiancang** [comment]
这样好麻烦呀，从 1.0 迁移过去的代码，意味着所有的地方都要增加一个参数了，有没有通过全局配置的方式去实现呢？减少 1.0 升级到 2.0 的障碍

**Comment by woniudiancang** [comment]
否则很多项目中用的1.0，如果都需要增加参数的话，可能升级代码侵入太强，升级阻碍会比较大，看看大佬们能不能好好考虑一下这个问题，尽可能的减少1.0到2.0的升级难度哦～

**Comment by wenshao** [comment]
JSON.config这个方法

**Comment by woniudiancang** [comment]
> JSON.config这个方法是全局配置的

这个方法有个 boolean state 参数，没看到有注释说明啥意思，能否帮忙解释一下这个 state 参数是做什么用的

**Comment by wenshao** [comment]
true就是打开，false就是关闭
