### ISSUE TITLE
[BUG]CamelCase has some problems

### ISSUE THREAD

**Issue by SuperEdison** [alibaba/fastjson2#546]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  Mac M1
 - JDK信息： zulu8
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `BeanUtils.getterName` 方法
2. 输入 `UId`  数据
3. 出现 `UId` 错误
```java
    public static void main(String[] args) {
        A vo = new A();
        vo.setCId("2");
        System.out.println(JSON.toJSONString(vo));
        //{"CId":"2"}
    }

    @Data
    static public  class A {
        private String uId;
        private String cId;
    }
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
//{"cId":"2"}

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

{"CId":"2"}
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
<img width="668" alt="image" src="https://user-images.githubusercontent.com/84554944/178403353-4deb7db3-a4fa-4cc8-9ef3-e7633e94f58f.png">

**Comment by SuperEdison** [comment]
and than i found the error code that is here

<img width="642" alt="image" src="https://user-images.githubusercontent.com/84554944/178403558-0d743c39-b8c4-4bdb-869b-e56d36153a98.png">

CamelCase's definition is the first word is lowercase. but here why do you add char[1] && chars[1] <= 'Z' judge

**Comment by SuperEdison** [comment]
my mr [https://github.com/alibaba/fastjson2/pull/547](url)

**Comment by SuperEdison** [comment]
fastjson v1 is use reflect to solve fields name, but fastjson2 is use gettername to solve fields name. so i think need to use CamelCase definition to make obvious distinction.

**Comment by wenshao** [comment]
```java
  @Test
    public void test2() {
        assertEquals("abc", JSON.parseObject("{\"uId\":\"abc\"}", C.class).uId);
        assertEquals("abc", JSON.parseObject("{\"UId\":\"abc\"}", C.class).uId);
    }

    public static class C {
        private String uId;

        public String getUId() {
            return uId;
        }

        public void setUId(String uId) {
            this.uId = uId;
        }
    }
```
最新快照版本反序列化已经能支持自动识别多种输入

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
