### ISSUE TITLE
[BUG] 兼容版本2.0.9 JSON.parseObject 转换实体   时间格式空串会默认 1970-01-01 08:00:00属性值 

### ISSUE THREAD

**Issue by afish177** [alibaba/fastjson2#550]
### 问题描述
*简要描述您碰到的问题。*
升级兼容版本 2.0.9 出现 转换实体 时间类型空串 默认1970 数据值
1.2.83 没这默认 

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_201]
 - 版本信息：[e.g.：Fastjson 2.0.9]
 

### 重现步骤
*如何操作可以重现该问题：*
 

1. 使用 JSON.parseObject方法
2. 输入{"ieFlag":"I","isIgnore":"0","status":0,"ciqStatus":"","bizDate":"2022-07-12","ciqCommitType":"0","customMaster":"4732","cusType":"1","seqNo":"","preEntryId":"","entryId":"","iePort":"4732","manualNo":"E534118A0032","ieDate":"2022-07-12","ddate":""} 数据
3. 出现  对应实体 ddate 属性 不是null  而是默认  1970-01-01 08:00:00  错误
```java
//可在此输入示例代码
```
JSON.parseObject({"ieFlag":"I","isIgnore":"0","status":0,"ciqStatus":"","bizDate":"2022-07-12","ciqCommitType":"0","customMaster":"4732","cusType":"1","seqNo":"","preEntryId":"","entryId":"","iePort":"4732","manualNo":"E534118A0032","ieDate":"2022-07-12","ddate":""} , 实体.class);
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

 对应实体 ddate 属性 应该是null 而不是默认1970 这样得数据  因为是空串  
### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
如图 调试 信息

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://user-images.githubusercontent.com/32056262/178461010-abf81f04-ba30-4a99-a0f3-bf916c3a30ff.png)
![image](https://user-images.githubusercontent.com/32056262/178461033-529b3fc7-4c02-4da7-8553-5bdc1ce2edb1.png)
![image](https://user-images.githubusercontent.com/32056262/178461057-eb181bab-ceda-416a-8964-efc205bb4e65.png)
![image](https://user-images.githubusercontent.com/32056262/178461085-d31274fa-0f34-4e8f-b9fa-4d79426f5475.png)
![image](https://user-images.githubusercontent.com/32056262/178461104-815e535f-1c62-42a3-9e94-20d03a4685af.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.10-SNAPSHOT/
问题已修复，请用2.0.10-SNAPSHOT版本验证，2.0.10版本预计在7月底发布

**Comment by afish177** [comment]
好的 我试试 谢谢大佬
&nbsp;


浮生ふ物语
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月13日(星期三) 上午9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/fastjson2] [BUG] 兼容版本2.0.9 JSON.parseObject 转换实体   时间格式空串会默认 1970-01-01 08:00:00属性值  (Issue #550)





 
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.10-SNAPSHOT/
 问题已修复，请用2.0.10-SNAPSHOT版本验证，2.0.10版本预计在7月底发布

**Comment by afish177** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.10-SNAPSHOT/ 问题已修复，请用2.0.10-SNAPSHOT版本验证，2.0.10版本预计在7月底发布

我用的 是1.x的 兼容版本 包名不是fastjson2的 
 <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>fastjson</artifactId>
      <version>2.0.9</version>
    </dependency>

能否 给一个 这个2.0.10的 快照

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.10-SNAPSHOT/

**Comment by afish177** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.10-SNAPSHOT/
![image](https://user-images.githubusercontent.com/32056262/178693187-db769df8-3f51-4ce4-a4a1-e84ca2758891.png)
是哪里 不对吗

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
问题已修复，请用新版本
