### ISSUE TITLE
[BUG]Tuple2<A,B>被序列化为List<Object>

### ISSUE THREAD

**Issue by pusabless** [alibaba/fastjson2#554]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息

 - OS信息：  macos
 - JDK信息：Openjdk 1.8.0_312
 - 版本信息：Fastjson2 2.0.8
 

### 重现步骤

1. Tuples.of(new A(),new B())构造Tuple2<A,B> data对象
2. 使用com.alibaba.fastjson2.JSON.toJSONString(data) 
3. 输出结果为[{},{}]

### 期待的正确结果
期望输出{"t1":{},"t2":{}}

#### 附加信息
com.alibaba.fastjson和gson的序列化结果都是 {"t1":{},"t2":{}}

**Comment by wsxe9988** [comment]
麻烦提供下完整的case,以供复现

**Comment by pusabless** [comment]
public class Test {
   static class A{
        private String a;
        public A(String a) {
            this.a = a;
        }

       public String getA() {
           return a;
       }

       public void setA(String a) {
           this.a = a;
       }
   }
    static class B{
        private String b;
        public B(String b) {
            this.b = b;
        }

        public String getB() {
            return b;
        }

        public void setB(String b) {
            this.b = b;
        }
    }
    public static void main(String[] args) {
        Tuple2<A,B> data = Tuples.of(new A("a"),new B("b"));
        Gson gson = new Gson();
        System.out.println("fastjson2:"+com.alibaba.fastjson2.JSON.toJSON(data));
        System.out.println("fastjson:" + com.alibaba.fastjson.JSON.toJSON(data));
        System.out.println("gson:"+ gson.toJson(data));
    }
}


输出结果：
![image](https://user-images.githubusercontent.com/25945400/178637846-0e9d5f1c-bd2e-4d30-afae-6326abc20ef2.png)

**Comment by wsxe9988** [comment]
Tuples，Tuple2这两个类是什么呢，能提供下么

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.10-SNAPSHOT/
问题已修复，请用2.0.10-SNAPSHOT版本验证，2.0.10版本预计在2月24日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
问题已修复，请用新版本
