### ISSUE TITLE
Set类型集合无法正常反序列化

### ISSUE THREAD

**Issue by 1455668754** [alibaba/fastjson2#555]
### 问题描述
对象中存在Set类型集合时，序列化时会添加Set标识，但无法正常反序列化获取到数据
![image](https://user-images.githubusercontent.com/88491446/178637164-98b4bbf7-1c39-4167-b72e-4271fa60d365.png)
![image](https://user-images.githubusercontent.com/88491446/178636754-3daf1586-50fc-4eaf-9a4c-9db5aa233c72.png)
![image](https://user-images.githubusercontent.com/88491446/178636917-132e60bd-8069-48d7-864a-fe4ee75a9e8f.png)
(实测：手动移除掉Set标识后，可正常反序列化)

版本： 在>2.0.4版本均存在该问题（包括最新发布的2.0.9版本）

**Comment by wsxe9988** [comment]
麻烦提供下完整的case,以供复现

**Comment by wenshao** [comment]
问题没重现，需要帮助提供重现问题的testcase

**Comment by 1455668754** [comment]
import com.alibaba.fastjson2.JSON;
import java.util.Set;

public class Test {

    public static void main(String[] args)  {
        // 反序列化异常 （有Set）
        String ss =  "{\"@type\":\"com.xueyi.system.api.model.LoginUser\",\"enterpriseId\":1,\"enterpriseName\":\"administrator\",\"expireTime\":1657824093068,\"ipaddr\":\"127.0.0.1\",\"isLessor\":\"Y\",\"loginTime\":1657780893068,\"permissions\":Set[\"*:*:*\"],\"roleIds\": Set[],\"roles\":Set[\"administrator\",\"admin\"],\"scope\":{\"dataScope\":\"1\",\"deptScope\":Set[],\"postScope\":Set[],\"userScope\":Set[]},\"sourceName\":\"slave\",\"token\":\"d9d04f73-6933-47b5-8549-963733b96ddf\",\"userId\":1,\"userName\":\"admin\",\"userType\":\"00\"}";
        // 可正常序列化 （无Set）
//        String ss =  "{\"@type\":\"com.xueyi.system.api.model.LoginUser\",\"enterpriseId\":1,\"enterpriseName\":\"administrator\",\"expireTime\":1657824093068,\"ipaddr\":\"127.0.0.1\",\"isLessor\":\"Y\",\"loginTime\":1657780893068,\"permissions\":[\"*:*:*\"],\"roleIds\": [],\"roles\":[\"administrator\",\"admin\"],\"scope\":{\"dataScope\":\"1\",\"deptScope\":[],\"postScope\":[],\"userScope\":[]},\"sourceName\":\"slave\",\"token\":\"d9d04f73-6933-47b5-8549-963733b96ddf\",\"userId\":1,\"userName\":\"admin\",\"userType\":\"00\"}";

        LoginUser bean = JSON.parseObject(ss, LoginUser.class);
//        Bean bean = JSON.parseObject("{\"values\":Set[]}", Bean.class);
        System.out.println(bean);
    }

    public static class LoginUser {

        private static final long serialVersionUID = 1L;

        /** 用户唯一标识 */
        private String token;

        /** 企业账号Id */
        private Long enterpriseId;

        /** 企业账号 */
        private String enterpriseName;

        /** 租户标识 */
        private String isLessor;

        /** 用户名Id */
        private Long userId;

        /** 用户名 */
        private String userName;

        /** 用户标识 */
        private String userType;

        /** 主数据源 */
        private String sourceName;

        /** 登录时间 */
        private Long loginTime;

        /** 过期时间 */
        private Long expireTime;

        /** 登录IP地址 */
        private String ipaddr;

        /** 权限列表 */
        private Set<String> permissions;

        /** 角色权限列表 */
        private Set<String> roles;

        /** 角色Id列表 */
        private Set<Long> roleIds;

        public String getToken() {
            return token;
        }

        public void setToken(String token) {
            this.token = token;
        }

        public Long getEnterpriseId() {
            return enterpriseId;
        }

        public void setEnterpriseId(Long enterpriseId) {
            this.enterpriseId = enterpriseId;
        }

        public String getEnterpriseName() {
            return enterpriseName;
        }

        public void setEnterpriseName(String enterpriseName) {
            this.enterpriseName = enterpriseName;
        }

        public String getIsLessor() {
            return isLessor;
        }

        public void setIsLessor(String isLessor) {
            this.isLessor = isLessor;
        }

        public Long getUserId() {
            return userId;
        }

        public void setUserId(Long userId) {
            this.userId = userId;
        }

        public String getUserName() {
            return userName;
        }

        public void setUserName(String userName) {
            this.userName = userName;
        }

        public String getUserType() {
            return userType;
        }

        public void setUserType(String userType) {
            this.userType = userType;
        }

        public String getSourceName() {
            return sourceName;
        }

        public void setSourceName(String sourceName) {
            this.sourceName = sourceName;
        }

        public Long getLoginTime() {
            return loginTime;
        }

        public void setLoginTime(Long loginTime) {
            this.loginTime = loginTime;
        }

        public Long getExpireTime() {
            return expireTime;
        }

        public void setExpireTime(Long expireTime) {
            this.expireTime = expireTime;
        }

        public String getIpaddr() {
            return ipaddr;
        }

        public void setIpaddr(String ipaddr) {
            this.ipaddr = ipaddr;
        }

        public Set<String> getPermissions() {
            return permissions;
        }

        public void setPermissions(Set<String> permissions) {
            this.permissions = permissions;
        }

        public Set<String> getRoles() {
            return roles;
        }

        public void setRoles(Set<String> roles) {
            this.roles = roles;
        }

        public Set<Long> getRoleIds() {
            return roleIds;
        }

        public void setRoleIds(Set<Long> roleIds) {
            this.roleIds = roleIds;
        }

    }
}

**Comment by 1455668754** [comment]
可以直接拿这整段测试（不好意思，没找到怎么上传文件），简单的Set集合对象是可以转换的，但是在复杂对象中，无法正常转换，demo中我测试了两个情况，前者是有Set标识，无法正常转换，后者无Set标识，可以正常转换（注释掉的ss字符串）

**Comment by 1455668754** [comment]
可以直接拿这整段测试（不好意思，没找到怎么上传文件），简单的Set集合对象是可以转换的，但是在复杂对象中，无法正常转换，demo中我测试了两个情况，前者是有Set标识，无法正常转换，后者无Set标识，可以正常转换（注释掉的ss字符串）

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.10-SNAPSHOT/
问题已经修复，请用2.0.10-SNAPSHOT版本验证，2.0.10预计在7月24日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
问题已修复，请用新版本
