### ISSUE TITLE
[BUG]jsonobject里的record类型序列化异常

### ISSUE THREAD

**Issue by cjdxhjj** [alibaba/fastjson2#559]
### 问题描述
*简要描述您碰到的问题。*
如图
![image](https://user-images.githubusercontent.com/5616997/178728677-027e2d48-8ac7-4829-95e4-578c2d72855b.png)

![image](https://user-images.githubusercontent.com/5616997/178728747-eeedcc72-613f-4a86-b307-2c3786bf0813.png)

![image](https://user-images.githubusercontent.com/5616997/178728807-cb832b17-2264-401c-99ab-49e1e84d5d7d.png)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
public record LogoutEntity(String serviceTicket, String url) {
}
var jo = new JSONObject();
        jo.put("type", 2);
        jo.put("id", "cxcc");
        jo.put("uid", "uid");
        jo.put("data", List.of(new LogoutEntity("aa","111"), new LogoutEntity("bbb", "222")));
        System.out.println(jo.toJSONString());
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by SuperEdison** [comment]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/84554944/178761146-15d31cbd-c510-414f-8c98-765d5c64be4c.png">
没有任何问题，看看是不是没有get方法

**Comment by cjdxhjj** [comment]
public record LogoutEntity(String serviceTicket, String url) {
}
这个是record

**Comment by cjdxhjj** [comment]
我本地百分百重现
win10 64, fastjson2 2.0.9, java 17

**Comment by babydragon** [comment]
我也遇到同样问题 ，直接使用JSON.toJSONString序列化一个Record,返回的是"{}"
Linux java open jdk 17, fastjson2 2.0.9

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
问题已修复，请用新版本
