### ISSUE TITLE
[QUESTION]在fastjson1时，Long全部转为字符串，现在fastjson2该如何处理？

### ISSUE THREAD

**Issue by zacat** [alibaba/fastjson2#563]
Fastjson 1时的配置      

        FastJsonHttpMessageConverter fastJsonConverter = new FastJsonHttpMessageConverter();
        FastJsonConfig fjc = new FastJsonConfig();
        SerializeConfig serializeConfig = SerializeConfig.globalInstance;
        serializeConfig.put(Long.class , ToStringSerializer.instance);
        serializeConfig.put(Long.TYPE , ToStringSerializer.instance);
        fjc.setSerializeConfig(serializeConfig);
        fastJsonConverter.setFastJsonConfig(fjc);
        converters.add(fastJsonConverter);

**Comment by zacat** [comment]
但我这里的前端要求如果是Long的都用字符串返回？我现在变成只能用ValueFilter来处理，没有办法使用上面的方法。

**Comment by gzymomo** [comment]
@zacat  有解吗

**Comment by zacat** [comment]
@gzymomo 自已写一个ValueFilter来处理。

**Comment by hongshuo-wang** [comment]
目前找到这个函数可以实现该功能`JSON.register(Long.class, ObjectWriters.ofToString(Object::toString));`

**Comment by wenshao** [comment]
```java
JSON.toJSONString(obj, JSONWriter.Feature.WriteLongAsString)
```
也可以用这个

**Comment by duanluan** [comment]
使用 [2.1 Spring Web MVC Converter](https://github.com/alibaba/fastjson2/blob/main/docs/spring_support_cn.md#21--spring-web-mvc-converter) 时，可以`config.setWriterFeatures(JSONWriter.Feature.WriteLongAsString)`。
