### ISSUE TITLE
[BUG]Typeutils转换char类型到String类型再通过Typeutils转换回char类型时会导致char的值变成"

### ISSUE THREAD

**Issue by FanJiaRui** [alibaba/fastjson2#564]
### 问题描述
使用Fastjson提供的Typeutils转换char类型到String类型再通过Typeutils转换回char类型时会导致char的值变成"

原因应该是因为char类型经过Typeuitls转换为String时变成了"1",然而转换回char时取的第一个字符正好为"导致
char转字符串加双引号是否有问题不好说,但我觉得Typeuitls双向转换之后值失真应该是个bug

### 环境信息
*请填写以下信息：*

 - OS信息：  Windows 10
 - JDK信息： Oracle jdk 1.8.0_201
 - 版本信息：Fastjson2 2.0.10-SNAPSHOT
 

### 重现步骤
执行以下代码
```
public class TestUtils {
    public static void main(String[] args) {
        char a = '1';
        String str = TypeUtils.cast(a, String.class);
        char b = TypeUtils.cast(str, char.class);
        System.out.println(a);
        System.out.println(b);
    }
}
```

### 期待的正确结果
预期输出结果为
1
1

### 相关日志输出
 然而实际输出结果为
1
"

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.10-SNAPSHOT/
问题已经修复，请用2.0.10-SNAPSHOT版本验证，2.0.10预计在7月24日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
问题已修复，请用新版本
