### ISSUE TITLE
[BUG] 子类对象无法反序列化

### ISSUE THREAD

**Issue by leshalv** [alibaba/fastjson2#567]

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by leshalv** [comment]
```java
package com.example.fastjson2;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
public class Test {

    private Config config;

    @Data
    public static class Config{

    }

    @Data
    @EqualsAndHashCode(callSuper = true)
    public static class CatConfig extends Config{
        private String height;
        private String width;
    }

    public static void main(String[] args) {
        CatConfig catConfig = new CatConfig();
        catConfig.setHeight("200");
        catConfig.setWidth("100");
        Test test = new Test();
        test.setConfig(catConfig);
        String json = JSON.toJSONString(test, JSONWriter.Feature.WriteClassName);
        System.out.println(json);
        //JSON结果 {"@type":"com.example.fastjson2.Test","config":{"@type":"com.example.fastjson2.Test$CatConfig","height":"200","width":"100"}}
        Test t = (Test) JSON.parseObject(json, Test.class);
        System.out.println(t.getConfig());
        //对象结果：Test.Config() 
    }
}
```

**Comment by wuyuweixin** [comment]
+1

**Comment by wuyuweixin** [comment]
+1

**Comment by kuacode** [comment]
> ```java
> package com.example.fastjson2;
> 
> import com.alibaba.fastjson2.JSON;
> import com.alibaba.fastjson2.JSONWriter;
> import lombok.Data;
> import lombok.EqualsAndHashCode;
> 
> @Data
> public class Test {
> 
>     private Config config;
> 
>     @Data
>     public static class Config{
> 
>     }
> 
>     @Data
>     @EqualsAndHashCode(callSuper = true)
>     public static class CatConfig extends Config{
>         private String height;
>         private String width;
>     }
> 
>     public static void main(String[] args) {
>         CatConfig catConfig = new CatConfig();
>         catConfig.setHeight("200");
>         catConfig.setWidth("100");
>         Test test = new Test();
>         test.setConfig(catConfig);
>         String json = JSON.toJSONString(test, JSONWriter.Feature.WriteClassName);
>         System.out.println(json);
>         //JSON结果 {"@type":"com.example.fastjson2.Test","config":{"@type":"com.example.fastjson2.Test$CatConfig","height":"200","width":"100"}}
>         Test t = (Test) JSON.parseObject(json, Test.class);
>         System.out.println(t.getConfig());
>         //对象结果：Test.Config() 
>     }
> }
> ```
> 
> fastjson1 版本是可以的，fastjson2 不可以，升级失败！

Test t = JSON.parseObject(json, Test.class, JSONReader.Feature.SupportAutoType);
System.out.println(t.getConfig().getClass() == CatConfig.class);

**Comment by leshalv** [comment]
这个BUG大概什么版本可以修复？ @wenshao

**Comment by wenshao** [comment]
> 这个BUG大概什么版本可以修复？ @wenshao

问题无法重现哦，你用2.0.11版本再试试看？

**Comment by leshalv** [comment]
> > 这个BUG大概什么版本可以修复？ @wenshao
> 
> 问题无法重现哦，你用2.0.11版本再试试看？

https://github.com/alibaba/fastjson2/issues/567#issuecomment-1209311852

**Comment by leshalv** [comment]
这个bug还有希望吗？

**Comment by dujie-js** [comment]
这个不应该复现不了呀,粘贴下来直接运行就是异常的情况

**Comment by leshalv** [comment]
@wenshao 在艾特一下温老板。

**Comment by dujie-js** [comment]
> @wenshao 在艾特一下温老板。

追加一张楼主提供case的运行截图,用的2.0.15版本
![image](https://user-images.githubusercontent.com/56857589/198976156-c9191a6d-79ce-4d00-9c75-0d1e9f9a8a32.png)

**Comment by leshalv** [comment]
@wenshao 在艾特一下温老板

**Comment by wenshao** [comment]
@leshalv  问题没重现，你能用最新版本2.0.47再验证下么？

**Comment by leshalv** [comment]
> @leshalv 问题没重现，你能用最新版本2.0.47再验证下么？

还是不可以，我用了2.0.48

**Comment by wenshao** [comment]
要手动加上 SupportAutoType
```java
Bean t = (Bean) JSON.parseObject(json, Bean.class, JSONReader.Feature.SupportAutoType);
```
看这个文档 https://github.com/alibaba/fastjson2/wiki/fastjson2_autotype_cn
