### ISSUE TITLE
[BUG] JavaBean无法序列化为JSON

### ISSUE THREAD

**Issue by moten-07** [alibaba/fastjson2#570]
### 问题描述
JavaBean无法转化为Json字符串

### 环境信息
 - OS信息： Ubuntu 22.04LTS  
 - JDK信息： corretto-11.0.15
 - 版本信息：fastjson2:2.0.9.android
 

### 重现步骤
*如何操作可以重现该问题：*

1. 创建类U，属性a
```java
public class U {
	private Integer a;
	private Integer b;

	public U(Integer a, Integer b) {
		this.a = a;
		this.b = b;
	}

	@Override
	public String toString() {
		return "U{" +
				"a=" + a +
				", b=" + b +
				'}';
	}
}
```
2. 创建U对象 `U u = new U(180,1);`
3. 使用JSON.toJSONString将其转化为JSON字符串
4. 输出
5. 输出为空

### 期待的正确结果
输出字符串
{"a":180,"b":1}

### 相关日志输出
2022-07-19 20:48:36.462 15240-15240/com.cover.six E/TAG: U{a=180, b=1}
2022-07-19 20:48:36.462 15240-15240/com.cover.six E/TAG: {}
2022-07-19 20:48:36.462 15240-15240/com.cover.six E/TAG: {}

#### 附加信息

![微信图片_20220719210311](https://user-images.githubusercontent.com/58394845/179756747-43cff1d7-63c8-4fa3-98f8-2dcc3781ee7d.jpg)

**Comment by wenshao** [comment]
```java
U u = new U(180, 1);
assertEquals("{\"a\":180,\"b\":1}", JSON.toJSONString(u, JSONWriter.Feature.FieldBased));
```
缺省是基于public field和getter方法来序列化的，你可以显示指定JSONWriter.Feature.FieldBased达到你要的效果
