### ISSUE TITLE
[BUG]空值数组反序列化，内存溢出

### ISSUE THREAD

**Issue by NeverMorewhz** [alibaba/fastjson2#573]
### 问题描述
空值数组反序列化，内存溢出
<img width="612" alt="111" src="https://user-images.githubusercontent.com/11847788/180125957-6d9ebe35-d233-4ae7-93d7-233715cc0780.png">
fastjson版本为2.0.9

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.10-SNAPSHOT/
问题重现并修复，请帮忙用2.0.10-SNAPSHOT版本验证，2.0.10版本预计在周六发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
问题已修复，请用新版本
