### ISSUE TITLE
fastjson的扩展性 可定制性

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/fastjson2#58]
1.x 相对于jackson来讲，扩展性，可定制性没有jackson强，2.x这块是否有增强呢

**Comment by wenshao** [comment]
fastjson2的有完善的扩展机制，包括Module/Reader/ReaderCreator/Writer/WriterCreator/MixIn/Annotation等扩展机制。

代码实现已经有了，但文档还需要补充。
