### ISSUE TITLE
提升ParseTree的性能

### ISSUE THREAD

**Issue by wenshao** [alibaba/fastjson2#580]
提升在ParserTree场景，也就是JSON字符串Parse为JSONObject场景的性能。在fastjson 1.x中，使用SymbolTable避免重用的Key重复创建从而提升性能。

有用户测试，在这个场景下，fastjson 1.x有更好的性能：
https://juejin.cn/post/7115219049931341854?share_token=f89354b2-5966-4518-ad6a-260b79324771

需要引入类似fastjson 1.x SymbolTable的机制，避免常有Key字符串对象的创建提升性能。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/commit/296798f3ce4a044bad9caf244fed1454e04c8ce5

**Comment by ahgaoyong** [comment]
666

**Comment by wenshao** [comment]
最新性能数据看这里
https://github.com/alibaba/fastjson2/blob/main/docs/benchmark/benchmark_2.0.11_1.md
