### ISSUE TITLE
Package com.alibaba.fastjson2.codegen not found in module

### ISSUE THREAD

**Issue by FrogIf** [alibaba/fastjson2#581]
环境信息: java11, gradle7.5, IDEA2021.3.1, fastjson2-2.0.8.
现象: 
1. 用gradle打包成可执行jar没有问题, 可执行jar也可以正常执行;
2. 用idea断点调试启动报错, 报错信息: ```Caused by: java.lang.module.InvalidModuleDescriptorException: Package com.alibaba.fastjson2.codegen not found in module```

找了一下, 有这个:
![1658670028331](https://user-images.githubusercontent.com/28251986/180649699-86623531-c559-4485-bd88-c21c7f71595f.png)

应该怎样办呢? 谢谢!

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.11
问题已修复，请用新版本
