### ISSUE TITLE
[QUESTION] fastjson1迁移至2的用法问题

### ISSUE THREAD

**Issue by alon-sys** [alibaba/fastjson2#583]
SimplePropertyPreFilter
SerializeFilter
ExtraProcessor
请问上面这几个对应fastjson2的是哪些?

**Comment by wenshao** [comment]
SimplePropertyPreFilter和SerializeFilter现在是支持的，ExtraProcessor目前还不支持

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.15
请用新版本，升级文档看这里：https://github.com/alibaba/fastjson2/wiki/fastjson_1_upgrade_cn

**Comment by lifw555** [comment]
version: 2.0.44

error:
`The method toJSONString(Object, JSONWriter.Feature...) in the type JSONObject is not applicable for the arguments (List<Subject>, SimplePropertyPreFilter)`
