### ISSUE TITLE
[BUG]兼容版本 2.0.10 调用 JSON.parseArray(jsonData, clazz);出错 无法转换

### ISSUE THREAD

**Issue by afish177** [alibaba/fastjson2#584]
### 问题描述
*简要描述您碰到的问题。*
1.2.83 版本调用 JSON.parseArray(jsonData, clazz);无误
![image](https://user-images.githubusercontent.com/32056262/180693170-86e2ae8a-810b-423b-9ac8-aed36ab74be5.png)

2.0.10兼容版本 JSON.parseArray(jsonData, clazz); 出现 转换出对象 值config 为null
某类包含 config属性 转换对应属性  为空 (转换串 属性 有符号__config__ 可看图  标识下面jsonData 黑色粗体得key 是带了符号 )
![image](https://user-images.githubusercontent.com/32056262/180694280-ff717887-600f-487f-acf2-d7d44bf4f79a.png)
![image](https://user-images.githubusercontent.com/32056262/180694228-cee75517-c46e-4dd4-9b95-144adf9628bb.png)
![image](https://user-images.githubusercontent.com/32056262/180692808-1f1252ab-a97a-4c6a-8d0b-068a555ad868.png)
![image](https://user-images.githubusercontent.com/32056262/180692823-ed5dc12c-6cb0-4748-b716-5ba59695e009.png)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson 2.0.10- 1.x兼容版本]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 JSON.parseArray(jsonData, clazz);方法
2. 输入 jsonData  数据
3. 出现 对象属性 config 为null错误
```java
//可在此输入示例代码
```

jsonData :

[{
	"__config__": {
		"formId": 115,
		"visibility": ["pc", "app"],
		"pfKey": "select",
		"defaultValue": "",
		"dataType": "static",
		"dictionaryType": "",
		"dragDisabled": false,
		"label": "所属项目",
		"propsUrl": "",
		"showLabel": true,
		"required": false,
		"props": {
			"label": "fullName",
			"value": "id"
		},
		"renderKey": 1611127618069,
		"tableName": "test_subpackage",
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-select",
		"tag": "el-select",
		"span": 24
	},
	"__vModel__": "projectS",
	"disabled": false,
	"placeholder": "请选择",
	"__slot__": {
		"options": [{
			"fullName": "选项一",
			"id": "1"
		}, {
			"fullName": "选项二",
			"id": "2"
		}]
	}
}, {
	"__config__": {
		"formId": 101,
		"visibility": ["pc", "app"],
		"pfKey": "depSelect",
		"dragDisabled": false,
		"label": "所属部门",
		"showLabel": true,
		"required": false,
		"renderKey": 1606979361829,
		"tableName": "test_subpackage",
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-department",
		"changeTag": true,
		"tag": "dep-select",
		"regList": [],
		"span": 12
	},
	"__vModel__": "depNameA",
	"disabled": false,
	"placeholder": "请选择"
}, {
	"clearable": true,
	"__config__": {
		"formId": 116,
		"visibility": ["pc", "app"],
		"pfKey": "userSelect",
		"dragDisabled": false,
		"label": "填单人",
		"trigger": "click",
		"showLabel": true,
		"required": false,
		"tableName": "test_subpackage",
		"renderKey": 1652256065583,
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-user",
		"tag": "user-select",
		"regList": [],
		"span": 12
	},
	"multiple": false,
	"__vModel__": "applys",
	"disabled": false,
	"placeholder": "请选择",
	"on": {
		"change": "({ data, formData, setFormData, setShowOrHide, setRequired, setDisabled, request, getFieldOptions, setFieldOptions }) => {\n    // 在此编写代码\n    \n}"
	}
}, {
	"clearable": true,
	"prefix-icon": "",
	"show-password": false,
	"__config__": {
		"formId": 118,
		"visibility": ["pc", "app"],
		"pfKey": "comInput",
		"noShow": false,
		"dragDisabled": false,
		"label": "承包方",
		"trigger": "blur",
		"showLabel": true,
		"required": false,
		"tableName": "test_subpackage",
		"renderKey": 1652256104063,
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-input",
		"tag": "el-input",
		"regList": [],
		"span": 24
	},
	"readonly": false,
	"__vModel__": "contractor",
	"style": {
		"width": "100%"
	},
	"disabled": false,
	"placeholder": "请输入",
	"show-word-limit": false,
	"__slot__": {
		"prepend": "",
		"append": ""
	},
	"suffix-icon": "",
	"on": {
		"change": "({ data, formData, setFormData, setShowOrHide, setRequired, setDisabled, request, getFieldOptions, setFieldOptions }) => {\n    // 在此编写代码\n    \n}",
		"blur": "({ data, formData, setFormData, setShowOrHide, setRequired, setDisabled, request, getFieldOptions, setFieldOptions }) => {\n    // 在此编写代码\n    \n}"
	}

}]
2.0.10兼容版本 JSON.parseArray(jsonData, clazz); 出现 转换对象 值config 为null
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
JSON.parseArray(jsonData, clazz); 
希望能转换出 对应属性 的值
如图 类似1.2.83 不为空
序列正常 
![image](https://user-images.githubusercontent.com/32056262/180693161-85e83f22-6e46-4148-aa12-c9f4e67409bf.png)

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by afish177** [comment]
`[{
	"__config__": {
		"formId": 115,
		"visibility": ["pc", "app"],
		"jnpfKey": "select",
		"defaultValue": "",
		"dataType": "static",
		"dictionaryType": "",
		"dragDisabled": false,
		"label": "所属项目",
		"propsUrl": "",
		"showLabel": true,
		"required": false,
		"props": {
			"label": "fullName",
			"value": "id"
		},
		"renderKey": 1611127618069,
		"tableName": "test_subpackage",
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-select",
		"tag": "el-select",
		"span": 24
	},
	"__vModel__": "projectS",
	"disabled": false,
	"placeholder": "请选择",
	"__slot__": {
		"options": [{
			"fullName": "选项一",
			"id": "1"
		}, {
			"fullName": "选项二",
			"id": "2"
		}]
	}
}, {
	"__config__": {
		"formId": 101,
		"visibility": ["pc", "app"],
		"jnpfKey": "depSelect",
		"dragDisabled": false,
		"label": "所属部门",
		"showLabel": true,
		"required": false,
		"renderKey": 1606979361829,
		"tableName": "test_subpackage",
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-department",
		"changeTag": true,
		"tag": "dep-select",
		"regList": [],
		"span": 12
	},
	"__vModel__": "depNameA",
	"disabled": false,
	"placeholder": "请选择"
}, {
	"clearable": true,
	"__config__": {
		"formId": 116,
		"visibility": ["pc", "app"],
		"jnpfKey": "userSelect",
		"dragDisabled": false,
		"label": "填单人",
		"trigger": "click",
		"showLabel": true,
		"required": false,
		"tableName": "test_subpackage",
		"renderKey": 1652256065583,
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-user",
		"tag": "user-select",
		"regList": [],
		"span": 12
	},
	"multiple": false,
	"__vModel__": "applys",
	"disabled": false,
	"placeholder": "请选择",
	"on": {
		"change": "({ data, formData, setFormData, setShowOrHide, setRequired, setDisabled, request, getFieldOptions, setFieldOptions }) => {\n    // 在此编写代码\n    \n}"
	}
}, {
	"clearable": true,
	"prefix-icon": "",
	"show-password": false,
	"__config__": {
		"formId": 118,
		"visibility": ["pc", "app"],
		"jnpfKey": "comInput",
		"noShow": false,
		"dragDisabled": false,
		"label": "承包方",
		"trigger": "blur",
		"showLabel": true,
		"required": false,
		"tableName": "test_subpackage",
		"renderKey": 1652256104063,
		"layout": "colFormItem",
		"tagIcon": "icon-ym icon-ym-generator-input",
		"tag": "el-input",
		"regList": [],
		"span": 24
	},
	"readonly": false,
	"__vModel__": "contractor",
	"style": {
		"width": "100%"
	},
	"disabled": false,
	"placeholder": "请输入",
	"show-word-limit": false,
	"__slot__": {
		"prepend": "",
		"append": ""
	},
	"suffix-icon": "",
	"on": {
		"change": "({ data, formData, setFormData, setShowOrHide, setRequired, setDisabled, request, getFieldOptions, setFieldOptions }) => {\n    // 在此编写代码\n    \n}",
		"blur": "({ data, formData, setFormData, setShowOrHide, setRequired, setDisabled, request, getFieldOptions, setFieldOptions }) => {\n    // 在此编写代码\n    \n}"
	}

}]`

**Comment by wsxe9988** [comment]
对应的实体类麻烦也提供下，谢谢

**Comment by afish177** [comment]
> 对应的实体类麻烦也提供下，谢谢

@Data
public class FieLdsModel {
    private ConfigModel config;
    private SlotModel slot;
    private String placeholder;
    private Object style;
    private Boolean clearable;
    private String prefixicon;
    private Integer precision;
    private String suffixicon;
    private String maxlength;
    private Boolean showWordLimit;
    private Boolean readonly;
    private Boolean disabled;
  
    private String vModel="";
    
    private String modelId="";
   
    private String relationField;
    private Boolean hasPage;
    private String pageSize;
    private String type;
    private Object autosize;
    private Integer step;
    private Boolean stepstrictly;
    private String controlsposition;
    private Object textStyle;
    private Integer lineHeight;
    private Integer fontSize;
    private Boolean showChinese;
    private Boolean showPassword;

   
    private String size;
    private Boolean filterable;
    
    private String showField;
}

@Data
public class ConfigModel {
    private String label;
    private String labelWidth;
    private Boolean showLabel;
    private Boolean changeTag;
    private Boolean border;
    private String tag;
    private String tagIcon;
    private boolean required = false;
    private String layout;
    private String dataType;
    private Integer span = 24;
    private String pfKey;
    private String dictionaryType;
    private Integer formId;
    private Long renderKey;
    private Integer columnWidth;
    private List<RegListModel> regList;
    private Object defaultValue;
    private String active;
    
    private String options;
   
    private String valueType;
    private String propsUrl;
    private String optionType;
    private ConfigPropsModel props;
   
    private Boolean showTitle;
    private String tableName;
    private List<FieLdsModel> children;

   
    private String visibility="[\"app\",\"pc\"]" ;

    
    private String rule;

    
    private String trigger="blur";
   
    private Boolean noShow=false;
   
    private int childNum;
    private String model;

   
    private boolean app = true;
    private boolean pc = true;
}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.14-SNAPSHOT/
问题已修复，请用2.0.14-SNAPSHOT版本帮忙验证，2.0.14版本预计在9月17日前发布

**Comment by afish177** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.14-SNAPSHOT/ 问题已修复，请用2.0.14-SNAPSHOT版本帮忙验证，2.0.14版本预计在9月17日前发布



你好 温大佬,我用得是 1.x得兼容版本 能否发包一个 快照版本

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.14
问题已修复，请用新版本

**Comment by afish177** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.14 问题已修复，请用新版本

还是 不行 测试还是为null

**Comment by afish177** [comment]
![image](https://user-images.githubusercontent.com/32056262/190835799-531dfe83-31b0-4eb2-8827-017236222988.png)
![image](https://user-images.githubusercontent.com/32056262/190835851-58e800ed-0ba1-48f4-a038-a9b99e7453fd.png)
