### ISSUE TITLE
[FEATURE] ObjectWriterBaseModule 类是否可以定义为public

### ISSUE THREAD

**Issue by jovezhao** [alibaba/fastjson2#585]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*

ObjectWriterBaseModule 类定义为public，当我需要注册一个新的ObjectWriterModule时可以从ObjectWriterBaseModule继承以获得大量以存在的功能。

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
问题已修复，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本
