### ISSUE TITLE
[BUG] 反序列化带Long泛型的Set时异常

### ISSUE THREAD

**Issue by weixuehu** [alibaba/fastjson2#586]
### 问题描述
反序列化带Long泛型的Set时异常，把泛型去掉就没有问题

序列化数据如下：
{
"@type":"xx.xx.AdminUserVO",
"resourceIds":Set[1L,100L,1000L,1001L,1002L,1003L,1004L,1005L,1006L]
}

实体：
public class AdminUserVO implements Serializable {
    private static final long serialVersionUID = -2346129123795338367L;
    private Set< Long > resourceIds;
}

Set < Long >反序列异常
Set 反序列正常

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.10
这个问题修复过，请用2.0.10验证下问题是否还存在

**Comment by weixuehu** [comment]
验证过了2.0.10没有问题，谢谢
