### ISSUE TITLE
[BUG] toJSONString() 时似乎会忽略 Boolean 类型的属性

### ISSUE THREAD

**Issue by TigerBeanst** [alibaba/fastjson2#587]
### 问题描述
toJSONString() 时似乎会忽略 Boolean 类型的属性

### 环境信息
*请填写以下信息：*

 - OS信息：  Android 12
 - JDK信息： Android Default JDK: 11.0.13
 - 版本信息：fastjson2-kotlin:2.0.10.android
 

### 重现步骤
```kotlin
	@Test
    fun testToJSONString(){
        data class BackupMMKV(val mmkvKey: String, val mmkvValue: Boolean)
        val mmkvList = mutableListOf<BackupMMKV>()
        mmkvList.add(BackupMMKV("test1",true))
        mmkvList.add(BackupMMKV("test2",false))
        val json = mmkvList.toJSONString()
        println(json)
    }
```

### 期待的正确结果
```json
[{"mmkvKey":"test1","mmkvValue":true},{"mmkvKey":"test2","mmkvValue":false}]
```

### 实际输出
```json
[{"mmkvKey":"test1"},{"mmkvKey":"test2"}]
```

### 额外
将 mmkvValue 修改为 `Int` 类型的话，是可以正常包含在输出的 Json 里的

**Comment by TigerBeanst** [comment]
似乎会因为未知原因吞掉 mmkvValue 这个字段名，我顺手改成 isSuccess 后能输出了……不过是 `success`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.11
问题已修复，请用新版本
