### ISSUE TITLE
[BUG]json字符串里面值是null时转换会报错。

### ISSUE THREAD

**Issue by leblancvn** [alibaba/fastjson2#596]
public class WinningInformationBo {
    private boolean isSuccess;
    private String wxId;
    private Map<String, String> parems;
}

String str3 = "{\"wx_id\":\"xxx\",\"success\":true,\"parems\":null}";
WinningInformationBo bo = JSON.parseObject(str3, WinningInformationBo.class);
此时会报错抛出异常。
使用fastjson 2.0.9兼容版本和fastjson2 2.0.9都会报错。
期望值是null时不用赋值

**Comment by wsxe9988** [comment]
复测过，升级到fastjson 2.0.10兼容版本和fastjson2 2.0.10 不会抛出异常。
json字符串里面params属性的值是null
转换后的bo的params还是null，没有赋值

**Comment by leblancvn** [comment]
好的，感谢

**Comment by leblancvn** [comment]
> 复测过，升级到fastjson 2.0.10兼容版本和fastjson2 2.0.10 不会抛出异常。 json字符串里面params属性的值是null 转换后的bo的params还是null，没有赋值

使用了2.0.10版本是当使用了lombok的@Accessors(chain = true)注解的时候依然会报错.
@Setter
@Getter
@Accessors(chain = true)
public class WinningInformationBo{
    private boolean isSuccess;
    private String wxId;
    private Map<String, String> parems;
}

编译后的类为:
public class WinningInformationBo{
    private boolean isSuccess;
    private String wxId;
    private Map<String, String> parems;

    public TestVO() {
    }

    public TestVO setSuccess(final boolean isSuccess) {
        this.isSuccess = isSuccess;
        return this;
    }

    public TestVO setWxId(final String wxId) {
        this.wxId = wxId;
        return this;
    }

    public TestVO setParems(final Map<String, String> parems) {
        this.parems = parems;
        return this;
    }

    public boolean isSuccess() {
        return this.isSuccess;
    }

    public String getWxId() {
        return this.wxId;
    }

    public Map<String, String> getParems() {
        return this.parems;
    }
}

**Comment by wenshao** [comment]
问题没有重现

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本
