### ISSUE TITLE
用阿里编程规约扫描了，值得调整的地方还是很多

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/fastjson2#60]
![image](https://user-images.githubusercontent.com/5828057/164882595-8e32091e-b077-4a2f-8bd4-89bf8290b1ec.png)
在想想怎么参与进来

**Comment by wenshao** [comment]
Blocker部分的应该修改，你可以参与进来提PR么？

**Comment by wsxe9988** [comment]
可以

**Comment by wsxe9988** [comment]
已提交pr #61

**Comment by wenshao** [comment]
已经合入，欢迎进一步参与

**Comment by wsxe9988** [comment]
嗯呢，没问题，从简单的开始，我一点点修改提交

**Comment by wsxe9988** [comment]
![image](https://user-images.githubusercontent.com/5828057/164894402-6f952e9d-2a2f-4902-9d13-d91cb34c4faa.png)

**Comment by wenshao** [comment]
不应该

**Comment by wsxe9988** [comment]
嗯好的，那这块先不动了。我也是没看明白这块
