### ISSUE TITLE
[兼容性]只支持Android 8.0+系统（API 26+），是否太高了

### ISSUE THREAD

**Issue by tzSharing** [alibaba/fastjson2#600]
这最低API level定的是否太高了，导致我只能被迫将minSdk 从20提升到26，直接影响到APP覆盖率。

**Comment by wenshao** [comment]
低版本不支持java.time，支持起来很困难

**Comment by ChunsFox** [comment]
最低sdk22 用2.0.10.android 就行

**Comment by kirin521** [comment]
通过Android的脱糖能支持低版本API吗？
https://developer.android.com/studio/write/java8-support-table?hl=zh-cn#java-time-customizations
