### ISSUE TITLE
[BUG] fastjson2 针对MutablePair序列化的结果多出字段

### ISSUE THREAD

**Issue by tangjwtj** [alibaba/fastjson2#608]
### 问题描述
针对apache common3的MutablePair类型，fastjson2会序列化出key、value序列化成字段，fastjson1不会.

针对以下对像做序列化：
System.out.println(JSON.toJSONString(new MutablePair<>("aaa","bbb")));

fastjson1 输出为：
{"aaa":"bbb"}

fastjson2输出为：
{"key":"aaa","left":"aaa","right":"bbb","value":"bbb"}

fastjson1的序列化结果是正确的。

注：已经使用最新的snapshot版本测试， 也是同样的输出 ，snapshot版本：fastjson2-2.0.11-20220803.041711-15

### 环境信息

 - 版本信息：[Fastjson2 2.0.10]

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.11
问题已修复，请用新版本
