### ISSUE TITLE
性能fastjson2还有很大的优化空间[BUG]

### ISSUE THREAD

**Issue by wycst** [alibaba/fastjson2#613]
参考数据： [https://github.com/wycst/wast-jmh-test](https://github.com/wycst/wast-jmh-test)
测试使用的wast版本是0.0.3（最新版本0.0.5）， fastjson2版本是2.0.6，评测的结果fastjson2完败，差距还很大（也许选的场景样本数据有针对性）
希望通过不断的超越和反超越一步一步接近极限。

**Comment by wyyl1** [comment]
在这里居然发现了大佬的微信！
