### ISSUE TITLE
[BUG]2.0.10版本无法序列化oracle的CLOB类型字段

### ISSUE THREAD

**Issue by freeman66** [alibaba/fastjson2#644]
### 问题描述
*升级2.0.10版本后，在用Map接收oracle数据库返回的CLOB字段数据时，调用序列化方法的时候报错：java.sql.SQLFeatureNotSupportedException: 不支持的特性: getDBAccessProperties，另外直接return给前端的时候报内存溢出错误，但亲测1.2.83版本能正常使用，其他版本未知*

### 环境信息
*请填写以下信息：*
 - JDK：1.8
 - springboot：2.3.0.RELEASE
 

### 重现步骤
*查询oracle数据库CLOB类型字段测试*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
问题已修复，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本

**Comment by freeman66** [comment]
> 

经实际验证，2.0.12版本已修复问题
