### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lovecxgood** [alibaba/fastjson2#650]
### 问题描述
JSON.isValid("null")  返回了 true 

### 期待的正确结果
JSON.isValid("null")  返回 false

**Comment by wenshao** [comment]
你应该调用：
JSON.isValidObject

**Comment by Lovecxgood** [comment]
> JSON.isValidObject

没有这个方法  2.0.11
只有 JSON.isValidArray  和 JSON.isValid这两个方法   
如果分array和object  那isValid 是不是同时验证这两种才对呢

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
新版本发布，已经支持JSON. isValidObject
