### ISSUE TITLE
Jsonb 与 CBOR 在功能上有何区别？

### ISSUE THREAD

**Issue by chenakam** [alibaba/fastjson2#67]
Jsonb 与 CBOR 在功能上有何区别？不是多此一举吗？

**Comment by wenshao** [comment]
FASTJSON2的JSONB在性能和大小上有很明显的优势，和CBOR的比较数据我还没做，后续我会补上，你自己也可以做一个测试

**Comment by wenshao** [comment]
从https://github.com/eishay/jvm-serializers/wiki 这里提供的数据看，cbor在大小和性能都不出色
