### ISSUE TITLE
[BUG] Boolean field lost after JSON.toJSONString()

### ISSUE THREAD

**Issue by HugoChoi-AI** [alibaba/fastjson2#673]
### 问题描述
*简要描述您碰到的问题。*
Boolean 字段，没get方法，有isXXX方法
转换JSONString后字段丢失

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

![image](https://user-images.githubusercontent.com/39721848/184085051-d136532d-c598-4f19-9b2c-9baad3b52609.png)

**Comment by HugoChoi-AI** [comment]
![isStatus-new](https://user-images.githubusercontent.com/39721848/184088868-7c1e7198-afec-44a0-97b1-bfa5facf1fb5.jpg)

没权限commit，我尝试这样改动，it works

**Comment by HugoChoi-AI** [comment]
![image](https://user-images.githubusercontent.com/39721848/184092804-a40d4a7e-9302-44d3-9684-77dee803756c.png)
can not commit

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
