### ISSUE TITLE
Could not initialize class com.alibaba.fastjson2.JSONFactory

### ISSUE THREAD

**Issue by subenkun** [alibaba/fastjson2#677]
### 问题描述
版本2.0.10升级2.0.11后报错
![1660273823023](https://user-images.githubusercontent.com/902220/184277956-edb182f4-e5db-4cd5-b516-b87e1bf333c4.jpg)

### 环境信息
 - OS信息：  windows 10
 - JDK信息：jdk 1.8.0_271
 - 版本信息：2.0.11
 

### 重现步骤
{"record":{"rowid":"374","Userid":"1234","name":"test","sex":"男","phone":"","CertID":"","dptmntName":"默认","time":"2022-08-12 11:11:21","UnlockMode":"face","image":"xxxx"},"DevCode":"xxxxxxxxx","cmd":"SendRec"}

public class MqttReceiveMessageBody {

    private String cmd;

    @JSONField(name = "DevCode")
    private String devCode;

    private String record;

}

JSONObject.parseObject(payload, MqttReceiveMessageBody.class)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
问题已修复，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本
