### ISSUE TITLE
[FEATURE]是否考虑提供汉字转unicode编码的序列化配置？

### ISSUE THREAD

**Issue by fanyawei** [alibaba/fastjson2#678]
### 请描述您的需求或者改进建议
虽然这几年的浏览器,不需要再将汉字转为unicode编码，但是，在对接其他的语言或其他接口的是候，还是会有这样的需求，建议提供一个序列化的Feature配置，可将汉字转unicode编码

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
```java
String STR = "中国";
String JSON_STR = "\"\\u4e2d\\u56fd\"";
String json = JSON.toJSONString(STR, JSONWriter.Feature.EscapeNoneAscii);
assertEquals(JSON_STR, json);
assertEquals(STR, JSON.parse(json));
```
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
已经支持，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
问题已修复，请用新版本
