### ISSUE TITLE
com.alibaba.fastjson.support.spring  这个包好像没有了

### ISSUE THREAD

**Issue by bnuboy** [alibaba/fastjson2#69]
从fastjson1.2升级到fastjson2时，基本上没有bug，就是com.alibaba.fastjson.support.spring  这个包好像没有了

**Comment by VictorZeng** [comment]
2.0.2 version  will be released soon.

**Comment by wenshao** [comment]
预计5月3日前会发布2.0.2版本，会带上com.alibaba.fastjson.support.spring 这个包
