### ISSUE TITLE
[BUG]fastjson1-compatible class cannot be converted to same class

### ISSUE THREAD

**Issue by icetimidus** [alibaba/fastjson2#699]
### fastjson1-compatible class cannot be converted to same class. 
当JSONArray内部元素类型与转换的目标类型相同时，toJavaList()会转换失败抛出异常。

### 环境信息

 - OS信息：   Windows [版本 10.0.19044.1889]
 - JDK信息： Oracle JDK 1.8.0_291
 - 版本信息：Fastjson2 2.0.11
 

### 重现步骤
```java
JSONArray array = JSON.parseArray("[\"a\",\"b\",\"c\"]");
List<String> list = array.toJavaList(String.class);
```

### 期待的正确结果
正常转换不报错。

### 相关日志输出
```
Exception in thread "main" com.alibaba.fastjson2.JSONException: class java.lang.String cannot be converted to class java.lang.String
	at com.alibaba.fastjson.JSONArray.toJavaList(JSONArray.java:817)
	at TestFastJson.main(TestFastJson.java:26)
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.12-SNAPSHOT/
问题已修复，请帮忙用2.0.12-SNAPSHOT版本验证，2.0.12版本预计在8月21日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.12
请用新版本
