### ISSUE TITLE
How is FastJson2 integrated in Springboot?

### ISSUE THREAD

**Issue by Yu-Xiao-Sheng** [alibaba/fastjson2#7]
In the FastJson1.X version, I added FastJson to the SpringIOC container by configuring the following beans.

```java
@Bean
public HttpMessageConverters fadtJsonHttpMessageConverters(){
    FastJsonHttpMessageConverter fastJsonHttpMessageConverter = new FastJsonHttpMessageConverter();
    FastJsonConfig fastJsonConfig = new FastJsonConfig();
    fastJsonConfig.setSerializerFeatures(SerializerFeature.PrettyFormat);
    fastJsonHttpMessageConverter.setFastJsonConfig(fastJsonConfig);
    HttpMessageConverter<?> converter = fastJsonHttpMessageConverter;
    return new HttpMessageConverters(converter);
}
```

But it seems to be no longer available in FastJson2. Is there any good way?

**Comment by VictorZeng** [comment]
@Yu-Xiao-Sheng Hi, fastjson2 does not support spring framework currently. You can submit a PR for this feature if you wish.

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
