### ISSUE TITLE
Does fastjson2 also support retrofit2?

### ISSUE THREAD

**Issue by Wang-Yumin** [alibaba/fastjson2#70]
I can't find RetrofitConverterFactory in fastjson2, Does fastjson2 also support retrofit2?

**Comment by VictorZeng** [comment]
`RetrofitConverterFactory `in 2.0.2 version, will be released soon.

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
