### ISSUE TITLE
jdk11,springboot 采用fastjson2序列化错误

### ISSUE THREAD

**Issue by yushuijiang** [alibaba/fastjson2#700]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alibaba.fastjson2.util.JDKUtils
WARNING: Please consider reporting this to the maintainers of com.alibaba.fastjson2.util.JDKUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
    使用redisTemplate取对象反序列化出错:
class com.alibaba.fastjson2.JSONObject cannot be cast to class com.cn.xxx (com.alibaba.fastjson2.JSONObject and com.cn.xxx are in unnamed module of loader 'app')

**Comment by wsxe9988** [comment]
能否提供完整的可复现该问题的最小case

**Comment by wsxe9988** [comment]
以及使用的版本号

**Comment by wenshao** [comment]
这个是WANING，不影响使用，可以忽略

**Comment by leogorden** [comment]
fastjson 版本2.0.20
jdk版本
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
