### ISSUE TITLE
[QUESTION]请问如何过滤is开头的方法，不做序列化

### ISSUE THREAD

**Issue by linhere20** [alibaba/fastjson2#707]
用fastjson2序列化thrift对象，因为thrift类生成出来会有很多isSetXXX的方法，用来判断该属性是否设置了值。
![image](https://user-images.githubusercontent.com/12524609/186564135-e1554383-d89e-4b0a-8174-158b7a6db0b0.png)

有什么方法可以过滤掉isSetXXX的方法，不做序列化吗？谢谢

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by linhere20** [comment]
大佬牛逼！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
