### ISSUE TITLE
JSONPath.arrayAdd方法，当path不存在时不自动创建 [BUG]

### ISSUE THREAD

**Issue by wangzhe56888** [alibaba/fastjson2#708]
### 问题描述
*1. 例：JSONPath.of("$.user.score").arrayAdd(root, 100, 80)，当 path 不存在时不自动创建和赋值*
*2. 对数组指定下标赋值时期望不要抛异常，而是用null来补全下标之前的元素*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.12]
 

### 重现步骤

1. 使用 `JSONPath.arrayAdd` 方法
2. 未正确添加元素

```java
JSONObject root = new JSONObject();
//JSONPath.of("$.user.name").set(root, "demo-name");

// JSONPath.of("$.user.score").set(root, new LinkedList<>());
JSONPath.of("$.user.score").arrayAdd(root, 100d, 80.05d);
```

### 期待的正确结果
*在执行完 JSONPath.of("$.user.score").arrayAdd(root, 100d, 80.05d); 后，即使 $.user.score 不存在也期望能正确创建数组并添加元素。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
