### ISSUE TITLE
 parseArray(String text, Class<T> type)当解析的字符串最后多一个逗号会导致异常[BUG]

### ISSUE THREAD

**Issue by bobtang** [alibaba/fastjson2#709]
### 问题描述
*JSONArray.parseArray当解析的字符串最后多一个逗号会导致数据一直插入0直到内存崩溃*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.12]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 parseArray(String text, Class<T> type)
2. 输入[1,], Integer.class  
3. 出现 java.lang.OutOfMemoryError: Java heap space 错误
```java
String str = "[1,]";
List<Integer> list = JSONArray.parseArray(str, Integer.class);
```

### 期待的正确结果
*执行完上述代码得到list有1一个数值*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证

**Comment by zhrgithub** [comment]
我草 你是中毒了吗 怎么一直发
