### ISSUE TITLE
[FEATURE] 能不能输出属性不要按字母排序 按javabean代码属性顺序

### ISSUE THREAD

**Issue by javahui** [alibaba/fastjson2#713]
能不能输出属性不要按字母排序按 javabean属性顺序
```java
public class SystemUser {
	private Integer id;
	private String code;
	private String password;
}
```
输出{ "id": 1 , code: "10001", password:"123456"  }  效果这样

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
请用2.0.13-SNAPSHOT版本验证，2.0.13版本预计在9月12日前发布。需要配置JSONType.alphabetic = true，比如
```java
@JSONType(alphabetic=false)
public class SystemUser {
	private Integer id;
	private String code;
	private String password;
}
```
这个取决于编译器的行为，顺序不确定的

**Comment by javahui** [comment]
> [https://os.sonatype.org/jsoncontent/repositories/snapshots/com/alib/fastjson2/fastaba/2.0.13-SNAPSHOT/](https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/) 用2.0.13-SNAPSHOT版本，验证2.0.13版本请在9月12日前发布发布。需要配置JSONType.alphabetic = true，比如
> 
> ```java
> @JSONType(alphabetic=false)
> public class SystemUser {
> 	private Integer id;
> 	private String code;
> 	private String password;
> }
> ```
> 
> 什么是这个编译器的行为，目的是

我是过滤中得到Bean,有可能是各种形式的bean, 我不可在所有bean上加@JSONType, 能不能加个SerializerFeature参数

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
