### ISSUE TITLE
[FEATURE]JSONReader.Feature全局配置功能

### ISSUE THREAD

**Issue by slqx** [alibaba/fastjson2#714]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*

历史问题，前端返回的 jsonArray 格式为 首字母大写，后端对象定义为首字母小写（驼峰）， 在1.x的版本中，默认正常反序列化，在2.x版本中需要设置 JSONReader.Feature.SupportSmartMatch，改动地方过多，希望能够有可全局配置生效的方式。

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

增加项目全局 JSONReader.Feature 设置

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

目前为所有用到的地方全部检查是否增加 JSONReader.Feature

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
```java
JSON.config(JSONReader.Feature.SupportSmartMatch);
```
可以通过上面的代码实现全局配置

**Comment by hks2002** [comment]
启动程序下，进行设定，比如设定日期格式
```
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.alibaba.fastjson2.JSON;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        JSON.configWriterDateFormat("yyyy-MM-dd");
        SpringApplication.run(Application.class, args);
    }
}
```
当然还可以JSON添加各种Features
