### ISSUE TITLE
[Android环境下，JSONB解析报错，com.alibaba.fastjson2.JSONException: set address error, offset 17]

### ISSUE THREAD

**Issue by Fish-Bin** [alibaba/fastjson2#715]
### 问题描述
*JSONB.parseObject(bytes, Student.class)报错*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [1.8]
 - 版本信息：[implementation 'com.alibaba.fastjson2:fastjson2:2.0.12.android']
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSONB.parseObject(bytes, Student.class)` 方法
2. 输入 `    Student student = new Student("bin",12,"湖北");
        byte[] bytes = JSONB.toBytes(student);
        Student student2 = JSONB.parseObject(bytes, Student.class);
        L.INSTANCE.i("Bin", student2.toString());`  数据
3. 出现 `com.alibaba.fastjson2.JSONException: set address error, offset 17` 错误
```java
       Student student = new Student("bin",12,"湖北");
        byte[] bytes = JSONB.toBytes(student);
        Student student2 = JSONB.parseObject(bytes, Student.class);
        L.INSTANCE.i("Bin", student2.toString());

public class Student {
    private String name;
    private int sge;
    private String address;

    public Student(String name, int sge, String address) {
        this.name = name;
        this.sge = sge;
        this.address = address;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getSge() {
        return sge;
    }

    public void setSge(int sge) {
        this.sge = sge;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "Student{" +
                "name='" + name + '\'' +
                ", sge=" + sge +
                ", address='" + address + '\'' +
                '}';
    }

```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*com.alibaba.fastjson2.JSONException: set address error, offset 17
        at com.alibaba.fastjson2.reader.FieldReaderStringMethod.readFieldValue(FieldReaderStringMethod.java:34)
        at com.alibaba.fastjson2.reader.ObjectReader3.readJSONBObject(ObjectReader3.java:176)
        at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:328)
        at com.bin.jsonb.TestActivity.test1(TestActivity.java:45)
        at com.bin.jsonb.TestActivity.access$000(TestActivity.java:16)
        at com.bin.jsonb.TestActivity$1.onClick(TestActivity.java:25)
        at android.view.View.performClick(View.java:7317)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View.performClickInternal(View.java:7291)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28247)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)*

#### 附加信息
*很好的一个库，最近想用它来优化项目存储，但是感觉对安卓支持力度很小，JSONB的一些基本功能都不能正常跑通*

**Comment by wenshao** [comment]
是Student类没有缺省构造函数，你可以这样试试看
```java
Student student = new Student("bin",12,"湖北");
byte[] bytes = JSONB.toBytes(student, JSONWriter.Feature.FieldBased);
Student student2 = JSONB.parseObject(bytes, Student.class, JSONReader.Feature.FieldBased);
```

**Comment by Fish-Bin** [comment]
加上无参构造方法，或者加上JSONWriter.Feature.FieldBased确实可以，但是将Student对象转成kotlin就还是会报错
![image](https://user-images.githubusercontent.com/22335406/187409325-7e640045-2c0c-4934-939b-935ddce86900.png)

**Comment by Fish-Bin** [comment]
这个是kotlin对象
![image](https://user-images.githubusercontent.com/22335406/187419007-06e5e471-c9eb-4d43-a80a-c00efaeeafaf.png)

**Comment by wenshao** [comment]
```java
package com.alibaba.fastjson2.issues

import com.alibaba.fastjson2.JSONB
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Issue715K {
    @Test
    fun test() {
        val student = Student("bin", 12, "湖北")
        var jsonbBytes = JSONB.toBytes(student);
        var student2 = JSONB.parseObject(jsonbBytes, Student::class.java);
        assertEquals(student.name, student2.name);
        assertEquals(student.sge, student2.sge);
        assertEquals(student.address, student2.address);
    }
}

class Student {
    var name: String = ""
    var sge: Int = 0
    var address: String = ""

    constructor(
        name: String,
        sge: Int,
        address: String
    ) {
        this.name = name
        this.sge = sge
        this.address = address
    }

    constructor() {
    }
}
```
没问题啊

**Comment by Fish-Bin** [comment]
1. 不引入implementation 'org.jetbrains.kotlin:kotlin-reflect:1.7.10'会报
![image](https://user-images.githubusercontent.com/22335406/187849821-036e2edf-43c0-4cd7-99a6-d5d240c0e185.png)
2. 引入implementation 'org.jetbrains.kotlin:kotlin-reflect:1.7.10'的话编译会报：
![image](https://user-images.githubusercontent.com/22335406/187850010-8e959735-3dc2-428d-a44f-cc317088240b.png)
是我kotlin版本低了吗？我当前版本是 ext.kotlin_version = "1.4.32"，已经是比较新的了

**Comment by wenshao** [comment]
引入implementation 'org.jetbrains.kotlin:kotlin-reflect:1.4.32'试试看

**Comment by Fish-Bin** [comment]
1. 引入implementation 'org.jetbrains.kotlin:kotlin-reflect:1.4.32'可以了
2. @JSONField(name = "n") 会导致 JSONB.parseObject(bytes, JNote::class.java) 报错
   
![image](https://user-images.githubusercontent.com/22335406/188054932-2fed2994-37a4-4642-a542-6977c789e4c8.png)

3. @JSONField( serialize= false) 也会导致 JSONB.parseObject(bytes, JNote::class.java) 报错
![image](https://user-images.githubusercontent.com/22335406/188055138-28cc26ae-1824-47e5-99fb-c33d32b50996.png)

对象信息：
![image](https://user-images.githubusercontent.com/22335406/188056418-ae7e65e9-e6c5-46ca-8b12-c45e19ffb69d.png)

**Comment by Fish-Bin** [comment]
类似的还有@JSONField(serializeFeatures = [JSONWriter.Feature.NotWriteDefaultValue])
                   @JSONField(format = "yyyy-MM-dd HH:mm:ss")
                    @JSONField(serializeUsing = TypeSerializer::class)
                    @JSONType(ignores = ["noteId","firstPageId"])
                    @JSONType(serializeFeatures = [JSONWriter.Feature.NotWriteDefaultValue])
这些注解不生效的问题,麻烦排查下

**Comment by wenshao** [comment]
@Fish-Bin 发文本，按照图再输入一遍很烦人

**Comment by Fish-Bin** [comment]
data class Note(
    var noteId: String = "",

    var name: String? = "",
    var firstPageID: String = "",

    var type: Int = 1,//1为普通笔记,2为贺卡,3为pdf笔记,4为文件夹

    var maxPageNumber: Int = 9999,

    var deleteFlag: Int = 0, // -1 -- 垃圾箱，0 -- 为可用，-2 -- 为要删除但还没删完的, -3 -- 为要导入但没有导入完

    var userid: String = "",

    var backgroundUrl: String = "",//全局背景图

    var paperParamConfig: String = "",

    var lastPageIndex: Int = 0,//最后打开页

    var parentId: String = "",//父类文件夹id

    var isImpOutline: Int = 0,//是否导入过PDF大纲与page大纲到大纲表。0没有导入过；1已导入过；新建普通笔记，导入PDF时设置为1。

    var paperWidth: Float = 1024f,

    var paperHeight: Float = 1750f,

    var modify: Boolean = false,
    var needDown: Boolean = false,
    var isClouding: Boolean = false,
    var cloudId: String = "",
    var progress: Int = 0,
    var maxProgress: Int = 0,
    var fileSize: Int = 0,
    var firstBackgroundUrl: String = "",//封面
    var scaleGlobal: String = "",
) {
    override fun toString(): String {
        return "Note(noteId='$noteId', name='$name', firstPageID='$firstPageID', type=$type, maxPageNumber=$maxPageNumber, deleteFlag=$deleteFlag, userid='$userid', backgroundUrl='$backgroundUrl', paperParamConfig='$paperParamConfig', lastPageIndex=$lastPageIndex, parentId='$parentId', isImpOutline=$isImpOutline, paperWidth=$paperWidth, paperHeight=$paperHeight, modify=$modify, needDown=$needDown, isClouding=$isClouding, cloudId='$cloudId', progress=$progress, maxProgress=$maxProgress, fileSize=$fileSize, firstBackgroundUrl='$firstBackgroundUrl', scaleGlobal='$scaleGlobal')"
    }
}

**Comment by Fish-Bin** [comment]
val note = Note(
            noteId = noteId,
            name = "无名",
            firstPageID = pageId,
            type = 1,
            maxPageNumber = 9999,
            userid = "77800484",
            backgroundUrl = "PageBg/White_Wide_Line_Paper",
            parentId = "",
            firstBackgroundUrl = "/Cover/natural2",
            paperParamConfig = "{\"defaultHorParts\":5.0,\"defaultVerParts\":5.0,\"horParts\":0.0,\"paperBg\":\"PageBg/White_Wide_Line_Paper\",\"verParts\":0.0}",
            lastPageIndex = 1,
            isImpOutline = 1,
            paperWidth = 1240f,
            paperHeight = 1750f,
            scaleGlobal = "bin"
        )

**Comment by wenshao** [comment]
主要是data class不允许为空，使用Feature.FieldBased就好了

**Comment by Fish-Bin** [comment]
> 主要是data class不允许为空，使用Feature.FieldBased就好了

好的，我验证下

**Comment by Fish-Bin** [comment]
在对象头上也要加上@JSONType(serializeFeatures = [JSONWriter.Feature.FieldBased])这个吧，不然也还是报错

**Comment by Fish-Bin** [comment]
加了Feature.FieldBased 后 @JSONType的大部分注解都生效了，除了JSONWriter.Feature.NotWriteDefaultValue不生效，但是会导致@JSONField的注解都不生效了
![image](https://user-images.githubusercontent.com/22335406/188086689-fa4a784c-33a3-44d3-9c30-29ef0593a81a.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
