### ISSUE TITLE
[FEATURE] 能不能加个接口：JSON.toJSONString(obj, objectWriterProvider, features)？

### ISSUE THREAD

**Issue by noear** [alibaba/fastjson2#719]
没有它的话，定制的 ObjectWriterProvider 实例不能快捷的使用

**Comment by wenshao** [comment]
parseObject有类似的方法，比如：
```java
interface JSON {
static <T> T parseObject(String text, Class<T> clazz, JSONReader.Context context);
}
```

使用是这样用：
```java
ObjectReaderProvider provider = ...;
JSON.parseObject(str, JSONObject.class, JSONFactory.createReadContext(provider));
```

你可以参考这个提交一个PR么？

**Comment by noear** [comment]
> 

可以：）

**Comment by noear** [comment]
pr#724 已提

**Comment by wenshao** [comment]
PR怎么关了？重新提一个吧？

**Comment by noear** [comment]
> PR怎么关了？重新提一个吧？

之前的经验是，提交新pr前，旧pr 得关掉。。。写单测，我得把项目编译通，要花时间：）

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证

**Comment by noear** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.13 2.0.13版本已经发布，请用帮忙用新版本验证

试了，OK
