### ISSUE TITLE
[BUG] 使用 @JSONType(writeEnumAsJavaBean = true) 序列化枚举，与期待结果不一致

### ISSUE THREAD

**Issue by caryyin** [alibaba/fastjson2#730]
### 问题描述
使用 `@JSONType(writeEnumAsJavaBean = true) ` 序列化枚举，与期待结果不一致

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win10]
 - JDK信息： [e.g.：jdk1.8.0_45]
 - 版本信息：[e.g.：Fastjson2 2.0.12]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 执行单元测试 `test_serializeEnumAsJavaBean()` 方法

```java
package com.alibaba.fastjson2.v1issues.issue_1400;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.annotation.JSONType;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class OrderTypeTest {

    @Test
    public void test_serializeEnumAsJavaBean() {
        String text = JSON.toJSONString(OrderType.PayOrder);
        assertEquals("{\"remark\":\"支付订单\",\"value\":1}", text);
    }

    @JSONType(writeEnumAsJavaBean = true)
    public enum OrderType {

        PayOrder(1, "支付订单"), //
        SettleBill(2, "结算单");

        public final int value;
        public final String remark;

        OrderType(int value, String remark) {
            this.value = value;
            this.remark = remark;
        }
    }
}
```

### 期待的正确结果
预期:{"remark":"支付订单","value":1}

### 实际结果
实际:"PayOrder"

![image](https://user-images.githubusercontent.com/9817765/188129162-7c8c8334-7310-4ad3-b0e2-4d41feed31b1.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本帮忙验证，2.0.13版本预计9月12日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证

**Comment by zhrgithub** [comment]
你狗日的 不想活啦


| |
Zhr
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年09月10日 15:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [alibaba/fastjson2] [BUG] 使用 @JSONType(writeEnumAsJavaBean = true) 序列化枚举，与期待结果不一致 (Issue #730) |

https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
