### ISSUE TITLE
[BUG]TypeReference复杂类型处理时好时坏

### ISSUE THREAD

**Issue by Lce-Lemon** [alibaba/fastjson2#731]
### 问题描述
*简要描述您碰到的问题。*
fastjson1.2.83升级fastjson2.0.12遇到如下问题
JSON.parseObject(str, new TypeReference<AjaxResult.PageResult<TagHistoryModel>>() {});
可以成功parse，但是类型解析时好时坏

### 环境信息
*请填写以下信息：*

 - OS信息：  win10
 - JDK信息： jdk1.8.0_291
 - 版本信息：Fastjson2.0.12
 

### 重现步骤
*如何操作可以重现该问题：*
将提供的方法放到任意一个可执行的地方，频繁执行几次，会发现此方法时好时坏

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
AjaxResult.PageResult<TagHistoryModel> result = new AjaxResult.PageResult<>();
result.setData(Lists.newArrayList(new TagHistoryModel().setTag(“COUNTER13_14”)));
result.setTotal(10L);
result.setPageNum(1);
result.setPageSize(10);
String s1 = JSON.toJSONString(result);
System.out.println(s1);
AjaxResult.PageResult<TagHistoryModel> parseResult = JSON.parseObject(s1, new TypeReference<AjaxResult.PageResult<TagHistoryModel>>() {
});
try {
List<TagHistoryModel> list1 = parseResult.getData();
list1.forEach(item -> {
System.out.println(item instanceof TagHistoryModel);
});
} catch (Exception e) {
log.error(e.getMessage());
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
期望可以修复此问题

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
{“data”:[{“tag”:”COUNTER13_14”}],”message”:”success”,”pageNum”:1,”pageSize”:10,”status”:0,”timestamp”:1662362256626,”total”:10}
2022-09-05 15:17:36|ERROR|Fastjson2Test(—) — com.alibaba.fastjson2.JSONObject cannot be cast to com.xxx.req.TagHistoryModel

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
把AjaxResult和TagHistoryModel这两个类的代码提供下

**Comment by Lce-Lemon** [comment]
> 把AjaxResult和TagHistoryModel这两个类的代码提供下

我将JSONReader.Feature指定了一下，然后好了

**Comment by Lce-Lemon** [comment]
指定JSONReader.Feature后无问题
