### ISSUE TITLE
[QUESTION]SerializerFeature.IgnoreNonFieldGetter缺少对应的JSONWrieter.Feature.IgnoreNonFieldGetter

### ISSUE THREAD

**Issue by kervin521** [alibaba/fastjson2#733]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本帮忙验证，2.0.13版本预计9月12日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证

**Comment by kervin521** [comment]
有问题，序列号打印不出来
