### ISSUE TITLE
[BUG]兼容包无法正常反序列化Map<Long, Long>

### ISSUE THREAD

**Issue by XAGU** [alibaba/fastjson2#737]
### 问题描述
*简要描述您碰到的问题。*
兼容包无法正常反序列化Map<Long, Long>

### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.12]
 

### 重现步骤
*如何操作可以重现该问题：*

兼容包JSONObject.parseObject()

new TypeReference<Map<Long, Long>>(){}  失败
new TypeReference<Map<String, Long>>(){}  成功
new TypeReference<HashMap<Long, Long>>(){}  成功

```java
        Map<Long, Long> map = new HashMap<>();
        map.put(11L, 111L);
        map.put(22L, 222L);
        String json = JSONObject.toJSONString(map);
        Map<Long, Long> parseObject = JSONObject.parseObject(json, new TypeReference<Map<Long, Long>>(){});
```

### 期待的正确结果
*使用兼容包正确反序列化*

### 相关日志输出
*Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at com.alibaba.fastjson.JSONObject.put(JSONObject.java:46)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:275)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:271)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:166)
	at com.sinitek.sirm.common.utils.Test.main(Test.java:45)*

**Comment by wenshao** [comment]
问题已修复，请用新版本
https://github.com/alibaba/fastjson2/releases/tag/2.0.14

**Comment by ai-smalleryu** [comment]
感觉问题还是存在，在flink使用时候，直接使用json转换为jsonobject，在处理后直接发出，这时候依然会报错Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.alibaba.fastjson2.JSONObject

**Comment by wenshao** [comment]
能提供重现问题的testcase么？
