### ISSUE TITLE
[BUG]使用JSONPath时，对数组内子对象进行过滤时无法正常返回，但使用jayway.jsonpath是正常的。

### ISSUE THREAD

**Issue by tousen2001** [alibaba/fastjson2#742]
### JSON String
`{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888",
      "address"  : {
            "streetAddress": "naist street1",
            "city"         : "Nara1",
            "postalCode"   : "630-0192"
          }
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910",
            "address"  : {
            "streetAddress": "naist street2",
            "city"         : "Nara2",
            "postalCode"   : "630-0192"
          }
    }
  ]
}`

### 过滤条件如下：
`$.phoneNumbers[?(@.address.city == 'Nara1')]`
 

### 错误日志
![image](https://user-images.githubusercontent.com/24559743/189022617-c7792d3f-750e-40b3-962a-ace6f519e08b.png)

### 在线验证是正常的（通过jayway.jsonpath也是可以正确过滤）
![image](https://user-images.githubusercontent.com/24559743/189022853-1a6cb0b9-b24e-4289-ae20-0f4768f8fe0f.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本帮忙验证，2.0.13版本预计9月12日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
