### ISSUE TITLE
[BUG] JSONB 序列化特定的JSON是报数组溢出错误

### ISSUE THREAD

**Issue by jimichan** [alibaba/fastjson2#744]
### 问题描述
JSONB 序列化特定的JSON是报数组溢出错误，测试JOSN文件在 
[test.json.zip](https://github.com/alibaba/fastjson2/files/9527755/test.json.zip)

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 17]
 - 版本信息：[e.g.：Fastjson2 2.0.12]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `JSONB.toBytes` 方法
2. 输入 `附件中的test.json`  数据
3. 出现  错误
```kotlin
    val json = File("test.json").readText()

    val map = JSON.parseObject(json)

    val bytes = JSONB.toBytes(map)
```

### 期待的正确结果
别爆出异常

### 相关日志输出

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 274141 out of bounds for byte[274140]
	at java.base/java.lang.System.arraycopy(Native Method)
	at com.alibaba.fastjson2.JSONWriterJSONB.writeString(JSONWriterJSONB.java:575)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.writeJSONB(ObjectWriterImplMap.java:257)
	at com.alibaba.fastjson2.JSONB.toBytes(JSONB.java:793)
	at TestKt.main(Test.kt:15)
	at TestKt.main(Test.kt)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

[test.json.zip](https://github.com/alibaba/fastjson2/files/9527755/test.json.zip)

**Comment by jimichan** [comment]
```java
               if (utf16) {
                    ensureCapacity(off + 5 + value.length);
                    // 猜测这里off++ 导致了后面的off+1，导致的错误嘛?
                    bytes[off++] = JDKUtils.BIG_ENDIAN ? BC_STR_UTF16BE : BC_STR_UTF16LE;
                    writeInt32(value.length);
                    System.arraycopy(value, 0, bytes, off, value.length);
                    off += value.length;
                    return;
                }
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
问题已经修复，请用2.0.13-SNAPSHOT版本帮忙验证，2.0.13版本预计9月12日发布

**Comment by jimichan** [comment]
测试了 fastjson2-2.0.13-20220907.220828-61.jar 
应该没有被修复

**Comment by wenshao** [comment]
我本地没重现，能提供下在新的错误堆栈信息么？

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证

**Comment by jimichan** [comment]
可以了👍
