### ISSUE TITLE
[FEATURE] readString 时候，如果有逗号，会将逗号给过滤掉

### ISSUE THREAD

**Issue by 562498146** [alibaba/fastjson2#747]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*
希望告诉调用者，readString中逗号。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.13-SNAPSHOT/
新增加了JSONReader#hasComma方法， 请用2.0.13-SNAPSHOT版本帮忙验证，2.0.13版本预计9月12日发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.13
2.0.13版本已经发布，请用帮忙用新版本验证
