### ISSUE TITLE
[BUG] ContextAutoTypeBeforeHandler 无法处理内部类

### ISSUE THREAD

**Issue by AlbumenJ** [alibaba/fastjson2#750]
### 问题描述
*简要描述您碰到的问题。*

- ContextAutoTypeBeforeHandler 无法处理内部类
 

### 重现步骤
*如何操作可以重现该问题：*

1. ContextAutoTypeBeforeHandler apply 检查类名的时候自动将 `$` 转成了 `.`

![image](https://user-images.githubusercontent.com/9292748/189537687-f047b50c-63fa-4809-b361-96fd44030661.png)

2. 但是 ContextAutoTypeBeforeHandler 构造器传入的 acceptNames 没有处理 `$` 到 `.` 的转换

![image](https://user-images.githubusercontent.com/9292748/189537713-6b01154e-195b-472f-a5a0-d6c2bfa4b2a8.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.14
问题已修复，请用新版本
