### ISSUE TITLE
[BUG] JSON末端包含非显示字符时解析错误

### ISSUE THREAD

**Issue by jayzch** [alibaba/fastjson2#757]
### 问题描述
com.alibaba.fastjson2.JSONException: input not end, offset 206, character , line 1, column 207, fastjson-version 2.0.13 {"visit_time":1662950912,"visit_user":{"userid":"51753998","username":"","usernick":"","usersex":"M"},"visit_oauth":{"access_token":"8d82afa4189cdd1a623b1a45412ca3f93e1a4373","token_expires":"1662999033"}}
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:184)

### 环境信息

Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T02:41:47+08:00)
Maven home: /usr/share/apache-maven-3.6.0
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /usr/java/jdk1.8.0_191-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.41.1.el7.x86_64", arch: "amd64", family: "unix"
 - 版本信息：Fastjson2 2.0.13

**Comment by jayzch** [comment]
上面的报错信息，均为原始内容未做修改。

而实际上原始内容中username和usernick为Unicode编码文本。以\u开通，感觉之前发生的Unicode编码无法解析的问题，又回来了。 @wenshao

**Comment by wenshao** [comment]
问题没有重现，比较奇怪了

**Comment by jayzch** [comment]
我知道原因了。当json字符串默认有些特殊控制符时，会出错

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.14-SNAPSHOT/
trim影响性能，可以用2.0.14-SNAPSHOT版本验证下

**Comment by jayzch** [comment]
测试通过

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.14
问题已修复，请用新版本
