### ISSUE TITLE
基于kotlin 原生特性的支持 这个有计划吗？？

### ISSUE THREAD

**Issue by ming0804** [alibaba/fastjson2#76]
现在kotlin在实际的应用中还是很常见的 ，但是他的反序列化各个json库支持的都不是很好 ，这个方面有计划吗？？？

**Comment by wenshao** [comment]
要做的，但是目前还没有做详细的测试和匹配

**Comment by ming0804** [comment]
嗯嗯 期待

**Comment by TechAilurus** [comment]
我也表示期待，Kotlin在服务端的生态越来越多了，甚至有的库都是Kotlin写的（OKIO，OKHTTP甚至专门重写了一遍）希望这个库也至少提供类似Rxjava，Spring的拓展支持。

**Comment by tanranran** [comment]
+1

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases
已经支持，请用最新2.0.3

Kotlin原生支持需要加上下面依赖：
```xml
<groupId>com.alibaba.fastjson2</groupId>
<artifactId>fastjson2-kotlin</artifactId>
<version>2.0.3</version>
```
