### ISSUE TITLE
[BUG]java.util.Date 序列化异常

### ISSUE THREAD

**Issue by jayzch** [alibaba/fastjson2#762]
### 问题描述
同一个类中，
一个字段类型java.util.Date，该字段未加任何注解
在不同的情况下，序列化后得到的字符串会不一样。

```java

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONObject;

    public void onMessage(TalkRecord talkRecord) {
            TalkRecord talkRecord1 = new TalkRecord();
            talkRecord1.setUpdateTime(new Date());
        System.out.println(talkRecord1.getUpdateTime());
        System.out.println(JSON.toJSONString(talkRecord1));
        System.out.println(JSON.toJSONString(talkRecord));
        System.out.println(talkRecord.getTalkTime());
    }
```

> Tue Sep 13 14:16:09 CST 2022

> {"updateTime":"2022-09-13T14:16:09.877+08:00"}

> {"createTime":"2022-09-13 12:19:28","talkTime":"2022-09-13 12:19:28","updateTime":"2022-09-13 12:19:28"}

> Tue Sep 13 12:19:28 CST 2022

> 

另外想问下，如何指定输出为时间戳？

 
### 环境信息

 - OS信息：Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /usr/java/jdk1.8.0_191-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.36.2.el7.x86_64", arch: "amd64", family: "unix"
 - JDK信息：java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
 - 版本信息： Fastjson2 2.0.13

**Comment by wenshao** [comment]
```java
JSON.toJSONString(new Date(), "millis");
```
这样可以输出时间戳

**Comment by jayzch** [comment]
那么奇怪 的是，

**Comment by jayzch** [comment]
通过IDEA调试后，发现同一个class，不同的是实例，序列化后打印出来，的确就是不一样。断点调试无法定位到具体代码。似乎由于是在接口中实现方法，调试时，一直卡在
`objectWriter.write(writer, object, null, null, 0);`

**Comment by wenshao** [comment]
TalkRecord 这类的代码发一下

**Comment by wenshao** [comment]
主要是有的有毫秒数，有的没有

**Comment by jayzch** [comment]
`
import java.util.Date;

public class TalkRecord implements Serializable {
    private static final long serialVersionUID = 1L;
    private Date talkTime;
    private Date createTime;
    private Date updateTime;
     public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
      public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
 public Date getTalkTime() {
        return talkTime;
    }

    public void setTalkTime(Date talkTime) {
        this.talkTime = talkTime;
    }

}
`

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.14
问题已修复，请用新版本
