### ISSUE TITLE
从fastjson升级到fastjson2之后，自定义的ObjectSerializer 该如何迁移到fastjson2？

### ISSUE THREAD

**Issue by myaniu** [alibaba/fastjson2#77]
温少，您好，问一下，从fastjson升级到fastjson2之后，自定义的ObjectSerializer 该如何迁移到fastjson2。我看可以实现ObjectReader/ObjectWriter，自己实现之后，改如何注册这个Writer/Reader呢？

**Comment by myaniu** [comment]
好的，谢谢温少。

**Comment by wenshao** [comment]
参考这个文档
https://github.com/alibaba/fastjson2/wiki/register_custom_reader_writer_cn
