### ISSUE TITLE
[BUG] 序列化特定格式的字段时失败

### ISSUE THREAD

**Issue by UncleDa** [alibaba/fastjson2#773]
### 问题描述
*简要描述您碰到的问题。*
序列化特定格式的字段时失败

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win11 64 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_322]
 - 版本信息：[e.g.：Fastjson2 2.0.13]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 新建一个类，添加由一个英文字母和另一个单词组成的实体类字段，eg: cType
2. 对实体类进行赋值后，转成jsonString
3. 打印后发现cType首字母变成了大写，而两个单词组成的字段则正常如myType
```java
@RunWith(SpringRunner.class)
public class MyTest {

    @Test
    public void test() {
        A a = new A();
        a.setCId("11");
        a.setCType("22");
        a.setMyType("type");
        System.out.println(a);
        System.out.println(JSON.toJSONString(a));
       //设置FieldBased后打印显示正常
        System.out.println(JSON.toJSONString(a, JSONWriter.Feature.FieldBased));

    }

    @Data
    public static class A  {

        private String cId;
        private String cType;
        private String myType;

    }
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
期望打印出
{"cId":"11","cType":"22","myType":"type"}
设置FieldBased后可打印出上面的效果，但现在默认的情况正常吗
### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
MyTest.A(cId=11, cType=22, myType=type)
{"CId":"11","CType":"22","myType":"type"}
{"cId":"11","cType":"22","myType":"type"}
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by UncleDa** [comment]
测试了下在fasjson1中输出是正常的
{"cId":"11","cType":"22","myType":"type"}

**Comment by wenshao** [comment]
看下这个issue:
https://github.com/alibaba/fastjson2/issues/607
