### ISSUE TITLE
parse、parseObject、parseArray等需要针对null进行过滤

### ISSUE THREAD

**Issue by kdl1217** [alibaba/fastjson2#78]
当null数据进行转换JSONReader.of(str)时，会调用com.alibaba.fastjson2.util.JDKUtils#getCharArray方法。
会导致系统错误！
见下图。
![image](https://user-images.githubusercontent.com/16287173/165031007-401acf2f-23ac-4ca4-9ad2-b6db64ef35e3.png)

**Comment by kdl1217** [comment]
提交了一个PR
[https://github.com/alibaba/fastjson2/pull/79](url)

另外，我在用fastjson2解析对象时产生了异常，后期将继续跟进。

**Comment by wenshao** [comment]
请签署CLA，这样我才能合入代码
