### ISSUE TITLE
[BUG] jdk17 Java: module not found: com.alibaba.fastjson2

### ISSUE THREAD

**Issue by wu1g119** [alibaba/fastjson2#780]
### 问题描述
jdk17 运行项目 报错 Java: module not found: com.alibaba.fastjson2

### 环境信息

 - OS信息：  [e.g.：Windows 11 专业版 Insider Preview Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz ]
 - JDK信息： [e.g.：corretto-17.0.4.1]
 - 版本信息：[e.g.：Fastjson2 2.0.14]
 

### 重现步骤

1. module-info.java
```java
  requires com.alibaba.fastjson2;
```
2. 测试类
 ```java
    public static void main(String[] args) {
        System.out.println("Hello world!");
        JSONObject jsonObject = JSON.parseObject("{\"isRemember\":false,\"account\":\"234\",\"password\":\"234\"}");
        System.out.println(jsonObject);
    }
```
4. 出现 `...` 错误
```java
  java: 找不到模块: com.alibaba.fastjson2
```

**Comment by wenshao** [comment]
问题已重现，还在定位原因，如果你有相关经验，也希望能帮忙

**Comment by wu1g119** [comment]
fastjson2-2.0.15-20220917.213214-2 经验证已修复该问题

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.15
2.0.15版本已发布，请用新版本
