### ISSUE TITLE
[FEATURE] 希望benchmark中增加 JSONB 针对序列化size的对比测试

### ISSUE THREAD

**Issue by ShiningXu** [alibaba/fastjson2#782]
最近想升级一下项目中的hessian，希望能用JSONB对比一下hessian/kryo/protobuf 等常用序列化后的的体积大小。帮助评估具体收益。

**Comment by wenshao** [comment]
JSONB大小比Hessian2要小，这个是在阿里内部业务真实环境的做过测试比较并且改进过的。

**Comment by wenshao** [comment]
比如Eishay的场景，两者的比较：
```
jsonb 409
hessian 656
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/wiki/eishay_jvm_serializers_benchmark
看下这个数据

**Comment by ShiningXu** [comment]
> 

好的，感谢温少
