### ISSUE TITLE
[FEATURE]支持动态模块的类清理

### ISSUE THREAD

**Issue by dashenbo** [alibaba/fastjson2#783]
### 请描述您的需求或者改进建议
热插拔模块是常见的设计思路，如插件实现了一个interface，宿主调用插件返回对象并用fastjson序列化，fastjson会对该插件类做cache，如果插件热更新后，老的classloader和类无法被gc掉。希望提供按classloader清理缓存的能力。

![image](https://user-images.githubusercontent.com/9404310/190973356-4e79d23d-371a-4b29-8791-b9b5e464a88b.png)

### 请描述你建议的实现方案
gson是实例级别缓存，当gson重新实例化后cache即释放。fastjson提供的是静态方法做序列化，建议cache也能按classloader提供机制做清理。

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.15
问题修复，请用新版本
