### ISSUE TITLE
为什么2.x的JSONObject直接改成继承LinkedHashMap?

### ISSUE THREAD

**Issue by xiaohuang1024** [alibaba/fastjson2#793]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
1.x的版本在创建JSONObject对象的时候，可以选择hashMap或者LinkdHashMap，但是2.x版本继承linkedHashMap就只能选择linkedHashMap,请问是有什么考虑吗？是从性能考虑？还是其他的呢？请问，不能像1.x版本一样自己选择吗？

**Comment by wenshao** [comment]
是考虑到最常用的场景是要保留顺序的，所以就用了继承自LinkedHashMap，继承比包装一层会性能略好。你可以通过配置JSONReader.Context.objectSupplier，按你的需要使用那种Map

**Comment by wenshao** [comment]
```java
assertEquals(
        HashMap.class,
        JSON.parse(
                "{}",
                JSONFactory.createReadContext(
                        () -> new HashMap()) // 指定objectSupplier为 HashMap
        ).getClass()
);

assertEquals(
        LinkedHashMap.class,
        JSON.parse(
                "{}",
                JSONFactory.createReadContext(
                        () -> new LinkedHashMap()) // 指定objectSupplier为 LinkedHashMap
        ).getClass()
);

assertEquals(
        TreeMap.class,
        JSON.parse(
                "{}",
                JSONFactory.createReadContext(
                        () -> new TreeMap()) // 指定objectSupplier为 TreeMap
        ).getClass()
);

assertEquals(
        ConcurrentHashMap.class,
        JSON.parse(
                "{}",
                JSONFactory.createReadContext(
                        () -> new ConcurrentHashMap()) // 指定objectSupplier为 ConcurrentHashMap
        ).getClass()
);
```
如上的例子，在fastjson2中，你可以很方便定制指定构造json object对应的Map

**Comment by wenshao** [comment]
```java
assertEquals(
        ArrayList.class,
        JSON.parse(
                "[]",
                JSONFactory.createReadContext(
                        null,
                        () -> new ArrayList()) // 指定arraySupplier为 ArrayList
        ).getClass()
);

assertEquals(
        LinkedList.class,
        JSON.parse(
                "[]",
                JSONFactory.createReadContext(
                        null,
                        () -> new LinkedList()) // 指定arraySupplier为 LinkedList
        ).getClass()
);

assertEquals(
        ArrayDeque.class,
        JSON.parse(
                "[]",
                JSONFactory.createReadContext(
                        null,
                        () -> new ArrayDeque()) // 指定arraySupplier为 ArrayDeque
        ).getClass()
);
```
如上的例子，在fastjson2中，你可以很方便定制指定构造json array对应的List

**Comment by huangnanjian** [comment]
> ```java
> assertEquals(
>         HashMap.class,
>         JSON.parse(
>                 "{}",
>                 JSONFactory.createReadContext(
>                         () -> new HashMap() // 指定objectSupplier为 HashMap
>                 )
>         ).getClass()
> );
> 
> assertEquals(
>         LinkedHashMap.class,
>         JSON.parse(
>                 "{}",
>                 JSONFactory.createReadContext(
>                         () -> new LinkedHashMap() // 指定objectSupplier为 LinkedHashMap
>                 )
>         ).getClass()
> );
> 
> assertEquals(
>         TreeMap.class,
>         JSON.parse(
>                 "{}",
>                 JSONFactory.createReadContext(
>                         () -> new TreeMap() // 指定objectSupplier为 TreeMap
>                 )
>         ).getClass()
> );
> 
> assertEquals(
>         ConcurrentHashMap.class,
>         JSON.parse(
>                 "{}",
>                 JSONFactory.createReadContext(
>                         () -> new ConcurrentHashMap() // 指定objectSupplier为 ConcurrentHashMap
>                 )
>         ).getClass()
> );
> ```
> 
> 如上的例子，在fastjson2中，你可以很方便地定制构造json对象的映射

请问这个可以全局替换，还是每次创建对象之前都得这样操作？

**Comment by wenshao** [comment]
当前的API需要每次都设置。

https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.15-SNAPSHOT/
新版本支持全局设置，请帮忙用2.0.15-SNAPSHOT验证，2.0.15版本预计在10月7日前发布

新的API如下：
```java
JSONFactory.setDefaultObjectSupplier(
        () -> new TreeMap() // 全局指定objectSupplier为 TreeMap
);
assertEquals(
        TreeMap.class,
        JSON.parse("{}").getClass()
);

JSONFactory.setDefaultObjectSupplier(
        () -> new ConcurrentHashMap() // 全局指定objectSupplier为 ConcurrentHashMap
);
assertEquals(
        ConcurrentHashMap.class,
        JSON.parse("{}").getClass()
);

JSONFactory.setDefaultArraySupplier(
        () -> new LinkedList() // 全局指定arraySupplier为 LinkedList
);
assertEquals(
        LinkedList.class,
        JSON.parse("[]").getClass()
);

JSONFactory.setDefaultArraySupplier(
        () -> new CopyOnWriteArrayList() // 全局指定arraySupplier为 CopyOnWriteArrayList
);
assertEquals(
        CopyOnWriteArrayList.class,
        JSON.parse("[]").getClass()
);
```

**Comment by xiaohuang1024** [comment]
> 当前的API需要每次都设置。
> 
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.15-SNAPSHOT/ 新版本支持全局设置，请帮忙用2.0.15-SNAPSHOT验证，2.0.15版本预计在10月7日前发布
> 
> 新的API如下：
> 
> ```java
> JSONFactory.setDefaultObjectSupplier(
>         () -> new TreeMap() // 全局指定objectSupplier为 TreeMap
> );
> assertEquals(
>         TreeMap.class,
>         JSON.parse("{}").getClass()
> );
> 
> JSONFactory.setDefaultObjectSupplier(
>         () -> new ConcurrentHashMap() // 全局指定objectSupplier为 ConcurrentHashMap
> );
> assertEquals(
>         ConcurrentHashMap.class,
>         JSON.parse("{}").getClass()
> );
> 
> JSONFactory.setDefaultArraySupplier(
>         () -> new LinkedList() // 全局指定arraySupplier为 LinkedList
> );
> assertEquals(
>         LinkedList.class,
>         JSON.parse("[]").getClass()
> );
> 
> JSONFactory.setDefaultArraySupplier(
>         () -> new CopyOnWriteArrayList() // 全局指定arraySupplier为 CopyOnWriteArrayList
> );
> assertEquals(
>         CopyOnWriteArrayList.class,
>         JSON.parse("[]").getClass()
> );
> ```

你好，验证是通过的，但是这个更换的作用是在解析json这一步的？而不是往JsonObject对象添加数据的时候？
![image](https://user-images.githubusercontent.com/10085565/192188944-8ac1f845-b803-41cc-857c-1a3a072033eb.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.15
请用新版本
