### ISSUE TITLE
jsonPath.extract解析不对

### ISSUE THREAD

**Issue by HuangZL-github** [alibaba/fastjson2#80]
String str = "{\"id\":123,\"姓名\":{\"location\":{\"top\":277,\"left\":618,\"width\":372,\"height\":164},\"words\":\"张三\"},\"log_id\":1453528763137919643}";

JSONPath jsonPath = JSONPath.of("log_id");
JSONReader parser = JSONReader.of(str);
System.out.println(jsonPath.extract(parser));

为什么获取到的结果是{"location":{"top":277,"left":618,"width":372,"height":164},"words":"张三"}，而不是1453528763137919643

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.2
问题已修复，请使用新版本
