### ISSUE TITLE
 找不到com.alibaba.fastjson2.filter.ValueFilter的类文件[BUG]

### ISSUE THREAD

**Issue by yz8943** [alibaba/fastjson2#812]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：win11]
 - JDK信息： [e.g.：jdk1.8.0_111 ]
 - 版本信息：[e.g.：fastjson-2.0.14.graal.jar 包]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
```
  static void renderXJSON(Object obj){
        response.setContentTypeIfNotSet("application/json; charset=utf-8");
        String jsonString = JSON.toJSONString(obj, new ValueFilter() {
            @Override
            public Object process(Object o, String propertyName, Object propertyValue){
                if(org.apache.commons.lang3.StringUtils.endsWith(propertyName, "Id") || org.apache.commons.lang3.StringUtils.equals(propertyName, "id")){
                    if(propertyValue != null){
                        return propertyValue.toString();
                    }
                }
                return propertyValue;

            }
        });
        throw new RenderText(jsonString);
    }
### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

java: 无法访问com.alibaba.fastjson2.filter.ValueFilter
  找不到com.alibaba.fastjson2.filter.ValueFilter的类文件

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
很奇怪，无法判断问题所在，需要你自己查
