### ISSUE TITLE
[QUESTION] SerializerFeature无法找到这个依赖

### ISSUE THREAD

**Issue by poloyyluo** [alibaba/fastjson2#814]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
```java
JSON.toJSONString(data, SerializerFeature.WriteMapNullValue)
```
想解决字段值为null时不忽略该字段，搜了下网上都说用 SerializerFeature.WriteMapNullValue，但在fastjson2 没找到相关文档，代码中也无法引入这个依赖，请问是改了使用方法吗？

**Comment by wenshao** [comment]
JSON.toJSONString(data,  JSONWriter.Feature.WriteMapNullValue)

**Comment by poloyyluo** [comment]
ok. thx, 感觉这块可以补充下文档，也可能是我漏看了~
