### ISSUE TITLE
[BUG] 同一个兼容包反序列化结果不一致

### ISSUE THREAD

**Issue by YAGAMIL** [alibaba/fastjson2#822]
### 问题描述
将String类型的数字反序列化为Long时，使用fastjson1.x没有问题
使用com.alibaba.fastjson2.JSON也没有问题
`com.alibaba.fastjson2.JSON#parseObject(java.lang.String, java.lang.Class<T>)`不出错
`com.alibaba.fastjson.JSON#parseObject(java.lang.String, java.lang.Class<T>)` 出错
但是当使用兼容包时，

### 环境信息
*请填写以下信息：*

 - OS信息： macOS、Linux、Windows
 - JDK信息： Jdk8
 - 版本信息：[e.g.：Fastjson2 2.0.15]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 分别使用不同包名下的两个JSON的 `parseObject(java.lang.String, java.lang.Class<T>)` 方法对一个string类型的字符串反序列化，使用一下代码可复现

```java
public class Test {
	public static void main(String[] args) {
		Map<String, Long> map = new HashMap<>();
		map.put("100", 100L);
		String s = JSON.toJSONString(DemoString.builder().map(map).build());
		System.err.println(com.alibaba.fastjson2.JSON.parseObject(s, Demo.class));
		System.out.println(JSON.parseObject(s, Demo.class));
	}

	@Data
	@Builder
	@NoArgsConstructor
	@AllArgsConstructor
	public static class Demo{
		private Map<Long, Long> map;
	}
	@Data
	@Builder
	@NoArgsConstructor
	@AllArgsConstructor
	public static class DemoString{
		private Map<String, Long> map;
	}

```

### 期待的正确结果
*两次都应该执行成功并输出相同的结果，但该案例在1.x中成立、在兼容包fastjson2下成立，但是在兼容包fastjson包下不成立

### 相关日志输出
```
Test.Demo(map={100=100})
Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at com.alibaba.fastjson.JSONObject.put(JSONObject.java:46)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMapTyped.readObject(ObjectReaderImplMapTyped.java:306)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:224)
```

maven依赖：
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>2.0.15</version>
            </dependency>

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
问题已经修复，请用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月30日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本
