### ISSUE TITLE
[BUG] json类型和实体类型不一致时，parse报错

### ISSUE THREAD

**Issue by Lce-Lemon** [alibaba/fastjson2#827]
### 问题描述
*简要描述您碰到的问题。*
json类型和实体类型不一致时，parse报错

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： Openjdk 1.8.0_312
 - 版本信息：Fastjson2 2.0.15
 

### 重现步骤
*如何操作可以重现该问题：*
1.新建实体类A
2.定义字符串json("{\"content\": \"aaa\", \"type\": \"\"}")
使用JSON.parseObject(json, A.class)报错

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
//可在此输入示例代码
public class TestJson {

@Data
public static class A {
    private Integer type;
    private String content;
}

public static void main(String[] args) {
    String json2 = "{\n" +
            "  \"content\": \"123456\",\n" +
            "  \"type\": \"\"\n" +
            "}";
    A a = JSON.parseObject(json2, A.class);
    System.out.println(a);
}
}
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
TestJson.A(type=null, content=123456)

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
Exception in thread “main” com.alibaba.fastjson.JSONException: illegal fieldName input
, offset 38, character
, line 4, column 2, fastjson-version 2.0.15
{
“content”: “123456”,
“type”: “”
}
at com.alibaba.fastjson.JSON.parseObject(JSON.java:234)
at com.hollysys.smartfactory.system.controller.TestJson.main(TestJson.java:28)
Caused by: com.alibaba.fastjson2.JSONException: illegal fieldName input
, offset 38, character
, line 4, column 2, fastjson-version 2.0.15
{
“content”: “123456”,
“type”: “”
}
at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:951)
at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:224)
… 1 more

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
若更换json中两个字段的位置，则可正常解析，如下
 String json2 = "{\n" +
            "  \"type\": \"\",\n" +
            "  \"content\": \"123456\"\n" +
            "}";

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
问题已经修复，请用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月30日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本
