### ISSUE TITLE
[BUG]JSONObject中放入null值后，toJSONString输出异常

### ISSUE THREAD

**Issue by dfengwei** [alibaba/fastjson2#828]
### 问题描述
2.0.15版本，当往一个JSONObject中放入值为null的属性后，toJSONString输出异常。2.0.14版本无此问题。

### 环境信息
 - OS信息：  WIndows11
 - JDK信息： Openjdk 11
 - 版本信息：Fastjson2 2.0.15
 
### 重现步骤
1.执行以下代码：
  ```java
  JSONObject test = new JSONObject();
  test.put("a", "a value");
  test.put("b", null);
  test.put("c", "c value");
  System.out.println(test.toJSONString());
  ```
2.输出：
  ```
  {"a":"a value",,"c":"c value"}
  ```

### 期待的正确结果
```
{"a":"a value","c":"c value"}
```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
问题已经修复，请用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月30日前发布

**Comment by galaxy-sea** [comment]
hello @wenshao ，这个issue又引发了一个问题了


# 重现步骤

1.执行以下代码：
```java
JSONObject test = new JSONObject();
test.put("a", "a value");
test.put("b", null);
test.put("c", "c value");
System.out.println(test.toJSONString());
```
2.输出：

```json
{
    "a": "a value",
    "c": "c value"
}
```

# 期待的正确结果

```json
{
    "a": "a value",
    "b": null,
    "c": "c value"
}
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本
