### ISSUE TITLE
[BUG]枚举类作为其他类属性时JSONTYPE=serializeEnumAsJavaBean=true失效，单独序列化成功

### ISSUE THREAD

**Issue by yqt2016** [alibaba/fastjson2#835]
问题描述
2.0.15版本，枚举类作为其他类属性时@JSONTYPE=serializeEnumAsJavaBean=true失效，而作为单独的类序列化，注解生效，使用fastjon1.x版本，注解生效

环境信息
OS信息： linux
JDK信息： Openjdk 8
版本信息：Fastjson2 2.0.15
重现步骤
1.执行以下代码：

package com..test.demo;

import com.alibaba.fastjson.annotation.JSONType;
import com.alibaba.fastjson2.JSON;
import lombok.*;

@Data
@NoArgsConstructor
@RequiredArgsConstructor(staticName = "ofCode")
public class Result<T> {
    private Object others;
    private T bo;
    @NonNull
    private ServiceCode code;

    @JSONType(serializeEnumAsJavaBean = true)
    @ToString
    @Getter
    public  enum ServiceCode {
        /**
         * SUCCESS
         */
        SUCCESS("00", "SUCCESS"),
        /**
         * ERROR
         */
        ERROR("01", "SERVER_ERROR");

        ServiceCode(String code, String msgId) {
            this.code = code;
            this.msgId = msgId;

        }

        private String code;
        private String msgId;
        @Setter
        private String msg;

    }

    public static void main(String[] args) {
        Result genericResult= Result.ofCode(ServiceCode.SUCCESS);
        System.out.println(JSON.toJSONString(genericResult));
        //{"code":0}
        System.out.println(JSON.toJSONString(ServiceCode.SUCCESS));
        //{"code":"00","msgId":"SUCCESS"}
        System.out.println(com.alibaba.fastjson.JSON.toJSONString(genericResult));
        //{"code":{"code":"00","msgId":"SUCCESS"}}
    }
2.输出：
{"code":0}
期待的正确结果
 {"code":{"code":"00","msgId":"SUCCESS"}}

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
问题已经修复，请用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月30日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本
