### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by xxcka** [alibaba/fastjson2#841]
使用com.alibaba.fastjson2.JSON#writeTo(java.io.OutputStream, java.lang.Object, com.alibaba.fastjson2.JSONWriter.Feature...)序列化大对象（数组，200M）时会出现OutOfMemoryError，查看是因为MAX_ARRAY_SIZE限制为64M。请问为什么是限制64M呢，可以修改这个值吗？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
新增加一个JSONWriter.Feature.LargeObject，启用后就可以写大于512M的对象，请帮忙用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月30日前发布

**Comment by wenshao** [comment]
限制64M是为了有一些循环引用的场景导致内存占用过大的保护措施

**Comment by xxcka** [comment]
2.0.16-SNAPSHOT使用JSONWriter.Feature.LargeObject写大于200M的对象没问题。感谢！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本

**Comment by lizu18xz** [comment]
dubbo中怎么配置这个参数 JSONWriter.Feature.LargeObject
