### ISSUE TITLE
jsonpath not support integer key  

### ISSUE THREAD

**Issue by qq1053831109** [alibaba/fastjson2#842]
$.items[0].data.\0\

\0\ is data  Object 

0是data对象的键 data是个对象 不是数组

**Comment by qq1053831109** [comment]
从fastjson1 升级到fastjson2 发现好多jsonpath  不兼容问题 ！数字key在tostring的时候也会报错类型转换错误，貌似底层fastjson2 认为json的key只能是字符串

**Comment by qq1053831109** [comment]
还有要支持宽松的 解析模式  很多json都是手写的  不想严格按照json格式来

**Comment by wenshao** [comment]
```java
String str = "{\"items\": [{\"data\":{\"0\":\"abc\"}}]}";
Object result = JSONPath.eval(str, "$.items[0].data.0");
assertEquals("abc", result);
```
这个是不是你想要的？

**Comment by qq1053831109** [comment]
String jsonPath = "$.items[0].data.0"; 

        Map data = new LinkedHashMap<>();
        JSONPath.set(data, jsonPath, "设置成功");

设置不进去  我的是fastjson-2.0.15

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
问题已经修复，请用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月30日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本

**Comment by qq1053831109** [comment]
Map data = new LinkedHashMap<>();
        JSONPath.set(data,  "$.obj.5", "设置成功");
        System.out.println(JSONObject.toJSONString(data));
会打印：
{"obj":[]}

我希望是打印 {"obj":{5:"设置成功"}}    obj是对象 不是数组

我用的最新的2.0.16

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.17
问题已修复，请用新版本

**Comment by qq1053831109** [comment]
Map data = new LinkedHashMap<>();
    JSONPath.set(data,  "$.obj.5", "设置成功");
    System.out.println(JSONObject.toJSONString(data));
会打印：
{"obj":[null,null,null,null,null,"设置成功"]}

我希望是打印 {"obj":{5:"设置成功"}} obj是对象 不是数组

我用的最新的2.0.17

**Comment by qq1053831109** [comment]
以前的fastjson1 就是支持数字key的 或者说是字符串为数字的 如key 为"12345"
