### ISSUE TITLE
[BUG] 值为null时,toString将会留下空白

### ISSUE THREAD

**Issue by hnuuhc** [alibaba/fastjson2#843]
fastjson2的版本为2.0.15
在当某个值为null时,使用toString会留下多余的空白,导致无法正常转回JSON
例子:
System.out.println(new JSONObject().fluentPut("1", 2).fluentPut("2", null).fluentPut("3", 4).toString());
输出为:
{"1":2,,"3":4}
可以见到键值1和3之间多出不应该出现的逗号,导致无法正常转回JSON,会提示not allow unquoted fieldName异常
我知道可以全局配置JSON.config(JSONReader.Feature.AllowUnQuotedFieldNames),但是这明显是一个不该存在的错误

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.16-SNAPSHOT/
问题已经修复，请用2.0.16-SNAPSHOT帮忙验证，2.0.16版本预计在10月30日前发布

**Comment by cmlibo** [comment]
这种低级错误也能出现，刚idea提示升级到2.0.15，升级了一下，toJSONString为null的就变成,,,,了，然后就无法反序列化了。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本
