### ISSUE TITLE
[BUG] TypeReference反序列化Map<Long,Long>类型存在问题

### ISSUE THREAD

**Issue by hnuuhc** [alibaba/fastjson2#844]
fastjson版本2.0.14和2.0.15
例子:
JSONObject json1 = new JSONObject();
json1.put(String.valueOf(1), 2);
json1.put(String.valueOf(2), 3);
json1.put(String.valueOf(3), 4);
Map<Long, Long> status = JSONObject.parseObject(json1.toJSONString(), new TypeReference<>() {});
for (Map.Entry<Long, Long> l : status.entrySet()) {
	System.out.println(l.getValue() - l.getKey());  // 运算异常
}
会报以下异常:
Exception in thread "main" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
多次尝试发现是TypeReference反序列化的Long类型虽然可以读取,但是根本无法进行计算
整个过程中不会报任何异常,直至进行运算操作
在循环中:
long x =  l.getValue() ; 异常
System.out.println(l.getValue()); 正常输出

**Comment by wenshao** [comment]
```java
        JSONObject json1 = new JSONObject();
        json1.put(String.valueOf(1), 2);
        json1.put(String.valueOf(2), 3);
        json1.put(String.valueOf(3), 4);

        Map<Long, Long> status = JSONObject.parseObject(
                json1.toJSONString(),
                new TypeReference<Map<Long, Long>>() {}
        );
        for (Map.Entry<Long, Long> entry : status.entrySet()) {
            Object originValue = json1.getLongValue(String.valueOf(entry.getKey()));
            Long value = entry.getValue();
            assertEquals(originValue, value);
        }
```
我测试试好了，你看下

**Comment by hnuuhc** [comment]
是否可以更简洁的方式进行转换:
期待: JSONObject.parseObject(json1.toJSONString(), new TypeReference<>() {});
实际: JSONObject.parseObject(json1.toJSONString(), new TypeReference<HashMap<Long,Long>() {});
必须写明内部类型才能正确转换,使用泛型也不能正确的转换
```
public static <K, V> Map<K, V> toMap(@NotNull String str) {
	return JSONObject.parseObject(str, new TypeReference<HashMap<K, V>>() {});
}

System.out.println(entry.getValue() - entry.getKey()); 
```

**Comment by hnuuhc** [comment]
> ```java
>         JSONObject json1 = new JSONObject();
>         json1.put(String.valueOf(1), 2);
>         json1.put(String.valueOf(2), 3);
>         json1.put(String.valueOf(3), 4);
> 
>         Map<Long, Long> status = JSONObject.parseObject(
>                 json1.toJSONString(),
>                 new TypeReference<Map<Long, Long>>() {}
>         );
>         for (Map.Entry<Long, Long> entry : status.entrySet()) {
>             Object originValue = json1.getLongValue(String.valueOf(entry.getKey()));
>             Long value = entry.getValue();
>             assertEquals(originValue, value);
>         }
> ```
> 
> 我测试试好了，你看下


是否可以更简洁的方式进行转换：
期待： JSONObject.parseObject（json1.toJSONString（）， new TypeReference<>（） {}）;
实际： JSONObject.parseObject（json1.toJSONString（）， new TypeReference<HashMap<Long，Long>（） {}）;
必须写明内部类型才能正确转换,使用泛型也不能正确的转换
```
public static <K, V> Map<K, V> toMap(@NotNull String str) {
	return JSONObject.parseObject(str, new TypeReference<HashMap<K, V>>() {});
}

System.out.println(entry.getValue() - entry.getKey()); 
```

**Comment by wenshao** [comment]
这个是Java语言的机制，目前没找到更简洁的写法
