### ISSUE TITLE
[BUG]kotlin类序列化异常

### ISSUE THREAD

**Issue by cjdxhjj** [alibaba/fastjson2#848]
### 问题描述
*简要描述您碰到的问题。*
一个简单的kotlin类使用fastjson序列化异常

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：windows 10]
 - JDK信息： [e.g.：oracle jdk 11]
 - 版本信息：[e.g.：Fastjson2 2.0.15]
 

### 重现步骤
*如何操作可以重现该问题：*
![391d1e4507c521b741f448e4e443b5b](https://user-images.githubusercontent.com/5616997/196120166-1be663b4-c49a-4749-ba89-a50b7cc45d19.jpg)
![e599a1404012ea5e95a9c53f2fe331b](https://user-images.githubusercontent.com/5616997/196120207-01f784d5-61b4-433a-9b3b-7945de59393e.jpg)
![1403808b7c509c9ebe2eda4502248ce](https://user-images.githubusercontent.com/5616997/196120241-d760e2c8-f8cf-4309-ab63-d85f6f7e638a.jpg)
![d28093bdecba150ac437c7bc10d49fb](https://user-images.githubusercontent.com/5616997/196120389-58dea234-4aea-4fb6-8817-2a1a9d9cd927.jpg)

引入了kotlin扩展也不管用

**Comment by wenshao** [comment]
@kraity 帮看下

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本
