### ISSUE TITLE
@FastJsonView注解

### ISSUE THREAD

**Issue by lihoubing** [alibaba/fastjson2#857]
@FastJsonView 过滤返回属性在fastjson2.0.15 中没有找到，是否有什么替代方案？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.22-SNAPSHOT/
问题已修复，请帮忙用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
