### ISSUE TITLE
[BUG] WriteEnumUsingName不生效

### ISSUE THREAD

**Issue by 18990999908** [alibaba/fastjson2#859]
### 问题描述
*简要描述您碰到的问题。*
JSONObject.toJSONString(build, SerializerFeature.WriteEnumUsingName);
最后输出的 还是ordinal

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Mac OS]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.15]
 

### 重现步骤
*如何操作可以重现该问题：*
1. 构建一个带枚举的class, 并实例化
```java
PayoutBill build = PayoutBill.builder()
                .currency(Currency.CNY)
                .build();
@Getter
@AllArgsConstructor
public enum Currency {
    CNY("人民币"),
    USD("美元"),
    EUR("欧元"),
    GBP("英镑"),
    HKD("港币");

    private final String desc;
}


JSONObject.toJSONString(build, SerializerFeature.WriteEnumUsingName);

```
### 期待的正确结果
*希望序列化时使用枚举的name()输出*
实际输出为
{"cbsPayout":false,"currency":0,"poPayout":false}

期望输出为: 
{"cbsPayout":false,"currency":"CNY","poPayout":false}

#### 附加信息
* JSON.config方法没有case: WriteEnumUsingName并写入到context中

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.16-SNAPSHOT/
问题已经修复，请帮忙用2.0.16-SNAPSHOT版本验证，2.0.16正式版预计在10月23日前发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.16
问题已修复，请用2.0.16版本

**Comment by ganweiming** [comment]
@wenshao kotlin 版本SerializerFeature.WriteEnumUsingName依然不生效. version 2.0.19

**Comment by wenshao** [comment]
@ganweiming 请提一个新的issue，帮忙提供重现问题的testcase
