### ISSUE TITLE
[BUG]Long类型的自定义ObjectWriter，注册为全局时不生效

### ISSUE THREAD

**Issue by wufenglover** [alibaba/fastjson2#863]
### 问题描述
*简要描述您碰到的问题。*
自定义ObjectWriter，实现Long转String时，如果通过JSON.register全局注册时不生效。

### 环境信息
*请填写以下信息：*

 - OS信息：  windows11
 - JDK信息： 1.8.0_333
 - 版本信息：fastjson2.0.15
 

### 重现步骤
*如何操作可以重现该问题：*

1. 自定义ObjectWriter后，全局设置
        JSON.register(BigInteger.class, NumberSerializer.instance);
        JSON.register(BigDecimal.class, NumberSerializer.instance);
        JSON.register(Long.class, NumberSerializer.instance);
        JSON.register(Long.TYPE, NumberSerializer.instance);
        JSON.register(Timestamp.class, TimestampSerializer.instance);
2. SpringBoot注册fastjson2转换器，通过ResponseBody写回客户端后，Long类型没有转成String，Timestamp类型按自定义格式转换成功。经测试NumberSerializer序列化都没有进入。

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
Long类型能转成String类型。

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
用2.0.16帮忙验证下

**Comment by wufenglover** [comment]
> 用2.0.16帮忙验证下

已解决
