### ISSUE TITLE
[FEATURE] 空字符串序列化BEAN问题

### ISSUE THREAD

**Issue by aokunsang** [alibaba/fastjson2#873]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*
fastjson1 中空字符串反序列化成BEAN为null(或者不序列化)，fastjson2 中空字符反序列化BEAN是非NULL，一个空对象。

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*
是否可以添加个JSONReader.Feature能够控制空字符串反序列化对象是NULL或者空对象？

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
能帮忙提供重现问题的testcase么？
