### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by dada-Hao** [alibaba/fastjson2#874]
### 请描述您的需求或者改进建议
*对您想要需求或建议的清晰简洁的描述。*
fastjson2 2.0.16版本 
缺少JSONPath#read(java.lang.String, java.lang.String, java.lang.reflect.Type)

fastjson 1.2.76+ 支持JSON.read方法 
com.alibaba.fastjson.JSONPath#read(java.lang.String, java.lang.String, java.lang.reflect.Type)

### 请描述你建议的实现方案
*对您想要需求或建议的实现方案的详细描述。*

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

<img width="2004" alt="image" src="https://user-images.githubusercontent.com/30745396/198188245-7e777529-bd46-4588-8b72-0de0c5e6e655.png">

**Comment by bdzxm** [comment]
what’s the fucking this

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.17-SNAPSHOT/
问题已修复，请帮忙用2.0.17-SNAPSHOT版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.17
问题已修复，请用新版本
