### ISSUE TITLE
jpath星号通配符异常行为

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/fastjson2#88]
String data = "{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1632273205,"3"],[1632273210,"3"],[1632273215,"3"],[1632273220,"3"],[1632273225,"3"],[1632273230,"3"],[1632273235,"3"],[1632273240,"3"],[1632273245,"3"],[1632273250,"3"],[1632273255,"3"],[1632273260,"3"],[1632273265,"3"],[1632273270,"3"],[1632273275,"3"],[1632273280,"3"],[1632273285,"3"],[1632273290,"3"],[1632273295,"3"],[1632273300,"3"],[1632273305,"3"]]}]}}\n";
Object obj = JSONPath.eval(data, "$.data.result[0].values[*][0]");
只返回一个JSONArray,[1632273205, 3]
预期应该返回
[1632273205,1632273210,1632273215........]

ref https://github.com/alibaba/fastjson/issues/3903

**Comment by yinwoods** [comment]
参考：com.alibaba.fastjson2.jsonpath.PathTest9#test0，目前的行为是符合预期的，建议后续补充相应文档，当前 issue 可关闭。
