### ISSUE TITLE
[QUESTION]fastjson 1.2.73->2.0.12

### ISSUE THREAD

**Issue by byuyuyu** [alibaba/fastjson2#888]
出现了\u0000

**Comment by wenshao** [comment]
用2.0.17看是否还存在问题

**Comment by byuyuyu** [comment]
> 用2.0.17看是否还存在问题

升级到2.0.17json中还是存在\u0000

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by byuyuyu** [comment]
> 能提供重现问题的testcase么？

在WebSphere 8.5.5.22上有问题，Tomcat8.0.50下没有
	
	public void formatQueryDecimalData(List<Map<String, Object>> resultMap, Map<String, ReportFieldConfig> decimalAndDateFields) {
		resultMap.stream().forEach(
			result -> result.keySet().forEach(key -> {
				if(decimalAndDateFields.containsKey(key) && StringUtils.isNotBlank(decimalAndDateFields.get(key).getDataFormat())) {
					if("DECIMAL".equals(decimalAndDateFields.get(key).getDataType())) {
						try {
							result.put(key, new DecimalFormat(decimalAndDateFields.get(key).getDataFormat()).format(result.get(key)));
						} catch (Exception e) {
							// 如果因为配置中填写的格式有问题导致转换失败，则默认保留两位
							result.put(key, new DecimalFormat("0.00").format(result.get(key)));
						}
					} else if("DATE".equals(decimalAndDateFields.get(key).getDataType())) {
						//日期/时间的格式化处理
						try {
							result.put(key, transformDateFromResult(result.get(key), decimalAndDateFields.get(key).getDataFormat()));
						} catch (Exception e) {
							// 如果因为配置中填写的格式有问题导致转换失败，则默认YYYY-MM-DD
							try {
								result.put(key, transformDateFromResult(result.get(key), DateUtil.DATE_PATTERN2));
							} catch (Exception e1) {}
						}
					}
				}
			})
		);
	}

	public String transformDateFromResult(Object result, String format) throws Exception{
		if(result instanceof java.sql.Time) {
			return new SimpleDateFormat(format).format((java.util.Date)result);
		}else if(result instanceof java.sql.Date) {
			return new SimpleDateFormat(format).format((java.sql.Date)result);
		}else if(result instanceof java.sql.Timestamp) {
			return new SimpleDateFormat(format).format((java.util.Date)result);
		}else if(result instanceof java.util.Date) {
			return new SimpleDateFormat(format).format((java.sql.Time)result);
		} else if(result instanceof oracle.sql.TIMESTAMP) {
			TIMESTAMP t = (oracle.sql.TIMESTAMP)result;
			return new SimpleDateFormat(format).format(t.timestampValue());
		}
		return result.toString();
	}

	JSONObject resultJson = new JSONObject();
	this.formatQueryDecimalData(resultMap, decimalAndDateFields);
	resultJson.put("data", resultMap);
	logger.info(resultJson);

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.19-SNAPSHOT/
问题已修复，请帮忙用2.0.19-SNAPSHOT验证，2.0.19版本预计在11月13日前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本

**Comment by phptalker** [comment]
我们用的2.0.25还是存在这个问题 {"signData":"c6c4ba0cb129a7f86382dd85732c165faf56d9f867baf76bc73a6c3712c7c2ec43c28cbd207aa0f22841020ca5f543a192963c81bf50671406d62cf2bf11e2d533a2227d829c953cf6601d354d5374943fbf8106f44083346f48cb1a0e0302f85fd46e7834e83ca1f71e45da7ab049deb82cdf0353c1443cf2f54ff5d27a720a\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","terminalNo":"","orgNo":"","endDate":"20230829142501\u0000\u0000","requestDate":"20230829142501\u0000\u0000","pageSize":"1","currentPage":"1","loginNo":"","startDate":"20230828142500\u0000\u0000","merchantNo":""}

**Comment by phptalker** [comment]
![image](https://github.com/alibaba/fastjson2/assets/14799682/06393396-fee4-4fa7-9f4c-2635b1a33218)
