### ISSUE TITLE
[BUG]2.0.17-SNAPSHOT core 模块下运行单元测试有 13 个没有通过

### ISSUE THREAD

**Issue by wyyl1** [alibaba/fastjson2#889]
### 问题描述
core 模块下运行单元测试有 13 个没有通过

### 环境信息
*请填写以下信息：*

 - OS信息：  [MacOS Monterey 12.2.1 2.7 | GHz 四核Intel Core i7 | 16 GB 2133 MHz LPDDR3]
 - JDK信息： [Oracle OpenJDK version 1.8.0_191]
 - 版本信息：[fastjson2 2.0.17-SNAPSHOT]
 

### 重现步骤

1. 执行 ~/fastjson2/core/src/test/java 目录下所有单元测试
2. 执行后有 13 个测试未通过

### 期待的正确结果

期待所有测试全部通过

#### 附加信息

![tests-failed-13](https://user-images.githubusercontent.com/3048393/199300530-832c16b4-781b-4f6a-a6f3-10f685cdde14.png)

### 补充

我是否可以尝试修复后提交 PR ？

**Comment by wenshao** [comment]
现在mvn test只跑com.alibaba.fastjson2目录下的

**Comment by wyyl1** [comment]
谢谢

**Comment by wyyl1** [comment]
我重新跑了一遍测试，确认是 core 模块下 com.alibaba.fastjson2 目录下的测试有 13 个没有通过，麻烦您再看一下

![fastjson-2](https://user-images.githubusercontent.com/3048393/199500906-879bf710-d157-40af-9205-88f9f27c8447.png)

**Comment by wenshao** [comment]
欢迎提交PR

**Comment by wyyl1** [comment]
## 新问题

版本信息：[fastjson2 2.0.17-SNAPSHOT]

刚才 fork 了一份代码，切换到 Zulu JDK 跑了一下发现和 Oracle 的测试结果不一样

JDK Azul zulu 1.8.0_345 测试后有 **11** 个没有通过： **JSONReaderTest1** 的两个测试用例在这里是通过的

对比图

![fastjson-3](https://user-images.githubusercontent.com/3048393/200167702-ea35a2f0-2421-4d0d-91f9-0fe5b14c5941.png)

**Comment by wenshao** [comment]
在MacOS或者在Ubuntu下，跑ZuluJDK8/11/17都是能跑过的
