### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by dyj2012** [alibaba/fastjson2#899]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.x.x]
 

### 重现步骤
*如何操作可以重现该问题：*

1. 使用 `xxx.xxx` 方法
2. 输入 `...`  数据
3. 出现 `...` 错误
```java
        Timer timer;
        ClassLoader prevContextCL = Thread.currentThread().getContextClassLoader();
        try {
            Thread.currentThread().setContextClassLoader(null);
            timer = new Timer("test", true);
        } finally {
            Thread.currentThread().setContextClassLoader(prevContextCL);
        }
        timer.schedule(new TimerTask() {
            public void run() {
                System.out.println(111);
            }
        }, 3500);
```

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

java.lang.NullPointerException
	at com.alibaba.fastjson2.JSONReaderJSONB.checkAutoType(JSONReaderJSONB.java:800)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:508)
	at com.xxxxx
	at java.lang.ThreadLocal$ThreadLocalMap.<init>(ThreadLocal.java:391)
	at java.lang.ThreadLocal$ThreadLocalMap.<init>(ThreadLocal.java:298)
	at java.lang.ThreadLocal.createInheritedMap(ThreadLocal.java:255)
	at java.lang.Thread.init(Thread.java:417)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:445)
	at java.util.TimerThread.<init>(Timer.java:499)
	at java.util.Timer.<init>(Timer.java:101)

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
![image](https://user-images.githubusercontent.com/37611109/199744879-157154ba-7d62-4ecd-8a8b-9cdcdbcf6bae.png)
![image](https://user-images.githubusercontent.com/37611109/199745175-8642d8f4-88e9-453b-be78-22a95d642899.png)

**Comment by wenshao** [comment]
问题未重现，请用2.0.17帮忙验证

**Comment by dyj2012** [comment]
重现代码  

  @Test
    public void m6() {
        Vo vo = new Vo();
        for (int i = 0; i < 10; i++) {
            Thread.currentThread().setContextClassLoader(null);
            byte[] bytes = JSONB.toBytes(vo, JSONWriter.Feature.WriteClassName);
            JSONB.parseObject(bytes, Object.class, JSONReader.Feature.SupportAutoType, JSONReader.Feature.SupportClassForName);
        }
    }

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.18-SNAPSHOT/
问题已修复，请帮忙用2.0.18-SNAPSHOT版本验证，2.0.18版本预计在周末发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.18
问题已修复，请用新版本
