### ISSUE TITLE
[BUG]关于序列化首字母大写的问题

### ISSUE THREAD

**Issue by HuShao96** [alibaba/fastjson2#901]
### 问题描述
*使用了lombok，在对象序列化时，首字母为大写，不符合期待值的问题*

### 环境信息
*请填写以下信息：*

 - 版本信息：[e.g.：Fastjson2 2.0.17]
 

### 重现步骤
*如何操作可以重现该问题：*

3. 出现 `...` 错误
```java
{"CName":"222","committeeCategory":"121"}
```

### 期待的正确结果
*{"cName":"222","committeeCategory":"121"}*

看了日志，前几个版本说修复了，但是还是没有到

**Comment by wenshao** [comment]
生成的方法就是getCName()，这个符合javaBean的规范

**Comment by HuShao96** [comment]
好的。谢谢
