### ISSUE TITLE
[QUESTION] 如何根据多级子节点进行过滤？

### ISSUE THREAD

**Issue by pengten** [alibaba/fastjson2#904]
### 请描述您的问题
*询问有关本项目的使用和其他方面的相关问题。*
我向做到类似这个表达式的过滤，现在是不支持吗？
$.transactions[?(@.transaction.message.accountKeys.indexOf('11111111111111111111111111111111')!=-1)]

**Comment by wenshao** [comment]
能给出相关的json数据样本么？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.19-SNAPSHOT/
请帮忙用2.0.19-SNAPSHOT验证，2.0.19版本预计在11月13日前发布。

JSONPath需要修改为
```javascript
$.transactions[?(@.transaction.message.accountKeys.contains('1a'))]
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本
