### ISSUE TITLE
Android使用打包报错

### ISSUE THREAD

**Issue by lixiangkai1987** [alibaba/fastjson2#91]
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

**Comment by wenshao** [comment]
Android的匹配要晚些时间，预计会要到6月份，具体时间后续我再在这里回复，谢谢你的支持！

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.2.android-SNAPSHOT/
你试试这个版本，预计5月2日会发布，我还没来得及在android验证过，需要你的帮忙

**Comment by nganh1** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.2.android-SNAPSHOT/ 你试试这个版本，预计5月2日会发布，我还没来得及在android验证过，需要你的帮忙

我使用最新的`androidx.constraintlayout:constraintlayout:2.1.3`，编译时依然会报这个错误

**Comment by nganh1** [comment]
> 我也遇到了同样的问题，请问解决了吗？

没有，我先降回`fastjson1`了，等后面再弄吧

**Comment by kraity** [comment]
你好, 在Android中版本有要求, 因为fastjson2使用了`MethodHandle`, 要Android API O及其之上版本, 需要在应用模块`build.gradle`将`minSdkVersion`设置为21及其之上, 需要注意的是`targetSdkVersion`为26及其之上

**Comment by luckpig** [comment]
大佬你好，项目配置如下：
com.android.tools.build:gradle : 3.4.3
gradle_wrapper : gradle-5.4.1-all.zip
compileSdkVersion : 28,
buildToolsVersion : "28.0.3",
minSdkVersion : 21,
targetSdkVersion : 28
fastjson配置的2.0.4版本，但是编译还是提示
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
请问这是哪里配置的问题？需要更新gradle tools的版本吗？

**Comment by kraity** [comment]
> 大佬你好，项目配置如下： com.android.tools.build:gradle : 3.4.3 gradle_wrapper : gradle-5.4.1-all.zip compileSdkVersion : 28, buildToolsVersion : "28.0.3", minSdkVersion : 21, targetSdkVersion : 28 fastjson配置的2.0.4版本，但是编译还是提示 MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26) 请问这是哪里配置的问题？需要更新gradle tools的版本吗？

你好, 如果你的用户基本都在Android 8.0 (API26)版本及其之后, 
那么当前解决办法是26<=minSdkVersion<=targetSdkVersion

因为在Android API26+可以使用Java1.8的一些新增功能, 比如MethodHandle和java.util.Base64

**Comment by luckpig** [comment]
用户中存在低系统版本的，最高设置minSdkVersion=21。请问有没有其他其他办法可解决这个问题呢？还是只能使用fastjson1了。感谢回复
