### ISSUE TITLE
[BUG] JSONObject.to SupportClassForName没效果

### ISSUE THREAD

**Issue by RockyLOMO** [alibaba/fastjson2#914]
### 问题描述
JSONObject.to SupportClassForName没效果

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.18]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
  return new JSONObject(map).to(type,JSONReader.Feature.SupportClassForName);    //没效果
  return JSON.parseObject(JSON.toJSONString(map),type, JSONReader.Feature.SupportClassForName);  //有效果
```

### 期待的正确结果
JSONObject.to SupportClassForName 生效

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.19-SNAPSHOT/
问题已修复，请帮忙用2.0.19-SNAPSHOT验证，2.0.19版本预计在11月13日前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本
