### ISSUE TITLE
[QUESTION]关于ObjectNode的序列化问题

### ISSUE THREAD

**Issue by memoryTravel** [alibaba/fastjson2#921]
之前一直是用fastjson1.0做序列化，因为今天项目引入了一个工作流demo，然后发现它的返回格式是ObjectNode，结果序列化后得到的不是一个json串，而是一个字符串，看了下1.0的代码，是对ObjectNode直接转成了String，这个问题我看之前也有人提过。
![image](https://user-images.githubusercontent.com/52353743/201282558-828b4146-b4b6-4681-9fe9-1547c959c759.png)
然后我将fastjson升级到2.0，然后做了以下配置
![image](https://user-images.githubusercontent.com/52353743/201285436-f73f4e67-82d8-45d7-ad21-58c7047a6cec.png)
![image](https://user-images.githubusercontent.com/52353743/201287587-ffe63ef7-061a-4103-9202-59fab149b7a9.png)
结果最后报了栈溢出
![image](https://user-images.githubusercontent.com/52353743/201288076-9090cb0c-ae12-4834-950f-7f3fc93584f5.png)
请问有没有比较好的解决方案？

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.19-SNAPSHOT/
问题已修复，请帮忙用2.0.19-SNAPSHOT验证，2.0.19版本预计在11月13日前发布。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本
