### ISSUE TITLE
Lombok @Value annotation support

### ISSUE THREAD

**Issue by osivinyuk** [alibaba/fastjson2#923]
We are working with FastJson 1 and Lombok.
A lot of our DTO classes was with @Value annotation
New FastJson 2 version does not support automaticaly field name mapping from JSONField for variables.
We need to create separate constructor with JSONField annotation and its working normally.
Is it intended behavior?
Thank you

**Comment by wenshao** [comment]
can you provide a testcase to show the problem?

**Comment by osivinyuk** [comment]
https://github.com/osivinyuk/FastJson2

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请用2.0.20-SNAPSHOT版本帮忙验证

**Comment by osivinyuk** [comment]
Thank you so much. Its working)
