### ISSUE TITLE
[BUG]大写单字母名称字段序列化与反序列化错误

### ISSUE THREAD

**Issue by kelincxm** [alibaba/fastjson2#924]
### 问题描述
对包含大写单字母名称的字段进行序列化与反序列化时错误

### 环境信息

 - OS信息：  windows10 19042.1706 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz 8GB
 - JDK信息： Openjdk 1.8.0_301
 - 版本信息：2.0.15
 

### 重现步骤

```java
public class Main {
	public static void main(String[] args) {
                System.out.println(new Entity(100L));
		System.out.println(JSON.toJSONString(new Entity(100L)));
		System.out.println(JSON.parseObject(JSON.toJSONString(new Entity(100L)), Entity.class));
	}

	@AllArgsConstructor
	@NoArgsConstructor
	@Data
	public static class Entity {
		private Long C;
	}
}
```

### 期待正确结果
Main.Entity(C=100)
{"C":100}
Main.Entity(C=100)

### 实际输出结果
Main.Entity(C=100)
{"c":100}
Main.Entity(C=100)

#### 附加信息
第二行代码应该被序列化为{"C":100}。但实际上被序列化为{"c":100}。而通过{"c":100}去反序列化Entity时，正确的结果应该是Main.Entity(C=null)。

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.19-SNAPSHOT/
问题已修复，请帮忙用2.0.19-SNAPSHOT验证，2.0.19版本预计在11月13日前发布。

**Comment by kelincxm** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.19-SNAPSHOT/ 问题已修复，请帮忙用2.0.19-SNAPSHOT验证，2.0.19版本预计在11月13日前发布。

经过测试，对象序列化为字符串是正确的。但通过字符串{"c": 100}反序列化对象时，对象的C字段仍然可以保存为100。

我认为反序列化后的C字段应该是null，因为C和c大小写不一致。

**Comment by kelincxm** [comment]
`
public class Main {
	public static void main(String[] args) {
		System.out.println(JSON.parseObject("{\"c\":100}", Entity.class));
	}

	public static class Entity {
		private Long C;

		public Entity(Long c) {
			C = c;
		}

		public Entity() {
		}

		public Long getC() {
			return C;
		}

		public void setC(Long c) {
			C = c;
		}

		@Override
		public String toString() {
			return "Entity{" +
				"C=" + C +
				'}';
		}
	}
}
`

### 期望结果
Entity{C=null}

### 实际结果
Entity{C=100}

**Comment by wenshao** [comment]
反序列化这个场景需要自动识别"c"和"C"，要不然会有升级兼容问题

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
请用新版本

**Comment by kelincxm** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.19 请用新版本

好的
