### ISSUE TITLE
Kotlin 版本2.0.19 WriteEnumUsingToString 不生效

### ISSUE THREAD

**Issue by ganweiming** [alibaba/fastjson2#928]
### 问题描述
由1.2.79版本升级上来后所有枚举.toJSONString()输出不符合预期

### 环境信息

 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：[Fastjson2 2.0.19](fastjson2-kotlin:2.0.19)]
 
实际输出为{}

**Comment by ganweiming** [comment]
1.从1.2版本到现在Enum默认输出都不跟随@JSONField(name = "")的值输出. name属性只有在解析的时候生效.

**Comment by ganweiming** [comment]
2.0.19版本枚举直接输出为{}

**Comment by wenshao** [comment]
能提供重现代码的testcase么？

**Comment by ganweiming** [comment]
![企业微信截图_17abe9e9-4e92-4832-8220-462a4afc718d](https://user-images.githubusercontent.com/18005096/201632549-3f98c5b0-1f22-4fa1-9d94-91112c5b435d.png)
![企业微信截图_c07ad7a7-224f-4e61-aa2e-7d1def410040](https://user-images.githubusercontent.com/18005096/201632566-9c9b9d4b-8
![企业微信截图_0a561935-3208-467b-833e-b2c9cb2c4109](https://user-images.githubusercontent.com/18005096/201632586-f6c5110b-2196-40c2-9937-d10de1645166.png)
588-4318-b49a-52e2fd9a6760.png)

**Comment by ganweiming** [comment]
![2](https://user-images.githubusercontent.com/18005096/201632708-c0a7c2a8-3f60-478d-b6f2-d1290fe1b05f.png)
![3](https://user-images.githubusercontent.com/18005096/201632743-596465da-366c-4e2a-a08f-5dd3129e802d.png)
![1](https://user-images.githubusercontent.com/18005096/201632760-f133b9ab-dcc3-416a-81f2-4908b9b109c9.png)

**Comment by ganweiming** [comment]
@wenshao 这个问题从1.2.x开始kotlin版本就已经存在了. UsingName不生效. 只有UsingToString才生效, 现在2.0.19都不生效了

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请用2.0.20-SNAPSHOT版本帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.20
请用新版本
