### ISSUE TITLE
[FEATURE] 增强对FASTJSON 1.x兼容

### ISSUE THREAD

**Issue by wenshao** [alibaba/fastjson2#929]
提升测试和用户升级过程中发现的FASTJSON 1.x兼容问题

**Comment by m1ngyuan** [comment]
还有一种情况下，会出现与1.x不兼容的情况，例如DTO中增加字段 Boolean isSuccess;

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.20
问题已修复，请用新版本

**Comment by m1ngyuan** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.20 问题已修复，请用新版本

不好意思，我可能 没有表达清楚我的意思 ，我已经添加相关的case d3ab94d4d113f4e650d0b84bb4921c2b522ea617

**Comment by wenshao** [comment]
@m1ngyuan 我新建了一个issue
https://github.com/alibaba/fastjson2/issues/976
