### ISSUE TITLE
[FEATURE]关于ZonedDateTime类型序列化问题

### ISSUE THREAD

**Issue by royzj** [alibaba/fastjson2#933]
### 请描述您的需求或者改进建议

fastjson2版本：
```
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.4</version>
        </dependency>

```
jdk版本：11

```java

    @Test
    public void test() {
        Map<String, ZonedDateTime> date = Map.of("date", ZonedDateTime.parse("2022-11-15T00:00:00.000+08:00", DateTimeFormatter.ISO_DATE_TIME));
        System.out.println(JSON.toJSONString(date));
    }

```
期望获得：`2022-11-15T00:00:00.000+08:00`
实际获得：`2020-08-01T00:00:00[+08:00]`

> 加上这个序列化出来[Asia/Shanghai]没有+08:00

**Comment by wsxe9988** [comment]
你可以升级到最新版再试下，最新版是2.0.19

**Comment by wenshao** [comment]
```java
2022-11-15T00:00:00.000+08:00
2020-08-01T00:00:00[+08:00]
```
这两个是一样的意思，是什么原因一定要".000“啊，如果你需要固定格式，可以配置format

**Comment by royzj** [comment]
”.000“不是必须的，在于”[+8:00]“这个中括号

![image](https://user-images.githubusercontent.com/51261841/202368991-50c4fbc6-daa5-4066-a760-e871e1c35ae4.png)

![image](https://user-images.githubusercontent.com/51261841/202369016-2a0c1205-d5b2-4b72-bf97-4d84338239c0.png)

spring自带的jackson序列化 `2020-08-01T00:00:00[+08:00]` 会报错

我目前是用replace代替一下
JSON.toJSONString(xxx).replace("[", "").replace("]", "")

报错信息
```
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `java.time.ZonedDateTime` from String "2020-08-01T00:00:00[+08:00]": Text '2020-08-01T00:00:00[+08:00]' could not be parsed at index 19; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.ZonedDateTime` from String "2020-08-01T00:00:00[+08:00]": Text '2020-08-01T00:00:00[+08:00]' could not be parsed at index 19

```

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请用2.0.20-SNAPSHOT版本帮忙验证
