### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by China2K** [alibaba/fastjson2#939]
### 问题描述
fastjson2使用兼容模式，序列化过程后枚举类型的转化和fastjson1结果不一致

### 相关日志输出
{"expired":0,"logType":0,"playType":6,"seconds":0,"seriesNumber":0,"startWatchTime":0,"totalSeriesNumber":0}
{"expired":0,"logType":"begin","playType":"LK","seconds":0,"seriesNumber":0,"startWatchTime":0,"totalSeriesNumber":0}

#### 附加信息
![image](https://user-images.githubusercontent.com/6488972/202623780-f520ff47-95eb-4cd8-b9b6-3954ae535f05.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/issues/928
和这个Issue类似，是WriteEnumUsingToString的实现问题。

https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请帮忙用2.0.20-SNAPSHOT版本帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.20
问题已修复，请用新版本
