### ISSUE TITLE
JDKUtils非法映射

### ISSUE THREAD

**Issue by gxyxd** [alibaba/fastjson2#94]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alibaba.fastjson2.util.JDKUtils (file:/***/com/alibaba/fastjson2/fastjson2/2.0.1/fastjson2-2.0.1.jar) to field java.lang.StringUTF16.HI_BYTE_SHIFT
WARNING: Please consider reporting this to the maintainers of com.alibaba.fastjson2.util.JDKUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

fastjson版本 2.0.1
jdk: dragonwell11

**Comment by wenshao** [comment]
JDK 11支持，但有警告，不影响运行，忽略吧。JDK 17如果没有add open，也开始可以正常运行的。

**Comment by trydofor** [comment]
compile: --add-exports=java.base/java.lang.invoke=ALL-UNNAMED
runtime: --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
