### ISSUE TITLE
[BUG] 对象内的BigDecimal 自定义序列化失效

### ISSUE THREAD

**Issue by WangChenPeng** [alibaba/fastjson2#940]
### 问题描述
*简要描述您碰到的问题。*

压测环境中使用fastjson2 会出现对账对不齐的情况 ( 暂无法提供复现数据,靠压测脚本跑的,变量只有反序列化更改为fastjson2 )
而使用fastjson则无此情况 , 因此怀疑是fastjson2对BigDecimal处理有问题
尝试注册自定义反序列化 发现不生效

测试代码如下

### 环境信息

 - 版本信息：[e.g.：Fastjson2 2.0.18]
 

### 重现步骤
*如何操作可以重现该问题：*

```
import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONReader;
import com.alibaba.fastjson2.reader.ObjectReader;

import java.lang.reflect.Type;
import java.math.BigDecimal;

public class Test2 {

    public static void main(String[] args) {
        String json = "{\"data\":\"1.111\"}";
        
        JSON.register(BigDecimal.class, Test2.InstantReader.INSTANCE);
        Test2.TestJsonObj testJsonObj = JSON.parseObject(json, Test2.TestJsonObj.class);
    }

    static class InstantReader implements ObjectReader<BigDecimal> {
        public static final Test2.InstantReader INSTANCE = new Test2.InstantReader();
        @Override
        public BigDecimal readObject(JSONReader jsonReader, Type fieldType, Object fieldName, long features) {
            if (jsonReader.nextIfNull()) {
                return null;
            }
            System.out.println("readObject fieldType:"+ fieldType+" fieldName:"+fieldName+" features:"+features+" data:"+jsonReader.readString());
           
            return null;
        }
    }

    static class TestJsonObj{

        BigDecimal data;

        public BigDecimal getData() {
            return data;
        }

        public void setData(BigDecimal data) {
            this.data = data;
        }

        @Override
        public String toString() {
            return "TestJsonObj{" +
                    "data=" + data +
                    '}';
        }
    }
    
}

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
打印log

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*
无log打印

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.19
能帮忙用2.0.19版本验证下么，2.0.19修复过这个问题

* 修复12个字段时JSONObject.toJavaObject方法会丢失字段的问题 https://github.com/alibaba/fastjson2/issues/900

**Comment by WangChenPeng** [comment]
> https://github.com/alibaba/fastjson2/releases/tag/2.0.19 能帮忙用2.0.19版本验证下么，2.0.19修复过这个问题
> 
> * 修复12个字段时JSONObject.toJavaObject方法会丢失字段的问题 [[BUG]非常罕见的序列化或反序列化时丢失字段的问题 #900](https://github.com/alibaba/fastjson2/issues/900)

尝试了 2.0.19 还没修复此问题

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
已经支持自定义BigDecimal类型反序列化，请用2.0.20-SNAPSHOT版本帮忙验证

**Comment by WangChenPeng** [comment]
> https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/ 已经支持自定义BigDecimal类型反序列化，请用2.0.20-SNAPSHOT版本帮忙验证

从git中 找不到此tag 或 分支 ， 从maven也拉不到包

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.20
问题已修复，请用新版本
