### ISSUE TITLE
Creating JSONObject()

### ISSUE THREAD

**Issue by osivinyuk** [alibaba/fastjson2#941]
Hello.
In fastjson v1 was functionality to create JSONObject linked(you are using LinkedHashMap)
In this version I dont have constructor like this: new JSONObject(true)
Did you change it or you have other way to create this object?
Thank you

**Comment by wenshao** [comment]
fastjson2 support user-define ObjectSupplier, such as:

```java
JSONReader.Context context = JSONFactory.createReadContext();
context.setObjectSupplier(HashMap::new);
assertEquals(HashMap.class, JSON.parse("{}", context).getClass());
```

```java
JSONReader.Context context = JSONFactory.createReadContext();
context.setObjectSupplier(ConcurrentHashMap::new);
assertEquals(ConcurrentHashMap.class, JSON.parse("{}", context).getClass());
```
