### ISSUE TITLE
JSON.parseObject does not work correctly

### ISSUE THREAD

**Issue by osivinyuk** [alibaba/fastjson2#942]
Hello 

https://github.com/osivinyuk/FastJson2

I update this project with new JSON and parser doesnt parse Map<String,String>
The param name is "network_interfaces", but a lot of other params does not parse too.

Here it doesnt understand JSONField annotation: 
@JSONField(name = "analytics")
List<RunningAnalyticsDTO> runningAnalytics;

Please check my project

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请用2.0.20-SNAPSHOT版本帮忙验证

**Comment by osivinyuk** [comment]
Yes. I use this 2.0.20-SNAPSHOT, but I updated json and it’s not working. You could try this example with this library, but you need to update Pom file for dependancy

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.20
问题已修复，请用新版本
