### ISSUE TITLE
double 数组写入越界

### ISSUE THREAD

**Issue by worendeni** [alibaba/fastjson2#951]
double 数组写入越界

https://github.com/alibaba/fastjson2/blob/a3de4182e929747dd29859f22776792a77ec00e4/core/src/main/java/com/alibaba/fastjson2/JSONWriterUTF16.java#L1391

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请帮忙用2.0.20-SNAPSHOT版本帮忙验证

**Comment by worendeni** [comment]
测试没问题
