### ISSUE TITLE
[BUG] DateUtils.toMillis19("2022-12-31 23:59:59", 0, ZoneId.of("Asia/Shanghai"))

### ISSUE THREAD

**Issue by m1ngyuan** [alibaba/fastjson2#952]
https://github.com/alibaba/fastjson2/blob/a3de4182e929747dd29859f22776792a77ec00e4/core/src/main/java/com/alibaba/fastjson2/util/DateUtils.java#L2288

DateUtils.toMillis19("2022-12-31 23:59:59", 0, ZoneId.of("Asia/Shanghai"))

throw DateTimeParseException("illegal input")

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请帮忙用2.0.20-SNAPSHOT版本帮忙验证
