### ISSUE TITLE
用jsonpath 设置数字key 

### ISSUE THREAD

**Issue by qq1053831109** [alibaba/fastjson2#956]
Map data = new LinkedHashMap<>();
JSONPath.set(data, "$.obj.5", "设置成功");
System.out.println(JSONObject.toJSONString(data));
会打印：
{"obj":[null,null,null,null,null,"设置成功"]}

我希望是打印 {"obj":{5:"设置成功"}} obj是对象 不是数组

我用的最新的2.0.19

以前的fastjson1 就是支持数字key的 或者说是字符串为数字的 如key 为"12345"

**Comment by wenshao** [comment]
```java
Map data = new LinkedHashMap<>();
JSONPath.set(data, "$.obj['5']", "设置成功");
assertEquals("{\"obj\":{\"5\":\"设置成功\"}}", JSONObject.toJSONString(data));
```
你可以这样用

**Comment by qq1053831109** [comment]
JSONPath.paths 遇到数字key返回的是$.obj.5 能改成 $.obj['5'] 吗 ？ 不然不能配套使用

**Comment by wenshao** [comment]
> JSONPath.paths 遇到数字key返回的是$.obj.5 能改成 $.obj['5'] 吗 ？ 不然不能配套使用

可以的，我也打算这样改

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.21-SNAPSHOT/
问题已经解决，请帮用快照版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.21
问题已修复，请用新版本
