### ISSUE TITLE
[BUG]接收科学计数法格式的double类型转换出错

### ISSUE THREAD

**Issue by TonyWang972** [alibaba/fastjson2#959]
### 问题描述
接收科学计数法格式的double类型转换出错，将版本变更为fastjson1就可以了

### 环境信息
 - OS信息：  [e.g.：win11]
 - JDK信息： [e.g.：java 1.8]
 - 版本信息：[e.g.：Fastjson2 2.0.19]

### 重现步骤
运行
```java
    public static void main(String[] args) {
        String json = "{\"V\": -2.0089457919266330204e-15}";

        JSONObject jsonObject = JSON.parseObject(json);
        System.out.println(jsonObject);
    }
```

### 期待的正确结果
{"V":-2.0089457919266330204E-15}

### 相关日志输出
![image](https://user-images.githubusercontent.com/55622087/203687858-27982d1b-c93d-4be2-89ff-64366ae84cb7.png)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.20-SNAPSHOT/
问题已修复，请帮忙用2.0.20-SNAPSHOT版本帮忙验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.20
问题已修复，请用新版本
