### ISSUE TITLE
序列化和反序列化能否增加对防御XSS攻击的支持？

### ISSUE THREAD

**Issue by XuJincai** [alibaba/fastjson2#964]
### 请描述您的需求或者改进建议
序列化和反序列化能否增加对防御XSS攻击的支持？

### 请描述你建议的实现方案
建议在JSONReader.Feature和JSONWriter.Feature增加防御XSS攻击的配置
转义方法可参考org.springframework.web.util.HtmlUtils类

### 描述您考虑过的替代方案
*对您考虑过的任何替代解决方案或功能的描述。*

#### 附加信息
![2022-11-25_105609](https://user-images.githubusercontent.com/16322049/203891827-236564bc-c9e1-4439-ba5a-91e50ca40544.png)

**Comment by wenshao** [comment]
已经补上类似FASTJSON 1.x SerializeFeature.BrowserSecure一样的功能，用法同样了类似：
```java
Model model = new Model();
model.name = "<>";
String str = JSON.toJSONString(model, JSONWriter.Feature.BrowserSecure);
assertEquals("{\"name\":\"\\u003c\\u003e\"}", str);

 public static class Model {
        public String name;
}
```

**Comment by XuJincai** [comment]
好像跟我的期望有出入
![image](https://user-images.githubusercontent.com/16322049/204948898-4b4b3a4b-f07a-4510-854c-aa37cbed389e.png)
我是想在上面配置里加上配置
![image](https://user-images.githubusercontent.com/16322049/204949046-995ad410-77bd-4adc-85c6-f535a8a20f52.png)
发送json请求后
![image](https://user-images.githubusercontent.com/16322049/204949180-8468a7fe-b0bd-47ba-9605-bef101b1d490.png)
这里接收到的数据是转义后的数据  &lt;script&gt;&lt;/script&gt

**Comment by wenshao** [comment]
通过\uXXXX转义也是安全的

**Comment by XuJincai** [comment]
![image](https://user-images.githubusercontent.com/16322049/205562805-dbb95819-56f4-4b7d-bd0c-effb722ecb10.png)
JSONReader.Feature中好像没有相关配置

**Comment by wenshao** [comment]
Reader不需要做额外配置吧

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.21
请用新版本

**Comment by XuJincai** [comment]
前端给后端传json数据，后端用对象接收，怎么接收转义后的数据？

**Comment by XuJincai** [comment]
> Reader不需要做额外配置吧

前端给后端传json数据，后端用对象接收，怎么接收转义后的数据？
![image](https://user-images.githubusercontent.com/16322049/206943183-db819136-273c-4153-bf48-0a2624488d88.png)

**Comment by WilliamHWM** [comment]
我前端post的json对象为 
{
  "password": "test123",
  "username": "<script>test</scipt>666"
}
为什么接收解析完是username 为 test666的，我怎么能接收到&lt;test&gt;666  这样的数据？
JSONReader.Feature应该设置什么

**Comment by WilliamHWM** [comment]
上面的<>是转义后的，& lt; & gt;这样的
