### ISSUE TITLE
[BUG] OutOfMemory？我使用的问题还是fastjson2的问题？🐔

### ISSUE THREAD

**Issue by MagicFollower** [alibaba/fastjson2#966]
### 问题描述
使用JSONObject#toJSONString序列化一个Map，Map含有一个大字符串，出现了OOM。

### 环境信息
 - OS信息：   Windows11 22623.891 
 - JDK信息：  JDK-11.0.16
 - 版本信息： Fastjson2 2.0.19
 

### 重现步骤
`
        final String filename = "一个60M的文件.pdf";
        ClassPathResource classPathResource = new ClassPathResource(filename);
        byte[] bytes = classPathResource.getInputStream().readAllBytes();

        HashMap<String, String> res = new HashMap<>();
        res.put("data", Base64Utils.encodeToString(bytes));
        res.put("filename", filename);
        String s = JSONObject.toJSONString(res);
`

### 期待的正确结果
预期情况，正常序列化。这仅仅是一个示例，切换gson库后不会出现这个问题。
运行时，可用盾内存大小：
    JVM最小可用内存-Xms：1518MB
    JVM最大可用内存-Xmx：24560MB

### 相关日志输出
java.lang.OutOfMemoryError: null
	at com.alibaba.fastjson2.JSONWriterUTF16.writeString(JSONWriterUTF16.java:220) ~[fastjson2-2.0.19.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:473) ~[fastjson2-2.0.19.jar:na]
	at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:2245) ~[fastjson2-2.0.19.jar:na]
	at com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1099) ~[fastjson2-2.0.19.jar:na]

#### 附加信息
![image](https://user-images.githubusercontent.com/89330933/203954774-fabada38-ffb6-413b-a6f1-aa218a0fc4c5.png)
![image](https://user-images.githubusercontent.com/89330933/203954808-d4d78209-33b4-407b-918c-1a37f4f5823b.png)

**Comment by wenshao** [comment]
这个是一个保护措施，是为了防止序列化有循环引用对象消耗过大资源的保护措施。可以使用JSONWriter.Feature.LargeObject来避免这个问题：
```java
String s = JSONObject.toJSONString(res, JSONWriter.Feature.LargeObject);
```

**Comment by MagicFollower** [comment]
好的，谢谢你😊😊😊 合理作息，保持健康！

**Comment by 15102552479** [comment]
请问这个问题,如何设置全局来解决

**Comment by 15102552479** [comment]
请问如何调整64MB,这个全局的阈值?

**Comment by wenshao** [comment]
JSON.config(JSONWriter.Feature.LargeObject)

**Comment by wenshao** [comment]
JSON.config(JSONWriter.Feature.LargeObject)

**Comment by 15102552479** [comment]
请问Springboot2.X项目呢？

**Comment by 15102552479** [comment]
翻了下源码，晓得了，谢谢哈
