### ISSUE TITLE
 JSON.parseArray丢失Long的精度

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/fastjson2#97]
下面是实体类

@Data
@Slf4j
public class LiveWaterVO implements Serializable {

  private String name;

  private Long level1;
  
  private Long level2;
 
  private Long level3;
 
  private Long wl;

  @JsonIgnoreProperties(ignoreUnknown = true)
  private Long wlSixHoursAgo;

  @JsonIgnoreProperties(ignoreUnknown = true)
  private Long wlThreeHoursAgo;

  @JsonIgnoreProperties(ignoreUnknown = true)
  private Long wlOneHourAgo;
}
原来的JSON：

[{"wl":0.01,"name":"西桥","level1":"9","level3":"0.7","level2":"1.4"}]
进行下面的转换后：

List<LiveWaterVO> liveWaterVOS = JSON.parseArray(jsonArrayStr,LiveWaterVO.class);
 System.out.println(liveWaterVOS);
结果显示如下：
[LiveWaterVO(name=西桥, level1=9, level2=1, level3=0, wl=0, wlSixHoursAgo=null, wlThreeHoursAgo=null, wlOneHourAgo=null)]

ref https://github.com/alibaba/fastjson/issues/4038

**Comment by wsxe9988** [comment]
原始json串中 wl值为0.01 parseArray 输出变成0；level3值为0.7 parseArray 输出变成0；level2值为1.4 parseArray 输出变成1,,精度缺失了

**Comment by wenshao** [comment]
对象类型就是Long，按这个输入，就应该是截断吧

**Comment by wsxe9988** [comment]
确实是,Long是长整型，会截断，Double就不会丢失精度了
