### ISSUE TITLE
fastjson2序列化的结果和fastjson1不一致。

### ISSUE THREAD

**Issue by 599166320** [alibaba/fastjson2#970]
### 问题描述
*fastjson2序列化的结果和fastjson1不一致。*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：CentOS 8.4.2105 4Core 3.10GHz 16 GB]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.19]
 

### 重现步骤

```java

@Setter
@Getter
public class MyBean{
	private String qStr;
}



JSONObject obj = new JSONObject();
obj.put("qStr","abc");

MyBean mybean = obj.toJavaObject(MyBean.class);
System.out.println(JSON.toJSONString(mybean));



fastjson2最新版本
{"QStr":"abc"}

fastjon1
{qStr":"abc"}

```

### 期待的正确结果
*fastjson1和fastjson2输出一致。*

**Comment by kraity** [comment]
通过注解@Getter, 会得到setQStr(String)方法. 不兼容原因你可以查看PR [Camelcase#issuecomment-1181634178](https://github.com/alibaba/fastjson2/pull/551#issuecomment-1181634178)

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson/2.0.22-SNAPSHOT/
问题已经修复，使用兼容API保持原来的命名风格输出，请帮忙用2.0.22-SNAPSHOT版本验证，2.0.22版本预计在元旦期间发布

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.22
问题已修复，请用新版本
