### ISSUE TITLE
[BUG]toJSONString 枚举类型报错

### ISSUE THREAD

**Issue by ganweiming** [alibaba/fastjson2#972]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - 版本信息：[e.g.：Fastjson2 2.0.20]
 

### 重现步骤
枚举输出报错
![1](https://user-images.githubusercontent.com/18005096/204218857-82ea15d0-c623-45a6-98d0-7e0208d61879.png)

![2](https://user-images.githubusercontent.com/18005096/204218877-f724a9ab-be51-4757-9b44-b8542279ee33.png)

![3](https://user-images.githubusercontent.com/18005096/204218887-b9a1d631-4b75-4c29-822c-25aea0f95caa.png)

**Comment by wenshao** [comment]
请帮忙补提交文本的代码，降低重现问题的工作量

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.21-SNAPSHOT/
问题已经解决，请帮用快照版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.21
问题已修复，请用新版本
