### ISSUE TITLE
[BUG]2.0.20.graal 版本在公共仓库不存在   

### ISSUE THREAD

**Issue by wuxuanqicn** [alibaba/fastjson2#979]
### 问题描述
2.0.20.graal 版本在公共仓库不存在 ，但在文档https://github.com/alibaba/fastjson2/releases/tag/2.0.20 中存在
https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2/
![image](https://user-images.githubusercontent.com/89442834/204488205-c3585f06-fa95-4387-bac5-94d40fdd7510.png)

### 重现步骤
依赖最新版本
```java
<dependency>
	<groupId>com.alibaba.fastjson2</groupId>
	<artifactId>fastjson2</artifactId>
	<version>2.0.20.graal</version>
</dependency>
```

### 期待的正确结果
可以正常引用

### 相关日志输出
Could not find artifact com.alibaba.fastjson2:fastjson2:pom:2.0.20.graal

**Comment by wenshao** [comment]
发布后一直不出现在maven中央仓库中，已经发布多次了，但就是不出现，比较奇怪

**Comment by wenshao** [comment]
https://repo1.maven.org/maven2/com/alibaba/fastjson2/fastjson2/2.0.20.graal/
已经出现在maven中央仓库了
