### ISSUE TITLE
JsonArray [*]通配符匹配不符合预期

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/fastjson2#98]
JSONPath.extract("[3,{"tag": ["tag1", "tag2"]},["tag1","tag2"],6]", "$[].tag[]")

上面预期获得结果["tag1": "tag2"]，实际会报错

![image](https://user-images.githubusercontent.com/5828057/165550860-56b550f8-4da0-4160-bf8f-b837b1378bbe.png)

ref https://github.com/alibaba/fastjson/issues/3924

**Comment by yinwoods** [comment]
> JSONPath.extract("[3,{"tag": ["tag1", "tag2"]},["tag1","tag2"],6]", "$[].tag[]")
> 
> 上面预期获得结果["tag1": "tag2"]，实际会报错
> 
> ![image](https://user-images.githubusercontent.com/5828057/165550860-56b550f8-4da0-4160-bf8f-b837b1378bbe.png)
> 
> ref [alibaba/fastjson#3924](https://github.com/alibaba/fastjson/issues/3924)

是不是表达式写错了，我试了下 $[1].tag[*] 是好的
