### ISSUE TITLE
fastjson2不支持SerializerFeature

### ISSUE THREAD

**Issue by 1506085843** [alibaba/fastjson2#981]
我使用的版本是Fastjson2.0.20  ，jdk是1.8

下面是我的测试代码：

```java      
        Map<String,String> map=new HashMap<>();
        map.put("测试1",null);
        map.put("测试2","hello");
        String str = JSON.toJSONString(map,SerializerFeature.WriteMapNullValue);
        System.out.println(str) ;
```

编译器提示未找到SerializerFeature，fastjson2是不支持SerializerFeature吗?
![image](https://user-images.githubusercontent.com/39946319/204724158-469c588e-ae3b-4ae4-a2ee-f4847b10b5a6.png)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/wiki/fastjson_1_upgrade_cn

com.alibaba.fastjson.serializer.SerializerFeature   -> com.alibaba.fastjson2.JSONReader.Feature
