### ISSUE TITLE
[BUG]IDEA提示出错，2.0.19是正常的

### ISSUE THREAD

**Issue by Wangijun** [alibaba/fastjson2#984]
### 问题描述
*IDEA提示出错，2.0.19是正常的*

### 环境信息

 - OS信息：  [e.g.：Win11]
 - JDK信息： [e.g.：JDK17]
 - 版本信息：[e.g.：Fastjson2 2.0.20]
 

### 重现步骤

1. 使用 `JSON.parseArray` 方法，出现类型推断错误

```java
for (String s : JSON.parseArray("",String.class)) {
            System.out.println(s);
 }
```

### 期待的正确结果
*能正确推断类型*

#### 附加信息
![image](https://user-images.githubusercontent.com/40266995/204950756-47af60cf-b77a-45b5-8ecc-e724fa86cc5e.png)

**Comment by Wangijun** [comment]
这涉及到API的变动，只要这样写的，升级2.0.20后编译是过不去的。是属于不兼容的改动

**Comment by wenshao** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/fastjson2/fastjson2/2.0.21-SNAPSHOT/
问题已经解决，请帮用快照版本验证

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.21
请用新版本
