### ISSUE TITLE
非法的反射访问[BUG]

### ISSUE THREAD

**Issue by fy287216637** [alibaba/fastjson2#990]
### 问题描述
控制台会有警告：

JDK11

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alibaba.fastjson2.util.JDKUtils (file:/D:/All_Jar/com/alibaba/fastjson2/fastjson2/2.0.19/fastjson2-2.0.19.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of com.alibaba.fastjson2.util.JDKUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### 环境信息
*请填写以下信息：*

 - JDK信息： [e.g.：Openjdk 11.0.14.1]
 - 版本信息：[e.g.：Fastjson2 2.0.20]

**Comment by wenshao** [comment]
这个警告不会是已知的，不影响运行，可以忽略

**Comment by fy287216637** [comment]
哈哈，担心公司安全不给通过
多问一句引起这个警告的原因是什么呢～感谢解答

**Comment by wenshao** [comment]
JDK 11 ~ JDK 15支持通过反射或者String的coder和value字段，这个能够减少拷贝提升性能。

**Comment by fy287216637** [comment]
好的~ 那我先忽略
感谢wenshao解答

**Comment by fy287216637** [comment]
请问最新版本是处理这个警告了吗？我看20版本没有了

**Comment by wenshao** [comment]
是的，最新版本已经没有这个警告了

**Comment by fy287216637** [comment]
好的~ 感谢wenshao
